import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, tip, word } from "../builders";
import type { Course } from "../types";

const chaoHoi = lesson({
  slug: "chao-hoi-va-gioi-thieu",
  title: "Chào hỏi và giới thiệu",
  minutes: 18,
  free: true,
  lecture: {
    title: "Động từ to be: am, is, are",
    blocks: [
      p("Trong tiếng Anh, câu giới thiệu bản thân gần như luôn dùng động từ **to be**. Nó giống chữ “là” trong tiếng Việt, nhưng đổi hình thức theo chủ ngữ: **am**, **is** hoặc **are**."),
      table(
        ["Chủ ngữ", "to be", "Viết tắt", "Ví dụ"],
        ["I (tôi)", "am", "I'm", "I'm Lan."],
        ["you (bạn)", "are", "you're", "You're a student."],
        ["he / she / it", "is", "he's / she's / it's", "She's my teacher."],
        ["we / they", "are", "we're / they're", "We're from Vietnam."],
      ),
      p("Muốn hỏi, đảo **to be** lên trước chủ ngữ. Muốn phủ định, thêm **not** sau **to be**."),
      ex("Are you a teacher?", "Bạn có phải là giáo viên không?"),
      ex("No, I'm not. I'm a nurse.", "Không, tôi không phải. Tôi là y tá."),
      ex("Nice to meet you, Minh.", "Rất vui được gặp bạn, Minh.", "Câu quen thuộc khi gặp ai đó lần đầu."),
      tip("Khi nói, người bản xứ gần như luôn dùng dạng viết tắt: I'm, you're, she's. Dùng dạng đầy đủ nghe khá cứng."),
      mistake("I from Vietnam.", "I'm from Vietnam.", "Tiếng Việt nói “Tôi từ Việt Nam”, nhưng tiếng Anh không được bỏ động từ to be."),
      mistake("She are my friend.", "She is my friend.", "He, she, it luôn đi với is."),
    ],
  },
  words: [
    word("hello", "/həˈləʊ/", "xin chào", "Hello, I'm Lan.", "hel|lo", 1),
    word("name", "/neɪm/", "tên", "My name is Minh.", "name", 0),
    word("student", "/ˈstjuː.dənt/", "sinh viên, học sinh", "I'm a student.", "stu|dent", 0, "Nhớ bật âm /t/ ở cuối, đừng nuốt mất."),
    word("teacher", "/ˈtiː.tʃər/", "giáo viên", "She's my teacher.", "tea|cher", 0),
    word("country", "/ˈkʌn.tri/", "đất nước", "What country are you from?", "coun|try", 0),
    word("nice", "/naɪs/", "vui, dễ chịu", "Nice to meet you.", "nice", 0, "Kết thúc bằng âm /s/, không đọc thành “nai”."),
    word("friend", "/frend/", "bạn bè", "This is my friend, Hoa.", "friend", 0),
  ],
  exercises: [
    mc("a1-1-1", "I ___ from Vietnam.", ["is", "am", "are"], 1, "Với I ta luôn dùng am."),
    mc("a1-1-2", "They ___ students.", ["are", "is", "am"], 0, "They đi với are."),
    fill("a1-1-3", "She ___ my teacher.", ["is", "'s"], "He, she, it đi với is."),
    fill("a1-1-4", "Nice to ___ you.", ["meet", "see"], "Lần đầu gặp: Nice to meet you. Gặp lại người quen: Nice to see you."),
    reorder("a1-1-5", "Where are you from?"),
    reorder("a1-1-6", "What is your name?", "Câu hỏi với từ để hỏi: What + is + your name?"),
    listen("a1-1-7", "Are you a student?", ["Bạn có phải là sinh viên không?", "Bạn là giáo viên à?", "Bạn đến từ đâu?"], 0),
    listen("a1-1-8", "He's from Japan.", ["Anh ấy đến từ Nhật Bản.", "Cô ấy đến từ Nhật Bản.", "Anh ấy đang ở Nhật Bản."], 0),
  ],
  speaking: [
    say("Hello, my name is Lan.", "Xin chào, tên tôi là Lan."),
    say("I'm a student from Vietnam.", "Tôi là sinh viên đến từ Việt Nam."),
    say("Nice to meet you.", "Rất vui được gặp bạn."),
  ],
});

const giaDinh = lesson({
  slug: "gia-dinh-va-do-vat",
  title: "Gia đình và đồ vật",
  minutes: 20,
  lecture: {
    title: "a/an, số nhiều, this/that và my/your",
    blocks: [
      p("Trước danh từ số ít đếm được, tiếng Anh luôn cần **a** hoặc **an** (một). Dùng **a** trước **âm** phụ âm và **an** trước **âm** nguyên âm. Hãy nghe âm đầu, đừng nhìn chữ cái."),
      ex("I have a bag and an umbrella.", "Tôi có một cái túi và một cái ô."),
      tip("Nhìn âm chứ không nhìn chữ: **a university** (âm đầu /j/ là phụ âm) nhưng **an hour** (chữ h câm, âm đầu là nguyên âm /aʊ/)."),
      p("Khi có từ hai vật trở lên, danh từ phải đổi sang **số nhiều**. Phần lớn chỉ cần thêm **-s**, nhưng có vài quy tắc và vài từ bất quy tắc cần học thuộc."),
      table(
        ["Quy tắc", "Số ít", "Số nhiều"],
        ["Thường: thêm -s", "book, phone", "books, phones"],
        ["Tận cùng -s, -x, -ch, -sh: thêm -es", "box, watch", "boxes, watches"],
        ["Phụ âm + y: đổi y thành -ies", "baby, family", "babies, families"],
        ["Bất quy tắc", "child, man, woman, person", "children, men, women, people"],
      ),
      mistake("I have two book.", "I have two books.", "Tiếng Việt nói “hai quyển sách” mà danh từ không đổi, nhưng tiếng Anh bắt buộc thêm -s khi có từ hai vật trở lên."),
      table(
        ["", "Ở gần", "Ở xa"],
        ["Số ít", "this (cái này)", "that (cái kia, cái đó)"],
        ["Số nhiều", "these (những cái này)", "those (những cái kia)"],
      ),
      table(
        ["Chủ ngữ", "Tính từ sở hữu", "Ví dụ"],
        ["I", "my", "This is my phone."],
        ["you", "your", "Is that your bag?"],
        ["he", "his", "His name is Nam."],
        ["she", "her", "Her name is Hoa."],
        ["we", "our", "These are our children."],
        ["they", "their", "Those are their books."],
      ),
      ex("This is my brother. His name is Nam.", "Đây là anh trai tôi. Tên anh ấy là Nam.", "Tính từ sở hữu luôn đứng trước danh từ: my brother, không nói brother my."),
      mistake("She is my sister. His name is Hoa.", "She is my sister. Her name is Hoa.", "Tiếng Việt nói chung “tên của bạn ấy”, nên người Việt hay lẫn his và her. His dùng cho nam, her dùng cho nữ."),
    ],
  },
  words: [
    word("family", "/ˈfæm.əl.i/", "gia đình", "I have a big family.", "fam|i|ly", 0, "Người bản xứ thường nói nhanh thành hai âm tiết: /ˈfæm.li/."),
    word("mother", "/ˈmʌð.ər/", "mẹ", "My mother is a teacher.", "moth|er", 0, "Âm /ð/ đặt đầu lưỡi giữa hai hàm răng, đừng đọc thành /d/ hay /z/."),
    word("father", "/ˈfɑː.ðər/", "bố", "His father is a doctor.", "fa|ther", 0),
    word("brother", "/ˈbrʌð.ər/", "anh trai, em trai", "These are my two brothers.", "broth|er", 0),
    word("sister", "/ˈsɪs.tər/", "chị gái, em gái", "Her sister is a student.", "sis|ter", 0),
    word("bag", "/bæɡ/", "cái túi, cặp", "Is this your bag?", "bag", 0, "Nhớ bật âm /ɡ/ ở cuối để không nghe nhầm thành back."),
    word("umbrella", "/ʌmˈbrel.ə/", "cái ô, cái dù", "I have an umbrella in my bag.", "um|brel|la", 1),
    word("phone", "/fəʊn/", "điện thoại", "That is his phone.", "phone", 0),
  ],
  exercises: [
    mc("a1-2-1", "This is ___ umbrella.", ["a", "an", "two"], 1, "Umbrella bắt đầu bằng âm nguyên âm /ʌ/ nên dùng an."),
    mc("a1-2-2", "I have two ___.", ["box", "boxs", "boxes"], 2, "Danh từ tận cùng bằng -x thêm -es."),
    fill("a1-2-3", "She is my sister. ___ name is Hoa.", ["Her", "her"], "Chủ ngữ là she (nữ) nên dùng her."),
    fill("a1-2-4", "They have three ___. (child)", ["children"], "Child là danh từ bất quy tắc: số nhiều là children."),
    reorder("a1-2-5", "My parents have three children.", "Tính từ sở hữu my đứng trước danh từ; child có số nhiều bất quy tắc là children."),
    reorder("a1-2-6", "Where are my books?", "Books là số nhiều nên dùng are; câu hỏi đảo are lên trước chủ ngữ my books."),
    listen("a1-2-7", "That is his phone.", ["Đây là điện thoại của anh ấy.", "Đó là điện thoại của anh ấy.", "Đó là điện thoại của cô ấy."], 1, "That là cái ở xa (đó, kia); his là của anh ấy."),
    listen("a1-2-8", "These are our children.", ["Đây là con của họ.", "Kia là các con của chúng tôi.", "Đây là các con của chúng tôi."], 2, "These là những cái ở gần (đây); our là của chúng tôi."),
  ],
  speaking: [
    say("This is my mother.", "Đây là mẹ tôi."),
    say("These are my two brothers.", "Đây là hai anh trai của tôi."),
    say("She is my sister. Her name is Lan.", "Cô ấy là chị gái tôi. Tên chị ấy là Lan."),
  ],
});

const soTuoi = lesson({
  slug: "so-tuoi-va-so-dien-thoai",
  title: "Số, tuổi và số điện thoại",
  minutes: 18,
  lecture: {
    title: "Số đếm từ 1 đến 100",
    blocks: [
      p("Các số từ 1 đến 12 cần học thuộc. Từ 13 đến 19 thêm đuôi **-teen**, còn các số tròn chục từ 20 đến 90 thêm đuôi **-ty**. Các số như 21, 35, 99 ghép chục với đơn vị bằng dấu gạch nối: twenty-one, thirty-five, ninety-nine."),
      table(
        ["Số", "Cách viết", "Trọng âm"],
        ["13", "thirteen", "thir-TEEN (nhấn âm sau)"],
        ["30", "thirty", "THIR-ty (nhấn âm trước)"],
        ["14", "fourteen", "four-TEEN (nhấn âm sau)"],
        ["40", "forty", "FOR-ty (nhấn âm trước)"],
        ["15", "fifteen", "fif-TEEN (nhấn âm sau)"],
        ["50", "fifty", "FIF-ty (nhấn âm trước)"],
      ),
      tip("Cặp 13 và 30 rất dễ nghe nhầm. Với **-teen**, nhấn mạnh và kéo dài âm cuối /tiːn/, nhớ đọc rõ âm /n/. Với **-ty**, nhấn âm đầu và đọc âm cuối thật ngắn."),
      p("Để hỏi tuổi, dùng **How old are you?** Trả lời bằng động từ to be cộng số tuổi, có thể thêm years old hoặc không."),
      ex("How old are you? I'm twenty-five.", "Bạn bao nhiêu tuổi? Tôi hai mươi lăm tuổi."),
      ex("My son is eight years old.", "Con trai tôi tám tuổi.", "Đã nói years thì phải có old: không nói “He is eight years.”"),
      mistake("I have 25 years old.", "I'm 25 years old.", "Tiếng Việt nói “tôi có 25 tuổi”, nhưng tiếng Anh dùng to be (am, is, are), không dùng have."),
      mistake("How many years old are you?", "How old are you?", "Đừng dịch từng chữ “bao nhiêu tuổi”. Hỏi tuổi chỉ cần How old."),
      p("Số điện thoại được đọc **từng chữ số một**, ngắt nghỉ theo nhóm. Số 0 thường đọc là **oh** (kiểu Anh) hoặc zero. Hai chữ số giống nhau đứng liền nhau có thể đọc là **double**: 55 là double five."),
      ex("What's your phone number? It's oh nine oh four, double five six, seven eight one.", "Số điện thoại của bạn là gì? Là 0904 556 781."),
    ],
  },
  words: [
    word("number", "/ˈnʌm.bər/", "số, con số", "What's your phone number?", "num|ber", 0),
    word("twelve", "/twelv/", "mười hai", "My daughter is twelve.", "twelve", 0, "Kết thúc bằng /lv/, đừng đọc thành “tu-eo”."),
    word("thirteen", "/θɜːˈtiːn/", "mười ba", "He is thirteen years old.", "thir|teen", 1, "Nhấn âm sau để phân biệt với thirty."),
    word("thirty", "/ˈθɜː.ti/", "ba mươi", "I'm thirty years old.", "thir|ty", 0, "Nhấn âm đầu, âm cuối đọc ngắn."),
    word("fifteen", "/fɪfˈtiːn/", "mười lăm", "There are fifteen students in my class.", "fif|teen", 1),
    word("hundred", "/ˈhʌn.drəd/", "trăm", "One hundred people work here.", "hun|dred", 0, "Nói one hundred hoặc a hundred, không thêm -s: two hundred."),
    word("old", "/əʊld/", "già, cũ; (bao nhiêu) tuổi", "How old is your mother?", "old", 0),
    word("age", "/eɪdʒ/", "tuổi, độ tuổi", "Lan and I are the same age.", "age", 0, "Khi hỏi tuổi, người bản xứ thường nói How old are you? hơn là What's your age?"),
  ],
  exercises: [
    listen("a1-3-1", "fifteen", ["50", "15", "5"], 1, "Trọng âm rơi vào âm sau (fif-TEEN) nên đây là 15."),
    listen("a1-3-2", "She's forty years old.", ["Cô ấy 14 tuổi.", "Cô ấy 4 tuổi.", "Cô ấy 40 tuổi."], 2, "Forty nhấn âm đầu (FOR-ty) nên là 40."),
    listen("a1-3-3", "My number is oh nine one two, double three four, five six seven.", ["0912 334 567", "0912 344 567", "0921 334 567"], 0, "Double three nghĩa là hai số 3 liền nhau."),
    mc("a1-3-4", "___ old are you?", ["What", "How", "How many"], 1, "Hỏi tuổi dùng How old."),
    mc("a1-3-5", "Trong số điện thoại, “77” thường được đọc là:", ["double seven", "seventy-seven", "two seven"], 0, "Hai chữ số giống nhau liền nhau đọc là double."),
    fill("a1-3-6", "I ___ twenty-two years old.", ["am", "'m"], "Nói tuổi dùng to be; với I là am."),
    fill("a1-3-7", "What's your phone ___?", ["number"]),
    reorder("a1-3-8", "How old is your brother?", "Hỏi tuổi: How old + to be + chủ ngữ?"),
  ],
  speaking: [
    say("I'm twenty-five years old.", "Tôi hai mươi lăm tuổi."),
    say("My sister is thirteen, not thirty.", "Em gái tôi mười ba tuổi, không phải ba mươi."),
    say("My phone number is oh nine one two, double three four, five six seven.", "Số điện thoại của tôi là 0912 334 567."),
  ],
});

const motNgay = lesson({
  slug: "mot-ngay-cua-toi",
  title: "Một ngày của tôi",
  minutes: 22,
  lecture: {
    title: "Thì hiện tại đơn và trạng từ tần suất",
    blocks: [
      p("Thì **hiện tại đơn** dùng để nói về thói quen và những việc lặp lại hằng ngày. Với I, you, we, they, động từ giữ nguyên. Với **he, she, it**, động từ phải thêm **-s** hoặc **-es**."),
      table(
        ["Chủ ngữ", "Khẳng định", "Phủ định", "Câu hỏi"],
        ["I / you / we / they", "I work.", "I don't work.", "Do you work?"],
        ["he / she / it", "She works.", "She doesn't work.", "Does she work?"],
      ),
      table(
        ["Quy tắc thêm -s", "Ví dụ"],
        ["Thường: thêm -s", "work → works, get → gets"],
        ["Tận cùng -o, -s, -ch, -sh, -x: thêm -es", "go → goes, watch → watches"],
        ["Phụ âm + y: đổi y thành -ies", "study → studies"],
        ["Bất quy tắc", "have → has"],
      ),
      mistake("She work in a bank.", "She works in a bank.", "Động từ tiếng Việt không bao giờ đổi, nên người Việt rất hay quên -s sau he, she, it."),
      mistake("She doesn't works.", "She doesn't work.", "Khi đã có does hoặc doesn't, động từ chính quay về nguyên mẫu, không thêm -s nữa."),
      p("**Trạng từ tần suất** cho biết bạn làm việc gì thường xuyên đến mức nào: **always** (luôn luôn), **usually** (thường thường), **often** (hay), **sometimes** (thỉnh thoảng), **never** (không bao giờ). Chúng đứng **trước động từ thường** nhưng **sau to be**."),
      ex("I usually get up at six o'clock.", "Tôi thường dậy lúc sáu giờ."),
      ex("He is never late.", "Anh ấy không bao giờ đến muộn.", "Với to be, trạng từ đứng sau is, am, are."),
      p("Để hỏi giờ, dùng **What time is it?** Để nói làm việc gì lúc mấy giờ, dùng **at** trước giờ. Giờ chẵn thêm o'clock, giờ rưỡi là half past."),
      ex("What time do you have lunch? At half past twelve.", "Bạn ăn trưa lúc mấy giờ? Lúc mười hai giờ rưỡi."),
      tip("Cách nói giờ dễ nhất là đọc giờ rồi đọc phút: 7:15 là **seven fifteen**, 9:40 là **nine forty**."),
    ],
  },
  words: [
    word("morning", "/ˈmɔː.nɪŋ/", "buổi sáng", "I drink coffee in the morning.", "mor|ning", 0),
    word("breakfast", "/ˈbrek.fəst/", "bữa sáng", "I have breakfast at seven.", "break|fast", 0, "Phần break ở đây đọc là /brek/, không đọc /breɪk/ như từ break (làm vỡ)."),
    word("lunch", "/lʌntʃ/", "bữa trưa", "We have lunch at twelve.", "lunch", 0),
    word("work", "/wɜːk/", "làm việc; công việc", "She works in a hospital.", "work", 0, "Đừng nhầm với walk /wɔːk/ (đi bộ)."),
    word("always", "/ˈɔːl.weɪz/", "luôn luôn", "He always gets up early.", "al|ways", 0),
    word("usually", "/ˈjuː.ʒu.ə.li/", "thường thường", "I usually go to work by bus.", "u|su|al|ly", 0),
    word("sometimes", "/ˈsʌm.taɪmz/", "thỉnh thoảng", "We sometimes watch TV at night.", "some|times", 0),
    word("o'clock", "/əˈklɒk/", "giờ (đúng)", "It's nine o'clock.", "o'|clock", 1, "Chỉ dùng cho giờ chẵn: eight o'clock, không nói eight thirty o'clock."),
  ],
  exercises: [
    mc("a1-4-1", "My father ___ coffee every morning.", ["drink", "drinks", "drinking"], 1, "My father là he nên động từ thêm -s."),
    mc("a1-4-2", "___ your sister work in Hanoi?", ["Do", "Is", "Does"], 2, "Your sister là she nên câu hỏi dùng Does."),
    mc("a1-4-3", "Chọn câu đúng:", ["I am always late.", "I always am late.", "Always I am late."], 0, "Với to be, trạng từ tần suất đứng sau am, is, are."),
    fill("a1-4-4", "She ___ like tea. (không thích)", ["doesn't", "does not"], "Phủ định với she dùng doesn't, động từ like giữ nguyên."),
    fill("a1-4-5", "He ___ to work at eight o'clock. (go)", ["goes"], "Go tận cùng bằng -o nên thêm -es."),
    reorder("a1-4-6", "My father never drinks coffee.", "Never đứng trước động từ thường drinks; my father là he nên drinks có -s."),
    listen("a1-4-7", "She never watches TV in the morning.", ["Cô ấy thường xem ti vi vào buổi sáng.", "Cô ấy không bao giờ xem ti vi vào buổi sáng.", "Cô ấy thỉnh thoảng xem ti vi vào buổi tối."], 1, "Never là không bao giờ."),
    listen("a1-4-8", "It's half past nine.", ["Bây giờ là chín giờ.", "Bây giờ là chín giờ mười lăm.", "Bây giờ là chín giờ rưỡi."], 2, "Half past nine là chín giờ ba mươi."),
  ],
  speaking: [
    say("I usually get up at six o'clock.", "Tôi thường dậy lúc sáu giờ."),
    say("My mother works in a hospital.", "Mẹ tôi làm việc ở bệnh viện."),
    say("Do you have breakfast every day?", "Bạn có ăn sáng mỗi ngày không?"),
  ],
});

const doAn = lesson({
  slug: "do-an-va-goi-mon",
  title: "Đồ ăn và gọi món",
  minutes: 20,
  lecture: {
    title: "Danh từ đếm được, không đếm được và cách gọi món",
    blocks: [
      p("Danh từ **đếm được** là những thứ đếm từng cái: an apple, two eggs. Danh từ **không đếm được** là những thứ không đếm từng cái như nước, gạo, sữa, bánh mì. Danh từ không đếm được **không đi với a/an** và **không thêm -s**."),
      table(
        ["Đếm được", "Không đếm được"],
        ["an apple, two apples", "water, milk"],
        ["an egg, three eggs", "rice, bread"],
        ["a banana, four bananas", "tea, sugar"],
      ),
      mistake("I eat two rices.", "I eat two bowls of rice.", "Tiếng Việt nói “hai bát cơm” nên người Việt hay thêm -s vào rice. Rice không đếm được, ta đếm bằng cái bát."),
      p("Muốn đếm thứ không đếm được, dùng từ chỉ đồ đựng: **a glass of** water (một cốc nước), **a cup of** tea (một tách trà), **a bowl of** rice (một bát cơm), **a bottle of** water (một chai nước)."),
      ex("A bowl of pho, please.", "Cho tôi một bát phở."),
      p("Dùng **some** trong câu khẳng định và khi mời, xin. Dùng **any** trong câu phủ định và câu hỏi. Cả hai đi được với danh từ số nhiều và danh từ không đếm được."),
      table(
        ["Loại câu", "Dùng", "Ví dụ"],
        ["Khẳng định", "some", "I have some eggs."],
        ["Phủ định", "any", "We don't have any milk."],
        ["Câu hỏi", "any", "Do you have any bread?"],
        ["Lời mời, xin", "some", "Would you like some tea?"],
      ),
      p("Khi gọi món, dùng **Can I have...?** hoặc **I'd like...** Muốn hỏi giá, nói **How much is it?** (một món) hoặc **How much are they?** (nhiều món)."),
      ex("Can I have a cup of coffee, please?", "Cho tôi một cốc cà phê nhé?"),
      ex("How much is it? It's thirty thousand dong.", "Bao nhiêu tiền vậy? Ba mươi nghìn đồng.", "Khi nói giá tiền, thousand không thêm -s: thirty thousand."),
      tip("Thêm **please** vào cuối câu để lịch sự hơn. Câu “Give me a coffee” nghe khá cộc lốc với người bản xứ. Lưu ý: khi gọi đồ uống ở quán, người ta vẫn nói **a coffee**, **two teas** với nghĩa một cốc, hai tách."),
      mistake("I'd like a bread.", "I'd like some bread.", "Bread không đếm được nên không dùng a. Muốn nói một ổ, dùng a loaf of bread hoặc a sandwich."),
    ],
  },
  words: [
    word("water", "/ˈwɔː.tər/", "nước", "Can I have a glass of water?", "wa|ter", 0),
    word("rice", "/raɪs/", "cơm, gạo", "I eat rice every day.", "rice", 0, "Nhớ đọc âm /s/ ở cuối, nếu không sẽ nghe thành “rai”."),
    word("bread", "/bred/", "bánh mì", "We have some bread for breakfast.", "bread", 0),
    word("egg", "/eɡ/", "quả trứng", "I'd like two eggs, please.", "egg", 0),
    word("chicken", "/ˈtʃɪk.ɪn/", "thịt gà, con gà", "Chicken rice, please.", "chick|en", 0),
    word("coffee", "/ˈkɒf.i/", "cà phê", "A cup of coffee, please.", "cof|fee", 0, "Nhấn âm đầu: COF-fee, khác với “cà phê” nhấn âm sau."),
    word("menu", "/ˈmen.juː/", "thực đơn", "Can I see the menu, please?", "men|u", 0),
    word("bottle", "/ˈbɒt.əl/", "cái chai", "A bottle of water is ten thousand dong.", "bot|tle", 0),
  ],
  exercises: [
    mc("a1-5-1", "I'd like ___ water, please.", ["a", "an", "some"], 2, "Water không đếm được nên không dùng a/an; dùng some."),
    mc("a1-5-2", "Do you have ___ eggs?", ["any", "a", "an"], 0, "Câu hỏi với danh từ số nhiều dùng any."),
    mc("a1-5-3", "Chọn cách gọi món lịch sự nhất:", ["Give me a coffee.", "Can I have a coffee, please?", "I want coffee now."], 1, "Can I have... please? là cách gọi món lịch sự và tự nhiên."),
    fill("a1-5-4", "We don't have ___ milk. (không có chút nào)", ["any"], "Câu phủ định dùng any."),
    fill("a1-5-5", "A ___ of rice, please. (bát)", ["bowl"], "Một bát cơm là a bowl of rice."),
    reorder("a1-5-6", "I'd like a bowl of rice.", "Mẫu câu gọi món: I'd like + a bowl of + danh từ không đếm được."),
    listen("a1-5-7", "How much is it?", ["Bao nhiêu tiền vậy?", "Cái này là gì?", "Bạn muốn ăn gì?"], 0, "How much is it? dùng để hỏi giá."),
    listen("a1-5-8", "Two glasses of orange juice, please.", ["Cho tôi hai chai nước cam.", "Cho tôi một cốc nước cam.", "Cho tôi hai cốc nước cam."], 2, "Glass là cái cốc thủy tinh; bottle mới là cái chai."),
  ],
  speaking: [
    say("Can I have a bowl of pho, please?", "Cho tôi một bát phở nhé?"),
    say("I'd like some water, please.", "Cho tôi một ít nước."),
    say("How much is a cup of coffee?", "Một cốc cà phê bao nhiêu tiền?"),
  ],
});

const nhaNoiChon = lesson({
  slug: "nha-va-noi-chon",
  title: "Nhà và nơi chốn",
  minutes: 20,
  lecture: {
    title: "There is, there are và giới từ chỉ vị trí",
    blocks: [
      p("Để nói ở đâu đó **có** cái gì, tiếng Anh dùng **there is** (với danh từ số ít hoặc không đếm được) và **there are** (với danh từ số nhiều). Đây là chữ “có” chỉ sự tồn tại, không phải “có” chỉ sở hữu."),
      table(
        ["", "Số ít / không đếm được", "Số nhiều"],
        ["Khẳng định", "There is (There's) a sofa.", "There are two chairs."],
        ["Phủ định", "There isn't a TV.", "There aren't any pictures."],
        ["Câu hỏi", "Is there a lamp?", "Are there any windows?"],
      ),
      ex("How many bedrooms are there? There are two.", "Có bao nhiêu phòng ngủ? Có hai phòng.", "Hỏi số lượng: How many + danh từ số nhiều + are there?"),
      mistake("In my room have a bed.", "There is a bed in my room.", "Tiếng Việt nói “Trong phòng tôi có một cái giường”, nên người Việt hay dịch “có” thành have. Khi nói về sự tồn tại, dùng there is/are."),
      ex("Is there a bank near here? Yes, there is.", "Gần đây có ngân hàng không? Có."),
      tip("Câu trả lời ngắn là **Yes, there is.** hoặc **No, there isn't.** Không viết tắt ở câu trả lời có: không nói “Yes, there's.”"),
      p("**Giới từ chỉ vị trí** cho biết đồ vật ở đâu. Cấu trúc thường gặp: đồ vật + to be + giới từ + nơi chốn."),
      table(
        ["Giới từ", "Nghĩa", "Ví dụ"],
        ["in", "trong", "The keys are in the bag."],
        ["on", "trên (có chạm bề mặt)", "The phone is on the table."],
        ["under", "dưới", "The cat is under the bed."],
        ["next to", "bên cạnh", "The lamp is next to the sofa."],
        ["between", "ở giữa (hai vật)", "The table is between the two chairs."],
        ["behind", "phía sau", "The garden is behind the house."],
        ["in front of", "phía trước", "The car is in front of the house."],
      ),
      ex("My bag is on the chair, not under it.", "Túi của tôi ở trên ghế, không phải ở dưới ghế."),
      mistake("The bank is in front the school.", "The bank is in front of the school.", "In front of và next to là cụm cố định; đừng bỏ of hay to."),
      tip("**In front of** nghĩa là ngay phía trước, không phải “đối diện” bên kia đường. Đối diện là **opposite**: The bank is opposite the school."),
    ],
  },
  words: [
    word("kitchen", "/ˈkɪtʃ.ən/", "nhà bếp", "There is a big table in the kitchen.", "kitch|en", 0),
    word("bedroom", "/ˈbed.ruːm/", "phòng ngủ", "There are two bedrooms in my flat.", "bed|room", 0),
    word("bathroom", "/ˈbɑːθ.ruːm/", "phòng tắm", "Is there a bathroom upstairs?", "bath|room", 0, "Âm /θ/ đặt đầu lưỡi giữa hai hàm răng, đừng đọc thành /t/."),
    word("table", "/ˈteɪ.bəl/", "cái bàn", "The keys are on the table.", "ta|ble", 0),
    word("chair", "/tʃeər/", "cái ghế", "There are four chairs in the room.", "chair", 0),
    word("sofa", "/ˈsəʊ.fə/", "ghế sô pha", "The cat is under the sofa.", "so|fa", 0),
    word("window", "/ˈwɪn.dəʊ/", "cửa sổ", "The desk is next to the window.", "win|dow", 0),
    word("between", "/bɪˈtwiːn/", "ở giữa", "The lamp is between the bed and the desk.", "be|tween", 1),
  ],
  exercises: [
    mc("a1-6-1", "There ___ two bedrooms in my flat.", ["is", "are", "be"], 1, "Two bedrooms là số nhiều nên dùng there are."),
    mc("a1-6-2", "___ there a TV in the living room?", ["Are", "Do", "Is"], 2, "A TV là số ít nên câu hỏi dùng Is there."),
    mc("a1-6-3", "The cat is ___ the bed. (ở dưới gầm giường)", ["under", "on", "in"], 0, "Under nghĩa là ở dưới."),
    fill("a1-6-4", "The lamp is next ___ the sofa.", ["to"], "Next to là cụm cố định, nghĩa là bên cạnh."),
    fill("a1-6-5", "There ___ a big window in the kitchen.", ["is", "'s"], "A big window là số ít nên dùng there is."),
    reorder("a1-6-6", "How many chairs are there in the kitchen?", "How many + danh từ số nhiều + are there + nơi chốn?"),
    listen("a1-6-7", "The keys are on the table.", ["Chìa khóa ở dưới bàn.", "Chìa khóa ở trên bàn.", "Chìa khóa ở trong túi."], 1, "On là ở trên bề mặt."),
    listen("a1-6-8", "Is there a bank near here?", ["Ngân hàng ở đâu?", "Gần đây có chợ không?", "Gần đây có ngân hàng không?"], 2, "Is there...? dùng để hỏi ở đâu đó có cái gì không."),
  ],
  speaking: [
    say("There is a small kitchen in my house.", "Nhà tôi có một căn bếp nhỏ."),
    say("My phone is on the table.", "Điện thoại của tôi ở trên bàn."),
    say("Is there a bank near here?", "Gần đây có ngân hàng không?"),
  ],
});

export const tiengAnhA1: Course = {
  slug: "tieng-anh-a1",
  title: "Tiếng Anh A1: Nền tảng",
  level: "A1",
  goal: "lo-trinh",
  summary: "Cho người mất gốc: nói được những câu đầu tiên về bản thân, gia đình và cuộc sống hằng ngày.",
  outcomes: [
    "Giới thiệu bản thân và người khác",
    "Nói số, tuổi, giờ và số điện thoại",
    "Kể về một ngày của bạn",
    "Gọi món và hỏi đồ vật ở đâu",
  ],
  audience: [
    "Người mất gốc hoặc đã quên gần hết kiến thức phổ thông",
    "Người muốn học lại tiếng Anh từ đầu một cách bài bản",
  ],
  teacher: {
    name: "Cô Hà My",
    initials: "HM",
    bio: "8 năm dạy tiếng Anh cho người mới bắt đầu, chứng chỉ CELTA. Chuyên sửa phát âm cho người Việt.",
  },
  priceVnd: 690_000,
  durationWeeks: 6,
  rating: 4.9,
  reviews: [
    { name: "Minh Anh", role: "Nhân viên kế toán, Hà Nội", quote: "Mình mất gốc từ cấp 3. Phần bài giảng giải thích bằng tiếng Việt rất dễ hiểu, mình không còn sợ ngữ pháp nữa." },
    { name: "Đức Long", role: "Kỹ sư phần mềm, Đà Nẵng", quote: "Mỗi bài chỉ khoảng 15 phút nên mình học được trên xe buýt." },
  ],
  faqs: [
    { q: "Mình mất gốc hoàn toàn thì học được không?", a: "Được. Khóa A1 bắt đầu từ động từ to be và những câu chào hỏi đầu tiên." },
    { q: "Học xong A1 thì học gì tiếp?", a: "Bạn học tiếp khóa A2: Giao tiếp hằng ngày. Mỗi cấp có chứng chỉ riêng." },
  ],
  status: "open",
  modules: [
    { id: "m1", title: "Làm quen", lessons: [chaoHoi, giaDinh, soTuoi] },
    { id: "m2", title: "Cuộc sống hằng ngày", lessons: [motNgay, doAn, nhaNoiChon] },
  ],
};
