import { A, B, dialogue, ex, fill, lesson, listen, mc, mistake, p, reorder, say, summary, table, task, teacher, tip, word } from "../builders";
import nGoiDienVaHopTrucTuyen from "../lessons/b2/goi-dien-va-hop-truc-tuyen";
import nDieuKienNangCao from "../lessons/b2/dieu-kien-nang-cao";
import nDongTuKhuyetThieuQuaKhu from "../lessons/b2/dong-tu-khuyet-thieu-qua-khu";
import nGiaDinhKhongThat from "../lessons/b2/gia-dinh-khong-that";
import nMoTaSoLieu from "../lessons/b2/mo-ta-so-lieu";
import nTuNoiNangCao from "../lessons/b2/tu-noi-nang-cao";
import nRutGonMenhDe from "../lessons/b2/rut-gon-menh-de";
import nMaoTu from "../lessons/b2/mao-tu";
import nToVHayVIng from "../lessons/b2/to-v-hay-v-ing";
import nThanPhienVaXuLy from "../lessons/b2/than-phien-va-xu-ly";
import { chapter } from "../review";
import type { Course } from "../types";

const vietEmail = lesson({
  slug: "viet-email-chuyen-nghiep",
  title: "Viết email chuyên nghiệp",
  minutes: 20,
  lecture: {
    title: "Văn phong trang trọng và lời đề nghị lịch sự",
    blocks: [
      p("Chị Thu, nhân viên xuất nhập khẩu ở Hải Phòng, gửi cho đối tác Đức một email chỉ có một dòng: **Send me the price list.** Ba ngày không thấy trả lời. Không phải đối tác bận, mà vì câu ấy đọc lên nghe như **ra lệnh**. Trong tiếng Việt, ta làm mềm bằng “anh ơi”, “giúp em với”; tiếng Anh làm mềm bằng **cấu trúc câu**. Bài này dạy bạn viết một email vừa rõ ràng vừa lịch sự."),
      p("Email công việc bằng tiếng Anh có hai mức văn phong chính: **trang trọng** (gửi đối tác, khách hàng, cấp trên chưa quen) và **trung tính** (gửi đồng nghiệp đã quen). Người Việt hay viết email quá thân mật hoặc dịch từng chữ từ tiếng Việt, khiến câu nghe cộc lốc hoặc ra lệnh."),
      table(
        ["Phần email", "Trang trọng", "Trung tính"],
        ["Mở đầu", "Dear Mr Smith,", "Hi Anna,"],
        ["Lý do viết", "I am writing to enquire about…", "Just a quick note about…"],
        ["Đính kèm", "Please find attached the report.", "I've attached the report."],
        ["Nhắc lại", "I am following up on my email of 3 May.", "Just following up on this."],
        ["Kết thư", "I look forward to hearing from you. Kind regards,", "Speak soon. Best,"],
      ),
      p("Một email **rõ ràng và đủ chi tiết** luôn có bốn phần: **dòng tiêu đề** nói đúng việc (Subject: Revised quotation for order 245, không viết “Hello” hay “Urgent!!!”), **câu mở** nêu lý do viết, **thân thư** mỗi đoạn một ý kèm số liệu, ngày tháng cụ thể, và **câu cuối** nói rõ người nhận cần làm gì, trước khi nào. Người đọc bận rộn chỉ cần lướt tiêu đề và câu cuối là biết việc."),
      p("Khi nhờ ai làm gì, đừng dùng câu mệnh lệnh trần như **Send me the file.** Hãy dùng các mẫu lịch sự. Càng xuống dưới bảng, câu càng dài và càng lịch sự; với khách hàng mới hoặc cấp trên, hãy chọn hai dòng cuối."),
      table(
        ["Mức độ", "Mẫu câu", "Ví dụ"],
        ["Ra lệnh (tránh dùng)", "V + tân ngữ", "Send me the file."],
        ["Lịch sự", "Could you + V…?", "Could you send me the file?"],
        ["Rất lịch sự", "Would you mind + V-ing…?", "Would you mind sending me the file?"],
        ["Trang trọng nhất", "I would appreciate it if you could + V…", "I would appreciate it if you could send me the file."],
      ),
      ex("Could you send me the updated figures by Friday?", "Anh/chị có thể gửi tôi số liệu cập nhật trước thứ Sáu được không?"),
      ex("I would appreciate it if you could confirm the meeting time.", "Tôi rất cảm kích nếu anh/chị xác nhận giúp thời gian cuộc họp.", "Sau “I would appreciate it if you could” là động từ nguyên mẫu. Chữ “it” không được bỏ."),
      ex("Please find attached the signed contract.", "Xin gửi kèm theo đây bản hợp đồng đã ký.", "Đây là cụm cố định có trật tự đặc biệt: attached đứng trước tân ngữ. Cũng có thể viết The signed contract is attached."),
      ex("Would you mind checking the figures before I send them to the client?", "Anh/chị có phiền kiểm tra giúp các số liệu trước khi tôi gửi cho khách không?", "Would you mind + V-ing. Nghĩa đen là “anh/chị có phiền không”, nên muốn đồng ý thì trả lời “No, not at all.”"),
      mistake("I look forward to hear from you.", "I look forward to hearing from you.", "Trong cụm look forward to, “to” là giới từ nên động từ phía sau phải thêm -ing. Người Việt quen “to + V” nên hay viết sai câu kết thư quen thuộc nhất này."),
      mistake("Please send me the file as soon as possible!!!", "Could you send me the file when you have a moment?", "Câu mệnh lệnh kèm “as soon as possible” và nhiều dấu chấm than nghe gấp gáp, thiếu tôn trọng người nhận. Tiếng Việt thêm “ạ”, “giúp em” là đủ mềm, nhưng chữ please trong tiếng Anh không đủ để làm mềm một câu mệnh lệnh."),
      mistake("Dear Mr John,", "Dear Mr Smith,", "Người Việt quen gọi “anh Minh”, “chị Lan” bằng tên riêng. Trong tiếng Anh, Mr/Ms đi với họ (surname). Nếu muốn gọi tên riêng thì bỏ Mr: Dear John,"),
      tip("Khi nhờ người khác làm gì, **Would you mind** đi với **V-ing**: Would you mind checking this? Nếu đồng ý giúp, người ta trả lời “Not at all”, nghĩa là “Không phiền gì cả”."),
      tip("Khi không biết tên người nhận, dùng **Dear Sir or Madam** hoặc tốt hơn là **Dear Hiring Manager / Dear Customer Service Team**. Không viết “Dear Sir/Madam Lan”."),
      teacher("Sau nhiều năm chữa email cho học trò, tôi thấy lỗi lớn nhất không phải ngữ pháp mà là **giọng điệu**. Trước khi bấm gửi, hãy đọc to email lên và tự hỏi: **nếu sếp nói với mình câu này, mình có thấy khó chịu không?** Nếu có, hãy đổi câu mệnh lệnh thành Could you… hoặc I would appreciate it if you could… Mỗi ngày viết lại một email cũ theo cách lịch sự hơn, chỉ một tháng là tay bạn tự viết đúng."),
      summary(
        "Email có bốn phần: **tiêu đề** nói đúng việc, **câu mở** nêu lý do viết, **thân thư** mỗi đoạn một ý, **câu cuối** nói rõ người nhận cần làm gì và trước khi nào.",
        "Chọn văn phong theo người nhận: **Dear Mr/Ms + họ** cho đối tác, khách hàng mới; **Hi + tên** cho đồng nghiệp đã quen.",
        "Không ra lệnh trần. Nhờ việc bằng **Could you + V?**, **Would you mind + V-ing?** hoặc **I would appreciate it if you could + V**.",
        "**Look forward to + V-ing**: I look forward to hearing from you. Chữ to ở đây là giới từ.",
        "Gửi kèm tài liệu: **Please find attached…**; nhắc lại việc cũ: **I am following up on…**",
      ),
    ],
  },
  words: [
    word("attachment", "/əˈtætʃ.mənt/", "tệp đính kèm", "The attachment is too large to open.", "at|tach|ment", 1),
    word("request", "/rɪˈkwest/", "yêu cầu, đề nghị", "We have received your request.", "re|quest", 1, "Trọng âm rơi vào âm tiết thứ hai: re-QUEST."),
    word("regarding", "/rɪˈɡɑː.dɪŋ/", "về việc, liên quan đến", "I am writing regarding your invoice.", "re|gard|ing", 1),
    word("colleague", "/ˈkɒl.iːɡ/", "đồng nghiệp", "My colleague will contact you tomorrow.", "col|league", 0, "Đọc là /ˈkɒl.iːɡ/, không đọc thành “cô-lê-gơ”."),
    word("deadline", "/ˈded.laɪn/", "hạn chót", "The deadline for the proposal is next Monday.", "dead|line", 0),
    word("confirm", "/kənˈfɜːm/", "xác nhận", "Could you confirm your attendance?", "con|firm", 1),
    word("recipient", "/rɪˈsɪp.i.ənt/", "người nhận", "Check the recipient's address before you click send.", "re|cip|i|ent", 1),
    word("urgent", "/ˈɜː.dʒənt/", "khẩn cấp", "This is an urgent matter, so please reply today.", "ur|gent", 0),
  ],
  exercises: [
    mc("b2-1-1", "Which opening is most suitable for an email to a new client?", ["Hey guys,", "Dear Ms Nguyen,", "Hi mate,"], 1, "Với khách hàng mới, dùng Dear + danh xưng + họ."),
    mc("b2-1-2", "Would you mind ___ the report before the meeting?", ["to check", "check", "checked", "checking"], 3, "Khi nhờ ai làm gì, Would you mind đi với V-ing."),
    fill("b2-1-3", "I look forward to ___ from you.", ["hearing"], "Look forward to + V-ing, vì “to” ở đây là giới từ."),
    fill("b2-1-4", "Please find ___ the invoice for March.", ["attached", "enclosed"], "Please find attached (hoặc enclosed) là cụm cố định khi gửi kèm tài liệu."),
    reorder("b2-1-5", "Would you mind checking the figures again?", "Would you mind + V-ing: nhờ ai làm gì một cách rất lịch sự. Again đứng cuối câu, sau tân ngữ."),
    reorder("b2-1-6", "I am following up on my previous email.", "Follow up on: nhắc lại, hỏi tiếp về một việc đã gửi trước đó."),
    listen("b2-1-7", "Could you confirm the delivery date by Thursday?", ["Anh/chị đã giao hàng vào thứ Năm chưa?", "Anh/chị có thể xác nhận ngày giao hàng trước thứ Năm không?", "Chúng tôi sẽ giao hàng vào thứ Năm."], 1),
    listen("b2-1-8", "I'm writing to enquire about your training courses.", ["Tôi viết thư để hỏi về các khóa đào tạo của quý công ty.", "Tôi viết thư để đăng ký một khóa đào tạo.", "Tôi viết thư để phàn nàn về khóa đào tạo."], 0, "Enquire about nghĩa là hỏi thông tin về điều gì."),
  ],
  speaking: [
    say("I am writing regarding the meeting next week.", "Tôi viết thư về cuộc họp tuần tới."),
    say("Could you send me the report by Friday?", "Anh/chị có thể gửi tôi bản báo cáo trước thứ Sáu không?"),
    say("I look forward to hearing from you.", "Tôi mong sớm nhận được phản hồi của anh/chị."),
  ],
  dialogue: dialogue(
    "Sửa email trước khi gửi đối tác",
    "Chị Thu, nhân viên xuất nhập khẩu, soạn xong email gửi ông Weber bên đối tác Đức. Trước khi gửi, chị nhờ anh Mark, trưởng phòng người Anh, đọc giúp.",
    { A: "Thu, nhân viên xuất nhập khẩu", B: "Mark, trưởng phòng" },
    A("Hi Mark, would you mind having a quick look at my email to Mr Weber before I send it?", "Chào anh Mark, anh có phiền xem nhanh giúp em email gửi ông Weber trước khi em gửi không?"),
    B("Not at all. Hmm, your subject line just says Hello. What is the email about?", "Không phiền gì. Ừm, dòng tiêu đề của em chỉ ghi Hello. Email này về việc gì vậy?"),
    A("I'm asking for their new price list and the delivery date for order two four five.", "Em hỏi bảng giá mới của họ và ngày giao hàng của đơn hai bốn năm."),
    B("Then say exactly that: Price list and delivery date for order two four five.", "Vậy thì ghi đúng như thế: Bảng giá và ngày giao hàng cho đơn hai bốn năm."),
    A("Good idea. And the first line? I wrote: Send me the price list.", "Hay quá. Còn câu đầu tiên thì sao ạ? Em viết: Send me the price list."),
    B("That sounds like an order. Try: I am writing to enquire about your updated price list.", "Câu đó nghe như ra lệnh. Em thử viết: Tôi viết thư để hỏi về bảng giá cập nhật của quý công ty."),
    A("And for the date, could I write: Could you confirm the delivery date by Friday?", "Còn phần ngày giao hàng, em viết “Ông có thể xác nhận ngày giao hàng trước thứ Sáu không?” có được không ạ?"),
    B("Perfect. It's polite, and it tells him exactly what to do and when.", "Rất tốt. Câu đó lịch sự, lại nói rõ ông ấy cần làm gì và khi nào."),
    A("At the end I wrote: I look forward to hear from you.", "Cuối thư em viết: I look forward to hear from you."),
    B("Almost. It's look forward to hearing, with -ing. Then Kind regards and your full name.", "Gần đúng rồi. Phải là look forward to hearing, có -ing. Sau đó là Kind regards và họ tên đầy đủ của em."),
    A("Thanks, Mark. I'll fix it and send it this afternoon.", "Cảm ơn anh Mark. Em sẽ sửa và gửi ngay chiều nay."),
    B("Great. And don't forget the order form: Please find attached the order form.", "Tốt lắm. Và đừng quên phiếu đặt hàng: Xin gửi kèm theo đây phiếu đặt hàng."),
  ),
  task: task({
    prompt: "Viết một email trang trọng gửi bà Sarah Lee, quản lý bên nhà cung cấp, nhờ bà gửi bảng giá cập nhật và xác nhận ngày giao hàng cho đơn hàng của công ty bạn. Có dòng tiêu đề, lời chào, lý do viết, lời nhờ lịch sự, tài liệu đính kèm và câu kết thư.",
    hints: [
      "Dòng tiêu đề nói đúng việc, ví dụ: Updated price list and delivery date for order 312.",
      "Mở bằng Dear Ms Lee, rồi I am writing regarding… hoặc I am writing to enquire about…",
      "Dùng ít nhất hai mẫu nhờ việc khác nhau: Could you…?, Would you mind + V-ing…?, I would appreciate it if you could…",
      "Câu cuối nêu hạn trả lời cụ thể, rồi kết bằng I look forward to hearing from you. Kind regards,",
    ],
    model: "Subject: Updated price list and delivery date for order 312\n\nDear Ms Lee,\n\nI am writing regarding order 312, which we placed on 2 October. Could you send me your updated price list for the fourth quarter? I would also appreciate it if you could confirm the delivery date, as our warehouse needs to plan the space. Please find attached a copy of the purchase order for your reference. Would you mind replying by Friday, 10 October?\n\nI look forward to hearing from you.\n\nKind regards,\nNguyen Thu Ha\nPurchasing Officer",
    checklist: [
      "Dòng tiêu đề nói rõ việc cần trao đổi, không phải Hello hay Urgent.",
      "Lời chào dùng Dear Ms + họ, không dùng tên riêng sau Ms.",
      "Không có câu mệnh lệnh trần; mọi lời nhờ đều dùng Could you, Would you mind + V-ing hoặc I would appreciate it if you could.",
      "Có câu cuối nêu hạn trả lời cụ thể (ngày, thứ).",
      "Kết thư viết đúng I look forward to hearing from you, có -ing.",
    ],
    minWords: 70,
  }),
});

const hopThaoLuan = lesson({
  slug: "hop-va-thao-luan",
  title: "Họp và thảo luận",
  minutes: 22,
  lecture: {
    title: "Suy đoán về quá khứ và xen ngang lịch sự",
    blocks: [
      p("Chín giờ sáng, cuộc họp online với khách hàng Úc đã bắt đầu mà anh Tuấn chưa vào. Sếp hỏi: **Where's Tuan?** Nhiều bạn sẽ trả lời “Maybe he forget” hoặc chỉ nói “I don't know”. Người đi làm chuyên nghiệp sẽ nói: **He might have forgotten. He must have had a problem with his internet connection.** Đó chính là cách **suy đoán về quá khứ**, một kỹ năng dùng hằng ngày trong họp hành."),
      p("Ở B1, bài **Chắc là, có lẽ, không thể nào**, các bạn đã đoán về hiện tại với **must be, might be, can't be**. Hôm nay ta lùi về quá khứ: tiếng Anh dùng **modal + have + V3** để suy đoán về việc đã xảy ra. Mức độ chắc chắn vẫn thể hiện qua việc chọn **must**, **might/may/could** hay **can't**."),
      table(
        ["Cấu trúc", "Mức độ chắc chắn", "Ví dụ"],
        ["must have + V3", "Gần như chắc chắn là có", "He must have missed the train."],
        ["might / may / could have + V3", "Có thể đã xảy ra", "She might have forgotten the meeting."],
        ["can't / couldn't have + V3", "Gần như chắc chắn là không", "They can't have received the email."],
      ),
      ex("The client hasn't replied. They must have been busy.", "Khách hàng chưa trả lời. Chắc hẳn họ đã rất bận.", "Been là V3 của be, nên must have been = chắc hẳn đã (ở trạng thái)."),
      ex("Tom can't have finished the report already. He only started an hour ago.", "Tom không thể nào đã làm xong báo cáo rồi. Anh ấy mới bắt đầu một tiếng trước.", "Câu thứ hai là bằng chứng. Người bản xứ gần như luôn đưa lý do sau lời suy đoán."),
      ex("She might have sent it to the wrong address.", "Có thể cô ấy đã gửi nhầm địa chỉ.", "Might have, may have và could have gần như cùng nghĩa: có thể đã, nhưng chưa chắc."),
      mistake("He must missed the train.", "He must have missed the train.", "Tiếng Việt chỉ cần thêm chữ “đã” là thành quá khứ, nên học trò hay quên “have”. Khi suy đoán về quá khứ phải có đủ “have + V3”."),
      mistake("She mustn't have seen the message.", "She can't have seen the message.", "Phủ định của “must have” khi suy đoán là “can't have”. Mustn't nghĩa là “cấm”, không dùng để đoán."),
      mistake("He must have went home.", "He must have gone home.", "Sau have luôn là V3 (quá khứ phân từ), không phải V2. Tiếng Việt không chia động từ nên người Việt hay lẫn went và gone; hãy học động từ bất quy tắc theo bộ ba: go, went, gone."),
      tip("Khi nói nhanh, **have** trong cấu trúc này đọc nhẹ thành /əv/: **must have** nghe như “must-tợv” /ˈmʌs.təv/, **might have** nghe như /ˈmaɪ.təv/. Đừng nhấn mạnh chữ have, hãy nhấn vào động từ chính: He must've **missed** it."),
      p("Muốn xen ngang hoặc hỏi lại trong cuộc họp, người Việt hay im lặng hoặc nói thẳng “No, wrong”. Hãy dùng các cụm mềm mỏng sau."),
      table(
        ["Mục đích", "Cụm từ"],
        ["Xen ngang", "Sorry to interrupt, but… / Can I just come in here?"],
        ["Hỏi lại cho rõ", "Could you clarify what you mean by…? / Sorry, I didn't quite catch that."],
        ["Đưa ý kiến", "From my point of view… / I'd like to suggest that…"],
        ["Đồng ý, phản đối", "I completely agree with Lan on this. / I see your point, but I'm not sure it will work."],
        ["Kéo về chủ đề", "Let's get back to the main point. / Shall we move on to the next item?"],
        ["Chốt việc cần làm", "So, to sum up, we've agreed to… / Who's going to take care of this?"],
      ),
      tip("Khi không nghe rõ, đừng nói **What?**. Hãy nói **Sorry, could you say that again?** hoặc **Sorry, I didn't quite catch that.**"),
      teacher("Tôi dạy người đi làm đã nhiều thế hệ, và cái bẫy lớn nhất trong họp không phải là thiếu từ, mà là **sợ nói sai nên im lặng**. Người nước ngoài không đánh giá bạn vì một lỗi ngữ pháp, nhưng họ sẽ nghĩ bạn không có ý kiến nếu bạn ngồi im cả buổi. Hãy thuộc lòng ba câu: **Sorry to interrupt, but…**, **Could you clarify that?** và **I'd like to suggest that…** Trước mỗi cuộc họp, tự đặt mục tiêu nói ít nhất một câu. Nói được một câu hôm nay, tuần sau bạn sẽ nói được năm câu."),
      summary(
        "Suy đoán về quá khứ: **modal + have + V3**. **Must have** (chắc hẳn đã), **might / may / could have** (có thể đã), **can't have** (không thể nào đã).",
        "Phủ định của must have khi đoán là **can't have**. Mustn't nghĩa là cấm, không dùng để đoán.",
        "Sau have luôn là **V3**: must have gone, không phải must have went.",
        "Người bản xứ đưa **bằng chứng** ngay sau lời đoán: He must have left. His laptop isn't here.",
        "Trong họp: **Sorry to interrupt, but…**, **Could you clarify…?**, **Sorry, I didn't quite catch that.**, **So, to sum up…**",
      ),
    ],
  },
  words: [
    word("agenda", "/əˈdʒen.də/", "chương trình họp", "Let's look at the first item on the agenda.", "a|gen|da", 1),
    word("clarify", "/ˈklær.ɪ.faɪ/", "làm rõ", "Could you clarify the timeline for us?", "clar|i|fy", 0),
    word("postpone", "/pəʊstˈpəʊn/", "hoãn lại", "We had to postpone the launch until June.", "post|pone", 1),
    word("consensus", "/kənˈsen.səs/", "sự đồng thuận", "The team finally reached a consensus.", "con|sen|sus", 1),
    word("interrupt", "/ˌɪn.təˈrʌpt/", "ngắt lời, xen ngang", "Sorry to interrupt, but I have a quick question.", "in|ter|rupt", 2, "Trọng âm chính ở âm tiết cuối: in-ter-RUPT."),
    word("priority", "/praɪˈɒr.ə.ti/", "ưu tiên", "Customer feedback is our top priority.", "pri|or|i|ty", 1),
    word("budget", "/ˈbʌdʒ.ɪt/", "ngân sách", "The project is already over budget.", "bud|get", 0),
    word("summarise", "/ˈsʌm.ər.aɪz/", "tóm tắt", "Let me summarise what we have agreed.", "sum|ma|rise", 0),
  ],
  exercises: [
    mc("b2-2-1", "The lights are off in his office. He ___ gone home.", ["must have", "can't have", "mustn't have"], 0, "Có bằng chứng rõ ràng nên dùng must have: chắc hẳn đã."),
    mc("b2-2-2", "She ___ sent the file. My inbox is empty.", ["must have", "can't have", "should"], 1, "Hộp thư trống nên gần như chắc chắn cô ấy chưa gửi: can't have."),
    reorder("b2-2-3", "Could you say that again?", "Cách hỏi lại lịch sự khi chưa nghe rõ, thay cho câu cộc lốc What? Có thể thêm Sorry ở đầu cho mềm hơn."),
    fill("b2-2-4", "I'm not sure why he's late. He might have ___ the bus. (miss)", ["missed"], "Sau might have là động từ ở dạng V3 (quá khứ phân từ): miss thành missed."),
    fill("b2-2-5", "Could you ___ what you mean by “flexible hours”? (làm rõ)", ["clarify", "explain"], "Clarify hoặc explain đều dùng để nhờ người khác giải thích rõ hơn."),
    reorder("b2-2-6", "Shall we move on to the next item?", "Câu chuyển sang mục tiếp theo trong chương trình họp."),
    listen("b2-2-7", "Sorry, I didn't quite catch that.", ["Xin lỗi, tôi không đồng ý.", "Xin lỗi, tôi đến muộn.", "Xin lỗi, tôi chưa nghe rõ lắm."], 2, "Catch ở đây nghĩa là nghe kịp, nghe rõ."),
    listen("b2-2-8", "They can't have read the proposal yet.", ["Chắc chắn họ đã đọc bản đề xuất.", "Họ không thể nào đã đọc bản đề xuất rồi.", "Họ không được phép đọc bản đề xuất."], 1),
  ],
  speaking: [
    say("Sorry to interrupt, but could I add something?", "Xin lỗi đã ngắt lời, tôi có thể bổ sung một ý không?"),
    say("He must have missed the train this morning.", "Chắc hẳn anh ấy đã lỡ chuyến tàu sáng nay."),
    say("Let's get back to the main point.", "Chúng ta hãy quay lại vấn đề chính."),
  ],
  dialogue: dialogue(
    "Cuộc họp nhóm sáng thứ Hai",
    "Chín giờ sáng, chị Lan chủ trì cuộc họp dự án. Anh Tuấn chưa đến, khách hàng chưa trả lời bản đề xuất. Chị Lan và anh David, quản lý dự án người Anh, vừa đoán lý do vừa bàn bước tiếp theo.",
    { A: "Lan, trưởng nhóm", B: "David, quản lý dự án" },
    A("Shall we start? Tuan still isn't here.", "Mình bắt đầu nhé? Tuấn vẫn chưa đến."),
    B("He must have got stuck in traffic. It's been raining all morning.", "Chắc hẳn cậu ấy bị kẹt xe rồi. Trời mưa suốt cả sáng mà."),
    A("Or he might have forgotten. We moved the meeting to nine only yesterday.", "Hoặc có thể cậu ấy quên. Mới hôm qua mình dời cuộc họp sang chín giờ."),
    B("He can't have forgotten. He accepted the new invitation last night.", "Cậu ấy không thể quên được. Tối qua cậu ấy đã chấp nhận lời mời mới rồi."),
    A("OK, let's look at the first item on the agenda: the Lotus Hotel proposal.", "Được rồi, mình xem mục đầu tiên trong chương trình họp: bản đề xuất cho khách sạn Lotus."),
    B("Sorry to interrupt, but have they replied yet?", "Xin lỗi đã ngắt lời, nhưng họ đã trả lời chưa?"),
    A("Not yet. They must have been busy with the audit this week.", "Chưa. Chắc hẳn tuần này họ bận với đợt kiểm toán."),
    B("Sorry, I didn't quite catch that. Did you say audit?", "Xin lỗi, tôi chưa nghe rõ lắm. Chị nói kiểm toán à?"),
    A("Yes. Their finance team is checking everything, so they may have put our email aside.", "Đúng vậy. Bộ phận tài chính của họ đang rà soát mọi thứ, nên có thể họ đã tạm gác email của mình lại."),
    B("I see. From my point of view, we should call them instead of waiting.", "Tôi hiểu rồi. Theo tôi, mình nên gọi cho họ thay vì ngồi chờ."),
    A("I completely agree. So, to sum up, you'll call the client, and I'll update Tuan.", "Tôi hoàn toàn đồng ý. Vậy tóm lại, anh sẽ gọi cho khách, còn tôi sẽ cập nhật cho Tuấn."),
    B("Sounds good. Shall we move on to the next item?", "Được đấy. Mình chuyển sang mục tiếp theo nhé?"),
  ),
  task: task({
    prompt: "Viết lời bạn sẽ nói trong cuộc họp nhóm: khách hàng chưa trả lời email bạn gửi từ tuần trước. Hãy xen vào lịch sự, đưa ra hai hoặc ba suy đoán về lý do (kèm bằng chứng), đề xuất bước tiếp theo và chốt việc cần làm.",
    hints: [
      "Mở bằng Sorry to interrupt, but… hoặc Can I just come in here?",
      "Chọn must have, might/may have hay can't have tùy bằng chứng bạn có, và nêu bằng chứng ngay sau lời đoán.",
      "Đưa ý kiến bằng From my point of view… hoặc I'd like to suggest that…",
      "Kết thúc bằng So, to sum up… và nói rõ ai làm gì, khi nào.",
    ],
    model: "Sorry to interrupt, but I'd like to add something about the Lotus Hotel project. The client still hasn't replied to the email we sent last Monday. They can't have missed it, because the system shows that their manager opened it on Tuesday. They might have been busy with their new branch, or they may have passed our email to another department. From my point of view, we shouldn't wait any longer. I'd like to suggest that I call their manager tomorrow morning. So, to sum up, I'll call the client and report back to you by Thursday.",
    checklist: [
      "Có ít nhất ba câu suy đoán dạng modal + have + V3.",
      "Chọn đúng mức độ: must have khi có bằng chứng mạnh, might/may have khi chưa chắc, can't have khi gần như chắc chắn không.",
      "Sau have là V3 (been, missed, passed), không phải V2.",
      "Có ít nhất một cụm xen ngang hoặc đưa ý kiến lịch sự.",
      "Câu cuối chốt việc: ai làm gì, trước khi nào.",
    ],
    minWords: 70,
  }),
});

const tuongThuat = lesson({
  slug: "tuong-thuat-loi-noi",
  title: "Tường thuật lời nói",
  minutes: 22,
  lecture: {
    title: "Câu tường thuật và lùi thì",
    blocks: [
      p("Vừa gặp khách hàng Nhật xong, sếp gọi điện hỏi: **So what did they say?** Bạn phải kể lại: khách nói gì, hỏi gì, yêu cầu gì. Nếu bạn nói “He say he want discount”, sếp vẫn hiểu, nhưng bạn sẽ mất điểm chuyên nghiệp. Kể lại lời người khác cho chính xác là việc người đi làm làm mỗi ngày: báo cáo cho sếp, viết biên bản họp, chuyển lời cho đồng nghiệp."),
      p("Khi kể lại lời người khác, ta dùng **câu tường thuật**. Tiếng Việt chỉ cần thêm “anh ấy nói là…”, nhưng tiếng Anh thường phải **lùi thì** một bậc khi động từ tường thuật ở quá khứ."),
      table(
        ["Lời nói trực tiếp", "Câu tường thuật"],
        ["“I work in sales.”", "She said (that) she worked in sales."],
        ["“We are reviewing the plan.”", "He said they were reviewing the plan."],
        ["“I have sent the invoice.”", "She said she had sent the invoice."],
        ["“I will call you tomorrow.”", "He said he would call me the next day."],
        ["“We can meet on Monday.”", "They said they could meet on Monday."],
      ),
      p("Khi kể lại vào một thời điểm khác, các từ chỉ **thời gian và nơi chốn** cũng phải đổi theo, vì “hôm nay” của người nói đã không còn là hôm nay nữa."),
      table(
        ["Lời nói trực tiếp", "Câu tường thuật"],
        ["today", "that day"],
        ["tomorrow", "the next day / the following day"],
        ["yesterday", "the day before / the previous day"],
        ["next week", "the following week"],
        ["here / this", "there / that"],
      ),
      p("Với câu hỏi, dùng **asked** và đưa câu về **trật tự câu kể** (chủ ngữ đứng trước động từ), giống hệt câu hỏi gián tiếp **Could you tell me…?** các bạn đã học ở B1. Câu hỏi Yes/No dùng **if** hoặc **whether**. Với lời yêu cầu, dùng **asked/told + tân ngữ + to V**; lời dặn đừng làm gì thì dùng **told + tân ngữ + not to V**: She told me not to worry."),
      ex("She asked me where the meeting room was.", "Cô ấy hỏi tôi phòng họp ở đâu.", "Câu gốc là “Where is the meeting room?”. Khi tường thuật, không viết “where was the meeting room” mà đưa chủ ngữ lên trước động từ."),
      ex("The manager asked if we had finished the report.", "Quản lý hỏi chúng tôi đã làm xong báo cáo chưa.", "Câu gốc là “Have you finished the report?”. Câu hỏi Yes/No nên dùng if, và have finished lùi thành had finished."),
      ex("He told me to send the file before noon.", "Anh ấy bảo tôi gửi tệp trước buổi trưa."),
      p("Động từ tường thuật khác **said** giúp câu chính xác hơn: **explain that**, **promise to V**, **suggest + V-ing** hoặc **suggest that + S + V**, **remind + sb + to V**."),
      ex("She reminded me to book the meeting room.", "Cô ấy nhắc tôi đặt phòng họp.", "Remind + người + to V. Một chữ reminded thay được cả câu dài “She said: Don't forget to book the room.”"),
      mistake("He suggested me to call the client.", "He suggested calling the client.", "Suggest không đi với “sb + to V”. Dùng suggest + V-ing hoặc suggest that I (should) call the client. Người Việt dịch từng chữ “anh ấy gợi ý tôi gọi” nên hay đặt tân ngữ ngay sau suggest."),
      mistake("She said me that the price was too high.", "She told me that the price was too high.", "Said không có tân ngữ chỉ người đứng ngay sau. Muốn nói với ai thì dùng told + người. Tiếng Việt “nói với tôi” và “bảo tôi” gần giống nhau nên người học hay dùng lẫn."),
      mistake("He asked me did I finish the report.", "He asked me if I had finished the report.", "Người Việt giữ nguyên câu hỏi vì tiếng Việt chỉ cần thêm “hỏi”. Tiếng Anh phải bỏ trợ động từ did, thêm if và lùi thì."),
      tip("Nếu thông tin **vẫn còn đúng** ở hiện tại, có thể không lùi thì: **She said the office opens at eight.** Nhưng trong văn viết trang trọng, lùi thì vẫn an toàn hơn."),
      teacher("Học trò của tôi hay cố nhớ cả bảng lùi thì rồi rối tung lên. Tôi dặn thế này: **cứ lùi một bậc về quá khứ**, hiện tại thành quá khứ, quá khứ thành quá khứ hoàn thành, will thành would, can thành could. Mỗi tối, hãy kể lại bằng tiếng Anh ba câu mà ai đó nói với bạn trong ngày, bắt đầu bằng **He said…**, **She asked…**, **My boss told me to…** Làm đều hai tuần, lùi thì sẽ thành phản xạ."),
      summary(
        "Động từ tường thuật ở quá khứ thì **lùi một bậc**: is → was, has sent → had sent, will → would, can → could.",
        "Đổi từ chỉ thời gian, nơi chốn: tomorrow → **the next day**, yesterday → **the day before**, here → **there**.",
        "Câu hỏi tường thuật dùng **trật tự câu kể**; câu hỏi Yes/No thêm **if / whether**: She asked if I had finished.",
        "Lời yêu cầu: **told / asked + người + (not) to V**. Said không có người đứng ngay sau; muốn có người thì dùng **told me**.",
        "Động từ chính xác hơn said: **suggest + V-ing**, **remind + người + to V**, **promise to V**, **explain that…**",
      ),
    ],
  },
  words: [
    word("announce", "/əˈnaʊns/", "thông báo, công bố", "The CEO announced a new strategy yesterday.", "an|nounce", 1),
    word("mention", "/ˈmen.ʃən/", "nhắc đến, đề cập", "She mentioned that the budget had been cut.", "men|tion", 0),
    word("deny", "/dɪˈnaɪ/", "phủ nhận", "He denied making the mistake.", "de|ny", 1),
    word("insist", "/ɪnˈsɪst/", "khăng khăng, nhất quyết", "The client insisted on a lower price.", "in|sist", 1),
    word("recommend", "/ˌrek.əˈmend/", "khuyên, đề xuất", "I recommend hiring an external consultant.", "rec|om|mend", 2),
    word("complain", "/kəmˈpleɪn/", "phàn nàn", "Several customers complained about the delay.", "com|plain", 1),
    word("admit", "/ədˈmɪt/", "thừa nhận", "She admitted that the figures were wrong.", "ad|mit", 1),
    word("warn", "/wɔːn/", "cảnh báo", "He warned us not to sign the contract yet.", "warn", 0, "Đọc giống “worn”, không đọc thành “wan”."),
  ],
  exercises: [
    mc("b2-3-1", "“I am working on the budget.” She said she ___ on the budget.", ["is working", "was working", "has worked"], 1, "Hiện tại tiếp diễn lùi thành quá khứ tiếp diễn."),
    mc("b2-3-2", "Which sentence is correct?", ["He asked me where was the file.", "He asked me where is the file.", "He asked me where the file was.", "He asked me where the file is it."], 2, "Câu hỏi tường thuật dùng trật tự câu kể: chủ ngữ trước động từ."),
    fill("b2-3-3", "“I will finish it tomorrow.” He promised he ___ finish it the next day.", ["would"], "Will lùi thì thành would."),
    fill("b2-3-4", "She suggested ___ the meeting to Friday. (dời lịch)", ["moving", "postponing", "rescheduling", "changing", "shifting", "pushing"], "Suggest + V-ing: moving, postponing hay rescheduling đều đúng."),
    reorder("b2-3-5", "The manager told us to finish the report.", "Told + người + to V dùng để tường thuật lời yêu cầu. Không dùng said us hay suggested us."),
    reorder("b2-3-6", "She asked if I had read the contract.", "Câu hỏi Yes/No trong tường thuật dùng if, và thì hiện tại hoàn thành lùi thành quá khứ hoàn thành."),
    listen("b2-3-7", "He explained that the shipment had been delayed.", ["Anh ấy hỏi vì sao lô hàng bị chậm.", "Anh ấy hứa sẽ giao hàng đúng hạn.", "Anh ấy phàn nàn về lô hàng.", "Anh ấy giải thích rằng lô hàng đã bị chậm."], 3),
    listen("b2-3-8", "She told me not to worry about the deadline.", ["Cô ấy bảo tôi đừng lo về hạn chót.", "Cô ấy lo lắng về hạn chót.", "Cô ấy hỏi tôi về hạn chót."], 0, "Told + người + not to V: bảo ai đừng làm gì."),
  ],
  speaking: [
    say("She said she would send the report the next day.", "Cô ấy nói sẽ gửi bản báo cáo vào ngày hôm sau."),
    say("The client asked if we could offer a discount.", "Khách hàng hỏi liệu chúng tôi có thể giảm giá không."),
    say("My manager suggested hiring two more people.", "Quản lý của tôi đề xuất tuyển thêm hai người."),
  ],
  dialogue: dialogue(
    "Báo cáo lại cho sếp sau buổi gặp khách",
    "Anh Minh vừa gặp ông Tanaka, khách hàng Nhật, xong. Sếp của anh, chị Sophie, gọi điện hỏi khách đã nói gì, hỏi gì và yêu cầu gì.",
    { A: "Minh, nhân viên kinh doanh", B: "Sophie, trưởng phòng" },
    B("So, how did the meeting with Mr Tanaka go? What did he say?", "Thế buổi gặp ông Tanaka thế nào? Ông ấy nói gì?"),
    A("It went well. He said they were very happy with the first shipment.", "Suôn sẻ ạ. Ông ấy nói họ rất hài lòng với lô hàng đầu tiên."),
    B("Good. Did he mention the price?", "Tốt. Ông ấy có nhắc đến giá không?"),
    A("Yes. He asked if we could offer a five per cent discount on the next order.", "Có ạ. Ông ấy hỏi liệu mình có thể giảm năm phần trăm cho đơn hàng tới không."),
    B("And what did you tell him?", "Thế em trả lời ông ấy thế nào?"),
    A("I told him that I would discuss it with you first.", "Em bảo ông ấy là em sẽ bàn với chị trước."),
    B("Fine. Anything else?", "Được. Còn gì nữa không?"),
    A("He explained that two boxes had arrived damaged, and he asked us to replace them this month.", "Ông ấy giải thích rằng có hai thùng hàng đến nơi bị hỏng, và ông ấy nhờ mình thay trong tháng này."),
    B("I see. Did he say when they were planning the next order?", "Chị hiểu rồi. Ông ấy có nói khi nào họ định đặt đơn tiếp theo không?"),
    A("He said they were going to order again in December. He also suggested meeting in Osaka next spring.", "Ông ấy nói họ sẽ đặt hàng lại vào tháng Mười Hai. Ông ấy còn đề xuất gặp nhau ở Osaka vào mùa xuân tới."),
    B("Great news. Please remind me to call him on Friday.", "Tin vui đấy. Em nhớ nhắc chị gọi cho ông ấy vào thứ Sáu nhé."),
    A("Sure. I'll write up the notes and send them to you this afternoon.", "Vâng ạ. Em sẽ viết biên bản và gửi chị chiều nay."),
  ),
  task: task({
    prompt: "Sếp của bạn không dự được buổi họp với khách hàng sáng nay. Viết một email ngắn tường thuật lại cho sếp: khách đã nói gì, hỏi gì, yêu cầu và đề xuất gì, và bạn đã hứa gì với khách.",
    hints: [
      "Dùng nhiều động từ tường thuật: said, mentioned, explained, asked, suggested, promised.",
      "Nhớ lùi thì: is → was, has arrived → had arrived, will → would, can → could.",
      "Câu hỏi Yes/No dùng asked whether/if + trật tự câu kể; lời nhờ dùng asked me to + V.",
      "Không viết said me. Muốn nói với ai thì dùng told me.",
    ],
    model: "Hi Long,\n\nHere is a quick summary of this morning's meeting with Ms Carter from Green Farm. She said that they were very happy with our service. However, she mentioned that the last delivery had arrived two days late. She asked whether we could deliver on Mondays instead of Wednesdays. She also asked me to send her the new price list by the end of the week, and she suggested meeting again next month. I promised that I would give her an answer by Friday.\n\nBest regards,\nMinh",
    checklist: [
      "Dùng ít nhất bốn động từ tường thuật khác nhau.",
      "Mọi động từ sau said, mentioned, explained đã lùi thì đúng.",
      "Câu hỏi tường thuật dùng trật tự câu kể, có if hoặc whether cho câu Yes/No.",
      "Lời nhờ dùng asked/told + người + to V; suggest đi với V-ing.",
      "Không có lỗi said me hoặc suggested me to.",
    ],
    minWords: 70,
  }),
});

const tiecNuoi = lesson({
  slug: "tiec-nuoi-va-gia-dinh",
  title: "Tiếc nuối và giả định quá khứ",
  minutes: 23,
  lecture: {
    title: "Câu điều kiện loại 3, câu hỗn hợp và wish",
    blocks: [
      p("Dự án ra mắt ứng dụng trễ hạn hai tuần, khách hàng phàn nàn. Trong buổi họp rút kinh nghiệm, trưởng nhóm nói: “Nếu mình kiểm thử sớm hơn thì đã không trễ” và “Giá mà mình đọc kỹ hợp đồng”. Người Việt nói những câu này rất tự nhiên, nhưng sang tiếng Anh lại hay chọn sai thì. Bài này giúp bạn nói về **những điều đã không xảy ra** một cách chính xác."),
      p("Ở B1, bài **Nếu… thì…**, các bạn đã học câu điều kiện loại 1 (có thể xảy ra) và loại 2 (không có thật ở hiện tại), và bài **Chuyện xảy ra trước đó** đã dạy **had + V3**. Hôm nay ghép hai thứ ấy lại. Khi rút kinh nghiệm, ta hay nói “Giá mà…” hoặc “Nếu hồi đó… thì đã…”. Tiếng Anh dùng **câu điều kiện loại 3** để nói về điều **không có thật trong quá khứ** và kết quả tưởng tượng của nó."),
      table(
        ["Loại câu", "Mệnh đề if", "Mệnh đề chính", "Ví dụ"],
        ["Loại 3", "If + had + V3", "would have + V3", "If we had started earlier, we would have met the deadline."],
        ["Hỗn hợp", "If + had + V3", "would + V", "If I had accepted the offer, I would be in London now."],
        ["Wish / If only", "wish + had + V3", "Không cần mệnh đề chính", "I wish I had read the contract more carefully."],
      ),
      ex("If they had tested the software, the launch wouldn't have failed.", "Nếu họ đã kiểm thử phần mềm thì buổi ra mắt đã không thất bại.", "Thực tế: họ không kiểm thử và buổi ra mắt thất bại."),
      ex("If only we had listened to the customers!", "Giá mà chúng ta đã lắng nghe khách hàng!"),
      p("**Câu hỗn hợp** nối một nguyên nhân trong quá khứ với một kết quả ở **hiện tại**: vế if dùng had + V3, vế chính dùng **would + V** (không có have)."),
      ex("If I had studied finance, I would understand these reports now.", "Nếu hồi đó tôi học tài chính thì bây giờ tôi đã hiểu những báo cáo này.", "Vế if nói về quá khứ (hồi đi học), vế chính nói về hiện tại (now), nên vế chính dùng would + V, không có have."),
      p("Với **wish**, hãy nhìn xem bạn đang tiếc điều gì ở **hiện tại** hay ở **quá khứ**, rồi lùi thì một bậc so với thực tế."),
      table(
        ["Tiếc về", "Thực tế", "Câu với wish"],
        ["Hiện tại", "I don't speak Japanese.", "I wish I spoke Japanese."],
        ["Hiện tại", "I can't come to the meeting.", "I wish I could come to the meeting."],
        ["Quá khứ", "I didn't read the contract carefully.", "I wish I had read the contract carefully."],
        ["Quá khứ", "We cut the budget.", "I wish we hadn't cut the budget."],
      ),
      mistake("If I would have known, I would have told you.", "If I had known, I would have told you.", "Tiếng Việt dùng “thì đã” ở cả hai vế nên học trò hay đặt would have vào cả hai. Trong câu điều kiện loại 3, vế if phải là had + V3, would have chỉ nằm ở vế chính."),
      mistake("I wish I didn't send that email yesterday.", "I wish I hadn't sent that email yesterday.", "Tiếc nuối về quá khứ phải dùng wish + had + V3. Wish + quá khứ đơn chỉ dùng cho hiện tại. Tiếng Việt không đổi thì nên người học chỉ nhìn chữ yesterday mà quên lùi thì."),
      mistake("If we had knew the price, we would have ordered more.", "If we had known the price, we would have ordered more.", "Sau had phải là V3. Know, knew, known là bộ ba bất quy tắc người Việt hay lẫn nhất."),
      tip("Khi nói nhanh, **would have** được đọc gần như **would've** /ˈwʊd.əv/, và **had** rút gọn thành **'d**: **If I'd known, I would've called.** Trong vế if, 'd là had chứ không phải would."),
      teacher("Sau nhiều năm đứng lớp, tôi có một mẹo cho học trò hay rối: trước khi nói, hãy **nói ra thực tế** trước đã. “Thực tế: mình không kiểm thử, dự án trễ.” Rồi **đảo ngược cả hai vế và lùi thì**: If we had tested it, we wouldn't have been late. Làm như vậy vài chục lần, bạn sẽ không bao giờ nhầm nữa. Và nhớ: câu tiếc nuối dùng để **rút kinh nghiệm**, đừng dùng để đổ lỗi cho đồng nghiệp trong cuộc họp."),
      summary(
        "Loại 3, điều không có thật trong quá khứ: **If + had + V3, would have + V3**. Would have chỉ nằm ở vế chính, không bao giờ ở vế if.",
        "Câu hỗn hợp, nguyên nhân quá khứ và kết quả hiện tại: **If + had + V3, would + V** (thường có now).",
        "Tiếc về hiện tại: **wish + quá khứ đơn** (I wish I spoke Japanese). Tiếc về quá khứ: **wish / if only + had + V3**.",
        "Mẹo: nói **thực tế** trước, rồi đảo nghĩa cả hai vế và lùi thì.",
        "Khi nói nhanh: **If I'd known, I would've called.** Trong vế if, 'd là had.",
      ),
    ],
  },
  words: [
    word("opportunity", "/ˌɒp.əˈtʃuː.nə.ti/", "cơ hội", "We missed a great opportunity to expand.", "op|por|tu|ni|ty", 2, "Trọng âm chính ở âm tiết thứ ba: op-por-TU-ni-ty."),
    word("regret", "/rɪˈɡret/", "hối tiếc", "I regret not asking for more details.", "re|gret", 1),
    word("investment", "/ɪnˈvest.mənt/", "khoản đầu tư", "The investment paid off within two years.", "in|vest|ment", 1),
    word("decision", "/dɪˈsɪʒ.ən/", "quyết định", "It was a difficult decision for the board.", "de|ci|sion", 1),
    word("consequence", "/ˈkɒn.sɪ.kwəns/", "hậu quả", "The delay had serious consequences for the company.", "con|se|quence", 0),
    word("outcome", "/ˈaʊt.kʌm/", "kết quả", "We are happy with the outcome of the negotiation.", "out|come", 0),
    word("promotion", "/prəˈməʊ.ʃən/", "sự thăng chức", "She would have got a promotion if she had stayed.", "pro|mo|tion", 1),
    word("overlook", "/ˌəʊ.vəˈlʊk/", "bỏ sót, bỏ qua", "We overlooked a small but important detail.", "o|ver|look", 2),
  ],
  exercises: [
    mc("b2-4-1", "If we ___ the risks, we would have avoided the problem.", ["had considered", "considered", "would consider"], 0, "Vế if của câu loại 3 dùng had + V3."),
    mc("b2-4-2", "If she had taken the job in Singapore, she ___ there now.", ["would have lived", "would live", "had lived"], 1, "Câu hỗn hợp: nguyên nhân ở quá khứ, kết quả ở hiện tại (now), nên dùng would + V."),
    fill("b2-4-3", "I wish I ___ asked more questions in the interview.", ["had", "'d"], "Wish + had + V3 để tiếc nuối về quá khứ."),
    fill("b2-4-4", "If the supplier had delivered on time, we would have ___ the order. (complete)", ["completed", "finished", "fulfilled", "delivered", "shipped"], "Would have + V3: complete thành completed."),
    reorder("b2-4-5", "I wish I hadn't sent that email.", "Wish + hadn't + V3: tiếc là hồi đó đã làm một việc không nên làm."),
    reorder("b2-4-6", "If only we had signed the deal earlier.", "If only + had + V3 diễn tả sự tiếc nuối mạnh."),
    listen("b2-4-7", "If I'd known about the problem, I would've called you.", ["Tôi biết có vấn đề nên đã gọi cho bạn.", "Nếu tôi mà biết có vấn đề thì tôi đã gọi cho bạn rồi.", "Nếu có vấn đề, tôi sẽ gọi cho bạn."], 1, "I'd known = I had known; would've = would have."),
    listen("b2-4-8", "I wish we hadn't cut the marketing budget.", ["Giá mà chúng ta đã không cắt giảm ngân sách tiếp thị.", "Chúng ta nên cắt giảm ngân sách tiếp thị.", "Tôi mong chúng ta sẽ tăng ngân sách tiếp thị."], 0),
  ],
  speaking: [
    say("If we had started earlier, we would have finished on time.", "Nếu chúng ta bắt đầu sớm hơn thì đã hoàn thành đúng hạn."),
    say("I wish I had read the contract more carefully.", "Giá mà tôi đã đọc hợp đồng kỹ hơn."),
    say("If I had accepted that offer, I would be a manager now.", "Nếu hồi đó tôi nhận lời đề nghị ấy thì giờ tôi đã là quản lý."),
  ],
  dialogue: dialogue(
    "Họp rút kinh nghiệm sau dự án trễ hạn",
    "Ứng dụng đặt vé của công ty ra mắt trễ hai tuần. Anh Hùng, trưởng nhóm, và chị Emma, phụ trách kiểm thử, ngồi lại rút kinh nghiệm cho dự án sau.",
    { A: "Hùng, trưởng nhóm", B: "Emma, phụ trách kiểm thử" },
    A("Let's be honest. The launch was two weeks late. What went wrong?", "Mình nói thẳng nhé. Buổi ra mắt trễ hai tuần. Sai ở đâu?"),
    B("If we had tested the payment feature earlier, we wouldn't have found that bug so late.", "Nếu mình kiểm thử tính năng thanh toán sớm hơn thì đã không phát hiện lỗi đó muộn như vậy."),
    A("I agree. I wish I had asked for two more testers in March.", "Tôi đồng ý. Giá mà hồi tháng Ba tôi đã xin thêm hai người kiểm thử."),
    B("And if the client had sent the final design on time, we would have started coding sooner.", "Và nếu khách hàng gửi bản thiết kế cuối đúng hạn thì mình đã bắt đầu viết mã sớm hơn."),
    A("True, but we overlooked a few details in the contract too. If only we had read it more carefully.", "Đúng, nhưng mình cũng bỏ sót vài chi tiết trong hợp đồng. Giá mà mình đọc nó kỹ hơn."),
    B("Yes. If we had checked the deadlines properly, we wouldn't be working at weekends now.", "Phải. Nếu mình kiểm tra hạn chót cẩn thận thì giờ đã không phải làm cả cuối tuần."),
    A("Exactly. So what's the main lesson for the next project?", "Chính xác. Vậy bài học chính cho dự án sau là gì?"),
    B("Test every feature as soon as it's ready, not at the end.", "Kiểm thử từng tính năng ngay khi làm xong, đừng để đến cuối."),
    A("Good. I wish we'd had this conversation before the project started.", "Hay đấy. Giá mà mình nói chuyện này trước khi dự án bắt đầu."),
    B("Well, at least we've learnt something. Let's write it down for the next team.", "Dù sao thì mình cũng rút ra được bài học. Ghi lại cho nhóm sau nhé."),
  ),
  task: task({
    prompt: "Viết một đoạn rút kinh nghiệm về một việc trong công việc hoặc cuộc sống đã không diễn ra như ý (một sự kiện, một dự án, một kỳ thi). Kể thực tế ngắn gọn, rồi nói điều gì lẽ ra đã khác, bạn tiếc điều gì, và bài học cho lần sau.",
    hints: [
      "Viết một hoặc hai câu kể thực tế trước, rồi đảo nghĩa và lùi thì thành câu loại 3.",
      "Thêm một câu hỗn hợp nối việc trong quá khứ với tình hình hiện tại: If I had…, I would… now.",
      "Dùng I wish / If only + had + V3 cho một điều bạn tiếc.",
      "Kết thúc bằng một bài học cho lần sau, không đổ lỗi cho người khác.",
    ],
    model: "Last year our team organised a product launch in Da Nang, and it did not go as planned. We booked the venue too late, so we had to use a small hotel room. If we had booked it two months earlier, we would have got a much bigger hall. Only forty guests came. If we had sent the invitations sooner, more customers would have attended. If I had studied event planning, I would feel more confident now. I wish I had asked an expert for advice. Next time, we will start planning three months in advance.",
    checklist: [
      "Có ít nhất hai câu điều kiện loại 3 đúng dạng: If + had + V3, would have + V3.",
      "Có một câu hỗn hợp với kết quả ở hiện tại (would + V).",
      "Có một câu I wish hoặc If only + had + V3.",
      "Không đặt would have trong vế if.",
      "Sau had là V3 đúng (known, sent, booked), không phải V2.",
      "Có một câu bài học cho lần sau.",
    ],
    minWords: 70,
  }),
});

const thuyetTrinh = lesson({
  slug: "thuyet-trinh",
  title: "Thuyết trình",
  minutes: 22,
  lecture: {
    title: "Mệnh đề quan hệ và cụm dẫn dắt khi thuyết trình",
    blocks: [
      p("Chị Hà lên thuyết trình trước ban giám đốc: “We have a new product. The product is cheap. The product sold well in Da Nang.” Ba câu ngắn, lặp chữ product ba lần, nghe như đọc danh sách. Người bản xứ sẽ nói: **Our new product, which is very affordable, sold well in Da Nang.** Một câu, gọn, trôi chảy. Bí quyết nằm ở **mệnh đề quan hệ**."),
      p("Bài thuyết trình tốt cần câu gọn và rõ. **Mệnh đề quan hệ** giúp bạn thêm thông tin về người hoặc vật mà không phải tách thành nhiều câu ngắn. Ở B1, bài **Người mà, cái mà**, các bạn đã học loại **xác định** (không có dấu phẩy, cho biết là người nào, cái nào). Trọng tâm hôm nay là loại **không xác định** (có dấu phẩy, chỉ thêm thông tin), loại mà người thuyết trình dùng nhiều nhất."),
      table(
        ["Đại từ", "Dùng cho", "Ví dụ"],
        ["who", "người", "The manager who leads the project is on holiday."],
        ["which", "vật, sự việc", "The report, which was published in May, shows strong growth."],
        ["that", "người hoặc vật (chỉ mệnh đề xác định)", "This is the product that sold best last year."],
        ["whose", "sở hữu (của ai, của cái gì)", "We work with a supplier whose prices are very competitive."],
      ),
      ex("The customers who took part in the survey were very positive.", "Những khách hàng đã tham gia khảo sát đều rất tích cực.", "Mệnh đề xác định: cho biết là khách hàng nào."),
      ex("Our Hanoi office, which opened in 2020, now has fifty staff.", "Văn phòng Hà Nội của chúng tôi, mở cửa năm 2020, hiện có năm mươi nhân viên.", "Mệnh đề không xác định: chỉ thêm thông tin, bỏ đi câu vẫn đủ nghĩa."),
      ex("The product that we launched in March is selling well.", "Sản phẩm mà chúng tôi ra mắt hồi tháng Ba đang bán rất chạy.", "Ở đây that làm tân ngữ (we launched the product), nên trong mệnh đề xác định có thể bỏ hẳn: The product we launched in March…"),
      mistake("Our CEO, that joined in 2019, will speak first.", "Our CEO, who joined in 2019, will speak first.", "Không dùng that sau dấu phẩy. Mệnh đề không xác định dùng who, which (hoặc whose, where…), không dùng that."),
      mistake("This is the chart which I showed it earlier.", "This is the chart which I showed earlier.", "Tiếng Việt nói “cái biểu đồ mà tôi đã cho xem nó” nghe vẫn được, nên người học hay giữ lại it. Trong tiếng Anh, which đã thay cho “the chart”, không lặp lại đại từ it."),
      mistake("The customers who buys our app are mostly students.", "The customers who buy our app are mostly students.", "Động từ trong mệnh đề quan hệ chia theo danh từ đứng trước who. Customers là số nhiều nên dùng buy. Tiếng Việt không có số nhiều nên người Việt hay bỏ sót chỗ này."),
      p("Cụm **dẫn dắt** (signposting) giúp người nghe biết bạn đang ở phần nào của bài nói."),
      table(
        ["Mục đích", "Cụm từ"],
        ["Mở đầu", "Today I'd like to talk about… / I've divided my talk into three parts."],
        ["Chuyển ý", "Moving on to… / Let's now turn to…"],
        ["Nhấn mạnh", "What's important here is… / I'd like to highlight…"],
        ["Kết thúc", "To sum up… / Thank you for listening. Are there any questions?"],
      ),
      tip("Khi chỉ vào slide, nói **As you can see on this slide…** thay vì **You see this slide**. Nghe tự nhiên và chuyên nghiệp hơn nhiều."),
      tip("Khi nói, mệnh đề không xác định được đọc như một **lời chen vào**: ngừng nhẹ ở dấu phẩy thứ nhất, hạ giọng khi đọc phần thông tin thêm, rồi ngừng nhẹ trước khi quay lại câu chính. **Our team, (ngừng) which has twelve members, (ngừng) works in three countries.**"),
      teacher("Tôi đã ngồi nghe hàng nghìn bài thuyết trình của học trò. Bài nào cũng có đủ ý, nhưng bài hay là bài **người nghe biết mình đang ở đâu**. Vì vậy, hãy viết sẵn bốn câu dẫn dắt: mở đầu, chuyển ý, nhấn mạnh, kết thúc, và tập nói to chúng trước gương. Nội dung bạn có thể quên, nhưng bốn câu ấy sẽ giữ bạn không lạc. Và đừng đọc slide: slide để người nghe nhìn, còn bạn nói câu dài hơn, có mệnh đề quan hệ để giải thích."),
      summary(
        "**Who** cho người, **which** cho vật, **whose + danh từ** chỉ sở hữu, **that** chỉ dùng trong mệnh đề xác định.",
        "Mệnh đề **không xác định** đứng giữa hai dấu phẩy, chỉ thêm thông tin, và **không dùng that**.",
        "Đại từ quan hệ đã thay cho danh từ, nên **không lặp lại** it, him, them trong mệnh đề.",
        "Động từ trong mệnh đề chia theo danh từ đứng trước: customers who **buy**, a customer who **buys**.",
        "Dẫn dắt người nghe: **Today I'd like to talk about…**, **Moving on to…**, **What's important here is…**, **To sum up…**",
      ),
    ],
  },
  words: [
    word("audience", "/ˈɔː.di.əns/", "khán giả, người nghe", "Try to make eye contact with your audience.", "au|di|ence", 0),
    word("highlight", "/ˈhaɪ.laɪt/", "làm nổi bật, nhấn mạnh", "I'd like to highlight three key results.", "high|light", 0),
    word("illustrate", "/ˈɪl.ə.streɪt/", "minh họa", "This graph illustrates our sales trend.", "il|lus|trate", 0, "Trọng âm ở âm tiết đầu: IL-lus-trate."),
    word("revenue", "/ˈrev.ən.juː/", "doanh thu", "Revenue rose by ten per cent last quarter.", "rev|e|nue", 0),
    word("conclusion", "/kənˈkluː.ʒən/", "phần kết luận", "In conclusion, the project was a success.", "con|clu|sion", 1),
    word("overview", "/ˈəʊ.və.vjuː/", "cái nhìn tổng quan", "Let me start with a brief overview.", "o|ver|view", 0),
    word("slide", "/slaɪd/", "trang trình chiếu", "As you can see on this slide, costs have fallen.", "slide", 0, "Nhớ bật âm /d/ ở cuối."),
  ],
  exercises: [
    mc("b2-5-1", "Our director, ___ joined the company last year, will open the conference.", ["that", "who", "which"], 1, "Mệnh đề không xác định (giữa hai dấu phẩy) nói về người thì dùng who. Không dùng that sau dấu phẩy, còn which chỉ dùng cho vật."),
    reorder("b2-5-2", "We chose a partner whose experience is excellent.", "Whose chỉ sở hữu: kinh nghiệm của đối tác. Sau whose là danh từ, rồi mới đến động từ."),
    mc("b2-5-3", "Which sentence is punctuated correctly?", ["My boss, who lives in Da Nang, is visiting us.", "My boss who lives in Da Nang, is visiting us.", "My boss, that lives in Da Nang, is visiting us."], 0, "Mệnh đề không xác định đặt giữa hai dấu phẩy và dùng who, không dùng that."),
    fill("b2-5-4", "The new app, ___ was launched last month, has ten thousand users.", ["which"], "Sau dấu phẩy, chỉ vật dùng which."),
    fill("b2-5-5", "Now let's ___ to the second part of my presentation. (chuyển sang)", ["turn", "move", "go", "come", "proceed"], "Let's turn to / Let's move on to (hoặc go to, come to): chuyển sang phần tiếp theo."),
    reorder("b2-5-6", "I've divided my talk into three parts.", "Câu mở đầu giới thiệu bố cục bài thuyết trình."),
    listen("b2-5-7", "To sum up, our revenue has grown steadily.", ["Tóm lại, doanh thu của chúng ta đã tăng đều đặn.", "Trước hết, doanh thu của chúng ta giảm mạnh.", "Doanh thu của chúng ta cần tăng nhanh hơn."], 0, "To sum up dùng để tóm tắt ở phần kết."),
    listen("b2-5-8", "This is the client whose order we delayed.", ["Đây là khách hàng đã hủy đơn hàng.", "Đây là khách hàng có đơn hàng bị chúng ta giao chậm.", "Đây là khách hàng đã giao hàng chậm."], 1),
  ],
  speaking: [
    say("Today I'd like to talk about our results for this year.", "Hôm nay tôi muốn nói về kết quả năm nay của chúng ta."),
    say("Our team, which has twelve members, works in three countries.", "Nhóm của chúng tôi, gồm mười hai thành viên, làm việc ở ba quốc gia."),
    say("Thank you for listening. Are there any questions?", "Cảm ơn mọi người đã lắng nghe. Có ai có câu hỏi không?"),
  ],
  dialogue: dialogue(
    "Tập thuyết trình trước buổi họp ban giám đốc",
    "Ngày mai chị Hà thuyết trình về sản phẩm mới trước ban giám đốc. Chị nhờ anh Peter, đồng nghiệp người Úc, nghe thử và góp ý.",
    { A: "Hà, chuyên viên tiếp thị", B: "Peter, đồng nghiệp" },
    A("Peter, could you listen to my opening? I'm presenting to the board tomorrow.", "Peter, anh nghe thử phần mở đầu của em được không? Mai em thuyết trình trước ban giám đốc."),
    B("Sure, go ahead.", "Được chứ, em bắt đầu đi."),
    A("Good morning. Today I'd like to talk about our new water filter, which we launched in Da Nang in May.", "Chào buổi sáng. Hôm nay tôi muốn nói về máy lọc nước mới, sản phẩm chúng ta ra mắt ở Đà Nẵng hồi tháng Năm."),
    B("Nice. One sentence instead of three short ones. It sounds much smoother.", "Hay đấy. Một câu thay cho ba câu ngắn. Nghe trôi chảy hơn nhiều."),
    A("Then I say: I've divided my talk into three parts: sales, customer feedback and next steps.", "Sau đó em nói: Tôi chia bài nói thành ba phần: doanh số, phản hồi của khách hàng và bước tiếp theo."),
    B("Very clear. Who are the customers that bought it first?", "Rất rõ ràng. Những khách hàng mua đầu tiên là ai?"),
    A("Mostly young families whose children have allergies. As you can see on this slide, they make up sixty per cent of buyers.", "Chủ yếu là các gia đình trẻ có con bị dị ứng. Như mọi người thấy trên trang này, họ chiếm sáu mươi phần trăm người mua."),
    B("Good. And what's the key result?", "Tốt. Còn kết quả chính là gì?"),
    A("What's important here is that our revenue, which was flat last year, has grown by twenty per cent.", "Điều quan trọng ở đây là doanh thu của chúng ta, vốn đi ngang năm ngoái, đã tăng hai mươi phần trăm."),
    B("Great. Just pause a little at the commas. How do you finish?", "Tuyệt. Chỉ cần ngừng nhẹ ở các dấu phẩy. Em kết thúc thế nào?"),
    A("To sum up, the product is selling well, and we'd like to open two more stores. Thank you for listening. Are there any questions?", "Tóm lại, sản phẩm đang bán chạy và chúng tôi muốn mở thêm hai cửa hàng. Cảm ơn mọi người đã lắng nghe. Có ai có câu hỏi không?"),
    B("That's perfect. You'll be fine tomorrow.", "Hoàn hảo. Mai em sẽ làm tốt thôi."),
  ),
  task: task({
    prompt: "Viết phần mở đầu và đoạn đầu tiên của một bài thuyết trình ngắn giới thiệu công ty, sản phẩm hoặc dự án của bạn. Bài phải có câu giới thiệu chủ đề, câu nêu bố cục, vài câu có mệnh đề quan hệ và các cụm dẫn dắt.",
    hints: [
      "Mở đầu: Good morning, everyone. Today I'd like to talk about… rồi I've divided my talk into… parts.",
      "Gộp các câu ngắn bằng who, which, whose; thông tin thêm thì đặt giữa hai dấu phẩy.",
      "Dùng Let's start with…, What's important here is…, Moving on to… để người nghe biết bạn đang ở đâu.",
    ],
    model: "Good morning, everyone. Today I'd like to talk about Green Leaf, a small tea company which I started with two friends in 2021. I've divided my talk into three parts: our products, our customers and our plans. Let's start with our products. Our best seller is a jasmine tea that comes from farms in Thai Nguyen. Our customers, who are mostly office workers, buy it online. What's important here is that we work with farmers whose families have grown tea for generations. Moving on to our plans, we would like to open a shop in Hanoi next year.",
    checklist: [
      "Có câu giới thiệu chủ đề và một câu nêu bố cục bài nói.",
      "Có ít nhất ba mệnh đề quan hệ, trong đó có một mệnh đề không xác định giữa hai dấu phẩy.",
      "Không dùng that sau dấu phẩy và không lặp lại it, them trong mệnh đề quan hệ.",
      "Động từ trong mệnh đề quan hệ chia đúng theo danh từ đứng trước.",
      "Có ít nhất hai cụm dẫn dắt (Let's start with, Moving on to, What's important here is…).",
    ],
    minWords: 70,
  }),
});

const damPhan = lesson({
  slug: "dam-phan-va-thuyet-phuc",
  title: "Đàm phán và thuyết phục",
  minutes: 24,
  lecture: {
    title: "Ngôn ngữ mềm, đề xuất và nhượng bộ",
    blocks: [
      p("Anh Nam, trưởng nhóm kinh doanh ở TP.HCM, ngồi đàm phán với một nhà cung cấp Singapore. Anh mở lời: **Your price is too high. We want ten per cent discount.** Không khí lập tức căng thẳng, và đối phương không nhượng bộ đồng nào. Cùng yêu cầu ấy, nếu anh nói **We were wondering if you could be a little more flexible on price**, cuộc nói chuyện đã khác hẳn. Trong đàm phán, **cách nói** quyết định không kém **điều bạn nói**."),
      p("Người Việt khi đàm phán bằng tiếng Anh hay dùng câu quá thẳng như **We want a lower price.** Người nghe có thể thấy bạn thiếu thiện chí. Hãy **nói giảm, nói mềm** bằng cách dùng thì quá khứ tiếp diễn, động từ khuyết thiếu và từ giảm nhẹ."),
      table(
        ["Câu thẳng", "Câu mềm hơn"],
        ["We want a discount.", "We were wondering if you could offer a discount."],
        ["Your price is too high.", "Your price seems a little high for us."],
        ["Deliver it next week.", "Would you be willing to deliver it next week?"],
        ["That's impossible.", "I'm afraid that might be difficult for us."],
      ),
      table(
        ["Kỹ thuật làm mềm", "Cách dùng", "Ví dụ"],
        ["Quá khứ tiếp diễn", "I was wondering if…", "I was wondering if you could help."],
        ["Động từ khuyết thiếu", "could, might, would", "That might be a problem."],
        ["Từ giảm nhẹ", "a little, slightly, quite", "The price is slightly higher than we expected."],
        ["Lời rào đón", "I'm afraid…, To be honest…", "I'm afraid we can't accept that."],
      ),
      ex("I was wondering if we could extend the deadline.", "Tôi đang băn khoăn không biết chúng ta có thể lùi hạn chót được không.", "Quá khứ tiếp diễn “was wondering” làm lời đề nghị nhẹ nhàng hơn, không mang nghĩa quá khứ."),
      ex("Would you be willing to consider a two-year contract?", "Anh/chị có sẵn lòng cân nhắc một hợp đồng hai năm không?"),
      p("Khi đưa ra **đề xuất có điều kiện**, dùng **If you…, we could/would…** hoặc **provided that / as long as**, những từ các bạn đã học ở bài **Điều kiện không chỉ có if**. Khi **nhượng bộ**, dùng **We're prepared to… if…** để luôn đổi lại một điều có lợi."),
      ex("If you order five hundred units, we could offer a ten per cent discount.", "Nếu quý công ty đặt năm trăm sản phẩm, chúng tôi có thể giảm giá mười phần trăm.", "Vế if dùng hiện tại đơn, vế chính dùng could để lời đề xuất nghe như một khả năng, chưa phải lời hứa chắc chắn."),
      ex("We're prepared to lower the price, provided that you pay within thirty days.", "Chúng tôi sẵn sàng giảm giá, với điều kiện quý công ty thanh toán trong vòng ba mươi ngày.", "Nhượng bộ nhưng luôn kèm điều kiện. Provided that trang trọng hơn if một chút."),
      mistake("I was wondering if could you lower the price.", "I was wondering if you could lower the price.", "Sau “I was wondering if” là trật tự câu kể: chủ ngữ đứng trước động từ, không đảo như câu hỏi. Người Việt nghĩ đây là câu hỏi nên đảo could lên trước."),
      mistake("We will agree provided that you will pay in advance.", "We will agree provided that you pay in advance.", "Sau provided that / as long as dùng thì hiện tại đơn khi nói về tương lai, giống mệnh đề if. Tiếng Việt thêm “sẽ” ở cả hai vế nên người học hay thêm will vào cả hai."),
      mistake("We very want to cooperate with you.", "We would very much like to work with you.", "Dịch từng chữ “chúng tôi rất muốn”. Very không đứng trước động từ; hãy dùng would very much like to hoặc are very keen to."),
      table(
        ["Giai đoạn", "Cụm từ"],
        ["Thăm dò", "How flexible can you be on the price? / What would you say to a two-year contract?"],
        ["Gặp nhau ở giữa", "Could we meet you halfway? / Let's split the difference."],
        ["Chốt thỏa thuận", "So, to confirm, we've agreed on… / I'll put that in writing and send it to you today."],
      ),
      tip("Đừng từ chối bằng **No.** trơn. Hãy mở đầu bằng **I see your point, but…** hoặc **I'm afraid we can't…, but we could…** để giữ không khí hợp tác."),
      teacher("Học trò đi làm hay hỏi tôi: nói mềm như vậy có bị coi là yếu thế không? Không đâu. Kinh nghiệm của tôi là **mềm ở lời, chắc ở điều kiện**. Bạn có thể nói rất lịch sự, nhưng mỗi lần nhượng bộ phải đổi lấy một điều: **We could…, if you…** Trước mỗi buổi đàm phán, hãy viết ra ba câu đề xuất có điều kiện và một câu từ chối lịch sự, rồi tập nói đến khi trôi chảy. Chuẩn bị kỹ thì lúc căng thẳng bạn mới không quay về câu cộc lốc."),
      summary(
        "Làm mềm yêu cầu: **I was wondering if + S + could…**, **Would you be willing to + V?**, thêm **a little, slightly**.",
        "Sau I was wondering if là **trật tự câu kể**: if you could, không phải if could you.",
        "Đề xuất có điều kiện: **If you + hiện tại đơn, we could…**; nhượng bộ: **We're prepared to…, provided that / as long as + hiện tại đơn**.",
        "Từ chối lịch sự: **I'm afraid we can't…, but we could…**; ghi nhận ý kiến: **I see your point, but…**",
        "**Mềm ở lời, chắc ở điều kiện**: mỗi lần nhượng bộ phải đổi lấy một điều có lợi.",
      ),
    ],
  },
  words: [
    word("negotiate", "/nəˈɡəʊ.ʃi.eɪt/", "đàm phán", "We need to negotiate better terms with the supplier.", "ne|go|ti|ate", 1),
    word("compromise", "/ˈkɒm.prə.maɪz/", "sự thỏa hiệp", "Both sides had to make a compromise.", "com|pro|mise", 0),
    word("discount", "/ˈdɪs.kaʊnt/", "sự giảm giá", "Could you offer a discount for bulk orders?", "dis|count", 0),
    word("contract", "/ˈkɒn.trækt/", "hợp đồng", "The contract will be signed next week.", "con|tract", 0, "Danh từ nhấn âm đầu: CON-tract. Động từ “contract” (co lại) nhấn âm sau."),
    word("flexible", "/ˈflek.sə.bəl/", "linh hoạt", "We can be flexible on the delivery date.", "flex|i|ble", 0),
    word("proposal", "/prəˈpəʊ.zəl/", "bản đề xuất", "They accepted our proposal after a long discussion.", "pro|pos|al", 1),
    word("concession", "/kənˈseʃ.ən/", "sự nhượng bộ", "We made a small concession on price.", "con|ces|sion", 1),
    word("deal", "/diːl/", "thỏa thuận, giao dịch", "I think we have a deal.", "deal", 0),
  ],
  exercises: [
    mc("b2-6-1", "Which request is the most polite?", ["Give us a better price.", "We want a better price now.", "We were wondering if you could improve your price.", "Your price is bad."], 2, "Was wondering if + S + could là cách đề nghị rất mềm mỏng."),
    mc("b2-6-2", "We can deliver next week as long as you ___ the order today.", ["will confirm", "confirm", "would confirm"], 1, "Sau as long as dùng hiện tại đơn khi nói về tương lai."),
    fill("b2-6-3", "Would you be ___ to share the costs? (sẵn lòng)", ["willing", "prepared", "happy", "able"], "Would you be willing / prepared / happy to + V: anh/chị có sẵn lòng…? (Would you be able to: anh/chị có thể…?)"),
    fill("b2-6-4", "I'm ___ that we can't accept those terms.", ["afraid", "sorry"], "I'm afraid… (hoặc I'm sorry…) giúp lời từ chối bớt gay gắt."),
    reorder("b2-6-5", "I was wondering if you could lower the price.", "Sau I was wondering if là trật tự câu kể: you đứng trước could, không đảo như câu hỏi."),
    reorder("b2-6-6", "We are prepared to offer a small discount.", "Be prepared to + V: sẵn sàng làm gì, thường dùng khi nhượng bộ."),
    listen("b2-6-7", "I see your point, but we need a longer contract.", ["Tôi hoàn toàn đồng ý với anh/chị.", "Chúng tôi không cần hợp đồng dài hạn.", "Tôi muốn xem lại bản hợp đồng.", "Tôi hiểu ý anh/chị, nhưng chúng tôi cần một hợp đồng dài hơn."], 3, "I see your point, but… vừa ghi nhận ý kiến đối phương vừa đưa ra quan điểm của mình."),
    listen("b2-6-8", "Would you be willing to pay half in advance?", ["Anh/chị có sẵn lòng trả trước một nửa không?", "Anh/chị đã trả trước một nửa chưa?", "Chúng tôi sẽ trả trước một nửa."], 0),
  ],
  speaking: [
    say("I was wondering if you could offer a small discount.", "Tôi đang nghĩ liệu anh/chị có thể giảm giá một chút không."),
    say("If you order two hundred units, we could deliver for free.", "Nếu anh/chị đặt hai trăm sản phẩm, chúng tôi có thể giao hàng miễn phí."),
    say("I see your point, but we need more time.", "Tôi hiểu ý anh/chị, nhưng chúng tôi cần thêm thời gian."),
  ],
  dialogue: dialogue(
    "Đàm phán giá với nhà cung cấp",
    "Anh Nam, trưởng nhóm mua hàng ở TP.HCM, đàm phán với ông Lim, đại diện nhà cung cấp Singapore, về giá và điều khoản của một đơn hàng ghế văn phòng.",
    { A: "Nam, trưởng nhóm mua hàng", B: "Mr Lim, nhà cung cấp" },
    A("Thank you for your proposal, Mr Lim. To be honest, your price seems a little high for us.", "Cảm ơn ông về bản đề xuất. Thật lòng mà nói, mức giá của ông hơi cao so với chúng tôi."),
    B("I see your point, but our chairs are of the best quality in the region.", "Tôi hiểu ý anh, nhưng ghế của chúng tôi có chất lượng tốt nhất khu vực."),
    A("We don't doubt that. We were wondering if you could offer a ten per cent discount.", "Chúng tôi không nghi ngờ điều đó. Chúng tôi đang băn khoăn liệu ông có thể giảm giá mười phần trăm không."),
    B("I'm afraid ten per cent might be difficult for us. How many units are you planning to order?", "Tôi e rằng mười phần trăm hơi khó cho chúng tôi. Anh định đặt bao nhiêu chiếc?"),
    A("About five hundred units in the first year.", "Khoảng năm trăm chiếc trong năm đầu."),
    B("In that case, if you order five hundred units, we could offer six per cent.", "Nếu vậy, nếu anh đặt năm trăm chiếc, chúng tôi có thể giảm sáu phần trăm."),
    A("Could we meet you halfway at eight per cent?", "Chúng ta gặp nhau ở giữa, tám phần trăm được không?"),
    B("We're prepared to accept eight per cent, provided that you sign a two-year contract.", "Chúng tôi sẵn sàng chấp nhận tám phần trăm, với điều kiện anh ký hợp đồng hai năm."),
    A("That sounds reasonable. Would you be willing to deliver the first order by March?", "Nghe hợp lý. Ông có sẵn lòng giao đơn đầu tiên trước tháng Ba không?"),
    B("Yes, as long as you confirm the order this week.", "Được, miễn là anh xác nhận đơn hàng trong tuần này."),
    A("Great. So, to confirm, we've agreed on eight per cent, a two-year contract and delivery by March.", "Tuyệt. Vậy để xác nhận, chúng ta đã thống nhất giảm tám phần trăm, hợp đồng hai năm và giao hàng trước tháng Ba."),
    B("Exactly. I'll put that in writing and send it to you today.", "Chính xác. Tôi sẽ ghi lại bằng văn bản và gửi anh ngay hôm nay."),
  ),
  task: task({
    prompt: "Viết email gửi nhà cung cấp để đàm phán về báo giá họ vừa gửi: làm mềm lời đề nghị giảm giá, đưa ra một đề xuất có điều kiện, và từ chối lịch sự một điều khoản bạn không chấp nhận được (kèm phương án thay thế).",
    hints: [
      "Mở lời mềm: To be honest, the price seems slightly higher than we expected.",
      "Đề nghị bằng We were wondering if you could… (chủ ngữ đứng trước could).",
      "Đề xuất có điều kiện: If you…, we could… hoặc We are prepared to…, provided that…",
      "Từ chối: I'm afraid we can't…, but we could…",
    ],
    model: "Dear Mr Lim,\n\nThank you for your quotation for the office chairs. To be honest, the price seems slightly higher than we expected. We were wondering if you could be a little more flexible. If you offer a seven per cent discount, we could increase our order to three hundred units. I'm afraid we can't pay the full amount in advance, but we are prepared to pay within fifteen days, provided that the chairs arrive before 1 June.\n\nI look forward to hearing from you.\n\nKind regards,\nTran Hoang Nam",
    checklist: [
      "Không có câu yêu cầu thẳng như We want… hay Your price is too high.",
      "Có ít nhất một câu I/We were wondering if + chủ ngữ + could, đúng trật tự câu kể.",
      "Có một đề xuất có điều kiện dạng If you…, we could…",
      "Có một lời từ chối lịch sự bằng I'm afraid… kèm phương án thay thế.",
      "Sau provided that và as long as dùng hiện tại đơn, không dùng will.",
    ],
    minWords: 70,
  }),
});

export const tiengAnhB2: Course = {
  slug: "tieng-anh-b2",
  title: "Tiếng Anh B2: Tiếng Anh công việc",
  level: "B2",
  goal: "lo-trinh",
  summary: "Cho người đi làm: viết email, họp, thuyết trình và đàm phán bằng tiếng Anh tự tin, đúng văn phong công sở.",
  outcomes: [
    "Viết email công việc trang trọng, lịch sự và rõ ràng",
    "Tham gia họp, suy đoán, xen ngang và hỏi lại một cách khéo léo",
    "Tường thuật lời người khác và rút kinh nghiệm bằng câu điều kiện",
    "Thuyết trình mạch lạc và đàm phán bằng ngôn ngữ mềm mỏng",
  ],
  audience: [
    "Người đi làm cần dùng tiếng Anh với đồng nghiệp, khách hàng hoặc đối tác nước ngoài",
    "Người đã học xong B1 muốn nâng tiếng Anh lên mức làm việc chuyên nghiệp",
  ],
  teacher: {
    name: "Thầy Michael Grant",
    initials: "MG",
    bio: "12 năm giảng dạy tiếng Anh thương mại, thạc sĩ TESOL. Từng đào tạo nhân viên cho nhiều doanh nghiệp đa quốc gia tại TP.HCM.",
  },
  durationWeeks: 16,
  rating: 4.9,
  reviews: [
    { name: "Thu Trang", role: "Chuyên viên xuất nhập khẩu, Hải Phòng", quote: "Trước đây email của mình toàn câu mệnh lệnh mà không biết. Sau bài đầu tiên, đối tác phản hồi nhanh và thân thiện hơn hẳn." },
    { name: "Hoàng Nam", role: "Trưởng nhóm kinh doanh, TP.HCM", quote: "Phần đàm phán rất thực tế. Mình áp dụng ngay các mẫu câu nói giảm trong buổi họp với khách hàng Singapore." },
  ],
  faqs: [
    { q: "Mình cần trình độ nào để học khóa B2?", a: "Bạn nên nắm chắc ngữ pháp B1 như thì hiện tại hoàn thành, câu bị động và câu điều kiện loại 1, 2. Nếu chưa chắc, hãy làm bài kiểm tra xếp lớp trước." },
    { q: "Học xong B2 thì học gì tiếp?", a: "Bạn học tiếp khóa C1 để luyện diễn đạt tinh tế, học thuật và tự nhiên như người bản xứ. Mỗi cấp có chứng chỉ riêng." },
  ],
  status: "open",
  modules: [
    chapter(1, "Giao tiếp nơi công sở", [vietEmail, hopThaoLuan, tuongThuat, nGoiDienVaHopTrucTuyen]),
    chapter(2, "Giả định và tiếc nuối", [tiecNuoi, nDieuKienNangCao, nDongTuKhuyetThieuQuaKhu, nGiaDinhKhongThat]),
    chapter(3, "Trình bày và viết", [thuyetTrinh, nMoTaSoLieu, nTuNoiNangCao, nRutGonMenhDe]),
    chapter(4, "Thuyết phục và xử lý tình huống", [damPhan, nMaoTu, nToVHayVIng, nThanPhienVaXuLy]),
  ],
};
