import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, tip, word } from "../builders";
import type { Course } from "../types";

const noiTuNhien = lesson({
  slug: "noi-tu-nhien",
  title: "Nói tự nhiên như người bản xứ",
  minutes: 20,
  lecture: {
    title: "Cụm động từ và kết hợp từ tự nhiên",
    blocks: [
      p("Nhiều người học trình độ cao nói đúng ngữ pháp nhưng vẫn nghe “sách vở”. Lý do chính: dùng từ đơn trang trọng thay vì **phrasal verb** (cụm động từ), và ghép từ theo kiểu dịch từ tiếng Việt thay vì theo **collocation** (kết hợp từ cố định)."),
      table(
        ["Loại", "Ví dụ", "Vị trí tân ngữ", "Ghi chú"],
        ["Tách được (separable)", "put off, turn down, figure out", "put the meeting off / put it off", "Đại từ bắt buộc đứng giữa"],
        ["Không tách được (inseparable)", "look after, come across, run into", "look after the kids / look after them", "Tân ngữ luôn đứng sau tiểu từ"],
        ["Ba thành phần", "put up with, come up with, look forward to", "put up with the noise / put up with it", "Thường không tách được"],
      ),
      p("Quy tắc vàng: với phrasal verb tách được, nếu tân ngữ là **đại từ** (it, them, him), đại từ phải chen vào **giữa** động từ và tiểu từ."),
      mistake("Can you turn down it?", "Can you turn it down?", "Với phrasal verb tách được, đại từ phải đứng giữa động từ và tiểu từ."),
      ex("I came across an old photo while I was clearing out the attic.", "Tôi tình cờ thấy một bức ảnh cũ khi đang dọn gác mái.", "come across không tách được, nên không nói come an old photo across."),
      p("Collocation là những từ người bản xứ quen dùng cùng nhau. Tiếng Việt nói “mưa to”, nhưng tiếng Anh nói **heavy rain**, không nói big rain. Phân biệt **make** và **do** cũng là lỗi rất phổ biến của người Việt, vì cả hai đều dịch là “làm”."),
      table(
        ["Nhóm", "Kết hợp tự nhiên", "Tránh dùng"],
        ["make", "make a decision, make progress, make an effort", "do a decision, do an effort"],
        ["do", "do research, do damage, do someone a favour", "make research, make a favour"],
        ["take", "take a risk, take responsibility, take something into account", "make a risk"],
        ["tính từ + danh từ", "heavy rain, strong coffee, a high chance", "big rain, thick coffee, a big chance"],
      ),
      ex("We need to take the budget into account before we make a final decision.", "Chúng ta cần tính đến ngân sách trước khi đưa ra quyết định cuối cùng."),
      mistake("Our team did a big progress this quarter.", "Our team made significant progress this quarter.", "Progress đi với make và là danh từ không đếm được nên không có a. Big progress nghe không tự nhiên; hãy dùng significant hoặc considerable."),
      tip("Khi học từ mới, hãy ghi cả cụm, ví dụ **make a decision** thay vì chỉ **decision**. Trước khi viết email quan trọng, tra từ điển collocation để kiểm tra từ nào thường đi với từ nào."),
    ],
  },
  words: [
    word("collocation", "/ˌkɒl.əˈkeɪ.ʃən/", "kết hợp từ (các từ thường đi cùng nhau)", "Heavy rain is a common collocation in English.", "col|lo|ca|tion", 2),
    word("idiomatic", "/ˌɪd.i.əˈmæt.ɪk/", "tự nhiên, đúng kiểu người bản xứ", "Her English is fluent and highly idiomatic.", "id|i|o|mat|ic", 3),
    word("inseparable", "/ɪnˈsep.ər.ə.bəl/", "không thể tách rời", "Look after is an inseparable phrasal verb.", "in|sep|a|ra|ble", 1),
    word("postpone", "/pəʊstˈpəʊn/", "hoãn lại", "The board decided to postpone the launch until spring.", "post|pone", 1, "Đây là cách nói trang trọng của put off. Trong hội thoại, người bản xứ hay nói put off hơn."),
    word("tolerate", "/ˈtɒl.ər.eɪt/", "chịu đựng, dung thứ", "I won't tolerate rudeness in meetings.", "tol|er|ate", 0, "Trang trọng hơn put up with."),
    word("substantial", "/səbˈstæn.ʃəl/", "đáng kể, lớn", "The new policy made a substantial difference to staff morale.", "sub|stan|tial", 1),
    word("overlook", "/ˌəʊ.vəˈlʊk/", "bỏ sót, không để ý tới", "It's easy to overlook small errors when you're tired.", "o|ver|look", 2),
  ],
  exercises: [
    mc("c1-1-1", "Chọn câu đúng.", ["Could you turn down it?", "Could you turn it down?", "Could you it turn down?"], 1, "Turn down tách được, nên đại từ it phải đứng giữa: turn it down."),
    mc("c1-1-2", "Scientists are ___ research into the effects of sleep deprivation.", ["making", "taking", "doing"], 2, "Research đi với do (hoặc carry out), không đi với make."),
    fill("c1-1-3", "I can't put up ___ his constant complaining any longer.", ["with"], "Put up with là cụm ba thành phần, nghĩa là chịu đựng."),
    fill("c1-1-4", "Investing all your savings in one company means ___ a huge risk.", ["taking", "running"], "Tiếng Anh nói take a risk hoặc run a risk, không nói make a risk."),
    reorder("c1-1-5", "She came up with a brilliant solution.", "Come up with nghĩa là nghĩ ra, và không bao giờ tách."),
    reorder("c1-1-6", "Could you look after my plants for me?", "Look after không tách được: tân ngữ my plants đứng sau after."),
    listen("c1-1-7", "We were caught in heavy rain on the way home.", ["Chúng tôi về nhà trước khi trời mưa.", "Trời mưa nên chúng tôi ở nhà.", "Chúng tôi gặp mưa to trên đường về nhà."], 2, "Heavy rain là mưa to; be caught in the rain là bị mắc mưa."),
    listen("c1-1-8", "I ran into an old colleague at the conference.", ["Tôi chạy đến chỗ một đồng nghiệp cũ ở hội nghị.", "Tôi tình cờ gặp một đồng nghiệp cũ ở hội nghị.", "Tôi va phải một đồng nghiệp cũ ở hội nghị."], 1, "Run into someone nghĩa là tình cờ gặp ai đó."),
  ],
  speaking: [
    say("I'll look into it and get back to you tomorrow.", "Tôi sẽ xem xét việc này và phản hồi bạn vào ngày mai."),
    say("We need to make a decision before we take any more risks.", "Chúng ta cần đưa ra quyết định trước khi chấp nhận thêm rủi ro."),
    say("I can't put up with this noise any longer.", "Tôi không thể chịu đựng tiếng ồn này thêm nữa."),
  ],
});

const daoNgu = lesson({
  slug: "dao-ngu-de-nhan-manh",
  title: "Đảo ngữ để nhấn mạnh",
  minutes: 22,
  lecture: {
    title: "Đảo ngữ phủ định",
    blocks: [
      p("Khi một trạng từ mang nghĩa phủ định hoặc hạn chế (**never**, **rarely**, **seldom**, **hardly**, **little**, **not only**, **only after**) được đưa lên đầu câu, trợ động từ phải đứng **trước** chủ ngữ, giống cấu trúc câu hỏi. Cách này tạo sức nặng và kịch tính, thường gặp trong văn viết, diễn văn và bài thi IELTS."),
      table(
        ["Cấu trúc", "Câu thường", "Câu đảo ngữ"],
        ["Never", "I have never seen such chaos.", "Never have I seen such chaos."],
        ["Rarely / Seldom", "We rarely get feedback this detailed.", "Rarely do we get feedback this detailed."],
        ["Not only ... but also", "She not only wrote the report but also presented it.", "Not only did she write the report, but she also presented it."],
        ["Hardly ... when", "I had hardly sat down when the phone rang.", "Hardly had I sat down when the phone rang."],
        ["No sooner ... than", "He had no sooner arrived than he was asked to leave.", "No sooner had he arrived than he was asked to leave."],
        ["Only after", "We understood the problem only after the audit.", "Only after the audit did we understand the problem."],
        ["Little", "I didn't realise how serious it was.", "Little did I realise how serious it was."],
      ),
      p("Hai điểm người Việt hay sai. Thứ nhất, câu ở thì hiện tại đơn và quá khứ đơn phải **mượn do/does/did**, và động từ chính trở về nguyên mẫu (riêng động từ be thì đảo trực tiếp: Never was I so nervous). Thứ hai, với **Only after**, **Only when** và **Not until**, đảo ngữ nằm ở **mệnh đề chính**, không nằm ở mệnh đề đi ngay sau only."),
      mistake("Rarely we see such dedication.", "Rarely do we see such dedication.", "Sau trạng từ phủ định ở đầu câu phải đảo trợ động từ lên trước chủ ngữ; thì hiện tại đơn thì mượn do."),
      mistake("Only after he left did I realised my mistake.", "Only after he left did I realise my mistake.", "Đã có did thì động từ chính phải ở nguyên mẫu. Đảo ngữ nằm ở mệnh đề chính (did I realise), không đảo ở he left."),
      ex("No sooner had we launched the product than competitors began to copy it.", "Chúng tôi vừa ra mắt sản phẩm thì đối thủ đã bắt đầu sao chép.", "Hardly đi với when, No sooner đi với than. Đừng trộn lẫn hai cặp này."),
      ex("Not only does the plan save money, but it also reduces waste.", "Kế hoạch này không chỉ tiết kiệm tiền mà còn giảm lãng phí."),
      ex("Seldom have I worked with such a committed team.", "Hiếm khi tôi được làm việc với một đội tận tâm như vậy.", "Thì hiện tại hoàn thành đã có have nên chỉ cần đảo have lên trước I."),
      tip("Về **register** (văn phong): đảo ngữ nghe trang trọng và mạnh. Trong bài luận hay bài phát biểu, dùng một hai lần là đủ gây ấn tượng. Trong trò chuyện thường ngày, dùng quá nhiều sẽ nghe như đang **đọc diễn văn**."),
    ],
  },
  words: [
    word("inversion", "/ɪnˈvɜː.ʃən/", "sự đảo ngữ", "Negative inversion adds weight to a formal argument.", "in|ver|sion", 1),
    word("emphasis", "/ˈem.fə.sɪs/", "sự nhấn mạnh", "The speaker placed great emphasis on transparency.", "em|pha|sis", 0, "Danh từ đi với on (place emphasis on), nhưng động từ emphasise không có on: emphasise the point."),
    word("seldom", "/ˈsel.dəm/", "hiếm khi", "Seldom have I met such a dedicated team.", "sel|dom", 0),
    word("scarcely", "/ˈskeəs.li/", "vừa mới, hầu như không", "Scarcely had the meeting begun when the power went out.", "scarce|ly", 0),
    word("unprecedented", "/ʌnˈpres.ɪ.den.tɪd/", "chưa từng có tiền lệ", "The company faced unprecedented demand last year.", "un|prec|e|dent|ed", 1),
    word("register", "/ˈredʒ.ɪ.stər/", "văn phong, mức độ trang trọng", "Inversion belongs to a formal register.", "reg|is|ter", 0),
    word("rhetorical", "/rɪˈtɒr.ɪ.kəl/", "thuộc về tu từ", "Inversion is a powerful rhetorical device.", "rhe|tor|i|cal", 1),
  ],
  exercises: [
    mc("c1-2-1", "Never ___ such a well-organised conference.", ["I have attended", "have I attended", "I attended", "did I attended"], 1, "Never đứng đầu câu nên phải đảo trợ động từ have lên trước I."),
    mc("c1-2-2", "No sooner had the train left ___ it started to snow.", ["when", "that", "than"], 2, "No sooner luôn đi với than; hardly và scarcely mới đi với when."),
    fill("c1-2-3", "Rarely ___ we receive complaints about this product.", ["do"], "Thì hiện tại đơn nên mượn do để đảo ngữ."),
    fill("c1-2-4", "Only after the results were published ___ the scientists realise their error.", ["did"], "Đảo ngữ ở mệnh đề chính; động từ realise ở nguyên mẫu nên cần did."),
    reorder("c1-2-5", "Little did we know that the company was about to collapse.", "Little + did + chủ ngữ + know/realise: nhấn mạnh rằng lúc đó hoàn toàn không hề biết."),
    reorder("c1-2-6", "Not only did she miss the deadline but she also lost the file.", "Not only + did + chủ ngữ + động từ nguyên mẫu, but + chủ ngữ + also + động từ quá khứ."),
    listen("c1-2-7", "Not until I moved abroad did I appreciate my hometown.", ["Tôi chưa bao giờ thích quê mình dù đã ra nước ngoài.", "Mãi đến khi ra nước ngoài sống, tôi mới trân trọng quê hương.", "Tôi chuyển ra nước ngoài vì không thích quê mình."], 1, "Not until... did I... nghĩa là mãi đến khi... tôi mới..."),
    listen("c1-2-8", "Seldom does the board approve a budget this large.", ["Hội đồng quản trị thường duyệt ngân sách lớn như vậy.", "Hội đồng quản trị đã từ chối ngân sách này.", "Hội đồng quản trị hiếm khi duyệt một ngân sách lớn như thế này."], 2, "Seldom nghĩa là hiếm khi, không phải thường xuyên."),
  ],
  speaking: [
    say("Never have I seen such a talented group of students.", "Tôi chưa bao giờ thấy một nhóm sinh viên tài năng như vậy."),
    say("Not only does this plan save time, but it also cuts costs.", "Kế hoạch này không chỉ tiết kiệm thời gian mà còn cắt giảm chi phí."),
    say("Only after the meeting did I understand the real problem.", "Chỉ sau cuộc họp tôi mới hiểu vấn đề thực sự."),
  ],
});

const cauChe = lesson({
  slug: "cau-che-va-nhan-manh",
  title: "Câu chẻ và nhấn mạnh",
  minutes: 20,
  lecture: {
    title: "Câu chẻ, do nhấn mạnh và đưa thành phần lên đầu câu",
    blocks: [
      p("Tiếng Việt nhấn mạnh bằng giọng hoặc bằng từ “chính”, “chính là”. Khi viết tiếng Anh, bạn cần công cụ ngữ pháp: **câu chẻ** (cleft sentence), **do nhấn mạnh** và **fronting** (đưa một thành phần lên đầu câu)."),
      p("**It-cleft**: It + be + phần cần nhấn mạnh + that/who + phần còn lại. Dùng khi muốn sửa lại thông tin hoặc làm nổi bật một chi tiết."),
      table(
        ["Câu gốc", "Muốn nhấn mạnh", "Câu nhấn mạnh"],
        ["Linh sent the report on Monday.", "Người gửi", "It was Linh who sent the report on Monday."],
        ["Linh sent the report on Monday.", "Thứ được gửi", "It was the report that Linh sent on Monday."],
        ["Linh sent the report on Monday.", "Thời gian", "It was on Monday that Linh sent the report."],
        ["I need more time.", "Điều mình cần (wh-cleft)", "What I need is more time."],
        ["The price worries me.", "Điều khiến mình lo (wh-cleft)", "What worries me is the price."],
        ["I didn't understand the problem until the meeting.", "Thời điểm (Not until)", "It was not until the meeting that I understood the problem."],
      ),
      p("**Wh-cleft**: What + mệnh đề + be + phần nhấn mạnh. Cấu trúc này rất hữu ích để mở đầu ý chính khi thuyết trình: What we need to focus on is..."),
      ex("It wasn't the price that put customers off; it was the poor service.", "Không phải giá cả khiến khách hàng ngần ngại, mà là dịch vụ kém.", "Cấu trúc It wasn't X... it was Y dùng để bác bỏ và sửa thông tin."),
      mistake("What I need it is a break.", "What I need is a break.", "Trong câu wh-cleft, mệnh đề What I need đã là chủ ngữ, không thêm it."),
      p("**Do nhấn mạnh**: thêm do/does/did trước động từ nguyên mẫu trong câu khẳng định để khẳng định mạnh hoặc phản bác điều người khác nghĩ."),
      ex("I did send the email. Please check your spam folder.", "Tôi đã gửi email thật mà. Bạn kiểm tra thư mục thư rác nhé."),
      mistake("She does works hard.", "She does work hard.", "Sau do/does/did nhấn mạnh, động từ trở về nguyên mẫu."),
      tip("**Fronting**: đưa tân ngữ lên đầu câu để tạo tương phản, ví dụ: Some of his ideas I agree with; others I find unrealistic. Cách này hay gặp trong **văn nói trang trọng** và bài luận."),
    ],
  },
  words: [
    word("emphatic", "/ɪmˈfæt.ɪk/", "dứt khoát, mang tính nhấn mạnh", "Her answer was an emphatic no.", "em|phat|ic", 1),
    word("contrast", "/ˈkɒn.trɑːst/", "sự tương phản", "The cleft sentence creates a sharp contrast between the two ideas.", "con|trast", 0, "Danh từ nhấn âm đầu, còn động từ nhấn âm sau: /kənˈtrɑːst/."),
    word("clarify", "/ˈklær.ɪ.faɪ/", "làm rõ", "Let me clarify what I meant.", "clar|i|fy", 0),
    word("highlight", "/ˈhaɪ.laɪt/", "làm nổi bật", "What I'd like to highlight is the cost.", "high|light", 0),
    word("misconception", "/ˌmɪs.kənˈsep.ʃən/", "quan niệm sai lầm", "It is a common misconception that grammar kills fluency.", "mis|con|cep|tion", 2),
    word("underlying", "/ˌʌn.dəˈlaɪ.ɪŋ/", "tiềm ẩn, nằm bên dưới", "What we need to address is the underlying cause.", "un|der|ly|ing", 2),
    word("crucial", "/ˈkruː.ʃəl/", "cực kỳ quan trọng", "What is crucial is that we act quickly.", "cru|cial", 0),
  ],
  exercises: [
    mc("c1-3-1", "Câu nào nhấn mạnh rằng chính Nam, không phải ai khác, đã phát hiện ra lỗi?", ["What Nam found was the error.", "Nam did find the error.", "It was Nam who found the error.", "The error was found by someone."], 2, "It was + người + who... nhấn mạnh người thực hiện hành động."),
    mc("c1-3-2", "What I really need ___ a long holiday.", ["is", "it is", "are", "that is"], 0, "Mệnh đề What I really need là chủ ngữ số ít, nên đi với is."),
    fill("c1-3-3", "It was in Hanoi ___ I first met my business partner.", ["that"], "Câu chẻ nhấn mạnh nơi chốn vẫn dùng that sau It was in Hanoi."),
    fill("c1-3-4", "I know you think I forgot, but I ___ call her yesterday.", ["did"], "Did nhấn mạnh để phản bác; động từ call giữ nguyên mẫu."),
    reorder("c1-3-5", "What we need to do is reduce our costs.", "Wh-cleft nhấn mạnh hành động: What + chủ ngữ + need to do + is + động từ nguyên mẫu."),
    reorder("c1-3-6", "It was not until midnight that I finished the report.", "It was not until + thời điểm + that + mệnh đề: mãi đến... mới..."),
    listen("c1-3-7", "It wasn't the software that failed; it was the training.", ["Phần mềm bị lỗi vì nhân viên chưa được đào tạo.", "Không phải phần mềm hỏng, mà là khâu đào tạo có vấn đề.", "Cả phần mềm lẫn khâu đào tạo đều thất bại."], 1, "It wasn't X... it was Y: không phải X, mà là Y."),
    listen("c1-3-8", "What surprised me was how quickly they agreed.", ["Điều làm tôi bất ngờ là họ đồng ý nhanh đến thế.", "Tôi bất ngờ vì họ không đồng ý.", "Họ bất ngờ vì tôi đồng ý quá nhanh."], 0),
  ],
  speaking: [
    say("What I'd like to focus on today is customer feedback.", "Điều tôi muốn tập trung vào hôm nay là phản hồi của khách hàng."),
    say("It was my mother who taught me to love reading.", "Chính mẹ tôi là người đã dạy tôi yêu việc đọc sách."),
    say("I do understand your concerns, but we need to move forward.", "Tôi thực sự hiểu những lo ngại của bạn, nhưng chúng ta cần tiến lên."),
  ],
});

const lapLuan = lesson({
  slug: "lap-luan-va-phan-bien",
  title: "Lập luận và phản biện",
  minutes: 22,
  lecture: {
    title: "Nhượng bộ và phản biện",
    blocks: [
      p("Lập luận thuyết phục ở trình độ C1 không phải là phủ nhận hoàn toàn quan điểm đối lập, mà là **thừa nhận** phần hợp lý của nó rồi **phản bác**. Kỹ thuật này gọi là nhượng bộ (concession)."),
      table(
        ["Từ nối", "Theo sau là", "Ví dụ"],
        ["although / even though", "mệnh đề (S + V)", "Although the plan is costly, it will pay off."],
        ["despite / in spite of", "danh từ hoặc V-ing", "Despite the cost, the plan will pay off."],
        ["while", "mệnh đề, thường đứng đầu câu", "While I see your point, I disagree."],
        ["even so / nevertheless", "thường đứng đầu câu mới", "The plan is costly. Even so, it will pay off."],
        ["admittedly", "thường đứng đầu câu, để thừa nhận một điểm yếu", "Admittedly, the plan is costly."],
      ),
      mistake("Despite the plan is costly, it will pay off.", "Despite the fact that the plan is costly, it will pay off.", "Despite và in spite of không đi trực tiếp với mệnh đề. Hãy dùng although, hoặc thêm the fact that."),
      mistake("Although it was raining, but we went out.", "Although it was raining, we went out.", "Tiếng Việt nói “Mặc dù... nhưng...”, còn tiếng Anh chỉ dùng một liên từ: although hoặc but, không dùng cả hai."),
      p("Một đoạn phản biện chặt chẽ thường gồm bốn bước: **nêu quan điểm đối lập**, **thừa nhận phần hợp lý**, **phản bác**, rồi **khẳng định lại quan điểm của mình**."),
      ex("Some argue that remote work harms collaboration.", "Một số người cho rằng làm việc từ xa làm giảm sự hợp tác.", "Bước một: nêu quan điểm đối lập."),
      ex("Admittedly, spontaneous conversations are less frequent online.", "Phải thừa nhận rằng các cuộc trò chuyện ngẫu hứng ít xảy ra hơn khi làm việc trực tuyến.", "Bước hai: thừa nhận."),
      ex("Even so, well-designed digital tools can more than make up for this.", "Dù vậy, các công cụ số được thiết kế tốt hoàn toàn có thể bù đắp điều này.", "Bước ba và bốn: phản bác và khẳng định lại."),
      tip("Các cụm như **That said**, **On the other hand**, **Be that as it may** giúp chuyển ý mượt mà. Tránh mở đầu mọi câu bằng **However**; thay đổi từ nối giúp bài viết tự nhiên hơn."),
    ],
  },
  words: [
    word("concession", "/kənˈseʃ.ən/", "sự nhượng bộ, sự thừa nhận", "Making a small concession can make your argument more convincing.", "con|ces|sion", 1),
    word("counterargument", "/ˈkaʊn.tər.ɑː.ɡjə.mənt/", "lập luận phản bác", "A strong essay anticipates the main counterargument.", "coun|ter|ar|gu|ment", 0),
    word("acknowledge", "/əkˈnɒl.ɪdʒ/", "thừa nhận", "I acknowledge that the proposal has some weaknesses.", "ac|know|ledge", 1, "Chữ k câm, đọc là /əkˈnɒl.ɪdʒ/."),
    word("rebuttal", "/rɪˈbʌt.əl/", "sự bác bỏ", "Her rebuttal was calm, precise and convincing.", "re|but|tal", 1),
    word("valid", "/ˈvæl.ɪd/", "hợp lý, có cơ sở", "You raise a valid point, but it doesn't change the overall picture.", "val|id", 0),
    word("nevertheless", "/ˌnev.ə.ðəˈles/", "tuy nhiên, dù vậy", "The risks are real. Nevertheless, the benefits outweigh them.", "nev|er|the|less", 3),
    word("compelling", "/kəmˈpel.ɪŋ/", "thuyết phục, đầy sức nặng", "She presented compelling evidence for the change.", "com|pel|ling", 1),
    word("undermine", "/ˌʌn.dəˈmaɪn/", "làm suy yếu", "One weak example can undermine your whole argument.", "un|der|mine", 2),
  ],
  exercises: [
    mc("c1-4-1", "___ the heavy traffic, we arrived on time.", ["Although", "Despite", "Even though", "However"], 1, "The heavy traffic là cụm danh từ, nên dùng despite. Although và even though cần một mệnh đề."),
    mc("c1-4-2", "Câu nào đúng?", ["Although he was tired, but he kept working.", "Despite he was tired, he kept working.", "Even though he was tired, he kept working."], 2, "Không dùng although cùng but; despite không đi trực tiếp với mệnh đề."),
    fill("c1-4-3", "In spite ___ the criticism, the director refused to change the ending.", ["of"], "Luôn là in spite of, còn despite thì không có of."),
    fill("c1-4-4", "The new system is expensive. Even ___, it will save us money in the long run.", ["so"], "Even so nghĩa là dù vậy, đứng đầu câu mới."),
    reorder("c1-4-5", "Some critics argue that the policy is unfair.", "Mở đầu phản biện bằng cách nêu quan điểm đối lập."),
    reorder("c1-4-6", "Their success came despite a lack of funding.", "Despite + cụm danh từ (a lack of funding), không cần of."),
    listen("c1-4-7", "Admittedly, the plan has flaws, but it's the best option we have.", ["Kế hoạch có nhiều lỗi nên chúng ta nên bỏ nó.", "Kế hoạch hoàn hảo và là lựa chọn duy nhất.", "Chúng ta chưa có kế hoạch nào tốt.", "Phải thừa nhận kế hoạch có thiếu sót, nhưng đó là lựa chọn tốt nhất ta có."], 3, "Admittedly dùng để thừa nhận một điểm yếu trước khi phản bác."),
    listen("c1-4-8", "Even though the evidence is limited, the conclusion seems reasonable.", ["Mặc dù bằng chứng còn hạn chế, kết luận có vẻ hợp lý.", "Vì thiếu bằng chứng nên kết luận không hợp lý.", "Bằng chứng rất rõ ràng nên kết luận hợp lý."], 0),
  ],
  speaking: [
    say("I see your point, but I'm not sure it applies here.", "Tôi hiểu ý bạn, nhưng tôi không chắc nó áp dụng được trong trường hợp này."),
    say("Admittedly, the cost is high. Even so, it's worth it.", "Phải thừa nhận là chi phí cao. Dù vậy, nó vẫn đáng."),
    say("Despite the risks, I believe we should go ahead.", "Bất chấp rủi ro, tôi tin chúng ta nên tiến hành."),
  ],
});

const tinhTe = lesson({
  slug: "ngon-ngu-tinh-te",
  title: "Ngôn ngữ tinh tế",
  minutes: 20,
  lecture: {
    title: "Nói giảm, rào đón và hàm ý",
    blocks: [
      p("Người bản xứ, nhất là người Anh, hiếm khi nói thẳng “Tôi không đồng ý” hay “Ý tưởng này tệ”. Họ dùng **nói giảm** (understatement) và **rào đón** (hedging). Hiểu sai hàm ý là nguyên nhân của rất nhiều hiểu lầm trong môi trường làm việc quốc tế."),
      table(
        ["Câu nói", "Nghĩa đen", "Hàm ý thực sự"],
        ["It's not ideal.", "Nó chưa lý tưởng.", "Có vấn đề khá lớn."],
        ["I'm not entirely convinced.", "Tôi chưa hoàn toàn bị thuyết phục.", "Tôi không đồng ý."],
        ["That's an interesting idea.", "Ý tưởng thú vị đấy.", "Tôi nghi ngờ ý tưởng này."],
        ["With all due respect...", "Với tất cả sự tôn trọng...", "Tôi sắp phản bác bạn."],
        ["It could be better.", "Nó có thể tốt hơn.", "Nó khá tệ."],
      ),
      p("**Hedging** là làm mềm câu nói để tránh khẳng định tuyệt đối, bằng các từ như **might**, **could**, **tend to**, **seem**, **arguably**, **to some extent**. Cách này vừa lịch sự vừa cho thấy tư duy thận trọng."),
      ex("This approach might not be the most efficient.", "Cách làm này có lẽ không phải hiệu quả nhất.", "Nhẹ nhàng hơn nhiều so với: This approach is inefficient."),
      ex("I was a bit disappointed with the results.", "Tôi hơi thất vọng về kết quả.", "Với người Anh, a bit disappointed có thể có nghĩa là rất thất vọng."),
      mistake("Your plan is wrong.", "I'm not sure the plan fully addresses the problem.", "Trong môi trường chuyên nghiệp, câu phủ định thẳng thừng dễ bị coi là thô lỗ. Hãy rào đón và nhắm vào vấn đề, không nhắm vào người."),
      p("**Thành ngữ** cũng mang sắc thái riêng và cần đúng ngữ cảnh: **the elephant in the room** (vấn đề ai cũng biết nhưng né tránh), **a blessing in disguise** (trong cái rủi có cái may), **cut corners** (làm ẩu để tiết kiệm thời gian hoặc tiền)."),
      mistake("Let's address the elephant of the room.", "Let's address the elephant in the room.", "Thành ngữ là cụm cố định: không được đổi giới từ hay thay từ nào."),
      tip("Khi nghe phản hồi, hãy chú ý **ngữ điệu** và các từ rào đón. Trong tiếng Anh-Anh, quite good thường chỉ có nghĩa là **tạm được**, không phải “khá tốt” như người Việt hay hiểu."),
    ],
  },
  words: [
    word("subtle", "/ˈsʌt.əl/", "tinh tế, khó nhận ra", "There's a subtle difference between confident and arrogant.", "sub|tle", 0, "Chữ b câm, không đọc âm /b/."),
    word("understatement", "/ˈʌn.də.steɪt.mənt/", "cách nói giảm", "Calling the project a challenge is an understatement.", "un|der|state|ment", 0),
    word("hedge", "/hedʒ/", "nói rào đón, tránh cam kết", "Politicians often hedge when asked difficult questions.", "hedge", 0),
    word("implication", "/ˌɪm.plɪˈkeɪ.ʃən/", "hàm ý", "The implication was that we had made a mistake.", "im|pli|ca|tion", 2),
    word("diplomatic", "/ˌdɪp.ləˈmæt.ɪk/", "khéo léo, tế nhị", "She gave a diplomatic answer to avoid offending anyone.", "dip|lo|mat|ic", 2),
    word("tactful", "/ˈtækt.fəl/", "tế nhị, biết ý", "It was tactful of him not to mention the mistake.", "tact|ful", 0),
    word("blunt", "/blʌnt/", "thẳng thừng, bộc trực", "To be blunt, the proposal isn't good enough.", "blunt", 0),
    word("sarcastic", "/sɑːˈkæs.tɪk/", "mỉa mai", "When he said “great job”, he was being sarcastic.", "sar|cas|tic", 1),
  ],
  exercises: [
    mc("c1-5-1", "Quản lý người Anh nói về bản kế hoạch của bạn: “It's not ideal.” Ý thực sự là gì?", ["Kế hoạch rất tốt, chỉ cần sửa chút ít.", "Kế hoạch hoàn hảo.", "Kế hoạch có vấn đề đáng kể."], 2, "It's not ideal là cách nói giảm; thực tế vấn đề khá nghiêm trọng."),
    mc("c1-5-2", "Câu nào lịch sự và có rào đón nhất?", ["This idea is bad.", "This idea might need a little more work.", "I hate this idea.", "This idea is wrong."], 1, "Might và a little làm mềm lời phê bình."),
    fill("c1-5-3", "The results were, to some ___, better than we expected.", ["extent", "degree"], "To some extent (ở một mức độ nào đó) là cụm rào đón phổ biến."),
    fill("c1-5-4", "Nobody wanted to mention the elephant in the ___: the budget cuts.", ["room"], "The elephant in the room: vấn đề ai cũng biết nhưng không ai dám nói."),
    reorder("c1-5-5", "I'm not entirely convinced by this proposal.", "Cách lịch sự để nói rằng bạn không đồng ý."),
    reorder("c1-5-6", "Losing that job was a blessing in disguise.", "A blessing in disguise: trong cái rủi có cái may."),
    listen("c1-5-7", "With all due respect, I think we may be missing the bigger picture.", ["Với tất cả sự tôn trọng, tôi nghĩ có lẽ chúng ta đang bỏ qua bức tranh toàn cảnh.", "Tôi hoàn toàn đồng ý với bạn.", "Tôi rất tôn trọng bạn nên không có ý kiến gì thêm."], 0, "With all due respect thường báo hiệu một lời phản bác."),
    listen("c1-5-8", "The presentation was quite good, but it could be better.", ["Bài thuyết trình xuất sắc.", "Bài thuyết trình tạm được, còn nhiều điểm cần cải thiện.", "Bài thuyết trình rất tệ, không cứu vãn được."], 1, "Quite good kèm it could be better nghĩa là tạm được, chưa tốt."),
  ],
  speaking: [
    say("I'm not entirely convinced this is the best approach.", "Tôi chưa hoàn toàn bị thuyết phục rằng đây là cách tốt nhất."),
    say("It's not ideal, but we can make it work.", "Nó chưa lý tưởng, nhưng chúng ta có thể xoay xở được."),
    say("Let's address the elephant in the room.", "Hãy nói thẳng vào vấn đề mà ai cũng đang né tránh."),
  ],
});

const hocThuat = lesson({
  slug: "van-phong-hoc-thuat",
  title: "Văn phong học thuật",
  minutes: 24,
  lecture: {
    title: "Danh từ hóa và cấu trúc khách quan",
    blocks: [
      p("Văn phong học thuật (bài luận, báo cáo, IELTS Writing) khác văn nói ở ba điểm: dùng **danh từ hóa** (nominalisation), chọn **từ trang trọng** thay cho phrasal verb đời thường, và dùng **cấu trúc khách quan** thay vì I think."),
      p("**Danh từ hóa** là biến động từ hoặc tính từ thành danh từ, giúp câu súc tích và mang tính khái niệm hơn."),
      ex("The government reduced taxes, so people spent more.", "Chính phủ giảm thuế, nên người dân chi tiêu nhiều hơn.", "Văn nói: nhiều động từ, nhiều mệnh đề."),
      ex("The reduction in taxes led to an increase in consumer spending.", "Việc giảm thuế đã dẫn đến sự gia tăng chi tiêu tiêu dùng.", "Văn học thuật: reduce thành reduction, spend thành spending."),
      table(
        ["Thân mật", "Trang trọng", "Ví dụ học thuật"],
        ["get", "obtain / receive", "Participants obtained higher scores."],
        ["find out", "discover / determine", "The study aimed to determine the cause."],
        ["look into", "investigate / examine", "This paper examines the impact of AI."],
        ["go up", "increase / rise", "Prices rose significantly."],
        ["a lot of", "a significant number of / considerable", "A significant number of students agreed."],
        ["show", "demonstrate / indicate", "The data indicate a clear trend."],
      ),
      p("**Cấu trúc khách quan** giúp tránh I think và tạo khoảng cách với người viết: **It is widely believed that...**, **It has been argued that...**, **It is estimated that...**, hoặc dạng **X is thought to...**"),
      ex("It is widely believed that early education shapes lifelong success.", "Nhiều người tin rằng giáo dục sớm định hình thành công suốt đời."),
      mistake("I think that social media is very bad for teenagers.", "It has been argued that social media may have a negative impact on teenagers.", "Trong bài học thuật, tránh I think và tính từ cảm tính như very bad. Dùng cấu trúc khách quan và rào đón bằng may."),
      mistake("Researchers got a lot of data from the survey.", "Researchers obtained a substantial amount of data from the survey.", "Get và a lot of quá thân mật cho văn học thuật; hãy dùng obtain và a substantial amount of."),
      tip("Đừng danh từ hóa mọi thứ. Quá nhiều danh từ nối tiếp sẽ làm câu nặng nề, khó đọc. Mục tiêu là **rõ ràng và chính xác**, không phải phức tạp."),
    ],
  },
  words: [
    word("nominalisation", "/ˌnɒm.ɪ.nəl.aɪˈzeɪ.ʃən/", "sự danh từ hóa", "Nominalisation makes academic writing more concise.", "nom|i|nal|i|sa|tion", 4, "Tiếng Anh-Mỹ viết là nominalization."),
    word("obtain", "/əbˈteɪn/", "thu được, đạt được", "The researchers obtained permission from all participants.", "ob|tain", 1),
    word("objective", "/əbˈdʒek.tɪv/", "khách quan", "Academic writing should remain objective and balanced.", "ob|jec|tive", 1),
    word("impersonal", "/ɪmˈpɜː.sən.əl/", "không mang tính cá nhân, khách quan", "Impersonal structures help writers avoid sounding biased.", "im|per|son|al", 1),
    word("hypothesis", "/haɪˈpɒθ.ə.sɪs/", "giả thuyết", "The data support the original hypothesis.", "hy|poth|e|sis", 1, "Số nhiều là hypotheses /haɪˈpɒθ.ə.siːz/."),
    word("substantiate", "/səbˈstæn.ʃi.eɪt/", "chứng minh bằng bằng chứng", "The author fails to substantiate her main claim.", "sub|stan|ti|ate", 1),
    word("methodology", "/ˌmeθ.əˈdɒl.ə.dʒi/", "phương pháp luận", "The methodology section explains how the data were collected.", "meth|o|dol|o|gy", 2),
  ],
  exercises: [
    mc("c1-6-1", "Từ nào trang trọng nhất để thay cho find out trong bài học thuật?", ["figure out", "work out", "get to know", "determine"], 3, "Determine phù hợp văn học thuật; figure out và work out mang tính thân mật."),
    mc("c1-6-2", "Câu nào phù hợp nhất với văn phong học thuật?", ["It is widely believed that exercise improves memory.", "Everyone knows exercise is great for your memory.", "I reckon exercise helps your memory a lot."], 0, "Cấu trúc khách quan It is widely believed that... thay cho cách nói cảm tính."),
    fill("c1-6-3", "It is widely ___ that climate change will affect food production.", ["believed", "accepted", "thought", "acknowledged", "recognised", "recognized", "expected", "known", "agreed", "predicted", "assumed", "anticipated", "feared", "argued", "held"], "It is widely + quá khứ phân từ + that... là cấu trúc khách quan."),
    fill("c1-6-4", "Following the announcement, there was a sharp ___ in oil prices (giá dầu tăng mạnh).", ["increase", "rise", "jump", "surge", "spike"], "Danh từ hóa: thay vì viết prices increased sharply, ta viết a sharp increase in prices."),
    reorder("c1-6-5", "The study aims to examine the impact of social media.", "Examine trang trọng hơn look into."),
    reorder("c1-6-6", "It is estimated that prices will rise further.", "It is estimated that... là cấu trúc khách quan."),
    listen("c1-6-7", "The findings indicate a strong correlation between sleep and academic performance.", ["Ngủ nhiều khiến kết quả học tập giảm sút.", "Kết quả cho thấy mối tương quan chặt chẽ giữa giấc ngủ và kết quả học tập.", "Nghiên cứu chưa tìm thấy mối liên hệ nào giữa giấc ngủ và học tập."], 1, "Indicate a strong correlation: cho thấy mối tương quan chặt chẽ."),
    listen("c1-6-8", "Further research is needed to substantiate these claims.", ["Những khẳng định này đã được chứng minh đầy đủ.", "Nghiên cứu này bác bỏ những khẳng định trước đó.", "Cần thêm nghiên cứu để chứng minh những khẳng định này."], 2, "Substantiate: chứng minh bằng bằng chứng."),
  ],
  speaking: [
    say("It is widely believed that education reduces inequality.", "Nhiều người tin rằng giáo dục giúp giảm bất bình đẳng."),
    say("The findings indicate a significant increase in demand.", "Kết quả cho thấy nhu cầu tăng đáng kể."),
    say("Further research is needed to confirm this hypothesis.", "Cần thêm nghiên cứu để xác nhận giả thuyết này."),
  ],
});

export const tiengAnhC1: Course = {
  slug: "tieng-anh-c1",
  title: "Tiếng Anh C1: Thành thạo",
  level: "C1",
  goal: "lo-trinh",
  summary: "Cho người đã vững B2: nói và viết tự nhiên, tinh tế như người dùng tiếng Anh thành thạo, từ cuộc họp quốc tế đến bài luận học thuật.",
  outcomes: [
    "Dùng cụm động từ và kết hợp từ tự nhiên như người bản xứ",
    "Nhấn mạnh ý bằng đảo ngữ và câu chẻ",
    "Lập luận, nhượng bộ và phản biện một cách thuyết phục",
    "Viết theo văn phong học thuật chuẩn mực",
  ],
  audience: [
    "Người đã ở trình độ B2 muốn vượt qua giai đoạn “chững lại”",
    "Người đi làm và nghiên cứu sinh cần tiếng Anh cho họp, thuyết trình và viết báo cáo",
  ],
  teacher: {
    name: "Cô Diệu Linh",
    initials: "DL",
    bio: "Thạc sĩ Ngôn ngữ học ứng dụng, chứng chỉ DELTA. 12 năm dạy tiếng Anh học thuật và kỹ năng thuyết trình cho người đi làm.",
  },
  durationWeeks: 10,
  rating: 4.9,
  reviews: [
    { name: "Bảo Ngọc", role: "Chuyên viên phân tích tài chính, TP. Hồ Chí Minh", quote: "Trước đây mình nói đúng ngữ pháp nhưng nghe rất cứng. Bài về nói giảm và rào đón giúp mình tự tin hơn hẳn khi họp với đối tác người Anh." },
    { name: "Tuấn Kiệt", role: "Nghiên cứu sinh, Huế", quote: "Phần văn phong học thuật cực kỳ thực tế. Mình áp dụng danh từ hóa vào bài báo đầu tiên và được giáo sư hướng dẫn khen." },
  ],
  faqs: [
    { q: "Làm sao biết mình đủ trình độ để học C1?", a: "Bạn nên hoàn thành khóa B2 hoặc làm bài kiểm tra đầu vào. Nếu bạn đọc hiểu báo tiếng Anh mà không cần tra từ liên tục, bạn đã sẵn sàng." },
    { q: "Học xong C1 thì học gì tiếp?", a: "Nếu cần chứng chỉ, bạn có thể học tiếp khóa luyện thi IELTS để biến kỹ năng thành điểm số. Nếu không, hãy duy trì luyện tập hằng ngày: đọc báo, nghe podcast và viết thường xuyên để giữ vững trình độ." },
  ],
  status: "open",
  modules: [
    { id: "m1", title: "Tiếng Anh tự nhiên", lessons: [noiTuNhien, daoNgu, cauChe] },
    { id: "m2", title: "Lập luận tinh tế", lessons: [lapLuan, tinhTe, hocThuat] },
  ],
};
