import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, tip, word } from "../builders";
import type { Course } from "../types";

const homQua = lesson({
  slug: "hom-qua-ban-lam-gi",
  title: "Hôm qua bạn làm gì",
  minutes: 20,
  free: true,
  lecture: {
    title: "Thì quá khứ đơn: kể chuyện đã xảy ra",
    blocks: [
      p("Tiếng Việt chỉ cần thêm “hôm qua”, “tuần trước” là người nghe hiểu chuyện đã qua. Tiếng Anh thì khác: **động từ phải đổi sang dạng quá khứ**. Với động từ có quy tắc, ta thêm **-ed**: work → worked, play → played."),
      table(
        ["Âm cuối của động từ", "-ed đọc là", "Ví dụ"],
        ["/p/, /k/, /s/, /ʃ/, /tʃ/, /f/", "/t/", "worked, watched, finished"],
        ["nguyên âm và các âm hữu thanh còn lại", "/d/", "played, called, lived"],
        ["/t/, /d/", "/ɪd/", "wanted, visited, decided"],
      ),
      p("Nhiều động từ thông dụng là **bất quy tắc**, phải học thuộc: go → went, have → had, see → saw, buy → bought, eat → ate, get → got, make → made."),
      p("Câu hỏi và câu phủ định dùng **did** / **didn't**, và động từ chính quay về **dạng nguyên mẫu**."),
      ex("What did you do yesterday?", "Hôm qua bạn làm gì?"),
      ex("I didn't go out. I watched a film at home.", "Tôi không ra ngoài. Tôi xem phim ở nhà."),
      ex("We moved to Da Nang three years ago.", "Chúng tôi chuyển đến Đà Nẵng ba năm trước.", "Ago đứng sau khoảng thời gian: three years ago, two days ago."),
      tip("Các cụm chỉ thời gian quá khứ hay gặp: **yesterday**, **last night**, **last week**, **last year**, **two days ago**. Không nói “yesterday night”, hãy nói **last night**."),
      mistake("I didn't went to school.", "I didn't go to school.", "Đã có didn't báo quá khứ rồi thì động từ chính giữ nguyên mẫu."),
      mistake("Yesterday I go to the market.", "Yesterday I went to the market.", "Có “yesterday” vẫn phải chia động từ ở quá khứ, không bỏ được như tiếng Việt."),
    ],
  },
  words: [
    word("yesterday", "/ˈjes.tə.deɪ/", "hôm qua", "I called my mum yesterday.", "yes|ter|day", 0),
    word("visit", "/ˈvɪz.ɪt/", "thăm", "We visited our grandparents last weekend.", "vis|it", 0, "Visit kết thúc bằng âm /t/ nên đuôi -ed trong visited đọc là /ɪd/."),
    word("travel", "/ˈtræv.əl/", "đi du lịch, đi lại", "They travelled to Hue last summer.", "trav|el", 0),
    word("finish", "/ˈfɪn.ɪʃ/", "hoàn thành, kết thúc", "I finished work at six.", "fin|ish", 0, "Finished đọc là /ˈfɪn.ɪʃt/, chỉ thêm âm /t/, không đọc thành “fi-nít-sờ-đờ”."),
    word("decide", "/dɪˈsaɪd/", "quyết định", "She decided to stay at home.", "de|cide", 1),
    word("ago", "/əˈɡəʊ/", "cách đây, trước", "I started this job two years ago.", "a|go", 1),
    word("watch", "/wɒtʃ/", "xem", "We watched a football match last night.", "watch", 0),
  ],
  exercises: [
    mc("a2-1-1", "I ___ my grandparents last weekend.", ["visit", "visited", "visiting", "visits"], 1, "Last weekend là thời gian đã qua nên dùng quá khứ: visited."),
    mc("a2-1-2", "Từ nào có đuôi -ed đọc là /ɪd/?", ["played", "worked", "wanted"], 2, "Want kết thúc bằng âm /t/ nên wanted đọc là /ˈwɒn.tɪd/."),
    fill("a2-1-3", "She didn't ___ to the party yesterday.", ["go", "come"], "Sau didn't, động từ giữ nguyên mẫu: go hoặc come."),
    fill("a2-1-4", "I ___ a new phone two days ago. (buy)", ["bought"], "Buy là động từ bất quy tắc: buy → bought."),
    reorder("a2-1-5", "What did you do yesterday?", "Từ để hỏi + did + chủ ngữ + động từ nguyên mẫu."),
    reorder("a2-1-6", "My mother made a birthday cake", "Make là động từ bất quy tắc: make → made."),
    listen("a2-1-7", "I finished work at six yesterday.", ["Hôm nay tôi làm xong việc lúc sáu giờ.", "Hôm qua tôi làm xong việc lúc sáu giờ.", "Hôm qua tôi bắt đầu làm việc lúc sáu giờ."], 1),
    listen("a2-1-8", "Did you call your mother last night?", ["Tối nay bạn sẽ gọi cho mẹ chứ?", "Mẹ bạn có gọi cho bạn tối qua không?", "Tối qua bạn có gọi cho mẹ không?"], 2, "Did you call...? là câu hỏi quá khứ: bạn có gọi... không."),
  ],
  speaking: [
    say("Yesterday I visited my friend in Hanoi.", "Hôm qua tôi đến thăm bạn tôi ở Hà Nội."),
    say("I didn't watch TV last night.", "Tối qua tôi không xem ti vi."),
    say("We went to Da Lat two years ago.", "Chúng tôi đã đi Đà Lạt hai năm trước."),
  ],
});

const keHoach = lesson({
  slug: "ke-hoach-cuoi-tuan",
  title: "Kế hoạch cuối tuần",
  minutes: 18,
  lecture: {
    title: "Be going to và hiện tại tiếp diễn chỉ tương lai",
    blocks: [
      p("Khi nói về dự định đã nghĩ sẵn, người bản xứ hay dùng **be going to + động từ nguyên mẫu**, chứ không chỉ dùng will như nhiều người Việt vẫn quen."),
      table(
        ["Chủ ngữ", "be going to", "Ví dụ"],
        ["I", "am going to", "I'm going to clean my room."],
        ["he / she / it", "is going to", "She's going to visit her aunt."],
        ["you / we / they", "are going to", "We're going to have a picnic."],
      ),
      p("Nếu kế hoạch đã **hẹn giờ, hẹn người** cụ thể, dùng **hiện tại tiếp diễn** kèm thời gian tương lai: I'm meeting Lan on Saturday."),
      ex("What are you doing this weekend?", "Cuối tuần này bạn làm gì?", "Câu hỏi rất tự nhiên về kế hoạch, thường dùng trước khi rủ ai đó đi chơi."),
      ex("I'm going to see a film on Sunday.", "Chủ nhật tôi định đi xem phim."),
      p("Mời và nhận lời: **Would you like to...?**, **Do you want to...?** Nhận lời: **I'd love to.**, **Sounds great!** Từ chối lịch sự: **Sorry, I can't. I'm working on Saturday.**"),
      ex("Would you like to come to my party?", "Bạn có muốn đến bữa tiệc của mình không?"),
      tip("Khi từ chối, người bản xứ thường nói **Sorry** và kèm một lý do ngắn. Chỉ nói “No” nghe rất cộc."),
      mistake("I going to visit my parents.", "I'm going to visit my parents.", "Không được bỏ am/is/are trước going to."),
      mistake("Would you like go to the cinema?", "Would you like to go to the cinema?", "Sau would like phải có to trước động từ."),
    ],
  },
  words: [
    word("plan", "/plæn/", "kế hoạch; lên kế hoạch", "Do you have any plans for the weekend?", "plan", 0),
    word("invite", "/ɪnˈvaɪt/", "mời", "She invited me to her birthday party.", "in|vite", 1),
    word("free", "/friː/", "rảnh", "Are you free on Saturday?", "free", 0, "Free còn có nghĩa là miễn phí, tùy ngữ cảnh."),
    word("busy", "/ˈbɪz.i/", "bận", "Sorry, I'm busy tomorrow.", "bus|y", 0, "Đọc là /ˈbɪz.i/, không đọc là “bớt-si”."),
    word("tomorrow", "/təˈmɒr.əʊ/", "ngày mai", "I'm meeting my friends tomorrow.", "to|mor|row", 1),
    word("cinema", "/ˈsɪn.ə.mə/", "rạp chiếu phim", "Let's go to the cinema tonight.", "cin|e|ma", 0),
    word("picnic", "/ˈpɪk.nɪk/", "buổi dã ngoại", "We're going to have a picnic in the park.", "pic|nic", 0),
  ],
  exercises: [
    mc("a2-2-1", "I ___ going to visit my aunt on Sunday.", ["is", "am", "are"], 1, "I đi với am: I am going to."),
    mc("a2-2-2", "A: Would you like to come to my party? B: ___", ["Yes, I like.", "No, I don't like.", "I'd love to!"], 2, "I'd love to là cách nhận lời tự nhiên nhất."),
    fill("a2-2-3", "We're ___ to have a picnic this weekend.", ["going"], "Cấu trúc be going to + động từ nguyên mẫu."),
    fill("a2-2-4", "Would you like ___ come with us?", ["to"], "Would like + to + động từ."),
    reorder("a2-2-5", "What are you doing this weekend?"),
    reorder("a2-2-6", "What time are you meeting Lan?", "Hiện tại tiếp diễn cho một cuộc hẹn đã sắp xếp: What time + are you + meeting...?"),
    listen("a2-2-7", "Sorry, I can't. I'm working on Saturday.", ["Xin lỗi, mình không đi được. Thứ Bảy mình phải làm việc.", "Xin lỗi, thứ Bảy mình rảnh.", "Mình rất muốn đi vào thứ Bảy."], 0),
    listen("a2-2-8", "Are you free tomorrow evening?", ["Tối nay bạn có rảnh không?", "Sáng mai bạn có rảnh không?", "Tối mai bạn có rảnh không?"], 2, "Tomorrow evening là tối mai."),
  ],
  speaking: [
    say("I'm going to visit my parents this weekend.", "Cuối tuần này tôi định về thăm bố mẹ."),
    say("Would you like to have dinner with us on Friday?", "Thứ Sáu bạn có muốn ăn tối với chúng tôi không?"),
    say("Sorry, I can't. I'm meeting my friend tomorrow.", "Xin lỗi, mình không đi được. Mai mình có hẹn với bạn."),
  ],
});

const soSanh = lesson({
  slug: "so-sanh-va-mua-sam",
  title: "So sánh và mua sắm",
  minutes: 20,
  lecture: {
    title: "So sánh hơn, so sánh nhất và as...as",
    blocks: [
      p("Tiếng Việt chỉ cần thêm “hơn” hoặc “nhất”. Tiếng Anh chia tính từ làm hai nhóm: **tính từ ngắn** thêm **-er / -est**, **tính từ dài** dùng **more / the most**. Khi nêu rõ vật được so sánh, dùng **than** trước vật đó: cheaper **than** that one."),
      table(
        ["Tính từ", "So sánh hơn", "So sánh nhất"],
        ["cheap (rẻ)", "cheaper", "the cheapest"],
        ["big (to)", "bigger", "the biggest"],
        ["easy (dễ)", "easier", "the easiest"],
        ["expensive (đắt)", "more expensive", "the most expensive"],
        ["good (tốt)", "better", "the best"],
        ["bad (tệ)", "worse", "the worst"],
      ),
      ex("This bag is cheaper than that one.", "Cái túi này rẻ hơn cái kia."),
      ex("It's the most expensive shop in the city.", "Đó là cửa hàng đắt nhất thành phố."),
      p("Muốn nói “bằng”, dùng **as + tính từ + as**: This shirt is as nice as that one. Phủ định **not as...as** nghĩa là “không bằng”."),
      p("Mẫu câu khi mua sắm: **How much is this?**, **Can I try it on?**, **Do you have it in a smaller size?**, **I'll take it.**"),
      ex("Do you have this in a bigger size?", "Bạn có cái này cỡ lớn hơn không?", "Câu hỏi rất hay dùng khi mua quần áo, giày dép."),
      tip("Tính từ hai âm tiết tận cùng bằng **-y** đổi y thành i rồi thêm -er / -est: happy → happier, easy → the easiest."),
      mistake("This phone is more cheaper.", "This phone is cheaper.", "Đã thêm -er thì không dùng more nữa."),
      mistake("It's the most good restaurant.", "It's the best restaurant.", "Good là bất quy tắc: good → better → the best."),
    ],
  },
  words: [
    word("cheap", "/tʃiːp/", "rẻ", "This market is very cheap.", "cheap", 0),
    word("expensive", "/ɪkˈspen.sɪv/", "đắt", "That watch is too expensive.", "ex|pen|sive", 1),
    word("price", "/praɪs/", "giá", "What's the price of this jacket?", "price", 0, "Kết thúc bằng âm /s/, khác với prize /praɪz/ (giải thưởng)."),
    word("size", "/saɪz/", "cỡ, kích thước", "What size do you wear?", "size", 0),
    word("discount", "/ˈdɪs.kaʊnt/", "giảm giá", "Can I get a discount?", "dis|count", 0),
    word("customer", "/ˈkʌs.tə.mər/", "khách hàng", "The shop is full of customers.", "cus|to|mer", 0),
    word("comfortable", "/ˈkʌmf.tə.bəl/", "thoải mái, dễ chịu", "These shoes are more comfortable.", "comf|ta|ble", 0, "Chỉ có ba âm tiết, âm “for” gần như bị nuốt mất."),
  ],
  exercises: [
    mc("a2-3-1", "This phone is ___ than my old one.", ["more cheap", "cheaper", "cheapest", "more cheaper"], 1, "Cheap là tính từ ngắn: cheap → cheaper."),
    mc("a2-3-2", "It's the ___ restaurant in town.", ["better", "good", "best"], 2, "Có the và so sánh với cả thị trấn nên dùng so sánh nhất: the best."),
    fill("a2-3-3", "My brother is taller ___ me.", ["than"], "Sau so sánh hơn dùng than."),
    fill("a2-3-4", "This shirt is as cheap ___ that one.", ["as"], "Cấu trúc as + tính từ + as."),
    reorder("a2-3-5", "Where can I try it on?", "Try on là cụm động từ; đại từ it đứng giữa try và on."),
    reorder("a2-3-6", "It's the most expensive shop in town", "Tính từ dài dùng the most."),
    listen("a2-3-7", "How much are these shoes?", ["Đôi giày này cỡ bao nhiêu?", "Đôi giày này bao nhiêu tiền?", "Bạn có đôi giày nào rẻ hơn không?"], 1, "How much hỏi về giá tiền."),
    listen("a2-3-8", "Do you have it in a bigger size?", ["Bạn có cỡ nhỏ hơn không?", "Bạn có màu khác không?", "Bạn có cỡ lớn hơn không?"], 2),
  ],
  speaking: [
    say("This jacket is cheaper than that one.", "Cái áo khoác này rẻ hơn cái kia."),
    say("These are the most comfortable shoes in the shop.", "Đây là đôi giày thoải mái nhất trong cửa hàng."),
    say("Do you have this shirt in a smaller size?", "Bạn có cái áo này cỡ nhỏ hơn không?"),
  ],
});

const hoiDuong = lesson({
  slug: "hoi-duong-va-di-lai",
  title: "Hỏi đường và đi lại",
  minutes: 18,
  lecture: {
    title: "Câu mệnh lệnh để chỉ đường và nói về phương tiện",
    blocks: [
      p("Khi chỉ đường, người bản xứ dùng **câu mệnh lệnh**: bắt đầu bằng động từ nguyên mẫu, không có chủ ngữ. Đây không phải là bất lịch sự, mà là cách nói bình thường."),
      table(
        ["Tiếng Anh", "Nghĩa"],
        ["Go straight on.", "Đi thẳng."],
        ["Turn left / right.", "Rẽ trái / phải."],
        ["Take the second street on the left.", "Rẽ vào con phố thứ hai bên trái."],
        ["Cross the road.", "Băng qua đường."],
        ["It's next to / opposite the bank.", "Nó ở cạnh / đối diện ngân hàng."],
      ),
      p("Để hỏi đường, mở đầu bằng **Excuse me** rồi hỏi **How do I get to...?** hoặc **Is there a... near here?**"),
      ex("Excuse me, how do I get to the train station?", "Xin lỗi, cho tôi hỏi đến ga tàu đi thế nào?"),
      ex("Go straight on and turn right at the traffic lights.", "Đi thẳng rồi rẽ phải ở chỗ đèn giao thông."),
      p("Nói về phương tiện: **by bus**, **by train**, **by taxi**, **by motorbike**, nhưng đi bộ là **on foot**. Hỏi thời gian đi: **How long does it take?** Trả lời: **It takes about twenty minutes.**"),
      ex("It takes about ten minutes on foot.", "Đi bộ mất khoảng mười phút."),
      tip("Sau **by** không dùng a hay the: nói **by bus**, không nói “by the bus”."),
      mistake("I go to work by foot.", "I go to work on foot.", "Đi bộ là on foot, các phương tiện khác mới dùng by."),
      mistake("How long it takes?", "How long does it take?", "Câu hỏi ở hiện tại đơn cần trợ động từ does."),
    ],
  },
  words: [
    word("straight", "/streɪt/", "thẳng", "Go straight on for two hundred metres.", "straight", 0),
    word("turn", "/tɜːn/", "rẽ", "Turn left at the bank.", "turn", 0),
    word("corner", "/ˈkɔː.nər/", "góc phố", "The café is on the corner.", "cor|ner", 0),
    word("opposite", "/ˈɒp.ə.zɪt/", "đối diện", "The pharmacy is opposite the school.", "op|po|site", 0, "Trọng âm ở âm đầu: ÓP-pơ-zít."),
    word("station", "/ˈsteɪ.ʃən/", "nhà ga, bến", "Where is the bus station?", "sta|tion", 0),
    word("bridge", "/brɪdʒ/", "cây cầu", "Cross the bridge and turn right.", "bridge", 0),
    word("ticket", "/ˈtɪk.ɪt/", "vé", "How much is a bus ticket?", "tick|et", 0),
  ],
  exercises: [
    mc("a2-4-1", "I go to work ___ foot.", ["by", "on", "in"], 1, "Đi bộ là on foot."),
    mc("a2-4-2", "How long ___ it take to get to the airport?", ["is", "do", "does", "takes"], 2, "It là ngôi thứ ba số ít nên dùng does."),
    fill("a2-4-3", "___ left at the traffic lights.", ["Turn", "turn"], "Câu mệnh lệnh bắt đầu bằng động từ nguyên mẫu."),
    fill("a2-4-4", "It usually ___ about ten minutes by taxi.", ["takes"], "It takes + khoảng thời gian."),
    reorder("a2-4-5", "How do I get to the station?"),
    reorder("a2-4-6", "Take the first street on the right", "Câu mệnh lệnh bắt đầu bằng động từ nguyên mẫu take."),
    listen("a2-4-7", "The museum is opposite the park.", ["Bảo tàng ở cạnh công viên.", "Bảo tàng ở đối diện công viên.", "Bảo tàng ở sau công viên."], 1, "Opposite nghĩa là đối diện."),
    listen("a2-4-8", "Take the second street on the left.", ["Rẽ vào con phố thứ hai bên trái.", "Rẽ vào con phố đầu tiên bên phải.", "Đi thẳng qua hai con phố."], 0),
  ],
  speaking: [
    say("Excuse me, how do I get to the train station?", "Xin lỗi, cho tôi hỏi đến ga tàu đi thế nào?"),
    say("Go straight and turn left at the corner.", "Đi thẳng rồi rẽ trái ở góc phố."),
    say("It takes about fifteen minutes by bus.", "Đi xe buýt mất khoảng mười lăm phút."),
  ],
});

const sucKhoe = lesson({
  slug: "suc-khoe-va-loi-khuyen",
  title: "Sức khỏe và lời khuyên",
  minutes: 20,
  lecture: {
    title: "Should, have to và must",
    blocks: [
      p("Người Việt nói “Tôi bị đau đầu”, nhưng tiếng Anh dùng **have**: **I have a headache**, **I have a fever**. Đau họng là **a sore throat**."),
      p("Ba nhóm từ dưới đây đều đứng trước **động từ nguyên mẫu**, nhưng nghĩa khác nhau khá nhiều."),
      table(
        ["Từ", "Nghĩa", "Ví dụ"],
        ["should / shouldn't", "nên / không nên (lời khuyên)", "You should rest."],
        ["have to / has to", "phải (do quy định, hoàn cảnh)", "She has to take this medicine."],
        ["don't have to", "không cần, không bắt buộc", "You don't have to come tomorrow."],
        ["must", "phải (người nói thấy rất cần)", "I must see a doctor."],
        ["mustn't", "không được phép, cấm", "You mustn't smoke here."],
      ),
      ex("You look tired. You should go to bed early.", "Trông bạn mệt quá. Bạn nên đi ngủ sớm."),
      ex("You shouldn't drink cold water.", "Bạn không nên uống nước lạnh."),
      ex("It's Sunday, so I don't have to get up early.", "Hôm nay Chủ nhật nên tôi không cần dậy sớm."),
      tip("**Don't have to** và **mustn't** trông giống nhau nhưng nghĩa rất khác: don't have to là “không cần”, mustn't là “cấm”."),
      mistake("You should to rest.", "You should rest.", "Sau should, must không có to."),
      mistake("I am headache.", "I have a headache.", "Tiếng Anh dùng have + tên bệnh, không dùng to be."),
      mistake("He have to work today.", "He has to work today.", "He, she, it đi với has to."),
    ],
  },
  words: [
    word("headache", "/ˈhed.eɪk/", "đau đầu", "I have a terrible headache.", "head|ache", 0, "Ache đọc là /eɪk/, không đọc là “át-chờ”."),
    word("stomach", "/ˈstʌm.ək/", "dạ dày, bụng", "My stomach hurts.", "stom|ach", 0, "Chữ ch ở đây đọc là /k/."),
    word("fever", "/ˈfiː.vər/", "sốt", "The baby has a fever.", "fe|ver", 0),
    word("cough", "/kɒf/", "ho; cơn ho", "He has a bad cough.", "cough", 0, "Chữ gh đọc là /f/."),
    word("throat", "/θrəʊt/", "họng", "I have a sore throat.", "throat", 0),
    word("medicine", "/ˈmed.ɪ.sən/", "thuốc", "Take this medicine after meals.", "med|i|cine", 0),
    word("rest", "/rest/", "nghỉ ngơi", "You should rest for a few days.", "rest", 0),
    word("dentist", "/ˈden.tɪst/", "nha sĩ", "I have to see the dentist on Monday.", "den|tist", 0),
  ],
  exercises: [
    mc("a2-5-1", "You look tired. You ___ go to bed early.", ["should", "shouldn't", "don't have to"], 0, "Đây là lời khuyên nên dùng should."),
    mc("a2-5-2", "It's Sunday. I ___ get up early.", ["mustn't", "don't have to", "should"], 1, "Chủ nhật không phải đi làm, nên là “không cần”: don't have to."),
    fill("a2-5-3", "She ___ to take this medicine three times a day. (have)", ["has"], "She đi với has to."),
    fill("a2-5-4", "You ___ smoke in the hospital. (bị cấm)", ["mustn't", "must not", "can't", "cannot"], "Hút thuốc trong bệnh viện là bị cấm: mustn't (hoặc can't)."),
    reorder("a2-5-5", "I have a bad headache"),
    reorder("a2-5-6", "He has to stay in bed", "He, she, it đi với has to + động từ nguyên mẫu."),
    listen("a2-5-7", "You shouldn't drink cold water.", ["Bạn nên uống nước lạnh.", "Bạn không cần uống nước lạnh.", "Bạn không nên uống nước lạnh."], 2),
    listen("a2-5-8", "I've got a sore throat and a cough.", ["Tôi bị đau đầu và sốt.", "Tôi bị đau họng và ho.", "Tôi bị đau bụng và ho."], 1, "I've got nghĩa là I have (hay dùng trong tiếng Anh-Anh). Sore throat là đau họng, cough là ho."),
  ],
  speaking: [
    say("I have a headache and a fever.", "Tôi bị đau đầu và sốt."),
    say("You should drink more water and rest.", "Bạn nên uống nhiều nước hơn và nghỉ ngơi."),
    say("You don't have to go to work tomorrow.", "Mai bạn không cần đi làm."),
  ],
});

const banDaTung = lesson({
  slug: "ban-da-tung",
  title: "Bạn đã từng…?",
  minutes: 22,
  lecture: {
    title: "Thì hiện tại hoàn thành với ever và never",
    blocks: [
      p("Muốn hỏi ai đó “đã từng... bao giờ chưa”, tiếng Anh dùng **thì hiện tại hoàn thành**: **have / has + quá khứ phân từ (V3)**. Ta chỉ quan tâm việc đó có xảy ra trong đời hay chưa, không nói rõ khi nào."),
      table(
        ["Nguyên mẫu", "Quá khứ", "Quá khứ phân từ"],
        ["go", "went", "been / gone"],
        ["eat", "ate", "eaten"],
        ["see", "saw", "seen"],
        ["meet", "met", "met"],
        ["try", "tried", "tried"],
        ["visit", "visited", "visited"],
      ),
      p("Hỏi dùng **Have you ever + V3?** Trả lời ngắn: **Yes, I have.** / **No, I haven't.** Nói “chưa bao giờ” dùng **I've never + V3**."),
      ex("Have you ever been to Japan?", "Bạn đã từng đến Nhật Bản chưa?", "Been to nghĩa là đã đến rồi và đã về. Gone to là đã đi và chưa về."),
      ex("I've never eaten durian.", "Tôi chưa bao giờ ăn sầu riêng."),
      p("Khi kể tiếp chi tiết như **khi nào**, **với ai**, ta chuyển sang **quá khứ đơn**, vì lúc đó đã có thời điểm cụ thể."),
      ex("Yes, I have. I went there two years ago.", "Có, tôi từng đến. Tôi đến đó hai năm trước."),
      tip("Ever đặt giữa have và V3 trong câu hỏi. Câu khẳng định không dùng ever: nói **I've been to Hue**, không nói “I've ever been to Hue”."),
      mistake("I have visited Hue last year.", "I visited Hue last year.", "Có thời gian cụ thể (last year) thì dùng quá khứ đơn."),
      mistake("I haven't never seen snow.", "I've never seen snow.", "Never đã mang nghĩa phủ định, không dùng thêm not."),
    ],
  },
  words: [
    word("ever", "/ˈev.ər/", "đã từng (trong câu hỏi)", "Have you ever tried pho?", "ev|er", 0),
    word("never", "/ˈnev.ər/", "chưa bao giờ", "I've never been on a plane.", "nev|er", 0),
    word("abroad", "/əˈbrɔːd/", "ở nước ngoài, ra nước ngoài", "Have you ever worked abroad?", "a|broad", 1, "Abroad là trạng từ, không nói “go to abroad”."),
    word("experience", "/ɪkˈspɪə.ri.əns/", "trải nghiệm, kinh nghiệm", "It was a great experience.", "ex|pe|ri|ence", 1),
    word("festival", "/ˈfes.tɪ.vəl/", "lễ hội", "Have you ever been to a music festival?", "fes|ti|val", 0),
    word("delicious", "/dɪˈlɪʃ.əs/", "ngon", "The food was delicious.", "de|li|cious", 1),
    word("famous", "/ˈfeɪ.məs/", "nổi tiếng", "I've never met a famous person.", "fa|mous", 0),
    word("foreign", "/ˈfɒr.ən/", "nước ngoài", "Have you ever tried foreign food?", "for|eign", 0, "Chữ g không đọc: /ˈfɒr.ən/."),
  ],
  exercises: [
    mc("a2-6-1", "Have you ever ___ sushi?", ["ate", "eaten", "eat", "eating"], 1, "Sau have dùng quá khứ phân từ: eat → ate → eaten."),
    mc("a2-6-2", "I ___ to Hue last year.", ["have been", "have gone", "went"], 2, "Last year là thời điểm cụ thể nên dùng quá khứ đơn."),
    fill("a2-6-3", "She has never ___ a famous person. (meet)", ["met"], "Meet → met → met."),
    fill("a2-6-4", "A: Have you ever been to Japan? B: Yes, I ___.", ["have"], "Trả lời ngắn lặp lại trợ động từ have."),
    reorder("a2-6-5", "Have you ever been abroad?"),
    reorder("a2-6-6", "I have never tried Indian food", "Never đứng giữa have và quá khứ phân từ."),
    listen("a2-6-7", "I've never seen snow.", ["Tôi chưa bao giờ thấy tuyết.", "Tôi đã từng thấy tuyết.", "Tôi muốn được thấy tuyết."], 0),
    listen("a2-6-8", "Has he ever worked abroad?", ["Anh ấy có muốn làm việc ở nước ngoài không?", "Anh ấy đã từng làm việc ở nước ngoài chưa?", "Anh ấy đang làm việc ở nước ngoài à?"], 1, "Has he ever...? hỏi về trải nghiệm: đã từng... chưa."),
  ],
  speaking: [
    say("Have you ever been to Da Nang?", "Bạn đã từng đến Đà Nẵng chưa?"),
    say("I've never eaten durian.", "Tôi chưa bao giờ ăn sầu riêng."),
    say("Yes, I have. I went there two years ago.", "Có, tôi từng đến. Tôi đến đó hai năm trước."),
  ],
});

export const tiengAnhA2: Course = {
  slug: "tieng-anh-a2",
  title: "Tiếng Anh A2: Giao tiếp hằng ngày",
  level: "A2",
  goal: "lo-trinh",
  summary: "Kể chuyện đã qua, nói về kế hoạch, mua sắm, hỏi đường và chia sẻ trải nghiệm bằng những câu tiếng Anh tự nhiên.",
  outcomes: [
    "Kể lại những việc đã làm bằng thì quá khứ đơn",
    "Nói về kế hoạch, mời và nhận lời hoặc từ chối",
    "So sánh khi mua sắm, hỏi đường và nói về phương tiện",
    "Xin và cho lời khuyên về sức khỏe, kể về trải nghiệm đã từng có",
  ],
  audience: [
    "Người đã học xong A1 hoặc nắm được thì hiện tại đơn và động từ to be",
    "Người muốn tự tin xử lý các tình huống giao tiếp hằng ngày khi đi làm, đi du lịch",
  ],
  teacher: {
    name: "Cô Ngọc Anh",
    initials: "NA",
    bio: "10 năm dạy tiếng Anh giao tiếp cho người đi làm, chứng chỉ TESOL, nổi tiếng với cách giải thích ngữ pháp bằng tình huống đời thường.",
  },
  priceVnd: 790_000,
  durationWeeks: 8,
  rating: 4.8,
  reviews: [
    { name: "Thu Trang", role: "Nhân viên văn phòng, TP. Hồ Chí Minh", quote: "Trước đây mình toàn nói “Yesterday I go”. Học xong bài quá khứ đơn mình mới hiểu vì sao phải đổi động từ." },
    { name: "Hoàng Nam", role: "Hướng dẫn viên du lịch, Hội An", quote: "Bài hỏi đường và so sánh giá dùng được ngay khi mình nói chuyện với khách nước ngoài." },
  ],
  faqs: [
    { q: "Mình chưa học khóa A1 thì có vào thẳng A2 được không?", a: "Được, nếu bạn đã dùng được động từ to be và thì hiện tại đơn. Nếu chưa chắc, hãy làm bài kiểm tra trình độ trước." },
    { q: "Học xong A2 thì học gì tiếp?", a: "Bạn học tiếp khóa B1: Tự tin trò chuyện, để kể chuyện dài hơn và bày tỏ quan điểm. Mỗi cấp có chứng chỉ riêng." },
  ],
  status: "open",
  modules: [
    { id: "m1", title: "Chuyện đã qua và sắp tới", lessons: [homQua, keHoach, soSanh] },
    { id: "m2", title: "Ra ngoài và chăm sóc bản thân", lessons: [hoiDuong, sucKhoe, banDaTung] },
  ],
};
