import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, tip, word } from "../builders";
import type { Course } from "../types";

const vietEmail = lesson({
  slug: "viet-email-chuyen-nghiep",
  title: "Viết email chuyên nghiệp",
  minutes: 20,
  free: true,
  lecture: {
    title: "Văn phong trang trọng và lời đề nghị lịch sự",
    blocks: [
      p("Email công việc bằng tiếng Anh có hai mức văn phong chính: **trang trọng** (gửi đối tác, khách hàng, cấp trên chưa quen) và **trung tính** (gửi đồng nghiệp đã quen). Người Việt hay viết email quá thân mật hoặc dịch từng chữ từ tiếng Việt, khiến câu nghe cộc lốc hoặc ra lệnh."),
      table(
        ["Phần email", "Trang trọng", "Trung tính"],
        ["Mở đầu", "Dear Mr Smith,", "Hi Anna,"],
        ["Lý do viết", "I am writing to enquire about…", "Just a quick note about…"],
        ["Đính kèm", "Please find attached the report.", "I've attached the report."],
        ["Nhắc lại", "I am following up on my email of 3 May.", "Just following up on this."],
        ["Kết thư", "I look forward to hearing from you. Kind regards,", "Speak soon. Best,"],
      ),
      p("Khi nhờ ai làm gì, đừng dùng câu mệnh lệnh trần như **Send me the file.** Hãy dùng các mẫu lịch sự: **Could you…?**, **Would you mind + V-ing…?**, **I would appreciate it if you could…**"),
      ex("Could you send me the updated figures by Friday?", "Anh/chị có thể gửi tôi số liệu cập nhật trước thứ Sáu được không?"),
      ex("I would appreciate it if you could confirm the meeting time.", "Tôi rất cảm kích nếu anh/chị xác nhận giúp thời gian cuộc họp.", "Sau “I would appreciate it if you could” là động từ nguyên mẫu."),
      ex("Please find attached the signed contract.", "Xin gửi kèm theo đây bản hợp đồng đã ký."),
      tip("Khi nhờ người khác làm gì, **Would you mind** đi với **V-ing**: Would you mind checking this? Nếu đồng ý giúp, người ta trả lời “Not at all”, nghĩa là “Không phiền gì cả”."),
      mistake("I look forward to hear from you.", "I look forward to hearing from you.", "Trong cụm look forward to, “to” là giới từ nên động từ phía sau phải thêm -ing."),
      mistake("Please send me the file as soon as possible!!!", "Could you send me the file when you have a moment?", "Câu mệnh lệnh kèm nhiều dấu chấm than nghe như ra lệnh và thiếu tôn trọng người nhận."),
      tip("Khi không biết tên người nhận, dùng **Dear Sir or Madam** hoặc tốt hơn là **Dear Hiring Manager / Dear Customer Service Team**. Không viết “Dear Sir/Madam Lan”."),
    ],
  },
  words: [
    word("attachment", "/əˈtætʃ.mənt/", "tệp đính kèm", "The attachment is too large to open.", "at|tach|ment", 1),
    word("request", "/rɪˈkwest/", "yêu cầu, đề nghị", "We have received your request.", "re|quest", 1, "Trọng âm rơi vào âm tiết thứ hai: re-QUEST."),
    word("regarding", "/rɪˈɡɑː.dɪŋ/", "về việc, liên quan đến", "I am writing regarding your invoice.", "re|gard|ing", 1),
    word("colleague", "/ˈkɒl.iːɡ/", "đồng nghiệp", "My colleague will contact you tomorrow.", "col|league", 0, "Đọc là /ˈkɒl.iːɡ/, không đọc thành “cô-lê-gơ”."),
    word("deadline", "/ˈded.laɪn/", "hạn chót", "The deadline for the proposal is next Monday.", "dead|line", 0),
    word("confirm", "/kənˈfɜːm/", "xác nhận", "Could you confirm your attendance?", "con|firm", 1),
    word("recipient", "/rɪˈsɪp.i.ənt/", "người nhận", "Check the recipient's address before you click send.", "re|cip|i|ent", 1),
    word("urgent", "/ˈɜː.dʒənt/", "khẩn cấp", "This is an urgent matter, so please reply today.", "ur|gent", 0),
  ],
  exercises: [
    mc("b2-1-1", "Which opening is most suitable for an email to a new client?", ["Hey guys,", "Dear Ms Nguyen,", "Hi mate,"], 1, "Với khách hàng mới, dùng Dear + danh xưng + họ."),
    mc("b2-1-2", "Would you mind ___ the report before the meeting?", ["to check", "check", "checked", "checking"], 3, "Khi nhờ ai làm gì, Would you mind đi với V-ing."),
    fill("b2-1-3", "I look forward to ___ from you.", ["hearing"], "Look forward to + V-ing, vì “to” ở đây là giới từ."),
    fill("b2-1-4", "Please find ___ the invoice for March.", ["attached"], "Please find attached là cụm cố định khi gửi kèm tài liệu."),
    reorder("b2-1-5", "I would appreciate it if you could reply soon.", "Mẫu câu đề nghị rất lịch sự: I would appreciate it if you could + V."),
    reorder("b2-1-6", "I am following up on my previous email.", "Follow up on: nhắc lại, hỏi tiếp về một việc đã gửi trước đó."),
    listen("b2-1-7", "Could you confirm the delivery date by Thursday?", ["Anh/chị đã giao hàng vào thứ Năm chưa?", "Anh/chị có thể xác nhận ngày giao hàng trước thứ Năm không?", "Chúng tôi sẽ giao hàng vào thứ Năm."], 1),
    listen("b2-1-8", "I'm writing to enquire about your training courses.", ["Tôi viết thư để hỏi về các khóa đào tạo của quý công ty.", "Tôi viết thư để đăng ký một khóa đào tạo.", "Tôi viết thư để phàn nàn về khóa đào tạo."], 0, "Enquire about nghĩa là hỏi thông tin về điều gì."),
  ],
  speaking: [
    say("I am writing regarding the meeting next week.", "Tôi viết thư về cuộc họp tuần tới."),
    say("Could you send me the report by Friday?", "Anh/chị có thể gửi tôi bản báo cáo trước thứ Sáu không?"),
    say("I look forward to hearing from you.", "Tôi mong sớm nhận được phản hồi của anh/chị."),
  ],
});

const hopThaoLuan = lesson({
  slug: "hop-va-thao-luan",
  title: "Họp và thảo luận",
  minutes: 22,
  lecture: {
    title: "Suy đoán về quá khứ và xen ngang lịch sự",
    blocks: [
      p("Trong cuộc họp, ta thường đoán lý do của một sự việc đã xảy ra. Tiếng Anh dùng **modal + have + V3** để suy đoán về quá khứ. Mức độ chắc chắn thể hiện qua việc chọn **must**, **might/may/could** hay **can't**."),
      table(
        ["Cấu trúc", "Mức độ chắc chắn", "Ví dụ"],
        ["must have + V3", "Gần như chắc chắn là có", "He must have missed the train."],
        ["might / may / could have + V3", "Có thể đã xảy ra", "She might have forgotten the meeting."],
        ["can't / couldn't have + V3", "Gần như chắc chắn là không", "They can't have received the email."],
      ),
      ex("The client hasn't replied. They must have been busy.", "Khách hàng chưa trả lời. Chắc hẳn họ đã rất bận."),
      ex("Tom can't have finished the report already. He only started an hour ago.", "Tom không thể nào đã làm xong báo cáo rồi. Anh ấy mới bắt đầu một tiếng trước."),
      mistake("He must missed the train.", "He must have missed the train.", "Khi suy đoán về quá khứ phải có “have + V3”. Không có have thì câu sai ngữ pháp."),
      mistake("She mustn't have seen the message.", "She can't have seen the message.", "Phủ định của “must have” khi suy đoán là “can't have”. Mustn't nghĩa là “cấm”, không dùng để đoán."),
      p("Muốn xen ngang hoặc hỏi lại trong cuộc họp, người Việt hay im lặng hoặc nói thẳng “No, wrong”. Hãy dùng các cụm mềm mỏng sau."),
      table(
        ["Mục đích", "Cụm từ"],
        ["Xen ngang", "Sorry to interrupt, but… / Can I just come in here?"],
        ["Hỏi lại cho rõ", "Could you clarify what you mean by…? / Sorry, I didn't quite catch that."],
        ["Đưa ý kiến", "From my point of view… / I'd like to suggest that…"],
        ["Kéo về chủ đề", "Let's get back to the main point. / Shall we move on to the next item?"],
      ),
      tip("Khi không nghe rõ, đừng nói **What?**. Hãy nói **Sorry, could you say that again?** hoặc **Sorry, I didn't quite catch that.**"),
    ],
  },
  words: [
    word("agenda", "/əˈdʒen.də/", "chương trình họp", "Let's look at the first item on the agenda.", "a|gen|da", 1),
    word("clarify", "/ˈklær.ɪ.faɪ/", "làm rõ", "Could you clarify the timeline for us?", "clar|i|fy", 0),
    word("postpone", "/pəʊstˈpəʊn/", "hoãn lại", "We had to postpone the launch until June.", "post|pone", 1),
    word("consensus", "/kənˈsen.səs/", "sự đồng thuận", "The team finally reached a consensus.", "con|sen|sus", 1),
    word("interrupt", "/ˌɪn.təˈrʌpt/", "ngắt lời, xen ngang", "Sorry to interrupt, but I have a quick question.", "in|ter|rupt", 2, "Trọng âm chính ở âm tiết cuối: in-ter-RUPT."),
    word("priority", "/praɪˈɒr.ə.ti/", "ưu tiên", "Customer feedback is our top priority.", "pri|or|i|ty", 1),
    word("budget", "/ˈbʌdʒ.ɪt/", "ngân sách", "The project is already over budget.", "bud|get", 0),
    word("summarise", "/ˈsʌm.ər.aɪz/", "tóm tắt", "Let me summarise what we have agreed.", "sum|ma|rise", 0),
  ],
  exercises: [
    mc("b2-2-1", "The lights are off in his office. He ___ gone home.", ["must have", "can't have", "mustn't have"], 0, "Có bằng chứng rõ ràng nên dùng must have: chắc hẳn đã."),
    mc("b2-2-2", "She ___ sent the file. My inbox is empty.", ["must have", "can't have", "should"], 1, "Hộp thư trống nên gần như chắc chắn cô ấy chưa gửi: can't have."),
    mc("b2-2-3", "Which phrase is the most polite way to interrupt?", ["Stop, listen to me.", "You are wrong.", "Wait, that's not true.", "Sorry to interrupt, but…"], 3),
    fill("b2-2-4", "I'm not sure why he's late. He might have ___ the bus.", ["missed"], "Sau might have là động từ ở dạng V3 (quá khứ phân từ)."),
    fill("b2-2-5", "Could you ___ what you mean by “flexible hours”?", ["clarify", "explain"], "Clarify hoặc explain đều dùng để nhờ người khác giải thích rõ hơn."),
    reorder("b2-2-6", "Shall we move on to the next item?", "Câu chuyển sang mục tiếp theo trong chương trình họp."),
    listen("b2-2-7", "Sorry, I didn't quite catch that.", ["Xin lỗi, tôi không đồng ý.", "Xin lỗi, tôi đến muộn.", "Xin lỗi, tôi chưa nghe rõ lắm."], 2, "Catch ở đây nghĩa là nghe kịp, nghe rõ."),
    listen("b2-2-8", "They can't have read the proposal yet.", ["Chắc chắn họ đã đọc bản đề xuất.", "Họ không thể nào đã đọc bản đề xuất rồi.", "Họ không được phép đọc bản đề xuất."], 1),
  ],
  speaking: [
    say("Sorry to interrupt, but could I add something?", "Xin lỗi đã ngắt lời, tôi có thể bổ sung một ý không?"),
    say("He must have missed the train this morning.", "Chắc hẳn anh ấy đã lỡ chuyến tàu sáng nay."),
    say("Let's get back to the main point.", "Chúng ta hãy quay lại vấn đề chính."),
  ],
});

const tuongThuat = lesson({
  slug: "tuong-thuat-loi-noi",
  title: "Tường thuật lời nói",
  minutes: 22,
  lecture: {
    title: "Câu tường thuật và lùi thì",
    blocks: [
      p("Khi kể lại lời người khác trong công việc (báo cáo cho sếp, tóm tắt cuộc họp), ta dùng **câu tường thuật**. Tiếng Việt chỉ cần thêm “anh ấy nói là…”, nhưng tiếng Anh thường phải **lùi thì** một bậc khi động từ tường thuật ở quá khứ."),
      table(
        ["Lời nói trực tiếp", "Câu tường thuật"],
        ["“I work in sales.”", "She said (that) she worked in sales."],
        ["“We are reviewing the plan.”", "He said they were reviewing the plan."],
        ["“I have sent the invoice.”", "She said she had sent the invoice."],
        ["“I will call you tomorrow.”", "He said he would call me the next day."],
        ["“We can meet on Monday.”", "They said they could meet on Monday."],
      ),
      p("Với câu hỏi, dùng **asked** và đưa câu về **trật tự câu kể** (chủ ngữ đứng trước động từ). Câu hỏi Yes/No dùng **if** hoặc **whether**. Với lời yêu cầu, dùng **asked/told + tân ngữ + to V**."),
      ex("She asked me where the meeting room was.", "Cô ấy hỏi tôi phòng họp ở đâu.", "Không viết “where was the meeting room”."),
      ex("The manager asked if we had finished the report.", "Quản lý hỏi chúng tôi đã làm xong báo cáo chưa."),
      ex("He told me to send the file before noon.", "Anh ấy bảo tôi gửi tệp trước buổi trưa."),
      p("Động từ tường thuật khác **said** giúp câu chính xác hơn: **explain that**, **promise to V**, **suggest + V-ing** hoặc **suggest that + S + V**, **remind + sb + to V**."),
      mistake("He suggested me to call the client.", "He suggested calling the client.", "Suggest không đi với “sb + to V”. Dùng suggest + V-ing hoặc suggest that I (should) call the client."),
      mistake("She said me that the price was too high.", "She told me that the price was too high.", "Said không có tân ngữ chỉ người đứng ngay sau. Muốn nói với ai thì dùng told + người."),
      tip("Nếu thông tin **vẫn còn đúng** ở hiện tại, có thể không lùi thì: **She said the office opens at eight.** Nhưng trong văn viết trang trọng, lùi thì vẫn an toàn hơn."),
    ],
  },
  words: [
    word("announce", "/əˈnaʊns/", "thông báo, công bố", "The CEO announced a new strategy yesterday.", "an|nounce", 1),
    word("mention", "/ˈmen.ʃən/", "nhắc đến, đề cập", "She mentioned that the budget had been cut.", "men|tion", 0),
    word("deny", "/dɪˈnaɪ/", "phủ nhận", "He denied making the mistake.", "de|ny", 1),
    word("insist", "/ɪnˈsɪst/", "khăng khăng, nhất quyết", "The client insisted on a lower price.", "in|sist", 1),
    word("recommend", "/ˌrek.əˈmend/", "khuyên, đề xuất", "I recommend hiring an external consultant.", "rec|om|mend", 2),
    word("complain", "/kəmˈpleɪn/", "phàn nàn", "Several customers complained about the delay.", "com|plain", 1),
    word("admit", "/ədˈmɪt/", "thừa nhận", "She admitted that the figures were wrong.", "ad|mit", 1),
    word("warn", "/wɔːn/", "cảnh báo", "He warned us not to sign the contract yet.", "warn", 0, "Đọc giống “worn”, không đọc thành “wan”."),
  ],
  exercises: [
    mc("b2-3-1", "“I am working on the budget.” She said she ___ on the budget.", ["is working", "was working", "has worked"], 1, "Hiện tại tiếp diễn lùi thành quá khứ tiếp diễn."),
    mc("b2-3-2", "Which sentence is correct?", ["He asked me where was the file.", "He asked me where is the file.", "He asked me where the file was.", "He asked me where the file is it."], 2, "Câu hỏi tường thuật dùng trật tự câu kể: chủ ngữ trước động từ."),
    fill("b2-3-3", "“I will finish it tomorrow.” He promised he ___ finish it the next day.", ["would"], "Will lùi thì thành would."),
    fill("b2-3-4", "She suggested ___ the meeting to Friday.", ["moving", "postponing", "rescheduling", "changing", "shifting", "pushing"], "Suggest + V-ing."),
    mc("b2-3-5", "The manager ___ us to submit the report by five.", ["said", "suggested", "told"], 2, "Told + người + to V dùng để tường thuật lời yêu cầu."),
    reorder("b2-3-6", "She asked if I had read the contract.", "Câu hỏi Yes/No trong tường thuật dùng if, và thì hiện tại hoàn thành lùi thành quá khứ hoàn thành."),
    listen("b2-3-7", "He explained that the shipment had been delayed.", ["Anh ấy hỏi vì sao lô hàng bị chậm.", "Anh ấy hứa sẽ giao hàng đúng hạn.", "Anh ấy phàn nàn về lô hàng.", "Anh ấy giải thích rằng lô hàng đã bị chậm."], 3),
    listen("b2-3-8", "She told me not to worry about the deadline.", ["Cô ấy bảo tôi đừng lo về hạn chót.", "Cô ấy lo lắng về hạn chót.", "Cô ấy hỏi tôi về hạn chót."], 0, "Told + người + not to V: bảo ai đừng làm gì."),
  ],
  speaking: [
    say("She said she would send the report the next day.", "Cô ấy nói sẽ gửi bản báo cáo vào ngày hôm sau."),
    say("The client asked if we could offer a discount.", "Khách hàng hỏi liệu chúng tôi có thể giảm giá không."),
    say("My manager suggested hiring two more people.", "Quản lý của tôi đề xuất tuyển thêm hai người."),
  ],
});

const tiecNuoi = lesson({
  slug: "tiec-nuoi-va-gia-dinh",
  title: "Tiếc nuối và giả định quá khứ",
  minutes: 23,
  lecture: {
    title: "Câu điều kiện loại 3, câu hỗn hợp và wish",
    blocks: [
      p("Khi rút kinh nghiệm sau một dự án, ta hay nói “Giá mà…” hoặc “Nếu hồi đó… thì đã…”. Tiếng Anh dùng **câu điều kiện loại 3** để nói về điều **không có thật trong quá khứ** và kết quả tưởng tượng của nó."),
      table(
        ["Loại câu", "Mệnh đề if", "Mệnh đề chính", "Ví dụ"],
        ["Loại 3", "If + had + V3", "would have + V3", "If we had started earlier, we would have met the deadline."],
        ["Hỗn hợp", "If + had + V3", "would + V", "If I had accepted the offer, I would be in London now."],
        ["Wish / If only", "wish + had + V3", "Không cần mệnh đề chính", "I wish I had read the contract more carefully."],
      ),
      ex("If they had tested the software, the launch wouldn't have failed.", "Nếu họ đã kiểm thử phần mềm thì buổi ra mắt đã không thất bại.", "Thực tế: họ không kiểm thử và buổi ra mắt thất bại."),
      ex("If only we had listened to the customers!", "Giá mà chúng ta đã lắng nghe khách hàng!"),
      p("**Câu hỗn hợp** nối một nguyên nhân trong quá khứ với một kết quả ở **hiện tại**: vế if dùng had + V3, vế chính dùng **would + V** (không có have)."),
      ex("If I had studied finance, I would understand these reports now.", "Nếu hồi đó tôi học tài chính thì bây giờ tôi đã hiểu những báo cáo này."),
      mistake("If I would have known, I would have told you.", "If I had known, I would have told you.", "Trong câu điều kiện loại 3, không dùng would have ở mệnh đề if. Vế if phải là had + V3."),
      mistake("I wish I didn't send that email yesterday.", "I wish I hadn't sent that email yesterday.", "Tiếc nuối về quá khứ phải dùng wish + had + V3. Wish + quá khứ đơn chỉ dùng cho hiện tại."),
      tip("Khi nói nhanh, **would have** được đọc gần như **would've** /ˈwʊd.əv/, và **had** rút gọn thành **'d**: **If I'd known, I would've called.** Trong vế if, 'd là had chứ không phải would."),
    ],
  },
  words: [
    word("opportunity", "/ˌɒp.əˈtʃuː.nə.ti/", "cơ hội", "We missed a great opportunity to expand.", "op|por|tu|ni|ty", 2, "Trọng âm chính ở âm tiết thứ ba: op-por-TU-ni-ty."),
    word("regret", "/rɪˈɡret/", "hối tiếc", "I regret not asking for more details.", "re|gret", 1),
    word("investment", "/ɪnˈvest.mənt/", "khoản đầu tư", "The investment paid off within two years.", "in|vest|ment", 1),
    word("decision", "/dɪˈsɪʒ.ən/", "quyết định", "It was a difficult decision for the board.", "de|ci|sion", 1),
    word("consequence", "/ˈkɒn.sɪ.kwəns/", "hậu quả", "The delay had serious consequences for the company.", "con|se|quence", 0),
    word("outcome", "/ˈaʊt.kʌm/", "kết quả", "We are happy with the outcome of the negotiation.", "out|come", 0),
    word("promotion", "/prəˈməʊ.ʃən/", "sự thăng chức", "She would have got a promotion if she had stayed.", "pro|mo|tion", 1),
    word("overlook", "/ˌəʊ.vəˈlʊk/", "bỏ sót, bỏ qua", "We overlooked a small but important detail.", "o|ver|look", 2),
  ],
  exercises: [
    mc("b2-4-1", "If we ___ the risks, we would have avoided the problem.", ["had considered", "considered", "would consider"], 0, "Vế if của câu loại 3 dùng had + V3."),
    mc("b2-4-2", "If she had taken the job in Singapore, she ___ there now.", ["would have lived", "would live", "had lived"], 1, "Câu hỗn hợp: nguyên nhân ở quá khứ, kết quả ở hiện tại (now), nên dùng would + V."),
    fill("b2-4-3", "I wish I ___ asked more questions in the interview.", ["had"], "Wish + had + V3 để tiếc nuối về quá khứ."),
    fill("b2-4-4", "If the supplier had delivered on time, we would have ___ the order.", ["completed", "finished", "fulfilled", "delivered", "shipped"], "Would have + V3."),
    mc("b2-4-5", "Which sentence expresses regret about the past?", ["I wish I have more time.", "I wish I will have more time.", "I wish I had more time.", "I wish I had had more time for the project."], 3, "Had had + V3: tiếc là hồi đó đã không có đủ thời gian."),
    reorder("b2-4-6", "If only we had signed the deal earlier.", "If only + had + V3 diễn tả sự tiếc nuối mạnh."),
    listen("b2-4-7", "If I'd known about the problem, I would've called you.", ["Tôi biết có vấn đề nên đã gọi cho bạn.", "Nếu tôi biết có vấn đề thì tôi đã gọi cho bạn rồi.", "Nếu có vấn đề, tôi sẽ gọi cho bạn."], 1, "I'd known = I had known; would've = would have."),
    listen("b2-4-8", "I wish we hadn't cut the marketing budget.", ["Giá mà chúng ta đã không cắt giảm ngân sách tiếp thị.", "Chúng ta nên cắt giảm ngân sách tiếp thị.", "Tôi mong chúng ta sẽ tăng ngân sách tiếp thị."], 0),
  ],
  speaking: [
    say("If we had started earlier, we would have finished on time.", "Nếu chúng ta bắt đầu sớm hơn thì đã hoàn thành đúng hạn."),
    say("I wish I had read the contract more carefully.", "Giá mà tôi đã đọc hợp đồng kỹ hơn."),
    say("If I had accepted that offer, I would be a manager now.", "Nếu hồi đó tôi nhận lời đề nghị ấy thì giờ tôi đã là quản lý."),
  ],
});

const thuyetTrinh = lesson({
  slug: "thuyet-trinh",
  title: "Thuyết trình",
  minutes: 22,
  lecture: {
    title: "Mệnh đề quan hệ và cụm dẫn dắt khi thuyết trình",
    blocks: [
      p("Bài thuyết trình tốt cần câu gọn và rõ. **Mệnh đề quan hệ** giúp bạn thêm thông tin về người hoặc vật mà không phải tách thành nhiều câu ngắn. Có hai loại: **xác định** (không có dấu phẩy) và **không xác định** (có dấu phẩy)."),
      table(
        ["Đại từ", "Dùng cho", "Ví dụ"],
        ["who", "người", "The manager who leads the project is on holiday."],
        ["which", "vật, sự việc", "The report, which was published in May, shows strong growth."],
        ["that", "người hoặc vật (chỉ mệnh đề xác định)", "This is the product that sold best last year."],
        ["whose", "sở hữu (của ai, của cái gì)", "We work with a supplier whose prices are very competitive."],
      ),
      ex("The customers who took part in the survey were very positive.", "Những khách hàng đã tham gia khảo sát đều rất tích cực.", "Mệnh đề xác định: cho biết là khách hàng nào."),
      ex("Our Hanoi office, which opened in 2020, now has fifty staff.", "Văn phòng Hà Nội của chúng tôi, mở cửa năm 2020, hiện có năm mươi nhân viên.", "Mệnh đề không xác định: chỉ thêm thông tin, bỏ đi câu vẫn đủ nghĩa."),
      mistake("Our CEO, that joined in 2019, will speak first.", "Our CEO, who joined in 2019, will speak first.", "Không dùng that sau dấu phẩy. Mệnh đề không xác định dùng who, which (hoặc whose, where…), không dùng that."),
      mistake("This is the chart which I showed it earlier.", "This is the chart which I showed earlier.", "Which đã thay cho “the chart”, không lặp lại đại từ it."),
      p("Cụm **dẫn dắt** (signposting) giúp người nghe biết bạn đang ở phần nào của bài nói."),
      table(
        ["Mục đích", "Cụm từ"],
        ["Mở đầu", "Today I'd like to talk about… / I've divided my talk into three parts."],
        ["Chuyển ý", "Moving on to… / Let's now turn to…"],
        ["Nhấn mạnh", "What's important here is… / I'd like to highlight…"],
        ["Kết thúc", "To sum up… / Thank you for listening. Are there any questions?"],
      ),
      tip("Khi chỉ vào slide, nói **As you can see on this slide…** thay vì **You see this slide**. Nghe tự nhiên và chuyên nghiệp hơn nhiều."),
    ],
  },
  words: [
    word("audience", "/ˈɔː.di.əns/", "khán giả, người nghe", "Try to make eye contact with your audience.", "au|di|ence", 0),
    word("highlight", "/ˈhaɪ.laɪt/", "làm nổi bật, nhấn mạnh", "I'd like to highlight three key results.", "high|light", 0),
    word("illustrate", "/ˈɪl.ə.streɪt/", "minh họa", "This graph illustrates our sales trend.", "il|lus|trate", 0, "Trọng âm ở âm tiết đầu: IL-lus-trate."),
    word("revenue", "/ˈrev.ən.juː/", "doanh thu", "Revenue rose by ten per cent last quarter.", "rev|e|nue", 0),
    word("conclusion", "/kənˈkluː.ʒən/", "phần kết luận", "In conclusion, the project was a success.", "con|clu|sion", 1),
    word("overview", "/ˈəʊ.və.vjuː/", "cái nhìn tổng quan", "Let me start with a brief overview.", "o|ver|view", 0),
    word("slide", "/slaɪd/", "trang trình chiếu", "As you can see on this slide, costs have fallen.", "slide", 0, "Nhớ bật âm /d/ ở cuối."),
  ],
  exercises: [
    mc("b2-5-1", "The engineer ___ designed the system will answer your questions.", ["which", "who", "whose"], 1, "Chỉ người dùng who."),
    mc("b2-5-2", "We chose a partner ___ experience in Asia is excellent.", ["who", "which", "that", "whose"], 3, "Whose chỉ sở hữu: kinh nghiệm của đối tác."),
    mc("b2-5-3", "Which sentence is punctuated correctly?", ["My boss, who lives in Da Nang, is visiting us.", "My boss who lives in Da Nang, is visiting us.", "My boss, that lives in Da Nang, is visiting us."], 0, "Mệnh đề không xác định đặt giữa hai dấu phẩy và dùng who, không dùng that."),
    fill("b2-5-4", "The new app, ___ was launched last month, has ten thousand users.", ["which"], "Sau dấu phẩy, chỉ vật dùng which."),
    fill("b2-5-5", "Now let's ___ to the second part of my presentation.", ["turn", "move", "go", "come", "proceed"], "Let's turn to / Let's move on to (hoặc go to, come to): chuyển sang phần tiếp theo."),
    reorder("b2-5-6", "I've divided my talk into three parts.", "Câu mở đầu giới thiệu bố cục bài thuyết trình."),
    listen("b2-5-7", "To sum up, our revenue has grown steadily.", ["Tóm lại, doanh thu của chúng ta đã tăng đều đặn.", "Trước hết, doanh thu của chúng ta giảm mạnh.", "Doanh thu của chúng ta cần tăng nhanh hơn."], 0, "To sum up dùng để tóm tắt ở phần kết."),
    listen("b2-5-8", "This is the client whose order we delayed.", ["Đây là khách hàng đã hủy đơn hàng.", "Đây là khách hàng có đơn hàng bị chúng ta giao chậm.", "Đây là khách hàng đã giao hàng chậm."], 1),
  ],
  speaking: [
    say("Today I'd like to talk about our results for this year.", "Hôm nay tôi muốn nói về kết quả năm nay của chúng ta."),
    say("Our team, which has twelve members, works in three countries.", "Nhóm của chúng tôi, gồm mười hai thành viên, làm việc ở ba quốc gia."),
    say("Thank you for listening. Are there any questions?", "Cảm ơn mọi người đã lắng nghe. Có ai có câu hỏi không?"),
  ],
});

const damPhan = lesson({
  slug: "dam-phan-va-thuyet-phuc",
  title: "Đàm phán và thuyết phục",
  minutes: 24,
  lecture: {
    title: "Ngôn ngữ mềm, đề xuất và nhượng bộ",
    blocks: [
      p("Người Việt khi đàm phán bằng tiếng Anh hay dùng câu quá thẳng như **We want a lower price.** Người nghe có thể thấy bạn thiếu thiện chí. Hãy **nói giảm, nói mềm** bằng cách dùng thì quá khứ tiếp diễn, động từ khuyết thiếu và từ giảm nhẹ."),
      table(
        ["Câu thẳng", "Câu mềm hơn"],
        ["We want a discount.", "We were wondering if you could offer a discount."],
        ["Your price is too high.", "Your price seems a little high for us."],
        ["Deliver it next week.", "Would you be willing to deliver it next week?"],
        ["That's impossible.", "I'm afraid that might be difficult for us."],
      ),
      ex("I was wondering if we could extend the deadline.", "Tôi đang nghĩ không biết liệu chúng ta có thể gia hạn hạn chót được không.", "Quá khứ tiếp diễn “was wondering” làm lời đề nghị nhẹ nhàng hơn, không mang nghĩa quá khứ."),
      ex("Would you be willing to consider a two-year contract?", "Anh/chị có sẵn lòng cân nhắc một hợp đồng hai năm không?"),
      p("Khi đưa ra **đề xuất có điều kiện**, dùng **If you…, we could/would…** hoặc **provided that / as long as**. Khi **nhượng bộ**, dùng **We're prepared to… if…** để luôn đổi lại một điều có lợi."),
      ex("If you order five hundred units, we could offer a ten per cent discount.", "Nếu quý công ty đặt năm trăm sản phẩm, chúng tôi có thể giảm giá mười phần trăm."),
      mistake("I was wondering if could you lower the price.", "I was wondering if you could lower the price.", "Sau “I was wondering if” là trật tự câu kể: chủ ngữ đứng trước động từ, không đảo như câu hỏi."),
      mistake("We will agree provided that you will pay in advance.", "We will agree provided that you pay in advance.", "Sau provided that / as long as dùng thì hiện tại đơn khi nói về tương lai, giống mệnh đề if."),
      tip("Đừng từ chối bằng **No.** trơn. Hãy mở đầu bằng **I see your point, but…** hoặc **I'm afraid we can't…, but we could…** để giữ không khí hợp tác."),
    ],
  },
  words: [
    word("negotiate", "/nəˈɡəʊ.ʃi.eɪt/", "đàm phán", "We need to negotiate better terms with the supplier.", "ne|go|ti|ate", 1),
    word("compromise", "/ˈkɒm.prə.maɪz/", "sự thỏa hiệp", "Both sides had to make a compromise.", "com|pro|mise", 0),
    word("discount", "/ˈdɪs.kaʊnt/", "sự giảm giá", "Could you offer a discount for bulk orders?", "dis|count", 0),
    word("contract", "/ˈkɒn.trækt/", "hợp đồng", "The contract will be signed next week.", "con|tract", 0, "Danh từ nhấn âm đầu: CON-tract. Động từ “contract” (co lại) nhấn âm sau."),
    word("flexible", "/ˈflek.sə.bəl/", "linh hoạt", "We can be flexible on the delivery date.", "flex|i|ble", 0),
    word("proposal", "/prəˈpəʊ.zəl/", "bản đề xuất", "They accepted our proposal after a long discussion.", "pro|pos|al", 1),
    word("concession", "/kənˈseʃ.ən/", "sự nhượng bộ", "We made a small concession on price.", "con|ces|sion", 1),
    word("deal", "/diːl/", "thỏa thuận, giao dịch", "I think we have a deal.", "deal", 0),
  ],
  exercises: [
    mc("b2-6-1", "Which request is the most polite?", ["Give us a better price.", "We want a better price now.", "We were wondering if you could improve your price.", "Your price is bad."], 2, "Was wondering if + S + could là cách đề nghị rất mềm mỏng."),
    mc("b2-6-2", "We can deliver next week as long as you ___ the order today.", ["will confirm", "confirm", "would confirm"], 1, "Sau as long as dùng hiện tại đơn khi nói về tương lai."),
    fill("b2-6-3", "Would you be ___ to share the costs?", ["willing", "prepared", "happy", "able"], "Would you be willing / prepared / happy to + V: anh/chị có sẵn lòng…? (Would you be able to: anh/chị có thể…?)"),
    fill("b2-6-4", "I'm ___ that we can't accept those terms.", ["afraid", "sorry"], "I'm afraid… (hoặc I'm sorry…) giúp lời từ chối bớt gay gắt."),
    mc("b2-6-5", "“If you sign a three-year contract, we ___ offer free maintenance.”", ["could", "had", "have"], 0, "Đề xuất có điều kiện: If you + hiện tại, we could + V."),
    reorder("b2-6-6", "We are prepared to offer a small discount.", "Be prepared to + V: sẵn sàng làm gì, thường dùng khi nhượng bộ."),
    listen("b2-6-7", "I see your point, but we need a longer contract.", ["Tôi hoàn toàn đồng ý với anh/chị.", "Chúng tôi không cần hợp đồng dài hạn.", "Tôi muốn xem lại bản hợp đồng.", "Tôi hiểu ý anh/chị, nhưng chúng tôi cần một hợp đồng dài hơn."], 3, "I see your point, but… vừa ghi nhận ý kiến đối phương vừa đưa ra quan điểm của mình."),
    listen("b2-6-8", "Would you be willing to pay half in advance?", ["Anh/chị có sẵn lòng trả trước một nửa không?", "Anh/chị đã trả trước một nửa chưa?", "Chúng tôi sẽ trả trước một nửa."], 0),
  ],
  speaking: [
    say("I was wondering if you could offer a small discount.", "Tôi đang nghĩ liệu anh/chị có thể giảm giá một chút không."),
    say("If you order two hundred units, we could deliver for free.", "Nếu anh/chị đặt hai trăm sản phẩm, chúng tôi có thể giao hàng miễn phí."),
    say("I see your point, but we need more time.", "Tôi hiểu ý anh/chị, nhưng chúng tôi cần thêm thời gian."),
  ],
});

export const tiengAnhB2: Course = {
  slug: "tieng-anh-b2",
  title: "Tiếng Anh B2: Tiếng Anh công việc",
  level: "B2",
  goal: "lo-trinh",
  summary: "Cho người đi làm: viết email, họp, thuyết trình và đàm phán bằng tiếng Anh tự tin, đúng văn phong công sở.",
  outcomes: [
    "Viết email công việc trang trọng, lịch sự và rõ ràng",
    "Tham gia họp, suy đoán, xen ngang và hỏi lại một cách khéo léo",
    "Tường thuật lời người khác và rút kinh nghiệm bằng câu điều kiện",
    "Thuyết trình mạch lạc và đàm phán bằng ngôn ngữ mềm mỏng",
  ],
  audience: [
    "Người đi làm cần dùng tiếng Anh với đồng nghiệp, khách hàng hoặc đối tác nước ngoài",
    "Người đã học xong B1 muốn nâng tiếng Anh lên mức làm việc chuyên nghiệp",
  ],
  teacher: {
    name: "Thầy Michael Grant",
    initials: "MG",
    bio: "12 năm giảng dạy tiếng Anh thương mại, thạc sĩ TESOL. Từng đào tạo nhân viên cho nhiều doanh nghiệp đa quốc gia tại TP.HCM.",
  },
  priceVnd: 990_000,
  durationWeeks: 10,
  rating: 4.9,
  reviews: [
    { name: "Thu Trang", role: "Chuyên viên xuất nhập khẩu, Hải Phòng", quote: "Trước đây email của mình toàn câu mệnh lệnh mà không biết. Sau bài đầu tiên, đối tác phản hồi nhanh và thân thiện hơn hẳn." },
    { name: "Hoàng Nam", role: "Trưởng nhóm kinh doanh, TP.HCM", quote: "Phần đàm phán rất thực tế. Mình áp dụng ngay các mẫu câu nói giảm trong buổi họp với khách hàng Singapore." },
  ],
  faqs: [
    { q: "Mình cần trình độ nào để học khóa B2?", a: "Bạn nên nắm chắc ngữ pháp B1 như thì hiện tại hoàn thành, câu bị động và câu điều kiện loại 1, 2. Nếu chưa chắc, hãy làm bài kiểm tra xếp lớp trước." },
    { q: "Học xong B2 thì học gì tiếp?", a: "Bạn học tiếp khóa C1 để luyện diễn đạt tinh tế, học thuật và tự nhiên như người bản xứ. Mỗi cấp có chứng chỉ riêng." },
  ],
  status: "open",
  modules: [
    { id: "m1", title: "Giao tiếp nơi công sở", lessons: [vietEmail, hopThaoLuan, tuongThuat] },
    { id: "m2", title: "Lập luận và thuyết phục", lessons: [tiecNuoi, thuyetTrinh, damPhan] },
  ],
};
