import { A, B, dialogue, ex, fill, lesson, listen, mc, mistake, p, reorder, say, summary, table, task, teacher, tip, word } from "../builders";
import nTinhLuocVaThayThe from "../lessons/c1/tinh-luoc-va-thay-the";
import nTuongLaiNangCao from "../lessons/c1/tuong-lai-nang-cao";
import nCauTaoTu from "../lessons/c1/cau-tao-tu";
import nDieuKienNangCao from "../lessons/c1/dieu-kien-nang-cao";
import nBangThaiCach from "../lessons/c1/bang-thai-cach";
import nDongTuTuongThuat from "../lessons/c1/dong-tu-tuong-thuat";
import nBiDongNangCao from "../lessons/c1/bi-dong-nang-cao";
import nMenhDeQuanHeNangCao from "../lessons/c1/menh-de-quan-he-nang-cao";
import nTrangTuBinhLuan from "../lessons/c1/trang-tu-binh-luan";
import nVietLuanVaTomTat from "../lessons/c1/viet-luan-va-tom-tat";
import { chapter } from "../review";
import type { Course } from "../types";

const noiTuNhien = lesson({
  slug: "noi-tu-nhien",
  title: "Nói tự nhiên như người bản xứ",
  minutes: 20,
  lecture: {
    title: "Cụm động từ và kết hợp từ tự nhiên",
    blocks: [
      p("Hãy hình dung bạn đang họp trực tuyến với đồng nghiệp người Úc. Bạn nói: “We should postpone the meeting.” Họ hiểu, nhưng chính họ sẽ nói: “Let's put it off till Friday.” Câu của bạn không sai, chỉ là nghe như **đọc công văn**. Ở trình độ C1, cái khoảng cách giữa “đúng” và “tự nhiên” chính là thứ bài này muốn lấp đầy."),
      p("Nhiều người học trình độ cao nói đúng ngữ pháp nhưng vẫn nghe “sách vở”. Lý do chính: dùng từ đơn trang trọng thay vì **phrasal verb** (cụm động từ), và ghép từ theo kiểu dịch từ tiếng Việt thay vì theo **collocation** (kết hợp từ cố định)."),
      table(
        ["Loại", "Ví dụ", "Vị trí tân ngữ", "Ghi chú"],
        ["Tách được (separable)", "put off, turn down, figure out", "put the meeting off / put it off", "Đại từ bắt buộc đứng giữa"],
        ["Không tách được (inseparable)", "look after, come across, run into", "look after the kids / look after them", "Tân ngữ luôn đứng sau tiểu từ"],
        ["Ba thành phần", "put up with, come up with, look forward to", "put up with the noise / put up with it", "Thường không tách được"],
      ),
      p("Quy tắc vàng: với phrasal verb tách được, nếu tân ngữ là **đại từ** (it, them, him), đại từ phải chen vào **giữa** động từ và tiểu từ."),
      mistake("Can you turn down it?", "Can you turn it down?", "Với phrasal verb tách được, đại từ phải đứng giữa động từ và tiểu từ."),
      ex("I came across an old photo while I was clearing out the attic.", "Tôi tình cờ thấy một bức ảnh cũ khi đang dọn gác mái.", "come across không tách được, nên không nói come an old photo across."),
      ex("Let's put the meeting off until Friday. Actually, let's put it off until next week.", "Mình hoãn cuộc họp đến thứ Sáu nhé. À thôi, hoãn hẳn sang tuần sau đi.", "Với danh từ (the meeting), bạn có thể nói put the meeting off hoặc put off the meeting. Với đại từ (it), chỉ có một cách: put it off."),
      p("Collocation là những từ người bản xứ quen dùng cùng nhau. Tiếng Việt nói “mưa to”, nhưng tiếng Anh nói **heavy rain**, không nói big rain. Phân biệt **make** và **do** cũng là lỗi rất phổ biến của người Việt, vì cả hai đều dịch là “làm”."),
      table(
        ["Nhóm", "Kết hợp tự nhiên", "Tránh dùng"],
        ["make", "make a decision, make progress, make an effort", "do a decision, do an effort"],
        ["do", "do research, do damage, do someone a favour", "make research, make a favour"],
        ["take", "take a risk, take responsibility, take something into account", "make a risk"],
        ["tính từ + danh từ", "heavy rain, strong coffee, a high chance", "big rain, thick coffee, a big chance"],
      ),
      ex("We need to take the budget into account before we make a final decision.", "Chúng ta cần tính đến ngân sách trước khi đưa ra quyết định cuối cùng."),
      mistake("Our team did a big progress this quarter.", "Our team made significant progress this quarter.", "Progress đi với make và là danh từ không đếm được nên không có a. Big progress nghe không tự nhiên; hãy dùng significant hoặc considerable."),
      mistake("The price of this laptop is very expensive.", "The price of this laptop is very high.", "Tiếng Việt nói “giá đắt” nên người Việt ghép price với expensive. Trong tiếng Anh, expensive dùng cho món đồ (This laptop is expensive), còn price đi với high hoặc low."),
      table(
        ["Văn phong (register)", "Khi nào dùng", "Cùng một ý: xin hoãn cuộc gọi"],
        ["Thân mật", "nhắn tin, nói với đồng nghiệp thân", "Something's come up. Can we put the call off till Friday?"],
        ["Trung tính", "email công việc hằng ngày", "Something has come up. Could we move the call to Friday?"],
        ["Trang trọng", "thư gửi khách hàng, cấp trên, đối tác mới", "I'm afraid we will have to postpone the call until Friday due to unforeseen circumstances."],
      ),
      tip("Người dùng C1 không chỉ nói tự nhiên, mà còn biết **đổi văn phong** theo người nghe. Phrasal verb và câu ngắn hợp với văn thân mật; từ đơn gốc Latinh như **postpone**, **tolerate**, **investigate** hợp với văn trang trọng. Khi học từ mới, hãy ghi cả cụm, ví dụ **make a decision** thay vì chỉ **decision**. Trước khi viết email quan trọng, tra từ điển collocation để kiểm tra từ nào thường đi với từ nào."),
      tip("Mẹo phát âm: trong phrasal verb, trọng âm thường rơi vào **tiểu từ**, không rơi vào động từ: put it **OFF**, come **ACROSS**, turn it **DOWN**. Nhớ nối âm cuối của động từ với đại từ: turn it down đọc liền thành /tɜː.nɪt/, đừng tách từng chữ như đọc chính tả."),
      teacher("Sau nhiều năm đứng lớp, tôi thấy một điều lạ: học viên giỏi ngữ pháp nhất lại thường nói cứng nhất, vì các bạn quen dịch từng chữ từ tiếng Việt. Cách chữa rất đơn giản. **Mỗi ngày chọn một phrasal verb**, đặt ba câu về chính đời mình: công việc, gia đình, chuyến đi gần nhất. Cuối tuần, lấy một email mình đã viết, gạch dưới các từ trang trọng như postpone, investigate, tolerate, rồi tự hỏi: nếu nói với đồng nghiệp bên ly cà phê, mình sẽ dùng cụm nào? Làm đều ba tháng, các bạn sẽ nghe chính mình khác hẳn."),
      summary(
        "Phrasal verb tách được: đại từ **bắt buộc** đứng giữa (turn it down, put it off); danh từ đứng giữa hay sau tiểu từ đều được.",
        "Phrasal verb không tách được (look after, come across, run into) và cụm ba thành phần (put up with): tân ngữ **luôn đứng sau**.",
        "Make và do đều là “làm”, nên đừng đoán: học **theo cụm** (make a decision, make progress, do research, take a risk).",
        "Kết hợp tính từ với danh từ theo thói quen người bản xứ: heavy rain, a high price, significant progress, không dịch từng chữ.",
        "Đổi **văn phong** theo người nghe: phrasal verb cho câu thân mật, từ gốc Latinh (postpone, tolerate) cho thư trang trọng.",
      ),
    ],
  },
  words: [
    word("collocation", "/ˌkɒl.əˈkeɪ.ʃən/", "kết hợp từ (các từ thường đi cùng nhau)", "Heavy rain is a common collocation in English.", "col|lo|ca|tion", 2),
    word("idiomatic", "/ˌɪd.i.əˈmæt.ɪk/", "tự nhiên, đúng kiểu người bản xứ", "Her English is fluent and highly idiomatic.", "id|i|o|mat|ic", 3),
    word("inseparable", "/ɪnˈsep.ər.ə.bəl/", "không thể tách rời", "Look after is an inseparable phrasal verb.", "in|sep|a|ra|ble", 1),
    word("postpone", "/pəʊstˈpəʊn/", "hoãn lại", "The board decided to postpone the launch until spring.", "post|pone", 1, "Đây là cách nói trang trọng của put off. Trong hội thoại, người bản xứ hay nói put off hơn."),
    word("tolerate", "/ˈtɒl.ər.eɪt/", "chịu đựng, dung thứ", "I won't tolerate rudeness in meetings.", "tol|er|ate", 0, "Trang trọng hơn put up with."),
    word("substantial", "/səbˈstæn.ʃəl/", "đáng kể, lớn", "The new policy made a substantial difference to staff morale.", "sub|stan|tial", 1),
    word("overlook", "/ˌəʊ.vəˈlʊk/", "bỏ sót, không để ý tới", "It's easy to overlook small errors when you're tired.", "o|ver|look", 2),
  ],
  exercises: [
    mc("c1-1-1", "Chọn câu đúng.", ["Could you turn down it?", "Could you turn it down?", "Could you it turn down?"], 1, "Turn down tách được, nên đại từ it phải đứng giữa: turn it down."),
    mc("c1-1-2", "Scientists are ___ research into the effects of sleep deprivation.", ["making", "taking", "doing"], 2, "Research đi với do (hoặc carry out), không đi với make."),
    fill("c1-1-3", "I can't put up ___ his constant complaining any longer.", ["with"], "Put up with là cụm ba thành phần, nghĩa là chịu đựng."),
    fill("c1-1-4", "Investing all your savings in one company means ___ a huge risk (chấp nhận).",["taking", "running"], "Tiếng Anh nói take a risk hoặc run a risk, không nói make a risk."),
    reorder("c1-1-5", "She came up with a brilliant solution.", "Come up with nghĩa là nghĩ ra, và không bao giờ tách."),
    reorder("c1-1-6", "Could you look after my plants for me?", "Look after không tách được: tân ngữ my plants đứng sau after."),
    listen("c1-1-7", "Something's come up. Can we put the call off till Friday?", ["Có việc đột xuất rồi. Mình hoãn cuộc gọi đến thứ Sáu được không?", "Có việc đột xuất nên mình gọi sớm hơn vào thứ Sáu nhé.", "Cuộc gọi hôm thứ Sáu đã bị hủy hẳn."], 0, "Put off là hoãn, cách nói thân mật của postpone. Trong thư trang trọng, cùng ý này sẽ là: I'm afraid we will have to postpone the call."),
    listen("c1-1-8", "I ran into an old colleague at the conference.", ["Tôi chạy đến chỗ một đồng nghiệp cũ ở hội nghị.", "Tôi tình cờ gặp một đồng nghiệp cũ ở hội nghị.", "Tôi va phải một đồng nghiệp cũ ở hội nghị."], 1, "Run into someone nghĩa là tình cờ gặp ai đó."),
  ],
  speaking: [
    say("I'll look into it and get back to you tomorrow.", "Tôi sẽ xem xét việc này và phản hồi bạn vào ngày mai."),
    say("We need to make a decision before we take any more risks.", "Chúng ta cần đưa ra quyết định trước khi chấp nhận thêm rủi ro."),
    say("I can't put up with this noise any longer.", "Tôi không thể chịu đựng tiếng ồn này thêm nữa."),
  ],
  dialogue: dialogue(
    "Hoãn buổi demo với khách hàng",
    "Cuộc họp trực tuyến giữa Sarah, trưởng dự án người Úc, và Minh, kỹ sư phần mềm người Việt. Khách hàng vừa báo có việc đột xuất, cả nhóm phải dời buổi demo và quyết định cách xử lý một lỗi đăng nhập.",
    { A: "Sarah (trưởng dự án)", B: "Minh (kỹ sư phần mềm)" },
    A("Minh, something's come up on the client's side. Can we put the demo off till Thursday?", "Minh này, bên khách hàng có việc đột xuất. Mình hoãn buổi demo đến thứ Năm được không?"),
    B("Sure, we can put it off. Actually, that gives us time to figure out the login bug.", "Được chứ, mình hoãn được. Thật ra như vậy còn có thời gian tìm ra nguyên nhân lỗi đăng nhập."),
    A("Good. Have you made any progress on it?", "Tốt. Anh đã có tiến triển gì chưa?"),
    B("Some. I came across a similar issue on a developer forum, and Lan came up with a workaround.", "Có chút ít. Tôi tình cờ thấy một lỗi tương tự trên diễn đàn lập trình, và Lan đã nghĩ ra một cách xử lý tạm."),
    A("Great. But before we make a final decision, we need to take the security risks into account.", "Tuyệt. Nhưng trước khi đưa ra quyết định cuối cùng, chúng ta cần tính đến các rủi ro bảo mật."),
    B("Agreed. I'll look into it this afternoon and get back to you by five.", "Đồng ý. Chiều nay tôi sẽ xem xét việc đó và phản hồi chị trước năm giờ."),
    A("Perfect. And how's the team coping with all the overtime?", "Tuyệt. Còn cả đội xoay xở thế nào với chừng ấy giờ làm thêm?"),
    B("Honestly, they've been putting up with a lot. I'd rather not take the risk of burning them out.", "Thật lòng mà nói, mọi người đã chịu đựng khá nhiều. Tôi không muốn liều để họ kiệt sức."),
    A("Fair enough. I'll turn down the client's request for extra features this sprint.", "Hợp lý. Tôi sẽ từ chối yêu cầu thêm tính năng của khách trong đợt làm việc này."),
    B("Thanks. I'll write to the client myself, though. With them, I'd say postpone rather than put off.", "Cảm ơn chị. Nhưng để tôi tự viết thư cho khách. Với họ, tôi sẽ dùng postpone chứ không dùng put off."),
  ),
  task: task({
    prompt: "Buổi demo với khách hàng phải dời từ thứ Ba sang thứ Năm. Hãy viết hai đoạn cùng một nội dung nhưng khác văn phong: (1) email trang trọng gửi khách hàng; (2) tin nhắn thân mật gửi đồng nghiệp, nhờ người đó kiểm tra phần bảo mật.",
    hints: [
      "Email: dùng từ trang trọng như postpone, due to, convenient; tránh phrasal verb đời thường.",
      "Tin nhắn: dùng ít nhất ba phrasal verb (put off, look into, get back to, come up with...), đặt đại từ đúng chỗ.",
      "Chèn ít nhất hai collocation của bài: make progress, take something into account, make a decision.",
    ],
    model:
      "Email to the client: Dear Mr Harris, I am afraid we will have to postpone Tuesday's product demonstration until Thursday at ten o'clock, due to an unforeseen technical issue. Our team has made significant progress in resolving it, and we would like to take your security requirements fully into account before presenting the final version. Please let me know whether the new time is convenient for you. Kind regards, Minh.\n\nMessage to a colleague: Hi Lan, something's come up with the login bug, so we've put the demo off till Thursday. Your workaround was brilliant, by the way. Could you look into the security side this afternoon and get back to me before five? Thanks a lot!",
    checklist: [
      "Email không có phrasal verb thân mật, có lời chào và lời kết trang trọng",
      "Tin nhắn có ít nhất ba phrasal verb, đại từ đứng giữa khi cần (put it off, không viết put off it)",
      "Dùng đúng ít nhất hai collocation (make progress, take ... into account, make a decision)",
      "Không có lỗi make/do như do a decision hay make research",
      "Đọc hai đoạn liền nhau, người nghe nhận ra ngay đâu là thư gửi khách, đâu là tin nhắn cho đồng nghiệp",
    ],
    minWords: 90,
  }),
});

const daoNgu = lesson({
  slug: "dao-ngu-de-nhan-manh",
  title: "Đảo ngữ để nhấn mạnh",
  minutes: 22,
  lecture: {
    title: "Đảo ngữ phủ định",
    blocks: [
      p("Bạn nghe một bài phát biểu tốt nghiệp và diễn giả mở đầu: “Never before have we faced such a challenge.” Hay bạn đọc một bài IELTS Writing điểm cao: “Not only does tourism create jobs, but it also...” Nhiều học viên Việt nhìn thấy trợ động từ đứng trước chủ ngữ thì tưởng là câu hỏi. Thật ra đó là **đảo ngữ**, công cụ để người viết đặt sức nặng vào ý mình muốn nói."),
      p("Khi một trạng từ hoặc cụm từ mang nghĩa phủ định hoặc hạn chế (**never**, **rarely**, **seldom**, **hardly**, **little**, **not only**, **only after**) được đưa lên đầu câu, trợ động từ phải đứng **trước** chủ ngữ, giống cấu trúc câu hỏi. Cách này tạo sức nặng và kịch tính, thường gặp trong văn viết, diễn văn và bài thi IELTS."),
      table(
        ["Cấu trúc", "Câu thường", "Câu đảo ngữ"],
        ["Never", "I have never seen such chaos.", "Never have I seen such chaos."],
        ["Rarely / Seldom", "We rarely get feedback this detailed.", "Rarely do we get feedback this detailed."],
        ["Not only ... but also", "She not only wrote the report but also presented it.", "Not only did she write the report, but she also presented it."],
        ["Hardly ... when", "I had hardly sat down when the phone rang.", "Hardly had I sat down when the phone rang."],
        ["No sooner ... than", "He had no sooner arrived than he was asked to leave.", "No sooner had he arrived than he was asked to leave."],
        ["Only after", "We understood the problem only after the audit.", "Only after the audit did we understand the problem."],
        ["Little", "I didn't realise how serious it was.", "Little did I realise how serious it was."],
      ),
      p("Hai điểm người Việt hay sai. Thứ nhất, câu ở thì hiện tại đơn và quá khứ đơn phải **mượn do/does/did**, và động từ chính trở về nguyên mẫu (riêng động từ be thì đảo trực tiếp: Never was I so nervous). Thứ hai, với **Only after**, **Only when** và **Not until**, đảo ngữ nằm ở **mệnh đề chính**, không nằm ở mệnh đề đi ngay sau only."),
      mistake("Rarely we see such dedication.", "Rarely do we see such dedication.", "Sau trạng từ phủ định ở đầu câu phải đảo trợ động từ lên trước chủ ngữ; thì hiện tại đơn thì mượn do."),
      mistake("Only after he left did I realised my mistake.", "Only after he left did I realise my mistake.", "Đã có did thì động từ chính phải ở nguyên mẫu. Đảo ngữ nằm ở mệnh đề chính (did I realise), không đảo ở he left."),
      ex("No sooner had we launched the product than competitors began to copy it.", "Chúng tôi vừa ra mắt sản phẩm thì đối thủ đã bắt đầu sao chép.", "Hardly đi với when, No sooner đi với than. Đừng trộn lẫn hai cặp này."),
      ex("Not only does the plan save money, but it also reduces waste.", "Kế hoạch này không chỉ tiết kiệm tiền mà còn giảm lãng phí."),
      ex("Seldom have I worked with such a committed team.", "Hiếm khi tôi được làm việc với một đội tận tâm như vậy.", "Thì hiện tại hoàn thành đã có have nên chỉ cần đảo have lên trước I."),
      ex("Under no circumstances should you share your password with anyone.", "Trong bất kỳ trường hợp nào bạn cũng không được chia sẻ mật khẩu cho ai.", "Under no circumstances và In no way cũng gây đảo ngữ. Câu có động từ khuyết thiếu thì đảo chính động từ đó: should you share."),
      mistake("Hardly had I sat down than the phone rang.", "Hardly had I sat down when the phone rang.", "Tiếng Việt chỉ có một cách nói “vừa... thì...”, nên người Việt hay trộn hai cặp. Hãy học thuộc theo cặp: Hardly/Scarcely đi với when, No sooner đi với than."),
      tip("Mẹo nhớ: hãy coi nửa sau của câu đảo ngữ như một **câu hỏi**. Từ câu hỏi Have I ever seen such chaos?, chỉ cần thay ever bằng Never đặt lên đầu: **Never have I seen such chaos.** Khi đọc thành tiếng, nhấn mạnh vào từ phủ định đầu câu rồi ngừng rất nhẹ sau từ đó."),
      tip("Về **register** (văn phong): đảo ngữ nghe trang trọng và mạnh. Trong bài luận hay bài phát biểu, dùng một hai lần là đủ gây ấn tượng. Trong trò chuyện thường ngày, dùng quá nhiều sẽ nghe như đang **đọc diễn văn**."),
      teacher("Cái bẫy tôi gặp nhiều nhất ở học viên giỏi là thế này: các bạn đảo được trợ động từ, nhưng quên trả động từ chính về nguyên mẫu, thành ra viết Only then did I realised. Cách tự kiểm tra của tôi: cứ thấy **did** đứng trước chủ ngữ thì đưa mắt tìm ngay động từ phía sau, nó phải ở dạng nguyên mẫu trơn, không đuôi -ed, không đuôi -s. Mỗi tối, các bạn lấy ba câu bình thường mình đã nói trong ngày, viết lại thành ba câu đảo ngữ với Never, Rarely và Not only. Một tháng sau, cấu trúc này sẽ tự bật ra khi các bạn cần nhấn mạnh."),
      summary(
        "Từ phủ định hoặc hạn chế đứng đầu câu (Never, Rarely, Seldom, Little, Not only, Under no circumstances) thì **trợ động từ đứng trước chủ ngữ**, như câu hỏi.",
        "Hiện tại đơn và quá khứ đơn phải **mượn do/does/did**, động từ chính về nguyên mẫu: Only then did I realise, không viết did I realised.",
        "Với Only after, Only when, Not until: đảo ngữ nằm ở **mệnh đề chính**, không đảo ở mệnh đề ngay sau only.",
        "Học theo cặp: **Hardly/Scarcely ... when**, **No sooner ... than**; không trộn lẫn.",
        "Đảo ngữ thuộc văn phong trang trọng: hai ba câu ở chỗ then chốt của bài luận hay bài phát biểu là đủ.",
      ),
    ],
  },
  words: [
    word("inversion", "/ɪnˈvɜː.ʃən/", "sự đảo ngữ", "Negative inversion adds weight to a formal argument.", "in|ver|sion", 1),
    word("emphasis", "/ˈem.fə.sɪs/", "sự nhấn mạnh", "The speaker placed great emphasis on transparency.", "em|pha|sis", 0, "Danh từ đi với on (place emphasis on), nhưng động từ emphasise không có on: emphasise the point."),
    word("seldom", "/ˈsel.dəm/", "hiếm khi", "Seldom have I met such a dedicated team.", "sel|dom", 0),
    word("scarcely", "/ˈskeəs.li/", "vừa mới, hầu như không", "Scarcely had the meeting begun when the power went out.", "scarce|ly", 0),
    word("unprecedented", "/ʌnˈpres.ɪ.den.tɪd/", "chưa từng có tiền lệ", "The company faced unprecedented demand last year.", "un|prec|e|dent|ed", 1),
    word("register", "/ˈredʒ.ɪ.stər/", "văn phong, mức độ trang trọng", "Inversion belongs to a formal register.", "reg|is|ter", 0),
    word("rhetorical", "/rɪˈtɒr.ɪ.kəl/", "thuộc về tu từ", "Inversion is a powerful rhetorical device.", "rhe|tor|i|cal", 1),
  ],
  exercises: [
    mc("c1-2-1", "Never ___ such a well-organised conference.", ["I have attended", "have I attended", "I attended", "did I attended"], 1, "Never đứng đầu câu nên phải đảo trợ động từ have lên trước I."),
    mc("c1-2-2", "No sooner had the train left ___ it started to snow.", ["when", "that", "than"], 2, "No sooner luôn đi với than; hardly và scarcely mới đi với when."),
    fill("c1-2-3", "Rarely ___ we receive complaints about this product (trợ động từ của thì hiện tại đơn).", ["do"], "Thì hiện tại đơn nên mượn do để đảo ngữ."),
    fill("c1-2-4", "Only after the results were published ___ the scientists realise their error (trợ động từ của thì quá khứ đơn).", ["did"], "Đảo ngữ ở mệnh đề chính; động từ realise ở nguyên mẫu nên cần did."),
    reorder("c1-2-5", "Little did we know that the company was about to collapse.", "Little + did + chủ ngữ + know/realise: nhấn mạnh rằng lúc đó hoàn toàn không hề biết."),
    reorder("c1-2-6", "Not only did she miss the deadline, but she also lied.","Not only + did + chủ ngữ + động từ nguyên mẫu, but + chủ ngữ + also + động từ quá khứ."),
    listen("c1-2-7", "Not until I moved abroad did I appreciate my hometown.", ["Tôi chưa bao giờ thích quê mình dù đã ra nước ngoài.", "Mãi đến khi ra nước ngoài sống, tôi mới trân trọng quê hương.", "Tôi chuyển ra nước ngoài vì không thích quê mình."], 1, "Not until... did I... nghĩa là mãi đến khi... tôi mới..."),
    listen("c1-2-8", "Seldom does the board approve a budget this large.", ["Hội đồng quản trị thường duyệt ngân sách lớn như vậy.", "Hội đồng quản trị đã từ chối ngân sách này.", "Hội đồng quản trị hiếm khi duyệt một ngân sách lớn như thế này."], 2, "Seldom nghĩa là hiếm khi, không phải thường xuyên."),
  ],
  speaking: [
    say("Never have I seen such a talented group of students.", "Tôi chưa bao giờ thấy một nhóm sinh viên tài năng như vậy."),
    say("Not only does this plan save time, but it also cuts costs.", "Kế hoạch này không chỉ tiết kiệm thời gian mà còn cắt giảm chi phí."),
    say("Only after the meeting did I understand the real problem.", "Chỉ sau cuộc họp tôi mới hiểu vấn đề thực sự."),
  ],
  dialogue: dialogue(
    "Tập dượt bài phát biểu tổng kết năm",
    "Chị Hà, giám đốc điều hành một công ty logistics ở TP.HCM, đang cùng Tom, chuyên gia viết diễn văn người Anh, sửa phần mở đầu bài phát biểu trong buổi tiệc tổng kết năm. Chị muốn câu chữ có sức nặng hơn.",
    { A: "Chị Hà (giám đốc điều hành)", B: "Tom (chuyên gia viết diễn văn)" },
    A("Tom, my opening feels flat. “We have never faced a year like this” sounds so ordinary.", "Tom, phần mở đầu của tôi nghe nhạt quá. Câu “Chúng ta chưa bao giờ đối mặt với một năm như thế này” nghe bình thường quá."),
    B("Then let's invert it: “Never have we faced a year like this.” The weight falls on never.", "Vậy mình đảo ngữ nhé: “Chưa bao giờ chúng ta đối mặt với một năm như thế này.” Sức nặng dồn cả vào chữ never."),
    A("Much better. Next, I want to say the team didn't just survive; it actually grew.", "Hay hơn nhiều. Tiếp theo, tôi muốn nói rằng đội ngũ không chỉ trụ vững mà còn thực sự lớn mạnh."),
    B("Try this: “Not only did our team survive the crisis, but it also doubled its client base.”", "Thử câu này: “Đội ngũ của chúng ta không chỉ vượt qua khủng hoảng mà còn tăng gấp đôi số khách hàng.”"),
    A("And the supply chain part? We only understood the risk after the audit.", "Còn đoạn về chuỗi cung ứng? Mãi sau đợt kiểm toán chúng ta mới hiểu được rủi ro."),
    B("“Only after the audit did we understand how fragile our supply chain was.” Remember: did we understand, not did we understood.", "“Chỉ sau đợt kiểm toán chúng ta mới hiểu chuỗi cung ứng của mình mong manh đến mức nào.” Nhớ nhé: did we understand, không phải did we understood."),
    A("Got it. Could I also say “Hardly had we recovered than prices rose again”?", "Hiểu rồi. Tôi có thể nói thêm “Hardly had we recovered than prices rose again” được không?"),
    B("Almost. Hardly goes with when; no sooner goes with than. So: “Hardly had we recovered when prices rose again.”", "Gần đúng. Hardly đi với when; no sooner mới đi với than. Vậy là: “Chúng ta vừa mới hồi phục thì giá lại tăng.”"),
    A("How many of these should I use? I don't want to sound like a politician.", "Tôi nên dùng bao nhiêu câu kiểu này? Tôi không muốn nghe như một chính trị gia."),
    B("Two or three at the key moments. Seldom does an audience remember more than that.", "Hai ba câu ở những điểm then chốt thôi. Hiếm khi khán giả nhớ được nhiều hơn thế."),
    A("Fine. And under no circumstances should I read it word for word, right?", "Được. Và tôi tuyệt đối không nên đọc từng chữ, đúng không?"),
    B("Exactly. Little do most speakers realise how much eye contact matters.", "Chính xác. Hầu hết diễn giả hoàn toàn không nhận ra giao tiếp bằng mắt quan trọng đến mức nào."),
  ),
  task: task({
    prompt: "Viết đoạn mở đầu (khoảng một trăm từ) cho bài phát biểu tổng kết năm trước toàn công ty, hoặc cho lễ tốt nghiệp của lớp bạn. Dùng ba hoặc bốn câu đảo ngữ, mỗi câu một cấu trúc khác nhau, đặt ở những khoảnh khắc quan trọng nhất.",
    hints: [
      "Mở đầu bằng Never have I... hoặc Rarely do we... để gây ấn tượng ngay câu đầu.",
      "Nêu hai thành tích cùng lúc bằng Not only did... but ... also.",
      "Kể một bước ngoặt bằng Only after... did... hoặc Little did we know...",
      "Xen kẽ các câu bình thường để đảo ngữ không bị lạm dụng.",
    ],
    model:
      "Good evening, everyone. Never have I been prouder to stand in front of this team. Twelve months ago, we were close to losing our biggest client, and few of us believed that this setback would become our turning point. Yet it did. Not only did we keep that client, but we also won four new contracts in markets we had never entered before. Each deal we closed seemed to bring the next opportunity, and our partners noticed the difference. Only after the final figures came in did I fully appreciate what you had achieved. Very few companies grow this fast without cutting corners, yet you managed it with integrity. So tonight, let me simply say thank you.",
    checklist: [
      "Có ba hoặc bốn câu đảo ngữ, mỗi câu một cấu trúc khác nhau (không lạm dụng)",
      "Sau do/does/did đảo lên, động từ chính ở dạng nguyên mẫu",
      "Với Only after, Only when, Not until, đảo ngữ nằm ở mệnh đề chính",
      "Nếu dùng, Hardly đi với when và No sooner đi với than",
      "Có các câu thường xen giữa, đoạn văn không đảo ngữ liên tục",
    ],
    minWords: 90,
  }),
});

const cauChe = lesson({
  slug: "cau-che-va-nhan-manh",
  title: "Câu chẻ và nhấn mạnh",
  minutes: 20,
  lecture: {
    title: "Câu chẻ, do nhấn mạnh và đưa thành phần lên đầu câu",
    blocks: [
      p("Trong cuộc họp, sếp người nước ngoài nói với bạn: “So, Minh, you sent the report late.” Nhưng thực ra phần bị gửi muộn là của bộ phận tài chính, còn bạn gửi phần của mình đúng hạn. Bạn cần sửa lại thật rõ mà vẫn lịch sự: “Actually, **it was the finance team that** sent their part late. I did send mine on time.” Chỉ một câu, người nghe biết ngay đâu là thông tin cần sửa."),
      p("Tiếng Việt nhấn mạnh bằng giọng hoặc bằng từ “chính”, “chính là”. Khi viết tiếng Anh, bạn cần công cụ ngữ pháp: **câu chẻ** (cleft sentence), **do nhấn mạnh** và **fronting** (đưa một thành phần lên đầu câu)."),
      p("**It-cleft**: It + be + phần cần nhấn mạnh + that/who + phần còn lại. Dùng khi muốn sửa lại thông tin hoặc làm nổi bật một chi tiết."),
      table(
        ["Câu gốc", "Muốn nhấn mạnh", "Câu nhấn mạnh"],
        ["Linh sent the report on Monday.", "Người gửi", "It was Linh who sent the report on Monday."],
        ["Linh sent the report on Monday.", "Thứ được gửi", "It was the report that Linh sent on Monday."],
        ["Linh sent the report on Monday.", "Thời gian", "It was on Monday that Linh sent the report."],
        ["I need more time.", "Điều mình cần (wh-cleft)", "What I need is more time."],
        ["The price worries me.", "Điều khiến mình lo (wh-cleft)", "What worries me is the price."],
        ["I didn't understand the problem until the meeting.", "Thời điểm (Not until)", "It was not until the meeting that I understood the problem."],
      ),
      p("**Wh-cleft**: What + mệnh đề + be + phần nhấn mạnh. Cấu trúc này rất hữu ích để mở đầu ý chính khi thuyết trình: What we need to focus on is..."),
      ex("It wasn't the price that put customers off; it was the poor service.", "Không phải giá cả khiến khách hàng ngần ngại, mà là dịch vụ kém.", "Cấu trúc It wasn't X... it was Y dùng để bác bỏ và sửa thông tin."),
      mistake("What I need it is a break.", "What I need is a break.", "Trong câu wh-cleft, mệnh đề What I need đã là chủ ngữ, không thêm it."),
      ex("What we need is more staff, not more meetings.", "Cái chúng ta cần là thêm người, chứ không phải thêm cuộc họp.", "Dù phần sau mang nghĩa số nhiều (more staff), động từ be thường vẫn là is, vì chủ ngữ thực sự là cả mệnh đề What we need."),
      mistake("It was Linh sent the report.", "It was Linh who sent the report.", "Tiếng Việt nói “Chính Linh đã gửi báo cáo” mà không cần từ nối, nên người Việt hay bỏ who hoặc that. Trong câu chẻ, phải có who (cho người) hoặc that nối phần nhấn mạnh với phần còn lại."),
      p("**Do nhấn mạnh**: thêm do/does/did trước động từ nguyên mẫu trong câu khẳng định để khẳng định mạnh hoặc phản bác điều người khác nghĩ."),
      ex("I did send the email. Please check your spam folder.", "Tôi đã gửi email thật mà. Bạn kiểm tra thư mục thư rác nhé."),
      mistake("She does works hard.", "She does work hard.", "Sau do/does/did nhấn mạnh, động từ trở về nguyên mẫu."),
      tip("**Fronting**: đưa tân ngữ lên đầu câu để tạo tương phản, ví dụ: Some of his ideas I agree with; others I find unrealistic. Cách này hay gặp trong **văn nói trang trọng** và bài luận."),
      tip("Mẹo phát âm: khi nói, sức nặng của câu nhấn mạnh nằm ở **giọng**. Với do nhấn mạnh, đọc to và dài từ did: I **DID** send the email. Với câu chẻ, nhấn vào phần được làm nổi bật: It was **LINH** who sent it. Nếu đọc đều đều như câu thường, người nghe sẽ không nhận ra bạn đang sửa thông tin."),
      teacher("Người Việt mình vốn ngại nói thẳng “không phải thế”, nên nhiều bạn cứ im lặng khi bị hiểu nhầm trong cuộc họp. Tôi dặn các bạn: câu chẻ chính là cách **sửa sai mà không gây mất lòng**, vì nó nhắm vào thông tin chứ không nhắm vào người. Các bạn hãy thuộc lòng hai khung câu: It wasn't X that..., it was Y, và What I meant was... Tập nói to mỗi khung mười lần cho quen miệng, để đến lúc cần, câu tự ra chứ không phải nghĩ."),
      summary(
        "**It-cleft**: It + be + phần nhấn mạnh + who/that + phần còn lại. Không bao giờ bỏ who/that.",
        "**Wh-cleft**: What + mệnh đề + is + phần nhấn mạnh (What we need is more time); không thêm it sau mệnh đề What.",
        "Muốn sửa thông tin mà không mất lòng: **It wasn't X that..., it was Y**. Câu nhắm vào sự việc, không nhắm vào người.",
        "**Do/does/did nhấn mạnh** + động từ nguyên mẫu để khẳng định hoặc phản bác: I did send it, không viết I did sent it.",
        "Khi nói, **nhấn giọng** vào phần được làm nổi bật; đọc đều đều thì câu chẻ mất tác dụng.",
      ),
    ],
  },
  words: [
    word("emphatic", "/ɪmˈfæt.ɪk/", "dứt khoát, mang tính nhấn mạnh", "Her answer was an emphatic no.", "em|phat|ic", 1),
    word("contrast", "/ˈkɒn.trɑːst/", "sự tương phản", "The cleft sentence creates a sharp contrast between the two ideas.", "con|trast", 0, "Danh từ nhấn âm đầu, còn động từ nhấn âm sau: /kənˈtrɑːst/."),
    word("clarify", "/ˈklær.ɪ.faɪ/", "làm rõ", "Let me clarify what I meant.", "clar|i|fy", 0),
    word("highlight", "/ˈhaɪ.laɪt/", "làm nổi bật", "What I'd like to highlight is the cost.", "high|light", 0),
    word("misconception", "/ˌmɪs.kənˈsep.ʃən/", "quan niệm sai lầm", "It is a common misconception that grammar kills fluency.", "mis|con|cep|tion", 2),
    word("underlying", "/ˌʌn.dəˈlaɪ.ɪŋ/", "tiềm ẩn, nằm bên dưới", "What we need to address is the underlying cause.", "un|der|ly|ing", 2),
    word("crucial", "/ˈkruː.ʃəl/", "cực kỳ quan trọng", "What is crucial is that we act quickly.", "cru|cial", 0),
  ],
  exercises: [
    mc("c1-3-1", "Câu nào nhấn mạnh rằng chính Nam, không phải ai khác, đã phát hiện ra lỗi?", ["What Nam found was the error.", "Nam did find the error.", "It was Nam who found the error.", "The error was found by someone."], 2, "It was + người + who... nhấn mạnh người thực hiện hành động."),
    mc("c1-3-2", "What I really need ___ a long holiday.", ["is", "it is", "are", "that is"], 0, "Mệnh đề What I really need là chủ ngữ số ít, nên đi với is."),
    fill("c1-3-3", "It was in Hanoi ___ I first met my business partner.", ["that"], "Câu chẻ nhấn mạnh nơi chốn vẫn dùng that sau It was in Hanoi."),
    fill("c1-3-4", "I know you think I forgot, but I ___ call her yesterday.", ["did"], "Did nhấn mạnh để phản bác; động từ call giữ nguyên mẫu."),
    reorder("c1-3-5", "What we need to do is reduce our costs.", "Wh-cleft nhấn mạnh hành động: What + chủ ngữ + need to do + is + động từ nguyên mẫu."),
    reorder("c1-3-6", "It was not until midnight that I finished the report.", "It was not until + thời điểm + that + mệnh đề: mãi đến... mới..."),
    listen("c1-3-7", "It wasn't the software that failed; it was the training.", ["Phần mềm bị lỗi vì nhân viên chưa được đào tạo.", "Không phải phần mềm hỏng, mà là khâu đào tạo có vấn đề.", "Cả phần mềm lẫn khâu đào tạo đều thất bại."], 1, "It wasn't X... it was Y: không phải X, mà là Y."),
    listen("c1-3-8", "What surprised me was how quickly they agreed.", ["Điều làm tôi bất ngờ là họ đồng ý nhanh đến thế.", "Tôi bất ngờ vì họ không đồng ý.", "Họ bất ngờ vì tôi đồng ý quá nhanh."], 0),
  ],
  speaking: [
    say("What I'd like to focus on today is customer feedback.", "Điều tôi muốn tập trung vào hôm nay là phản hồi của khách hàng."),
    say("It was my mother who taught me to love reading.", "Chính mẹ tôi là người đã dạy tôi yêu việc đọc sách."),
    say("I do understand your concerns, but we need to move forward.", "Tôi thực sự hiểu những lo ngại của bạn, nhưng chúng ta cần tiến lên."),
  ],
  dialogue: dialogue(
    "Họp rút kinh nghiệm sau đợt ra mắt sản phẩm",
    "David, giám đốc khu vực người Anh, họp với Minh, trưởng nhóm marketing ở Hà Nội, sau một đợt ra mắt sản phẩm có doanh số thấp. David hiểu nhầm nguyên nhân, và Minh cần sửa lại thông tin một cách rõ ràng nhưng lịch sự.",
    { A: "David (giám đốc khu vực)", B: "Minh (trưởng nhóm marketing)" },
    A("Minh, the launch figures are disappointing. I assume the campaign started late.", "Minh, số liệu ra mắt đáng thất vọng quá. Tôi đoán là chiến dịch bắt đầu muộn."),
    B("Actually, the campaign did start on time. It was the stock that arrived late.", "Thật ra chiến dịch đã bắt đầu đúng hạn. Chính hàng hóa mới là thứ về muộn."),
    A("I see. So it was the warehouse team that caused the delay?", "Tôi hiểu. Vậy chính đội kho gây ra sự chậm trễ?"),
    B("Not exactly. It was customs clearance that held everything up, not our warehouse.", "Không hẳn. Chính khâu thông quan làm mọi thứ bị kẹt lại, chứ không phải kho của mình."),
    A("Fair enough. What worries me, though, is the customer feedback.", "Cũng được. Tuy vậy, điều khiến tôi lo là phản hồi của khách hàng."),
    B("I do understand that. What customers complained about most was the waiting time, not the product itself.", "Tôi thực sự hiểu điều đó. Điều khách phàn nàn nhiều nhất là thời gian chờ, chứ không phải bản thân sản phẩm."),
    A("That's a crucial distinction. So what do we need to change?", "Đó là điểm khác biệt rất quan trọng. Vậy chúng ta cần thay đổi gì?"),
    B("What we need to do is book customs agents two weeks earlier. It was only in the final week that we saw how slow they were.", "Điều chúng ta cần làm là đặt đại lý hải quan sớm hơn hai tuần. Mãi đến tuần cuối chúng tôi mới thấy họ chậm đến mức nào."),
    A("And the discount codes? Some people say they confused customers.", "Còn mã giảm giá thì sao? Có người nói chúng làm khách bối rối."),
    B("Some of the codes did cause confusion, I admit. The rest, customers used without any problem.", "Tôi thừa nhận một số mã đúng là gây nhầm lẫn. Còn số còn lại thì khách dùng không có vấn đề gì."),
    A("Thanks for clarifying, Minh. What I'd like from you is a one-page summary by Friday.", "Cảm ơn Minh đã làm rõ. Điều tôi muốn ở anh là một bản tóm tắt dài một trang trước thứ Sáu."),
    B("You'll have it by Thursday, actually. What I've already done is the outline.", "Thật ra thứ Năm anh đã có rồi. Phần tôi làm xong rồi là dàn ý."),
  ),
  task: task({
    prompt: "Cấp trên gửi email cho rằng nhóm bạn gây ra sự chậm trễ của một dự án, nhưng thực ra nguyên nhân nằm ở chỗ khác. Hãy viết email trả lời: sửa lại thông tin cho rõ, vẫn giữ thái độ hợp tác, và đề xuất cách khắc phục.",
    hints: [
      "Mở đầu bằng do nhấn mạnh để thể hiện bạn thật sự hiểu mối lo của họ: I do understand...",
      "Sửa thông tin sai bằng It wasn't X that..., it was Y.",
      "Nêu đề xuất bằng wh-cleft: What we propose is...",
      "Nhận phần trách nhiệm của mình (nếu có) để giọng thư công bằng, không đổ lỗi.",
    ],
    model:
      "Dear David, thank you for sharing the launch figures. I do understand your concern, and I would like to clarify one point. It was not the marketing campaign that started late; it was the stock that arrived two weeks behind schedule. What held up the shipment was customs clearance, which was largely outside our control. That said, it was our team that failed to plan for this risk, and I take responsibility for that. What we propose is to book customs agents a fortnight earlier for the next launch. It is at the planning stage, not in the final week, that this kind of delay can be prevented. I will send you a one-page summary on Thursday. Best regards, Minh",
    checklist: [
      "Có ít nhất một câu It-cleft đầy đủ who/that",
      "Có ít nhất một câu wh-cleft, không thừa it sau mệnh đề What",
      "Có một câu do/does/did nhấn mạnh với động từ nguyên mẫu",
      "Thông tin sai được sửa rõ ràng nhưng không trách móc người đọc",
      "Thư kết thúc bằng một đề xuất hoặc hành động cụ thể",
    ],
    minWords: 100,
  }),
});

const lapLuan = lesson({
  slug: "lap-luan-va-phan-bien",
  title: "Lập luận và phản biện",
  minutes: 22,
  lecture: {
    title: "Nhượng bộ và phản biện",
    blocks: [
      p("Đối tác nước ngoài nói: “Your price is higher than your competitors'.” Nếu bạn đáp ngay “No, our price is fine”, cuộc đàm phán sẽ căng thẳng. Người đàm phán giỏi sẽ nói: “**Admittedly**, our price is higher. **Even so**, our after-sales service saves you money in the long run.” Đề IELTS Task 2 dạng discuss both views cũng chấm đúng kỹ năng này."),
      p("Lập luận thuyết phục ở trình độ C1 không phải là phủ nhận hoàn toàn quan điểm đối lập, mà là **thừa nhận** phần hợp lý của nó rồi **phản bác**. Kỹ thuật này gọi là nhượng bộ (concession)."),
      table(
        ["Từ nối", "Theo sau là", "Ví dụ"],
        ["although / even though", "mệnh đề (S + V)", "Although the plan is costly, it will pay off."],
        ["despite / in spite of", "danh từ hoặc V-ing", "Despite the cost, the plan will pay off."],
        ["while", "mệnh đề, thường đứng đầu câu", "While I see your point, I disagree."],
        ["even so / nevertheless", "thường đứng đầu câu mới", "The plan is costly. Even so, it will pay off."],
        ["admittedly", "thường đứng đầu câu, để thừa nhận một điểm yếu", "Admittedly, the plan is costly."],
      ),
      mistake("Despite the plan is costly, it will pay off.", "Despite the fact that the plan is costly, it will pay off.", "Despite và in spite of không đi trực tiếp với mệnh đề. Hãy dùng although, hoặc thêm the fact that."),
      mistake("Although it was raining, but we went out.", "Although it was raining, we went out.", "Tiếng Việt nói “Mặc dù... nhưng...”, còn tiếng Anh chỉ dùng một liên từ: although hoặc but, không dùng cả hai."),
      mistake("Despite of the rain, the match went ahead.", "Despite the rain, the match went ahead.", "Người Việt hay nhập despite với in spite of thành despite of. Despite không bao giờ có of; in spite thì luôn phải có of."),
      ex("Despite having little experience, she was promoted within a year.", "Dù ít kinh nghiệm, cô ấy vẫn được thăng chức chỉ trong một năm.", "Despite + V-ing: người có ít kinh nghiệm phải chính là chủ ngữ của mệnh đề chính (she). Nếu không trùng chủ ngữ, hãy dùng although."),
      p("Một đoạn phản biện chặt chẽ thường gồm bốn bước: **nêu quan điểm đối lập**, **thừa nhận phần hợp lý**, **phản bác**, rồi **khẳng định lại quan điểm của mình**."),
      ex("Some argue that remote work harms collaboration.", "Một số người cho rằng làm việc từ xa làm giảm sự hợp tác.", "Bước một: nêu quan điểm đối lập."),
      ex("Admittedly, spontaneous conversations are less frequent online.", "Phải thừa nhận rằng các cuộc trò chuyện ngẫu hứng ít xảy ra hơn khi làm việc trực tuyến.", "Bước hai: thừa nhận."),
      ex("Even so, well-designed digital tools can more than make up for this.", "Dù vậy, các công cụ số được thiết kế tốt hoàn toàn có thể bù đắp điều này.", "Bước ba và bốn: phản bác và khẳng định lại."),
      p("Khi tranh luận **bằng lời nói** (họp, thảo luận nhóm, IELTS Speaking phần ba), người dùng C1 còn cần hai loại câu nữa: câu **nối ý mình vào ý người khác**, để cho thấy mình đang nghe; và câu **câu giờ** để có vài giây suy nghĩ mà không im lặng hay ậm ừ. Người Việt hay im lặng khi chưa nghĩ ra, và người nước ngoài hiểu đó là không có ý kiến."),
      table(
        ["Chức năng", "Câu mẫu"],
        ["Nối vào ý người trước", "Building on what Lan just said, I'd add that..."],
        ["Quay lại một ý đã nêu", "To come back to your point about costs, ..."],
        ["Xin chen vào lịch sự", "Sorry, could I just come in here?"],
        ["Nhượng bộ khi nói", "I take your point, but I'd see it slightly differently."],
        ["Câu giờ để suy nghĩ", "That's a good question. Let me think about that for a second."],
      ),
      tip("Các cụm như **That said**, **On the other hand**, **Be that as it may** (thành ngữ giả định các bạn đã gặp ở bài Thể giả định) giúp chuyển ý mượt mà. Tránh mở đầu mọi câu bằng **However**; thay đổi từ nối giúp bài viết tự nhiên hơn."),
      tip("Mẹo nhớ bằng một câu: **although đi với câu, despite đi với cụm**. Muốn kiểm tra, hãy xem phía sau có động từ chia thì hay không: có thì dùng although, không có thì dùng despite. Còn **despite không of, in spite phải có of**."),
      teacher("Năm mươi năm đứng lớp, chấm không biết bao nhiêu bài luận, tôi thấy bài của người Việt thường mạnh về ý nhưng yếu về giọng: hoặc phủ nhận sạch trơn quan điểm kia, hoặc gật gù đồng ý hết. Giám khảo muốn thấy các bạn **công bằng với đối phương rồi mới phản bác**. Trước khi viết, hãy tự hỏi: người phản đối mình sẽ nói gì, và họ đúng ở điểm nào? Viết điểm đúng đó ra bằng Admittedly, rồi mới lật lại bằng Even so. Chỉ một bước nhỏ ấy thôi, bài của các bạn đã chín chắn hơn hẳn."),
      summary(
        "**Although / even though** + mệnh đề (S + V); **despite / in spite of** + danh từ hoặc V-ing.",
        "Despite không có of, in spite luôn có of. Không dùng although cùng but trong một câu.",
        "Đoạn phản biện bốn bước: nêu ý đối lập, **thừa nhận** (Admittedly), **phản bác** (Even so), khẳng định lại quan điểm.",
        "Khi tranh luận bằng lời: nối vào ý người khác (Building on what... said), xin chen lịch sự (Could I just come in here?), câu giờ thay vì im lặng.",
        "Thay đổi từ nối (That said, Nevertheless, On the other hand); đừng mở mọi câu bằng However.",
      ),
    ],
  },
  words: [
    word("concession", "/kənˈseʃ.ən/", "sự nhượng bộ, sự thừa nhận", "Making a small concession can make your argument more convincing.", "con|ces|sion", 1),
    word("counterargument", "/ˈkaʊn.tər.ɑː.ɡjə.mənt/", "lập luận phản bác", "A strong essay anticipates the main counterargument.", "coun|ter|ar|gu|ment", 0),
    word("acknowledge", "/əkˈnɒl.ɪdʒ/", "thừa nhận", "I acknowledge that the proposal has some weaknesses.", "ac|know|ledge", 1, "Chữ k câm, đọc là /əkˈnɒl.ɪdʒ/."),
    word("rebuttal", "/rɪˈbʌt.əl/", "sự bác bỏ", "Her rebuttal was calm, precise and convincing.", "re|but|tal", 1),
    word("valid", "/ˈvæl.ɪd/", "hợp lý, có cơ sở", "You raise a valid point, but it doesn't change the overall picture.", "val|id", 0),
    word("nevertheless", "/ˌnev.ə.ðəˈles/", "tuy nhiên, dù vậy", "The risks are real. Nevertheless, the benefits outweigh them.", "nev|er|the|less", 3),
    word("compelling", "/kəmˈpel.ɪŋ/", "thuyết phục, đầy sức nặng", "She presented compelling evidence for the change.", "com|pel|ling", 1),
    word("undermine", "/ˌʌn.dəˈmaɪn/", "làm suy yếu", "One weak example can undermine your whole argument.", "un|der|mine", 2),
  ],
  exercises: [
    mc("c1-4-1", "___ the heavy traffic, we arrived on time.", ["Although", "Despite", "Even though", "However"], 1, "The heavy traffic là cụm danh từ, nên dùng despite. Although và even though cần một mệnh đề."),
    mc("c1-4-2", "Câu nào đúng?", ["Although he was tired, but he kept working.", "Despite he was tired, he kept working.", "Even though he was tired, he kept working."], 2, "Không dùng although cùng but; despite không đi trực tiếp với mệnh đề."),
    fill("c1-4-3", "In spite ___ the criticism, the director refused to change the ending.", ["of"], "Luôn là in spite of, còn despite thì không có of."),
    fill("c1-4-4", "The new system is expensive. Even ___, it will save us money in the long run.", ["so"], "Even so nghĩa là dù vậy, đứng đầu câu mới."),
    reorder("c1-4-5", "Could I just come in here?", "Câu xin chen vào lịch sự khi đang họp: could I just + come in. Just làm lời xin phép nhẹ nhàng hơn; trong câu nói thật, người ta thường thêm Sorry ở đầu."),
    reorder("c1-4-6", "Their success came despite a lack of funding.", "Despite + cụm danh từ (a lack of funding), không cần of."),
    listen("c1-4-7", "Admittedly, the plan has flaws, but it's the best option we have.", ["Kế hoạch có nhiều lỗi nên chúng ta nên bỏ nó.", "Kế hoạch hoàn hảo và là lựa chọn duy nhất.", "Chúng ta chưa có kế hoạch nào tốt.", "Phải thừa nhận kế hoạch có thiếu sót, nhưng đó là lựa chọn tốt nhất ta có."], 3, "Admittedly dùng để thừa nhận một điểm yếu trước khi phản bác."),
    listen("c1-4-8", "Even though the evidence is limited, the conclusion seems reasonable.", ["Mặc dù bằng chứng còn hạn chế, kết luận có vẻ hợp lý.", "Vì thiếu bằng chứng nên kết luận không hợp lý.", "Bằng chứng rất rõ ràng nên kết luận hợp lý."], 0),
  ],
  speaking: [
    say("I see your point, but I'm not sure it applies here.", "Tôi hiểu ý bạn, nhưng tôi không chắc nó áp dụng được trong trường hợp này."),
    say("Admittedly, the cost is high. Even so, it's worth it.", "Phải thừa nhận là chi phí cao. Dù vậy, nó vẫn đáng."),
    say("Despite the risks, I believe we should go ahead.", "Bất chấp rủi ro, tôi tin chúng ta nên tiến hành."),
  ],
  dialogue: dialogue(
    "Đàm phán giá với nhà nhập khẩu",
    "Ông Klein, giám đốc mua hàng của một công ty nội thất Đức, đang đàm phán hợp đồng năm tới với chị Hương, giám đốc kinh doanh một xưởng gỗ ở Bình Dương. Ông cho rằng giá của chị quá cao; chị cần thừa nhận điểm hợp lý rồi phản bác khéo léo.",
    { A: "Ông Klein (giám đốc mua hàng)", B: "Chị Hương (giám đốc kinh doanh)" },
    A("Ms Huong, I'll be frank. Your price is twelve per cent higher than your competitors'.", "Chị Hương, tôi nói thẳng nhé. Giá của chị cao hơn các đối thủ mười hai phần trăm."),
    B("Admittedly, our unit price is higher. Even so, our defect rate is the lowest in the region.", "Phải thừa nhận là đơn giá của chúng tôi cao hơn. Dù vậy, tỷ lệ hàng lỗi của chúng tôi thấp nhất khu vực."),
    A("I take your point, but my board looks at the invoice, not the defect rate.", "Tôi hiểu ý chị, nhưng hội đồng quản trị của tôi nhìn vào hóa đơn chứ không nhìn vào tỷ lệ lỗi."),
    B("That's a valid concern. Although the invoice is higher, the total cost is lower once you count returns.", "Đó là mối lo có cơ sở. Mặc dù hóa đơn cao hơn, tổng chi phí lại thấp hơn khi tính cả hàng bị trả về."),
    A("Perhaps. Despite that, a late delivery last spring cost us a major customer.", "Có thể. Dù vậy, đợt giao hàng trễ mùa xuân năm ngoái đã khiến chúng tôi mất một khách hàng lớn."),
    B("You're right, and I won't make excuses. Nevertheless, we've since opened a second warehouse in Hai Phong.", "Ông nói đúng, và tôi sẽ không bào chữa. Tuy nhiên, từ đó đến nay chúng tôi đã mở thêm một kho thứ hai ở Hải Phòng."),
    A("A warehouse is one thing. What guarantee can you actually offer?", "Có kho là một chuyện. Chị thực sự có thể đưa ra bảo đảm gì?"),
    B("Building on what you said about delays, we could add a penalty clause for late delivery.", "Tiếp nối điều ông vừa nói về giao trễ, chúng tôi có thể thêm điều khoản phạt khi giao hàng chậm."),
    A("That's compelling. That said, I'd still need a small reduction to convince the board.", "Điều đó khá thuyết phục. Dù vậy, tôi vẫn cần giảm giá chút ít để thuyết phục hội đồng quản trị."),
    B("That's a fair request. Let me think about that for a second. In spite of our tight margins, we could offer three per cent on orders above ten thousand units.", "Đó là đề nghị hợp lý. Để tôi suy nghĩ một chút. Dù biên lợi nhuận đã mỏng, chúng tôi có thể giảm ba phần trăm cho các đơn hàng trên mười nghìn sản phẩm."),
    A("Even though it's less than I hoped for, I think I can work with that.", "Dù ít hơn tôi mong đợi, tôi nghĩ tôi có thể chấp nhận mức đó."),
  ),
  task: task({
    prompt: "Viết một đoạn văn nghị luận (kiểu IELTS Writing Task 2) phản biện ý kiến: “Làm việc từ xa làm giảm năng suất của nhân viên.” Đoạn văn phải đi đủ bốn bước: nêu ý đối lập, thừa nhận, phản bác, khẳng định lại.",
    hints: [
      "Câu một: nêu quan điểm đối lập bằng Some argue that...",
      "Câu hai: thừa nhận phần hợp lý bằng Admittedly, kèm một ví dụ cụ thể.",
      "Phần phản bác: mở bằng Even so hoặc Nevertheless, dùng một câu despite và một câu although.",
      "Câu cuối: khẳng định lại quan điểm, có thể mở bằng While... để giữ giọng cân bằng.",
    ],
    model:
      "Some argue that working from home inevitably reduces productivity, since employees are surrounded by distractions and receive less supervision. Admittedly, this concern is not without foundation: without a clear routine, some workers do struggle to stay focused, and spontaneous problem-solving with colleagues becomes less frequent. Even so, this view overlooks a considerable body of evidence. Despite having fewer face-to-face interactions, many remote employees report completing more work, largely because they no longer lose two hours a day commuting. Moreover, although supervision is less direct, well-designed digital tools allow managers to track progress transparently. On balance, while remote work may not suit every role, I would maintain that, when it is properly managed, it tends to enhance rather than undermine productivity.",
    checklist: [
      "Đoạn văn có đủ bốn bước: nêu ý đối lập, thừa nhận, phản bác, khẳng định lại",
      "Có ít nhất một despite hoặc in spite of + danh từ/V-ing, và một although hoặc even though + mệnh đề",
      "Không có although đi cùng but, không có despite of",
      "Dùng ít nhất ba từ nối khác nhau, không lặp However",
      "Phần phản bác có lý do hoặc bằng chứng cụ thể, không chỉ nói I disagree",
    ],
    minWords: 100,
  }),
});

const tinhTe = lesson({
  slug: "ngon-ngu-tinh-te",
  title: "Ngôn ngữ tinh tế",
  minutes: 20,
  lecture: {
    title: "Nói giảm, rào đón và hàm ý",
    blocks: [
      p("Một học viên của tôi làm ở công ty kiểm toán nhận email của sếp người Anh: “Perhaps you might like to have another look at the figures.” Bạn ấy tưởng là lời gợi ý, để đến tuần sau mới xem. Hôm sau sếp hỏi sao chưa sửa. Thực ra câu đó là **yêu cầu sửa ngay**, chỉ được nói rất nhẹ nhàng. Bài này giúp bạn đọc được cái ý nằm dưới lớp chữ."),
      p("Người bản xứ, nhất là người Anh, hiếm khi nói thẳng “Tôi không đồng ý” hay “Ý tưởng này tệ”. Họ dùng **nói giảm** (understatement) và **rào đón** (hedging). Hiểu sai hàm ý là nguyên nhân của rất nhiều hiểu lầm trong môi trường làm việc quốc tế."),
      table(
        ["Câu nói", "Nghĩa đen", "Hàm ý thực sự"],
        ["It's not ideal.", "Nó chưa lý tưởng.", "Có vấn đề khá lớn."],
        ["I'm not entirely convinced.", "Tôi chưa hoàn toàn bị thuyết phục.", "Tôi không đồng ý."],
        ["That's an interesting idea.", "Ý tưởng thú vị đấy.", "Tôi nghi ngờ ý tưởng này."],
        ["With all due respect...", "Với tất cả sự tôn trọng...", "Tôi sắp phản bác bạn."],
        ["It could be better.", "Nó có thể tốt hơn.", "Nó khá tệ."],
      ),
      p("**Hedging** là làm mềm câu nói để tránh khẳng định tuyệt đối, bằng các từ như **might**, **could**, **tend to**, **seem**, **arguably**, **to some extent**. Cách này vừa lịch sự vừa cho thấy tư duy thận trọng."),
      ex("This approach might not be the most efficient.", "Cách làm này có lẽ không phải hiệu quả nhất.", "Nhẹ nhàng hơn nhiều so với: This approach is inefficient."),
      ex("I was a bit disappointed with the results.", "Tôi hơi thất vọng về kết quả.", "Với người Anh, a bit disappointed có thể có nghĩa là rất thất vọng."),
      ex("The results seem to suggest that the campaign had a limited effect.", "Kết quả dường như cho thấy chiến dịch chỉ có tác động hạn chế.", "Seem to suggest và limited là hai lớp rào đón: người nói không khẳng định chiến dịch thất bại, nhưng ai cũng hiểu kết quả không tốt."),
      ex("Perhaps we could revisit the timeline before we commit.", "Có lẽ chúng ta nên xem lại tiến độ trước khi cam kết.", "Hình thức là gợi ý, nhưng trong họp hành, câu này thường có nghĩa là: tiến độ hiện tại không ổn."),
      mistake("Your plan is wrong.", "I'm not sure the plan fully addresses the problem.", "Trong môi trường chuyên nghiệp, câu phủ định thẳng thừng dễ bị coi là thô lỗ. Hãy rào đón và nhắm vào vấn đề, không nhắm vào người."),
      p("**Thành ngữ** cũng mang sắc thái riêng và cần đúng ngữ cảnh: **the elephant in the room** (vấn đề ai cũng biết nhưng né tránh), **a blessing in disguise** (trong cái rủi có cái may), **cut corners** (làm ẩu để tiết kiệm thời gian hoặc tiền)."),
      mistake("Let's address the elephant of the room.", "Let's address the elephant in the room.", "Thành ngữ là cụm cố định: không được đổi giới từ hay thay từ nào."),
      mistake("I think maybe perhaps this could possibly be a little wrong.", "This may not be entirely accurate.", "Vì sợ thất lễ, người Việt hay chồng nhiều lớp rào đón lên một câu, nghe thành rụt rè và khó hiểu. Một từ rào đón đặt đúng chỗ là đủ lịch sự."),
      p("Lớp nghĩa ngầm cuối cùng là **mỉa mai** (sarcasm): người nói dùng một lời khen quá mức so với tình huống, kèm giọng kéo dài hoặc đều đều, để nói điều ngược lại. Máy in hỏng lần thứ ba trong tuần, đồng nghiệp thở dài: “Oh, **brilliant**. Just what I needed.” Nghĩa thật là: bực quá. Dấu hiệu để nhận ra: lời khen **không khớp** với sự việc, và ngữ điệu **không vui**. Trong email không có giọng nói nên mỉa mai rất dễ bị hiểu lầm; vì vậy đừng viết mỉa mai trong thư công việc."),
      tip("Khi nghe phản hồi, hãy chú ý **ngữ điệu** và các từ rào đón. Trong tiếng Anh-Anh, quite good thường chỉ có nghĩa là **tạm được**, không phải “khá tốt” như người Việt hay hiểu."),
      teacher("Tôi hay nói với học viên: tiếng Việt mình cũng có nói giảm, như “để em xem lại” thay cho “không”, hay “cũng được” khi thật ra chưa hài lòng. Vậy nên các bạn **không thiếu sự tinh tế, chỉ thiếu vốn câu**. Mỗi khi nghe một người bản xứ nhận xét, hãy ghi câu họ nói vào sổ, bên cạnh ghi hai cột: nghĩa đen và điều họ thực sự muốn nói. Sau vài tháng, cuốn sổ ấy sẽ quý hơn bất kỳ cuốn sách ngữ pháp nào."),
      summary(
        "Người Anh hay **nói giảm**: It's not ideal nghĩa là có vấn đề đáng kể; I'm not entirely convinced nghĩa là tôi không đồng ý.",
        "Lời gợi ý của cấp trên (Perhaps you might like to...) thường là **yêu cầu**: hãy làm ngay, đừng để sau.",
        "**Rào đón** bằng might, could, tend to, seem, arguably, to some extent; một từ đặt đúng chỗ là đủ, đừng chồng nhiều lớp.",
        "Phê bình nhắm vào **vấn đề**, không nhắm vào người: I'm not sure the plan fully addresses..., không nói Your plan is wrong.",
        "Thành ngữ là cụm cố định (the elephant in the room, a blessing in disguise, cut corners). Mỉa mai là lời khen không khớp sự việc; đừng viết mỉa mai trong email công việc.",
      ),
    ],
  },
  words: [
    word("subtle", "/ˈsʌt.əl/", "tinh tế, khó nhận ra", "There's a subtle difference between confident and arrogant.", "sub|tle", 0, "Chữ b câm, không đọc âm /b/."),
    word("understatement", "/ˈʌn.dəˌsteɪt.mənt/", "cách nói giảm", "Calling the project a challenge is an understatement.", "un|der|state|ment", 0),
    word("hedge", "/hedʒ/", "nói rào đón, tránh cam kết", "Politicians often hedge when asked difficult questions.", "hedge", 0),
    word("implication", "/ˌɪm.plɪˈkeɪ.ʃən/", "hàm ý", "The implication was that we had made a mistake.", "im|pli|ca|tion", 2),
    word("diplomatic", "/ˌdɪp.ləˈmæt.ɪk/", "khéo léo, tế nhị", "She gave a diplomatic answer to avoid offending anyone.", "dip|lo|mat|ic", 2),
    word("tactful", "/ˈtækt.fəl/", "tế nhị, biết ý", "It was tactful of him not to mention the mistake.", "tact|ful", 0),
    word("blunt", "/blʌnt/", "thẳng thừng, bộc trực", "To be blunt, the proposal isn't good enough.", "blunt", 0),
    word("sarcastic", "/sɑːˈkæs.tɪk/", "mỉa mai", "When he said “great job”, he was being sarcastic.", "sar|cas|tic", 1),
  ],
  exercises: [
    mc("c1-5-1", "Quản lý người Anh nói về bản kế hoạch của bạn: “It's not ideal.” Ý thực sự là gì?", ["Kế hoạch rất tốt, chỉ cần sửa chút ít.", "Kế hoạch hoàn hảo.", "Kế hoạch có vấn đề đáng kể."], 2, "It's not ideal là cách nói giảm; thực tế vấn đề khá nghiêm trọng."),
    mc("c1-5-2", "Câu nào lịch sự và có rào đón nhất?", ["This idea is bad.", "This idea might need a little more work.", "I hate this idea.", "This idea is wrong."], 1, "Might và a little làm mềm lời phê bình."),
    fill("c1-5-3", "The results were, to some ___, better than we expected.", ["extent", "degree"], "To some extent (ở một mức độ nào đó) là cụm rào đón phổ biến."),
    fill("c1-5-4", "Nobody wanted to mention the elephant in the ___: the budget cuts.", ["room"], "The elephant in the room: vấn đề ai cũng biết nhưng không ai dám nói."),
    reorder("c1-5-5", "I'm not entirely convinced by this proposal.", "Cách lịch sự để nói rằng bạn không đồng ý."),
    reorder("c1-5-6", "Losing that job was a blessing in disguise.", "A blessing in disguise: trong cái rủi có cái may."),
    listen("c1-5-7", "With all due respect, I think we may be missing the bigger picture.", ["Với tất cả sự tôn trọng, tôi nghĩ có lẽ chúng ta đang bỏ qua bức tranh toàn cảnh.", "Tôi hoàn toàn đồng ý với bạn.", "Tôi rất tôn trọng bạn nên không có ý kiến gì thêm."], 0, "With all due respect thường báo hiệu một lời phản bác."),
    listen("c1-5-8", "The printer's broken again? Oh, brilliant. Just what I needed.", ["Người nói vui vì máy in đã được sửa xong.", "Người nói đang bực mình vì máy in lại hỏng.", "Người nói khen chiếc máy in mới rất tốt."], 1, "Brilliant ở đây là mỉa mai: lời khen không khớp với sự việc máy in hỏng, nên nghĩa thật là bực bội."),
  ],
  speaking: [
    say("I'm not entirely convinced this is the best approach.", "Tôi chưa hoàn toàn bị thuyết phục rằng đây là cách tốt nhất."),
    say("It's not ideal, but we can make it work.", "Nó chưa lý tưởng, nhưng chúng ta có thể xoay xở được."),
    say("Let's address the elephant in the room.", "Hãy nói thẳng vào vấn đề mà ai cũng đang né tránh."),
  ],
  dialogue: dialogue(
    "Nhận phản hồi về bản báo cáo",
    "James, quản lý người Anh ở một công ty tư vấn, góp ý bản nháp báo cáo khảo sát khách hàng của Linh, chuyên viên phân tích người Việt. Linh vừa phải đọc được hàm ý trong lời nhận xét của sếp, vừa phải tế nhị khi nói lên ý kiến của mình.",
    { A: "James (quản lý)", B: "Linh (chuyên viên phân tích)" },
    A("Thanks for the draft, Linh. It's an interesting approach.", "Cảm ơn em về bản nháp nhé Linh. Cách tiếp cận thú vị đấy."),
    B("Thank you. Should I take that to mean you have some doubts about it?", "Em cảm ơn anh. Em có nên hiểu là anh đang có chút nghi ngờ về nó không ạ?"),
    A("Well, I'm not entirely convinced the survey sample is large enough.", "Ờ, anh chưa hoàn toàn bị thuyết phục rằng mẫu khảo sát đủ lớn."),
    B("That's fair. To some extent, the sample size was limited by the budget.", "Hợp lý ạ. Ở một mức độ nào đó, cỡ mẫu bị giới hạn bởi ngân sách."),
    A("Understood. Perhaps you might like to have another look at the conclusions, too.", "Anh hiểu. Có lẽ em cũng nên xem lại phần kết luận."),
    B("I'll revise them today. Are they too strong?", "Em sẽ sửa ngay trong hôm nay. Chúng có khẳng định mạnh quá không ạ?"),
    A("A little. “The campaign failed” is rather blunt. “The results seem to suggest a limited effect” would be more diplomatic.", "Hơi mạnh. Câu “Chiến dịch đã thất bại” khá thẳng thừng. Câu “Kết quả dường như cho thấy tác động hạn chế” sẽ khéo hơn."),
    B("Got it. And with all due respect, I think the deadline might be a little tight for a second survey.", "Em hiểu rồi. Và với tất cả sự tôn trọng, em nghĩ hạn chót có lẽ hơi gấp để làm thêm một đợt khảo sát nữa."),
    A("You're right. Let's not cut corners, then. I'll ask the client for another week.", "Em nói đúng. Vậy thì đừng làm ẩu. Anh sẽ xin khách thêm một tuần."),
    B("Thank you. Missing the first deadline might turn out to be a blessing in disguise.", "Em cảm ơn anh. Lỡ hạn chót đầu tiên biết đâu lại là trong cái rủi có cái may."),
    A("Quite possibly. Oh, and the old client logo on page two? Brilliant. Just what the report needed.", "Có khi thế thật. À, còn cái logo cũ của khách ở trang hai? Tuyệt thật. Đúng là thứ bản báo cáo đang cần."),
    B("I'll take that as sarcasm and replace it with the new one straight away.", "Em sẽ hiểu đó là câu mỉa mai và thay ngay bằng logo mới ạ."),
  ),
  task: task({
    prompt: "Một đồng nghiệp gửi bạn bản đề xuất chương trình khách hàng thân thiết. Bạn thấy ngân sách đào tạo nhân viên chưa thực tế. Hãy viết email phản hồi: ghi nhận điểm tốt, nêu điểm chưa đồng ý một cách tế nhị, và gợi ý hướng sửa.",
    hints: [
      "Mở đầu bằng một lời ghi nhận thật lòng và cụ thể về phần làm tốt.",
      "Nêu điểm chưa đồng ý bằng I'm not entirely convinced... hoặc It might not be...",
      "Dùng ít nhất ba cách rào đón khác nhau (not entirely, seem to, might, perhaps), mỗi câu tối đa hai lớp.",
      "Kết bằng một đề xuất cụ thể theo dạng gợi ý: Perhaps we could...",
    ],
    model:
      "Dear Sophie, thank you for sending over the proposal for the new customer loyalty scheme. It is clearly the result of a great deal of work, and the section on digital rewards is particularly strong. That said, I'm not entirely convinced that the budget fully reflects the cost of staff training. The figures seem to suggest that we would need at least two additional trainers, which might not be realistic this year. Perhaps we could revisit the timeline and run a smaller pilot in two branches first, so that we can base the full budget on real data. I would be happy to discuss this further whenever it suits you. Best wishes, Nam",
    checklist: [
      "Không có câu phủ định thẳng thừng như Your plan is wrong hay This is bad",
      "Có ít nhất ba cách rào đón khác nhau, không câu nào chồng quá hai từ rào đón",
      "Lời phê bình nhắm vào con số hoặc vấn đề, không nhắm vào người viết",
      "Có ít nhất một đề xuất cụ thể thay cho lời chê chung chung",
      "Không có câu mỉa mai, không có thành ngữ sai giới từ",
    ],
    minWords: 100,
  }),
});

const hocThuat = lesson({
  slug: "van-phong-hoc-thuat",
  title: "Văn phong học thuật",
  minutes: 24,
  lecture: {
    title: "Danh từ hóa và cấu trúc khách quan",
    blocks: [
      p("Một nghiên cứu sinh gửi bản nháp bài báo cho giáo sư hướng dẫn ở Úc và nhận lại bản nháp với một lời phê lặp đi lặp lại ở khắp các trang: “too conversational”. Ý tưởng tốt, số liệu chắc, nhưng câu chữ nghe như đang kể chuyện: I think, a lot of, found out, got. Bài hôm nay dạy bạn chuyển giọng **từ nói chuyện sang viết học thuật**."),
      p("Văn phong học thuật (bài luận, báo cáo, IELTS Writing) khác văn nói ở ba điểm: dùng **danh từ hóa** (nominalisation), chọn **từ trang trọng** thay cho phrasal verb đời thường, và dùng **cấu trúc khách quan** thay vì I think."),
      p("**Danh từ hóa** là biến động từ hoặc tính từ thành danh từ, giúp câu súc tích và mang tính khái niệm hơn."),
      ex("The government reduced taxes, so people spent more.", "Chính phủ giảm thuế, nên người dân chi tiêu nhiều hơn.", "Văn nói: nhiều động từ, nhiều mệnh đề."),
      ex("The reduction in taxes led to an increase in consumer spending.", "Việc giảm thuế đã dẫn đến sự gia tăng chi tiêu tiêu dùng.", "Văn học thuật: reduce thành reduction, spend thành spending."),
      table(
        ["Thân mật", "Trang trọng", "Ví dụ học thuật"],
        ["get", "obtain / receive", "Participants obtained higher scores."],
        ["find out", "discover / determine", "The study aimed to determine the cause."],
        ["look into", "investigate / examine", "This paper examines the impact of AI."],
        ["go up", "increase / rise", "Prices rose significantly."],
        ["a lot of", "a significant number of / considerable", "A significant number of students agreed."],
        ["show", "demonstrate / indicate", "The data indicate a clear trend."],
      ),
      p("**Cấu trúc khách quan** giúp tránh I think và tạo khoảng cách với người viết: **It is widely believed that...**, **It has been argued that...**, **It is estimated that...**, hoặc dạng **X is thought to...** Đây chính là bị động với động từ tường thuật các bạn đã học kỹ ở bài “Người ta nói rằng…”; trong bài học thuật, hãy kết hợp chúng với từ rào đón (may, tend to) của bài Ngôn ngữ tinh tế."),
      ex("It is widely believed that early education shapes lifelong success.", "Nhiều người tin rằng giáo dục sớm định hình thành công suốt đời."),
      ex("Chronic stress is thought to weaken the immune system.", "Căng thẳng kéo dài được cho là làm suy yếu hệ miễn dịch.", "Dạng X is thought to + động từ nguyên mẫu ngắn gọn hơn It is thought that chronic stress weakens..., và đưa chủ đề chính (chronic stress) lên đầu câu."),
      mistake("I think that social media is very bad for teenagers.", "It has been argued that social media may have a negative impact on teenagers.", "Trong bài học thuật, tránh I think và tính từ cảm tính như very bad. Dùng cấu trúc khách quan và rào đón bằng may."),
      mistake("Researchers got a lot of data from the survey.", "Researchers obtained a substantial amount of data from the survey.", "Get và a lot of quá thân mật cho văn học thuật; hãy dùng obtain và a substantial amount of."),
      mistake("There was a sharp increase of oil prices.", "There was a sharp increase in oil prices.", "Tiếng Việt nói “sự tăng của giá dầu” nên người Việt dịch “của” thành of. Các danh từ chỉ thay đổi như increase, decrease, rise, fall, drop đi với in khi nói cái gì tăng giảm; còn of dùng cho mức tăng giảm: an increase of ten per cent."),
      tip("Đừng danh từ hóa mọi thứ. Quá nhiều danh từ nối tiếp sẽ làm câu nặng nề, khó đọc. Mục tiêu là **rõ ràng và chính xác**, không phải phức tạp."),
      tip("Mẹo phát âm: khi danh từ hóa, trọng âm thường **dịch chuyển**. Với đuôi -tion, trọng âm luôn rơi vào âm tiết ngay trước nó: inˈvestigate thành investiˈgation, ˈdemonstrate thành demonˈstration. Với -sis cũng đổi: ˈanalyse thành aˈnalysis. Đọc sai trọng âm khi thuyết trình là lỗi người Việt rất hay mắc."),
      teacher("Tôi vẫn dặn các bạn nghiên cứu sinh một cách tự sửa rất hiệu quả: viết bản nháp đầu tiên thoải mái như đang nói, rồi **sửa ba lượt, mỗi lượt chỉ tìm một thứ**. Lượt một, tìm và thay I think. Lượt hai, tìm get, a lot of và các phrasal verb đời thường. Lượt ba, tìm những câu có hai ba động từ nối nhau bằng so, and, because, rồi thử danh từ hóa một vế. Sửa một lúc mọi thứ thì rối; sửa từng lượt thì bài sạch mà các bạn còn nhớ lâu."),
      summary(
        "**Danh từ hóa** để câu súc tích: reduce thành reduction, spend thành spending; nhưng đừng nhồi quá nhiều danh từ liền nhau.",
        "Thay từ thân mật bằng từ trang trọng: get thành obtain, find out thành determine, look into thành examine, a lot of thành a significant number of.",
        "Tránh I think: dùng **It is widely believed that...**, **X is thought to...**, kết hợp rào đón may, tend to.",
        "Increase, decrease, rise, fall + **in** + thứ thay đổi; + **of** + mức thay đổi (an increase of ten per cent).",
        "Danh từ hóa làm **dịch trọng âm**: inˈvestigate thành investiˈgation, ˈanalyse thành aˈnalysis.",
      ),
    ],
  },
  words: [
    word("nominalisation", "/ˌnɒm.ɪ.nəl.aɪˈzeɪ.ʃən/", "sự danh từ hóa", "Nominalisation makes academic writing more concise.", "nom|i|nal|i|sa|tion", 4, "Tiếng Anh-Mỹ viết là nominalization."),
    word("obtain", "/əbˈteɪn/", "thu được, đạt được", "The researchers obtained permission from all participants.", "ob|tain", 1),
    word("objective", "/əbˈdʒek.tɪv/", "khách quan", "Academic writing should remain objective and balanced.", "ob|jec|tive", 1),
    word("impersonal", "/ɪmˈpɜː.sən.əl/", "không mang tính cá nhân, khách quan", "Impersonal structures help writers avoid sounding biased.", "im|per|son|al", 1),
    word("hypothesis", "/haɪˈpɒθ.ə.sɪs/", "giả thuyết", "The data support the original hypothesis.", "hy|poth|e|sis", 1, "Số nhiều là hypotheses /haɪˈpɒθ.ə.siːz/."),
    word("substantiate", "/səbˈstæn.ʃi.eɪt/", "chứng minh bằng bằng chứng", "The author fails to substantiate her main claim.", "sub|stan|ti|ate", 1),
    word("methodology", "/ˌmeθ.əˈdɒl.ə.dʒi/", "phương pháp luận", "The methodology section explains how the data were collected.", "meth|o|dol|o|gy", 2),
  ],
  exercises: [
    mc("c1-6-1", "Từ nào trang trọng nhất để thay cho find out trong bài học thuật?", ["figure out", "work out", "get to know", "determine"], 3, "Determine phù hợp văn học thuật; figure out và work out mang tính thân mật."),
    mc("c1-6-2", "Câu nào phù hợp nhất với văn phong học thuật?", ["It is widely believed that exercise improves memory.", "Everyone knows exercise is great for your memory.", "I reckon exercise helps your memory a lot."], 0, "Cấu trúc khách quan It is widely believed that... thay cho cách nói cảm tính."),
    fill("c1-6-3", "It is widely ___ that climate change will affect food production.", ["believed", "accepted", "thought", "acknowledged", "recognised", "recognized", "expected", "known", "agreed", "predicted", "assumed", "anticipated", "feared", "argued", "held"], "It is widely + quá khứ phân từ + that... là cấu trúc khách quan."),
    fill("c1-6-4", "Following the announcement, there was a sharp ___ in oil prices (giá dầu tăng mạnh).", ["increase", "rise", "jump", "surge", "spike", "hike"], "Danh từ hóa: thay vì viết prices increased sharply, ta viết a sharp increase in prices."),
    reorder("c1-6-5", "The study aims to examine the impact of social media.", "Examine trang trọng hơn look into."),
    reorder("c1-6-6", "It is estimated that prices will rise further.", "It is estimated that... là cấu trúc khách quan."),
    listen("c1-6-7", "The findings indicate a strong correlation between sleep and academic performance.", ["Ngủ nhiều khiến kết quả học tập giảm sút.", "Kết quả cho thấy mối tương quan chặt chẽ giữa giấc ngủ và kết quả học tập.", "Nghiên cứu chưa tìm thấy mối liên hệ nào giữa giấc ngủ và học tập."], 1, "Indicate a strong correlation: cho thấy mối tương quan chặt chẽ."),
    listen("c1-6-8", "Further research is needed to substantiate these claims.", ["Những khẳng định này đã được chứng minh đầy đủ.", "Nghiên cứu này bác bỏ những khẳng định trước đó.", "Cần thêm nghiên cứu để chứng minh những khẳng định này."], 2, "Substantiate: chứng minh bằng bằng chứng."),
  ],
  speaking: [
    say("It is widely believed that education reduces inequality.", "Nhiều người tin rằng giáo dục giúp giảm bất bình đẳng."),
    say("The findings indicate a significant increase in demand.", "Kết quả cho thấy nhu cầu tăng đáng kể."),
    say("Further research is needed to confirm this hypothesis.", "Cần thêm nghiên cứu để xác nhận giả thuyết này."),
  ],
  dialogue: dialogue(
    "Buổi gặp giáo sư hướng dẫn",
    "Hà, nghiên cứu sinh người Việt tại một trường đại học ở Úc, gặp giáo sư Clarke để sửa chương kết quả của luận án. Nội dung tốt nhưng văn phong còn giống văn nói; hai thầy trò cùng viết lại từng câu.",
    { A: "Giáo sư Clarke", B: "Hà (nghiên cứu sinh)" },
    A("Ha, your findings are solid, but the writing is still too conversational.", "Hà, kết quả của em rất chắc, nhưng cách viết vẫn còn quá giống văn nói."),
    B("I was afraid of that. Which sentences sound too informal?", "Em cũng lo như vậy. Những câu nào nghe quá thân mật ạ?"),
    A("Take this one: “We found out that a lot of students got lower scores.”", "Lấy câu này làm ví dụ: “Chúng tôi phát hiện ra rằng nhiều sinh viên bị điểm thấp hơn.”"),
    B("Would “The study determined that a significant number of students obtained lower scores” work better?", "Viết là “Nghiên cứu xác định rằng một số lượng đáng kể sinh viên đạt điểm thấp hơn” thì có tốt hơn không ạ?"),
    A("Much better. The next paragraph opens with “I think social media is bad for sleep.”", "Tốt hơn nhiều. Đoạn tiếp theo lại mở đầu bằng câu “Tôi nghĩ mạng xã hội có hại cho giấc ngủ.”"),
    B("Perhaps: “It has been argued that social media use may have a negative impact on sleep quality.”", "Có lẽ là: “Có ý kiến cho rằng việc sử dụng mạng xã hội có thể tác động tiêu cực đến chất lượng giấc ngủ.”"),
    A("Good, and you've hedged with may. Now nominalise this: “Screen time went up, so students slept less.”", "Tốt, em đã rào đón bằng may. Giờ hãy danh từ hóa câu này: “Thời gian dùng màn hình tăng lên nên sinh viên ngủ ít đi.”"),
    B("“The increase in screen time led to a reduction in sleep duration.”", "“Sự gia tăng thời gian sử dụng màn hình đã dẫn đến sự suy giảm thời lượng ngủ.”"),
    A("Exactly. And notice it's an increase in screen time, not an increase of screen time.", "Chính xác. Và để ý là an increase in screen time, không phải an increase of screen time."),
    B("So of is for the amount, as in an increase of twenty per cent?", "Vậy of là dùng cho mức tăng, như an increase of twenty per cent phải không ạ?"),
    A("Right. One last thing: in your presentation, say investigation with the stress on ga, not on ves.", "Đúng vậy. Điều cuối cùng: khi thuyết trình, đọc investigation nhấn vào âm ga, không nhấn vào âm ves."),
    B("Investigation. Thank you, Professor. I'll revise the whole chapter in three passes.", "Investigation. Em cảm ơn giáo sư. Em sẽ sửa cả chương theo ba lượt ạ."),
  ),
  task: task({
    prompt: "Viết lại đoạn văn nói sau thành một đoạn văn học thuật khoảng một trăm từ: “I think a lot of young people in Vietnam use their phones too much. We found out that screen time went up a lot during the pandemic, so kids slept less and got worse marks. Schools should look into this.”",
    hints: [
      "Thay I think bằng cấu trúc khách quan như It is widely believed that...",
      "Danh từ hóa ít nhất hai động từ: went up thành an increase in, slept less thành a reduction in.",
      "Thay các từ thân mật: a lot of, found out, got, look into, kids.",
      "Rào đón kết luận bằng appears to, may, hoặc further research is needed.",
    ],
    model:
      "It is widely believed that excessive smartphone use among young people in Vietnam has become a significant concern. A recent survey of secondary school students determined that there was a substantial increase in daily screen time during the pandemic. This increase appears to have been accompanied by a reduction in sleep duration and a decline in academic performance. Although further research is needed to substantiate a causal relationship, these findings indicate that the issue deserves closer attention. It is therefore recommended that schools examine the impact of mobile devices on learning and consider introducing clear guidelines on their use.",
    checklist: [
      "Không còn I think, a lot of, got, found out, look into hay kids",
      "Có ít nhất hai cụm danh từ hóa, ví dụ an increase in..., a reduction in...",
      "Có ít nhất một cấu trúc khách quan (It is ... that..., hoặc X is thought to...)",
      "Giới từ đúng: increase/reduction in + thứ thay đổi",
      "Kết luận có rào đón, không khẳng định tuyệt đối rằng điện thoại gây ra điểm kém",
    ],
    minWords: 90,
  }),
});

export const tiengAnhC1: Course = {
  slug: "tieng-anh-c1",
  title: "Tiếng Anh C1: Thành thạo",
  level: "C1",
  goal: "lo-trinh",
  summary: "Cho người đã vững B2: nói và viết tự nhiên, tinh tế như người dùng tiếng Anh thành thạo, từ cuộc họp quốc tế đến bài luận học thuật.",
  outcomes: [
    "Dùng cụm động từ và kết hợp từ tự nhiên như người bản xứ",
    "Nhấn mạnh ý bằng đảo ngữ và câu chẻ",
    "Lập luận, nhượng bộ và phản biện một cách thuyết phục",
    "Viết theo văn phong học thuật chuẩn mực",
  ],
  audience: [
    "Người đã ở trình độ B2 muốn vượt qua giai đoạn “chững lại”",
    "Người đi làm và nghiên cứu sinh cần tiếng Anh cho họp, thuyết trình và viết báo cáo",
  ],
  teacher: {
    name: "Cô Diệu Linh",
    initials: "DL",
    bio: "Thạc sĩ Ngôn ngữ học ứng dụng, chứng chỉ DELTA. 12 năm dạy tiếng Anh học thuật và kỹ năng thuyết trình cho người đi làm.",
  },
  durationWeeks: 18,
  rating: 4.9,
  reviews: [
    { name: "Bảo Ngọc", role: "Chuyên viên phân tích tài chính, TP. Hồ Chí Minh", quote: "Trước đây mình nói đúng ngữ pháp nhưng nghe rất cứng. Bài về nói giảm và rào đón giúp mình tự tin hơn hẳn khi họp với đối tác người Anh." },
    { name: "Tuấn Kiệt", role: "Nghiên cứu sinh, Huế", quote: "Phần văn phong học thuật cực kỳ thực tế. Mình áp dụng danh từ hóa vào bài báo đầu tiên và được giáo sư hướng dẫn khen." },
  ],
  faqs: [
    { q: "Làm sao biết mình đủ trình độ để học C1?", a: "Bạn nên hoàn thành khóa B2 hoặc làm bài kiểm tra đầu vào. Nếu bạn đọc hiểu báo tiếng Anh mà không cần tra từ liên tục, bạn đã sẵn sàng." },
    { q: "Học xong C1 thì học gì tiếp?", a: "Nếu cần chứng chỉ, bạn có thể học tiếp khóa luyện thi IELTS để biến kỹ năng thành điểm số. Nếu không, hãy duy trì luyện tập hằng ngày: đọc báo, nghe podcast và viết thường xuyên để giữ vững trình độ." },
  ],
  status: "open",
  modules: [
    chapter(1, "Tiếng Anh tự nhiên", [noiTuNhien, nTinhLuocVaThayThe, nTuongLaiNangCao, nCauTaoTu]),
    chapter(2, "Nhấn mạnh và giả định", [daoNgu, cauChe, nDieuKienNangCao, nBangThaiCach]),
    chapter(3, "Lập luận và tường thuật", [lapLuan, nDongTuTuongThuat, nBiDongNangCao, nMenhDeQuanHeNangCao]),
    chapter(4, "Văn phong tinh tế", [tinhTe, hocThuat, nTrangTuBinhLuan, nVietLuanVaTomTat]),
  ],
};
