import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "hoi-dap-hang-ngay",
  title: "Hỏi đáp về thói quen",
  minutes: 22,
  lecture: {
    title: "Câu hỏi Wh- với do/does và cách nói tần suất",
    blocks: [
      p("Bạn đã biết hỏi **Do you work?** và trả lời Yes hoặc No. Nhưng trò chuyện thật thì cần nhiều hơn thế: Bạn sống ở đâu? Mấy giờ bạn đi làm? Bao lâu bạn về quê một lần? Những câu này dùng **từ để hỏi** đứng trước **do / does**."),
      p("Công thức chỉ có một: **Từ để hỏi + do / does + chủ ngữ + động từ nguyên mẫu?** Dùng **does** với he, she, it; dùng **do** với I, you, we, they. Khi đã có does, động từ chính **không thêm -s** nữa."),
      table(
        ["Từ để hỏi", "Câu hỏi", "Câu trả lời"],
        ["What", "What do you do?", "I'm a nurse."],
        ["Where", "Where does your sister live?", "She lives in Da Nang."],
        ["When", "When do you visit your grandparents?", "At the weekend."],
        ["What time", "What time does the bank open?", "At eight o'clock."],
        ["How often", "How often do you go to the gym?", "Three times a week."],
      ),
      ex("What do you do? I'm an engineer.", "Bạn làm nghề gì? Tôi là kỹ sư.", "What do you do? là câu hỏi về nghề nghiệp, không phải “bạn đang làm gì”."),
      ex("Where does your brother work? He works in a bank.", "Anh trai bạn làm việc ở đâu? Anh ấy làm ở ngân hàng.", "Câu hỏi có does nên work giữ nguyên; câu trả lời không có does nên works có -s."),
      mistake("Where your sister lives?", "Where does your sister live?", "Tiếng Việt chỉ cần thêm chữ “ở đâu” vào câu kể là thành câu hỏi, nên người Việt hay quên does. Câu hỏi Wh- với động từ thường bắt buộc phải có do hoặc does."),
      mistake("What time does he gets up?", "What time does he get up?", "Does đã mang -s thay cho động từ rồi. Một câu chỉ cần một chữ -s, đừng thêm hai lần."),
      p("Để trả lời câu hỏi **How often...?**, bên cạnh always, usually, sometimes, bạn còn dùng các **cụm chỉ tần suất**. Các cụm này thường đứng **ở cuối câu**."),
      table(
        ["Cụm tần suất", "Nghĩa", "Ví dụ"],
        ["every day / every Monday", "mỗi ngày / mỗi thứ Hai", "I drink tea every day."],
        ["once a week", "một lần một tuần", "We eat out once a week."],
        ["twice a month", "hai lần một tháng", "She visits her parents twice a month."],
        ["three times a year", "ba lần một năm", "They go to Hue three times a year."],
      ),
      mistake("I go to the market one time a week.", "I go to the market once a week.", "Người Việt dịch “một lần” thành one time. Tiếng Anh dùng từ riêng: once (một lần), twice (hai lần); từ ba lần trở đi mới dùng times: three times, four times."),
      mistake("I every day drink coffee.", "I drink coffee every day.", "Tiếng Việt nói “tôi ngày nào cũng uống cà phê”, nên người Việt hay nhét every day vào giữa. Cụm tần suất đứng ở cuối câu, khác với always, usually đứng trước động từ."),
      ex("How often does your son play badminton? Every Saturday.", "Con trai bạn chơi cầu lông bao lâu một lần? Thứ Bảy nào cũng chơi."),
      tip("Trong câu hỏi, **do** và **does** được đọc rất nhẹ và nhanh, gần như dính vào từ sau: What do you do? nghe như /wɒt də jə duː/. Bạn không cần đọc to do, nhưng đừng bỏ nó đi."),
      teacher("Có một bài tập tôi giao cho mọi lớp A1 suốt mấy chục năm: mỗi em hỏi **năm câu** về thói quen của một người thân rồi ghi lại câu trả lời. Where does my mother go every morning? What time does my father have dinner? Hỏi về người thật thì các em phải dùng **does** thật, và chỉ sau một tuần, lỗi quên does giảm hẳn."),
    ],
  },
  words: [
    word("live", "/lɪv/", "sống", "Where do you live?", "live", 0, "Âm /ɪ/ ngắn. Đọc kéo dài thành /liːv/ là thành leave (rời đi)."),
    word("visit", "/ˈvɪz.ɪt/", "thăm", "I visit my grandparents every Sunday.", "vis|it", 0, "Chữ s ở đây đọc là /z/."),
    word("once", "/wʌns/", "một lần", "We go to the cinema once a month.", "once", 0, "Đọc là /wʌns/, bắt đầu bằng âm /w/, không đọc theo chữ viết “ôn-xơ”."),
    word("twice", "/twaɪs/", "hai lần", "She calls her mother twice a week.", "twice", 0),
    word("gym", "/dʒɪm/", "phòng tập thể dục", "How often do you go to the gym?", "gym", 0),
    word("market", "/ˈmɑː.kɪt/", "chợ", "My mother goes to the market every morning.", "mar|ket", 0, "Nhớ bật âm /t/ ở cuối."),
    word("dinner", "/ˈdɪn.ər/", "bữa tối", "What time do you have dinner?", "din|ner", 0),
    word("often", "/ˈɒf.ən/", "thường, hay", "How often do you visit your parents?", "of|ten", 0, "Chữ t thường câm: /ˈɒf.ən/. Một số người đọc /ˈɒf.tən/, cũng được chấp nhận."),
  ],
  exercises: [
    mc("a1-n08-1", "Where ___ your brother work?", ["do", "does", "is"], 1, "Your brother là he, và work là động từ thường, nên dùng does."),
    mc("a1-n08-2", "How often do you play tennis?", ["Twice a week.", "At seven o'clock.", "In the park."], 0, "How often hỏi bao lâu một lần, nên trả lời bằng cụm tần suất. At seven o'clock trả lời What time; in the park trả lời Where."),
    fill("a1-n08-3", "What time ___ the film start? (hiện tại đơn)", ["does"], "The film là it nên dùng does; động từ start giữ nguyên."),
    fill("a1-n08-4", "I go to the market ___ a week. (một lần)", ["once"], "Một lần là once, không nói one time."),
    reorder("a1-n08-5", "How often do you visit your parents?", "How often + do + chủ ngữ + động từ nguyên mẫu?"),
    reorder("a1-n08-6", "What time does your father get up?", "What time + does + chủ ngữ + động từ nguyên mẫu; get up không thêm -s vì đã có does."),
    listen("a1-n08-7", "When do you have dinner?", ["Bạn ăn tối ở đâu?", "Bạn ăn tối với ai?", "Bạn ăn tối khi nào?"], 2, "When là khi nào; where mới là ở đâu."),
    listen("a1-n08-8", "She goes to the gym three times a week.", ["Cô ấy đến phòng tập mỗi ngày.", "Cô ấy đến phòng tập ba lần một tuần.", "Cô ấy đến phòng tập ba lần một tháng."], 1, "Three times a week là ba lần một tuần."),
  ],
  speaking: [
    say("How often do you go to the market?", "Bạn đi chợ bao lâu một lần?"),
    say("I visit my parents twice a month.", "Tôi về thăm bố mẹ hai lần một tháng."),
    say("Where does your sister live?", "Chị gái bạn sống ở đâu?"),
  ],
});
