import { A, B, dialogue, ex, fill, lesson, listen, mc, mistake, p, reorder, say, summary, table, task, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "so-thich",
  title: "Sở thích của bạn",
  minutes: 20,
  lecture: {
    title: "like, love, enjoy, hate + V-ing",
    blocks: [
      p("Trò chuyện với bạn mới, với đồng nghiệp nước ngoài trong giờ nghỉ trưa, câu chuyện gần như luôn chuyển sang **sở thích**: Bạn thích làm gì lúc rảnh? Để trả lời, bạn cần bốn động từ chỉ cảm xúc và một quy tắc nhỏ: sau chúng, động từ thứ hai thêm **-ing**."),
      table(
        ["Mức độ", "Động từ", "Ví dụ"],
        ["Rất thích", "love", "I love reading."],
        ["Thích", "like", "She likes cooking."],
        ["Thích thú, tận hưởng", "enjoy", "We enjoy swimming in the sea."],
        ["Không thích", "don't like / doesn't like", "He doesn't like dancing."],
        ["Ghét", "hate", "I hate getting up early."],
      ),
      p("Công thức: **like / love / enjoy / hate + V-ing**. Sau các động từ này cũng có thể dùng danh từ: I love music. She likes football. Nhớ rằng với **he, she, it**, động từ chính vẫn phải thêm **-s**: she likes, he loves, my father enjoys. Like, love, hate cũng có thể đi với **to + động từ** (I like to read), nhưng **enjoy chỉ đi với V-ing**. Bài này tập trung vào dạng V-ing vì dùng được cho cả bốn động từ."),
      table(
        ["Quy tắc thêm -ing", "Ví dụ"],
        ["Thường: thêm -ing", "read → reading, cook → cooking, play → playing"],
        ["Tận cùng -e câm: bỏ e, thêm -ing", "dance → dancing, write → writing"],
        ["Từ một âm tiết, tận cùng một nguyên âm + một phụ âm: gấp đôi phụ âm", "swim → swimming, run → running, shop → shopping"],
      ),
      mistake("I like read books.", "I like reading books.", "Tiếng Việt nói “tôi thích đọc sách”, hai động từ đứng cạnh nhau mà không đổi gì. Tiếng Anh không để hai động từ nguyên mẫu đứng liền nhau như thế: phải nói like reading (hoặc like to read)."),
      mistake("I very like music.", "I really like music. / I like music very much.", "Người Việt dịch từng chữ “tôi rất thích”. Trong tiếng Anh, very không đứng trước like. Dùng really trước động từ, hoặc very much ở cuối câu."),
      ex("My father enjoys fishing at the weekend.", "Bố tôi thích đi câu cá vào cuối tuần.", "My father là he nên enjoys có -s; fish thành fishing."),
      ex("I love listening to music on the bus.", "Tôi rất thích nghe nhạc trên xe buýt.", "Nhớ có to sau listen: listen to music."),
      ex("She hates shopping, but she loves cooking.", "Cô ấy ghét đi mua sắm, nhưng lại rất thích nấu ăn.", "Shop gấp đôi p thành shopping."),
      p("Để hỏi người khác có thích gì không, dùng **Do / Does + chủ ngữ + like + V-ing?** Câu trả lời ngắn **không lặp lại like**, mà dùng **do / don't** hoặc **does / doesn't**."),
      table(
        ["Câu hỏi", "Trả lời có", "Trả lời không"],
        ["Do you like singing?", "Yes, I do.", "No, I don't."],
        ["Does he like football?", "Yes, he does.", "No, he doesn't."],
        ["Do they like swimming?", "Yes, they do.", "No, they don't."],
      ),
      mistake("Do you like cooking? Yes, I like.", "Do you like cooking? Yes, I do.", "Tiếng Việt trả lời “Có, tôi thích”, nên người Việt hay đáp Yes, I like. Tiếng Anh không để like đứng trơ trọi ở cuối; câu trả lời ngắn chỉ cần Yes, I do."),
      tip("Đuôi **-ing** đọc là /ɪŋ/: kết thúc bằng âm mũi ở cuống lưỡi, gần giống vần “inh” của tiếng Việt, nhưng **không bật thành /k/**: swimming là /ˈswɪm.ɪŋ/, không phải “xuy-mink”."),
      teacher("Nhiều bạn học viên hỏi tôi: sao nói mãi vẫn quên -ing? Tôi luôn trả lời: vì các bạn học quy tắc mà không học **cả cụm**. Các bạn hãy viết ra năm sở thích thật của chính mình dưới dạng cụm hoàn chỉnh: **I love cooking. I enjoy walking. I hate waiting.** Dán lên tủ lạnh, mỗi lần mở tủ đọc to một câu. Câu nói về chính mình thì nhớ lâu gấp mười câu trong sách."),
      summary(
        "Công thức: **like / love / enjoy / hate + V-ing**: I love reading. Không để hai động từ nguyên mẫu đứng liền nhau (không nói like read).",
        "Với **he, she, it**, động từ chính vẫn thêm -s: she likes cooking, my father enjoys fishing.",
        "**Enjoy** chỉ đi với V-ing; like, love, hate đi được cả với to + động từ.",
        "Không nói very like: dùng **really like** hoặc **like … very much**.",
        "Trả lời ngắn không lặp lại like: **Yes, I do. / No, she doesn't.**",
        "Chính tả -ing: dance → dancing (bỏ e), swim → swimming (gấp đôi phụ âm).",
      ),
    ],
  },
  words: [
    word("hobby", "/ˈhɒb.i/", "sở thích", "My hobby is reading.", "hob|by", 0),
    word("enjoy", "/ɪnˈdʒɔɪ/", "thích thú, tận hưởng", "I enjoy cooking for my family.", "en|joy", 1, "Nhấn âm sau: en-JOY."),
    word("hate", "/heɪt/", "ghét", "He hates waiting for the bus.", "hate", 0, "Bật âm /t/ ở cuối để không nghe thành hay /heɪ/."),
    word("swim", "/swɪm/", "bơi", "Do you like swimming?", "swim", 0, "Khép môi ở âm /m/ cuối; swimming gấp đôi chữ m."),
    word("dance", "/dɑːns/", "nhảy, khiêu vũ", "My daughter loves dancing.", "dance", 0, "Kết thúc bằng /ns/, nhớ đọc rõ âm /s/."),
    word("read", "/riːd/", "đọc", "She loves reading books.", "read", 0, "Kéo dài âm /iː/ và nhớ đọc âm /d/ ở cuối, đừng đọc thành “ri”."),
    word("music", "/ˈmjuː.zɪk/", "âm nhạc", "I listen to music every day.", "mu|sic", 0, "Âm giữa là /z/, không phải /s/: MYOO-zik."),
    word("football", "/ˈfʊt.bɔːl/", "bóng đá", "My brothers love playing football.", "foot|ball", 0),
  ],
  exercises: [
    mc("a1-n07-1", "I enjoy ___ in the sea.", ["to swim", "swim", "swimming"], 2, "Sau enjoy luôn dùng V-ing. Swim gấp đôi m thành swimming."),
    mc("a1-n07-2", "Do you like cooking? Yes, I ___.", ["like", "do", "am"], 1, "Câu hỏi bắt đầu bằng Do thì trả lời ngắn Yes, I do."),
    fill("a1-n07-3", "She loves ___ to music. (listen)", ["listening", "to listen"], "Sau love dùng V-ing: listening (to listen cũng đúng)."),
    fill("a1-n07-4", "He enjoys ___ on Sundays. (dance)", ["dancing"], "Dance tận cùng bằng -e câm: bỏ e rồi thêm -ing."),
    reorder("a1-n07-5", "Does your brother like playing football?", "Your brother là he nên câu hỏi dùng Does, và like giữ nguyên; sau like là V-ing."),
    reorder("a1-n07-6", "My mother really loves cooking.", "Really đứng trước động từ loves để nhấn mạnh; không dùng very trước động từ."),
    listen("a1-n07-7", "I hate getting up early.", ["Tôi ghét dậy sớm.", "Tôi thích dậy sớm.", "Tôi ghét đi ngủ muộn."], 0, "Hate là ghét; get up early là dậy sớm."),
    listen("a1-n07-8", "Does she like reading? No, she doesn't.", ["Cô ấy có thích đọc sách không? Có.", "Cô ấy có thích viết không? Không.", "Cô ấy có thích đọc sách không? Không."], 2, "No, she doesn't là câu trả lời không."),
  ],
  speaking: [
    say("I love reading books.", "Tôi rất thích đọc sách."),
    say("My brother enjoys playing football.", "Anh trai tôi thích chơi bóng đá."),
    say("Do you like dancing? Yes, I do.", "Bạn có thích nhảy không? Có, tôi thích."),
  ],
  dialogue: dialogue(
    "Giờ nghỉ trưa ở công ty",
    "Minh là nhân viên mới. Giờ nghỉ trưa, anh ngồi ăn cùng chị Anna, đồng nghiệp người Úc, và hai người hỏi nhau về sở thích.",
    { A: "Minh", B: "Anna" },
    A("Anna, do you like sports?", "Chị Anna, chị có thích thể thao không?"),
    B("Yes, I do. I love swimming. I swim every Saturday.", "Có chứ. Tôi rất thích bơi. Thứ Bảy nào tôi cũng bơi."),
    A("Really? I like swimming too, but I'm not very good.", "Thật à? Tôi cũng thích bơi, nhưng tôi bơi không giỏi lắm."),
    B("What about you, Minh? What's your hobby?", "Còn anh thì sao, Minh? Sở thích của anh là gì?"),
    A("I enjoy reading. And I really like cooking.", "Tôi thích đọc sách. Và tôi rất thích nấu ăn."),
    B("Oh, nice! Does your wife like cooking?", "Ồ, hay quá! Vợ anh có thích nấu ăn không?"),
    A("No, she doesn't. She hates cooking, but she loves eating!", "Không. Cô ấy ghét nấu ăn, nhưng lại rất thích ăn!"),
    B("My husband is the same. He enjoys playing football and watching it on TV.", "Chồng tôi cũng vậy. Anh ấy thích chơi bóng đá và xem bóng đá trên ti vi."),
    A("Do you like football?", "Chị có thích bóng đá không?"),
    B("No, I don't. I hate watching football. I like dancing.", "Không. Tôi ghét xem bóng đá. Tôi thích nhảy."),
  ),
  task: task({
    prompt: "Một người bạn nước ngoài hỏi bạn: What do you like doing? Hãy viết 5–6 câu về sở thích của bạn và của một người trong gia đình, có cả điều bạn thích và điều bạn không thích.",
    hints: [
      "Dùng like, love, enjoy, hate + V-ing: I love reading.",
      "Khi nói về bố, mẹ, anh chị: nhớ thêm -s cho động từ chính (she loves, he enjoys).",
      "Điều không thích: I don't like… / She doesn't like…",
      "Kết thúc bằng một câu hỏi lại bạn mình: Do you like…?",
    ],
    model: "My hobby is reading. I love reading books on the bus. I also enjoy cooking for my family. I don't like shopping, and I hate getting up early. My sister loves dancing, but she doesn't like cooking. Do you like reading?",
    checklist: [
      "Có ít nhất 4 câu dùng like, love, enjoy hoặc hate + V-ing",
      "Không có hai động từ nguyên mẫu đứng liền nhau (không viết like read)",
      "Câu nói về he hoặc she có động từ thêm -s (she loves, he enjoys)",
      "Có ít nhất một câu phủ định với don't like hoặc doesn't like",
      "Không viết very like; nếu muốn nhấn mạnh thì dùng really",
      "Viết đúng chính tả -ing (dancing, swimming, shopping)",
    ],
    minWords: 25,
  }),
});
