import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "thoi-gian-va-lich-hen",
  title: "Thời gian và lịch hẹn",
  minutes: 22,
  lecture: {
    title: "Nói giờ, thứ, tháng và giới từ in/on/at",
    blocks: [
      p("Đặt lịch khám bệnh, hẹn khách hàng, hỏi giờ tàu chạy: việc nào cũng cần nói đúng **giờ** và **ngày**. Hẹn nhầm “thứ Ba lúc chín giờ kém mười lăm” thành “chín giờ mười lăm” là bạn đã đến muộn nửa tiếng. Bài này dạy bạn cách nói giờ kiểu người Anh và ba giới từ **in, on, at** đi với thời gian."),
      p("Ở bài trước bạn đã biết cách đơn giản nhất: đọc giờ rồi đọc phút (seven fifteen). Người Anh còn một cách nữa rất phổ biến: dùng **past** (qua) cho nửa giờ đầu và **to** (kém) cho nửa giờ sau. **Quarter** là mười lăm phút, **half** là ba mươi phút."),
      table(
        ["Giờ", "Cách nói với past / to", "Nghĩa tiếng Việt"],
        ["7:00", "seven o'clock", "bảy giờ đúng"],
        ["7:10", "ten past seven", "bảy giờ mười"],
        ["7:15", "quarter past seven", "bảy giờ mười lăm"],
        ["7:30", "half past seven", "bảy giờ rưỡi"],
        ["7:45", "quarter to eight", "tám giờ kém mười lăm"],
        ["7:50", "ten to eight", "tám giờ kém mười"],
      ),
      mistake("6:45 = quarter to six", "6:45 = quarter to seven", "Nhiều người Việt thấy số 6 là nói ngay six. Nhưng to nghĩa là “kém”, giống hệt “bảy giờ kém mười lăm” của tiếng Việt, tức là 6:45."),
      tip("Mẹo nhớ: **past** là đã **qua** giờ đó, **to** là còn **tới** giờ đó. Và nhớ rằng chữ **l** trong **half** câm: đọc là /hɑːf/, không đọc âm /l/."),
      p("Tên **thứ** và **tháng** trong tiếng Anh luôn **viết hoa chữ cái đầu**: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday; January, February, March, April, May, June, July, August, September, October, November, December."),
      mistake("See you on monday.", "See you on Monday.", "Tiếng Việt viết thường “thứ hai”, nên người Việt hay quên viết hoa. Trong tiếng Anh, thứ và tháng là danh từ riêng, luôn viết hoa."),
      p("Ba giới từ chỉ thời gian đi theo quy tắc **từ lớn đến nhỏ**: khoảng thời gian dài dùng **in**, một ngày cụ thể dùng **on**, một thời điểm chính xác dùng **at**."),
      table(
        ["Giới từ", "Dùng với", "Ví dụ"],
        ["in", "tháng, năm, mùa, buổi trong ngày", "in May, in 2026, in the summer, in the morning"],
        ["on", "thứ, ngày tháng, buổi của một thứ cụ thể", "on Monday, on the fifth of May, on Friday afternoon"],
        ["at", "giờ, và vài cụm cố định", "at six o'clock, at noon, at night, at the weekend"],
      ),
      ex("My appointment with the dentist is on Thursday at half past two.", "Lịch hẹn nha sĩ của tôi là thứ Năm lúc hai giờ rưỡi.", "Có cả thứ và giờ: on đi với thứ, at đi với giờ."),
      ex("Our office is closed in August.", "Văn phòng chúng tôi đóng cửa vào tháng Tám."),
      ex("I drink tea in the morning, but at night I only drink water.", "Tôi uống trà vào buổi sáng, nhưng ban đêm tôi chỉ uống nước.", "Nói in the morning, in the afternoon, in the evening, nhưng lại là at night."),
      ex("The class starts on Monday morning.", "Lớp học bắt đầu vào sáng thứ Hai.", "Có tên thứ đi kèm thì dùng on, dù có chữ morning."),
      mistake("in Monday / at May", "on Monday / in May", "Tiếng Việt chỉ dùng một chữ “vào” cho mọi trường hợp: vào thứ Hai, vào tháng Năm, vào lúc sáu giờ. Tiếng Anh tách thành ba giới từ, nên phải học theo nhóm."),
      teacher("Tôi dạy học trò nhớ in, on, at bằng hình **cái phễu**: miệng phễu rộng là **in** (tháng, năm), giữa phễu là **on** (ngày), đáy phễu nhọn là **at** (giờ). Mỗi tối trước khi ngủ, các em thử nói lịch của ngày mai bằng tiếng Anh, một câu thôi: I have a meeting on Tuesday at nine. Ba tháng sau các em sẽ không cần nghĩ nữa."),
    ],
  },
  words: [
    word("Monday", "/ˈmʌn.deɪ/", "thứ Hai", "See you on Monday.", "Mon|day", 0, "Phần Mon đọc là /mʌn/, không đọc “mon” như chữ viết."),
    word("Wednesday", "/ˈwenz.deɪ/", "thứ Tư", "We have English on Wednesday.", "Wednes|day", 0, "Chữ d đầu tiên câm: đọc là /ˈwenz.deɪ/, chỉ có hai âm tiết."),
    word("week", "/wiːk/", "tuần", "There are seven days in a week.", "week", 0),
    word("month", "/mʌnθ/", "tháng", "My birthday is next month.", "month", 0, "Âm cuối /nθ/: đưa đầu lưỡi ra giữa hai hàm răng, đừng đọc thành “mân”."),
    word("minute", "/ˈmɪn.ɪt/", "phút", "The bus comes in five minutes.", "min|ute", 0),
    word("quarter", "/ˈkwɔː.tər/", "mười lăm phút, một phần tư", "It's quarter past ten.", "quar|ter", 0),
    word("half", "/hɑːf/", "một nửa, rưỡi", "It's half past six.", "half", 0, "Chữ l câm: đọc là /hɑːf/."),
    word("appointment", "/əˈpɔɪnt.mənt/", "cuộc hẹn, lịch hẹn", "I have an appointment at ten o'clock.", "ap|point|ment", 1),
  ],
  exercises: [
    mc("a1-n06-1", "I have an appointment ___ Monday.", ["in", "on", "at"], 1, "Ngày trong tuần luôn đi với on."),
    mc("a1-n06-2", "8:45 được nói là:", ["quarter to nine", "quarter past eight", "quarter to eight"], 0, "Còn mười lăm phút nữa tới chín giờ nên là quarter to nine (chín giờ kém mười lăm)."),
    fill("a1-n06-3", "My birthday is ___ May.", ["in"], "Tháng dùng in."),
    fill("a1-n06-4", "The meeting is ___ three o'clock. (lúc)", ["at"], "Giờ chính xác dùng at."),
    reorder("a1-n06-5", "What time is your appointment?", "Hỏi giờ của một sự việc: What time + is + sự việc?"),
    reorder("a1-n06-6", "Is the meeting on Friday afternoon?", "Câu hỏi với to be: Is đứng đầu. Buổi chiều của một thứ cụ thể dùng on: on Friday afternoon."),
    listen("a1-n06-7", "It's quarter to seven.", ["Bây giờ là bảy giờ mười lăm.", "Bây giờ là bảy giờ kém mười lăm.", "Bây giờ là sáu giờ kém mười lăm."], 1, "Quarter to seven là bảy giờ kém mười lăm, tức 6:45."),
    listen("a1-n06-8", "See you on Wednesday at ten.", ["Hẹn gặp bạn thứ Năm lúc mười giờ.", "Hẹn gặp bạn thứ Tư lúc hai giờ.", "Hẹn gặp bạn thứ Tư lúc mười giờ."], 2, "Wednesday là thứ Tư, at ten là lúc mười giờ."),
  ],
  speaking: [
    say("My birthday is in October.", "Sinh nhật tôi vào tháng Mười."),
    say("The meeting is on Monday at half past nine.", "Cuộc họp vào thứ Hai lúc chín giờ rưỡi."),
    say("It's quarter to eight. We're late.", "Bây giờ là tám giờ kém mười lăm. Chúng ta muộn rồi."),
  ],
});
