import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "gia-dinh-khong-that",
  title: "Giả định không có thật",
  minutes: 23,
  lecture: {
    title: "Would rather, it's time, as if và wish: quá khứ giả định",
    blocks: [
      p("Đồng nghiệp hay gọi điện cho bạn lúc mười một giờ đêm. Bạn muốn nhắc khéo mà không mất lòng: **I'd rather you didn't call me so late.** Để ý nhé: nói về chuyện **bây giờ và sau này**, nhưng động từ lại ở **thì quá khứ**. Đây là **quá khứ giả định**: tiếng Anh lùi thì một bước để cho biết điều đang nói **không phải sự thật**, hoặc chỉ là **mong muốn**. Tiếng Việt không chia thì nên đây là điểm người Việt thấy lạ nhất."),
      table(
        ["Cấu trúc", "Ví dụ", "Nghĩa"],
        ["wish + quá khứ đơn", "I wish I lived closer to the office.", "Ước gì tôi sống gần công ty hơn (thực tế: nhà xa)."],
        ["would rather + S + quá khứ đơn", "I'd rather you didn't call me after ten.", "Tôi mong anh đừng gọi cho tôi sau mười giờ."],
        ["it's (high/about) time + S + quá khứ đơn", "It's high time we updated the website.", "Đã đến lúc (lẽ ra phải làm từ lâu) chúng ta cập nhật trang web."],
        ["as if / as though + quá khứ đơn", "He talks as if he owned the company.", "Anh ta nói cứ như thể mình là chủ công ty (thực ra không phải)."],
      ),
      p("**Would rather** có hai mẫu. Khi nói về **chính mình**, dùng **would rather + V nguyên mẫu** (có thể thêm **than + V**). Khi muốn **người khác** làm gì, dùng **would rather + S + quá khứ đơn**. Phủ định: **I'd rather not + V** và **I'd rather you didn't + V**."),
      ex("I'd rather work late tonight than come in on Saturday.", "Tôi thà làm muộn tối nay còn hơn phải đi làm vào thứ Bảy.", "Cùng một chủ ngữ nên dùng nguyên mẫu: work, come. Không dùng to."),
      ex("Would you rather I sent the report today or tomorrow?", "Anh muốn tôi gửi báo cáo hôm nay hay ngày mai?", "Khác chủ ngữ (you và I) nên dùng quá khứ: sent, dù đang nói về tương lai."),
      mistake("I'd rather you don't tell anyone.", "I'd rather you didn't tell anyone.", "Vì đang nói chuyện hiện tại nên học trò giữ nguyên thì hiện tại. Nhưng sau would rather + một người khác, bắt buộc lùi về quá khứ."),
      p("**It's time to + V** nói chung chung là đến giờ làm gì. **It's time + S + quá khứ đơn** thì mang ý **lẽ ra phải làm rồi, đang muộn**. Thêm **high** hoặc **about** là nhấn mạnh thêm, thường có ý phàn nàn."),
      ex("It's about time the company fixed the air conditioning.", "Đã đến lúc công ty phải sửa điều hòa rồi đấy.", "Có ý chê: lẽ ra phải sửa từ lâu."),
      mistake("It's time we go home.", "It's time we went home.", "Tiếng Việt “đến lúc mình về rồi” không có dấu hiệu thì nào, nên học trò dùng hiện tại. Sau It's time + chủ ngữ phải dùng quá khứ đơn. Nếu không muốn chia thì, dùng It's time to go home."),
      p("**As if / as though** dùng thì quá khứ khi điều đó **không có thật**. Khi điều đó **có thể thật**, ta dùng thì bình thường, thường sau **look, seem, sound**. Trong văn trang trọng, dùng **were** cho mọi ngôi."),
      ex("She speaks English as if she were a native speaker.", "Cô ấy nói tiếng Anh cứ như người bản xứ.", "Thực tế cô ấy không phải người bản xứ. Văn nói hằng ngày cũng chấp nhận was."),
      ex("It looks as if the meeting is going to run late.", "Có vẻ như cuộc họp sẽ kéo dài quá giờ.", "Điều này rất có thể xảy ra nên dùng thì bình thường, không lùi thì."),
      mistake("I wish I can speak Japanese.", "I wish I could speak Japanese.", "Ước về hiện tại thì lùi một thì: can thành could, am thành were, have thành had. Nhớ phân biệt với bài Tiếc nuối: ước về quá khứ thì dùng had + V3."),
      tip("Mẹo nhớ: **lùi thì là lùi xa khỏi sự thật**. Hễ thấy **wish, would rather + người khác, it's time + chủ ngữ, as if (không thật)**, hãy lùi động từ một bậc: hiện tại thành quá khứ. Viết bốn cụm này lên một tấm thẻ và gọi chúng là **bốn chiếc chìa khóa lùi thì**."),
      teacher("Nhiều năm chấm bài, tôi thấy học trò không sai vì không biết quy tắc, mà vì **tai chưa quen**. Câu **It's time we went** nghe lạ tai nên các em sửa thành **go**. Cách chữa duy nhất là nghe và nói thật nhiều. Tôi khuyên các em mỗi ngày tự nói về bản thân một câu **I wish…**, một câu **I'd rather…** và một câu **It's time I…** Ví dụ: **It's time I started exercising.** Nói to, nói thật lòng về đời mình, cấu trúc sẽ bám vào trí nhớ lâu hơn bất kỳ bảng công thức nào."),
    ],
  },
  words: [
    word("preference", "/ˈpref.ər.əns/", "sự ưa thích hơn, lựa chọn ưu tiên", "Do you have a preference for the meeting time?", "pref|er|ence", 0, "Trọng âm ở âm tiết đầu: PREF-er-ence, khác với động từ prefer nhấn âm sau."),
    word("reality", "/riˈæl.ə.ti/", "thực tế, hiện thực", "He talks as if he were rich, but the reality is very different.", "re|al|i|ty", 1),
    word("pretend", "/prɪˈtend/", "giả vờ", "She pretended that she hadn't seen the message.", "pre|tend", 1),
    word("imaginary", "/ɪˈmædʒ.ɪ.nər.i/", "tưởng tượng, không có thật", "The problem is imaginary, so stop worrying.", "i|mag|i|nar|y", 1),
    word("overdue", "/ˌəʊ.vəˈdjuː/", "quá hạn, lẽ ra phải có từ lâu", "These repairs are long overdue. It's high time the landlord fixed the roof.", "o|ver|due", 2, "Trọng âm chính ở âm tiết cuối: o-ver-DUE. Người Anh đọc /djuː/, gần “điu”."),
    word("punctual", "/ˈpʌŋk.tʃu.əl/", "đúng giờ", "I'd rather you were more punctual in the mornings.", "punc|tu|al", 0),
    word("annoyed", "/əˈnɔɪd/", "bực mình", "My boss looked annoyed when I arrived late.", "an|noyed", 1, "Âm cuối là /d/, nhớ đọc ra, đừng nuốt mất."),
    word("hypothetical", "/ˌhaɪ.pəˈθet.ɪ.kəl/", "mang tính giả định", "It's only a hypothetical question, so don't worry.", "hy|po|thet|i|cal", 2, "Trọng âm chính ở âm tiết thứ ba: hy-po-THET-i-cal. Âm /θ/ đặt đầu lưỡi giữa hai hàm răng."),
  ],
  exercises: [
    mc("b2-n08-1", "I'd rather you ___ your phone during the meeting.", ["don't use", "didn't use", "not use", "won't use"], 1, "Would rather + người khác + quá khứ đơn: I'd rather you didn't use… (tôi mong anh đừng dùng…)."),
    mc("b2-n08-2", "It's already midnight. It's high time we ___ home.", ["go", "will go", "went"], 2, "It's high time + S + quá khứ đơn, mang ý đáng lẽ phải về từ trước rồi."),
    fill("b2-n08-3", "He acts as if he ___ the boss, but he's just an intern. (be)", ["were", "was"], "Điều không có thật sau as if dùng quá khứ. Were là dạng trang trọng cho mọi ngôi, was dùng trong văn nói."),
    fill("b2-n08-4", "I'd rather ___ at home tonight than go to the party. (stay)", ["stay"], "Cùng chủ ngữ: would rather + V nguyên mẫu, không thêm to."),
    reorder("b2-n08-5", "It's time we started the meeting.", "It's time + S + quá khứ đơn: đã đến lúc (hơi muộn rồi) chúng ta bắt đầu họp."),
    reorder("b2-n08-6", "I'd rather you didn't tell anyone.", "Lời đề nghị tế nhị: tôi mong anh đừng kể với ai."),
    listen("b2-n08-7", "He talks as if he knew everything.", ["Anh ta biết mọi thứ nên nói rất hay.", "Anh ta muốn biết mọi thứ.", "Anh ta nói cứ như thể mình biết hết mọi thứ."], 2, "Knew sau as if là quá khứ giả định: thực ra anh ta không biết hết."),
    listen("b2-n08-8", "I wish I had more free time.", ["Ước gì tôi có nhiều thời gian rảnh hơn.", "Giá mà hồi đó tôi có nhiều thời gian rảnh hơn.", "Tôi sẽ có nhiều thời gian rảnh hơn."], 0, "Wish + quá khứ đơn là ước về hiện tại. Tiếc về quá khứ phải là I wish I had had…"),
  ],
  speaking: [
    say("I'd rather you didn't call me after ten o'clock.", "Tôi mong anh đừng gọi cho tôi sau mười giờ."),
    say("It's high time we updated our website.", "Đã đến lúc chúng ta phải cập nhật trang web rồi."),
    say("She talks as if she knew everyone here.", "Cô ấy nói cứ như thể quen hết mọi người ở đây."),
  ],
});
