import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "goi-dien-va-hop-truc-tuyen",
  title: "Gọi điện và họp trực tuyến",
  minutes: 22,
  lecture: {
    title: "Tương lai tiếp diễn và lời hỏi gián tiếp lịch sự khi gọi điện, họp video",
    blocks: [
      p("Ngày nay rất nhiều bạn đi làm phải họp qua Zoom, Teams với đối tác nước ngoài. Trên mạng, bạn không có nét mặt, cử chỉ để đỡ lời. Mất tiếng, hình giật, quên bật mic… người Việt thường **im lặng chờ** hoặc nói cộc lốc **Hello? Hello?** Bài này trang bị cho bạn ba thứ: **cụm câu xử lý sự cố khi gọi**, **thì tương lai tiếp diễn** để báo lịch của mình, và **câu hỏi gián tiếp** để hỏi thật lịch sự."),
      table(
        ["Tình huống", "Câu nên dùng"],
        ["Mở đầu cuộc gọi", "Hi, it's Lan from Minh Phat. Is this a good time to talk?"],
        ["Người kia quên bật mic", "I think you're on mute. We can't hear you."],
        ["Tiếng bị ngắt quãng", "Sorry, you're breaking up. Could you repeat that?"],
        ["Nhờ nói to hoặc chậm hơn", "Could you speak up a little? / Could you slow down a bit?"],
        ["Mất một người trong cuộc họp", "I think we've lost Hung. Shall we wait a minute?"],
        ["Báo vào muộn, rời sớm", "I'll be joining late. / I'll have to leave at ten."],
      ),
      ex("Sorry, Mr Brown, you're on mute. Could you unmute yourself?", "Xin lỗi anh Brown, anh đang tắt mic. Anh bật mic lên được không ạ?", "Luôn nói on mute (có giới từ on), giống on hold (đang chờ máy), on the line (đang ở đầu dây)."),
      p("Khi báo lịch của mình trong một cuộc gọi, người bản xứ rất hay dùng **thì tương lai tiếp diễn: will be + V-ing**. Thì này có hai công dụng chính: nói việc **đang diễn ra tại một thời điểm trong tương lai**, và nói việc **đã sắp xếp, sẽ diễn ra như một lẽ đương nhiên**. Khi dùng để hỏi, **Will you be + V-ing?** nghe nhẹ nhàng hơn hẳn, vì bạn chỉ hỏi kế hoạch của người ta chứ không ép ai làm gì."),
      table(
        ["Dạng câu", "Cấu trúc", "Ví dụ"],
        ["Khẳng định", "S + will ('ll) be + V-ing", "I'll be joining from the airport."],
        ["Phủ định", "S + won't be + V-ing", "I won't be attending the call tomorrow."],
        ["Nghi vấn", "Will + S + be + V-ing?", "Will you be presenting the figures today?"],
      ),
      ex("This time tomorrow I'll be flying to Singapore, so I won't be able to take your call.", "Giờ này ngày mai tôi đang bay sang Singapore, nên tôi sẽ không nghe máy được.", "Việc đang diễn ra tại một thời điểm cụ thể trong tương lai: this time tomorrow."),
      ex("Will you be using the meeting room this afternoon?", "Chiều nay anh có dùng phòng họp không ạ?", "Hỏi kế hoạch một cách tế nhị. So sánh: Will you use the meeting room? nghe giống như đang đề nghị hoặc yêu cầu người ta dùng phòng."),
      mistake("I'll be join the call at ten.", "I'll be joining the call at ten.", "Tiếng Việt không bao giờ biến đổi động từ, nên học trò hay quên đuôi -ing sau be. Công thức luôn là will be + V-ing, thiếu -ing là sai."),
      mistake("You are mute.", "You're on mute.", "Dịch từng chữ “bạn đang tắt tiếng” thành You are mute là một lỗi khá buồn cười: tính từ mute nghĩa là người bị câm. Phải nói on mute: đang ở chế độ tắt tiếng."),
      p("Khi hỏi thông tin trong cuộc gọi, câu hỏi trực tiếp như **When does the meeting start?** không sai, nhưng hơi thẳng. Hãy bọc nó trong một câu mở đầu lịch sự: **Could you tell me…?**, **Do you know…?**, **I'd like to know…** Điều quan trọng nhất: phần sau cụm mở đầu dùng **trật tự câu kể** (chủ ngữ đứng trước động từ), không còn do/does/did, không đảo trợ động từ. Câu hỏi Có/Không thì dùng **if** hoặc **whether**."),
      ex("Could you tell me what time the webinar finishes?", "Anh có thể cho tôi biết mấy giờ buổi hội thảo trực tuyến kết thúc không?", "Câu trực tiếp là What time does the webinar finish? Khi hỏi gián tiếp, bỏ does và động từ thêm -es theo chủ ngữ."),
      ex("Do you know if the client has received the link?", "Anh có biết khách hàng đã nhận được đường link chưa?"),
      mistake("Could you tell me when does the meeting start?", "Could you tell me when the meeting starts?", "Học trò thuộc lòng công thức “từ để hỏi + does + S + V” rồi bê nguyên vào mọi câu. Trong câu hỏi gián tiếp, phần sau Could you tell me đã là câu kể: S + V, không còn does."),
      tip("Khi nói nhanh, **I'll be** đọc liền thành /aɪl bi/, và nhớ bật rõ âm /t/ cuối trong **mute** /mjuːt/. Nếu đọc thành “miu” thì người nghe dễ nhầm với **mew** (tiếng mèo kêu)."),
      teacher("Sau **năm mươi năm đứng lớp**, tôi thấy học trò giỏi ngữ pháp vẫn đứng hình khi mạng chập chờn, chỉ vì chưa có sẵn câu trong miệng. Cách tôi dặn các em: viết **năm câu cứu cánh** (You're on mute. You're breaking up. Could you repeat that? I'll be joining late. Could you tell me…?) ra một tờ giấy nhỏ, dán ngay cạnh màn hình máy tính. Trước mỗi cuộc họp, đọc to một lượt. Chỉ sau hai tuần, các câu ấy sẽ tự bật ra đúng lúc, không cần nghĩ."),
    ],
  },
  words: [
    word("mute", "/mjuːt/", "chế độ tắt tiếng; tắt tiếng", "Please put your microphone on mute when you're not speaking.", "mute", 0, "Bật rõ âm /t/ ở cuối, đừng đọc thành “miu”."),
    word("connection", "/kəˈnek.ʃən/", "đường truyền, kết nối", "My internet connection is quite slow today.", "con|nec|tion", 1),
    word("microphone", "/ˈmaɪ.krə.fəʊn/", "micrô", "Could you check your microphone? We can't hear you.", "mi|cro|phone", 0, "Trọng âm ở âm tiết đầu: MI-cro-phone. Âm đầu đọc là /maɪ/, không đọc là “mi”."),
    word("extension", "/ɪkˈsten.ʃən/", "số máy lẻ", "You can reach me on extension two four five.", "ex|ten|sion", 1),
    word("available", "/əˈveɪ.lə.bəl/", "rảnh, có mặt để làm việc", "Will you be available for a quick call on Friday?", "a|vai|la|ble", 1, "Trọng âm ở âm tiết thứ hai: a-VAI-la-ble."),
    word("reschedule", "/ˌriːˈʃed.juːl/", "dời lịch, sắp xếp lại lịch", "Could we reschedule the call for next Tuesday?", "re|sched|ule", 1, "Người Anh thường đọc /ˈʃed.juːl/, người Mỹ đọc /ˈskedʒ.uːl/. Chọn một cách và dùng nhất quán."),
    word("participant", "/pɑːˈtɪs.ɪ.pənt/", "người tham gia", "There are twelve participants in today's video call.", "par|tic|i|pant", 1),
    word("voicemail", "/ˈvɔɪs.meɪl/", "hộp thư thoại, tin nhắn thoại", "I left a voicemail, but she hasn't called me back.", "voice|mail", 0),
  ],
  exercises: [
    mc("b2-n04-1", "Sorry, we can't hear you. I think you're ___.", ["in mute", "on mute", "at mute", "mute"], 1, "Cụm cố định là on mute: đang tắt tiếng. You're mute lại có nghĩa là bạn bị câm."),
    mc("b2-n04-2", "Please don't call me at three o'clock. I ___ with a client then.", ["meet", "will have met", "will be meeting", "am meet"], 2, "Việc đang diễn ra tại một thời điểm trong tương lai (lúc ba giờ) dùng will be + V-ing."),
    fill("b2-n04-3", "Sorry, I'll be ___ the call about ten minutes late. (join)", ["joining"], "Will be + V-ing: sau be phải là động từ thêm -ing."),
    fill("b2-n04-4", "Do you know ___ the client has received the meeting link?", ["if", "whether"], "Câu hỏi gián tiếp dạng Có/Không dùng if hoặc whether, sau đó là trật tự câu kể."),
    reorder("b2-n04-5", "I'll be joining the meeting a bit late.", "Tương lai tiếp diễn dùng để báo trước một việc đã tính sẵn: I'll be joining late."),
    reorder("b2-n04-6", "Could you tell me where the meeting is?", "Sau Could you tell me là trật tự câu kể: where the meeting is, không phải where is the meeting."),
    listen("b2-n04-7", "Sorry, you're breaking up. Could you repeat that?", ["Xin lỗi, tiếng của anh bị ngắt quãng. Anh nhắc lại được không?", "Xin lỗi, anh đang tắt mic. Anh bật lên được không?", "Xin lỗi, anh nói nhanh quá. Anh nói chậm lại được không?"], 0, "Break up khi nói về cuộc gọi nghĩa là tiếng bị rè, đứt quãng do đường truyền kém."),
    listen("b2-n04-8", "Will you be using the meeting room this afternoon?", ["Chiều nay anh đã dùng phòng họp chưa?", "Chiều nay anh dọn giúp phòng họp nhé.", "Anh dùng phòng họp suốt cả buổi chiều à?", "Chiều nay anh có định dùng phòng họp không?"], 3, "Will you be + V-ing? là cách hỏi kế hoạch của người khác một cách tế nhị."),
  ],
  speaking: [
    say("Sorry, I'll be joining the call a few minutes late.", "Xin lỗi, tôi sẽ vào cuộc gọi muộn vài phút."),
    say("I think you're on mute, so we can't hear you.", "Hình như anh đang tắt mic nên chúng tôi không nghe thấy gì."),
    say("Could you tell me when the next meeting is?", "Anh có thể cho tôi biết cuộc họp tiếp theo là khi nào không?"),
  ],
});
