import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "mao-tu",
  title: "Mạo từ: a, an, the hay không gì cả",
  minutes: 24,
  lecture: {
    title: "Khi nào dùng the, khi nào không dùng mạo từ",
    blocks: [
      p("Nếu phải chọn **một** lỗi mà người Việt ở trình độ nào cũng mắc, tôi chọn **mạo từ**. Tiếng Việt không có a, an, the: ta nói “Tôi thích âm nhạc”, “Chị ấy là giáo viên”, “Mặt trời mọc” mà chẳng cần thêm gì. Vì vậy khi viết tiếng Anh, học trò hoặc **bỏ quên mạo từ**, hoặc **thêm the vào khắp nơi** cho chắc. Bài này giúp bạn có một cách nghĩ rõ ràng thay vì đoán mò."),
      table(
        ["Dùng", "Khi nào", "Ví dụ"],
        ["a / an", "Danh từ đếm được số ít, nhắc lần đầu, hoặc “một cái nào đó”; nghề nghiệp", "She is an engineer. I bought a laptop."],
        ["the", "Người nghe biết rõ cái nào: đã nhắc trước, có cụm xác định đi kèm, chỉ có một", "The laptop I bought is fast. The sun is hot."],
        ["the", "So sánh nhất, số thứ tự, only, same", "the best hotel, the first time, the same answer"],
        ["Không mạo từ", "Danh từ số nhiều nói chung", "Children need love."],
        ["Không mạo từ", "Danh từ không đếm được và danh từ trừu tượng nói chung", "Water is essential. Honesty matters."],
        ["Không mạo từ", "Hầu hết tên nước, thành phố, bữa ăn, môn học", "Vietnam, Hanoi, have lunch, study history"],
      ),
      p("Câu hỏi quan trọng nhất khi chọn mạo từ không phải “danh từ này là gì”, mà là **“người nghe có biết tôi đang nói đến cái cụ thể nào không?”**. So sánh: **Coffee is popular in Vietnam** (cà phê nói chung) với **The coffee in this café is excellent** (cà phê ở quán này, cụ thể)."),
      ex("Money can't buy happiness.", "Tiền không mua được hạnh phúc.", "Money và happiness đều nói chung, không đếm được, nên không có mạo từ."),
      ex("The money you lent me is in the drawer.", "Số tiền bạn cho tôi mượn nằm trong ngăn kéo.", "Có cụm “you lent me” xác định rõ là tiền nào, nên phải có the."),
      ex("I read an article about climate change. The article said sea levels are rising.", "Tôi đọc một bài báo về biến đổi khí hậu. Bài báo nói mực nước biển đang dâng.", "Nhắc lần đầu dùng an, lần sau người nghe đã biết nên dùng the."),
      p("Riêng với **trường học, bệnh viện, nhà tù, nhà thờ, đại học, giường ngủ**: nếu nói về **mục đích chính** của nơi đó thì **không dùng mạo từ**. Nếu chỉ nói về **tòa nhà, địa điểm** thì dùng **the**."),
      table(
        ["Mục đích chính (không mạo từ)", "Chỉ là địa điểm (the)"],
        ["My son goes to school by bus. (đi học)", "I went to the school to meet his teacher. (đến trường gặp cô giáo)"],
        ["He is in hospital with a broken leg. (nằm viện)", "I went to the hospital to visit him. (đến thăm)"],
        ["She was sent to prison for five years. (đi tù)", "The prison is near the river. (tòa nhà)"],
        ["It's late. I'm going to bed. (đi ngủ)", "Your phone is under the bed. (cái giường)"],
      ),
      ex("My father has been in hospital since Monday.", "Bố tôi nằm viện từ thứ Hai.", "Tiếng Anh-Anh nói in hospital. Người Mỹ thường nói in the hospital, cả hai đều được chấp nhận."),
      mistake("The life is short, so enjoy it.", "Life is short, so enjoy it.", "Tiếng Việt nói “cuộc sống”, “cuộc đời” nên học trò tưởng phải có mạo từ. Danh từ trừu tượng nói chung (life, love, success) không dùng the."),
      mistake("She is teacher at a high school.", "She is a teacher at a high school.", "Tiếng Việt nói “Cô ấy là giáo viên” không cần “một”. Tiếng Anh bắt buộc có a/an trước nghề nghiệp ở số ít."),
      mistake("I love the music, especially the jazz.", "I love music, especially jazz.", "Thích âm nhạc nói chung thì không có the. Chỉ nói “I love the music in this film” khi đó là âm nhạc cụ thể."),
      tip("Mẹo **“chỉ tay được không?”**: nếu bạn có thể chỉ tay hoặc nói thêm “cái đó, cái mà…” thì thường dùng **the**. Nếu bạn đang nói về cả một loại, chung chung khắp thế giới, thì bỏ mạo từ và dùng **số nhiều** hoặc **danh từ không đếm được**: **Dogs are loyal**, không phải **The dogs are loyal**."),
      teacher("Nói thật với các bạn, mạo từ là thứ **tôi chưa thấy học trò nào học xong trong một buổi**. Nó chỉ vào đầu bằng cách đọc thật nhiều và để ý. Cách tôi hay giao bài: mỗi ngày chép lại **một đoạn tin tiếng Anh ngắn**, rồi khoanh tròn mọi a, an, the và mọi danh từ đứng trơn không mạo từ, tự giải thích từng chỗ. Sau một tháng, tai và mắt bạn sẽ tự thấy “câu này thiếu cái gì đó”. Và đừng quá sợ: sai mạo từ ít khi làm người ta hiểu nhầm, nhưng **dùng đúng thì câu của bạn nghe chuyên nghiệp hẳn lên**."),
    ],
  },
  words: [
    word("article", "/ˈɑː.tɪ.kəl/", "mạo từ; bài báo", "“The” is called the definite article.", "ar|ti|cle", 0),
    word("specific", "/spəˈsɪf.ɪk/", "cụ thể, riêng biệt", "Could you give me a specific example?", "spe|cif|ic", 1, "Trọng âm ở âm tiết thứ hai: spe-CIF-ic. Âm /s/ đầu và âm /k/ cuối đều phải rõ."),
    word("unique", "/juˈniːk/", "duy nhất, độc nhất", "Each fingerprint is unique.", "u|nique", 1, "Âm đầu là /j/ giống chữ “you”: you-NEEK, trọng âm ở âm sau. Không đọc “u-ních”."),
    word("uncountable", "/ʌnˈkaʊn.tə.bəl/", "không đếm được", "“Advice” is an uncountable noun.", "un|count|a|ble", 1),
    word("institution", "/ˌɪn.stɪˈtjuː.ʃən/", "cơ quan, tổ chức, thiết chế", "Banks and universities are important institutions.", "in|sti|tu|tion", 2),
    word("prison", "/ˈprɪz.ən/", "nhà tù", "He spent two years in prison.", "pris|on", 0, "Chữ s ở đây đọc là /z/: PRIZ-ơn."),
    word("equipment", "/ɪˈkwɪp.mənt/", "thiết bị", "All the equipment in the lab is new.", "e|quip|ment", 1, "Equipment không đếm được: không nói “an equipment” hay “equipments”, mà nói “a piece of equipment”."),
    word("knowledge", "/ˈnɒl.ɪdʒ/", "kiến thức", "Knowledge is more valuable than money.", "knowl|edge", 0, "Chữ k câm: đọc NOL-ij, không đọc “nâu-lết”."),
  ],
  exercises: [
    mc("b2-n14-1", "___ is the most important thing in life.", ["The health", "A health", "Health"], 2, "Sức khỏe nói chung là danh từ trừu tượng, không đếm được, nên không dùng mạo từ."),
    mc("b2-n14-2", "My son has a fever, so he didn't go to ___ today.", ["the school", "school", "a school", "schools"], 1, "Đi học (mục đích chính của trường) thì không dùng mạo từ: go to school."),
    fill("b2-n14-3", "She works as ___ engineer at a factory in Da Nang.", ["an"], "Nghề nghiệp số ít phải có mạo từ; engineer bắt đầu bằng nguyên âm /e/ nên dùng an."),
    fill("b2-n14-4", "___ moon goes around the Earth about once a month.", ["The"], "Chỉ có một mặt trăng của Trái Đất, là thứ duy nhất, nên dùng the."),
    reorder("b2-n14-5", "The sun rises in the east.", "Mặt trời và phương đông đều là thứ duy nhất, nên cả hai có the."),
    reorder("b2-n14-6", "She is the most patient teacher I know.", "So sánh nhất luôn đi với the: the most patient."),
    listen("b2-n14-7", "My grandmother has been in hospital since Monday.", ["Bà tôi đi thăm bệnh viện hôm thứ Hai.", "Bà tôi nằm viện từ thứ Hai.", "Bà tôi làm việc ở bệnh viện từ thứ Hai."], 1, "In hospital không có mạo từ nghĩa là đang nằm viện, đang được điều trị."),
    listen("b2-n14-8", "I went to the school to talk to my daughter's teacher.", ["Tôi đi học cùng con gái.", "Con gái tôi là giáo viên ở trường.", "Tôi dạy ở trường của con gái.", "Tôi đến trường để nói chuyện với cô giáo của con gái tôi."], 3, "The school: người nói chỉ đến tòa nhà trường học, không phải đi học."),
  ],
  speaking: [
    say("Honesty is the best policy.", "Trung thực là thượng sách."),
    say("My brother is an engineer, and his wife is a doctor.", "Anh trai tôi là kỹ sư, còn vợ anh ấy là bác sĩ."),
    say("I went to the hospital to visit my uncle.", "Tôi đến bệnh viện để thăm chú tôi."),
  ],
});
