import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "mo-ta-so-lieu",
  title: "Mô tả số liệu và biểu đồ",
  minutes: 24,
  lecture: {
    title: "Động từ, danh từ chỉ xu hướng, trạng từ mức độ và giới từ đi với số liệu",
    blocks: [
      p("Báo cáo doanh số hằng tháng, bài thi IELTS Writing Task 1, buổi trình bày kết quả kinh doanh: ở đâu cũng phải **nói về con số**. Người Việt thường chỉ quen một chữ **increase** và nói **Sales increase ten per cent**, thiếu giới từ và sai thì. Muốn mô tả số liệu cho chuyên nghiệp, bạn cần bốn thứ: **từ chỉ xu hướng**, **từ chỉ mức độ**, **giới từ đi kèm con số** và **cách nói xấp xỉ**."),
      table(
        ["Xu hướng", "Động từ", "Danh từ"],
        ["Tăng", "rise, increase, grow, climb", "a rise, an increase, growth"],
        ["Giảm", "fall, drop, decrease, decline", "a fall, a drop, a decrease, a decline"],
        ["Đạt đỉnh", "peak (at)", "a peak"],
        ["Chững lại, đi ngang", "level off, remain stable", "(thường dùng động từ)"],
        ["Lên xuống thất thường", "fluctuate", "a fluctuation"],
      ),
      p("Có hai cách viết cùng một ý. Cách một: **động từ + trạng từ** (rose sharply). Cách hai: **There was / There has been + tính từ + danh từ** (a sharp rise). Dùng xen kẽ hai cách để bài viết không bị lặp."),
      ex("Sales rose sharply in March.", "Doanh số tăng mạnh vào tháng Ba.", "Rise là động từ bất quy tắc: rise, rose, risen."),
      ex("There was a sharp rise in sales in March.", "Doanh số có một đợt tăng mạnh vào tháng Ba.", "Sau danh từ rise dùng in để nói tăng cái gì: a rise in sales."),
      table(
        ["Mức độ", "Trạng từ (đi với động từ)", "Tính từ (đi với danh từ)"],
        ["Rất mạnh", "dramatically", "dramatic"],
        ["Mạnh, nhanh", "sharply", "sharp"],
        ["Đều đặn", "steadily", "steady"],
        ["Từ từ", "gradually", "gradual"],
        ["Nhẹ", "slightly", "slight"],
      ),
      mistake("Sales increased sharp last month.", "Sales increased sharply last month.", "Tiếng Việt nói “tăng mạnh”, chữ “mạnh” không đổi hình thức dù đứng sau động từ hay danh từ. Tiếng Anh thì bổ nghĩa cho động từ phải dùng trạng từ có đuôi -ly."),
      p("Giới từ là chỗ người Việt sai nhiều nhất, vì tiếng Việt chỉ nói “tăng mười phần trăm”, “tăng lên hai trăm”. Hãy phân biệt rõ: **by** là **mức thay đổi**, **to** là **con số sau khi thay đổi**, **from… to** là điểm đầu và điểm cuối, **of** đi sau danh từ, **at** là mức đứng tại một thời điểm."),
      table(
        ["Giới từ", "Dùng khi", "Ví dụ"],
        ["by", "lượng tăng hoặc giảm", "Prices rose by five per cent."],
        ["to", "con số đạt được sau khi thay đổi", "Prices rose to two hundred dollars."],
        ["from… to", "điểm đầu và điểm cuối", "Unemployment fell from eight to six per cent."],
        ["of", "sau danh từ chỉ sự thay đổi", "There was a rise of five per cent."],
        ["at", "mức tại một thời điểm, mức đỉnh", "Sales peaked at nine thousand units in July."],
      ),
      ex("The number of visitors fell by a third, to about two million.", "Lượng khách giảm một phần ba, xuống còn khoảng hai triệu.", "By a third là mức giảm, to about two million là con số còn lại. Một câu dùng được cả hai."),
      mistake("There was an increase by ten per cent.", "There was an increase of ten per cent.", "By đi với động từ (increased by). Khi đã đổi sang danh từ (an increase), phải dùng of."),
      mistake("Sales were risen in May.", "Sales rose in May.", "Tiếng Việt hay nói “doanh số được tăng lên” nên học trò dùng bị động. Rise và fall là nội động từ, không có dạng bị động. Nếu có người làm cho giá tăng, dùng raise: The company raised its prices."),
      p("Không phải lúc nào cũng cần con số chính xác. Người bản xứ rất hay dùng từ **xấp xỉ**: **about, around, roughly, approximately** (khoảng), **just over** (nhỉnh hơn một chút), **just under** (hụt một chút), **nearly, almost** (gần), **well over** (hơn hẳn). Khi nói về **tương lai của số liệu** (dự báo), dùng **be expected to / be likely to / be forecast to + V**: **Sales are expected to rise slightly next year.** Cách nói này cho thấy bạn đang dự đoán, không phải hứa chắc."),
      ex("Just under half of the staff said they preferred working from home.", "Gần một nửa (hụt một chút) số nhân viên nói họ thích làm việc ở nhà hơn.", "Just under half: khoảng bốn mươi tám, bốn mươi chín phần trăm."),
      tip("Chú ý trọng âm: danh từ **increase** nhấn âm đầu /ˈɪn.kriːs/, động từ **increase** nhấn âm sau /ɪnˈkriːs/. Và **per cent** /pə ˈsent/ nhấn vào **cent**, nhớ bật âm /t/ ở cuối."),
      teacher("Học trò của tôi thi IELTS, ai cũng thuộc mấy chục động từ tăng giảm, nhưng khi viết vẫn sai giới từ. Tôi luôn dặn: **viết xong một câu có con số, hãy hỏi lại con số đó là “mức thay đổi” hay “chỗ dừng lại”**. Mức thay đổi thì by, chỗ dừng lại thì to. Mỗi sáng mở một biểu đồ bất kỳ trên báo, giá xăng, tỷ giá, số ca bệnh, và nói to ba câu mô tả nó. Một tháng sau các bạn sẽ nói về số liệu trôi chảy như đọc bản tin."),
    ],
  },
  words: [
    word("fluctuate", "/ˈflʌk.tʃu.eɪt/", "dao động, lên xuống thất thường", "Oil prices fluctuated throughout the year.", "fluc|tu|ate", 0, "Trọng âm ở âm tiết đầu: FLUC-tu-ate."),
    word("decline", "/dɪˈklaɪn/", "sự suy giảm; suy giảm", "There has been a steady decline in newspaper sales.", "de|cline", 1),
    word("peak", "/piːk/", "đạt đỉnh; đỉnh cao nhất", "Visitor numbers peaked at two million in August.", "peak", 0, "Bật âm /k/ ở cuối, nếu không sẽ nghe giống “pea”."),
    word("approximately", "/əˈprɒk.sɪ.mət.li/", "xấp xỉ, khoảng", "Approximately sixty per cent of users are under thirty.", "ap|prox|i|mate|ly", 1, "Trọng âm ở âm tiết thứ hai: ap-PROX-i-mate-ly."),
    word("proportion", "/prəˈpɔː.ʃən/", "tỷ lệ, phần", "A large proportion of our customers live in the south.", "pro|por|tion", 1),
    word("figure", "/ˈfɪɡ.ər/", "con số, số liệu", "The latest figures show a slight fall in unemployment.", "fig|ure", 0, "Đọc là /ˈfɪɡ.ə/, không đọc thành “phi-gơ-rơ”."),
    word("significant", "/sɪɡˈnɪf.ɪ.kənt/", "đáng kể", "There was a significant increase in online orders.", "sig|nif|i|cant", 1),
    word("gradual", "/ˈɡrædʒ.u.əl/", "dần dần, từ từ", "We expect a gradual recovery next year.", "grad|u|al", 0),
  ],
  exercises: [
    mc("b2-n10-1", "Profits fell ___ ten per cent, from two million to one point eight million dollars.", ["to", "by", "of", "at"], 1, "Mười phần trăm là mức giảm, nên dùng by. To đi với con số còn lại sau khi giảm."),
    mc("b2-n10-2", "There was a ___ increase in sales after the advertising campaign.", ["sharpen", "sharply", "sharp"], 2, "Trước danh từ increase phải là tính từ: a sharp increase."),
    fill("b2-n10-3", "Unemployment rose ___ five per cent in January to six per cent in June. (từ)", ["from"], "From… to: nêu điểm đầu và điểm cuối của sự thay đổi."),
    fill("b2-n10-4", "Sales ___ at twelve thousand units in August and then began to fall. (đạt đỉnh)", ["peaked"], "Peak at + con số: đạt đỉnh ở mức nào. Chuyện đã qua nên dùng quá khứ đơn."),
    reorder("b2-n10-5", "There was a slight fall in prices.", "There was + a + tính từ + danh từ + in + thứ thay đổi."),
    reorder("b2-n10-6", "The number of users rose to nine million.", "Rose to + con số: tăng lên đến mức nào."),
    listen("b2-n10-7", "Sales levelled off in the second half of the year.", ["Doanh số chững lại trong nửa cuối năm.", "Doanh số giảm mạnh trong nửa cuối năm.", "Doanh số tăng gấp đôi trong nửa cuối năm."], 0, "Level off: chững lại, đi ngang sau một thời gian tăng hoặc giảm."),
    listen("b2-n10-8", "Just over a third of the staff work from home.", ["Gần một phần ba số nhân viên làm việc ở nhà.", "Chỉ một phần ba số nhân viên đến văn phòng.", "Đúng một phần ba số nhân viên làm việc ở nhà.", "Nhỉnh hơn một phần ba số nhân viên làm việc ở nhà."], 3, "Just over: hơn một chút. Ngược lại là just under: hụt một chút."),
  ],
  speaking: [
    say("Sales rose sharply in the first quarter.", "Doanh số tăng mạnh trong quý một."),
    say("There was a slight fall of two per cent in May.", "Tháng Năm có một đợt giảm nhẹ hai phần trăm."),
    say("The figure peaked at about nine thousand in July.", "Con số đạt đỉnh vào khoảng chín nghìn trong tháng Bảy."),
  ],
});
