import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "tu-noi-nang-cao",
  title: "Liên kết ý mạch lạc",
  minutes: 22,
  lecture: {
    title: "Từ nối chỉ đối lập, bổ sung, kết quả và cách đặt dấu câu",
    blocks: [
      p("Bạn viết một bản báo cáo gửi sếp người Úc. Ý nào cũng đúng, từ nào cũng đúng, vậy mà sếp đọc vẫn thấy “rời rạc”. Lý do thường nằm ở **từ nối**: người Việt quen viết một chuỗi câu ngắn nối bằng **and** và **but**, hoặc dùng từ nối sang trọng nhưng đặt sai dấu câu. Hôm nay ta học những từ nối hay gặp nhất trong văn viết công việc và, quan trọng không kém, **dấu phẩy, dấu chấm phẩy đặt ở đâu**."),
      table(
        ["Chức năng", "Từ nối", "Nghĩa", "Vị trí thường gặp"],
        ["Đối lập hai sự thật", "whereas", "trong khi (đó)", "Giữa câu, nối hai mệnh đề: A, whereas B."],
        ["Đối lập, trái mong đợi", "however", "tuy nhiên", "Đầu câu mới: A. However, B."],
        ["Đối lập, trái mong đợi (mạnh, trang trọng)", "nevertheless", "tuy vậy, dù vậy", "Đầu câu mới: A. Nevertheless, B."],
        ["Bổ sung", "moreover / furthermore", "hơn nữa, ngoài ra", "Đầu câu mới: A. Moreover, B."],
        ["Kết quả", "therefore", "vì vậy, do đó", "Đầu câu mới hoặc giữa câu: We have therefore decided…"],
        ["Kết quả", "as a result / consequently", "kết quả là, do đó", "Đầu câu mới: A. As a result, B."],
      ),
      p("Điểm mấu chốt: **whereas** là **liên từ**, nó nối hai mệnh đề trong **cùng một câu**. Còn **however, nevertheless, moreover, therefore, as a result, consequently** là **trạng từ liên kết**, chúng không đủ sức nối hai mệnh đề bằng một dấu phẩy. Muốn dùng chúng, bạn phải **kết thúc câu trước bằng dấu chấm** hoặc dùng **dấu chấm phẩy**, rồi đặt **dấu phẩy sau từ nối**."),
      table(
        ["Cách viết", "Đúng hay sai"],
        ["The price is high. However, the quality is excellent.", "Đúng"],
        ["The price is high; however, the quality is excellent.", "Đúng (trang trọng)"],
        ["The price is high, however the quality is excellent.", "Sai: chỉ có dấu phẩy nối hai câu"],
        ["The price is high, whereas the cost of repairs is low.", "Đúng: whereas là liên từ"],
      ),
      ex("In the north, winters are cold, whereas in the south it is warm all year round.", "Ở miền Bắc, mùa đông lạnh, trong khi ở miền Nam trời ấm quanh năm.", "Whereas so sánh hai sự thật song song, không có ý “trái mong đợi”."),
      ex("The project was difficult. Nevertheless, the team finished it on time.", "Dự án rất khó. Dù vậy, cả nhóm vẫn hoàn thành đúng hạn."),
      ex("The new office is closer to the city centre. Moreover, the rent is lower.", "Văn phòng mới gần trung tâm hơn. Hơn nữa, tiền thuê lại thấp hơn."),
      ex("Demand has fallen. We have, therefore, decided to reduce production.", "Nhu cầu đã giảm. Vì vậy, chúng tôi quyết định giảm sản lượng.", "Therefore có thể đứng giữa câu, sau trợ động từ; khi đó có thể đặt giữa hai dấu phẩy hoặc không."),
      ex("Heavy rain flooded the roads. As a result, many shops closed early.", "Mưa lớn làm ngập đường. Kết quả là nhiều cửa hàng đóng cửa sớm.", "As a result + mệnh đề; còn as a result of + danh từ: as a result of the rain."),
      p("Ở B1, bài **Bày tỏ ý kiến**, các bạn đã học nêu ý kiến, đồng ý và phản đối từng câu một. Ở B2, bạn phải **bảo vệ một quan điểm** bằng cả một đoạn: nêu quan điểm, đưa **mặt lợi** và **mặt hại**, thừa nhận ý kiến trái chiều rồi mới kết luận. Chính các từ nối ở trên là xương sống của đoạn lập luận. Chú ý **On the one hand** và **On the other hand** đi thành cặp để cân hai mặt đối lập, mỗi cụm đứng đầu câu và có dấu phẩy phía sau."),
      table(
        ["Bước lập luận", "Cụm từ", "Ví dụ"],
        ["Nêu quan điểm", "In my view, … / I would argue that…", "I would argue that flexible hours improve productivity."],
        ["Nêu mặt lợi", "One advantage of… is that… / The main benefit is…", "One advantage of working from home is that staff save time."],
        ["Nêu mặt hại", "The main drawback is that… / Another disadvantage is…", "The main drawback is that people can feel lonely."],
        ["Cân hai mặt", "On the one hand, … On the other hand, …", "On the one hand, the plan is cheap. On the other hand, it is slow."],
        ["Thừa nhận rồi phản bác", "While it is true that…, … / I'm not convinced that…", "While it is true that the system is expensive, it will save money in the long run."],
        ["Kết luận", "Overall, … / On balance, I believe…", "On balance, I believe the benefits outweigh the costs."],
      ),
      mistake("Although the room was small, but it was very clean.", "Although the room was small, it was very clean.", "Tiếng Việt nói “Mặc dù… nhưng…” nên học trò hay dùng cả although lẫn but. Tiếng Anh chỉ dùng một trong hai: Although A, B hoặc A, but B."),
      mistake("The hotel is near the beach. On the other hand, it has a big pool.", "The hotel is near the beach. Moreover, it has a big pool.", "“Mặt khác” trong tiếng Việt thường mang nghĩa bổ sung, nhưng On the other hand trong tiếng Anh luôn chỉ sự đối lập. Muốn thêm ý, dùng moreover hoặc furthermore."),
      mistake("The flight was delayed, therefore we missed the meeting.", "The flight was delayed. Therefore, we missed the meeting.", "Therefore là trạng từ, không nối hai câu bằng dấu phẩy được. Hãy tách câu, dùng dấu chấm phẩy, hoặc đổi sang liên từ so: …delayed, so we missed…"),
      tip("Mẹo nhớ nhanh: **liên từ** (and, but, so, whereas, although) thì **đi được với dấu phẩy**. **Trạng từ liên kết** (however, moreover, therefore…) thì **cần dấu chấm hoặc chấm phẩy đứng trước**. Đọc to câu văn: chỗ nào bạn phải ngừng hẳn hơi thì đó là chỗ của dấu chấm."),
      teacher("Sau nhiều năm dạy, tôi thấy học trò giỏi thường mắc một tật: **thấy moreover, therefore sang trọng quá nên câu nào cũng nhét vào**. Một đoạn văn năm câu mà có bốn từ nối thì đọc như bài diễn văn. Mỗi đoạn, **một hai từ nối là đủ**, và phải đúng chức năng. Cách luyện của tôi: viết xong một email, lấy bút tô tất cả từ nối, rồi tự hỏi từng từ một: “Ý sau là **thêm**, **ngược lại** hay **hệ quả** của ý trước?” Trả lời được thì giữ, không trả lời được thì xóa."),
    ],
  },
  words: [
    word("coherent", "/kəʊˈhɪə.rənt/", "mạch lạc, chặt chẽ", "Her report was clear and coherent.", "co|her|ent", 1, "Trọng âm ở âm tiết thứ hai: co-HER-ent, âm /ɪə/ đọc gần như “ia”."),
    word("whereas", "/weəˈræz/", "trong khi (đó)", "Tom likes working alone, whereas Lan prefers teamwork.", "where|as", 1, "Nhấn vào âm sau: where-AS, cuối từ là âm /z/, không phải /s/."),
    word("furthermore", "/ˌfɜː.ðəˈmɔːr/", "hơn nữa, ngoài ra", "Furthermore, the new model uses less energy.", "fur|ther|more", 2),
    word("nevertheless", "/ˌnev.ə.ðəˈles/", "tuy vậy, dù vậy", "It was a risky plan. Nevertheless, we decided to try it.", "nev|er|the|less", 3, "Bốn âm tiết, trọng âm rơi vào âm cuối: nev-er-the-LESS."),
    word("consequently", "/ˈkɒn.sɪ.kwənt.li/", "do đó, vì thế", "Sales fell. Consequently, the company cut its budget.", "con|se|quent|ly", 0),
    word("contrast", "/ˈkɒn.trɑːst/", "sự tương phản, đối lập", "There is a sharp contrast between the two reports.", "con|trast", 0, "Danh từ nhấn âm đầu: CON-trast. Động từ “to contrast” nhấn âm sau."),
    word("paragraph", "/ˈpær.ə.ɡrɑːf/", "đoạn văn", "Each paragraph should focus on one main idea.", "par|a|graph", 0),
    word("drawback", "/ˈdrɔː.bæk/", "nhược điểm, mặt hạn chế", "The main drawback of the plan is the cost.", "draw|back", 0, "Âm đầu /drɔː/ tròn môi, kéo dài; không đọc thành “đra”."),
  ],
  exercises: [
    mc("b2-n11-1", "The first plan is cheaper, ___ the second plan is much faster.", ["whereas", "moreover", "therefore", "as a result"], 0, "Hai sự thật đặt cạnh nhau để so sánh, nối trong cùng một câu bằng dấu phẩy: chỉ có liên từ whereas làm được."),
    mc("b2-n11-2", "Which sentence is punctuated correctly?", ["The price is high, however the quality is excellent.", "The price is high; however, the quality is excellent.", "The price is high however the quality is excellent."], 1, "However là trạng từ liên kết: trước nó cần dấu chấm hoặc dấu chấm phẩy, sau nó là dấu phẩy."),
    fill("b2-n11-3", "The train was cancelled. As a ___, we arrived two hours late.", ["result", "consequence"], "As a result (hoặc as a consequence): kết quả là. Hai cụm này đứng đầu câu và có dấu phẩy phía sau."),
    fill("b2-n11-4", "Our sales fell sharply last year. We have ___ decided to cut costs. (vì vậy)", ["therefore", "consequently", "thus"], "Therefore đứng được giữa câu, ngay sau trợ động từ have. Consequently và thus cũng đúng ở vị trí này."),
    reorder("b2-n11-5", "The main drawback is that it costs too much.", "The main drawback is that + mệnh đề: cách nêu mặt hại rõ ràng trong đoạn lập luận."),
    reorder("b2-n11-6", "I am not convinced that it will work.", "I'm not convinced that…: phản bác một ý kiến một cách lịch sự, thay cho câu cộc lốc That's wrong."),
    listen("b2-n11-7", "The hotel was expensive. Nevertheless, we enjoyed our stay.", ["Khách sạn đắt nên chúng tôi không vui.", "Khách sạn rẻ và chúng tôi rất thích.", "Khách sạn đắt vì chúng tôi ở lâu.", "Khách sạn đắt, dù vậy chúng tôi vẫn rất thích thời gian ở đó."], 3, "Nevertheless báo hiệu điều trái mong đợi: đắt nhưng vẫn vui."),
    listen("b2-n11-8", "Moreover, the new software is easier to use.", ["Tuy nhiên, phần mềm mới khó dùng hơn.", "Hơn nữa, phần mềm mới dễ sử dụng hơn.", "Vì vậy, chúng ta cần phần mềm mới."], 1, "Moreover dùng để thêm một ý cùng chiều với ý trước."),
  ],
  speaking: [
    say("The project was difficult. Nevertheless, we finished it on time.", "Dự án rất khó. Dù vậy, chúng tôi vẫn hoàn thành đúng hạn."),
    say("On balance, I believe the benefits outweigh the costs.", "Cân nhắc mọi mặt, tôi tin rằng lợi ích lớn hơn chi phí."),
    say("The flight was delayed. As a result, we missed the meeting.", "Chuyến bay bị hoãn. Kết quả là chúng tôi lỡ cuộc họp."),
  ],
});
