import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "bi-dong-nang-cao",
  title: "Bị động ở mọi thì",
  minutes: 22,
  lecture: {
    title: "Bị động với hiện tại hoàn thành, tương lai, động từ khuyết thiếu và have something done",
    blocks: [
      p("Sáng thứ Hai, bạn mở email công ty: “The meeting **has been cancelled**.” Trên cửa thang máy dán tờ giấy: “This lift **will be repaired** tomorrow.” Ở quầy lễ tân: “Bags **must be left** here.” Ở bài trước (Tin tức và sự việc), bạn đã học bị động ở hiện tại đơn và quá khứ đơn. Hôm nay ta mở rộng ra các thì khác, vì thông báo, tin tức và biển báo dùng chúng hằng ngày."),
      p("Nguyên tắc chỉ có một: **be** luôn đứng trước **V3**, và chính chữ be này được chia theo thì. Phần V3 không bao giờ thay đổi."),
      table(
        ["Thì hoặc dạng", "Cấu trúc bị động", "Ví dụ"],
        ["Hiện tại hoàn thành", "have / has been + V3", "The meeting has been cancelled."],
        ["Tương lai đơn", "will be + V3", "The results will be sent by email."],
        ["Động từ khuyết thiếu", "can / must / should + be + V3", "This form must be completed today."],
        ["Phủ định", "hasn't been / won't be / can't be + V3", "The problem hasn't been solved yet."],
        ["Nghi vấn", "Has… been / Will… be / Can… be + V3?", "Has the parcel been delivered?"],
      ),
      ex("All the rooms have been cleaned.", "Tất cả các phòng đã được dọn xong.", "Hiện tại hoàn thành bị động: việc vừa xong, kết quả còn đến bây giờ."),
      ex("The new metro line will be opened next year.", "Tuyến tàu điện mới sẽ được khai trương vào năm sau."),
      ex("Mobile phones must be switched off during the exam.", "Điện thoại di động phải được tắt trong giờ thi."),
      ex("This medicine should be kept in a cool place.", "Thuốc này nên được bảo quản ở nơi thoáng mát."),
      p("Còn một cấu trúc rất đời thường: **have / get + đồ vật + V3**, nghĩa là **nhờ hoặc thuê người khác làm** việc gì đó cho mình. Get thân mật hơn have một chút."),
      table(
        ["Tự làm", "Thuê người làm"],
        ["I cut my hair. (tôi tự cắt tóc)", "I had my hair cut. (tôi đi cắt tóc ở tiệm)"],
        ["She repairs her motorbike.", "She gets her motorbike repaired."],
        ["We will paint the house.", "We will have the house painted."],
      ),
      ex("I'm going to have my car washed this afternoon.", "Chiều nay tôi sẽ mang xe đi rửa.", "Thì được chia ở động từ have, còn V3 đứng sau đồ vật: have my car washed."),
      mistake("The road has repaired.", "The road has been repaired.", "Tiếng Việt nói “đường sửa rồi” mà không cần chữ “được”, nên người Việt hay quên been. Con đường không tự sửa được, phải có been + V3."),
      mistake("This form must be fill in before Friday.", "This form must be filled in before Friday.", "Sau be luôn là V3. Nhiều bạn nhớ quy tắc “sau must là động từ nguyên mẫu” nên dùng fill, nhưng động từ nguyên mẫu ở đây chính là be."),
      mistake("I cut my hair yesterday. (ý là đi tiệm)", "I had my hair cut yesterday.", "Tiếng Việt nói “hôm qua tôi cắt tóc” dù thợ cắt cho mình. Tiếng Anh I cut my hair nghĩa là tự tay cắt. Muốn nói thuê người làm, dùng have something done."),
      tip("Sau **can, must, should, will**, chữ be **luôn giữ nguyên là be**: must be done, will be done. Không bao giờ viết must is done hay will been done. Khi nói nhanh, been đọc nhẹ thành /bɪn/, đừng kéo dài thành “biiin”."),
      teacher("Sau nhiều năm dạy, tôi có một mẹo để các bạn kiểm tra câu bị động: **đếm xem có đủ hai mảnh chưa**, một mảnh be đã chia (is, has been, will be, must be) và một mảnh V3. Thiếu một mảnh là sai. Các bạn hãy chụp ảnh ba tấm biển thông báo bằng tiếng Anh ở sân bay, khách sạn hay siêu thị, rồi gạch chân hai mảnh đó. Nhìn thật nhiều là tự khắc viết đúng."),
    ],
  },
  words: [
    word("repair", "/rɪˈpeər/", "sửa chữa", "The lift will be repaired tomorrow.", "re|pair", 1),
    word("cancel", "/ˈkæn.səl/", "hủy bỏ", "The flight has been cancelled.", "can|cel", 0, "Trọng âm ở âm đầu: CAN-cel. Chữ c thứ hai đọc là /s/."),
    word("deliver", "/dɪˈlɪv.ər/", "giao hàng, chuyển đến", "Your order will be delivered on Monday.", "de|liv|er", 1),
    word("replace", "/rɪˈpleɪs/", "thay thế", "The old windows have been replaced.", "re|place", 1),
    word("renovate", "/ˈren.ə.veɪt/", "cải tạo, sửa sang lại", "Our school will be renovated this summer.", "ren|o|vate", 0),
    word("hairdresser", "/ˈheəˌdres.ər/", "thợ làm tóc; tiệm làm tóc", "I had my hair cut at the hairdresser's.", "hair|dress|er", 0),
    word("postpone", "/pəʊstˈpəʊn/", "hoãn lại", "The match has been postponed because of the rain.", "post|pone", 1, "Âm /t/ ở giữa gần như không đọc. Hoãn là postpone, còn hủy hẳn là cancel."),
    word("complete", "/kəmˈpliːt/", "hoàn thành, điền đầy đủ", "The form must be completed in English.", "com|plete", 1),
  ],
  exercises: [
    mc("b1-n14-1", "The meeting ___ until next Monday.", ["has postponed", "has been postponed", "has being postponed", "was postpone"], 1, "Cuộc họp không tự hoãn, nên cần bị động: has been + V3."),
    mc("b1-n14-2", "I ___ my motorbike repaired yesterday.", ["made", "did", "had"], 2, "Thuê người khác sửa xe: have something done. Quá khứ của have là had."),
    fill("b1-n14-3", "The results will ___ sent to you by email.", ["be"], "Tương lai bị động: will be + V3."),
    fill("b1-n14-4", "This form must be ___ before Friday. (complete)", ["completed"], "Sau must be phải là V3: completed."),
    reorder("b1-n14-5", "Your parcel has been sent to the wrong address.", "Hiện tại hoàn thành bị động: has been + V3 (sent)."),
    reorder("b1-n14-6", "Where can I get my phone repaired?", "Get + đồ vật + V3: nhờ người khác sửa. Đồ vật my phone đứng trước repaired."),
    listen("b1-n14-7", "All the rooms have been cleaned.", ["Các phòng sẽ được dọn vào ngày mai.", "Chưa phòng nào được dọn.", "Tất cả các phòng đã được dọn xong.", "Bạn phải tự dọn phòng của mình."], 2, "Have been cleaned: đã được dọn, và bây giờ đã sạch."),
    listen("b1-n14-8", "Mobile phones must be switched off during the exam.", ["Điện thoại di động phải được tắt trong giờ thi.", "Bạn có thể dùng điện thoại trong giờ thi.", "Điện thoại sẽ được trả lại sau giờ thi."], 0, "Must be + V3: bắt buộc phải được làm."),
  ],
  speaking: [
    say("The meeting has been cancelled.", "Cuộc họp đã bị hủy."),
    say("The new bridge will be finished next year.", "Cây cầu mới sẽ được hoàn thành vào năm sau."),
    say("I'm going to have my hair cut this weekend.", "Cuối tuần này tôi sẽ đi cắt tóc."),
  ],
});
