import { A, B, correct, dialogue, ex, fill, free, lesson, listen, listenQ, mc, mistake, p, reading, reorder, say, summary, table, task, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "cau-hoi-duoi",
  title: "Câu hỏi đuôi: …, isn't it?",
  minutes: 30,
  lecture: {
    title: "Question tags: đuôi phủ định, đuôi khẳng định và ngữ điệu",
    blocks: [
      p("Bạn đứng chờ thang máy cùng một đồng nghiệp người Anh. Anh ấy nhìn ra cửa sổ và nói: **Hot today, isn't it?** Anh ấy không cần bạn báo nhiệt độ, chỉ muốn bắt chuyện cho vui. Trước cuộc họp, chị trưởng phòng hỏi: **You've sent the report, haven't you?** Lần này chị ấy muốn kiểm tra lại cho chắc. Cái đuôi nhỏ ở cuối câu ấy gọi là **câu hỏi đuôi** (question tag), và người bản ngữ dùng nó suốt ngày."),
      p("Tiếng Việt chỉ cần gắn một chữ cố định vào cuối câu: “phải không?”, “đúng không?”, “nhỉ?”. Tiếng Anh thì đuôi **thay đổi theo từng câu**. Quy tắc gốc: câu chính **khẳng định** thì đuôi **phủ định**, câu chính **phủ định** thì đuôi **khẳng định**. Đuôi lặp lại **trợ động từ** (be, do, have, will, can…) của câu chính và **đại từ** thay cho chủ ngữ."),
      table(
        ["Câu chính có", "Câu hỏi đuôi", "Ví dụ"],
        ["be (am / is / are / was / were)", "lặp lại be", "The hotel is near the beach, isn't it?"],
        ["động từ thường ở hiện tại đơn", "don't / doesn't", "Your brother works in Hue, doesn't he?"],
        ["động từ thường ở quá khứ đơn", "didn't / did", "You called Lan yesterday, didn't you?"],
        ["have / has + V3", "haven't / hasn't", "She has finished the report, hasn't she?"],
        ["will / can / should / must", "lặp lại động từ khuyết thiếu", "You can't drive, can you?"],
      ),
      ex("It's a gorgeous day, isn't it?", "Hôm nay trời đẹp quá, nhỉ?", "Chủ ngữ it, động từ is: đuôi là isn't it."),
      ex("Minh doesn't eat seafood, does he?", "Minh không ăn hải sản, phải không?", "Câu chính phủ định (doesn't) nên đuôi khẳng định (does). Minh là nam nên đại từ là he."),
      ex("The train left on time, didn't it?", "Tàu chạy đúng giờ, phải không?", "Câu chính không có trợ động từ nào hiện ra (left), nên ta mượn did ở đuôi, giống như khi đặt câu hỏi."),
      p("Có vài trường hợp đặc biệt cần học thuộc, vì chúng không theo đúng quy tắc gốc:"),
      table(
        ["Câu chính", "Đuôi", "Ví dụ"],
        ["I am…", "aren't I?", "I'm late again, aren't I?"],
        ["Let's…", "shall we?", "Let's take a taxi, shall we?"],
        ["Câu mệnh lệnh", "will you? / won't you?", "Close the door, will you?"],
        ["There is / There are…", "isn't there? / aren't there?", "There's a bank near here, isn't there?"],
        ["never, nothing, nobody, hardly…", "đuôi khẳng định", "He never calls, does he?"],
        ["this / that; everyone, somebody", "it; they", "Everyone is here, aren't they?"],
      ),
      ex("Nothing happened while I was away, did it?", "Trong lúc tôi đi vắng không có chuyện gì xảy ra, phải không?", "Nothing đã mang nghĩa phủ định, nên câu chính được coi là phủ định và đuôi phải khẳng định: did it."),
      p("**Ngữ điệu** quyết định nghĩa của câu hỏi đuôi. **Lên giọng** ở đuôi: bạn thật sự không chắc và đang hỏi. **Xuống giọng** ở đuôi: bạn gần như chắc chắn, chỉ muốn người kia xác nhận hoặc đồng ý. Khi trả lời, hãy trả lời theo **sự thật**, không theo câu hỏi: You don't smoke, do you? Nếu bạn không hút thì nói **No, I don't**; nếu có hút thì nói **Yes, I do**."),
      tip("Mẹo nhớ: câu chính và đuôi như hai đầu cái cân, **một bên có not thì bên kia không có**. Mẹo phát âm: đuôi đọc lướt và liền như một từ: isn't it đọc gần như /ˈɪz.nɪt/, doesn't he đọc gần như /ˈdʌz.ən.ti/ (âm h bị nuốt). Đừng tách rời từng chữ, nghe sẽ rất cứng."),
      mistake("You're a new student, isn't it?", "You're a new student, aren't you?", "Tiếng Việt dùng “phải không?” cho mọi câu, nên người học gắn isn't it vào bất cứ đâu. Đuôi phải lặp lại động từ của câu chính (are) và đại từ của chủ ngữ (you)."),
      mistake("He went home early, wasn't he?", "He went home early, didn't he?", "Người học quen nghĩ “quá khứ là was”. Nhưng went là động từ thường, không có be, nên đuôi phải mượn did: didn't he."),
      mistake("She never drinks coffee, doesn't she?", "She never drinks coffee, does she?", "Tiếng Việt không có câu nào mà chữ “không bao giờ” làm thay đổi phần đuôi. Trong tiếng Anh, never đã là phủ định, nên đuôi phải khẳng định."),
      mistake("You don't eat pork, do you? – No, I eat it.", "You don't eat pork, do you? – Yes, I do.", "Người Việt đáp “Không, tôi có ăn” để bác lại ý người hỏi. Tiếng Anh trả lời theo sự thật: có ăn thì Yes, I do; không ăn thì No, I don't. Nói No mà lại có ăn thì người nghe sẽ hiểu ngược hẳn."),
      teacher("Nhiều bạn học viên hỏi tôi: “Em nói …, right? cho nhanh có được không?” Trong giao tiếp thân mật, right? vẫn dùng được. Nhưng nếu chỉ biết mỗi right?, các bạn sẽ không bắt kịp khi người khác nói nhanh isn't it, don't you, have you, và bài thi nói cũng sẽ mất điểm. Cách tôi hay cho học trò luyện: mỗi ngày chọn năm câu khẳng định về những thứ quanh mình, như The coffee is cold, Nam has left, và thêm đuôi thành tiếng, **một lần lên giọng, một lần xuống giọng**. Chỉ vài tuần là đuôi tự bật ra."),
      summary(
        "Câu chính **khẳng định** thì đuôi **phủ định**, câu chính **phủ định** thì đuôi **khẳng định**.",
        "Đuôi lặp lại trợ động từ hoặc động từ khuyết thiếu của câu chính; không có trợ động từ thì mượn **do / does / did**.",
        "Trường hợp đặc biệt: I am… **aren't I?**; Let's… **shall we?**; câu mệnh lệnh… **will you?**; there is… **isn't there?**",
        "never, nothing, nobody đã mang nghĩa phủ định, nên đuôi phải **khẳng định**: He never calls, does he?",
        "**Lên giọng** là hỏi thật; **xuống giọng** là mong người nghe đồng ý. Trả lời theo sự thật: Yes, I do hoặc No, I don't.",
      ),
    ],
  },
  words: [
    word("gorgeous", "/ˈɡɔː.dʒəs/", "rất đẹp, tuyệt đẹp", "It's a gorgeous morning, isn't it?", "gor|geous", 0, "Chữ g thứ hai đọc là /dʒ/, âm cuối /dʒəs/, không đọc thành “gơ-gi-ớt”."),
    word("awkward", "/ˈɔː.kwəd/", "ngượng ngùng, khó xử", "There was an awkward silence after his joke.", "awk|ward", 0, "Cụm aw đọc là /ɔː/, âm sau đọc nhẹ /kwəd/; không đọc âm r."),
    word("obviously", "/ˈɒb.vi.əs.li/", "rõ ràng là", "Obviously, she wasn't happy about the news.", "ob|vi|ous|ly", 0),
    word("surely", "/ˈʃɔː.li/", "chắc chắn là, hẳn là", "Surely you've heard of Ha Long Bay?", "sure|ly", 0, "Chữ s đọc là /ʃ/ như trong she."),
    word("nod", "/nɒd/", "gật đầu", "When I asked if he was ready, he just nodded.", "nod", 0, "Giữ rõ âm cuối /d/; quá khứ là nodded."),
    word("remark", "/rɪˈmɑːk/", "lời nhận xét; nhận xét", "She made a funny remark about the weather.", "re|mark", 1, "Trọng âm ở âm sau: ri-MAAK. Không đọc âm r cuối âm tiết."),
  ],
  exercises: [
    mc("b1-n19-1", "You're coming to the party tonight, ___?", ["isn't it", "don't you", "aren't you", "are you"], 2, "Câu chính khẳng định với are và chủ ngữ you, nên đuôi là aren't you."),
    mc("b1-n19-2", "Nobody called while I was out, ___?", ["didn't they", "did they", "did nobody", "didn't he"], 1, "Nobody đã mang nghĩa phủ định, nên đuôi khẳng định. Nobody, everyone, somebody dùng đại từ they ở đuôi."),
    fill("b1-n19-3", "Your sister works in a bank, ___?", ["doesn't she", "does she not"], "Câu chính có động từ thường ở hiện tại đơn (works), không có trợ động từ, nên mượn doesn't ở đuôi."),
    fill("b1-n19-4", "Let's order some bubble tea, ___?", ["shall we"], "Câu bắt đầu bằng Let's thì đuôi luôn là shall we."),
    reorder("b1-n19-5", "You haven't seen my keys, have you?", "Câu chính phủ định ở hiện tại hoàn thành (haven't seen), nên đuôi khẳng định: have you."),
    reorder("b1-n19-6", "I'm late again, aren't I?", "I am… đi với đuôi đặc biệt aren't I, không nói amn't I."),
    listen("b1-n19-7", "The meeting starts at nine, doesn't it?", ["Cuộc họp đã bắt đầu từ chín giờ rồi.", "Mấy giờ thì cuộc họp bắt đầu?", "Cuộc họp bắt đầu lúc chín giờ, phải không?"], 2, "Doesn't it ở cuối là câu hỏi đuôi, dùng để kiểm tra lại thông tin."),
    listen("b1-n19-8", "There isn't any milk left, is there?", ["Không còn chút sữa nào, phải không?", "Còn nhiều sữa lắm, đúng không?", "Bạn mua thêm sữa nhé?"], 0, "There isn't… is there?: câu chính phủ định, đuôi khẳng định với there."),
    correct("b1-n19-9", "Your brother lives in Da Nang, isn't he?", "Your brother lives in Da Nang, doesn't he?", "Lives là động từ thường ở hiện tại đơn, không có be, nên đuôi phải là doesn't he, không phải isn't he."),
    correct("b1-n19-10", "She has never been to Hue, hasn't she?", "She has never been to Hue, has she?", "Never đã là phủ định, nên đuôi phải khẳng định: has she."),
  ],
  speaking: [
    say("It's a gorgeous day, isn't it?", "Hôm nay trời đẹp quá, nhỉ?"),
    say("You haven't met my manager, have you?", "Bạn chưa gặp quản lý của tôi, phải không?"),
    say("Let's take a photo together, shall we?", "Mình chụp chung một tấm ảnh nhé?"),
  ],
  freeSpeaking: free(
    "How do you start a conversation with someone new at work or on a trip?",
    "Nói bạn thường bắt chuyện thế nào với một người mới gặp (đồng nghiệp mới, khách du lịch), kèm ít nhất ba câu hỏi đuôi bạn có thể dùng.",
    "When I meet someone new at work, I usually start with the weather or the traffic. For example, I say, \"It's really hot today, isn't it?\" or \"The traffic was terrible this morning, wasn't it?\" Then I ask about their job: \"You work in the marketing team, don't you?\" People usually smile and answer, and the conversation starts easily.",
  ),
  dialogue: dialogue(
    "Kiểm tra lại trước chuyến đi Hạ Long",
    "Tối thứ Năm, Sarah, đồng nghiệp mới người Úc, gặp Minh ở văn phòng để kiểm tra lại mọi thứ trước chuyến du lịch Hạ Long của công ty vào sáng hôm sau.",
    { A: "Sarah, đồng nghiệp người Úc", B: "Minh" },
    A("Minh, the bus leaves at seven tomorrow, doesn't it?", "Minh ơi, mai xe khởi hành lúc bảy giờ, phải không?"),
    B("Yes, seven o'clock sharp. You haven't forgotten your passport, have you? The hotel needs it.", "Ừ, đúng bảy giờ. Bạn chưa quên hộ chiếu đấy chứ? Khách sạn cần nó."),
    A("No, it's in my bag. We don't need to bring towels, do we?", "Không, nó ở trong túi rồi. Mình không cần mang khăn tắm, phải không?"),
    B("No, we don't. The hotel has everything. The boat trip is on Saturday, isn't it?", "Không cần đâu. Khách sạn có đủ cả. Chuyến đi thuyền là vào thứ Bảy, phải không nhỉ?"),
    A("That's right. And it's going to rain on Sunday, isn't it?", "Đúng rồi. Mà Chủ nhật trời sẽ mưa, phải không?"),
    B("I'm afraid so. Let's sit together on the bus, shall we?", "E là vậy. Mình ngồi cạnh nhau trên xe nhé?"),
    A("Good idea. Nobody gets seasick on those boats, do they?", "Ý hay đấy. Chắc chẳng ai say sóng trên mấy chiếc thuyền đó đâu nhỉ?"),
    B("Some people do, actually! You aren't afraid of boats, are you?", "Thật ra cũng có người bị đấy! Bạn không sợ đi thuyền chứ?"),
    A("No, I'm not. I grew up by the sea. You can swim, can't you?", "Không, mình không sợ. Mình lớn lên ở gần biển mà. Bạn biết bơi, phải không?"),
    B("Yes, I can, but not very well! Don't forget your hat, will you? The sun is very strong there.", "Có, nhưng bơi không giỏi lắm! Đừng quên mang mũ nhé. Nắng ở đó gắt lắm."),
    A("I won't. It's going to be a gorgeous weekend, isn't it?", "Mình sẽ không quên. Cuối tuần này chắc sẽ tuyệt lắm, nhỉ?"),
    B("Yes, it is. I'm really glad you're coming with us.", "Chắc chắn rồi. Mình rất vui vì bạn đi cùng mọi người."),
  ),
  dialogueQuestions: [
    listenQ("b1-n19-d1", "Why does Sarah need her passport?", "Yes, seven o'clock sharp. You haven't forgotten your passport, have you? The hotel needs it.", ["The hotel needs it.", "She is flying to Ha Long.", "The boat company needs it.", "She wants to change money."], 0, "Minh nói: The hotel needs it."),
    mc("b1-n19-d2", "When is the boat trip?", ["On Friday", "On Saturday", "On Sunday", "On Monday"], 1, "The boat trip is on Saturday, isn't it? – That's right."),
    mc("b1-n19-d3", "Why isn't Sarah afraid of boats?", ["She has been on many boat trips in Vietnam.", "She never gets seasick.", "She grew up by the sea."], 2, "Sarah nói: No, I'm not. I grew up by the sea."),
  ],
  reading: reading({
    title: "Questions that aren't really questions",
    text: `When I first moved to Manchester to study, I noticed something strange. People kept asking me questions that were not really questions. At the bus stop one morning, an old lady looked at the grey sky and said, "Terrible weather, isn't it?" I started to explain the weather in Vietnam, and she looked a little surprised. Later, I understood. She didn't want information. She just wanted a friendly chat.

In English, question tags like isn't it, don't you or have you help people to start a conversation and to sound polite. When the voice goes down at the end, the speaker is almost sure and only wants you to agree. The best answer is short: "Yes, it is!" When the voice goes up, it is a real question, and the speaker needs an answer.

My biggest problem was answering negative questions. My flatmate once asked, "You don't eat pork, do you?" I eat pork, but I answered "No", because in Vietnamese that means "You're wrong". She heard "No, I don't eat pork", and for a whole week she didn't cook pork when I was at home. In English, you answer about the facts: "Yes, I do" or "No, I don't".

Now, after two years, tags feel natural. I use them at work every day: "You've sent the report, haven't you?" or "Let's have a break, shall we?" My advice is simple: listen to the music of the voice, not only the words. A tag with a falling voice is often just a small, friendly way of saying hello.`,
    glossary: [
      ["notice", "để ý, nhận thấy"],
      ["grey", "xám, u ám"],
      ["flatmate", "bạn ở cùng căn hộ"],
      ["pork", "thịt lợn"],
      ["fact", "sự thật"],
      ["falling voice", "giọng đi xuống"],
    ],
    questions: [
      mc("b1-n19-r1", "What is the blog post mainly about?", ["How to talk about the weather in Manchester", "How the writer learnt to understand and use question tags", "Why the writer's flatmate stopped cooking", "The differences between English and Vietnamese food"], 1, "Cả bài kể người viết dần hiểu và dùng được câu hỏi đuôi khi sống ở Anh."),
      mc("b1-n19-r2", "What did the old lady at the bus stop want?", ["Information about the weather in Vietnam", "Directions to the university", "A friendly chat", "Help with her shopping"], 2, "Đoạn một: She didn't want information. She just wanted a friendly chat."),
      fill("b1-n19-r3", "When the voice goes ___ at the end of a tag, it is a real question.", ["up"], "Đoạn hai: When the voice goes up, it is a real question."),
      mc("b1-n19-r4", "Why didn't the flatmate cook pork for a week?", ["She thought the writer didn't eat pork.", "Pork was too expensive that week.", "The writer asked her not to.", "She didn't like pork herself."], 0, "Người viết đáp No theo kiểu tiếng Việt, nên cô bạn hiểu là người viết không ăn thịt lợn."),
      mc("b1-n19-r5", "What can we guess about the writer now?", ["The writer still avoids question tags.", "The writer feels more comfortable in English conversations.", "The writer wants to go back to Vietnam.", "The writer never talks about the weather."], 1, "Người viết nói tags feel natural và dùng chúng hằng ngày ở chỗ làm, nên ta đoán người viết đã tự tin hơn khi giao tiếp."),
    ],
  }),
  task: task({
    prompt: "Ngày mai bạn cùng một đồng nghiệp người nước ngoài tiếp khách hàng. Viết một tin nhắn (khoảng 90–110 từ) để kiểm tra lại các chi tiết của buổi gặp: giờ họp, phòng họp, tài liệu, bữa trưa. Dùng ít nhất 5 câu hỏi đuôi.",
    hints: [
      "Câu khẳng định đi với đuôi phủ định: The meeting starts at nine, doesn't it?",
      "Câu phủ định đi với đuôi khẳng định: You haven't changed the slides, have you?",
      "Dùng thêm một đuôi đặc biệt: Let's…, shall we? hoặc Don't forget…, will you?",
      "Chọn trợ động từ ở đuôi theo thì của câu chính: is, does, did, has, will.",
    ],
    model: "Hi Tom, I'm just checking a few things before our meeting with the clients from Singapore tomorrow. The meeting starts at nine, doesn't it? I've booked the small meeting room on the third floor, and it's big enough for six people, isn't it? You haven't changed the slides since Friday, have you? I want to print them tonight. Mr Lee doesn't eat seafood, does he? I remember something about that from his last visit, so I'm going to order lunch from the Thai restaurant near our office. Let's meet at half past eight and prepare together, shall we? And don't forget the new price list, will you? Thanks, Hoa",
    checklist: [
      "Có ít nhất 5 câu hỏi đuôi.",
      "Có cả đuôi phủ định sau câu khẳng định (doesn't it, isn't it) và đuôi khẳng định sau câu phủ định (have you, does he).",
      "Có ít nhất 1 đuôi đặc biệt: Let's… shall we? hoặc câu mệnh lệnh… will you?",
      "Trợ động từ ở đuôi khớp với câu chính: hiện tại đơn dùng do / does, hiện tại hoàn thành dùng have / has.",
      "Không gắn isn't it hay …, right? vào mọi câu.",
    ],
    minWords: 90,
  }),
});
