import { A, B, dialogue, ex, fill, lesson, listen, mc, mistake, p, reorder, say, summary, table, task, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "dong-tu-theo-sau",
  title: "Động từ theo sau là gì?",
  minutes: 22,
  lecture: {
    title: "Động từ + to V và động từ + V-ing",
    blocks: [
      p("Tiếng Việt ghép hai động từ rất tự do: “tôi **thích nấu** ăn”, “tôi **quyết định nghỉ** việc”, không cần thêm gì. Tiếng Anh thì khác: động từ đứng sau phải có hình thức do **động từ đứng trước quyết định**, hoặc **to + V**, hoặc **V-ing**. Không có quy tắc tuyệt đối, nên ta học theo nhóm."),
      table(
        ["Theo sau là", "Động từ thường gặp", "Ví dụ"],
        ["to + V", "want, decide, hope, plan, promise, refuse, agree, learn, need, would like", "I've decided to change my job."],
        ["V-ing", "enjoy, avoid, finish, mind, suggest, consider, keep, practise, give up", "I enjoy cooking for my family."],
        ["Cả hai, nghĩa gần như không đổi", "like, love, hate, start, begin", "It started raining. / It started to rain."],
      ),
      ex("She hopes to study abroad next year.", "Cô ấy hy vọng sẽ đi du học vào năm sau."),
      ex("We finished eating and asked for the bill.", "Chúng tôi ăn xong và gọi thanh toán."),
      ex("Would you mind closing the door?", "Bạn có phiền đóng cửa giúp tôi không?", "Would you mind + V-ing là cách nhờ rất lịch sự. Nếu đồng ý giúp, trả lời No, not at all (không phiền gì cả)."),
      p("Quy tắc chắc chắn nhất: **sau giới từ luôn là V-ing**. Các giới từ hay gặp: in, at, of, about, for, without, instead of, before, after."),
      table(
        ["Cụm", "Ví dụ"],
        ["be interested in + V-ing", "I'm interested in learning Japanese."],
        ["be good at + V-ing", "He's good at fixing computers."],
        ["thank you for + V-ing", "Thank you for helping me."],
        ["look forward to + V-ing", "I look forward to hearing from you."],
        ["before / after / without + V-ing", "Wash your hands before eating."],
      ),
      ex("He left without saying goodbye.", "Anh ấy bỏ đi mà không chào một tiếng."),
      tip("Mẹo nhớ: các động từ đi với **to V** thường hướng về **tương lai**, chuyện chưa làm (want, hope, plan, decide, promise). Các động từ đi với **V-ing** thường nói về **việc đang có, đang trải qua** (enjoy, finish, avoid, mind). Mẹo này đúng với phần lớn trường hợp, không phải tất cả, nên vẫn cần học thuộc danh sách."),
      p("Nhờ nhóm động từ đi với to V, bạn nói được về **ước mơ, hy vọng và dự định** của mình: **My dream is to…** (ước mơ của tôi là…), **I hope to…**, **I'd love to…**, **I'm planning to…**. Nếu kế hoạch còn đang cân nhắc, dùng **I'm thinking of + V-ing** hoặc **I'm considering + V-ing**. Of là giới từ, nên theo sau là V-ing."),
      ex("My dream is to open a small café by the sea. I'm thinking of taking a business course first.", "Ước mơ của tôi là mở một quán cà phê nhỏ bên bờ biển. Tôi đang tính học một khóa kinh doanh trước.", "My dream is + to V để nói ước mơ; think of + V-ing để nói dự định còn đang cân nhắc."),
      mistake("I enjoy to cook Vietnamese food.", "I enjoy cooking Vietnamese food.", "Tiếng Việt không đổi hình thức động từ nên người Việt hay chọn đại to V. Enjoy luôn đi với V-ing."),
      mistake("I look forward to hear from you.", "I look forward to hearing from you.", "Chữ to ở đây là giới từ, không phải to của động từ nguyên mẫu, nên theo sau phải là V-ing. Đây là lỗi rất hay gặp trong email công việc."),
      mistake("She decided going home early.", "She decided to go home early.", "Decide luôn đi với to V."),
      teacher("Tôi dạy nửa thế kỷ và chưa thấy ai nhớ được danh sách này bằng cách chép một trăm lần. Cách hiệu quả là **học động từ kèm luôn cái đuôi**: đừng học enjoy, hãy học **enjoy doing**; đừng học decide, hãy học **decide to do**. Các bạn viết vào sổ tay đúng như vậy. Mỗi khi viết email, trước khi gửi hãy dò lại những chữ look forward to, thank you for, interested in, xem sau chúng đã là V-ing chưa. Thói quen nhỏ này giúp các bạn tránh một lỗi mà sếp nước ngoài nhìn thấy ngay."),
      summary(
        "to + V sau want, decide, hope, plan, promise, refuse, agree, need, would like.",
        "V-ing sau enjoy, avoid, finish, mind, suggest, consider, keep, practise, give up.",
        "Sau giới từ luôn là V-ing: interested in, good at, thank you for, before / after / without.",
        "Look forward to + V-ing: chữ to ở đây là giới từ.",
        "Học động từ kèm luôn cái đuôi: enjoy doing, decide to do.",
      ),
    ],
  },
  words: [
    word("avoid", "/əˈvɔɪd/", "tránh", "I try to avoid driving in the rush hour.", "a|void", 1, "Luôn đi với V-ing: avoid doing something."),
    word("enjoy", "/ɪnˈdʒɔɪ/", "thích, tận hưởng", "My father enjoys reading the newspaper.", "en|joy", 1),
    word("refuse", "/rɪˈfjuːz/", "từ chối", "He refused to answer my question.", "re|fuse", 1, "Âm cuối là /z/, không phải /s/."),
    word("promise", "/ˈprɒm.ɪs/", "hứa", "I promise to call you tonight.", "prom|ise", 0, "Trọng âm ở âm đầu; âm cuối là /ɪs/, không đọc thành “pro-mai”."),
    word("suggest", "/səˈdʒest/", "đề nghị, gợi ý", "She suggested going to the beach.", "sug|gest", 1, "Chữ gg ở đây đọc là /dʒ/."),
    word("mind", "/maɪnd/", "phiền, bận tâm", "Do you mind waiting a few minutes?", "mind", 0),
    word("consider", "/kənˈsɪd.ər/", "cân nhắc, xem xét", "We're considering moving to Da Nang.", "con|sid|er", 1),
    word("hesitate", "/ˈhez.ɪ.teɪt/", "do dự, ngần ngại", "Please don't hesitate to contact me.", "hes|i|tate", 0, "Chữ s ở đây đọc là /z/."),
  ],
  exercises: [
    mc("b1-n07-1", "I've decided ___ a new job.", ["looking for", "to look for", "look for", "to looking for"], 1, "Decide đi với to + V: decided to look for."),
    mc("b1-n07-2", "Would you mind ___ the window?", ["to open", "open", "opening"], 2, "Mind luôn đi với V-ing: Would you mind opening…?"),
    fill("b1-n07-3", "She finished ___ the report at midnight. (write)", ["writing"], "Finish đi với V-ing: finished writing."),
    fill("b1-n07-4", "I'm looking forward to ___ you next week. (see)", ["seeing"], "To trong look forward to là giới từ, nên theo sau là V-ing."),
    reorder("b1-n07-5", "She refused to answer my question.", "Refuse đi với to + V: refused to answer."),
    reorder("b1-n07-6", "He is very good at fixing computers.", "Sau giới từ at dùng V-ing: good at fixing."),
    listen("b1-n07-7", "I avoid driving in the rush hour.", ["Tôi thích lái xe vào giờ cao điểm.", "Tôi tránh lái xe vào giờ cao điểm.", "Tôi chưa bao giờ học lái xe."], 1, "Avoid + V-ing: tránh làm việc gì."),
    listen("b1-n07-8", "Thank you for coming to my birthday party.", ["Cảm ơn bạn đã đến dự tiệc sinh nhật của tôi.", "Bạn có đến dự tiệc sinh nhật của tôi không?", "Tôi xin lỗi vì không đến dự tiệc sinh nhật của bạn."], 0, "Thank you for + V-ing: cảm ơn vì đã làm gì."),
  ],
  speaking: [
    say("I enjoy walking in the park after dinner.", "Tôi thích đi dạo trong công viên sau bữa tối."),
    say("My dream is to open a small café by the sea.", "Ước mơ của tôi là mở một quán cà phê nhỏ bên bờ biển."),
    say("Thank you for helping me with my homework.", "Cảm ơn bạn đã giúp tôi làm bài tập."),
  ],
  dialogue: dialogue(
    "Dự định năm tới",
    "Nam và Vy gặp nhau ở quán cà phê cuối tuần, kể cho nhau nghe về công việc và dự định sắp tới.",
    { A: "Nam", B: "Vy" },
    A("So, how's your new job? Do you enjoy working there?", "Công việc mới thế nào? Bạn có thích làm ở đó không?"),
    B("Yes, I do. And I've decided to learn Japanese, because my company is planning to open an office in Osaka.", "Có chứ. Mình còn quyết định học tiếng Nhật, vì công ty mình đang có kế hoạch mở văn phòng ở Osaka."),
    A("That's great! Are you thinking of moving there?", "Hay quá! Bạn đang tính chuyển sang đó à?"),
    B("Maybe. My manager suggested applying for a job there. I'm considering it.", "Có thể. Sếp mình gợi ý nộp đơn vào vị trí ở đó. Mình đang cân nhắc."),
    A("I hope to change jobs too. I really want to avoid spending two hours in traffic every day.", "Mình cũng hy vọng đổi việc. Mình thật sự muốn tránh mất hai tiếng kẹt xe mỗi ngày."),
    B("Have you considered working from home? Many companies allow it now.", "Bạn đã cân nhắc làm việc ở nhà chưa? Giờ nhiều công ty cho phép lắm."),
    A("Good idea. I'm good at designing websites, so I could work online.", "Ý hay đấy. Mình giỏi thiết kế trang web, nên có thể làm trực tuyến."),
    B("Exactly. Don't hesitate to ask me if you need help with your CV.", "Đúng vậy. Đừng ngại hỏi mình nếu bạn cần giúp viết CV nhé."),
    A("Thanks for offering. I promise to buy you dinner when I find a new job!", "Cảm ơn bạn đã ngỏ ý. Mình hứa sẽ mời bạn ăn tối khi tìm được việc mới!"),
    B("Deal! I'm looking forward to having that dinner.", "Chốt nhé! Mình mong bữa tối đó lắm đấy."),
  ),
  task: task({
    prompt: "Viết một email ngắn (6–8 câu) gửi một người bạn, kể về những việc bạn thích làm dạo này và dự định của bạn trong năm tới.",
    hints: [
      "Dùng enjoy / avoid / keep + V-ing cho thói quen.",
      "Dùng hope / plan / decide + to V cho dự định.",
      "Thêm ít nhất một cụm giới từ + V-ing: interested in, good at, before / after.",
      "Kết thư bằng I look forward to hearing from you.",
    ],
    model: "Hi Lan, how are you? These days I really enjoy cooking for my family at the weekend, and I've started going to the gym after work. I try to avoid eating fast food, but it isn't easy! I've decided to take a baking course next year because I'm interested in opening a small cake shop one day. I also hope to visit you in Da Nang in the summer. I promise to bring you some of my cakes. I look forward to hearing from you. Best wishes, Hoa",
    checklist: [
      "Có ít nhất hai động từ + V-ing (enjoy, avoid, keep, finish…).",
      "Có ít nhất hai động từ + to V (hope, plan, decide, promise…).",
      "Sau giới từ (in, at, for, after…) dùng V-ing.",
      "Viết đúng look forward to hearing, không viết to hear.",
      "Không có lỗi kiểu enjoy to cook hay decided going.",
    ],
    minWords: 60,
  }),
});
