import { A, B, dialogue, ex, fill, lesson, listen, mc, mistake, p, reorder, say, summary, table, task, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "menh-de-quan-he",
  title: "Người mà, cái mà",
  minutes: 22,
  lecture: {
    title: "Mệnh đề quan hệ xác định: who, which, that, where, whose",
    blocks: [
      p("Bạn muốn nói với khách nước ngoài: “Đây là **người mà** đã giúp tôi tìm khách sạn” hay “Đó là **quán mà** tôi hay ăn phở.” Để thêm thông tin xác định **người nào, cái nào, nơi nào**, tiếng Anh dùng **mệnh đề quan hệ**, đặt ngay sau danh từ. Tiếng Việt dùng một chữ “mà” cho mọi trường hợp, còn tiếng Anh chọn từ theo loại danh từ."),
      table(
        ["Từ", "Dùng cho", "Ví dụ"],
        ["who", "người", "The man who lives next door is a doctor."],
        ["which", "vật, con vật", "I lost the bag which my mother gave me."],
        ["that", "người hoặc vật (văn nói rất hay dùng)", "This is the phone that I bought last week."],
        ["where", "nơi chốn", "That's the café where we first met."],
        ["whose", "của người đó, của vật đó (sở hữu)", "I have a friend whose father is a pilot."],
      ),
      ex("A nurse is a person who looks after patients.", "Y tá là người chăm sóc bệnh nhân."),
      ex("Hanoi is the city where I was born.", "Hà Nội là thành phố nơi tôi sinh ra."),
      ex("She's the woman whose son won the competition.", "Bà ấy là người phụ nữ có cậu con trai đã thắng cuộc thi.", "Whose + danh từ: thay cho her son, his car, their house."),
      p("**Lược bỏ đại từ quan hệ**: khi who, which, that đóng vai **tân ngữ**, tức là theo sau nó đã có một chủ ngữ khác, ta có thể bỏ đi. Người bản xứ bỏ rất thường xuyên khi nói."),
      table(
        ["Đầy đủ", "Lược bỏ", "Có bỏ được không?"],
        ["The book that I'm reading is great.", "The book I'm reading is great.", "Được, vì sau that có chủ ngữ I."],
        ["The man who called you is my boss.", "(không bỏ được)", "Không, vì who chính là chủ ngữ của called."],
      ),
      ex("Is this the book you were talking about?", "Đây có phải cuốn sách mà bạn đã nhắc đến không?", "Đã lược bỏ that. Giới từ about được đẩy xuống cuối câu."),
      tip("Mẹo kiểm tra: che từ who / which / that đi rồi nhìn phía sau. Nếu ngay sau đó là **một chủ ngữ + động từ** (I bought, you met) thì bỏ được. Nếu ngay sau đó là **động từ** (lives, called) thì phải giữ lại. Mẹo phát âm: whose đọc là /huːz/, giống hệt who's; nghe theo ngữ cảnh để phân biệt."),
      mistake("The man who he lives next door is a doctor.", "The man who lives next door is a doctor.", "Người Việt quen nghĩ vế nào cũng phải có chủ ngữ riêng, nên thêm he vào sau who. Nhưng who đã làm chủ ngữ của lives rồi, không lặp lại he nữa."),
      mistake("I lost the bag which my mother gave it to me.", "I lost the bag which my mother gave me.", "Which đã thay cho the bag, nên không thêm it nữa."),
      mistake("That's the restaurant which we had dinner.", "That's the restaurant where we had dinner.", "Nói về nơi xảy ra sự việc thì dùng where (hoặc which … at, nhưng where tự nhiên hơn)."),
      teacher("Tôi vẫn nhớ một học viên làm hướng dẫn viên du lịch, mỗi lần giới thiệu đều nói một chuỗi câu ngắn: “This is a temple. It is old. People built it in 1070.” Tôi chỉ dạy anh ấy ghép lại: **This is a temple which people built in 1070.** Khách nghe thấy chuyên nghiệp hơn hẳn. Lời khuyên của tôi: mỗi ngày các bạn lấy hai câu ngắn có chung một danh từ và **ghép thành một câu** bằng who, which, where hay whose. Làm đều tay một tháng, câu nói của các bạn sẽ dài và mượt hơn rất nhiều."),
      summary(
        "who cho người, which cho vật, that cho cả người lẫn vật, where cho nơi chốn, whose + danh từ chỉ sở hữu.",
        "Mệnh đề quan hệ đứng ngay sau danh từ mà nó bổ nghĩa.",
        "Không lặp lại chủ ngữ hay tân ngữ: the man who lives (không phải who he lives), the bag which my mother gave me (không thêm it).",
        "Bỏ được who / which / that khi ngay sau nó là chủ ngữ + động từ: the book I'm reading.",
        "Nói về nơi xảy ra sự việc thì dùng where: the café where we first met.",
      ),
    ],
  },
  words: [
    word("landlord", "/ˈlænd.lɔːd/", "chủ nhà (cho thuê)", "The landlord who owns this building lives in Da Nang.", "land|lord", 0),
    word("recipe", "/ˈres.ɪ.pi/", "công thức nấu ăn", "This is the recipe my grandmother gave me.", "rec|i|pe", 0, "Có ba âm tiết, chữ e cuối được đọc: RES-i-pi, không đọc thành “ri-xíp”."),
    word("author", "/ˈɔː.θər/", "tác giả", "He's the author whose books are sold everywhere.", "au|thor", 0, "Âm th là /θ/: đặt đầu lưỡi giữa hai hàm răng và thổi hơi, đừng đọc thành /t/."),
    word("owner", "/ˈəʊ.nər/", "người chủ, chủ sở hữu", "I met the owner of the shop where I bought this.", "own|er", 0),
    word("device", "/dɪˈvaɪs/", "thiết bị", "A charger is a device that gives power to your phone.", "de|vice", 1, "Âm cuối là /s/. Đừng nhầm với động từ devise, âm cuối /z/."),
    word("village", "/ˈvɪl.ɪdʒ/", "làng", "This is the village where my parents grew up.", "vil|lage", 0, "Âm cuối là /ɪdʒ/, không đọc thành “vi-lết”."),
    word("describe", "/dɪˈskraɪb/", "miêu tả", "Can you describe the man who took your bag?", "de|scribe", 1),
    word("tool", "/tuːl/", "công cụ, dụng cụ", "A hammer is a tool which you use for hitting nails.", "tool", 0, "Âm /l/ cuối cần nâng lưỡi chạm lợi trên, đừng bỏ mất."),
  ],
  exercises: [
    mc("b1-n08-1", "A nurse is a person ___ looks after patients.", ["which", "who", "where", "whose"], 1, "Danh từ chỉ người (a person) và đại từ làm chủ ngữ của looks: who."),
    mc("b1-n08-2", "That's the hotel ___ we stayed last summer.", ["which", "who", "where"], 2, "Nơi xảy ra việc (chúng tôi ở đó) nên dùng where."),
    fill("b1-n08-3", "I have a friend ___ father is a pilot.", ["whose"], "Bố của người bạn đó: whose + danh từ."),
    fill("b1-n08-4", "The phone ___ I bought last week has stopped working. (đại từ quan hệ chỉ vật)", ["that", "which"], "Danh từ chỉ vật: that hoặc which. Ở câu này cũng có thể bỏ hẳn đại từ đi vì sau nó có chủ ngữ I."),
    reorder("b1-n08-5", "Is this the book you were talking about?", "Đã lược bỏ that sau the book. Giới từ about đứng cuối câu."),
    reorder("b1-n08-6", "Do you know anyone who speaks Japanese?", "Anyone chỉ người nên dùng who; who là chủ ngữ của speaks nên không bỏ được."),
    listen("b1-n08-7", "The girl who is sitting next to Lan is my cousin.", ["Cô gái ngồi cạnh Lan là em họ tôi.", "Lan đang ngồi cạnh em họ tôi.", "Em họ tôi tên là Lan."], 0, "Mệnh đề who is sitting next to Lan xác định cô gái nào."),
    listen("b1-n08-8", "That's the restaurant where we had our first date.", ["Chúng tôi định hẹn hò lần đầu ở nhà hàng đó.", "Nhà hàng đó đã đóng cửa sau buổi hẹn đầu tiên.", "Đó là nhà hàng nơi chúng tôi có buổi hẹn hò đầu tiên."], 2, "Where + mệnh đề: nơi xảy ra sự việc."),
  ],
  speaking: [
    say("My sister is a teacher who works in a village school.", "Chị gái tôi là giáo viên dạy ở một trường làng."),
    say("This is the phone I bought last week.", "Đây là chiếc điện thoại tôi mua tuần trước."),
    say("Hanoi is the city where I was born.", "Hà Nội là thành phố nơi tôi sinh ra."),
  ],
  dialogue: dialogue(
    "Dẫn khách dạo phố cổ",
    "Minh là hướng dẫn viên du lịch, đang dẫn chị Sarah, một du khách người Úc, đi dạo phố cổ Hà Nội.",
    { A: "Minh", B: "Sarah" },
    A("This is the street where you can buy traditional silk.", "Đây là con phố nơi chị có thể mua lụa truyền thống."),
    B("Lovely! Who is the old man who is sitting outside that shop?", "Đẹp quá! Ông cụ đang ngồi trước cửa hàng kia là ai vậy?"),
    A("He's the owner. He's a man whose family has run the shop for a hundred years.", "Ông ấy là chủ tiệm. Gia đình ông đã mở tiệm này suốt một trăm năm."),
    B("Amazing. And what's the dish that everyone is eating over there?", "Tuyệt thật. Còn món mà mọi người đang ăn đằng kia là gì?"),
    A("That's bun cha. It's the dish which President Obama tried in Hanoi.", "Đó là bún chả. Đó là món mà Tổng thống Obama đã ăn thử ở Hà Nội."),
    B("I read about that! Is this the restaurant where he ate it?", "Tôi có đọc về chuyện đó! Đây có phải nhà hàng nơi ông ấy đã ăn không?"),
    A("No, the restaurant he visited is on another street. I can take you there.", "Không, nhà hàng ông ấy ghé nằm ở phố khác. Tôi có thể đưa chị tới đó."),
    B("Great. I also need a shop that sells good coffee. It's for my friends at home.", "Tuyệt. Tôi cũng cần một cửa hàng bán cà phê ngon. Để làm quà cho bạn bè ở nhà."),
    A("I know a woman whose coffee shop is near the lake. Her coffee is the best I've ever tried.", "Tôi quen một chị có quán cà phê gần hồ. Cà phê của chị ấy ngon nhất mà tôi từng uống."),
    B("You're the kind of guide who knows everything! Let's go.", "Anh đúng là kiểu hướng dẫn viên cái gì cũng biết! Đi thôi."),
  ),
  task: task({
    prompt: "Viết một đoạn văn 6–8 câu giới thiệu quê hương hoặc khu phố của bạn cho một người bạn nước ngoài: một địa điểm, một người và một món ăn đặc biệt.",
    hints: [
      "Dùng where cho địa điểm: the market where…",
      "Dùng who hoặc whose cho người: a woman whose son…",
      "Dùng which / that, hoặc lược bỏ đại từ, cho món ăn và đồ vật.",
      "Thử ghép hai câu ngắn có chung một danh từ thành một câu.",
    ],
    model: "I come from Nam Dinh, a small city which is about ninety kilometres from Hanoi. Near my house there is a market where people sell fresh fish every morning. My favourite person there is an old lady who has sold rice cakes for forty years. She has a son whose restaurant is famous for beef noodle soup. It's a dish that every visitor should try. The temple I visit every spring is also worth seeing. I hope you can come and visit the city where I grew up.",
    checklist: [
      "Có ít nhất một câu với who và một câu với where.",
      "Có ít nhất một câu với whose + danh từ.",
      "Không lặp lại chủ ngữ hay tân ngữ trong mệnh đề (who he…, which… it).",
      "Có ít nhất một câu lược bỏ that / which đúng chỗ.",
      "Mệnh đề quan hệ đứng ngay sau danh từ mà nó bổ nghĩa.",
    ],
    minWords: 60,
  }),
});
