import { word } from "../builders";
import type { WordTopic } from "../types";

/** Extra A1 vocabulary by topic, reviewed with spaced repetition (see /tu-vung). */
const topics: WordTopic[] = [
  {
    id: "thong-tin-ca-nhan",
    title: "Thông tin cá nhân & chào hỏi",
    words: [
      word("hi", "/haɪ/", "chào (thân mật)", "Hi, I'm Lan.", "hi", 0),
      word("goodbye", "/ɡʊdˈbaɪ/", "tạm biệt", "Goodbye, see you tomorrow!", "good|bye", 1),
      word("bye", "/baɪ/", "tạm biệt (thân mật)", "Bye, Tom! See you later.", "bye", 0),
      word("please", "/pliːz/", "làm ơn, vui lòng", "Can I have some water, please?", "please", 0, "Cuối từ là âm /z/ rung nhẹ, không đọc cụt thành “pli”."),
      word("thanks", "/θæŋks/", "cảm ơn", "Thanks for your help.", "thanks", 0, "Âm /θ/: đặt đầu lưỡi giữa hai hàm răng rồi thổi hơi, không đọc thành “th” tiếng Việt."),
      word("sorry", "/ˈsɒr.i/", "xin lỗi", "Sorry, I'm late.", "sor|ry", 0),
      word("welcome", "/ˈwel.kəm/", "chào mừng", "Welcome to our school!", "wel|come", 0),
      word("yes", "/jes/", "vâng, có", "Yes, I'm a student.", "yes", 0, "Giữ âm /s/ ở cuối, không đọc thành “dê”."),
      word("okay", "/ˌəʊˈkeɪ/", "được, ổn", "Is everything okay?", "o|kay", 1),
      word("excuse", "/ɪkˈskjuːz/", "xin lỗi (khi làm phiền ai)", "Excuse me, where is the bank?", "ex|cuse", 1),
      word("address", "/əˈdres/", "địa chỉ", "What's your address?", "ad|dress", 1, "Nhấn âm sau: ə-DRES."),
      word("email", "/ˈiː.meɪl/", "thư điện tử", "Please send me an email.", "e|mail", 0),
      word("surname", "/ˈsɜː.neɪm/", "họ", "My surname is Nguyen.", "sur|name", 0),
      word("birthday", "/ˈbɜːθ.deɪ/", "sinh nhật", "My birthday is in May.", "birth|day", 0, "Âm /θ/ ở giữa: lưỡi đặt giữa hai hàm răng, không đọc thành “bớt-đây”."),
      word("form", "/fɔːm/", "mẫu đơn", "Please write your name on the form.", "form", 0),
      word("mobile", "/ˈməʊ.baɪl/", "điện thoại di động", "What's your mobile number?", "mo|bile", 0),
      word("photo", "/ˈfəʊ.təʊ/", "ảnh", "This is a photo of my family.", "pho|to", 0),
      word("man", "/mæn/", "người đàn ông", "That man is my teacher.", "man", 0),
      word("woman", "/ˈwʊm.ən/", "người phụ nữ", "The woman in the red dress is my aunt.", "wom|an", 0, "Đọc /ˈwʊm.ən/ (“wum-ần”), không đọc “wô-man”."),
      word("girl", "/ɡɜːl/", "cô gái, bé gái", "She is a happy girl.", "girl", 0),
      word("child", "/tʃaɪld/", "đứa trẻ", "They have one child.", "child", 0),
      word("baby", "/ˈbeɪ.bi/", "em bé", "The baby is sleeping.", "ba|by", 0),
      word("person", "/ˈpɜː.sən/", "người", "She is a very kind person.", "per|son", 0),
      word("people", "/ˈpiː.pəl/", "mọi người, người (số nhiều)", "There are five people in my family.", "peo|ple", 0),
      word("adult", "/ˈæd.ʌlt/", "người lớn", "The ticket is ten dollars for an adult.", "ad|ult", 0),
      word("home", "/həʊm/", "nhà (nơi mình sống)", "I go home at five o'clock.", "home", 0),
      word("letter", "/ˈlet.ə/", "lá thư", "I write a letter to my grandma.", "let|ter", 0),
      word("life", "/laɪf/", "cuộc sống", "My life in Hanoi is very busy.", "life", 0),
      word("waiter", "/ˈweɪ.tə/", "người phục vụ bàn", "The waiter brings our food.", "wait|er", 0),
      word("farmer", "/ˈfɑː.mə/", "nông dân", "My grandfather is a farmer.", "farm|er", 0),
      word("singer", "/ˈsɪŋ.ə/", "ca sĩ", "She is a famous singer.", "sing|er", 0),
      word("actor", "/ˈæk.tə/", "diễn viên", "My cousin is an actor.", "ac|tor", 0),
      word("player", "/ˈpleɪ.ə/", "cầu thủ, người chơi", "He is a football player.", "play|er", 0),
      word("dancer", "/ˈdɑːn.sə/", "vũ công", "My sister is a good dancer.", "dan|cer", 0),
      word("pilot", "/ˈpaɪ.lət/", "phi công", "The pilot flies the plane.", "pi|lot", 0),
      word("company", "/ˈkʌm.pə.ni/", "công ty", "My dad works for a big company.", "com|pa|ny", 0),
    ],
  },
  {
    id: "gia-dinh",
    title: "Gia đình & vật nuôi",
    words: [
      word("mum", "/mʌm/", "mẹ (thân mật)", "My mum makes breakfast every day.", "mum", 0),
      word("dad", "/dæd/", "bố (thân mật)", "My dad drives to work.", "dad", 0),
      word("parent", "/ˈpeə.rənt/", "bố hoặc mẹ", "My parents live in Da Nang.", "par|ent", 0),
      word("son", "/sʌn/", "con trai", "Their son is ten years old.", "son", 0),
      word("daughter", "/ˈdɔː.tə/", "con gái", "They have two daughters.", "daugh|ter", 0, "“gh” câm: đọc /ˈdɔː.tə/."),
      word("husband", "/ˈhʌz.bənd/", "chồng", "Her husband is a doctor.", "hus|band", 0),
      word("wife", "/waɪf/", "vợ", "His wife is from Hue.", "wife", 0),
      word("grandmother", "/ˈɡræn.mʌð.ə/", "bà", "My grandmother is eighty years old.", "grand|moth|er", 0),
      word("grandfather", "/ˈɡræn.fɑː.ðə/", "ông", "My grandfather likes tea.", "grand|fa|ther", 0),
      word("grandparent", "/ˈɡræn.peə.rənt/", "ông hoặc bà", "My grandparents live in the countryside.", "grand|par|ent", 0),
      word("grandma", "/ˈɡræn.mɑː/", "bà (thân mật)", "Grandma tells us stories.", "grand|ma", 0),
      word("grandpa", "/ˈɡræn.pɑː/", "ông (thân mật)", "Grandpa has a small garden.", "grand|pa", 0),
      word("uncle", "/ˈʌŋ.kəl/", "chú, bác, cậu", "My uncle is a farmer.", "un|cle", 0),
      word("aunt", "/ɑːnt/", "cô, dì, bác gái", "My aunt lives in Ho Chi Minh City.", "aunt", 0),
      word("cousin", "/ˈkʌz.ən/", "anh chị em họ", "My cousin is the same age as me.", "cous|in", 0, "Đọc /ˈkʌz.ən/ (“cá-dần”), không đọc theo chữ “cou-sin”."),
      word("boyfriend", "/ˈbɔɪ.frend/", "bạn trai", "Her boyfriend is very kind.", "boy|friend", 0),
      word("girlfriend", "/ˈɡɜːl.frend/", "bạn gái", "His girlfriend is a nurse.", "girl|friend", 0),
      word("pet", "/pet/", "thú cưng", "Do you have a pet?", "pet", 0),
      word("cat", "/kæt/", "con mèo", "Our cat sleeps on the sofa.", "cat", 0),
      word("animal", "/ˈæn.ɪ.məl/", "con vật", "What is your favourite animal?", "an|i|mal", 0),
      word("horse", "/hɔːs/", "con ngựa", "The horse is very big.", "horse", 0),
      word("cow", "/kaʊ/", "con bò", "There are three cows on the farm.", "cow", 0),
      word("rabbit", "/ˈræb.ɪt/", "con thỏ", "My brother has a white rabbit.", "rab|bit", 0),
      word("mouse", "/maʊs/", "con chuột", "The cat is looking at a mouse.", "mouse", 0),
      word("pig", "/pɪɡ/", "con lợn", "The pig is eating.", "pig", 0),
      word("duck", "/dʌk/", "con vịt", "There is a duck on the river.", "duck", 0),
      word("love", "/lʌv/", "yêu, rất thích", "I love my family.", "love", 0),
    ],
  },
  {
    id: "quoc-gia-quoc-tich",
    title: "Quốc gia & quốc tịch",
    words: [
      word("England", "/ˈɪŋ.ɡlənd/", "nước Anh", "London is in England.", "Eng|land", 0, "Chữ E đọc /ɪ/: “ING-glần”, không đọc “en-glần”."),
      word("English", "/ˈɪŋ.ɡlɪʃ/", "tiếng Anh; thuộc nước Anh", "I study English every day.", "Eng|lish", 0, "Chữ E đọc /ɪ/ và kết thúc bằng /ʃ/: “ING-glish”."),
      word("Britain", "/ˈbrɪt.ən/", "nước Anh (Vương quốc Anh)", "It often rains in Britain.", "Brit|ain", 0),
      word("British", "/ˈbrɪt.ɪʃ/", "thuộc nước Anh, người Anh", "My teacher is British.", "Brit|ish", 0),
      word("America", "/əˈmer.ɪ.kə/", "nước Mỹ", "My uncle lives in America.", "A|mer|i|ca", 1),
      word("American", "/əˈmer.ɪ.kən/", "người Mỹ, thuộc nước Mỹ", "She is American.", "A|mer|i|can", 1),
      word("Australia", "/ɒsˈtreɪ.li.ə/", "nước Úc", "Australia is a very big country.", "Aus|tra|li|a", 1),
      word("Australian", "/ɒsˈtreɪ.li.ən/", "người Úc, thuộc nước Úc", "Our new friend is Australian.", "Aus|tra|li|an", 1),
      word("Canada", "/ˈkæn.ə.də/", "nước Canada", "It is very cold in Canada in winter.", "Can|a|da", 0),
      word("Canadian", "/kəˈneɪ.di.ən/", "người Canada", "He is Canadian, from Toronto.", "Ca|na|di|an", 1),
      word("China", "/ˈtʃaɪ.nə/", "Trung Quốc", "China is next to Vietnam.", "Chi|na", 0),
      word("Chinese", "/tʃaɪˈniːz/", "tiếng Trung; người Trung Quốc", "She speaks Chinese.", "Chi|nese", 1),
      word("France", "/frɑːns/", "nước Pháp", "Paris is in France.", "France", 0),
      word("French", "/frentʃ/", "tiếng Pháp; người Pháp; thuộc nước Pháp", "I like French bread.", "French", 0),
      word("Germany", "/ˈdʒɜː.mə.ni/", "nước Đức", "My brother works in Germany.", "Ger|ma|ny", 0),
      word("German", "/ˈdʒɜː.mən/", "tiếng Đức; người Đức; thuộc nước Đức", "Is your car German?", "Ger|man", 0),
      word("Italy", "/ˈɪt.əl.i/", "nước Ý", "Italy has very good food.", "It|a|ly", 0),
      word("Italian", "/ɪˈtæl.jən/", "tiếng Ý; người Ý; thuộc nước Ý", "We eat at an Italian restaurant.", "I|tal|ian", 1, "Nhấn âm thứ hai: i-TAL-jần, khác với Italy (IT-ə-li)."),
      word("Spain", "/speɪn/", "Tây Ban Nha", "Spain is hot in summer.", "Spain", 0),
      word("Spanish", "/ˈspæn.ɪʃ/", "tiếng Tây Ban Nha", "She is learning Spanish.", "Span|ish", 0),
      word("Korea", "/kəˈriː.ə/", "Hàn Quốc", "Many tourists go to Korea.", "Ko|re|a", 1),
      word("Korean", "/kəˈriː.ən/", "tiếng Hàn; người Hàn; thuộc Hàn Quốc", "I like Korean food.", "Ko|re|an", 1),
      word("Japan", "/dʒəˈpæn/", "Nhật Bản", "My cousin lives in Japan.", "Ja|pan", 1),
      word("Thailand", "/ˈtaɪ.lænd/", "Thái Lan", "We often go to Thailand on holiday.", "Thai|land", 0, "“Th” ở đây đọc /t/, không phải /θ/."),
      word("Thai", "/taɪ/", "tiếng Thái; người Thái; thuộc Thái Lan", "Thai food is spicy.", "Thai", 0, "Đọc /taɪ/ như “tai”."),
      word("Vietnam", "/ˌvjetˈnæm/", "Việt Nam", "I am from Vietnam.", "Viet|nam", 1),
      word("India", "/ˈɪn.di.ə/", "Ấn Độ", "India is a very big country.", "In|di|a", 0),
      word("Indian", "/ˈɪn.di.ən/", "người Ấn Độ; thuộc Ấn Độ", "My friend cooks Indian food.", "In|di|an", 0),
      word("Mexico", "/ˈmek.sɪ.kəʊ/", "Mê-hi-cô", "Mexico is in North America.", "Mex|i|co", 0),
      word("Mexican", "/ˈmek.sɪ.kən/", "người Mê-hi-cô", "He is Mexican.", "Mex|i|can", 0),
      word("Brazil", "/brəˈzɪl/", "Bra-xin", "Brazil is famous for football.", "Bra|zil", 1),
      word("Brazilian", "/brəˈzɪl.jən/", "người Bra-xin", "Our coach is Brazilian.", "Bra|zil|ian", 1),
      word("Russia", "/ˈrʌʃ.ə/", "nước Nga", "Russia is very cold in winter.", "Rus|sia", 0),
      word("Russian", "/ˈrʌʃ.ən/", "tiếng Nga; người Nga", "Can you speak Russian?", "Rus|sian", 0),
      word("world", "/wɜːld/", "thế giới", "English is useful all over the world.", "world", 0, "Giữ cả /l/ và /d/ ở cuối: /wɜːld/."),
    ],
  },
  {
    id: "do-an-do-uong",
    title: "Đồ ăn & đồ uống",
    words: [
      word("food", "/fuːd/", "đồ ăn, thức ăn", "I love Vietnamese food.", "food", 0, "Giữ âm /d/ ở cuối, không đọc thành “phu”."),
      word("drink", "/drɪŋk/", "uống; đồ uống", "I drink tea in the morning.", "drink", 0),
      word("eat", "/iːt/", "ăn", "We eat rice every day.", "eat", 0),
      word("meal", "/miːl/", "bữa ăn", "Dinner is my favourite meal.", "meal", 0),
      word("hungry", "/ˈhʌŋ.ɡri/", "đói", "I'm hungry. Let's eat!", "hun|gry", 0),
      word("thirsty", "/ˈθɜː.sti/", "khát", "I'm thirsty. Can I have some water?", "thir|sty", 0, "Âm /θ/ ở đầu: lưỡi đặt giữa hai hàm răng."),
      word("apple", "/ˈæp.əl/", "quả táo", "I eat an apple every day.", "ap|ple", 0),
      word("fruit", "/fruːt/", "trái cây", "Do you like fruit?", "fruit", 0),
      word("vegetable", "/ˈvedʒ.tə.bəl/", "rau củ", "We eat a lot of vegetables.", "veg|ta|ble", 0, "Chỉ có 3 âm tiết: VEJ-tə-bəl."),
      word("potato", "/pəˈteɪ.təʊ/", "khoai tây", "I'd like chicken and potatoes, please.", "po|ta|to", 1),
      word("tomato", "/təˈmɑː.təʊ/", "cà chua", "There is a tomato in the salad.", "to|ma|to", 1),
      word("carrot", "/ˈkær.ət/", "cà rốt", "Rabbits like carrots.", "car|rot", 0),
      word("meat", "/miːt/", "thịt", "My brother doesn't eat meat.", "meat", 0),
      word("bean", "/biːn/", "hạt đậu, đậu", "I like green beans with rice.", "bean", 0),
      word("fish", "/fɪʃ/", "cá", "We have fish for dinner.", "fish", 0, "Kết thúc bằng /ʃ/ (“sh”), không đọc thành “phít”."),
      word("cheese", "/tʃiːz/", "phô mai", "I'd like a cheese sandwich.", "cheese", 0),
      word("butter", "/ˈbʌt.ə/", "bơ (làm từ sữa)", "She puts butter on her bread.", "but|ter", 0),
      word("soup", "/suːp/", "súp, canh", "This soup is very hot.", "soup", 0),
      word("salad", "/ˈsæl.əd/", "món rau trộn, xa lát", "I have a salad for lunch.", "sal|ad", 0),
      word("pizza", "/ˈpiːt.sə/", "bánh pizza", "Let's order a pizza tonight.", "piz|za", 0),
      word("pasta", "/ˈpæs.tə/", "mì Ý", "The children love pasta.", "pas|ta", 0),
      word("sandwich", "/ˈsæn.wɪdʒ/", "bánh kẹp", "I make a sandwich for lunch.", "sand|wich", 0),
      word("hamburger", "/ˈhæmˌbɜː.ɡə/", "bánh hamburger", "He eats a hamburger and chips.", "ham|bur|ger", 0),
      word("cake", "/keɪk/", "bánh ngọt", "We have a cake for her birthday.", "cake", 0),
      word("biscuit", "/ˈbɪs.kɪt/", "bánh quy", "Would you like a biscuit with your tea?", "bis|cuit", 0, "Đọc /ˈbɪs.kɪt/, chữ “u” câm."),
      word("chocolate", "/ˈtʃɒk.lət/", "sô-cô-la", "I love chocolate.", "choc|late", 0, "Chỉ 2 âm tiết: CHOK-lət."),
      word("tea", "/tiː/", "trà", "My grandfather drinks green tea.", "tea", 0),
      word("juice", "/dʒuːs/", "nước ép", "Can I have an orange juice, please?", "juice", 0),
      word("beer", "/bɪə/", "bia", "My dad has a beer after work.", "beer", 0),
      word("wine", "/waɪn/", "rượu vang", "They drink red wine with dinner.", "wine", 0),
      word("cup", "/kʌp/", "cái tách, cốc", "Would you like a cup of tea?", "cup", 0),
      word("glass", "/ɡlɑːs/", "cái cốc (thủy tinh)", "Can I have a glass of water?", "glass", 0),
      word("plate", "/pleɪt/", "cái đĩa", "Put the cake on a plate.", "plate", 0),
      word("restaurant", "/ˈres.tər.ɒnt/", "nhà hàng", "There is a good restaurant near my house.", "res|tau|rant", 0, "Nhấn âm đầu: RES-tə-ront."),
      word("cafe", "/ˈkæf.eɪ/", "quán cà phê", "Let's meet at the cafe.", "caf|e", 0),
    ],
  },
  {
    id: "thanh-pho-cua-hang",
    title: "Thành phố, cửa hàng & vị trí",
    words: [
      word("city", "/ˈsɪt.i/", "thành phố", "Hanoi is a big city.", "cit|y", 0),
      word("town", "/taʊn/", "thị trấn", "I live in a small town.", "town", 0),
      word("place", "/pleɪs/", "nơi, chỗ", "This is my favourite place in the city.", "place", 0),
      word("shop", "/ʃɒp/", "cửa hàng", "The shop opens at eight.", "shop", 0),
      word("bank", "/bæŋk/", "ngân hàng", "The bank is next to the post office.", "bank", 0),
      word("hospital", "/ˈhɒs.pɪ.təl/", "bệnh viện", "My mum works in a hospital.", "hos|pi|tal", 0),
      word("office", "/ˈɒf.ɪs/", "văn phòng", "My office is on the fifth floor.", "of|fice", 0),
      word("theatre", "/ˈθɪə.tə/", "nhà hát", "We go to the theatre on Saturday.", "thea|tre", 0, "Âm /θ/ ở đầu, không đọc thành “tê-a-tơ”."),
      word("building", "/ˈbɪl.dɪŋ/", "tòa nhà", "That building is very tall.", "build|ing", 0),
      word("centre", "/ˈsen.tə/", "trung tâm", "The shops are in the city centre.", "cen|tre", 0),
      word("farm", "/fɑːm/", "nông trại", "My grandparents have a farm.", "farm", 0),
      word("bookshop", "/ˈbʊk.ʃɒp/", "hiệu sách", "I buy my books at the bookshop.", "book|shop", 0),
      word("buy", "/baɪ/", "mua", "I want to buy a new bag.", "buy", 0),
      word("sell", "/sel/", "bán", "They sell fruit at the market.", "sell", 0),
      word("pay", "/peɪ/", "trả tiền", "Can I pay by card?", "pay", 0),
      word("cost", "/kɒst/", "có giá", "How much does this shirt cost?", "cost", 0, "Giữ cụm /st/ ở cuối."),
      word("shopping", "/ˈʃɒp.ɪŋ/", "việc mua sắm", "I go shopping on Sundays.", "shop|ping", 0),
      word("card", "/kɑːd/", "thẻ", "I pay with my bank card.", "card", 0),
      word("dollar", "/ˈdɒl.ə/", "đô la", "It costs ten dollars.", "dol|lar", 0),
      word("pound", "/paʊnd/", "bảng Anh", "The ticket is five pounds.", "pound", 0),
      word("present", "/ˈprez.ənt/", "món quà", "I buy a present for my mum.", "pres|ent", 0),
      word("open", "/ˈəʊ.pən/", "mở cửa; mở", "The bank is open from eight to five.", "o|pen", 0),
      word("far", "/fɑː/", "xa", "Is the station far from here?", "far", 0),
      word("right", "/raɪt/", "bên phải", "Turn right at the bank.", "right", 0),
      word("behind", "/bɪˈhaɪnd/", "phía sau", "The car park is behind the hotel.", "be|hind", 1),
      word("under", "/ˈʌn.də/", "ở dưới", "The cat is under the table.", "un|der", 0),
      word("inside", "/ɪnˈsaɪd/", "bên trong", "It's cold. Let's go inside.", "in|side", 1),
      word("outside", "/ˌaʊtˈsaɪd/", "bên ngoài", "The children are playing outside.", "out|side", 1),
    ],
  },
  {
    id: "di-lai-dich-vu",
    title: "Đi lại & phương tiện",
    words: [
      word("car", "/kɑː/", "xe ô tô", "My dad goes to work by car.", "car", 0),
      word("bus", "/bʌs/", "xe buýt", "I take the bus to school.", "bus", 0),
      word("train", "/treɪn/", "tàu hỏa", "The train leaves at nine.", "train", 0),
      word("plane", "/pleɪn/", "máy bay", "We go to Da Nang by plane.", "plane", 0),
      word("taxi", "/ˈtæk.si/", "xe taxi", "Let's get a taxi to the airport.", "tax|i", 0),
      word("bike", "/baɪk/", "xe đạp", "I ride my bike to school.", "bike", 0),
      word("bicycle", "/ˈbaɪ.sɪ.kəl/", "xe đạp", "She has a new bicycle.", "bi|cy|cle", 0),
      word("boat", "/bəʊt/", "thuyền", "We go to the island by boat.", "boat", 0),
      word("motorbike", "/ˈməʊ.tə.baɪk/", "xe máy", "Many people in Vietnam ride motorbikes.", "mo|tor|bike", 0),
      word("fly", "/flaɪ/", "bay, đi máy bay", "We fly to Bangkok tomorrow.", "fly", 0),
      word("go", "/ɡəʊ/", "đi", "I go to work by bus.", "go", 0),
      word("come", "/kʌm/", "đến", "Can you come to my party?", "come", 0),
      word("get", "/ɡet/", "đến (nơi nào đó)", "How do I get to the station?", "get", 0),
      word("take", "/teɪk/", "đi (xe), bắt (xe)", "We take a taxi to the hotel.", "take", 0),
      word("bring", "/brɪŋ/", "mang theo", "Please bring your passport.", "bring", 0),
      word("stay", "/steɪ/", "ở lại, lưu trú", "We stay in a small hotel.", "stay", 0),
      word("tourist", "/ˈtʊə.rɪst/", "khách du lịch", "Many tourists visit Hoi An.", "tour|ist", 0),
      word("way", "/weɪ/", "đường đi, lối", "Is this the way to the beach?", "way", 0),
      word("stop", "/stɒp/", "điểm dừng; dừng lại", "The bus stop is near my house.", "stop", 0),
      word("camera", "/ˈkæm.rə/", "máy ảnh", "Don't forget your camera!", "cam|era", 0),
      word("suitcase", "/ˈsuːt.keɪs/", "va li", "My suitcase is very heavy.", "suit|case", 0),
      word("map", "/mæp/", "bản đồ", "Can you show me on the map?", "map", 0),
      word("underground", "/ˈʌn.də.ɡraʊnd/", "tàu điện ngầm", "We take the underground in London.", "un|der|ground", 0),
      word("seat", "/siːt/", "chỗ ngồi", "Is this seat free?", "seat", 0),
      word("road", "/rəʊd/", "con đường", "Be careful when you cross the road.", "road", 0),
    ],
  },
  {
    id: "dong-tu-co-ban",
    title: "Động từ cơ bản",
    words: [
      word("be", "/biː/", "là, thì, ở", "I want to be a doctor.", "be", 0),
      word("have", "/hæv/", "có", "I have two brothers.", "have", 0),
      word("do", "/duː/", "làm", "I do my homework after dinner.", "do", 0),
      word("make", "/meɪk/", "làm ra, nấu", "My mum makes great cakes.", "make", 0),
      word("like", "/laɪk/", "thích", "I like green tea.", "like", 0),
      word("need", "/niːd/", "cần", "I need a new phone.", "need", 0),
      word("know", "/nəʊ/", "biết", "I don't know his name.", "know", 0, "Chữ “k” câm: đọc /nəʊ/."),
      word("see", "/siː/", "nhìn thấy", "I can see the sea from my window.", "see", 0),
      word("look", "/lʊk/", "nhìn", "Look at this photo!", "look", 0),
      word("hear", "/hɪə/", "nghe thấy", "Can you hear me?", "hear", 0),
      word("say", "/seɪ/", "nói", "How do you say this in English?", "say", 0),
      word("tell", "/tel/", "kể, bảo", "Please tell me your name.", "tell", 0),
      word("ask", "/ɑːsk/", "hỏi", "Can I ask a question?", "ask", 0, "Giữ cụm /sk/ ở cuối."),
      word("answer", "/ˈɑːn.sə/", "trả lời", "Please answer the question.", "an|swer", 0, "Chữ “w” câm: đọc /ˈɑːn.sə/."),
      word("talk", "/tɔːk/", "nói chuyện", "I talk to my friends every day.", "talk", 0, "Chữ “l” câm: đọc /tɔːk/."),
      word("study", "/ˈstʌd.i/", "học", "She studies English at night.", "stud|y", 0),
      word("learn", "/lɜːn/", "học, học được", "I learn five new words every day.", "learn", 0),
      word("teach", "/tiːtʃ/", "dạy", "My aunt teaches maths.", "teach", 0),
      word("understand", "/ˌʌn.dəˈstænd/", "hiểu", "I don't understand this word.", "un|der|stand", 2),
      word("close", "/kləʊz/", "đóng", "Please close the door.", "close", 0, "Động từ đọc với /z/ ở cuối: /kləʊz/."),
      word("start", "/stɑːt/", "bắt đầu", "The lesson starts at seven.", "start", 0),
      word("begin", "/bɪˈɡɪn/", "bắt đầu", "The film begins at eight.", "be|gin", 1),
      word("give", "/ɡɪv/", "đưa, cho", "Can you give me that pen?", "give", 0),
      word("put", "/pʊt/", "đặt, để", "Put your bag on the chair.", "put", 0),
      word("sit", "/sɪt/", "ngồi", "Please sit here.", "sit", 0),
      word("stand", "/stænd/", "đứng", "Please stand up.", "stand", 0),
      word("wash", "/wɒʃ/", "rửa, giặt", "Wash your hands before lunch.", "wash", 0),
      word("clean", "/kliːn/", "lau dọn; sạch", "I clean my room on Saturday.", "clean", 0),
      word("help", "/help/", "giúp đỡ", "Can you help me, please?", "help", 0),
      word("use", "/juːz/", "dùng, sử dụng", "Can I use your phone?", "use", 0),
      word("try", "/traɪ/", "thử, cố gắng", "Try this cake. It's delicious!", "try", 0),
      word("find", "/faɪnd/", "tìm thấy", "I can't find my keys.", "find", 0),
      word("call", "/kɔːl/", "gọi điện", "I call my mum every evening.", "call", 0),
      word("text", "/tekst/", "nhắn tin", "Text me when you get home.", "text", 0),
      word("meet", "/miːt/", "gặp", "Nice to meet you.", "meet", 0),
      word("draw", "/drɔː/", "vẽ (bằng bút)", "My son likes to draw animals.", "draw", 0),
      word("paint", "/peɪnt/", "sơn, vẽ (bằng màu)", "We paint pictures in art class.", "paint", 0),
    ],
  },
  {
    id: "quan-ao-mau-sac",
    title: "Quần áo & màu sắc",
    words: [
      word("clothes", "/kləʊðz/", "quần áo", "I need some new clothes.", "clothes", 0, "Đọc /kləʊðz/, gần như một âm tiết; không đọc “clô-thét”."),
      word("T-shirt", "/ˈtiː.ʃɜːt/", "áo phông", "He is wearing a white T-shirt.", "T|shirt", 0),
      word("skirt", "/skɜːt/", "chân váy", "She has a long blue skirt.", "skirt", 0),
      word("jeans", "/dʒiːnz/", "quần bò", "I wear jeans at the weekend.", "jeans", 0),
      word("coat", "/kəʊt/", "áo khoác dài", "Wear your coat. It's cold.", "coat", 0),
      word("sweater", "/ˈswet.ə/", "áo len", "This sweater is very warm.", "sweat|er", 0),
      word("jumper", "/ˈdʒʌm.pə/", "áo len chui đầu", "My grandma makes jumpers for me.", "jum|per", 0),
      word("hat", "/hæt/", "cái mũ", "Wear a hat in the sun.", "hat", 0),
      word("cap", "/kæp/", "mũ lưỡi trai", "He always wears a red cap.", "cap", 0),
      word("sock", "/sɒk/", "chiếc tất", "Where are my socks?", "sock", 0),
      word("boot", "/buːt/", "chiếc ủng, bốt", "I wear boots in the rain.", "boot", 0),
      word("shorts", "/ʃɔːts/", "quần soóc", "It's hot, so I'm wearing shorts.", "shorts", 0),
      word("scarf", "/skɑːf/", "khăn quàng cổ", "She has a pink scarf.", "scarf", 0),
      word("glove", "/ɡlʌv/", "găng tay", "Put on your gloves. It's cold.", "glove", 0),
      word("belt", "/belt/", "thắt lưng", "He has a black belt.", "belt", 0),
      word("pocket", "/ˈpɒk.ɪt/", "túi (quần áo)", "My phone is in my pocket.", "pock|et", 0),
      word("wear", "/weə/", "mặc, đội, đeo", "I wear a uniform at school.", "wear", 0),
      word("red", "/red/", "màu đỏ", "She has a red bag.", "red", 0),
      word("blue", "/bluː/", "màu xanh dương", "The sky is blue today.", "blue", 0),
      word("green", "/ɡriːn/", "màu xanh lá", "I love green tea.", "green", 0),
      word("white", "/waɪt/", "màu trắng", "He is wearing a white shirt.", "white", 0),
      word("brown", "/braʊn/", "màu nâu", "My dog has brown eyes.", "brown", 0),
      word("grey", "/ɡreɪ/", "màu xám", "The sky is grey today.", "grey", 0),
      word("pink", "/pɪŋk/", "màu hồng", "My daughter loves pink.", "pink", 0),
      word("purple", "/ˈpɜː.pəl/", "màu tím", "Purple is my favourite colour.", "pur|ple", 0),
      word("orange", "/ˈɒr.ɪndʒ/", "màu cam; quả cam", "I'd like an orange juice.", "or|ange", 0, "Đọc /ˈɒr.ɪndʒ/, 2 âm tiết, cuối là /dʒ/."),
      word("dark", "/dɑːk/", "tối, sẫm (màu)", "He is wearing a dark blue coat.", "dark", 0),
    ],
  },
  {
    id: "so-dem-kich-thuoc",
    title: "Số đếm & kích thước",
    words: [
      word("zero", "/ˈzɪə.rəʊ/", "số không", "My phone number starts with zero.", "ze|ro", 0),
      word("one", "/wʌn/", "một", "I have one sister.", "one", 0),
      word("two", "/tuː/", "hai", "We have two cats.", "two", 0),
      word("three", "/θriː/", "ba", "There are three people in my family.", "three", 0, "Âm /θ/ ở đầu: lưỡi giữa hai hàm răng, không đọc thành “tri”."),
      word("four", "/fɔː/", "bốn", "I have four cousins.", "four", 0),
      word("five", "/faɪv/", "năm", "I get up at five.", "five", 0, "Kết thúc bằng /v/: chạm răng trên vào môi dưới."),
      word("six", "/sɪks/", "sáu", "I finish work at six.", "six", 0),
      word("seven", "/ˈsev.ən/", "bảy", "There are seven days in a week.", "sev|en", 0),
      word("eight", "/eɪt/", "tám", "The shop opens at eight.", "eight", 0),
      word("nine", "/naɪn/", "chín", "My son is nine years old.", "nine", 0),
      word("ten", "/ten/", "mười", "I have ten English books.", "ten", 0),
      word("eleven", "/ɪˈlev.ən/", "mười một", "The film starts at eleven.", "e|lev|en", 1),
      word("fourteen", "/ˌfɔːˈtiːn/", "mười bốn", "My cousin is fourteen.", "four|teen", 1, "Nhấn vào -TEEN (four-TEEN) để phân biệt với forty (FOR-ty)."),
      word("sixteen", "/ˌsɪkˈstiːn/", "mười sáu", "There are sixteen students in my class.", "six|teen", 1),
      word("seventeen", "/ˌsev.ənˈtiːn/", "mười bảy", "She is seventeen years old.", "sev|en|teen", 2),
      word("eighteen", "/ˌeɪˈtiːn/", "mười tám", "He is eighteen today.", "eigh|teen", 1),
      word("nineteen", "/ˌnaɪnˈtiːn/", "mười chín", "The book costs nineteen dollars.", "nine|teen", 1),
      word("twenty", "/ˈtwen.ti/", "hai mươi", "I'm twenty years old.", "twen|ty", 0),
      word("forty", "/ˈfɔː.ti/", "bốn mươi", "My dad is forty.", "for|ty", 0, "Nhấn âm đầu: FOR-ty, khác fourteen (four-TEEN)."),
      word("fifty", "/ˈfɪf.ti/", "năm mươi", "The bus takes fifty minutes.", "fif|ty", 0),
      word("sixty", "/ˈsɪk.sti/", "sáu mươi", "My grandma is sixty.", "six|ty", 0),
      word("seventy", "/ˈsev.ən.ti/", "bảy mươi", "There are seventy rooms in the hotel.", "sev|en|ty", 0),
      word("eighty", "/ˈeɪ.ti/", "tám mươi", "My grandfather is eighty.", "eigh|ty", 0),
      word("ninety", "/ˈnaɪn.ti/", "chín mươi", "The ticket is ninety thousand dong.", "nine|ty", 0),
      word("thousand", "/ˈθaʊ.zənd/", "nghìn", "It costs one thousand dollars.", "thou|sand", 0, "Âm /θ/ ở đầu và /z/ ở giữa."),
      word("first", "/fɜːst/", "thứ nhất, đầu tiên", "This is my first English lesson.", "first", 0),
      word("second", "/ˈsek.ənd/", "thứ hai", "My office is on the second floor.", "sec|ond", 0),
      word("third", "/θɜːd/", "thứ ba", "He lives on the third floor.", "third", 0),
      word("big", "/bɪɡ/", "to, lớn", "They live in a big house.", "big", 0),
      word("small", "/smɔːl/", "nhỏ", "My room is small.", "small", 0),
      word("long", "/lɒŋ/", "dài", "She has long black hair.", "long", 0),
      word("short", "/ʃɔːt/", "ngắn; thấp", "This film is very short.", "short", 0),
      word("large", "/lɑːdʒ/", "rộng, lớn", "Can I have a large coffee, please?", "large", 0),
      word("little", "/ˈlɪt.əl/", "nhỏ bé", "They have a little dog.", "lit|tle", 0),
      word("high", "/haɪ/", "cao", "The mountain is very high.", "high", 0, "“gh” câm: đọc /haɪ/."),
    ],
  },
  {
    id: "nha-cua-do-vat",
    title: "Nhà cửa & đồ vật",
    words: [
      word("flat", "/flæt/", "căn hộ", "We live in a flat in the city centre.", "flat", 0),
      word("apartment", "/əˈpɑːt.mənt/", "căn hộ", "Their apartment has two bedrooms.", "a|part|ment", 1),
      word("room", "/ruːm/", "căn phòng", "My room is small but nice.", "room", 0),
      word("garden", "/ˈɡɑː.dən/", "khu vườn", "There are flowers in our garden.", "gar|den", 0),
      word("door", "/dɔː/", "cửa ra vào", "Please close the door.", "door", 0),
      word("floor", "/flɔː/", "sàn nhà; tầng", "The cat is sleeping on the floor.", "floor", 0),
      word("wall", "/wɔːl/", "bức tường", "There is a clock on the wall.", "wall", 0),
      word("stairs", "/steəz/", "cầu thang", "The bathroom is up the stairs.", "stairs", 0),
      word("toilet", "/ˈtɔɪ.lət/", "nhà vệ sinh", "Where is the toilet, please?", "toi|let", 0),
      word("shower", "/ˈʃaʊ.ə/", "vòi hoa sen; tắm vòi sen", "I have a shower every morning.", "show|er", 0),
      word("bath", "/bɑːθ/", "bồn tắm; việc tắm", "The children have a bath at night.", "bath", 0, "Kết thúc bằng /θ/, không đọc thành “bát”."),
      word("lamp", "/læmp/", "đèn bàn", "There is a lamp on my desk.", "lamp", 0),
      word("light", "/laɪt/", "đèn; ánh sáng", "Please turn off the light.", "light", 0),
      word("clock", "/klɒk/", "đồng hồ (treo tường, để bàn)", "The clock in the kitchen is slow.", "clock", 0),
      word("television", "/ˈtel.ɪ.vɪʒ.ən/", "ti vi", "We watch television after dinner.", "tel|e|vi|sion", 0),
      word("computer", "/kəmˈpjuː.tə/", "máy tính", "I use a computer at work.", "com|pu|ter", 1),
      word("laptop", "/ˈlæp.tɒp/", "máy tính xách tay", "My laptop is in my bag.", "lap|top", 0),
      word("internet", "/ˈɪn.tə.net/", "mạng internet", "I read the news on the internet.", "in|ter|net", 0),
      word("website", "/ˈweb.saɪt/", "trang web", "This website has free English lessons.", "web|site", 0),
      word("radio", "/ˈreɪ.di.əʊ/", "đài, radio", "My dad listens to the radio in the car.", "ra|di|o", 0),
      word("fridge", "/frɪdʒ/", "tủ lạnh", "The milk is in the fridge.", "fridge", 0),
      word("cupboard", "/ˈkʌb.əd/", "tủ (chạn, tủ bếp)", "The cups are in the cupboard.", "cup|board", 0, "Chữ “p” câm: đọc /ˈkʌb.əd/ (“cá-bợd”)."),
      word("picture", "/ˈpɪk.tʃə/", "bức tranh, bức ảnh", "There is a picture of my family on the wall.", "pic|ture", 0),
      word("film", "/fɪlm/", "bộ phim", "We watch a film at home on Friday.", "film", 0, "Giữ cả /l/ và /m/ ở cuối: /fɪlm/, không đọc thành “phim”."),
      word("thing", "/θɪŋ/", "đồ vật, thứ", "What is that thing on the table?", "thing", 0, "Âm /θ/ ở đầu: lưỡi giữa hai hàm răng."),
      word("toy", "/tɔɪ/", "đồ chơi", "The children have a lot of toys.", "toy", 0),
      word("ball", "/bɔːl/", "quả bóng", "The boys are playing with a ball.", "ball", 0),
      word("game", "/ɡeɪm/", "trò chơi", "Let's play a game!", "game", 0),
      word("pen", "/pen/", "bút mực", "Can I borrow your pen?", "pen", 0),
      word("pencil", "/ˈpen.səl/", "bút chì", "Write your name with a pencil.", "pen|cil", 0),
      word("paper", "/ˈpeɪ.pə/", "giấy", "I need a piece of paper.", "pa|per", 0),
      word("notebook", "/ˈnəʊt.bʊk/", "quyển vở, sổ tay", "Write the new words in your notebook.", "note|book", 0),
    ],
  },
  {
    id: "tinh-tu",
    title: "Tính từ: miêu tả & cảm xúc",
    words: [
      word("good", "/ɡʊd/", "tốt, giỏi", "She is a good student.", "good", 0),
      word("great", "/ɡreɪt/", "tuyệt vời", "This is a great film!", "great", 0),
      word("happy", "/ˈhæp.i/", "vui vẻ, hạnh phúc", "I'm very happy today.", "hap|py", 0),
      word("sad", "/sæd/", "buồn", "Why are you sad?", "sad", 0),
      word("angry", "/ˈæŋ.ɡri/", "tức giận", "My dad is angry with me.", "an|gry", 0),
      word("beautiful", "/ˈbjuː.tɪ.fəl/", "đẹp", "Ha Long Bay is beautiful.", "beau|ti|ful", 0),
      word("young", "/jʌŋ/", "trẻ", "My parents are young.", "young", 0),
      word("new", "/njuː/", "mới", "I have a new phone.", "new", 0),
      word("fast", "/fɑːst/", "nhanh", "The train is very fast.", "fast", 0),
      word("slow", "/sləʊ/", "chậm", "The bus is slow today.", "slow", 0),
      word("easy", "/ˈiː.zi/", "dễ", "This exercise is easy.", "eas|y", 0),
      word("difficult", "/ˈdɪf.ɪ.kəlt/", "khó", "English grammar is difficult for me.", "dif|fi|cult", 0),
      word("hard", "/hɑːd/", "khó; chăm chỉ", "The test is very hard.", "hard", 0),
      word("wrong", "/rɒŋ/", "sai", "Sorry, that's the wrong answer.", "wrong", 0, "Chữ “w” câm: đọc /rɒŋ/."),
      word("different", "/ˈdɪf.ər.ənt/", "khác nhau", "My brother and I are very different.", "dif|fer|ent", 0),
      word("same", "/seɪm/", "giống nhau", "We are in the same class.", "same", 0),
      word("favourite", "/ˈfeɪ.vər.ɪt/", "yêu thích nhất", "Blue is my favourite colour.", "fa|vour|ite", 0),
      word("interesting", "/ˈɪn.tres.tɪŋ/", "thú vị", "This book is very interesting.", "in|tres|ting", 0, "Thường đọc 3 âm tiết, nhấn đầu: IN-tres-ting."),
      word("boring", "/ˈbɔː.rɪŋ/", "nhàm chán", "The film is boring.", "bor|ing", 0),
      word("funny", "/ˈfʌn.i/", "buồn cười, hài hước", "My uncle is very funny.", "fun|ny", 0),
      word("friendly", "/ˈfrend.li/", "thân thiện", "The people here are very friendly.", "friend|ly", 0),
      word("quiet", "/ˈkwaɪ.ət/", "yên tĩnh, ít nói", "The library is very quiet.", "qui|et", 0, "2 âm tiết: KWAI-ət, khác quite /kwaɪt/."),
      word("lovely", "/ˈlʌv.li/", "đẹp, dễ thương, đáng yêu", "What a lovely dress!", "love|ly", 0),
      word("fine", "/faɪn/", "khỏe, ổn", "I'm fine, thank you.", "fine", 0),
      word("excited", "/ɪkˈsaɪ.tɪd/", "hào hứng", "The children are excited about the trip.", "ex|ci|ted", 1),
      word("interested", "/ˈɪn.tres.tɪd/", "quan tâm, thích thú", "I'm interested in music.", "in|tres|ted", 0),
      word("clever", "/ˈklev.ə/", "thông minh, khéo léo", "Your daughter is very clever.", "clev|er", 0),
      word("important", "/ɪmˈpɔː.tənt/", "quan trọng", "Family is very important to me.", "im|por|tant", 1),
      word("popular", "/ˈpɒp.jə.lə/", "được ưa chuộng", "Football is popular in Vietnam.", "pop|u|lar", 0),
      word("ready", "/ˈred.i/", "sẵn sàng", "Are you ready to go?", "read|y", 0),
      word("sure", "/ʃɔː/", "chắc chắn", "Are you sure?", "sure", 0),
      word("fun", "/fʌn/", "vui, niềm vui", "The party was a lot of fun.", "fun", 0),
      word("feel", "/fiːl/", "cảm thấy", "I feel happy today.", "feel", 0),
      word("bored", "/bɔːd/", "chán", "I'm bored. Let's go out.", "bored", 0),
      word("dirty", "/ˈdɜː.ti/", "bẩn", "Your shoes are dirty.", "dir|ty", 0),
      word("wonderful", "/ˈwʌn.də.fəl/", "tuyệt vời", "It was a wonderful day.", "won|der|ful", 0),
    ],
  },
  {
    id: "thoi-gian-thoi-quen",
    title: "Thời gian, thói quen & trường học",
    words: [
      word("day", "/deɪ/", "ngày", "I study English every day.", "day", 0),
      word("night", "/naɪt/", "đêm, buổi tối", "I go to bed at eleven at night.", "night", 0),
      word("evening", "/ˈiːv.nɪŋ/", "buổi tối", "We watch TV in the evening.", "eve|ning", 0, "Chỉ 2 âm tiết: EEV-ning."),
      word("afternoon", "/ˌɑːf.təˈnuːn/", "buổi chiều", "I play football in the afternoon.", "af|ter|noon", 2),
      word("today", "/təˈdeɪ/", "hôm nay", "Today is my birthday.", "to|day", 1),
      word("tonight", "/təˈnaɪt/", "tối nay", "What are you doing tonight?", "to|night", 1),
      word("hour", "/aʊə/", "giờ, tiếng đồng hồ", "I sleep eight hours a night.", "hour", 0, "Chữ “h” câm: đọc /aʊə/ như “our”."),
      word("date", "/deɪt/", "ngày tháng", "What's the date today?", "date", 0),
      word("year", "/jɪə/", "năm", "I'm twenty years old.", "year", 0),
      word("early", "/ˈɜː.li/", "sớm", "I get up early on weekdays.", "ear|ly", 0),
      word("late", "/leɪt/", "muộn", "Don't be late for class.", "late", 0),
      word("then", "/ðen/", "sau đó", "I have breakfast, then I go to work.", "then", 0, "Âm /ð/: lưỡi giữa hai hàm răng, rung dây thanh, không đọc thành “đen”."),
      word("after", "/ˈɑːf.tə/", "sau khi, sau", "I do my homework after dinner.", "af|ter", 0),
      word("before", "/bɪˈfɔː/", "trước khi, trước", "I brush my teeth before bed.", "be|fore", 1),
      word("every", "/ˈev.ri/", "mỗi, mọi", "I call my mum every Sunday.", "ev|ery", 0),
      word("wake", "/weɪk/", "thức dậy", "I wake up at six every morning.", "wake", 0),
      word("Tuesday", "/ˈtjuːz.deɪ/", "thứ Ba", "I have a guitar lesson on Tuesday.", "Tues|day", 0),
      word("Thursday", "/ˈθɜːz.deɪ/", "thứ Năm", "We have English on Thursday.", "Thurs|day", 0, "Âm /θ/ ở đầu, không đọc thành “tơ-đây”."),
      word("Friday", "/ˈfraɪ.deɪ/", "thứ Sáu", "On Friday we eat out.", "Fri|day", 0),
      word("Saturday", "/ˈsæt.ə.deɪ/", "thứ Bảy", "I clean the house on Saturday.", "Sat|ur|day", 0),
      word("Sunday", "/ˈsʌn.deɪ/", "Chủ nhật", "We visit my grandparents on Sunday.", "Sun|day", 0),
      word("January", "/ˈdʒæn.ju.ə.ri/", "tháng Một", "It's cold in January.", "Jan|u|ar|y", 0),
      word("February", "/ˈfeb.ru.ər.i/", "tháng Hai", "Tet is often in February.", "Feb|ru|ar|y", 0),
      word("March", "/mɑːtʃ/", "tháng Ba", "My birthday is in March.", "March", 0),
      word("April", "/ˈeɪ.prəl/", "tháng Tư", "We go on holiday in April.", "A|pril", 0),
      word("May", "/meɪ/", "tháng Năm", "The exam is in May.", "May", 0),
      word("June", "/dʒuːn/", "tháng Sáu", "School finishes in June.", "June", 0),
      word("July", "/dʒuˈlaɪ/", "tháng Bảy", "It's very hot in July.", "Ju|ly", 1, "Nhấn âm sau: ju-LAI."),
      word("August", "/ˈɔː.ɡəst/", "tháng Tám", "We go to the beach in August.", "Au|gust", 0),
      word("September", "/sepˈtem.bə/", "tháng Chín", "The new school year starts in September.", "Sep|tem|ber", 1),
      word("October", "/ɒkˈtəʊ.bə/", "tháng Mười", "My sister's birthday is in October.", "Oc|to|ber", 1),
      word("November", "/nəʊˈvem.bə/", "tháng Mười Một", "It often rains in November.", "No|vem|ber", 1),
      word("December", "/dɪˈsem.bə/", "tháng Mười Hai", "Christmas is in December.", "De|cem|ber", 1),
      word("school", "/skuːl/", "trường học", "I go to school by bike.", "school", 0),
      word("class", "/klɑːs/", "lớp học; tiết học", "There are twenty students in my class.", "class", 0),
      word("lesson", "/ˈles.ən/", "bài học, buổi học", "The English lesson starts at nine.", "les|son", 0),
      word("classroom", "/ˈklɑːs.ruːm/", "phòng học", "Our classroom is on the first floor.", "class|room", 0),
      word("test", "/test/", "bài kiểm tra", "We have a test on Friday.", "test", 0),
      word("maths", "/mæθs/", "môn toán", "Maths is my favourite subject.", "maths", 0),
      word("science", "/ˈsaɪ.əns/", "môn khoa học", "We do experiments in science.", "sci|ence", 0),
      word("history", "/ˈhɪs.tər.i/", "môn lịch sử", "I like history lessons.", "his|to|ry", 0),
      word("art", "/ɑːt/", "môn mỹ thuật", "We draw pictures in art.", "art", 0),
      word("sport", "/spɔːt/", "thể thao", "What sport do you play?", "sport", 0),
      word("subject", "/ˈsʌb.dʒekt/", "môn học", "What's your favourite subject?", "sub|ject", 0),
    ],
  },
  {
    id: "thoi-tiet-thien-nhien",
    title: "Thời tiết, mùa & thiên nhiên",
    words: [
      word("sun", "/sʌn/", "mặt trời", "The sun is very hot today.", "sun", 0),
      word("sunny", "/ˈsʌn.i/", "có nắng", "It's sunny and warm.", "sun|ny", 0),
      word("cloud", "/klaʊd/", "đám mây", "There are no clouds in the sky.", "cloud", 0),
      word("cloudy", "/ˈklaʊ.di/", "nhiều mây", "It's cloudy this morning.", "cloud|y", 0),
      word("plant", "/plɑːnt/", "cây (trồng), thực vật", "My mum has many plants in the garden.", "plant", 0),
      word("wind", "/wɪnd/", "gió", "The wind is very strong today.", "wind", 0),
      word("windy", "/ˈwɪn.di/", "có gió", "It's windy at the beach.", "wind|y", 0),
      word("snow", "/snəʊ/", "tuyết; có tuyết rơi", "It doesn't snow in Ho Chi Minh City.", "snow", 0),
      word("hot", "/hɒt/", "nóng", "It's very hot in summer.", "hot", 0),
      word("warm", "/wɔːm/", "ấm áp", "It's warm and sunny today.", "warm", 0),
      word("cool", "/kuːl/", "mát mẻ", "Da Lat is cool all year.", "cool", 0),
      word("sky", "/skaɪ/", "bầu trời", "The sky is blue.", "sky", 0),
      word("spring", "/sprɪŋ/", "mùa xuân", "Flowers grow in spring.", "spring", 0),
      word("summer", "/ˈsʌm.ə/", "mùa hè", "We go to the beach in summer.", "sum|mer", 0),
      word("autumn", "/ˈɔː.təm/", "mùa thu", "Hanoi is beautiful in autumn.", "au|tumn", 0, "Chữ “n” cuối câm: đọc /ˈɔː.təm/."),
      word("winter", "/ˈwɪn.tə/", "mùa đông", "It's cold in winter.", "win|ter", 0),
      word("wet", "/wet/", "ướt", "My shoes are wet.", "wet", 0),
      word("dry", "/draɪ/", "khô", "It's dry and sunny today.", "dry", 0),
      word("star", "/stɑː/", "ngôi sao", "I can see the stars tonight.", "star", 0),
      word("moon", "/muːn/", "mặt trăng", "The moon is very bright tonight.", "moon", 0),
      word("degree", "/dɪˈɡriː/", "độ (nhiệt độ)", "It's thirty-five degrees today.", "de|gree", 1),
      word("tree", "/triː/", "cây", "There is a big tree in the garden.", "tree", 0),
      word("flower", "/ˈflaʊ.ə/", "bông hoa", "She buys flowers for her mum.", "flow|er", 0),
      word("river", "/ˈrɪv.ə/", "dòng sông", "Hanoi is on the Red River.", "riv|er", 0),
      word("sea", "/siː/", "biển", "The sea is warm in summer.", "sea", 0),
      word("mountain", "/ˈmaʊn.tɪn/", "ngọn núi", "Fansipan is a high mountain.", "moun|tain", 0),
    ],
  },
  {
    id: "co-the-suc-khoe",
    title: "Cơ thể, sức khỏe & thể thao",
    words: [
      word("body", "/ˈbɒd.i/", "cơ thể", "Sport is good for your body.", "bod|y", 0),
      word("head", "/hed/", "cái đầu", "My head hurts.", "head", 0),
      word("face", "/feɪs/", "khuôn mặt", "Wash your face.", "face", 0),
      word("nose", "/nəʊz/", "cái mũi", "The baby has a small nose.", "nose", 0, "Kết thúc bằng /z/, không đọc thành “nâu”."),
      word("mouth", "/maʊθ/", "cái miệng", "Open your mouth, please.", "mouth", 0, "Kết thúc bằng /θ/: đưa lưỡi ra giữa hai hàm răng."),
      word("ear", "/ɪə/", "cái tai", "My ear hurts.", "ear", 0),
      word("tooth", "/tuːθ/", "cái răng", "I have a bad tooth.", "tooth", 0, "Kết thúc bằng /θ/, không đọc thành “tút”."),
      word("neck", "/nek/", "cái cổ", "She has a long neck.", "neck", 0),
      word("fat", "/fæt/", "béo", "Our cat is very fat.", "fat", 0),
      word("arm", "/ɑːm/", "cánh tay", "He has strong arms.", "arm", 0),
      word("hand", "/hænd/", "bàn tay", "Put up your hand.", "hand", 0),
      word("finger", "/ˈfɪŋ.ɡə/", "ngón tay", "A hand has five fingers.", "fin|ger", 0),
      word("leg", "/leɡ/", "chân (cả cẳng chân)", "My legs are tired after the walk.", "leg", 0),
      word("foot", "/fʊt/", "bàn chân", "I go to school on foot.", "foot", 0),
      word("tennis", "/ˈten.ɪs/", "quần vợt", "My father plays tennis on Sundays.", "ten|nis", 0),
      word("toe", "/təʊ/", "ngón chân", "My toes are cold.", "toe", 0),
      word("basketball", "/ˈbɑː.skɪt.bɔːl/", "bóng rổ", "My brother plays basketball after school.", "bas|ket|ball", 0),
      word("heart", "/hɑːt/", "trái tim", "Running is good for your heart.", "heart", 0),
      word("ill", "/ɪl/", "ốm", "I'm ill today, so I'm staying at home.", "ill", 0),
      word("sick", "/sɪk/", "ốm, bệnh", "My son is sick. He has a fever.", "sick", 0),
      word("hurt", "/hɜːt/", "đau; làm đau", "My back hurts.", "hurt", 0),
      word("well", "/wel/", "khỏe", "I don't feel well.", "well", 0),
      word("healthy", "/ˈhel.θi/", "khỏe mạnh; tốt cho sức khỏe", "Fruit is healthy food.", "health|y", 0),
      word("thin", "/θɪn/", "gầy, mỏng", "He is tall and thin.", "thin", 0, "Âm /θ/ ở đầu, không đọc thành “tin”."),
      word("strong", "/strɒŋ/", "khỏe, mạnh", "My brother is very strong.", "strong", 0),
      word("pretty", "/ˈprɪt.i/", "xinh xắn", "Your daughter is very pretty.", "pret|ty", 0),
      word("blond", "/blɒnd/", "(tóc) vàng hoe", "She has long blond hair.", "blond", 0),
    ],
  },
];

export default topics;
