import { word } from "../builders";
import type { WordTopic } from "../types";

/** Extra A2 vocabulary by topic, reviewed with spaced repetition (see /tu-vung). */
const topics: WordTopic[] = [
  {
    id: "gia-dinh-va-cac-moi-quan-he",
    title: "Gia đình và các mối quan hệ",
    words: [
      word("relative", "/ˈrel.ə.tɪv/", "họ hàng", "All my relatives came to the party.", "rel|a|tive", 0),
      word("nephew", "/ˈnef.juː/", "cháu trai (con của anh chị em)", "My nephew is five years old.", "neph|ew", 0, "ph đọc /f/"),
      word("niece", "/niːs/", "cháu gái (con của anh chị em)", "Her niece is starting school this year.", "niece", 0),
      word("grandson", "/ˈɡræn.sʌn/", "cháu trai (con của con)", "Their grandson visits them every Sunday.", "gran|son", 0, "chữ d không đọc: /ˈɡræn.sʌn/"),
      word("granddaughter", "/ˈɡræn.dɔː.tə/", "cháu gái (con của con)", "My granddaughter loves drawing.", "gran|daugh|ter", 0, "gh không đọc, chỉ đọc một âm /d/"),
      word("grandchild", "/ˈɡræn.tʃaɪld/", "cháu (con của con)", "Their first grandchild was born in May.", "gran|child", 0),
      word("couple", "/ˈkʌp.əl/", "cặp đôi, vợ chồng", "A young couple lives next door.", "cou|ple", 0),
      word("marry", "/ˈmær.i/", "kết hôn, cưới", "He wants to marry his girlfriend next spring.", "mar|ry", 0),
      word("twin", "/twɪn/", "anh/chị/em sinh đôi", "Lan has a twin sister.", "twin", 0),
      word("teenager", "/ˈtiːn.eɪ.dʒə/", "thiếu niên (13–19 tuổi)", "My son is a teenager now.", "teen|a|ger", 0),
      word("nickname", "/ˈnɪk.neɪm/", "biệt danh", "My nickname at school was Tiny.", "nick|name", 0),
      word("together", "/təˈɡeð.ə/", "cùng nhau", "We always have dinner together.", "to|geth|er", 1),
      word("grow", "/ɡrəʊ/", "lớn lên; trồng", "Children grow very fast.", "grow", 0),
      word("guest", "/ɡest/", "khách", "We have three guests for dinner tonight.", "guest", 0, "u không đọc: /ɡest/"),
      word("celebrate", "/ˈsel.ə.breɪt/", "tổ chức mừng", "We celebrate Tet with our family.", "cel|e|brate", 0),
      word("celebration", "/ˌsel.əˈbreɪ.ʃən/", "buổi lễ mừng", "There was a big celebration after the wedding.", "cel|e|bra|tion", 2),
      word("share", "/ʃeə/", "chia sẻ, dùng chung", "I share a room with my sister.", "share", 0),
      word("kiss", "/kɪs/", "hôn; nụ hôn", "She gave her baby a kiss.", "kiss", 0),
      word("hug", "/hʌɡ/", "ôm; cái ôm", "My mum gave me a big hug at the airport.", "hug", 0),
      word("housework", "/ˈhaʊs.wɜːk/", "việc nhà", "My brother never does any housework.", "house|work", 0),
      word("member", "/ˈmem.bə/", "thành viên", "There are five members in my family.", "mem|ber", 0),
      word("alone", "/əˈləʊn/", "một mình", "My grandmother lives alone.", "a|lone", 1),
      word("friendship", "/ˈfrend.ʃɪp/", "tình bạn", "Their friendship started at school.", "friend|ship", 0),
      word("babysit", "/ˈbeɪ.bi.sɪt/", "trông trẻ", "I sometimes babysit for my neighbours.", "ba|by|sit", 0),
      word("daily", "/ˈdeɪ.li/", "hằng ngày", "Cooking is part of my daily life.", "dai|ly", 0),
      word("invitation", "/ˌɪn.vɪˈteɪ.ʃən/", "lời mời, thiệp mời", "We got an invitation to their wedding.", "in|vi|ta|tion", 2),
      word("gift", "/ɡɪft/", "quà tặng", "This watch was a gift from my father.", "gift", 0),
      word("introduce", "/ˌɪn.trəˈdʒuːs/", "giới thiệu", "Let me introduce my wife, Mai.", "in|tro|duce", 2),
      word("care", "/keə/", "chăm sóc, quan tâm", "She takes care of her little brother.", "care", 0),
      word("relationship", "/rɪˈleɪ.ʃən.ʃɪp/", "mối quan hệ", "I have a good relationship with my parents.", "re|la|tion|ship", 1),
      word("generation", "/ˌdʒen.əˈreɪ.ʃən/", "thế hệ", "Three generations live in this house.", "gen|e|ra|tion", 2),
      word("single", "/ˈsɪŋ.ɡəl/", "độc thân", "My brother is thirty and still single.", "sin|gle", 0),
    ],
  },
  {
    id: "so-thich-va-giai-tri",
    title: "Sở thích, thể thao và giải trí",
    words: [
      word("camping", "/ˈkæm.pɪŋ/", "cắm trại", "We go camping in the mountains every summer.", "camp|ing", 0),
      word("fishing", "/ˈfɪʃ.ɪŋ/", "câu cá", "My grandfather goes fishing on Sundays.", "fish|ing", 0),
      word("hiking", "/ˈhaɪ.kɪŋ/", "đi bộ đường dài", "Hiking in Sa Pa is very popular.", "hik|ing", 0),
      word("climbing", "/ˈklaɪ.mɪŋ/", "leo núi", "Climbing is my favourite sport.", "climb|ing", 0, "b không đọc: /ˈklaɪ.mɪŋ/"),
      word("cycling", "/ˈsaɪ.klɪŋ/", "đạp xe", "Cycling to work keeps me healthy.", "cy|cling", 0),
      word("sailing", "/ˈseɪ.lɪŋ/", "đi thuyền buồm", "They went sailing on the lake.", "sail|ing", 0),
      word("skiing", "/ˈskiː.ɪŋ/", "trượt tuyết", "Have you ever tried skiing?", "ski|ing", 0),
      word("jogging", "/ˈdʒɒɡ.ɪŋ/", "chạy bộ", "I go jogging in the park before breakfast.", "jog|ging", 0),
      word("yoga", "/ˈjəʊ.ɡə/", "yoga", "My mother does yoga three times a week.", "yo|ga", 0),
      word("chess", "/tʃes/", "cờ vua", "Can you play chess?", "chess", 0),
      word("competition", "/ˌkɒm.pəˈtɪʃ.ən/", "cuộc thi", "She won a singing competition.", "com|pe|ti|tion", 2),
      word("prize", "/praɪz/", "giải thưởng", "The first prize is a new bike.", "prize", 0),
      word("score", "/skɔː/", "ghi (bàn, điểm)", "He scored two goals yesterday.", "score", 0),
      word("race", "/reɪs/", "cuộc đua", "Who won the race?", "race", 0),
      word("goal", "/ɡəʊl/", "bàn thắng", "What a fantastic goal!", "goal", 0),
      word("lose", "/luːz/", "thua", "Our team didn't want to lose the match.", "lose", 0, "đọc /luːz/ (u dài, kết thúc bằng /z/), khác loose /luːs/"),
      word("match", "/mætʃ/", "trận đấu", "Did you watch the football match last night?", "match", 0),
      word("pool", "/puːl/", "bể bơi", "Is there a pool at the hotel?", "pool", 0),
      word("throw", "/θrəʊ/", "ném", "Throw the ball to me!", "throw", 0),
      word("catch", "/kætʃ/", "bắt (bóng)", "Can you catch the ball?", "catch", 0),
      word("kick", "/kɪk/", "đá", "Kick the ball as hard as you can.", "kick", 0),
      word("club", "/klʌb/", "câu lạc bộ", "I joined the chess club at school.", "club", 0),
      word("painting", "/ˈpeɪn.tɪŋ/", "bức tranh; việc vẽ tranh", "There is a beautiful painting on the wall.", "paint|ing", 0),
      word("drawing", "/ˈdrɔː.ɪŋ/", "bức vẽ; việc vẽ", "My daughter's drawing won a prize.", "draw|ing", 0),
      word("collect", "/kəˈlekt/", "sưu tầm", "He collects old coins.", "col|lect", 1),
      word("exhibition", "/ˌek.sɪˈbɪʃ.ən/", "cuộc triển lãm", "We went to a photo exhibition.", "ex|hi|bi|tion", 2, "h không đọc: /ˌek.sɪˈbɪʃ.ən/"),
      word("gallery", "/ˈɡæl.ər.i/", "phòng tranh", "The gallery is free on Sundays.", "gal|le|ry", 0),
      word("cartoon", "/kɑːˈtuːn/", "phim hoạt hình", "My kids watch cartoons every morning.", "car|toon", 1),
      word("programme", "/ˈprəʊ.ɡræm/", "chương trình (TV)", "What's your favourite TV programme?", "pro|gramme", 0),
      word("channel", "/ˈtʃæn.əl/", "kênh (TV)", "Can I change the channel?", "chan|nel", 0),
      word("magazine", "/ˌmæɡ.əˈziːn/", "tạp chí", "I read a fashion magazine on the train.", "mag|a|zine", 2),
      word("novel", "/ˈnɒv.əl/", "tiểu thuyết", "This novel is very long.", "nov|el", 0),
      word("poem", "/ˈpəʊ.ɪm/", "bài thơ", "She wrote a poem for her mother.", "po|em", 0),
      word("activity", "/ækˈtɪv.ə.ti/", "hoạt động", "Swimming is my favourite activity.", "ac|tiv|i|ty", 1),
      word("musician", "/mjuːˈzɪʃ.ən/", "nhạc sĩ, nhạc công", "Her father is a famous musician.", "mu|si|cian", 1),
      word("instrument", "/ˈɪn.strə.mənt/", "nhạc cụ", "Do you play a musical instrument?", "in|stru|ment", 0),
      word("violin", "/ˌvaɪ.əˈlɪn/", "đàn vi-ô-lông", "She has played the violin since she was six.", "vi|o|lin", 2),
      word("drum", "/drʌm/", "cái trống", "He plays the drums very loudly.", "drum", 0),
      word("relax", "/rɪˈlæks/", "thư giãn", "I relax by listening to music.", "re|lax", 1),
      word("fan", "/fæn/", "người hâm mộ", "I'm a big fan of this band.", "fan", 0),
      word("comedy", "/ˈkɒm.ə.di/", "phim/kịch hài", "We watched a comedy and laughed a lot.", "com|e|dy", 0),
      word("joke", "/dʒəʊk/", "chuyện cười", "My dad tells terrible jokes.", "joke", 0),
      word("laugh", "/lɑːf/", "cười (thành tiếng)", "Everyone laughed at his joke.", "laugh", 0, "gh đọc /f/: /lɑːf/"),
    ],
  },
  {
    id: "du-lich-va-ky-nghi",
    title: "Du lịch và kỳ nghỉ",
    words: [
      word("backpack", "/ˈbæk.pæk/", "ba lô", "I only need a backpack for the weekend.", "back|pack", 0),
      word("sightseeing", "/ˈsaɪtˌsiː.ɪŋ/", "đi tham quan", "We did some sightseeing in Hue.", "sight|see|ing", 0, "gh không đọc: /ˈsaɪt/"),
      word("guidebook", "/ˈɡaɪd.bʊk/", "sách hướng dẫn du lịch", "The guidebook says the museum opens at nine.", "guide|book", 0),
      word("resort", "/rɪˈzɔːt/", "khu nghỉ dưỡng", "We stayed at a beach resort in Nha Trang.", "re|sort", 1, "s đọc /z/: /rɪˈzɔːt/"),
      word("hostel", "/ˈhɒs.təl/", "nhà nghỉ giá rẻ", "Students often stay in hostels.", "hos|tel", 0),
      word("campsite", "/ˈkæmp.saɪt/", "khu cắm trại", "The campsite is next to a river.", "camp|site", 0),
      word("tent", "/tent/", "cái lều", "We put up our tent near the lake.", "tent", 0),
      word("booking", "/ˈbʊk.ɪŋ/", "sự đặt chỗ", "I made a booking for two nights.", "book|ing", 0),
      word("double", "/ˈdʌb.əl/", "(phòng) đôi", "We'd like a double room, please.", "dou|ble", 0, "ou đọc /ʌ/: /ˈdʌb.əl/"),
      word("view", "/vjuː/", "quang cảnh", "Our room has a view of the sea.", "view", 0),
      word("sunbathe", "/ˈsʌn.beɪð/", "tắm nắng", "Many people sunbathe on the beach.", "sun|bathe", 0),
      word("postcard", "/ˈpəʊst.kɑːd/", "bưu thiếp", "I sent my grandmother a postcard from Paris.", "post|card", 0),
      word("guide", "/ɡaɪd/", "hướng dẫn viên", "Our guide spoke very good English.", "guide", 0),
      word("visa", "/ˈviː.zə/", "thị thực", "Do I need a visa to visit Japan?", "vi|sa", 0),
      word("arrival", "/əˈraɪ.vəl/", "sự đến nơi", "Call me on arrival at the hotel.", "a|rri|val", 1),
      word("pack", "/pæk/", "xếp đồ (vào va li)", "Don't forget to pack your passport.", "pack", 0),
      word("unpack", "/ʌnˈpæk/", "dỡ đồ ra", "I unpacked my suitcase and went to bed.", "un|pack", 1),
      word("sunglasses", "/ˈsʌŋˌɡlɑː.sɪz/", "kính râm", "Wear your sunglasses on the beach.", "sun|glass|es", 0),
      word("suncream", "/ˈsʌn.kriːm/", "kem chống nắng", "Put on some suncream before you go out.", "sun|cream", 0),
      word("swimsuit", "/ˈswɪm.suːt/", "đồ bơi", "I forgot my swimsuit at home.", "swim|suit", 0),
      word("towel", "/ˈtaʊ.əl/", "khăn tắm", "Can I have a clean towel, please?", "tow|el", 0),
      word("adventure", "/ədˈven.tʃə/", "cuộc phiêu lưu", "Our trip to the jungle was a real adventure.", "ad|ven|ture", 1),
      word("explore", "/ɪkˈsplɔː/", "khám phá", "We explored the old town on foot.", "ex|plore", 1),
      word("culture", "/ˈkʌl.tʃə/", "văn hóa", "I want to learn about Japanese culture.", "cul|ture", 0),
      word("local", "/ˈləʊ.kəl/", "(thuộc) địa phương", "Try the local food when you travel.", "lo|cal", 0),
      word("castle", "/ˈkɑː.səl/", "lâu đài", "We visited an old castle in Scotland.", "cas|tle", 0, "t không đọc: /ˈkɑː.səl/"),
      word("palace", "/ˈpæl.ɪs/", "cung điện", "The king lived in this palace.", "pal|ace", 0),
      word("temple", "/ˈtem.pəl/", "đền, chùa", "There is a famous temple in the city centre.", "tem|ple", 0),
      word("hire", "/haɪə/", "thuê (xe, đồ)", "You can hire a bike for a day.", "hire", 0),
      word("peaceful", "/ˈpiːs.fəl/", "yên bình", "The village is quiet and peaceful.", "peace|ful", 0),
      word("visitor", "/ˈvɪz.ɪ.tə/", "du khách, khách tham quan", "The old town gets thousands of visitors every day.", "vis|i|tor", 0, "s đọc /z/: /ˈvɪz.ɪ.tə/"),
    ],
  },
  {
    id: "cong-viec-va-nghe-nghiep",
    title: "Công việc và nghề nghiệp",
    words: [
      word("mechanic", "/məˈkæn.ɪk/", "thợ máy", "The mechanic fixed my car in an hour.", "me|chan|ic", 1, "ch đọc /k/: /məˈkæn.ɪk/"),
      word("lawyer", "/ˈlɔɪ.ə/", "luật sư", "She wants to become a lawyer.", "law|yer", 0),
      word("scientist", "/ˈsaɪ.ən.tɪst/", "nhà khoa học", "My uncle is a scientist in a big lab.", "sci|en|tist", 0),
      word("chef", "/ʃef/", "đầu bếp", "The chef made a special dish for us.", "chef", 0, "ch đọc /ʃ/ (từ gốc Pháp)"),
      word("cleaner", "/ˈkliː.nə/", "người dọn dẹp", "The cleaner comes to our office every evening.", "clean|er", 0),
      word("manager", "/ˈmæn.ɪ.dʒə/", "người quản lý", "I'd like to speak to the manager.", "man|a|ger", 0, "nhấn âm đầu: /ˈmæn.ɪ.dʒə/"),
      word("secretary", "/ˈsek.rə.tər.i/", "thư ký", "Please leave a message with my secretary.", "sec|re|tar|y", 0),
      word("boss", "/bɒs/", "sếp", "My boss is very friendly.", "boss", 0),
      word("staff", "/stɑːf/", "nhân viên (nói chung)", "The hotel staff were very helpful.", "staff", 0),
      word("factory", "/ˈfæk.tər.i/", "nhà máy", "My father works in a shoe factory.", "fac|to|ry", 0),
      word("firefighter", "/ˈfaɪə.faɪ.tə/", "lính cứu hỏa", "The firefighters arrived very quickly.", "fire|fight|er", 0),
      word("soldier", "/ˈsəʊl.dʒə/", "người lính", "My grandfather was a soldier.", "sol|dier", 0, "di đọc /dʒ/: /ˈsəʊl.dʒə/"),
      word("businessman", "/ˈbɪz.nɪs.mən/", "doanh nhân", "He is a successful businessman.", "busi|ness|man", 0, "chữ i thứ nhất không đọc: /ˈbɪz.nɪs/"),
      word("artist", "/ˈɑː.tɪst/", "họa sĩ, nghệ sĩ", "The artist painted a picture of the sea.", "art|ist", 0),
      word("designer", "/dɪˈzaɪ.nə/", "nhà thiết kế", "She is a fashion designer.", "de|sign|er", 1, "g không đọc, s đọc /z/"),
      word("worker", "/ˈwɜː.kə/", "công nhân, người lao động", "The factory has five hundred workers.", "work|er", 0),
      word("vet", "/vet/", "bác sĩ thú y", "We took our cat to the vet.", "vet", 0),
      word("assistant", "/əˈsɪs.tənt/", "trợ lý, nhân viên phụ", "She works as a shop assistant.", "as|sis|tant", 1),
      word("officer", "/ˈɒf.ɪ.sə/", "sĩ quan, cán bộ", "A police officer helped us find the way.", "of|fi|cer", 0),
      word("director", "/daɪˈrek.tə/", "giám đốc; đạo diễn", "The director of the company is on holiday.", "di|rec|tor", 1),
      word("earn", "/ɜːn/", "kiếm (tiền)", "How much does a nurse earn?", "earn", 0),
      word("part-time", "/ˌpɑːtˈtaɪm/", "bán thời gian", "I have a part-time job at a café.", "part|time", 1),
      word("full-time", "/ˌfʊlˈtaɪm/", "toàn thời gian", "She works full-time in a bank.", "full|time", 1),
      word("meeting", "/ˈmiː.tɪŋ/", "cuộc họp", "I have a meeting at ten o'clock.", "meet|ing", 0),
      word("skill", "/skɪl/", "kỹ năng", "Computer skills are important for this job.", "skill", 0),
      word("training", "/ˈtreɪ.nɪŋ/", "sự đào tạo", "New staff get two weeks of training.", "train|ing", 0),
      word("unemployed", "/ˌʌn.ɪmˈplɔɪd/", "thất nghiệp", "He has been unemployed since March.", "un|em|ployed", 2),
      word("business", "/ˈbɪz.nɪs/", "việc kinh doanh", "My parents run a small business.", "busi|ness", 0, "chữ i thứ nhất không đọc: /ˈbɪz.nɪs/"),
      word("rule", "/ruːl/", "quy định", "You must follow the rules at work.", "rule", 0),
      word("employee", "/ɪmˈplɔɪ.iː/", "nhân viên, người làm thuê", "The company has two hundred employees.", "em|ploy|ee", 1),
      word("employer", "/ɪmˈplɔɪ.ə/", "chủ, người thuê lao động", "My employer pays me every month.", "em|ploy|er", 1),
    ],
  },
  {
    id: "mua-sam-va-quan-ao",
    title: "Mua sắm, tiền bạc và quần áo",
    words: [
      word("cash", "/kæʃ/", "tiền mặt", "Can I pay in cash?", "cash", 0),
      word("coin", "/kɔɪn/", "đồng xu", "I need some coins for the machine.", "coin", 0),
      word("purse", "/pɜːs/", "ví (nữ)", "She put her purse in her bag.", "purse", 0),
      word("spend", "/spend/", "tiêu (tiền)", "I spend too much money on clothes.", "spend", 0),
      word("sale", "/seɪl/", "đợt giảm giá", "These shoes were in the sale.", "sale", 0),
      word("trainers", "/ˈtreɪ.nəz/", "giày thể thao", "I need new trainers for running.", "train|ers", 0),
      word("department", "/dɪˈpɑːt.mənt/", "gian hàng, bộ phận", "The shoe department is on the second floor.", "de|part|ment", 1),
      word("bill", "/bɪl/", "hóa đơn", "Can we have the bill, please?", "bill", 0),
      word("exchange", "/ɪksˈtʃeɪndʒ/", "đổi (hàng)", "Can I exchange this shirt for a bigger one?", "ex|change", 1),
      word("order", "/ˈɔː.də/", "đặt hàng; gọi món", "I ordered a new phone online.", "or|der", 0),
      word("basket", "/ˈbɑː.skɪt/", "cái giỏ", "Put the apples in the basket.", "bas|ket", 0),
      word("crisps", "/krɪsps/", "khoai tây chiên lát (đóng gói)", "Don't eat too many crisps.", "crisps", 0),
      word("save", "/seɪv/", "tiết kiệm", "I'm saving money for a new laptop.", "save", 0),
      word("rich", "/rɪtʃ/", "giàu", "He wants to be rich one day.", "rich", 0),
      word("poor", "/pɔː/", "nghèo", "Many poor families live in this area.", "poor", 0),
      word("advertisement", "/ədˈvɜː.tɪs.mənt/", "quảng cáo", "I saw an advertisement for this phone on TV.", "ad|ver|tise|ment", 1, "Anh-Anh nhấn âm 2: /ədˈvɜː.tɪs.mənt/"),
      word("sandal", "/ˈsæn.dəl/", "dép xăng-đan", "I wear sandals in summer.", "san|dal", 0),
      word("butcher", "/ˈbʊtʃ.ə/", "người bán thịt", "The butcher's shop is next to the bank.", "butch|er", 0),
      word("chemist", "/ˈkem.ɪst/", "hiệu thuốc; dược sĩ", "You can buy suncream at the chemist's.", "chem|ist", 0, "ch đọc /k/: /ˈkem.ɪst/"),
      word("packet", "/ˈpæk.ɪt/", "gói", "Can I have a packet of crisps?", "pack|et", 0),
      word("tie", "/taɪ/", "cà vạt", "My father wears a tie to work.", "tie", 0),
      word("suit", "/suːt/", "bộ com-lê", "He bought a new suit for the wedding.", "suit", 0),
      word("fashion", "/ˈfæʃ.ən/", "thời trang", "She is very interested in fashion.", "fash|ion", 0),
      word("fashionable", "/ˈfæʃ.ən.ə.bəl/", "hợp thời trang", "Wide trousers are fashionable again.", "fash|ion|a|ble", 0),
      word("style", "/staɪl/", "phong cách, kiểu", "I like the style of your jacket.", "style", 0),
      word("jewellery", "/ˈdʒuː.əl.ri/", "đồ trang sức", "She doesn't wear much jewellery.", "jew|el|lery", 0),
      word("necklace", "/ˈnek.ləs/", "vòng cổ", "He gave her a gold necklace.", "neck|lace", 0),
      word("ring", "/rɪŋ/", "chiếc nhẫn", "That's a beautiful ring!", "ring", 0),
      word("cotton", "/ˈkɒt.ən/", "vải bông", "This shirt is made of cotton.", "cot|ton", 0),
      word("wool", "/wʊl/", "len", "This scarf is made of wool.", "wool", 0),
      word("leather", "/ˈleð.ə/", "da (thuộc)", "I want a leather jacket.", "leath|er", 0),
      word("button", "/ˈbʌt.ən/", "cúc áo", "A button came off my shirt.", "but|ton", 0),
      word("blouse", "/blaʊz/", "áo sơ mi nữ", "She is wearing a white blouse.", "blouse", 0, "s đọc /z/: /blaʊz/"),
      word("raincoat", "/ˈreɪŋ.kəʊt/", "áo mưa", "Take your raincoat. It's going to rain.", "rain|coat", 0),
      word("handbag", "/ˈhænd.bæɡ/", "túi xách", "She put her phone in her handbag.", "hand|bag", 0),
      word("smart", "/smɑːt/", "(ăn mặc) lịch sự, bảnh", "You look very smart in that suit.", "smart", 0),
    ],
  },
  {
    id: "truong-hoc-va-hoc-tap",
    title: "Trường học và học tập",
    words: [
      word("geography", "/dʒiˈɒɡ.rə.fi/", "môn địa lý", "Geography is my favourite subject.", "ge|og|ra|phy", 1),
      word("biology", "/baɪˈɒl.ə.dʒi/", "môn sinh học", "We study plants in biology.", "bi|ol|o|gy", 1),
      word("chemistry", "/ˈkem.ɪ.stri/", "môn hóa học", "I have a chemistry test tomorrow.", "chem|is|try", 0, "ch đọc /k/: /ˈkem.ɪ.stri/"),
      word("physics", "/ˈfɪz.ɪks/", "môn vật lý", "Physics is difficult for me.", "phys|ics", 0, "ph đọc /f/, y đọc /ɪ/, s đọc /z/"),
      word("mark", "/mɑːk/", "điểm số", "I got a good mark in English.", "mark", 0),
      word("pass", "/pɑːs/", "thi đỗ", "I hope I pass the exam.", "pass", 0),
      word("fail", "/feɪl/", "thi trượt", "He failed his driving test.", "fail", 0),
      word("term", "/tɜːm/", "học kỳ", "The new term starts in September.", "term", 0),
      word("classmate", "/ˈklɑːs.meɪt/", "bạn cùng lớp", "My classmates are very friendly.", "class|mate", 0),
      word("pupil", "/ˈpjuː.pəl/", "học sinh", "There are thirty pupils in my class.", "pu|pil", 0),
      word("headteacher", "/ˌhedˈtiː.tʃə/", "hiệu trưởng", "The headteacher wants to see you.", "head|teach|er", 1),
      word("course", "/kɔːs/", "khóa học", "I'm doing an English course online.", "course", 0, "đọc /kɔːs/, không đọc chữ r"),
      word("college", "/ˈkɒl.ɪdʒ/", "trường cao đẳng", "My sister goes to college in Hanoi.", "col|lege", 0),
      word("note", "/nəʊt/", "ghi chú", "Take notes during the lesson.", "note", 0),
      word("ruler", "/ˈruː.lə/", "thước kẻ", "Can I borrow your ruler?", "rul|er", 0),
      word("rubber", "/ˈrʌb.ə/", "cục tẩy", "I need a rubber. I made a mistake.", "rub|ber", 0),
      word("scissors", "/ˈsɪz.əz/", "cái kéo", "Cut the paper with scissors.", "scis|sors", 0, "sc đọc /s/, ss đọc /z/: /ˈsɪz.əz/"),
      word("exam", "/ɪɡˈzæm/", "kỳ thi", "I have an English exam on Friday.", "ex|am", 1, "x đọc /ɡz/: /ɪɡˈzæm/"),
      word("whiteboard", "/ˈwaɪt.bɔːd/", "bảng trắng", "The teacher wrote the new words on the whiteboard.", "white|board", 0),
      word("playground", "/ˈpleɪ.ɡraʊnd/", "sân chơi", "The children are playing in the playground.", "play|ground", 0),
      word("canteen", "/kænˈtiːn/", "căng tin", "We have lunch in the school canteen.", "can|teen", 1),
      word("essay", "/ˈes.eɪ/", "bài luận", "Write an essay about your hometown.", "es|say", 0),
      word("translate", "/trænzˈleɪt/", "dịch", "Can you translate this sentence?", "trans|late", 1),
      word("correct", "/kəˈrekt/", "đúng; sửa (lỗi)", "Is this answer correct?", "cor|rect", 1),
      word("quiz", "/kwɪz/", "bài kiểm tra nhanh", "We have a vocabulary quiz every Friday.", "quiz", 0),
      word("certificate", "/səˈtɪf.ɪ.kət/", "chứng chỉ", "You get a certificate at the end of the course.", "cer|tif|i|cate", 1),
      word("drama", "/ˈdrɑː.mə/", "môn kịch", "Drama is my favourite subject.", "dra|ma", 0),
      word("primary", "/ˈpraɪ.mər.i/", "(trường) tiểu học", "My son is at primary school.", "pri|ma|ry", 0),
      word("secondary", "/ˈsek.ən.dər.i/", "(trường) trung học", "She teaches at a secondary school.", "sec|on|da|ry", 0),
      word("education", "/ˌedʒ.ʊˈkeɪ.ʃən/", "giáo dục", "Education is very important in Vietnam.", "ed|u|ca|tion", 2),
      word("lab", "/læb/", "phòng thí nghiệm", "We do experiments in the science lab.", "lab", 0),
    ],
  },
  {
    id: "suc-khoe-va-co-the",
    title: "Sức khỏe và cơ thể",
    words: [
      word("elbow", "/ˈel.bəʊ/", "khuỷu tay", "Don't put your elbows on the table.", "el|bow", 0),
      word("health", "/helθ/", "sức khỏe", "Smoking is bad for your health.", "health", 0, "th cuối đọc /θ/ (lưỡi giữa hai răng)"),
      word("skin", "/skɪn/", "da", "Use suncream to protect your skin.", "skin", 0),
      word("blood", "/blʌd/", "máu", "The doctor took some blood for a test.", "blood", 0, "oo đọc /ʌ/: /blʌd/"),
      word("bone", "/bəʊn/", "xương", "He broke a bone in his arm.", "bone", 0),
      word("brain", "/breɪn/", "não", "The brain controls the whole body.", "brain", 0),
      word("thumb", "/θʌm/", "ngón tay cái", "I cut my thumb while I was cooking.", "thumb", 0, "b không đọc; th là /θ/"),
      word("tongue", "/tʌŋ/", "lưỡi", "Show me your tongue, please.", "tongue", 0, "đọc /tʌŋ/, ue không đọc"),
      word("flu", "/fluː/", "bệnh cúm", "Half my class has got flu.", "flu", 0),
      word("toothache", "/ˈtuːθ.eɪk/", "đau răng", "I've got a terrible toothache.", "tooth|ache", 0),
      word("earache", "/ˈɪə.reɪk/", "đau tai", "The child has an earache.", "ear|ache", 0),
      word("sore", "/sɔː/", "đau rát", "I have a sore throat.", "sore", 0),
      word("pain", "/peɪn/", "cơn đau", "I have a pain in my back.", "pain", 0),
      word("temperature", "/ˈtem.prə.tʃə/", "nhiệt độ; cơn sốt", "The nurse took my temperature.", "tem|pera|ture", 0, "thường đọc 3 âm tiết: /ˈtem.prə.tʃə/"),
      word("pill", "/pɪl/", "viên thuốc", "Take two pills after breakfast.", "pill", 0),
      word("ambulance", "/ˈæm.bjə.ləns/", "xe cứu thương", "Call an ambulance!", "am|bu|lance", 0),
      word("patient", "/ˈpeɪ.ʃənt/", "bệnh nhân", "The doctor has twenty patients today.", "pa|tient", 0, "ti đọc /ʃ/: /ˈpeɪ.ʃənt/"),
      word("unhealthy", "/ʌnˈhel.θi/", "không lành mạnh", "Fast food is unhealthy.", "un|heal|thy", 1),
      word("diet", "/ˈdaɪ.ət/", "chế độ ăn", "A good diet has lots of vegetables.", "di|et", 0),
      word("fit", "/fɪt/", "cân đối, khỏe", "I cycle to work to stay fit.", "fit", 0),
      word("weight", "/weɪt/", "cân nặng", "The doctor checked my weight.", "weight", 0, "gh không đọc: /weɪt/"),
      word("height", "/haɪt/", "chiều cao", "What is your height?", "height", 0, "ei đọc /aɪ/, gh không đọc: /haɪt/"),
      word("breathe", "/briːð/", "thở", "Breathe in slowly.", "breathe", 0, "động từ đọc /briːð/; danh từ breath là /breθ/"),
      word("illness", "/ˈɪl.nəs/", "bệnh tật", "He missed school because of illness.", "ill|ness", 0),
      word("smoke", "/sməʊk/", "hút thuốc", "My father stopped smoking last year.", "smoke", 0),
      word("dead", "/ded/", "chết", "The plants are dead because I forgot to water them.", "dead", 0),
      word("stomachache", "/ˈstʌm.ək.eɪk/", "đau bụng", "I had a stomachache after lunch.", "stom|ach|ache", 0, "ch đọc /k/: /ˈstʌm.ək.eɪk/"),
      word("ache", "/eɪk/", "đau âm ỉ", "My legs ache after the long walk.", "ache", 0, "ch đọc /k/: /eɪk/"),
      word("fall", "/fɔːl/", "ngã", "Be careful! Don't fall on the ice.", "fall", 0),
      word("cut", "/kʌt/", "cắt; làm đứt tay", "Be careful not to cut your finger.", "cut", 0),
      word("bandage", "/ˈbæn.dɪdʒ/", "băng (vết thương)", "The nurse put a bandage on my arm.", "ban|dage", 0),
      word("chin", "/tʃɪn/", "cằm", "He has a small cut on his chin.", "chin", 0),
      word("cheek", "/tʃiːk/", "má", "The baby has pink cheeks.", "cheek", 0),
    ],
  },
  {
    id: "nha-cua-va-do-dung",
    title: "Nhà cửa và đồ dùng",
    words: [
      word("cottage", "/ˈkɒt.ɪdʒ/", "nhà nhỏ ở quê", "They have a small cottage by the sea.", "cot|tage", 0),
      word("garage", "/ˈɡær.ɑːʒ/", "nhà để xe", "Dad keeps his car in the garage.", "gar|age", 0, "Anh-Anh nhấn âm đầu: /ˈɡær.ɑːʒ/"),
      word("balcony", "/ˈbæl.kə.ni/", "ban công", "We have breakfast on the balcony.", "bal|co|ny", 0),
      word("roof", "/ruːf/", "mái nhà", "There is a cat on the roof.", "roof", 0),
      word("upstairs", "/ʌpˈsteəz/", "ở tầng trên", "My bedroom is upstairs.", "up|stairs", 1),
      word("downstairs", "/ˌdaʊnˈsteəz/", "ở tầng dưới", "The kitchen is downstairs.", "down|stairs", 1),
      word("hall", "/hɔːl/", "hành lang, sảnh", "Leave your shoes in the hall.", "hall", 0),
      word("lift", "/lɪft/", "thang máy", "Take the lift to the fifth floor.", "lift", 0),
      word("gate", "/ɡeɪt/", "cổng", "Please close the gate.", "gate", 0),
      word("wardrobe", "/ˈwɔː.drəʊb/", "tủ quần áo", "Hang your clothes in the wardrobe.", "war|drobe", 0),
      word("shelf", "/ʃelf/", "cái kệ, giá", "Put the books on the shelf.", "shelf", 0),
      word("drawer", "/drɔː/", "ngăn kéo", "The knives are in the top drawer.", "drawer", 0, "đọc một âm tiết: /drɔː/"),
      word("mirror", "/ˈmɪr.ə/", "cái gương", "She looked in the mirror.", "mir|ror", 0),
      word("carpet", "/ˈkɑː.pɪt/", "tấm thảm", "There is a blue carpet in the living room.", "car|pet", 0),
      word("curtain", "/ˈkɜː.tən/", "rèm cửa", "Can you open the curtains?", "cur|tain", 0),
      word("pillow", "/ˈpɪl.əʊ/", "cái gối", "I can't sleep without my pillow.", "pil|low", 0),
      word("blanket", "/ˈblæŋ.kɪt/", "cái chăn", "It's cold. I need another blanket.", "blan|ket", 0),
      word("armchair", "/ˈɑːm.tʃeə/", "ghế bành", "Grandpa is sleeping in his armchair.", "arm|chair", 0),
      word("bookcase", "/ˈbʊk.keɪs/", "tủ sách", "The bookcase is full.", "book|case", 0),
      word("cooker", "/ˈkʊk.ə/", "bếp nấu", "We have a gas cooker in the kitchen.", "cook|er", 0),
      word("oven", "/ˈʌv.ən/", "lò nướng", "Put the cake in the oven.", "ov|en", 0, "o đọc /ʌ/: /ˈʌv.ən/"),
      word("microwave", "/ˈmaɪ.krə.weɪv/", "lò vi sóng", "Heat the soup in the microwave.", "mi|cro|wave", 0),
      word("dishwasher", "/ˈdɪʃˌwɒʃ.ə/", "máy rửa bát", "Put the plates in the dishwasher.", "dish|wash|er", 0),
      word("sink", "/sɪŋk/", "bồn rửa", "The dirty cups are in the sink.", "sink", 0),
      word("tap", "/tæp/", "vòi nước", "Turn off the tap.", "tap", 0),
      word("iron", "/aɪən/", "bàn là; là (quần áo)", "I need to iron my shirt.", "iron", 0, "r không đọc: /aɪən/"),
      word("brush", "/brʌʃ/", "bàn chải; chải", "Brush your teeth before bed.", "brush", 0),
      word("soap", "/səʊp/", "xà phòng", "Wash your hands with soap.", "soap", 0),
      word("doorbell", "/ˈdɔː.bel/", "chuông cửa", "The doorbell is ringing.", "door|bell", 0),
      word("move", "/muːv/", "chuyển (nhà)", "We moved to a bigger flat last year.", "move", 0),
      word("electricity", "/ˌel.ɪkˈtrɪs.ə.ti/", "điện", "The electricity went off during the storm.", "el|ec|tric|i|ty", 2),
      word("ceiling", "/ˈsiː.lɪŋ/", "trần nhà", "The ceiling in this room is very high.", "ceil|ing", 0),
    ],
  },
  {
    id: "do-an-va-nau-nuong",
    title: "Đồ ăn và nấu nướng",
    words: [
      word("fry", "/fraɪ/", "rán, chiên", "Fry the onions in a little oil.", "fry", 0),
      word("bake", "/beɪk/", "nướng (bánh)", "My mum bakes a cake every Sunday.", "bake", 0),
      word("roast", "/rəʊst/", "quay, nướng lò", "We roasted a chicken for dinner.", "roast", 0),
      word("mix", "/mɪks/", "trộn", "Mix the eggs and the sugar.", "mix", 0),
      word("slice", "/slaɪs/", "lát; thái lát", "Would you like a slice of bread?", "slice", 0),
      word("pan", "/pæn/", "cái chảo", "Heat some oil in a pan.", "pan", 0),
      word("bowl", "/bəʊl/", "cái bát", "I eat a bowl of pho every morning.", "bowl", 0, "đọc /bəʊl/, không đọc như 'bao'"),
      word("fork", "/fɔːk/", "cái nĩa", "Can I have a knife and fork, please?", "fork", 0),
      word("knife", "/naɪf/", "con dao", "Be careful, this knife is very sharp.", "knife", 0, "k không đọc: /naɪf/"),
      word("spoon", "/spuːn/", "cái thìa", "Use a spoon to eat your soup.", "spoon", 0),
      word("flour", "/flaʊə/", "bột mì", "You need flour, eggs and milk.", "flour", 0, "đọc giống flower: /flaʊə/"),
      word("oil", "/ɔɪl/", "dầu ăn", "Don't use too much oil.", "oil", 0),
      word("pepper", "/ˈpep.ə/", "hạt tiêu", "Add some salt and pepper.", "pep|per", 0),
      word("sauce", "/sɔːs/", "nước sốt", "This sauce is a bit spicy.", "sauce", 0),
      word("fresh", "/freʃ/", "tươi", "We buy fresh fish at the market.", "fresh", 0),
      word("tasty", "/ˈteɪ.sti/", "ngon", "The soup was really tasty.", "tas|ty", 0),
      word("taste", "/teɪst/", "có vị; nếm", "This cake tastes of lemon.", "taste", 0),
      word("smell", "/smel/", "có mùi; ngửi", "Something smells good!", "smell", 0),
      word("snack", "/snæk/", "đồ ăn vặt", "I often have a snack in the afternoon.", "snack", 0),
      word("dessert", "/dɪˈzɜːt/", "món tráng miệng", "What would you like for dessert?", "des|sert", 1, "nhấn âm 2, ss đọc /z/; khác desert /ˈdez.ət/"),
      word("vegetarian", "/ˌvedʒ.ɪˈteə.ri.ən/", "người ăn chay", "My sister is a vegetarian.", "veg|e|tar|i|an", 2),
      word("cream", "/kriːm/", "kem sữa", "Do you want cream in your coffee?", "cream", 0),
      word("honey", "/ˈhʌn.i/", "mật ong", "Add a little honey to your tea.", "hon|ey", 0, "o đọc /ʌ/: /ˈhʌn.i/"),
      word("jam", "/dʒæm/", "mứt", "She made strawberry jam.", "jam", 0),
      word("garlic", "/ˈɡɑː.lɪk/", "tỏi", "This dish has a lot of garlic.", "gar|lic", 0),
      word("onion", "/ˈʌn.jən/", "hành tây", "Cut the onion into small pieces.", "on|ion", 0, "o đọc /ʌ/: /ˈʌn.jən/"),
      word("mushroom", "/ˈmʌʃ.ruːm/", "nấm", "I'd like a mushroom pizza.", "mush|room", 0),
      word("cabbage", "/ˈkæb.ɪdʒ/", "bắp cải", "Cabbage is cheap in winter.", "cab|bage", 0),
      word("lettuce", "/ˈlet.ɪs/", "rau xà lách", "Wash the lettuce before you eat it.", "let|tuce", 0, "đọc /ˈlet.ɪs/, không đọc 'lét-tút'"),
      word("lemon", "/ˈlem.ən/", "quả chanh vàng", "I'd like tea with lemon.", "lem|on", 0),
      word("grape", "/ɡreɪp/", "quả nho", "These grapes are very sweet.", "grape", 0),
      word("strawberry", "/ˈstrɔː.bər.i/", "dâu tây", "Strawberries are my favourite fruit.", "straw|ber|ry", 0),
      word("lamb", "/læm/", "thịt cừu", "We had roast lamb for lunch.", "lamb", 0, "b không đọc: /læm/"),
      word("steak", "/steɪk/", "bít tết", "How would you like your steak?", "steak", 0, "ea đọc /eɪ/: /steɪk/"),
      word("sausage", "/ˈsɒs.ɪdʒ/", "xúc xích", "I had sausages and eggs for breakfast.", "saus|age", 0, "au đọc /ɒ/: /ˈsɒs.ɪdʒ/"),
      word("noodle", "/ˈnuː.dəl/", "mì, bún, phở (sợi)", "I love chicken noodle soup.", "noo|dle", 0),
      word("yoghurt", "/ˈjɒɡ.ət/", "sữa chua", "I eat yoghurt with fruit every morning.", "yog|hurt", 0),
      word("burger", "/ˈbɜː.ɡə/", "bánh mì kẹp thịt", "The children want burgers and chips.", "bur|ger", 0),
    ],
  },
  {
    id: "thoi-tiet-va-thien-nhien",
    title: "Thời tiết và thiên nhiên",
    words: [
      word("foggy", "/ˈfɒɡ.i/", "có sương mù", "It's foggy this morning, so drive slowly.", "fog|gy", 0),
      word("fog", "/fɒɡ/", "sương mù", "The fog was very thick.", "fog", 0),
      word("snowy", "/ˈsnəʊ.i/", "có tuyết", "It was a cold, snowy day.", "snow|y", 0),
      word("icy", "/ˈaɪ.si/", "đóng băng, trơn", "Be careful, the roads are icy.", "i|cy", 0),
      word("ice", "/aɪs/", "băng, đá", "Would you like ice in your drink?", "ice", 0),
      word("freezing", "/ˈfriː.zɪŋ/", "lạnh cóng", "It's freezing outside!", "freez|ing", 0),
      word("sunshine", "/ˈsʌn.ʃaɪn/", "ánh nắng", "Let's enjoy the sunshine.", "sun|shine", 0),
      word("wood", "/wʊd/", "gỗ; khu rừng nhỏ", "We went for a walk in the woods.", "wood", 0),
      word("air", "/eə/", "không khí", "The air in the countryside is clean.", "air", 0),
      word("sunset", "/ˈsʌn.set/", "hoàng hôn", "We watched the sunset from the beach.", "sun|set", 0),
      word("sunrise", "/ˈsʌn.raɪz/", "bình minh", "We got up early to see the sunrise.", "sun|rise", 0),
      word("blow", "/bləʊ/", "thổi", "The wind is blowing hard.", "blow", 0),
      word("shine", "/ʃaɪn/", "chiếu sáng", "The sun is shining today.", "shine", 0),
      word("clear", "/klɪə/", "quang đãng", "The sky is clear tonight.", "clear", 0),
      word("forest", "/ˈfɒr.ɪst/", "rừng", "There are many birds in the forest.", "for|est", 0),
      word("jungle", "/ˈdʒʌŋ.ɡəl/", "rừng rậm", "Tigers live in the jungle.", "jun|gle", 0),
      word("desert", "/ˈdez.ət/", "sa mạc", "It hardly ever rains in the desert.", "des|ert", 0, "nhấn âm 1, s đọc /z/; khác dessert /dɪˈzɜːt/"),
      word("hill", "/hɪl/", "ngọn đồi", "Our house is at the top of the hill.", "hill", 0),
      word("valley", "/ˈvæl.i/", "thung lũng", "A river runs through the valley.", "val|ley", 0),
      word("ocean", "/ˈəʊ.ʃən/", "đại dương", "The Pacific is the biggest ocean.", "o|cean", 0, "c đọc /ʃ/: /ˈəʊ.ʃən/"),
      word("wave", "/weɪv/", "con sóng", "The waves are too big for swimming today.", "wave", 0),
      word("sand", "/sænd/", "cát", "The children played in the sand.", "sand", 0),
      word("rock", "/rɒk/", "tảng đá", "We sat on a rock by the sea.", "rock", 0),
      word("stone", "/stəʊn/", "hòn đá; đá", "The old bridge is made of stone.", "stone", 0),
      word("field", "/fiːld/", "cánh đồng", "There are cows in the field.", "field", 0),
      word("grass", "/ɡrɑːs/", "cỏ", "Please don't walk on the grass.", "grass", 0),
      word("leaf", "/liːf/", "chiếc lá", "The leaves turn yellow in autumn.", "leaf", 0),
      word("planet", "/ˈplæn.ɪt/", "hành tinh", "Earth is our planet.", "plan|et", 0),
      word("earth", "/ɜːθ/", "Trái Đất", "The Earth goes around the sun.", "earth", 0),
      word("environment", "/ɪnˈvaɪ.rən.mənt/", "môi trường", "We must protect the environment.", "en|vi|ron|ment", 1),
      word("insect", "/ˈɪn.sekt/", "côn trùng", "There are lots of insects in summer.", "in|sect", 0),
      word("butterfly", "/ˈbʌt.ə.flaɪ/", "con bướm", "A butterfly landed on the flower.", "but|ter|fly", 0),
      word("bee", "/biː/", "con ong", "Bees make honey.", "bee", 0),
      word("snake", "/sneɪk/", "con rắn", "I'm afraid of snakes.", "snake", 0),
      word("wild", "/waɪld/", "hoang dã", "You can see wild animals in this park.", "wild", 0),
      word("coast", "/kəʊst/", "bờ biển", "We drove along the coast.", "coast", 0),
      word("nature", "/ˈneɪ.tʃə/", "thiên nhiên", "I love walking in nature.", "na|ture", 0),
      word("recycle", "/ˌriːˈsaɪ.kəl/", "tái chế", "We recycle bottles and paper.", "re|cy|cle", 1),
    ],
  },
  {
    id: "giao-thong-va-chi-duong",
    title: "Giao thông và chỉ đường",
    words: [
      word("passenger", "/ˈpæs.ən.dʒə/", "hành khách", "The bus has forty passengers.", "pas|sen|ger", 0),
      word("coach", "/kəʊtʃ/", "xe khách đường dài", "We took a coach from Hanoi to Hai Phong.", "coach", 0),
      word("tram", "/træm/", "xe điện mặt đất", "You can get to the centre by tram.", "tram", 0),
      word("scooter", "/ˈskuː.tə/", "xe tay ga", "She rides a scooter to school.", "scoo|ter", 0),
      word("van", "/væn/", "xe tải nhỏ", "A white van is parked outside.", "van", 0),
      word("lorry", "/ˈlɒr.i/", "xe tải", "A big lorry blocked the road.", "lor|ry", 0),
      word("helicopter", "/ˈhel.ɪˌkɒp.tə/", "máy bay trực thăng", "The helicopter took him to hospital.", "hel|i|cop|ter", 0),
      word("ferry", "/ˈfer.i/", "phà", "We took the ferry to the island.", "fer|ry", 0),
      word("petrol", "/ˈpet.rəl/", "xăng", "We need to stop for petrol.", "pet|rol", 0),
      word("return", "/rɪˈtɜːn/", "(vé) khứ hồi; trở về", "A return ticket to Hue, please.", "re|turn", 1),
      word("turning", "/ˈtɜː.nɪŋ/", "chỗ rẽ", "Take the second turning on the left.", "turn|ing", 0),
      word("roundabout", "/ˈraʊnd.ə.baʊt/", "vòng xuyến", "Go straight on at the roundabout.", "round|a|bout", 0),
      word("along", "/əˈlɒŋ/", "dọc theo", "Walk along this street for five minutes.", "a|long", 1),
      word("across", "/əˈkrɒs/", "ở bên kia; băng qua", "The bank is across the road.", "a|cross", 1),
      word("past", "/pɑːst/", "đi qua", "Go past the church and turn right.", "past", 0),
      word("towards", "/təˈwɔːdz/", "về phía", "He walked towards the station.", "to|wards", 1),
      word("pavement", "/ˈpeɪv.mənt/", "vỉa hè", "Don't park your motorbike on the pavement.", "pave|ment", 0),
      word("motorway", "/ˈməʊ.tə.weɪ/", "đường cao tốc", "The motorway is very busy on Fridays.", "mo|tor|way", 0),
      word("path", "/pɑːθ/", "lối đi nhỏ", "Follow the path to the lake.", "path", 0),
      word("direction", "/daɪˈrek.ʃən/", "hướng; lời chỉ đường", "Can you give me directions to the station?", "di|rec|tion", 1),
      word("distance", "/ˈdɪs.təns/", "khoảng cách", "What's the distance from here to the airport?", "dis|tance", 0),
      word("sign", "/saɪn/", "biển báo", "Follow the signs to the city centre.", "sign", 0, "g không đọc: /saɪn/"),
      word("speed", "/spiːd/", "tốc độ", "Slow down! You're going at a dangerous speed.", "speed", 0),
      word("land", "/lænd/", "hạ cánh", "Our plane landed at six o'clock.", "land", 0),
      word("cyclist", "/ˈsaɪ.klɪst/", "người đi xe đạp", "There are more cyclists in the city now.", "cy|clist", 0),
      word("tunnel", "/ˈtʌn.əl/", "đường hầm", "The train went through a long tunnel.", "tun|nel", 0),
      word("seatbelt", "/ˈsiːt.belt/", "dây an toàn", "Please fasten your seatbelt.", "seat|belt", 0),
      word("wheel", "/wiːl/", "bánh xe", "A bike has two wheels.", "wheel", 0),
      word("engine", "/ˈen.dʒɪn/", "động cơ", "There's a problem with the engine.", "en|gine", 0),
      word("transport", "/ˈtræn.spɔːt/", "phương tiện giao thông", "Public transport in this city is cheap.", "trans|port", 0),
      word("tyre", "/taɪə/", "lốp xe", "I have a flat tyre on my bike.", "tyre", 0, "đọc /taɪə/, không đọc chữ r"),
      word("vehicle", "/ˈvɪə.kəl/", "xe cộ", "No vehicles are allowed in the old town.", "ve|hi|cle", 0, "h không đọc: /ˈvɪə.kəl/"),
      word("fare", "/feə/", "giá vé (xe, tàu)", "The bus fare is ten thousand dong.", "fare", 0),
    ],
  },
  {
    id: "cong-nghe-co-ban",
    title: "Công nghệ cơ bản",
    words: [
      word("keyboard", "/ˈkiː.bɔːd/", "bàn phím", "This keyboard is too small.", "key|board", 0),
      word("screen", "/skriːn/", "màn hình", "My phone screen is broken.", "screen", 0),
      word("online", "/ˌɒnˈlaɪn/", "trực tuyến", "I buy most things online.", "on|line", 1),
      word("download", "/ˌdaʊnˈləʊd/", "tải xuống", "Download the app for free.", "down|load", 1),
      word("upload", "/ʌpˈləʊd/", "tải lên", "She uploaded the photos to her blog.", "up|load", 1),
      word("password", "/ˈpɑːs.wɜːd/", "mật khẩu", "Don't tell anyone your password.", "pass|word", 0),
      word("app", "/æp/", "ứng dụng", "This app helps me learn English.", "app", 0),
      word("printer", "/ˈprɪn.tə/", "máy in", "The printer isn't working.", "print|er", 0),
      word("print", "/prɪnt/", "in", "Can you print this page for me?", "print", 0),
      word("file", "/faɪl/", "tệp, tập tin", "I saved the file on my computer.", "file", 0),
      word("click", "/klɪk/", "nhấp chuột", "Click on the blue button.", "click", 0),
      word("type", "/taɪp/", "gõ (phím)", "She can type very fast.", "type", 0),
      word("search", "/sɜːtʃ/", "tìm kiếm", "Search for the word on the internet.", "search", 0),
      word("battery", "/ˈbæt.ər.i/", "pin", "My phone battery is low.", "bat|ter|y", 0),
      word("headphones", "/ˈhed.fəʊnz/", "tai nghe", "I listen to music with my headphones.", "head|phones", 0),
      word("tablet", "/ˈtæb.lət/", "máy tính bảng", "My son reads books on his tablet.", "tab|let", 0),
      word("technology", "/tekˈnɒl.ə.dʒi/", "công nghệ", "Technology changes very fast.", "tech|nol|o|gy", 1, "ch đọc /k/: /tekˈnɒl.ə.dʒi/"),
      word("machine", "/məˈʃiːn/", "máy móc", "The coffee machine is broken.", "ma|chine", 1, "ch đọc /ʃ/, nhấn âm 2: /məˈʃiːn/"),
      word("chat", "/tʃæt/", "trò chuyện, nhắn tin", "I chat with my friends online every evening.", "chat", 0),
      word("blog", "/blɒɡ/", "blog", "She writes a blog about food.", "blog", 0),
      word("post", "/pəʊst/", "đăng (bài)", "He posted a photo of his dinner.", "post", 0),
      word("invent", "/ɪnˈvent/", "phát minh", "Who invented the telephone?", "in|vent", 1),
      word("invention", "/ɪnˈven.ʃən/", "vật phát minh", "The internet is a great invention.", "in|ven|tion", 1),
      word("link", "/lɪŋk/", "đường dẫn", "I'll send you the link.", "link", 0),
      word("user", "/ˈjuː.zə/", "người dùng", "This app has millions of users.", "us|er", 0),
      word("software", "/ˈsɒft.weə/", "phần mềm", "You need to update your software.", "soft|ware", 0),
      word("delete", "/dɪˈliːt/", "xóa", "I deleted the old photos from my phone.", "de|lete", 1),
      word("account", "/əˈkaʊnt/", "tài khoản", "Do you have an account on this website?", "ac|count", 1),
      word("video", "/ˈvɪd.i.əʊ/", "video", "He posts funny videos online.", "vid|e|o", 0),
      word("plug", "/plʌɡ/", "phích cắm; cắm điện", "Plug the charger into the wall.", "plug", 0),
      word("digital", "/ˈdɪdʒ.ɪ.təl/", "kỹ thuật số", "I bought a digital camera for my trip.", "dig|i|tal", 0),
      word("speaker", "/ˈspiː.kə/", "cái loa", "This speaker is small, but it's very loud.", "speak|er", 0),
    ],
  },
  {
    id: "cam-xuc-va-tinh-cach",
    title: "Cảm xúc, tính cách và ngoại hình",
    words: [
      word("afraid", "/əˈfreɪd/", "sợ", "My little brother is afraid of dogs.", "a|fraid", 1),
      word("frightened", "/ˈfraɪ.tənd/", "hoảng sợ", "The child was frightened by the storm.", "fright|ened", 0, "gh không đọc; -ened đọc /ənd/"),
      word("scared", "/skeəd/", "sợ hãi", "I'm scared of the dark.", "scared", 0),
      word("worried", "/ˈwʌr.id/", "lo lắng", "My mum is worried about my exams.", "wor|ried", 0, "o đọc /ʌ/: /ˈwʌr.id/"),
      word("nervous", "/ˈnɜː.vəs/", "hồi hộp, lo", "I always feel nervous before a test.", "ner|vous", 0),
      word("surprised", "/səˈpraɪzd/", "ngạc nhiên", "I was surprised to see him there.", "sur|prised", 1),
      word("pleased", "/pliːzd/", "hài lòng, vui", "My teacher was pleased with my work.", "pleased", 0),
      word("lonely", "/ˈləʊn.li/", "cô đơn", "She felt lonely in the new city.", "lone|ly", 0),
      word("unhappy", "/ʌnˈhæp.i/", "không vui", "He is unhappy at his new school.", "un|hap|py", 1),
      word("lucky", "/ˈlʌk.i/", "may mắn", "You're lucky to have such good friends.", "luck|y", 0),
      word("relaxed", "/rɪˈlækst/", "thoải mái", "I feel relaxed after a hot bath.", "re|laxed", 1),
      word("feeling", "/ˈfiː.lɪŋ/", "cảm giác, cảm xúc", "I have a feeling we're going to win.", "feel|ing", 0),
      word("hope", "/həʊp/", "hy vọng", "I hope you feel better soon.", "hope", 0),
      word("smile", "/smaɪl/", "nụ cười; mỉm cười", "She has a lovely smile.", "smile", 0),
      word("cry", "/kraɪ/", "khóc", "The baby is crying.", "cry", 0),
      word("amazing", "/əˈmeɪ.zɪŋ/", "tuyệt vời, đáng kinh ngạc", "The view from the top was amazing.", "a|maz|ing", 1),
      word("fantastic", "/fænˈtæs.tɪk/", "tuyệt vời", "We had a fantastic holiday.", "fan|tas|tic", 1),
      word("brilliant", "/ˈbrɪl.jənt/", "xuất sắc, tuyệt", "That's a brilliant idea!", "bril|liant", 0),
      word("terrible", "/ˈter.ə.bəl/", "tồi tệ", "The food was terrible.", "ter|ri|ble", 0),
      word("awful", "/ˈɔː.fəl/", "kinh khủng", "I feel awful. I think I have flu.", "aw|ful", 0),
      word("strange", "/streɪndʒ/", "lạ", "I heard a strange noise last night.", "strange", 0),
      word("glad", "/ɡlæd/", "vui, mừng", "I'm glad you came.", "glad", 0),
      word("rude", "/ruːd/", "thô lỗ", "It's rude to talk with your mouth full.", "rude", 0),
      word("lazy", "/ˈleɪ.zi/", "lười", "My cat is very lazy.", "la|zy", 0),
      word("stupid", "/ˈstjuː.pɪd/", "ngốc", "That was a stupid mistake.", "stu|pid", 0),
      word("honest", "/ˈɒn.ɪst/", "trung thực", "Please be honest with me.", "hon|est", 0, "h không đọc: /ˈɒn.ɪst/"),
      word("careful", "/ˈkeə.fəl/", "cẩn thận", "Be careful! The floor is wet.", "care|ful", 0),
      word("brave", "/breɪv/", "dũng cảm", "The firefighter was very brave.", "brave", 0),
      word("serious", "/ˈsɪə.ri.əs/", "nghiêm túc", "Our teacher looks serious, but she's very kind.", "se|ri|ous", 0),
      word("cheerful", "/ˈtʃɪə.fəl/", "vui vẻ", "She is always cheerful in the morning.", "cheer|ful", 0),
      word("helpful", "/ˈhelp.fəl/", "hay giúp đỡ", "The staff were very helpful.", "help|ful", 0),
      word("surprise", "/səˈpraɪz/", "điều bất ngờ", "What a nice surprise!", "sur|prise", 1),
      word("fair", "/feə/", "(tóc) vàng nhạt; (da) sáng", "She has fair hair and blue eyes.", "fair", 0),
      word("blonde", "/blɒnd/", "(tóc) vàng", "Her sister has long blonde hair.", "blonde", 0),
      word("ugly", "/ˈʌɡ.li/", "xấu xí", "I think that building is ugly.", "ug|ly", 0),
      word("good-looking", "/ˌɡʊdˈlʊk.ɪŋ/", "ưa nhìn, đẹp", "Her brother is very good-looking.", "good|look|ing", 1),
      word("moustache", "/məˈstɑːʃ/", "ria mép", "My grandfather has a grey moustache.", "mous|tache", 1, "Anh-Anh nhấn âm 2: /məˈstɑːʃ/"),
      word("silly", "/ˈsɪl.i/", "ngớ ngẩn", "Don't be silly!", "sil|ly", 0),
    ],
  },
];

export default topics;
