import { word } from "../builders";
import type { WordTopic } from "../types";

/** Extra B1 vocabulary by topic, reviewed with spaced repetition (see /tu-vung). */
const topics: WordTopic[] = [
  {
    id: "giao-duc",
    title: "Giáo dục và học tập",
    words: [
      word("attend", "/əˈtend/", "tham dự, theo học", "More than two thousand students attend this school.", "at|tend", 1, "Trọng âm ở âm sau: ə-TEND. Nhớ bật âm /d/ ở cuối."),
      word("assignment", "/əˈsaɪn.mənt/", "bài tập được giao", "I have to finish my history assignment by Friday.", "as|sign|ment", 1, "Chữ g không đọc: ə-SAIN-mənt."),
      word("diploma", "/dɪˈpləʊ.mə/", "văn bằng, bằng tốt nghiệp", "He studied for a diploma in nursing.", "di|plo|ma", 1),
      word("grade", "/ɡreɪd/", "điểm số", "She got good grades in all her exams.", "grade", 0),
      word("lecture", "/ˈlek.tʃə/", "bài giảng (ở đại học)", "The lecture starts at nine, so don't be late.", "lec|ture", 0),
      word("tutor", "/ˈtʃuː.tə/", "gia sư; giảng viên hướng dẫn", "My parents found me a maths tutor.", "tu|tor", 0),
      word("semester", "/sɪˈmes.tə/", "học kỳ (ở đại học)", "I'm taking four courses this semester.", "se|mes|ter", 1),
      word("campus", "/ˈkæm.pəs/", "khuôn viên trường", "Most first-year students live on campus.", "cam|pus", 0),
      word("concentrate", "/ˈkɒn.sən.treɪt/", "tập trung", "I can't concentrate when the TV is on.", "con|cen|trate", 0, "Trọng âm ở âm đầu: KON-sən-treɪt."),
      word("memorise", "/ˈmem.ə.raɪz/", "học thuộc lòng", "I try to memorise ten new words every day.", "mem|o|rise", 0),
      word("instruction", "/ɪnˈstrʌk.ʃən/", "lời hướng dẫn, chỉ dẫn", "Read the instructions carefully before you start.", "in|struc|tion", 1),
      word("private", "/ˈpraɪ.vət/", "tư thục; riêng tư", "They send their children to a private school.", "pri|vate", 0, "Âm cuối đọc là /vət/, không phải /veɪt/: PRAI-vət."),
      word("cheat", "/tʃiːt/", "gian lận, quay cóp", "He was caught cheating in the exam.", "cheat", 0),
      word("intelligent", "/ɪnˈtel.ɪ.dʒənt/", "thông minh", "She's an intelligent student who learns quickly.", "in|tel|li|gent", 1),
      word("method", "/ˈmeθ.əd/", "phương pháp", "What's the best method for learning new words?", "meth|od", 0, "Âm th là /θ/: đặt đầu lưỡi giữa hai hàm răng, không đọc thành /t/."),
      word("experiment", "/ɪkˈsper.ɪ.mənt/", "thí nghiệm", "We did an experiment with water and salt in class.", "ex|per|i|ment", 1),
      word("laboratory", "/ləˈbɒr.ə.tər.i/", "phòng thí nghiệm", "The science laboratory is on the second floor.", "la|bor|a|to|ry", 1, "Anh-Anh nhấn âm thứ hai: lə-BOR-ə-tri. Thường nói tắt là lab."),
      word("textbook", "/ˈtekst.bʊk/", "sách giáo khoa", "Open your textbooks at page forty-five.", "text|book", 0),
      word("absent", "/ˈæb.sənt/", "vắng mặt", "Three students were absent from class today.", "ab|sent", 0),
      word("punish", "/ˈpʌn.ɪʃ/", "phạt, trừng phạt", "The teacher punished him for being rude.", "pun|ish", 0),
      word("encourage", "/ɪnˈkʌr.ɪdʒ/", "khuyến khích, động viên", "My parents always encouraged me to read.", "en|cour|age", 1, "Chữ ou đọc là /ʌ/: in-KA-rɪdʒ."),
      word("enrol", "/ɪnˈrəʊl/", "đăng ký học, ghi danh", "I've enrolled on an evening course in photography.", "en|rol", 1),
      word("professor", "/prəˈfes.ə/", "giáo sư", "Professor Brown teaches chemistry at the university.", "pro|fes|sor", 1),
      word("presentation", "/ˌprez.ənˈteɪ.ʃən/", "bài thuyết trình", "I have to give a presentation to the whole class.", "pres|en|ta|tion", 2),
      word("summary", "/ˈsʌm.ər.i/", "bản tóm tắt", "Write a short summary of the story.", "sum|ma|ry", 0),
      word("progress", "/ˈprəʊ.ɡres/", "sự tiến bộ", "You've made great progress this term.", "prog|ress", 0),
      word("graduation", "/ˌɡrædʒ.uˈeɪ.ʃən/", "lễ tốt nghiệp; sự tốt nghiệp", "My whole family came to my graduation.", "grad|u|a|tion", 2),
      word("revision", "/rɪˈvɪʒ.ən/", "sự ôn tập", "I'm doing a lot of revision for my exams.", "re|vi|sion", 1, "Âm /ʒ/ ở giữa: ri-VIʒ-ən. Người Anh dùng revision cho việc ôn thi."),
      word("qualify", "/ˈkwɒl.ɪ.faɪ/", "đủ tiêu chuẩn; lấy được bằng", "She qualified as a doctor last year.", "qual|i|fy", 0),
      word("explanation", "/ˌek.spləˈneɪ.ʃən/", "lời giải thích", "The teacher gave a clear explanation of the rule.", "ex|pla|na|tion", 2),
      word("definition", "/ˌdef.ɪˈnɪʃ.ən/", "định nghĩa", "Look up the definition in your dictionary.", "def|i|ni|tion", 2),
      word("handwriting", "/ˈhændˌraɪ.tɪŋ/", "chữ viết tay", "I can't read your handwriting.", "hand|writ|ing", 0),
      word("beginner", "/bɪˈɡɪn.ə/", "người mới bắt đầu", "This course is for complete beginners.", "be|gin|ner", 1),
      word("intermediate", "/ˌɪn.təˈmiː.di.ət/", "trung cấp", "I'm in the intermediate class now.", "in|ter|me|di|ate", 2),
    ],
  },
  {
    id: "phim-anh-va-sach",
    title: "Phim ảnh, sách và văn học",
    words: [
      word("plot", "/plɒt/", "cốt truyện", "The film has a very simple plot.", "plot", 0),
      word("character", "/ˈkær.ək.tə/", "nhân vật", "Who is the main character in the book?", "char|ac|ter", 0, "Chữ ch đọc là /k/: KA-rək-tə."),
      word("scene", "/siːn/", "cảnh (phim, kịch)", "The last scene of the film made me cry.", "scene", 0, "Chữ c không đọc: /siːn/, giống hệt seen."),
      word("script", "/skrɪpt/", "kịch bản", "The actors are reading the script for the first time.", "script", 0, "Cụm /skr/ ở đầu và /pt/ ở cuối: đừng chèn thêm nguyên âm."),
      word("thriller", "/ˈθrɪl.ə/", "phim, truyện ly kỳ giật gân", "I love watching thrillers late at night.", "thril|ler", 0),
      word("horror", "/ˈhɒr.ə/", "(thể loại) kinh dị", "I never watch horror films on my own.", "hor|ror", 0),
      word("documentary", "/ˌdɒk.jəˈmen.tər.i/", "phim tài liệu", "We watched a documentary about elephants.", "doc|u|men|ta|ry", 2),
      word("animation", "/ˌæn.ɪˈmeɪ.ʃən/", "phim hoạt hình; hoạt họa", "Pixar is famous for its animations.", "an|i|ma|tion", 2),
      word("talent", "/ˈtæl.ənt/", "tài năng, năng khiếu", "She has a real talent for music.", "tal|ent", 0),
      word("review", "/rɪˈvjuː/", "bài phê bình, bài đánh giá", "The film got very good reviews.", "re|view", 1),
      word("performance", "/pəˈfɔː.məns/", "màn trình diễn; diễn xuất", "Her performance in the film was amazing.", "per|for|mance", 1),
      word("entertainment", "/ˌen.təˈteɪn.mənt/", "sự giải trí", "There isn't much entertainment in this small town.", "en|ter|tain|ment", 2),
      word("poet", "/ˈpəʊ.ɪt/", "nhà thơ", "Nguyen Du is one of Vietnam's most famous poets.", "po|et", 0),
      word("poetry", "/ˈpəʊ.ɪ.tri/", "thơ ca", "I don't read much poetry.", "po|et|ry", 0),
      word("fiction", "/ˈfɪk.ʃən/", "truyện hư cấu", "I prefer fiction to books about real life.", "fic|tion", 0),
      word("literature", "/ˈlɪt.rə.tʃə/", "văn học", "She studied English literature at university.", "lit|era|ture", 0),
      word("chapter", "/ˈtʃæp.tə/", "chương (sách)", "Read chapter three before the next lesson.", "chap|ter", 0),
      word("publish", "/ˈpʌb.lɪʃ/", "xuất bản", "Her first book was published in 2019.", "pub|lish", 0),
      word("biography", "/baɪˈɒɡ.rə.fi/", "tiểu sử", "I'm reading a biography of Steve Jobs.", "bi|og|ra|phy", 1),
      word("romantic", "/rəʊˈmæn.tɪk/", "lãng mạn", "It's a romantic story about two students in Paris.", "ro|man|tic", 1),
      word("ending", "/ˈen.dɪŋ/", "đoạn kết", "I didn't like the ending of the book.", "end|ing", 0),
      word("hero", "/ˈhɪə.rəʊ/", "người hùng; nhân vật chính", "The hero of the story is a young farmer.", "he|ro", 0),
      word("imagination", "/ɪˌmædʒ.ɪˈneɪ.ʃən/", "trí tưởng tượng", "Reading helps children develop their imagination.", "i|mag|i|na|tion", 3),
      word("series", "/ˈsɪə.riːz/", "loạt phim, bộ truyện", "Have you seen the new Netflix series?", "se|ries", 0, "Hai âm tiết: SIə-riːz. Số ít và số nhiều viết giống nhau."),
      word("episode", "/ˈep.ɪ.səʊd/", "tập (phim)", "I watched three episodes last night.", "ep|i|sode", 0),
      word("studio", "/ˈstjuː.di.əʊ/", "trường quay, phòng thu", "The film was made in a studio in London.", "stu|di|o", 0),
      word("stage", "/steɪdʒ/", "sân khấu", "The band came onto the stage at nine.", "stage", 0, "Âm cuối là /dʒ/: đừng bỏ mất hay đọc thành /s/."),
      word("musical", "/ˈmjuː.zɪ.kəl/", "vở nhạc kịch", "We saw a musical in London's West End.", "mu|si|cal", 0),
      word("moving", "/ˈmuː.vɪŋ/", "cảm động", "It's a very moving film about a family in the war.", "mov|ing", 0),
      word("scary", "/ˈskeə.ri/", "đáng sợ", "The film was so scary that I couldn't sleep.", "scar|y", 0),
      word("clap", "/klæp/", "vỗ tay", "Everyone clapped at the end of the show.", "clap", 0),
      word("role", "/rəʊl/", "vai diễn; vai trò", "She plays the role of a young doctor.", "role", 0),
      word("award", "/əˈwɔːd/", "giải thưởng", "The film won three awards.", "a|ward", 1, "Cụm war đọc là /wɔː/, âm cuối /d/: ə-WAWD, không đọc âm r."),
      word("perform", "/pəˈfɔːm/", "biểu diễn", "The band will perform in Hanoi next month.", "per|form", 1),
      word("mystery", "/ˈmɪs.tər.i/", "điều bí ẩn; truyện trinh thám", "She loves reading murder mysteries.", "mys|ter|y", 0),
    ],
  },
  {
    id: "tin-tuc-va-truyen-thong",
    title: "Tin tức, truyền thông và thời sự",
    words: [
      word("headline", "/ˈhed.laɪn/", "tiêu đề (báo)", "I only read the headlines this morning.", "head|line", 0),
      word("advertise", "/ˈæd.və.taɪz/", "quảng cáo (động từ)", "The company advertises on social media.", "ad|ver|tise", 0),
      word("press", "/pres/", "báo chí", "The minister refused to talk to the press.", "press", 0),
      word("presenter", "/prɪˈzen.tə/", "người dẫn chương trình", "She's a presenter on a morning TV show.", "pre|sent|er", 1),
      word("reporter", "/rɪˈpɔː.tə/", "phóng viên", "A reporter asked him about the accident.", "re|port|er", 1),
      word("editor", "/ˈed.ɪ.tə/", "biên tập viên", "The editor decided to change the headline.", "ed|i|tor", 0),
      word("current", "/ˈkʌr.ənt/", "hiện tại, hiện hành", "I like reading about current affairs.", "cur|rent", 0),
      word("politics", "/ˈpɒl.ə.tɪks/", "chính trị", "My dad loves talking about politics.", "pol|i|tics", 0, "Trọng âm ở âm đầu: POL-ə-tɪks; còn political lại nhấn âm thứ hai."),
      word("political", "/pəˈlɪt.ɪ.kəl/", "(thuộc) chính trị", "There are two main political parties.", "po|lit|i|cal", 1),
      word("politician", "/ˌpɒl.ɪˈtɪʃ.ən/", "chính trị gia", "Many people don't trust politicians.", "pol|i|ti|cian", 2),
      word("election", "/ɪˈlek.ʃən/", "cuộc bầu cử", "The next election is in May.", "e|lec|tion", 1),
      word("vote", "/vəʊt/", "bỏ phiếu", "You can vote when you're eighteen.", "vote", 0, "Âm /v/: răng trên chạm nhẹ môi dưới, khác với /w/."),
      word("president", "/ˈprez.ɪ.dənt/", "tổng thống; chủ tịch", "The president gave a speech on TV.", "pres|i|dent", 0),
      word("protest", "/ˈprəʊ.test/", "cuộc biểu tình, sự phản đối", "Thousands of people joined the protest.", "pro|test", 0),
      word("population", "/ˌpɒp.jəˈleɪ.ʃən/", "dân số", "The population of Hanoi is over eight million.", "pop|u|la|tion", 2),
      word("society", "/səˈsaɪ.ə.ti/", "xã hội", "Old people play an important role in our society.", "so|ci|e|ty", 1),
      word("public", "/ˈpʌb.lɪk/", "công cộng; công chúng", "Smoking is not allowed in public places.", "pub|lic", 0),
      word("international", "/ˌɪn.təˈnæʃ.ən.əl/", "quốc tế", "Noi Bai is an international airport.", "in|ter|na|tion|al", 2),
      word("national", "/ˈnæʃ.ən.əl/", "(thuộc) quốc gia", "Pho is Vietnam's national dish.", "na|tion|al", 0, "Chữ a đầu đọc là /æ/: NÆ-shə-nəl, không đọc thành 'nây'."),
      word("war", "/wɔː/", "chiến tranh", "My grandfather fought in the war.", "war", 0),
      word("peace", "/piːs/", "hòa bình", "Everyone wants to live in peace.", "peace", 0),
      word("rescue", "/ˈres.kjuː/", "cứu, giải cứu", "Firefighters rescued a family from the burning house.", "res|cue", 0),
      word("survive", "/səˈvaɪv/", "sống sót", "Only two people survived the crash.", "sur|vive", 1),
      word("celebrity", "/səˈleb.rə.ti/", "người nổi tiếng", "The magazine is full of celebrity news.", "ce|leb|ri|ty", 1),
      word("media", "/ˈmiː.di.ə/", "truyền thông", "The media often make stories sound worse than they are.", "me|di|a", 0),
      word("latest", "/ˈleɪ.tɪst/", "mới nhất", "Have you heard the latest news?", "lat|est", 0),
      word("situation", "/ˌsɪtʃ.uˈeɪ.ʃən/", "tình hình, tình huống", "The situation in the city is getting better.", "sit|u|a|tion", 3),
      word("discussion", "/dɪˈskʌʃ.ən/", "cuộc thảo luận", "We had a long discussion about the news.", "dis|cus|sion", 1),
      word("royal", "/ˈrɔɪ.əl/", "(thuộc) hoàng gia", "The royal wedding was shown on TV all over the world.", "roy|al", 0),
      word("announcement", "/əˈnaʊns.mənt/", "thông báo", "The government made an important announcement today.", "an|nounce|ment", 1),
      word("charity", "/ˈtʃær.ə.ti/", "tổ chức từ thiện", "We raised money for a children's charity.", "char|i|ty", 0),
      word("tradition", "/trəˈdɪʃ.ən/", "truyền thống", "Giving lucky money at Tet is an old tradition.", "tra|di|tion", 1),
      word("religion", "/rɪˈlɪdʒ.ən/", "tôn giáo", "People of every religion live in this city.", "re|li|gion", 1),
      word("ceremony", "/ˈser.ɪ.mə.ni/", "nghi lễ, buổi lễ", "The wedding ceremony was very beautiful.", "cer|e|mo|ny", 0),
      word("reader", "/ˈriː.də/", "độc giả, người đọc", "The newspaper has over a million readers.", "read|er", 0),
    ],
  },
  {
    id: "moi-truong",
    title: "Môi trường và thiên nhiên",
    words: [
      word("pollution", "/pəˈluː.ʃən/", "sự ô nhiễm", "Air pollution is a big problem in many cities.", "pol|lu|tion", 1),
      word("waste", "/weɪst/", "lãng phí; rác thải", "Don't waste water when you brush your teeth.", "waste", 0, "Giữ rõ cụm /st/ ở cuối."),
      word("plastic", "/ˈplæs.tɪk/", "nhựa", "Try not to use plastic bags.", "plas|tic", 0, "Trọng âm ở âm đầu: PLÆS-tɪk; nhớ đọc cả âm /s/."),
      word("global", "/ˈɡləʊ.bəl/", "toàn cầu", "Global warming is changing our weather.", "glo|bal", 0),
      word("energy", "/ˈen.ə.dʒi/", "năng lượng", "We should use less energy at home.", "en|er|gy", 0),
      word("solar", "/ˈsəʊ.lə/", "(thuộc) mặt trời", "Our school has solar panels on the roof.", "so|lar", 0),
      word("fuel", "/ˈfjuː.əl/", "nhiên liệu", "Cars that use less fuel are better for the planet.", "fu|el", 0),
      word("power", "/ˈpaʊ.ə/", "điện; năng lượng", "The storm cut off the power for six hours.", "pow|er", 0),
      word("natural", "/ˈnætʃ.ər.əl/", "tự nhiên", "Wind and sun are natural sources of energy.", "nat|u|ral", 0),
      word("wildlife", "/ˈwaɪld.laɪf/", "động vật hoang dã", "The park is home to a lot of wildlife.", "wild|life", 0),
      word("protect", "/prəˈtekt/", "bảo vệ", "We must protect the forests.", "pro|tect", 1),
      word("destroy", "/dɪˈstrɔɪ/", "phá hủy", "The fire destroyed hundreds of trees.", "de|stroy", 1),
      word("earthquake", "/ˈɜːθ.kweɪk/", "động đất", "The earthquake damaged many buildings.", "earth|quake", 0, "Âm /ɜː/ như trong bird, th là /θ/: ERTH-kweɪk."),
      word("hurricane", "/ˈhʌr.ɪ.kən/", "bão lớn, cuồng phong", "The hurricane hit the coast last night.", "hur|ri|cane", 0),
      word("disaster", "/dɪˈzɑː.stə/", "thảm họa", "The flood was the worst natural disaster in years.", "dis|as|ter", 1),
      word("chemical", "/ˈkem.ɪ.kəl/", "hóa chất", "Farmers use chemicals to protect their crops.", "chem|i|cal", 0, "Chữ ch đọc là /k/: KEM-ɪ-kəl."),
      word("reuse", "/ˌriːˈjuːz/", "tái sử dụng", "You can reuse these bags many times.", "re|use", 1),
      word("litter", "/ˈlɪt.ə/", "rác vứt bừa bãi", "There was litter all over the beach.", "lit|ter", 0),
      word("reduce", "/rɪˈdʒuːs/", "giảm", "We need to reduce the amount of rubbish we throw away.", "re|duce", 1),
      word("increase", "/ɪnˈkriːs/", "tăng", "The number of cars has increased a lot.", "in|crease", 1, "Động từ nhấn âm sau (in-KREES), danh từ nhấn âm đầu (IN-krees)."),
      word("oxygen", "/ˈɒk.sɪ.dʒən/", "khí ô-xy", "Trees produce oxygen.", "ox|y|gen", 0),
      word("gas", "/ɡæs/", "khí; khí đốt", "Cars produce gases that are bad for the air.", "gas", 0),
      word("environmental", "/ɪnˌvaɪ.rənˈmen.təl/", "(thuộc) môi trường", "Plastic waste is a serious environmental problem.", "en|vi|ron|men|tal", 3),
      word("harmful", "/ˈhɑːm.fəl/", "có hại", "Too much sun can be harmful to your skin.", "harm|ful", 0),
      word("species", "/ˈspiː.ʃiːz/", "loài", "Many species of birds live in this forest.", "spe|cies", 0, "Đọc là SPEE-shiːz. Số ít và số nhiều viết giống nhau."),
      word("volcano", "/vɒlˈkeɪ.nəʊ/", "núi lửa", "The volcano erupted last year.", "vol|ca|no", 1),
      word("soil", "/sɔɪl/", "đất trồng", "The soil here is good for growing coffee.", "soil", 0),
      word("crop", "/krɒp/", "cây trồng; vụ mùa", "Rice is the main crop in the Mekong Delta.", "crop", 0),
      word("rainforest", "/ˈreɪn.fɒr.ɪst/", "rừng mưa nhiệt đới", "The Amazon rainforest is getting smaller every year.", "rain|for|est", 0),
      word("humid", "/ˈhjuː.mɪd/", "ẩm ướt, oi bức", "Hanoi is hot and humid in summer.", "hu|mid", 0),
      word("breeze", "/briːz/", "gió nhẹ", "There's a cool breeze from the sea.", "breeze", 0),
      word("shade", "/ʃeɪd/", "bóng râm", "Let's sit in the shade of that tree.", "shade", 0),
      word("pond", "/pɒnd/", "cái ao", "There are fish in the pond behind our house.", "pond", 0),
      word("stream", "/striːm/", "dòng suối", "We crossed a small stream in the forest.", "stream", 0),
      word("waterfall", "/ˈwɔː.tə.fɔːl/", "thác nước", "Ban Gioc is a famous waterfall in Cao Bang.", "wa|ter|fall", 0),
    ],
  },
  {
    id: "cong-viec-va-nghe-nghiep",
    title: "Công việc và nghề nghiệp",
    words: [
      word("employ", "/ɪmˈplɔɪ/", "thuê, tuyển dụng", "The company employs over 500 people.", "em|ploy", 1),
      word("firm", "/fɜːm/", "công ty, hãng", "He works for a law firm in the city.", "firm", 0),
      word("industry", "/ˈɪn.də.stri/", "ngành công nghiệp", "Tourism is a very important industry for Vietnam.", "in|dus|try", 0, "Trọng âm ở âm đầu: IN-də-stri, không phải in-DUS-try."),
      word("profession", "/prəˈfeʃ.ən/", "nghề (chuyên môn)", "Teaching is a difficult but rewarding profession.", "pro|fes|sion", 1),
      word("professional", "/prəˈfeʃ.ən.əl/", "chuyên nghiệp", "You should get professional advice before you start a business.", "pro|fes|sion|al", 1),
      word("wage", "/weɪdʒ/", "tiền công (theo giờ, theo tuần)", "The minimum wage went up this year.", "wage", 0),
      word("position", "/pəˈzɪʃ.ən/", "vị trí, chức vụ", "I'm writing to apply for the position of receptionist.", "po|si|tion", 1),
      word("responsibility", "/rɪˌspɒn.səˈbɪl.ə.ti/", "trách nhiệm", "It's my responsibility to lock the office.", "re|spon|si|bil|i|ty", 4),
      word("shift", "/ʃɪft/", "ca làm việc", "She works the night shift at the hospital.", "shift", 0),
      word("organisation", "/ˌɔː.ɡən.aɪˈzeɪ.ʃən/", "tổ chức", "She works for a charity organisation.", "or|gan|i|sa|tion", 3),
      word("successful", "/səkˈses.fəl/", "thành công", "He runs a successful business.", "suc|cess|ful", 1),
      word("electrician", "/ˌel.ɪkˈtrɪʃ.ən/", "thợ điện", "We need an electrician to fix the lights.", "e|lec|tri|cian", 2),
      word("architect", "/ˈɑː.kɪ.tekt/", "kiến trúc sư", "An architect designed our new house.", "ar|chi|tect", 0, "Chữ ch đọc là /k/: AA-kɪ-tekt."),
      word("plumber", "/ˈplʌm.ə/", "thợ sửa ống nước", "Call a plumber because the kitchen tap is leaking.", "plumb|er", 0, "Chữ b không đọc: PLAM-ə."),
      word("volunteer", "/ˌvɒl.ənˈtɪə/", "tình nguyện viên", "She works as a volunteer at the hospital.", "vol|un|teer", 2),
      word("expert", "/ˈek.spɜːt/", "chuyên gia", "He's an expert in computer security.", "ex|pert", 0),
      word("application", "/ˌæp.lɪˈkeɪ.ʃən/", "đơn xin (việc, học)", "I sent my application last week.", "ap|pli|ca|tion", 2),
      word("skilled", "/skɪld/", "có tay nghề", "There aren't enough skilled workers.", "skilled", 0),
      word("experienced", "/ɪkˈspɪə.ri.ənst/", "có kinh nghiệm", "We're looking for an experienced driver.", "ex|pe|ri|enced", 1),
      word("instructor", "/ɪnˈstrʌk.tə/", "người hướng dẫn, huấn luyện viên", "My driving instructor never gets angry.", "in|struc|tor", 1),
      word("produce", "/prəˈdʒuːs/", "sản xuất", "The factory produces 200 cars a day.", "pro|duce", 1),
      word("product", "/ˈprɒd.ʌkt/", "sản phẩm", "Our products are sold all over the world.", "prod|uct", 0),
      word("client", "/ˈklaɪ.ənt/", "khách hàng (của dịch vụ)", "I'm meeting a client this afternoon.", "cli|ent", 0),
      word("builder", "/ˈbɪl.də/", "thợ xây", "The builders are working on our new kitchen.", "build|er", 0, "Chữ ui đọc là /ɪ/: BIL-də."),
      word("pharmacist", "/ˈfɑː.mə.sɪst/", "dược sĩ", "Ask the pharmacist which medicine is best.", "phar|ma|cist", 0, "Chữ ph đọc là /f/, chữ c đọc là /s/: FAA-mə-sist."),
      word("translator", "/trænzˈleɪ.tə/", "biên dịch viên", "She works as a translator for a Japanese company.", "trans|la|tor", 1),
      word("branch", "/brɑːntʃ/", "chi nhánh", "The bank has a branch near my office.", "branch", 0),
      word("promote", "/prəˈməʊt/", "thăng chức", "She was promoted to manager last year.", "pro|mote", 1),
      word("management", "/ˈmæn.ɪdʒ.mənt/", "sự quản lý; ban quản lý", "The hotel is under new management.", "man|age|ment", 0),
      word("leader", "/ˈliː.də/", "người lãnh đạo, trưởng nhóm", "She's the leader of our team.", "lead|er", 0),
      word("achievement", "/əˈtʃiːv.mənt/", "thành tích, thành tựu", "Getting this job was a great achievement.", "a|chieve|ment", 1),
      word("ability", "/əˈbɪl.ə.ti/", "khả năng", "He has the ability to explain things clearly.", "a|bil|i|ty", 1),
      word("employment", "/ɪmˈplɔɪ.mənt/", "việc làm", "It's hard to find employment in small towns.", "em|ploy|ment", 1),
      word("strike", "/straɪk/", "cuộc đình công", "The workers went on strike for better pay.", "strike", 0),
      word("retirement", "/rɪˈtaɪə.mənt/", "sự nghỉ hưu", "My father is enjoying his retirement.", "re|tire|ment", 1),
    ],
  },
  {
    id: "quan-he-va-cam-xuc",
    title: "Các mối quan hệ và cảm xúc",
    words: [
      word("partner", "/ˈpɑːt.nə/", "bạn đời, người yêu", "You can bring your partner to the party.", "part|ner", 0),
      word("engaged", "/ɪnˈɡeɪdʒd/", "đã đính hôn", "They got engaged last summer.", "en|gaged", 1),
      word("divorce", "/dɪˈvɔːs/", "ly hôn", "His parents got divorced when he was ten.", "di|vorce", 1),
      word("marriage", "/ˈmær.ɪdʒ/", "hôn nhân", "They've had a happy marriage for forty years.", "mar|riage", 0, "Chỉ có hai âm tiết: MÆ-rɪdʒ."),
      word("trust", "/trʌst/", "tin tưởng", "I trust my best friend completely.", "trust", 0),
      word("respect", "/rɪˈspekt/", "tôn trọng", "Children should respect their grandparents.", "re|spect", 1),
      word("support", "/səˈpɔːt/", "ủng hộ, hỗ trợ", "My family supported me when I lost my job.", "sup|port", 1),
      word("argue", "/ˈɑːɡ.juː/", "cãi nhau, tranh cãi", "My brother and I often argue about small things.", "ar|gue", 0),
      word("forgive", "/fəˈɡɪv/", "tha thứ", "Please forgive me. I didn't mean it.", "for|give", 1),
      word("jealous", "/ˈdʒel.əs/", "ghen tị, ghen", "He gets jealous when she talks to other boys.", "jeal|ous", 0, "Chữ ea đọc là /e/: JEL-əs."),
      word("embarrassed", "/ɪmˈbær.əst/", "ngượng, xấu hổ", "I was so embarrassed when I fell over.", "em|bar|rassed", 1, "Đuôi -ed đọc là /t/: im-BÆ-rəst."),
      word("anxious", "/ˈæŋk.ʃəs/", "lo lắng, bồn chồn", "I always feel anxious before exams.", "anx|ious", 0, "Chữ x ở đây đọc là /kʃ/: ÆNGK-shəs."),
      word("upset", "/ʌpˈset/", "buồn bực, khó chịu", "She was upset because nobody remembered her birthday.", "up|set", 1),
      word("proud", "/praʊd/", "tự hào", "My parents are very proud of me.", "proud", 0),
      word("grateful", "/ˈɡreɪt.fəl/", "biết ơn", "I'm really grateful for your help.", "grate|ful", 0),
      word("confused", "/kənˈfjuːzd/", "bối rối", "I'm confused. Can you explain it again?", "con|fused", 1),
      word("curious", "/ˈkjʊə.ri.əs/", "tò mò", "Children are curious about everything.", "cu|ri|ous", 0),
      word("satisfied", "/ˈsæt.ɪs.faɪd/", "hài lòng", "Are you satisfied with the service?", "sat|is|fied", 0),
      word("delighted", "/dɪˈlaɪ.tɪd/", "rất vui mừng", "We were delighted to hear your good news.", "de|light|ed", 1),
      word("miserable", "/ˈmɪz.ər.ə.bəl/", "khổ sở, buồn thảm", "I felt miserable when I was ill in bed.", "mis|er|a|ble", 0),
      word("emotion", "/ɪˈməʊ.ʃən/", "cảm xúc", "He doesn't often show his emotions.", "e|mo|tion", 1),
      word("mood", "/muːd/", "tâm trạng", "You're in a good mood today!", "mood", 0),
      word("fear", "/fɪə/", "nỗi sợ", "She has a fear of flying.", "fear", 0),
      word("pleasure", "/ˈpleʒ.ə/", "niềm vui, sự hân hạnh", "It's a pleasure to meet you.", "pleas|ure", 0, "Âm /ʒ/ ở giữa: PLEʒ-ə, không đọc thành /s/ hay /z/."),
      word("tear", "/tɪə/", "nước mắt", "There were tears in her eyes.", "tear", 0, "Nghĩa nước mắt đọc là /tɪə/; động từ xé (tear) đọc là /teə/."),
      word("flatmate", "/ˈflæt.meɪt/", "bạn cùng căn hộ", "My flatmate never does the washing-up.", "flat|mate", 0),
      word("stranger", "/ˈstreɪn.dʒə/", "người lạ", "Never get into a car with a stranger.", "stran|ger", 0),
      word("amazed", "/əˈmeɪzd/", "kinh ngạc", "I was amazed by how well she sings.", "a|mazed", 1),
      word("bride", "/braɪd/", "cô dâu", "The bride wore a red ao dai.", "bride", 0),
      word("honeymoon", "/ˈhʌn.i.muːn/", "tuần trăng mật", "They went to Phu Quoc for their honeymoon.", "hon|ey|moon", 0, "Chữ o đầu đọc là /ʌ/: HAN-i-muːn."),
      word("anger", "/ˈæŋ.ɡə/", "sự tức giận", "He couldn't hide his anger.", "an|ger", 0),
      word("happiness", "/ˈhæp.i.nəs/", "niềm hạnh phúc", "Money doesn't always bring happiness.", "hap|pi|ness", 0),
      word("terrified", "/ˈter.ə.faɪd/", "vô cùng sợ hãi", "I'm terrified of snakes.", "ter|ri|fied", 0),
      word("shocked", "/ʃɒkt/", "bị sốc, bàng hoàng", "We were shocked by the news.", "shocked", 0, "Đuôi -ed đọc là /t/: /ʃɒkt/."),
      word("furious", "/ˈfjʊə.ri.əs/", "giận dữ", "My mum was furious when I came home late.", "fu|ri|ous", 0),
    ],
  },
  {
    id: "tinh-cach",
    title: "Tính cách và thái độ",
    words: [
      word("personality", "/ˌpɜː.sənˈæl.ə.ti/", "tính cách", "She has a strong personality.", "per|son|al|i|ty", 2),
      word("attitude", "/ˈæt.ɪ.tʃuːd/", "thái độ", "He has a very positive attitude to work.", "at|ti|tude", 0),
      word("behaviour", "/bɪˈheɪ.vjə/", "cách cư xử, hành vi", "The children's behaviour was excellent.", "be|hav|iour", 1),
      word("generous", "/ˈdʒen.ər.əs/", "hào phóng", "It was generous of you to pay for dinner.", "gen|er|ous", 0),
      word("selfish", "/ˈsel.fɪʃ/", "ích kỷ", "Don't be so selfish. Share your sweets with your sister.", "self|ish", 0),
      word("impatient", "/ɪmˈpeɪ.ʃənt/", "thiếu kiên nhẫn", "He gets impatient when he has to wait.", "im|pa|tient", 1),
      word("sensible", "/ˈsen.sə.bəl/", "khôn ngoan, biết điều", "She's a sensible girl who never takes silly risks.", "sen|si|ble", 0, "Sensible là biết điều, khôn ngoan; nhạy cảm là sensitive."),
      word("sensitive", "/ˈsen.sɪ.tɪv/", "nhạy cảm", "He's very sensitive and cries easily.", "sen|si|tive", 0),
      word("cruel", "/ˈkruː.əl/", "độc ác, tàn nhẫn", "It's cruel to keep a dog in a small cage.", "cru|el", 0),
      word("reasonable", "/ˈriː.zən.ə.bəl/", "hợp lý, biết lý lẽ", "My boss is strict but reasonable.", "rea|son|a|ble", 0),
      word("easy-going", "/ˌiː.ziˈɡəʊ.ɪŋ/", "dễ tính", "My dad is very easy-going.", "ea|sy|go|ing", 2),
      word("determined", "/dɪˈtɜː.mɪnd/", "quyết tâm", "She was determined to pass the exam.", "de|ter|mined", 1, "Đuôi -mined đọc là /mɪnd/, không phải /maɪnd/."),
      word("independent", "/ˌɪn.dɪˈpen.dənt/", "độc lập", "She's very independent and lives on her own.", "in|de|pend|ent", 2),
      word("creative", "/kriˈeɪ.tɪv/", "sáng tạo", "Children are often very creative.", "cre|a|tive", 1),
      word("strict", "/strɪkt/", "nghiêm khắc", "Our maths teacher is very strict.", "strict", 0, "Cụm /str/ ở đầu và /kt/ ở cuối: đừng chèn thêm nguyên âm."),
      word("gentle", "/ˈdʒen.təl/", "hiền lành, nhẹ nhàng", "He's a gentle man who loves animals.", "gen|tle", 0),
      word("talented", "/ˈtæl.ən.tɪd/", "có tài", "She's a talented young singer.", "tal|ent|ed", 0),
      word("ambitious", "/æmˈbɪʃ.əs/", "có tham vọng, có hoài bão", "He's ambitious and wants to run his own company.", "am|bi|tious", 1),
      word("bad-tempered", "/ˌbædˈtem.pəd/", "nóng tính, cáu kỉnh", "He's always bad-tempered in the morning.", "bad|tem|pered", 1),
      word("humour", "/ˈhjuː.mə/", "sự hài hước", "He has a great sense of humour.", "hu|mour", 0),
      word("calm", "/kɑːm/", "bình tĩnh", "Stay calm and listen to me.", "calm", 0, "Chữ l không đọc: /kɑːm/."),
      word("nasty", "/ˈnɑː.sti/", "xấu tính; khó chịu", "That was a nasty thing to say.", "nas|ty", 0),
      word("positive", "/ˈpɒz.ə.tɪv/", "tích cực", "Try to stay positive.", "pos|i|tive", 0),
      word("negative", "/ˈneɡ.ə.tɪv/", "tiêu cực", "Don't be so negative about everything.", "neg|a|tive", 0),
      word("modest", "/ˈmɒd.ɪst/", "khiêm tốn", "He's very modest about his success.", "mod|est", 0),
      word("clumsy", "/ˈklʌm.zi/", "vụng về", "I'm so clumsy. I've broken another glass!", "clum|sy", 0),
      word("cautious", "/ˈkɔː.ʃəs/", "thận trọng", "She's a cautious driver.", "cau|tious", 0),
      word("mean", "/miːn/", "keo kiệt; xấu tính", "Don't be mean. Lend him some money.", "mean", 0),
      word("sociable", "/ˈsəʊ.ʃə.bəl/", "hòa đồng", "She's very sociable and loves parties.", "so|cia|ble", 0),
      word("bright", "/braɪt/", "sáng dạ, thông minh", "She's a bright girl who learns very fast.", "bright", 0),
      word("hopeless", "/ˈhəʊp.ləs/", "rất kém, dở tệ (về việc gì)", "I'm hopeless at cooking.", "hope|less", 0),
      word("greedy", "/ˈɡriː.di/", "tham lam", "Don't be greedy. Leave some cake for the others.", "greed|y", 0),
      word("thoughtful", "/ˈθɔːt.fəl/", "chu đáo, ân cần", "It was thoughtful of you to call.", "thought|ful", 0, "Chữ gh không đọc, th là /θ/: THOOT-fəl."),
      word("organised", "/ˈɔː.ɡən.aɪzd/", "ngăn nắp, có tổ chức", "She's very organised and never forgets anything.", "or|gan|ised", 0),
    ],
  },
  {
    id: "du-lich-va-cho-o",
    title: "Du lịch, đi lại và chỗ ở",
    words: [
      word("accommodation", "/əˌkɒm.əˈdeɪ.ʃən/", "chỗ ở", "The price includes flights and accommodation.", "ac|com|mo|da|tion", 3, "Viết hai chữ c, hai chữ m. Trọng âm ở -DEI-: ə-kom-ə-DEI-shən."),
      word("reservation", "/ˌrez.əˈveɪ.ʃən/", "sự đặt chỗ", "I'd like to make a reservation for two nights.", "res|er|va|tion", 2),
      word("reserve", "/rɪˈzɜːv/", "đặt trước", "I've reserved a table for four.", "re|serve", 1),
      word("facility", "/fəˈsɪl.ə.ti/", "tiện nghi, cơ sở vật chất", "The hotel has excellent sports facilities.", "fa|cil|i|ty", 1),
      word("destination", "/ˌdes.tɪˈneɪ.ʃən/", "điểm đến", "Da Nang is a popular holiday destination.", "des|ti|na|tion", 2),
      word("traveller", "/ˈtræv.əl.ə/", "du khách, người đi xa", "The hostel is popular with young travellers.", "trav|el|ler", 0),
      word("board", "/bɔːd/", "lên (tàu, xe, máy bay)", "Passengers can now board the plane.", "board", 0),
      word("customs", "/ˈkʌs.təmz/", "hải quan", "It took an hour to get through customs.", "cus|toms", 0),
      word("border", "/ˈbɔː.də/", "biên giới", "We crossed the border into Laos.", "bor|der", 0),
      word("route", "/ruːt/", "tuyến đường, lộ trình", "What's the quickest route to the airport?", "route", 0, "Anh-Anh đọc là /ruːt/, giống root."),
      word("package", "/ˈpæk.ɪdʒ/", "trọn gói; gói hàng", "We booked a package holiday to Thailand.", "pack|age", 0),
      word("check-in", "/ˈtʃek.ɪn/", "(quầy) làm thủ tục", "Check-in opens two hours before the flight.", "check|in", 0),
      word("overnight", "/ˌəʊ.vəˈnaɪt/", "qua đêm", "We took the overnight train from Hanoi to Lao Cai.", "o|ver|night", 2),
      word("cruise", "/kruːz/", "chuyến du thuyền", "They went on a cruise around Ha Long Bay.", "cruise", 0),
      word("take-off", "/ˈteɪk.ɒf/", "sự cất cánh", "Please keep your seatbelt on during take-off.", "take|off", 0),
      word("aisle", "/aɪl/", "lối đi giữa các hàng ghế", "Would you like a window or an aisle seat?", "aisle", 0, "Chữ s không đọc: /aɪl/, giống I'll."),
      word("cabin", "/ˈkæb.ɪn/", "khoang (máy bay, tàu)", "The cabin crew will serve drinks shortly.", "cab|in", 0),
      word("parking", "/ˈpɑː.kɪŋ/", "chỗ đỗ xe; việc đỗ xe", "Is there free parking at the hotel?", "park|ing", 0),
      word("baggage", "/ˈbæɡ.ɪdʒ/", "hành lý", "Please collect your baggage from belt 3.", "bag|gage", 0),
      word("sail", "/seɪl/", "đi thuyền, đi tàu biển", "We sailed to the island in a small boat.", "sail", 0),
      word("terminal", "/ˈtɜː.mɪ.nəl/", "nhà ga (sân bay)", "International flights leave from Terminal 2.", "ter|mi|nal", 0),
      word("crew", "/kruː/", "phi hành đoàn, thủy thủ đoàn", "The crew were very helpful during the flight.", "crew", 0),
      word("duty-free", "/ˌdjuː.tiˈfriː/", "miễn thuế", "I bought some perfume in the duty-free shop.", "du|ty|free", 2),
      word("caravan", "/ˈkær.ə.væn/", "nhà lưu động (kéo sau xe)", "We spent the summer in a caravan by the sea.", "car|a|van", 0),
      word("guesthouse", "/ˈɡest.haʊs/", "nhà khách", "We stayed in a small guesthouse in Sapa.", "guest|house", 0),
      word("breakdown", "/ˈbreɪk.daʊn/", "sự hỏng xe dọc đường", "We had a breakdown on the way to the airport.", "break|down", 0),
      word("puncture", "/ˈpʌŋk.tʃə/", "lốp bị thủng", "I got a puncture on the way to work.", "punc|ture", 0),
      word("diversion", "/daɪˈvɜː.ʃən/", "đường vòng tạm thời", "There's a diversion because the bridge is closed.", "di|ver|sion", 1),
      word("roadworks", "/ˈrəʊd.wɜːks/", "công trình sửa đường", "There are roadworks on the main road, so we'll be late.", "road|works", 0),
      word("junction", "/ˈdʒʌŋk.ʃən/", "giao lộ, nút giao", "Turn left at the next junction.", "junc|tion", 0),
      word("lane", "/leɪn/", "làn đường", "Stay in the left lane.", "lane", 0),
      word("cycle", "/ˈsaɪ.kəl/", "đạp xe", "We cycled along the coast for three days.", "cy|cle", 0, "Chữ y đọc là /aɪ/: SAI-kəl."),
      word("railway", "/ˈreɪl.weɪ/", "đường sắt", "The railway station is in the centre of town.", "rail|way", 0),
      word("pedestrian", "/pəˈdes.tri.ən/", "người đi bộ", "This street is only for pedestrians.", "pe|des|tri|an", 1),
    ],
  },
  {
    id: "tien-bac-va-mua-sam",
    title: "Tiền bạc và mua sắm",
    words: [
      word("income", "/ˈɪŋ.kʌm/", "thu nhập", "Many families live on a low income.", "in|come", 0),
      word("currency", "/ˈkʌr.ən.si/", "tiền tệ", "The currency of Japan is the yen.", "cur|ren|cy", 0),
      word("rate", "/reɪt/", "tỷ giá; mức", "What's the exchange rate today?", "rate", 0),
      word("loan", "/ləʊn/", "khoản vay", "He got a bank loan to buy a car.", "loan", 0),
      word("debt", "/det/", "món nợ", "She's in debt after buying a house.", "debt", 0, "Chữ b không đọc: /det/."),
      word("owe", "/əʊ/", "nợ", "I owe you ten pounds.", "owe", 0),
      word("savings", "/ˈseɪ.vɪŋz/", "tiền tiết kiệm", "He spent all his savings on a new car.", "sav|ings", 0),
      word("tax", "/tæks/", "thuế", "Prices include tax.", "tax", 0),
      word("fee", "/fiː/", "phí, lệ phí", "The university fees are very high.", "fee", 0),
      word("charge", "/tʃɑːdʒ/", "tính phí", "They charge five dollars for delivery.", "charge", 0, "Không đọc âm r; kết thúc bằng /dʒ/: /tʃɑːdʒ/."),
      word("brand", "/brænd/", "thương hiệu", "Which brand of phone do you have?", "brand", 0),
      word("label", "/ˈleɪ.bəl/", "nhãn", "Always read the label before you buy food.", "la|bel", 0, "Chữ a đọc là /eɪ/: LEI-bəl."),
      word("checkout", "/ˈtʃek.aʊt/", "quầy thanh toán", "There was a long queue at the checkout.", "check|out", 0),
      word("goods", "/ɡʊdz/", "hàng hóa", "The shop sells electrical goods.", "goods", 0),
      word("second-hand", "/ˌsek.əndˈhænd/", "đồ cũ, đã qua sử dụng", "I bought a second-hand bike.", "sec|ond|hand", 2),
      word("worth", "/wɜːθ/", "đáng giá", "This ring is worth a lot of money.", "worth", 0, "Chữ or đọc là /ɜː/ như trong bird; âm cuối là /θ/."),
      word("payment", "/ˈpeɪ.mənt/", "sự thanh toán", "We accept payment by card.", "pay|ment", 0),
      word("credit", "/ˈkred.ɪt/", "tín dụng; trả sau", "Can I pay by credit card?", "cred|it", 0),
      word("cashpoint", "/ˈkæʃ.pɔɪnt/", "cây ATM", "Is there a cashpoint near here?", "cash|point", 0),
      word("delivery", "/dɪˈlɪv.ər.i/", "sự giao hàng", "Delivery is free for orders over 500,000 dong.", "de|liv|er|y", 1),
      word("material", "/məˈtɪə.ri.əl/", "chất liệu, vải", "What material is this dress made of?", "ma|te|ri|al", 1),
      word("complaint", "/kəmˈpleɪnt/", "lời phàn nàn, khiếu nại", "I'd like to make a complaint about the service.", "com|plaint", 1),
      word("economy", "/ɪˈkɒn.ə.mi/", "nền kinh tế", "The economy is growing fast.", "e|con|o|my", 1),
      word("profit", "/ˈprɒf.ɪt/", "lợi nhuận", "The shop made a big profit last year.", "prof|it", 0),
      word("wrap", "/ræp/", "gói (quà)", "Could you wrap it as a present, please?", "wrap", 0, "Chữ w không đọc: /ræp/."),
      word("expense", "/ɪkˈspens/", "khoản chi phí", "Rent is our biggest expense.", "ex|pense", 1),
      word("interest", "/ˈɪn.trəst/", "tiền lãi", "The bank pays 5% interest on savings.", "in|terest", 0),
      word("value", "/ˈvæl.juː/", "giá trị", "The value of the house has doubled.", "val|ue", 0),
      word("tip", "/tɪp/", "tiền boa", "We left a tip for the waiter.", "tip", 0),
      word("donate", "/dəʊˈneɪt/", "quyên góp", "She donates money to charity every month.", "do|nate", 1),
      word("fortune", "/ˈfɔː.tʃuːn/", "gia tài, khoản tiền lớn", "That car must have cost a fortune.", "for|tune", 0),
      word("luxury", "/ˈlʌk.ʃər.i/", "sang trọng, xa xỉ", "They stayed in a luxury hotel.", "lux|u|ry", 0, "Chữ x đọc là /kʃ/: LAK-shə-ri."),
      word("purchase", "/ˈpɜː.tʃəs/", "món hàng đã mua; mua", "You can return your purchase within 30 days.", "pur|chase", 0, "Âm cuối đọc là /tʃəs/, không phải /tʃeɪs/."),
      word("cashier", "/kæʃˈɪə/", "thu ngân", "Please pay the cashier.", "cash|ier", 1),
    ],
  },
  {
    id: "suc-khoe-va-loi-song",
    title: "Sức khỏe và lối sống",
    words: [
      word("symptom", "/ˈsɪmp.təm/", "triệu chứng", "What are the symptoms of flu?", "symp|tom", 0),
      word("disease", "/dɪˈziːz/", "bệnh tật", "Smoking causes heart disease.", "dis|ease", 1, "Hai chữ s đều đọc là /z/: di-ZEEZ."),
      word("painful", "/ˈpeɪn.fəl/", "đau đớn", "My foot is still painful.", "pain|ful", 0),
      word("cure", "/kjʊə/", "cách chữa; chữa khỏi", "There's no cure for the common cold.", "cure", 0),
      word("treatment", "/ˈtriːt.mənt/", "sự điều trị", "She's having treatment at the hospital.", "treat|ment", 0),
      word("operation", "/ˌɒp.əˈreɪ.ʃən/", "ca phẫu thuật", "He needs an operation on his knee.", "op|e|ra|tion", 2),
      word("blind", "/blaɪnd/", "mù", "My grandmother is almost blind.", "blind", 0),
      word("prescription", "/prɪˈskrɪp.ʃən/", "đơn thuốc", "You need a prescription for this medicine.", "pre|scrip|tion", 1),
      word("vitamin", "/ˈvɪt.ə.mɪn/", "vi-ta-min", "Oranges are full of vitamin C.", "vit|a|min", 0, "Anh-Anh đọc VIT-ə-min, âm đầu /vɪt/, không phải 'vai'."),
      word("fitness", "/ˈfɪt.nəs/", "thể lực, sự khỏe khoắn", "Swimming is great for your fitness.", "fit|ness", 0),
      word("muscle", "/ˈmʌs.əl/", "cơ bắp", "I pulled a muscle playing football.", "mus|cle", 0, "Chữ c không đọc: MAS-əl."),
      word("infection", "/ɪnˈfek.ʃən/", "sự nhiễm trùng", "The doctor gave me antibiotics for the infection.", "in|fec|tion", 1),
      word("allergic", "/əˈlɜː.dʒɪk/", "bị dị ứng", "I'm allergic to seafood.", "al|ler|gic", 1),
      word("bleed", "/bliːd/", "chảy máu", "Your finger is bleeding!", "bleed", 0),
      word("recover", "/rɪˈkʌv.ə/", "hồi phục", "It took him a month to recover from the operation.", "re|cov|er", 1),
      word("stress", "/stres/", "sự căng thẳng", "Exercise helps to reduce stress.", "stress", 0),
      word("lifestyle", "/ˈlaɪf.staɪl/", "lối sống", "She has a very healthy lifestyle.", "life|style", 0),
      word("balanced", "/ˈbæl.ənst/", "cân bằng", "Try to eat a balanced diet.", "bal|anced", 0),
      word("overweight", "/ˌəʊ.vəˈweɪt/", "thừa cân", "The doctor said I was a bit overweight.", "o|ver|weight", 2),
      word("alcohol", "/ˈæl.kə.hɒl/", "rượu bia, đồ uống có cồn", "You shouldn't drink alcohol before driving.", "al|co|hol", 0),
      word("calorie", "/ˈkæl.ər.i/", "ca-lo", "This drink has 200 calories.", "cal|o|rie", 0),
      word("clinic", "/ˈklɪn.ɪk/", "phòng khám", "There's a small clinic in our village.", "clin|ic", 0),
      word("cancer", "/ˈkæn.sə/", "bệnh ung thư", "Smoking can cause lung cancer.", "can|cer", 0),
      word("asthma", "/ˈæs.mə/", "bệnh hen suyễn", "My son has asthma, so he always carries an inhaler.", "asth|ma", 0, "Chữ th không đọc: ÆS-mə."),
      word("ankle", "/ˈæŋ.kəl/", "mắt cá chân", "I twisted my ankle playing football.", "an|kle", 0),
      word("plaster", "/ˈplɑː.stə/", "miếng băng dán cá nhân", "Put a plaster on that cut.", "plas|ter", 0),
      word("check-up", "/ˈtʃek.ʌp/", "sự khám sức khỏe định kỳ", "I go to the dentist for a check-up twice a year.", "check|up", 0),
      word("wheelchair", "/ˈwiːl.tʃeə/", "xe lăn", "After the accident, he used a wheelchair for a month.", "wheel|chair", 0),
      word("disabled", "/dɪˈseɪ.bəld/", "khuyết tật", "The building has a lift for disabled people.", "dis|a|bled", 1),
      word("deaf", "/def/", "điếc", "My grandfather is a bit deaf.", "deaf", 0, "Chữ ea đọc là /e/: /def/."),
      word("pregnant", "/ˈpreɡ.nənt/", "có thai", "My sister is pregnant with her first baby.", "preg|nant", 0),
      word("unwell", "/ʌnˈwel/", "không khỏe, mệt", "She felt unwell and went home early.", "un|well", 1),
      word("physical", "/ˈfɪz.ɪ.kəl/", "(thuộc) thể chất", "Physical exercise is good for your mind too.", "phys|i|cal", 0),
      word("mental", "/ˈmen.təl/", "(thuộc) tinh thần", "Stress is bad for your mental health.", "men|tal", 0),
    ],
  },
  {
    id: "cong-nghe-va-internet",
    title: "Công nghệ và Internet",
    words: [
      word("install", "/ɪnˈstɔːl/", "cài đặt", "It takes a few minutes to install the software.", "in|stall", 1),
      word("browser", "/ˈbraʊ.zə/", "trình duyệt", "Open your browser and go to our website.", "brows|er", 0),
      word("folder", "/ˈfəʊl.də/", "thư mục", "Put all the photos in one folder.", "fold|er", 0),
      word("document", "/ˈdɒk.jə.mənt/", "tài liệu, văn bản", "Please send me the document by email.", "doc|u|ment", 0),
      word("data", "/ˈdeɪ.tə/", "dữ liệu", "The app collects data about how you use it.", "da|ta", 0),
      word("electronic", "/ˌel.ɪkˈtrɒn.ɪk/", "điện tử", "Please turn off all electronic devices.", "e|lec|tron|ic", 2),
      word("wireless", "/ˈwaɪə.ləs/", "không dây", "Do you have wireless internet here?", "wire|less", 0),
      word("signal", "/ˈsɪɡ.nəl/", "tín hiệu, sóng", "I can't get a signal in the mountains.", "sig|nal", 0),
      word("update", "/ʌpˈdeɪt/", "cập nhật", "I need to update the app.", "up|date", 1),
      word("virus", "/ˈvaɪə.rəs/", "vi-rút", "My computer has a virus.", "vi|rus", 0),
      word("robot", "/ˈrəʊ.bɒt/", "rô-bốt", "Robots do a lot of the work in this factory.", "ro|bot", 0),
      word("calculator", "/ˈkæl.kjə.leɪ.tə/", "máy tính cầm tay", "You can use a calculator in the maths exam.", "cal|cu|la|tor", 0),
      word("smartphone", "/ˈsmɑːt.fəʊn/", "điện thoại thông minh", "Almost everyone has a smartphone now.", "smart|phone", 0),
      word("operate", "/ˈɒp.ər.eɪt/", "vận hành", "Do you know how to operate this machine?", "op|er|ate", 0),
      word("scientific", "/ˌsaɪ.ənˈtɪf.ɪk/", "(thuộc) khoa học", "There's no scientific evidence for it.", "sci|en|tif|ic", 2),
      word("technical", "/ˈtek.nɪ.kəl/", "(thuộc) kỹ thuật", "We had some technical problems with the sound.", "tech|ni|cal", 0),
      word("webcam", "/ˈweb.kæm/", "webcam, camera máy tính", "My laptop has a built-in webcam.", "web|cam", 0),
      word("monitor", "/ˈmɒn.ɪ.tə/", "màn hình máy tính", "I work with two monitors on my desk.", "mon|i|tor", 0),
      word("cable", "/ˈkeɪ.bəl/", "dây cáp", "I need a longer cable for my laptop.", "ca|ble", 0),
      word("socket", "/ˈsɒk.ɪt/", "ổ cắm điện", "Is there a socket near the bed?", "sock|et", 0),
      word("program", "/ˈprəʊ.ɡræm/", "chương trình máy tính", "He wrote a computer program to check his spelling.", "pro|gram", 0),
      word("code", "/kəʊd/", "mã (lập trình, bảo mật)", "Enter the code to open the door.", "code", 0),
      word("wifi", "/ˈwaɪ.faɪ/", "mạng Wi-Fi", "Is there free wifi in the hotel?", "wi|fi", 0),
      word("broadband", "/ˈbrɔːd.bænd/", "internet băng thông rộng", "We've just got faster broadband at home.", "broad|band", 0),
      word("storage", "/ˈstɔː.rɪdʒ/", "bộ nhớ lưu trữ", "My phone doesn't have enough storage for these videos.", "stor|age", 0),
      word("inbox", "/ˈɪn.bɒks/", "hộp thư đến", "I have 200 emails in my inbox.", "in|box", 0),
      word("username", "/ˈjuː.zə.neɪm/", "tên đăng nhập", "Enter your username and password.", "us|er|name", 0),
      word("profile", "/ˈprəʊ.faɪl/", "trang cá nhân, hồ sơ", "I changed my profile picture.", "pro|file", 0),
      word("comment", "/ˈkɒm.ent/", "lời bình luận", "She left a nice comment under my photo.", "com|ment", 0),
      word("electrical", "/ɪˈlek.trɪ.kəl/", "(thuộc) điện", "We had an electrical problem in the kitchen.", "e|lec|tri|cal", 1),
      word("privacy", "/ˈprɪv.ə.si/", "sự riêng tư", "Check your privacy settings on social media.", "priv|a|cy", 0),
      word("inventor", "/ɪnˈven.tə/", "nhà phát minh", "Who was the inventor of the telephone?", "in|ven|tor", 1),
      word("automatic", "/ˌɔː.təˈmæt.ɪk/", "tự động", "The doors are automatic.", "au|to|mat|ic", 2),
      word("screenshot", "/ˈskriːn.ʃɒt/", "ảnh chụp màn hình", "Take a screenshot and send it to me.", "screen|shot", 0),
    ],
  },
  {
    id: "toi-pham-va-phap-luat",
    title: "Tội phạm và pháp luật",
    words: [
      word("crime", "/kraɪm/", "tội phạm, tội ác", "Crime has fallen in the city this year.", "crime", 0),
      word("criminal", "/ˈkrɪm.ɪ.nəl/", "kẻ phạm tội", "The police caught the criminals.", "crim|i|nal", 0),
      word("thief", "/θiːf/", "kẻ trộm", "A thief stole my bag on the bus.", "thief", 0, "Âm đầu /θ/: đặt lưỡi giữa hai hàm răng rồi thổi hơi, không đọc thành /t/."),
      word("steal", "/stiːl/", "ăn trộm", "Someone tried to steal my bike.", "steal", 0),
      word("rob", "/rɒb/", "cướp", "Two men robbed a bank in the city centre.", "rob", 0),
      word("robbery", "/ˈrɒb.ər.i/", "vụ cướp", "There was a robbery at the jeweller's last night.", "rob|ber|y", 0),
      word("burglar", "/ˈbɜː.ɡlə/", "kẻ trộm đột nhập", "A burglar broke into our house.", "bur|glar", 0),
      word("murder", "/ˈmɜː.də/", "tội giết người", "He was sent to prison for murder.", "mur|der", 0),
      word("detective", "/dɪˈtek.tɪv/", "thám tử", "I love detective stories.", "de|tec|tive", 1),
      word("investigate", "/ɪnˈves.tɪ.ɡeɪt/", "điều tra", "The police are investigating the robbery.", "in|ves|ti|gate", 1),
      word("witness", "/ˈwɪt.nəs/", "nhân chứng", "Were there any witnesses to the accident?", "wit|ness", 0),
      word("victim", "/ˈvɪk.tɪm/", "nạn nhân", "The victim was taken to hospital.", "vic|tim", 0),
      word("court", "/kɔːt/", "tòa án", "He will appear in court next week.", "court", 0, "Chữ ou đọc là /ɔː/, không đọc âm r: /kɔːt/."),
      word("trial", "/ˈtraɪ.əl/", "phiên tòa", "The trial lasted three weeks.", "tri|al", 0),
      word("guilty", "/ˈɡɪl.ti/", "có tội", "The jury found him guilty.", "guil|ty", 0, "Chữ u không đọc: GIL-ti."),
      word("innocent", "/ˈɪn.ə.sənt/", "vô tội", "She says she is innocent.", "in|no|cent", 0),
      word("law", "/lɔː/", "luật pháp", "It's against the law to drive without a licence.", "law", 0),
      word("illegal", "/ɪˈliː.ɡəl/", "bất hợp pháp", "It's illegal to smoke on the bus.", "il|le|gal", 1),
      word("legal", "/ˈliː.ɡəl/", "hợp pháp", "Is it legal to ride a bike on the pavement?", "le|gal", 0),
      word("punishment", "/ˈpʌn.ɪʃ.mənt/", "hình phạt", "The punishment for stealing is quite serious.", "pun|ish|ment", 0),
      word("jail", "/dʒeɪl/", "nhà tù", "He spent two years in jail.", "jail", 0),
      word("gun", "/ɡʌn/", "súng", "The robber had a gun.", "gun", 0),
      word("violent", "/ˈvaɪə.lənt/", "bạo lực", "There's too much violent crime on TV.", "vio|lent", 0),
      word("attack", "/əˈtæk/", "tấn công", "He was attacked on his way home.", "at|tack", 1),
      word("shoot", "/ʃuːt/", "bắn", "In the film, the soldiers shoot at the enemy.", "shoot", 0),
      word("escape", "/ɪˈskeɪp/", "trốn thoát", "Two prisoners escaped last night.", "es|cape", 1),
      word("security", "/sɪˈkjʊə.rə.ti/", "an ninh", "There's a security guard at the door.", "se|cu|ri|ty", 1),
      word("safety", "/ˈseɪf.ti/", "sự an toàn", "Wear a helmet for your own safety.", "safe|ty", 0),
      word("pickpocket", "/ˈpɪkˌpɒk.ɪt/", "kẻ móc túi", "Watch out for pickpockets in the market.", "pick|pock|et", 0),
      word("hacker", "/ˈhæk.ə/", "tin tặc", "Hackers stole the passwords of thousands of users.", "hack|er", 0),
      word("warning", "/ˈwɔː.nɪŋ/", "lời cảnh báo", "The police gave him a warning.", "warn|ing", 0),
      word("prisoner", "/ˈprɪz.ən.ə/", "tù nhân", "The prisoner escaped from jail.", "pris|on|er", 0),
      word("murderer", "/ˈmɜː.dər.ə/", "kẻ giết người", "The police are still looking for the murderer.", "mur|der|er", 0),
      word("weapon", "/ˈwep.ən/", "vũ khí", "The police found the weapon in the river.", "weap|on", 0, "Chữ ea đọc là /e/: WEP-ən."),
    ],
  },
  {
    id: "mo-ta-noi-chon",
    title: "Mô tả nơi chốn",
    words: [
      word("atmosphere", "/ˈæt.məs.fɪə/", "bầu không khí", "The café has a relaxing atmosphere.", "at|mos|phere", 0),
      word("scenery", "/ˈsiː.nər.i/", "phong cảnh", "The scenery in Ha Giang is beautiful.", "sce|ner|y", 0),
      word("landscape", "/ˈlænd.skeɪp/", "cảnh quan", "The landscape is flat and green.", "land|scape", 0),
      word("harbour", "/ˈhɑː.bə/", "bến cảng", "Boats were coming into the harbour.", "har|bour", 0),
      word("cave", "/keɪv/", "hang động", "Son Doong is the largest cave in the world.", "cave", 0),
      word("lively", "/ˈlaɪv.li/", "sôi động, náo nhiệt", "The Old Quarter is lively at night.", "live|ly", 0, "Chữ i đọc là /aɪ/: LAIV-li, khác với live /lɪv/."),
      word("historic", "/hɪˈstɒr.ɪk/", "có ý nghĩa lịch sử, cổ kính", "Hoi An is a historic town.", "his|tor|ic", 1),
      word("ancient", "/ˈeɪn.ʃənt/", "cổ xưa", "We visited an ancient temple.", "an|cient", 0, "Chữ a đọc là /eɪ/, ci đọc là /ʃ/: EIN-shənt."),
      word("rural", "/ˈrʊə.rəl/", "(thuộc) nông thôn", "Life in rural areas is quieter.", "ru|ral", 0),
      word("polluted", "/pəˈluː.tɪd/", "bị ô nhiễm", "The river is badly polluted.", "pol|lut|ed", 1),
      word("remote", "/rɪˈməʊt/", "xa xôi, hẻo lánh", "They live in a remote village in the mountains.", "re|mote", 1),
      word("enormous", "/ɪˈnɔː.məs/", "khổng lồ", "The new shopping centre is enormous.", "e|nor|mous", 1),
      word("narrow", "/ˈnær.əʊ/", "hẹp", "The streets in the old town are very narrow.", "nar|row", 0),
      word("steep", "/stiːp/", "dốc", "The road up the hill is very steep.", "steep", 0),
      word("attractive", "/əˈtræk.tɪv/", "hấp dẫn, thu hút", "Da Lat is an attractive city for tourists.", "at|trac|tive", 1),
      word("charming", "/ˈtʃɑː.mɪŋ/", "duyên dáng, đáng yêu", "We stayed in a charming little hotel.", "charm|ing", 0),
      word("pleasant", "/ˈplez.ənt/", "dễ chịu", "It's a pleasant place to live.", "pleas|ant", 0, "Chữ ea đọc là /e/: PLEZ-ənt."),
      word("impressive", "/ɪmˈpres.ɪv/", "ấn tượng", "The view from the top is impressive.", "im|pres|sive", 1),
      word("surround", "/səˈraʊnd/", "bao quanh", "The lake is surrounded by trees.", "sur|round", 1),
      word("statue", "/ˈstætʃ.uː/", "bức tượng", "There's a statue of Ly Thai To near the lake.", "stat|ue", 0),
      word("cathedral", "/kəˈθiː.drəl/", "nhà thờ lớn", "The cathedral is in the centre of the city.", "ca|the|dral", 1),
      word("tower", "/ˈtaʊ.ə/", "tòa tháp", "You can see the whole city from the tower.", "tow|er", 0),
      word("fountain", "/ˈfaʊn.tɪn/", "đài phun nước", "Children were playing near the fountain.", "foun|tain", 0),
      word("skyscraper", "/ˈskaɪˌskreɪ.pə/", "tòa nhà chọc trời", "The city is full of skyscrapers.", "sky|scrap|er", 0),
      word("district", "/ˈdɪs.trɪkt/", "khu, khu vực", "The business district is very busy on weekdays.", "dis|trict", 0),
      word("region", "/ˈriː.dʒən/", "vùng, miền", "The region is famous for its coffee.", "re|gion", 0),
      word("location", "/ləʊˈkeɪ.ʃən/", "vị trí, địa điểm", "The hotel is in a perfect location.", "lo|ca|tion", 1),
      word("edge", "/edʒ/", "rìa, mép", "The house is on the edge of the forest.", "edge", 0),
      word("outskirts", "/ˈaʊt.skɜːts/", "vùng ven đô, ngoại ô", "We live on the outskirts of Hanoi.", "out|skirts", 0),
      word("port", "/pɔːt/", "cảng", "Hai Phong is a busy port in the north.", "port", 0),
      word("bay", "/beɪ/", "vịnh", "Ha Long Bay is a UNESCO World Heritage Site.", "bay", 0),
      word("cliff", "/klɪf/", "vách đá", "The hotel stands at the top of a cliff.", "cliff", 0),
      word("pagoda", "/pəˈɡəʊ.də/", "chùa", "The One Pillar Pagoda is in the centre of Hanoi.", "pa|go|da", 1),
      word("cosy", "/ˈkəʊ.zi/", "ấm cúng", "It's a small but cosy café.", "co|sy", 0),
    ],
  },
];

export default topics;
