import { word } from "../builders";
import type { WordTopic } from "../types";

/** Extra B2 vocabulary by topic, reviewed with spaced repetition (see /tu-vung). */
const topics: WordTopic[] = [
  {
    id: "nghe-thuat-van-hoa",
    title: "Nghệ thuật và văn hoá",
    words: [
      word("sculpture", "/ˈskʌlp.tʃə/", "tác phẩm điêu khắc", "A huge bronze sculpture stands in the middle of the square.", "sculp|ture", 0),
      word("portrait", "/ˈpɔː.trət/", "bức chân dung", "She painted a portrait of her grandmother.", "por|trait", 0),
      word("audition", "/ɔːˈdɪʃ.ən/", "buổi thử vai", "Over two hundred actors came to the audition.", "au|di|tion", 1),
      word("rehearsal", "/rəˈhɜː.səl/", "buổi diễn tập", "The final rehearsal went on until midnight.", "re|hear|sal", 1),
      word("premiere", "/ˈprem.i.eə/", "buổi công chiếu đầu tiên", "The stars walked the red carpet at the film's premiere.", "pre|mi|ere", 0),
      word("playwright", "/ˈpleɪ.raɪt/", "nhà viết kịch", "Shakespeare is the most famous playwright in English.", "play|wright", 0, "Chữ w không đọc: PLAY-rait."),
      word("novelist", "/ˈnɒv.əl.ɪst/", "tiểu thuyết gia", "The novelist spent ten years writing her first book.", "nov|el|ist", 0),
      word("genre", "/ˈʒɒn.rə/", "thể loại", "Science fiction is my favourite genre.", "gen|re", 0, "Âm đầu là /ʒ/ (như 'gi' nhẹ trong tiếng Pháp), không đọc /dʒen/."),
      word("orchestra", "/ˈɔː.kɪ.strə/", "dàn nhạc giao hưởng", "The orchestra played Beethoven's Fifth Symphony.", "or|ches|tra", 0, "ch đọc là /k/: AW-kis-trờ."),
      word("composer", "/kəmˈpəʊ.zə/", "nhà soạn nhạc", "Mozart was a composer of genius.", "com|pos|er", 1),
      word("critic", "/ˈkrɪt.ɪk/", "nhà phê bình", "The film was praised by every critic.", "crit|ic", 0),
      word("acclaimed", "/əˈkleɪmd/", "được ca ngợi", "It is a critically acclaimed film.", "ac|claimed", 1),
      word("abstract", "/ˈæb.strækt/", "trừu tượng", "I find abstract art hard to understand.", "ab|stract", 0),
      word("contemporary", "/kənˈtem.pər.ər.i/", "đương đại", "The festival focuses on contemporary dance.", "con|tem|po|rar|y", 1),
      word("sketch", "/sketʃ/", "bản phác thảo; phác thảo", "She made a quick sketch of the bridge.", "sketch", 0),
      word("canvas", "/ˈkæn.vəs/", "vải vẽ tranh; bức tranh sơn dầu", "The artist stretched a new canvas on the frame.", "can|vas", 0),
      word("illustration", "/ˌɪl.əˈstreɪ.ʃən/", "hình minh hoạ", "The book has beautiful illustrations on every page.", "il|lus|tra|tion", 2),
      word("soundtrack", "/ˈsaʊnd.træk/", "nhạc phim", "The soundtrack won an award.", "sound|track", 0),
      word("sequel", "/ˈsiː.kwəl/", "phần tiếp theo", "The sequel was not as good as the original film.", "se|quel", 0),
      word("applause", "/əˈplɔːz/", "tràng pháo tay", "The pianist left the stage to loud applause.", "ap|plause", 1),
      word("backstage", "/ˌbækˈsteɪdʒ/", "hậu trường", "Fans waited backstage to meet the band.", "back|stage", 1),
      word("lyrics", "/ˈlɪr.ɪks/", "lời bài hát", "I love the melody, but I can't understand the lyrics.", "lyr|ics", 0),
      word("exhibit", "/ɪɡˈzɪb.ɪt/", "trưng bày", "Her photos are exhibited in a gallery in Hanoi.", "ex|hib|it", 1, "Chữ h không đọc: ig-ZIB-it."),
      word("imaginative", "/ɪˈmædʒ.ɪ.nə.tɪv/", "giàu trí tưởng tượng", "It's a very imaginative story for children.", "i|mag|i|na|tive", 1),
      word("creativity", "/ˌkriː.eɪˈtɪv.ə.ti/", "sự sáng tạo", "The course encourages creativity and self-expression.", "cre|a|tiv|i|ty", 2),
      word("cast", "/kɑːst/", "dàn diễn viên", "The film has an excellent cast.", "cast", 0),
      word("comedian", "/kəˈmiː.di.ən/", "diễn viên hài", "The comedian made the whole audience laugh.", "co|me|di|an", 1),
      word("autobiography", "/ˌɔː.tə.baɪˈɒɡ.rə.fi/", "tự truyện", "In his autobiography, he writes about his childhood in Hue.", "au|to|bi|og|ra|phy", 3),
      word("performer", "/pəˈfɔː.mə/", "người biểu diễn", "Street performers attract big crowds at weekends.", "per|form|er", 1),
      word("artistic", "/ɑːˈtɪs.tɪk/", "(thuộc) nghệ thuật; có khiếu nghệ thuật", "She comes from a very artistic family.", "ar|tis|tic", 1),
      word("tune", "/tjuːn/", "giai điệu", "He was whistling a cheerful tune.", "tune", 0),
      word("choir", "/kwaɪə/", "dàn hợp xướng", "She sings in the school choir.", "choir", 0, "Đọc /kwaɪə/ (quai-ờ), chữ ch ở đây là /k/."),
    ],
  },
  {
    id: "khoa-hoc-cong-nghe",
    title: "Khoa học và công nghệ",
    words: [
      word("innovation", "/ˌɪn.əˈveɪ.ʃən/", "sự đổi mới, cải tiến", "The company is famous for innovation.", "in|no|va|tion", 2),
      word("breakthrough", "/ˈbreɪk.θruː/", "bước đột phá", "Scientists have made a major breakthrough in cancer research.", "break|through", 0),
      word("microscope", "/ˈmaɪ.krə.skəʊp/", "kính hiển vi", "Bacteria can only be seen under a microscope.", "mi|cro|scope", 0),
      word("artificial", "/ˌɑː.tɪˈfɪʃ.əl/", "nhân tạo", "Artificial intelligence is changing many industries.", "ar|ti|fi|cial", 2),
      word("automation", "/ˌɔː.təˈmeɪ.ʃən/", "sự tự động hoá", "Automation has replaced many factory jobs.", "au|to|ma|tion", 2),
      word("algorithm", "/ˈæl.ɡə.rɪ.ðəm/", "thuật toán", "The app uses an algorithm to suggest videos.", "al|go|ri|thm", 0),
      word("database", "/ˈdeɪ.tə.beɪs/", "cơ sở dữ liệu", "All customer details are stored in a database.", "da|ta|base", 0),
      word("encryption", "/ɪnˈkrɪp.ʃən/", "sự mã hoá", "Encryption keeps your messages private.", "en|cryp|tion", 1),
      word("bandwidth", "/ˈbænd.wɪtθ/", "băng thông", "Streaming video uses a lot of bandwidth.", "band|width", 0),
      word("upgrade", "/ʌpˈɡreɪd/", "nâng cấp", "I need to upgrade my laptop's memory.", "up|grade", 1),
      word("malfunction", "/ˌmælˈfʌŋk.ʃən/", "sự trục trặc; trục trặc", "A computer malfunction delayed the flight.", "mal|func|tion", 1),
      word("prototype", "/ˈprəʊ.tə.taɪp/", "nguyên mẫu", "The engineers tested a prototype of the new car.", "pro|to|type", 0),
      word("patent", "/ˈpæt.ənt/", "bằng sáng chế", "She applied for a patent for her invention.", "pat|ent", 0),
      word("molecule", "/ˈmɒl.ɪ.kjuːl/", "phân tử", "A water molecule has two hydrogen atoms and one oxygen atom.", "mol|e|cule", 0),
      word("gravity", "/ˈɡræv.ə.ti/", "trọng lực", "Gravity keeps the planets moving around the sun.", "grav|i|ty", 0),
      word("radiation", "/ˌreɪ.diˈeɪ.ʃən/", "bức xạ", "The workers wear suits that protect them from radiation.", "ra|di|a|tion", 2),
      word("genetic", "/dʒəˈnet.ɪk/", "(thuộc) di truyền", "Some diseases are caused by genetic factors.", "ge|net|ic", 1),
      word("satellite", "/ˈsæt.əl.aɪt/", "vệ tinh", "The match was broadcast live by satellite.", "sat|el|lite", 0),
      word("virtual", "/ˈvɜː.tʃu.əl/", "ảo", "You can take a virtual tour of the museum online.", "vir|tu|al", 0),
      word("obsolete", "/ˈɒb.səl.iːt/", "lỗi thời", "Fax machines are almost obsolete now.", "ob|so|lete", 0),
      word("cutting-edge", "/ˌkʌt.ɪŋˈedʒ/", "tiên tiến nhất", "The hospital uses cutting-edge technology.", "cut|ting|edge", 2),
      word("compatible", "/kəmˈpæt.ə.bəl/", "tương thích", "This charger isn't compatible with my phone.", "com|pat|i|ble", 1),
      word("engineering", "/ˌen.dʒɪˈnɪə.rɪŋ/", "ngành kỹ thuật", "My brother is studying engineering at university.", "en|gi|nee|ring", 2),
      word("astronaut", "/ˈæs.trə.nɔːt/", "phi hành gia", "The astronaut spent six months in space.", "as|tro|naut", 0),
      word("telescope", "/ˈtel.ɪ.skəʊp/", "kính thiên văn", "We looked at the moon through a telescope.", "tel|e|scope", 0),
      word("variable", "/ˈveə.ri.ə.bəl/", "biến số; hay thay đổi", "Temperature is an important variable in the experiment.", "var|i|a|ble", 0),
      word("precise", "/prɪˈsaɪs/", "chính xác", "The instruments give very precise measurements.", "pre|cise", 1),
      word("technician", "/tekˈnɪʃ.ən/", "kỹ thuật viên", "A technician came to repair the printer.", "tech|ni|cian", 1),
      word("hardware", "/ˈhɑːd.weə/", "phần cứng", "The software is fine; the problem is the hardware.", "hard|ware", 0),
      word("portable", "/ˈpɔː.tə.bəl/", "xách tay, dễ mang theo", "I bought a portable speaker for the trip.", "por|ta|ble", 0),
      word("technological", "/ˌtek.nəˈlɒdʒ.ɪ.kəl/", "(thuộc) công nghệ", "We live in an age of rapid technological change.", "tech|no|log|i|cal", 2),
      word("calculation", "/ˌkæl.kjəˈleɪ.ʃən/", "phép tính, sự tính toán", "According to my calculations, we'll need three more days.", "cal|cu|la|tion", 2),
    ],
  },
  {
    id: "kinh-doanh-kinh-te",
    title: "Kinh doanh và kinh tế",
    words: [
      word("recession", "/rɪˈseʃ.ən/", "suy thoái kinh tế", "Many small firms closed during the recession.", "re|ces|sion", 1),
      word("inflation", "/ɪnˈfleɪ.ʃən/", "lạm phát", "Inflation has pushed up the price of food.", "in|fla|tion", 1),
      word("turnover", "/ˈtɜːnˌəʊ.və/", "doanh thu", "The company has an annual turnover of ten million dollars.", "turn|o|ver", 0),
      word("shareholder", "/ˈʃeəˌhəʊl.də/", "cổ đông", "The shareholders voted against the plan.", "share|hold|er", 0),
      word("acquisition", "/ˌæk.wɪˈzɪʃ.ən/", "sự thâu tóm, mua lại", "The acquisition of the rival firm cost billions.", "ac|qui|si|tion", 2),
      word("entrepreneur", "/ˌɒn.trə.prəˈnɜː/", "doanh nhân khởi nghiệp", "She became a successful entrepreneur at twenty-five.", "en|tre|pre|neur", 3, "Trọng âm ở âm cuối: on-trờ-prờ-NƠ."),
      word("startup", "/ˈstɑːt.ʌp/", "công ty khởi nghiệp", "He left his job to work for a tech startup.", "start|up", 0),
      word("competitor", "/kəmˈpet.ɪ.tə/", "đối thủ cạnh tranh", "Our main competitor has just lowered its prices.", "com|pet|i|tor", 1),
      word("tariff", "/ˈtær.ɪf/", "thuế quan", "The government raised tariffs on imported cars.", "tar|iff", 0),
      word("asset", "/ˈæs.et/", "tài sản", "Our staff are our most valuable asset.", "as|set", 0),
      word("bankrupt", "/ˈbæŋ.krʌpt/", "phá sản", "The airline went bankrupt last year.", "bank|rupt", 0),
      word("consumer", "/kənˈsjuː.mə/", "người tiêu dùng", "Consumers are spending less on luxury goods.", "con|sum|er", 1),
      word("wholesale", "/ˈhəʊl.seɪl/", "bán buôn", "We buy rice at wholesale prices.", "whole|sale", 0, "Chữ w không đọc: HÂUL-seil."),
      word("supplier", "/səˈplaɪ.ə/", "nhà cung cấp", "We found a cheaper supplier of paper.", "sup|pli|er", 1),
      word("taxation", "/tækˈseɪ.ʃən/", "việc đánh thuế", "High taxation can discourage investment.", "tax|a|tion", 1),
      word("profitable", "/ˈprɒf.ɪ.tə.bəl/", "có lãi", "The shop became profitable in its second year.", "prof|it|a|ble", 0),
      word("franchise", "/ˈfræn.tʃaɪz/", "cửa hàng nhượng quyền; quyền kinh doanh nhượng quyền", "He owns a coffee franchise in Da Nang.", "fran|chise", 0),
      word("economist", "/iˈkɒn.ə.mɪst/", "nhà kinh tế học", "Economists expect growth to slow next year.", "e|con|o|mist", 1),
      word("boom", "/buːm/", "sự bùng nổ, tăng vọt", "There has been a boom in online shopping.", "boom", 0),
      word("slump", "/slʌmp/", "sự sụt giảm mạnh", "Car sales suffered a slump after the price rise.", "slump", 0),
      word("commerce", "/ˈkɒm.ɜːs/", "thương mại", "E-commerce is growing fast in Southeast Asia.", "com|merce", 0),
      word("logistics", "/ləˈdʒɪs.tɪks/", "hậu cần, vận chuyển", "She manages logistics for a shipping company.", "lo|gis|tics", 1),
      word("outsource", "/ˈaʊt.sɔːs/", "thuê ngoài", "Many firms outsource their customer service.", "out|source", 0),
      word("stakeholder", "/ˈsteɪkˌhəʊl.də/", "bên liên quan", "We need to consult all stakeholders before we decide.", "stake|hold|er", 0),
      word("productivity", "/ˌprɒd.ʌkˈtɪv.ə.ti/", "năng suất", "Working from home increased our productivity.", "pro|duc|tiv|i|ty", 2),
      word("subsidy", "/ˈsʌb.sɪ.di/", "tiền trợ cấp", "Farmers receive a subsidy from the government.", "sub|si|dy", 0),
      word("investor", "/ɪnˈves.tə/", "nhà đầu tư", "Foreign investors are interested in Vietnam's tech sector.", "in|ves|tor", 1),
      word("corporation", "/ˌkɔː.pərˈeɪ.ʃən/", "tập đoàn", "She works for a large multinational corporation.", "cor|po|ra|tion", 2),
      word("wealth", "/welθ/", "sự giàu có, của cải", "Most of his wealth comes from property.", "wealth", 0, "Kết thúc bằng /lθ/: đặt lưỡi giữa hai răng ở cuối từ."),
      word("economical", "/ˌiː.kəˈnɒm.ɪ.kəl/", "tiết kiệm", "Small cars are more economical to run.", "e|co|nom|i|cal", 2),
      word("industrial", "/ɪnˈdʌs.tri.əl/", "(thuộc) công nghiệp", "There are many industrial parks near Ho Chi Minh City.", "in|dus|tri|al", 1),
      word("manufacturer", "/ˌmæn.jəˈfæk.tʃər.ə/", "nhà sản xuất", "The manufacturer has recalled thousands of cars.", "man|u|fac|tur|er", 2),
      word("partnership", "/ˈpɑːt.nə.ʃɪp/", "sự hợp tác, quan hệ đối tác", "The two companies have formed a partnership.", "part|ner|ship", 0),
    ],
  },
  {
    id: "xa-hoi-chinh-tri",
    title: "Xã hội và chính trị",
    words: [
      word("democracy", "/dɪˈmɒk.rə.si/", "nền dân chủ", "Free elections are the basis of democracy.", "de|moc|ra|cy", 1),
      word("candidate", "/ˈkæn.dɪ.dət/", "ứng cử viên", "There are three candidates in the election.", "can|di|date", 0),
      word("campaign", "/kæmˈpeɪn/", "chiến dịch", "They launched a campaign against plastic waste.", "cam|paign", 1, "Chữ g không đọc: kam-PEIN."),
      word("parliament", "/ˈpɑː.lə.mənt/", "quốc hội, nghị viện", "The new law was passed by parliament.", "par|lia|ment", 0, "Chữ i không đọc: PA-lờ-mần."),
      word("policy", "/ˈpɒl.ə.si/", "chính sách", "The government's housing policy has been criticised.", "pol|i|cy", 0),
      word("minister", "/ˈmɪn.ɪ.stə/", "bộ trưởng", "The Minister of Education visited our school.", "min|is|ter", 0),
      word("activist", "/ˈæk.tɪ.vɪst/", "nhà hoạt động", "Climate activists blocked the road.", "ac|ti|vist", 0),
      word("poverty", "/ˈpɒv.ə.ti/", "sự nghèo đói", "Millions of people still live in poverty.", "pov|er|ty", 0),
      word("welfare", "/ˈwel.feə/", "phúc lợi", "The state spends a lot on social welfare.", "wel|fare", 0),
      word("citizen", "/ˈsɪt.ɪ.zən/", "công dân", "Every citizen has the right to vote.", "cit|i|zen", 0),
      word("immigration", "/ˌɪm.ɪˈɡreɪ.ʃən/", "sự nhập cư", "Immigration is a hot topic in the election.", "im|mi|gra|tion", 2),
      word("refugee", "/ˌref.juˈdʒiː/", "người tị nạn", "The camp provides shelter for refugees.", "ref|u|gee", 2),
      word("discrimination", "/dɪˌskrɪm.ɪˈneɪ.ʃən/", "sự phân biệt đối xử", "The law bans discrimination against women at work.", "dis|crim|i|na|tion", 3),
      word("unemployment", "/ˌʌn.ɪmˈplɔɪ.mənt/", "tình trạng thất nghiệp", "Youth unemployment has fallen this year.", "un|em|ploy|ment", 2),
      word("corruption", "/kəˈrʌp.ʃən/", "tham nhũng", "The official was arrested for corruption.", "cor|rup|tion", 1),
      word("majority", "/məˈdʒɒr.ə.ti/", "đa số", "The majority of voters supported the plan.", "ma|jor|i|ty", 1),
      word("minority", "/maɪˈnɒr.ə.ti/", "thiểu số", "Only a minority of people disagreed.", "mi|nor|i|ty", 1),
      word("debate", "/dɪˈbeɪt/", "cuộc tranh luận; tranh luận", "There was a heated debate about the new law.", "de|bate", 1),
      word("opposition", "/ˌɒp.əˈzɪʃ.ən/", "phe đối lập; sự phản đối", "The plan faced strong opposition from local people.", "op|po|si|tion", 2),
      word("diversity", "/daɪˈvɜː.sə.ti/", "sự đa dạng", "The city is proud of its cultural diversity.", "di|ver|si|ty", 1),
      word("elect", "/ɪˈlekt/", "bầu chọn", "She was elected mayor in 2020.", "e|lect", 1),
      word("govern", "/ˈɡʌv.ən/", "cai trị, điều hành", "The party has governed the country for ten years.", "gov|ern", 0),
      word("petition", "/pəˈtɪʃ.ən/", "đơn kiến nghị", "Over ten thousand people signed the petition.", "pe|ti|tion", 1),
      word("boycott", "/ˈbɔɪ.kɒt/", "tẩy chay", "Customers boycotted the brand after the scandal.", "boy|cott", 0),
      word("controversial", "/ˌkɒn.trəˈvɜː.ʃəl/", "gây tranh cãi", "The decision to close the park was controversial.", "con|tro|ver|sial", 2),
      word("ballot", "/ˈbæl.ət/", "lá phiếu; cuộc bỏ phiếu kín", "The results of the ballot will be announced tonight.", "bal|lot", 0),
      word("racism", "/ˈreɪ.sɪ.zəm/", "sự phân biệt chủng tộc", "The club has promised to fight racism in football.", "ra|ci|sm", 0),
      word("donation", "/dəʊˈneɪ.ʃən/", "khoản quyên góp", "They made a donation to help flood victims.", "do|na|tion", 1),
      word("violence", "/ˈvaɪ.ə.ləns/", "bạo lực", "There has been an increase in violence in the area.", "vi|o|lence", 0),
      word("urban", "/ˈɜː.bən/", "(thuộc) đô thị", "More and more people are moving to urban areas.", "ur|ban", 0),
      word("status", "/ˈsteɪ.təs/", "địa vị", "In some cultures, owning a car is a sign of status.", "sta|tus", 0),
      word("freedom", "/ˈfriː.dəm/", "sự tự do", "Freedom of speech is an important right.", "free|dom", 0),
    ],
  },
  {
    id: "toi-pham-phap-luat",
    title: "Tội phạm và pháp luật",
    words: [
      word("burglary", "/ˈbɜː.ɡlər.i/", "vụ trộm đột nhập", "There has been a rise in burglary in this area.", "bur|glar|y", 0),
      word("theft", "/θeft/", "sự trộm cắp", "Car theft is common in big cities.", "theft", 0, "Âm /θ/: đặt đầu lưỡi giữa hai hàm răng, không đọc thành /t/."),
      word("shoplifting", "/ˈʃɒpˌlɪf.tɪŋ/", "tội ăn cắp đồ trong cửa hàng", "The teenager was caught shoplifting.", "shop|lift|ing", 0),
      word("jury", "/ˈdʒʊə.ri/", "bồi thẩm đoàn", "The jury found him guilty.", "ju|ry", 0),
      word("defendant", "/dɪˈfen.dənt/", "bị cáo", "The defendant denied all the charges.", "de|fend|ant", 1),
      word("offence", "/əˈfens/", "tội, hành vi phạm pháp", "Driving without a licence is a serious offence.", "of|fence", 1),
      word("bail", "/beɪl/", "tiền bảo lãnh tại ngoại", "She was released on bail.", "bail", 0),
      word("forensic", "/fəˈren.zɪk/", "(thuộc) pháp y", "Forensic tests showed his fingerprints on the knife.", "fo|ren|sic", 1),
      word("kidnap", "/ˈkɪd.næp/", "bắt cóc", "The businessman was kidnapped and held for a week.", "kid|nap", 0),
      word("surveillance", "/səˈveɪ.ləns/", "sự giám sát", "The building is under 24-hour surveillance.", "sur|veil|lance", 1),
      word("violate", "/ˈvaɪ.ə.leɪt/", "vi phạm", "The factory violated safety rules.", "vi|o|late", 0),
      word("barrister", "/ˈbær.ɪ.stə/", "luật sư tranh tụng", "Her barrister argued that the evidence was weak.", "bar|ris|ter", 0),
      word("cybercrime", "/ˈsaɪ.bə.kraɪm/", "tội phạm mạng", "Banks are spending more to fight cybercrime.", "cy|ber|crime", 0),
      word("robber", "/ˈrɒb.ə/", "kẻ cướp", "The robbers escaped in a stolen car.", "rob|ber", 0),
      word("gang", "/ɡæŋ/", "băng nhóm", "A gang of teenagers was causing trouble outside the shop.", "gang", 0),
      word("mug", "/mʌɡ/", "cướp giật (trên đường)", "He was mugged on his way home from work.", "mug", 0),
      word("mugger", "/ˈmʌɡ.ə/", "kẻ cướp giật", "The mugger grabbed her bag and ran.", "mug|ger", 0),
      word("commit", "/kəˈmɪt/", "phạm (tội)", "Most crimes in the area are committed at night.", "com|mit", 1),
      word("ban", "/bæn/", "cấm; lệnh cấm", "Smoking is banned in all public buildings.", "ban", 0),
      word("terrorist", "/ˈter.ə.rɪst/", "kẻ khủng bố", "The terrorist attack killed twenty people.", "ter|ror|ist", 0),
      word("dealer", "/ˈdiː.lə/", "kẻ buôn bán (ma tuý)", "Police arrested two drug dealers near the station.", "deal|er", 0),
      word("attacker", "/əˈtæk.ə/", "kẻ tấn công", "She was able to describe her attacker to the police.", "at|tack|er", 1),
      word("bully", "/ˈbʊl.i/", "bắt nạt; kẻ bắt nạt", "He was bullied at school because of his accent.", "bul|ly", 0, "Chữ u đọc là /ʊ/ như trong 'put', không phải /ʌ/."),
      word("fingerprint", "/ˈfɪŋ.ɡə.prɪnt/", "dấu vân tay", "The police found his fingerprints on the window.", "fin|ger|print", 0),
      word("sentence", "/ˈsen.təns/", "bản án; tuyên án", "He was sentenced to five years in prison.", "sen|tence", 0),
      word("release", "/rɪˈliːs/", "thả, phóng thích", "She was released from prison after three years.", "re|lease", 1),
      word("cell", "/sel/", "phòng giam", "He spent the night in a police cell.", "cell", 0),
      word("suspicion", "/səˈspɪʃ.ən/", "sự nghi ngờ", "He was arrested on suspicion of theft.", "sus|pi|cion", 1),
      word("investigation", "/ɪnˌves.tɪˈɡeɪ.ʃən/", "cuộc điều tra", "The police have started an investigation into the fire.", "in|ves|ti|ga|tion", 3),
      word("proof", "/pruːf/", "bằng chứng", "There is no proof that he took the money.", "proof", 0),
      word("justice", "/ˈdʒʌs.tɪs/", "công lý", "The victims' families want justice.", "jus|tice", 0),
    ],
  },
  {
    id: "moi-truong-khi-hau",
    title: "Môi trường và khí hậu",
    words: [
      word("emission", "/iˈmɪʃ.ən/", "khí thải, sự phát thải", "The country aims to cut carbon emissions by half.", "e|mis|sion", 1),
      word("greenhouse", "/ˈɡriːn.haʊs/", "nhà kính", "Greenhouse gases trap heat in the atmosphere.", "green|house", 0),
      word("deforestation", "/diːˌfɒr.ɪˈsteɪ.ʃən/", "nạn phá rừng", "Deforestation is a major cause of floods.", "de|for|es|ta|tion", 3),
      word("biodiversity", "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/", "đa dạng sinh học", "The national park is rich in biodiversity.", "bi|o|di|ver|si|ty", 3),
      word("renewable", "/rɪˈnjuː.ə.bəl/", "tái tạo được", "Wind and solar are renewable sources of energy.", "re|new|a|ble", 1),
      word("sustainable", "/səˈsteɪ.nə.bəl/", "bền vững", "We need a more sustainable way of farming.", "sus|tain|a|ble", 1),
      word("fossil", "/ˈfɒs.əl/", "hoá thạch", "Burning fossil fuels causes global warming.", "fos|sil", 0),
      word("carbon", "/ˈkɑː.bən/", "các-bon", "Trees absorb carbon dioxide.", "car|bon", 0),
      word("habitat", "/ˈhæb.ɪ.tæt/", "môi trường sống", "The forest is the natural habitat of many birds.", "hab|i|tat", 0),
      word("endangered", "/ɪnˈdeɪn.dʒəd/", "có nguy cơ tuyệt chủng", "The saola is an endangered species.", "en|dan|gered", 1),
      word("extinct", "/ɪkˈstɪŋkt/", "tuyệt chủng", "Dinosaurs became extinct millions of years ago.", "ex|tinct", 1),
      word("ecosystem", "/ˈiː.kəʊˌsɪs.təm/", "hệ sinh thái", "Plastic waste is damaging the ocean ecosystem.", "e|co|sys|tem", 0),
      word("conservation", "/ˌkɒn.səˈveɪ.ʃən/", "sự bảo tồn", "She works for a wildlife conservation group.", "con|ser|va|tion", 2),
      word("landfill", "/ˈlænd.fɪl/", "bãi chôn lấp rác", "Most of our rubbish ends up in landfill.", "land|fill", 0),
      word("toxic", "/ˈtɒk.sɪk/", "độc hại", "The factory was dumping toxic waste into the river.", "tox|ic", 0),
      word("contaminate", "/kənˈtæm.ɪ.neɪt/", "làm ô nhiễm", "The water supply was contaminated with chemicals.", "con|tam|i|nate", 1),
      word("glacier", "/ˈɡlæs.i.ə/", "sông băng", "The glaciers are melting faster than ever.", "gla|ci|er", 0),
      word("erosion", "/ɪˈrəʊ.ʒən/", "sự xói mòn", "Trees help prevent soil erosion.", "e|ro|sion", 1),
      word("pesticide", "/ˈpes.tɪ.saɪd/", "thuốc trừ sâu", "Organic farmers don't use pesticides.", "pes|ti|cide", 0),
      word("turbine", "/ˈtɜː.baɪn/", "tua-bin", "Wind turbines line the coast of Bac Lieu.", "tur|bine", 0),
      word("footprint", "/ˈfʊt.prɪnt/", "dấu chân; lượng phát thải", "Flying less is the easiest way to reduce your carbon footprint.", "foot|print", 0),
      word("biodegradable", "/ˌbaɪ.əʊ.dɪˈɡreɪ.də.bəl/", "phân huỷ sinh học được", "These bags are made from biodegradable material.", "bi|o|de|grad|a|ble", 3),
      word("wasteful", "/ˈweɪst.fəl/", "lãng phí", "It's wasteful to leave the lights on all day.", "waste|ful", 0),
      word("heatwave", "/ˈhiːt.weɪv/", "đợt nắng nóng", "The heatwave lasted for two weeks.", "heat|wave", 0),
      word("polar", "/ˈpəʊ.lə/", "(thuộc) địa cực", "Polar bears are losing their sea ice.", "po|lar", 0),
      word("ozone", "/ˈəʊ.zəʊn/", "tầng ô-dôn, khí ô-dôn", "Some gases damage the ozone layer.", "o|zone", 0),
      word("deplete", "/dɪˈpliːt/", "làm cạn kiệt", "Overfishing has depleted fish stocks.", "de|plete", 1),
      word("compost", "/ˈkɒm.pɒst/", "phân hữu cơ; ủ phân", "We compost all our fruit and vegetable waste.", "com|post", 0),
      word("organic", "/ɔːˈɡæn.ɪk/", "hữu cơ", "Organic vegetables are more expensive.", "or|gan|ic", 1),
      word("smog", "/smɒɡ/", "khói bụi, sương khói ô nhiễm", "Thick smog covered the city this morning.", "smog", 0),
      word("pollute", "/pəˈluːt/", "làm ô nhiễm", "Factories are polluting the river.", "pol|lute", 1),
    ],
  },
  {
    id: "suc-khoe-y-hoc",
    title: "Sức khoẻ và y học",
    words: [
      word("surgery", "/ˈsɜː.dʒər.i/", "ca phẫu thuật", "He needs surgery on his knee.", "sur|ger|y", 0),
      word("allergy", "/ˈæl.ə.dʒi/", "dị ứng", "I have an allergy to peanuts.", "al|ler|gy", 0, "Trọng âm ở âm đầu: A-lờ-dji, không phải a-LE-gy."),
      word("contagious", "/kənˈteɪ.dʒəs/", "dễ lây", "Chickenpox is highly contagious.", "con|ta|gious", 1),
      word("therapy", "/ˈθer.ə.pi/", "liệu pháp, trị liệu", "After the accident he had months of physical therapy.", "ther|a|py", 0),
      word("recovery", "/rɪˈkʌv.ər.i/", "sự hồi phục", "We wish you a speedy recovery.", "re|cov|er|y", 1),
      word("nutrition", "/njuːˈtrɪʃ.ən/", "dinh dưỡng", "Good nutrition is important for growing children.", "nu|tri|tion", 1),
      word("obesity", "/əʊˈbiː.sə.ti/", "bệnh béo phì", "Childhood obesity is becoming more common.", "o|be|si|ty", 1),
      word("disorder", "/dɪˈsɔː.də/", "rối loạn", "He has a rare sleep disorder.", "dis|or|der", 1),
      word("dose", "/dəʊs/", "liều thuốc", "Don't take more than the recommended dose.", "dose", 0),
      word("wound", "/wuːnd/", "vết thương", "The nurse cleaned the wound on his leg.", "wound", 0, "Danh từ 'vết thương' đọc /wuːnd/ (vần 'un'), không phải /waʊnd/."),
      word("bruise", "/bruːz/", "vết bầm tím", "I've got a big bruise on my arm.", "bruise", 0),
      word("sprain", "/spreɪn/", "bong gân", "She sprained her ankle playing basketball.", "sprain", 0),
      word("ward", "/wɔːd/", "khu, phòng bệnh", "My grandfather is on the heart ward on the third floor.", "ward", 0),
      word("epidemic", "/ˌep.ɪˈdem.ɪk/", "dịch bệnh", "There was a flu epidemic in the city last winter.", "ep|i|dem|ic", 2),
      word("fatal", "/ˈfeɪ.təl/", "gây tử vong", "The disease can be fatal if it isn't treated.", "fa|tal", 0),
      word("heal", "/hiːl/", "lành, chữa lành", "The cut healed in a few days.", "heal", 0),
      word("migraine", "/ˈmiː.ɡreɪn/", "chứng đau nửa đầu", "Bright lights sometimes give me a migraine.", "mi|graine", 0),
      word("diabetes", "/ˌdaɪ.əˈbiː.tiːz/", "bệnh tiểu đường", "Too much sugar increases the risk of diabetes.", "di|a|be|tes", 2),
      word("stroke", "/strəʊk/", "đột quỵ", "My uncle had a stroke last year.", "stroke", 0),
      word("painkiller", "/ˈpeɪnˌkɪl.ə/", "thuốc giảm đau", "Take a painkiller if your head still hurts.", "pain|kill|er", 0),
      word("hygiene", "/ˈhaɪ.dʒiːn/", "vệ sinh", "Good hygiene helps stop the spread of disease.", "hy|giene", 0),
      word("fatigue", "/fəˈtiːɡ/", "sự mệt mỏi", "Symptoms include fever and fatigue.", "fa|tigue", 1, "Trọng âm ở âm cuối: fờ-TIIG; ue không đọc."),
      word("faint", "/feɪnt/", "ngất xỉu", "She fainted because of the heat.", "faint", 0),
      word("swollen", "/ˈswəʊ.lən/", "bị sưng", "My ankle is still swollen.", "swol|len", 0),
      word("pregnancy", "/ˈpreɡ.nən.si/", "thai kỳ", "Women shouldn't drink alcohol during pregnancy.", "preg|nan|cy", 0),
      word("lung", "/lʌŋ/", "phổi", "Smoking damages your lungs.", "lung", 0),
      word("disability", "/ˌdɪs.əˈbɪl.ə.ti/", "khuyết tật", "The school welcomes children with disabilities.", "dis|a|bil|i|ty", 2),
      word("unconscious", "/ʌnˈkɒn.ʃəs/", "bất tỉnh", "He was knocked unconscious in the accident.", "un|con|scious", 1),
      word("germ", "/dʒɜːm/", "vi trùng", "Wash your hands to kill germs.", "germ", 0),
      word("specialist", "/ˈspeʃ.əl.ɪst/", "bác sĩ chuyên khoa, chuyên gia", "My doctor sent me to see a heart specialist.", "spe|cial|ist", 0),
      word("pulse", "/pʌls/", "mạch (đập)", "The nurse took my pulse.", "pulse", 0),
      word("therapist", "/ˈθer.ə.pɪst/", "nhà trị liệu", "She sees a therapist once a week.", "ther|a|pist", 0),
    ],
  },
  {
    id: "truyen-thong-quang-cao",
    title: "Truyền thông và quảng cáo",
    words: [
      word("broadcast", "/ˈbrɔːd.kɑːst/", "phát sóng; chương trình phát sóng", "The final will be broadcast live on TV.", "broad|cast", 0),
      word("tabloid", "/ˈtæb.lɔɪd/", "báo lá cải", "The tabloids are full of celebrity gossip.", "tab|loid", 0),
      word("censorship", "/ˈsen.sə.ʃɪp/", "sự kiểm duyệt", "Writers protested against censorship of the internet.", "cen|sor|ship", 0),
      word("coverage", "/ˈkʌv.ər.ɪdʒ/", "sự đưa tin", "The election received a lot of media coverage.", "cov|er|age", 0),
      word("correspondent", "/ˌkɒr.ɪˈspɒn.dənt/", "phóng viên thường trú", "Our correspondent in Tokyo sent this report.", "cor|re|spon|dent", 2),
      word("commercial", "/kəˈmɜː.ʃəl/", "quảng cáo trên TV/radio; thương mại", "They showed the same commercial ten times during the match.", "com|mer|cial", 1),
      word("slogan", "/ˈsləʊ.ɡən/", "khẩu hiệu", "The company changed its advertising slogan.", "slo|gan", 0),
      word("sponsor", "/ˈspɒn.sə/", "nhà tài trợ; tài trợ", "The festival is sponsored by a local bank.", "spon|sor", 0),
      word("publicity", "/pʌbˈlɪs.ə.ti/", "sự quảng bá, sự chú ý của công chúng", "The scandal gave the film a lot of free publicity.", "pub|lic|i|ty", 1),
      word("viral", "/ˈvaɪ.rəl/", "lan truyền nhanh", "Her video went viral overnight.", "vi|ral", 0),
      word("influencer", "/ˈɪn.flu.ən.sə/", "người có sức ảnh hưởng (trên mạng)", "Brands pay influencers to promote their products.", "in|flu|en|cer", 0),
      word("subscriber", "/səbˈskraɪ.bə/", "người đăng ký theo dõi", "His channel has a million subscribers.", "sub|scrib|er", 1),
      word("podcast", "/ˈpɒd.kɑːst/", "chương trình âm thanh podcast", "I listen to an English podcast on the way to work.", "pod|cast", 0),
      word("billboard", "/ˈbɪl.bɔːd/", "biển quảng cáo lớn", "A giant billboard advertises the new phone.", "bill|board", 0),
      word("persuasive", "/pəˈsweɪ.sɪv/", "có sức thuyết phục", "The advert is very persuasive.", "per|sua|sive", 1),
      word("misleading", "/ˌmɪsˈliː.dɪŋ/", "gây hiểu lầm", "The claims in the advert were misleading.", "mis|lead|ing", 1),
      word("logo", "/ˈləʊ.ɡəʊ/", "biểu tượng, lô-gô", "The logo is printed on every bag.", "lo|go", 0),
      word("columnist", "/ˈkɒl.əm.nɪst/", "người viết chuyên mục", "She is a columnist for a national newspaper.", "col|um|nist", 0, "Chữ n được đọc ở đây: KOL-ầm-nist, dù trong 'column' thì n câm."),
      word("exclusive", "/ɪkˈskluː.sɪv/", "độc quyền, tin độc quyền", "The magazine has an exclusive interview with the singer.", "ex|clu|sive", 1),
      word("sensational", "/senˈseɪ.ʃən.əl/", "giật gân", "I don't trust sensational headlines.", "sen|sa|tion|al", 1),
      word("journalism", "/ˈdʒɜː.nə.lɪ.zəm/", "nghề báo", "She studied journalism in Ho Chi Minh City.", "jour|na|li|sm", 0),
      word("commentator", "/ˈkɒm.ən.teɪ.tə/", "bình luận viên", "The football commentator got very excited.", "com|men|ta|tor", 0),
      word("spokesperson", "/ˈspəʊksˌpɜː.sən/", "người phát ngôn", "A spokesperson for the company refused to comment.", "spokes|per|son", 0),
      word("newsletter", "/ˈnjuːzˌlet.ə/", "bản tin", "Sign up for our weekly newsletter.", "news|let|ter", 0),
      word("manipulate", "/məˈnɪp.jə.leɪt/", "thao túng", "Some adverts manipulate our emotions.", "ma|nip|u|late", 1),
      word("publisher", "/ˈpʌb.lɪ.ʃə/", "nhà xuất bản", "She sent her novel to three publishers.", "pub|lish|er", 0),
      word("edition", "/ɪˈdɪʃ.ən/", "ấn bản, số báo", "The story was on the front page of today's edition.", "e|di|tion", 1),
      word("viewer", "/ˈvjuː.ə/", "khán giả truyền hình", "The show attracts millions of viewers.", "view|er", 0),
      word("listener", "/ˈlɪs.ən.ə/", "thính giả", "The radio station has two million listeners.", "lis|ten|er", 0, "Chữ t không đọc: LIS-ần-ờ."),
      word("advertiser", "/ˈæd.və.taɪ.zə/", "nhà quảng cáo", "Advertisers target young people on social media.", "ad|ver|tis|er", 0),
      word("journal", "/ˈdʒɜː.nəl/", "tạp chí chuyên ngành", "The study was published in a medical journal.", "jour|nal", 0),
    ],
  },
  {
    id: "cong-viec-su-nghiep",
    title: "Công việc và sự nghiệp",
    words: [
      word("recruit", "/rɪˈkruːt/", "tuyển dụng", "We're recruiting three new engineers.", "re|cruit", 1),
      word("resign", "/rɪˈzaɪn/", "từ chức, xin nghỉ việc", "She resigned because of the long hours.", "re|sign", 1, "Chữ g không đọc, s đọc là /z/: ri-ZAIN."),
      word("appraisal", "/əˈpreɪ.zəl/", "buổi đánh giá năng lực", "I have my annual appraisal with my manager next week.", "ap|prais|al", 1),
      word("workload", "/ˈwɜːk.ləʊd/", "khối lượng công việc", "My workload has doubled since my colleague left.", "work|load", 0),
      word("internship", "/ˈɪn.tɜːn.ʃɪp/", "kỳ thực tập", "He did a six-month internship at a bank.", "in|tern|ship", 0),
      word("apprentice", "/əˈpren.tɪs/", "người học việc", "He started as an apprentice electrician.", "ap|pren|tice", 1),
      word("vacancy", "/ˈveɪ.kən.si/", "vị trí còn trống", "We have a vacancy for a sales assistant.", "va|can|cy", 0),
      word("pension", "/ˈpen.ʃən/", "lương hưu", "My parents live on their pensions.", "pen|sion", 0),
      word("bonus", "/ˈbəʊ.nəs/", "tiền thưởng", "Everyone got a bonus at the end of the year.", "bo|nus", 0),
      word("perk", "/pɜːk/", "phúc lợi thêm", "Free lunch is one of the perks of the job.", "perk", 0),
      word("freelance", "/ˈfriː.lɑːns/", "làm tự do", "She works freelance as a translator.", "free|lance", 0),
      word("supervisor", "/ˈsuː.pə.vaɪ.zə/", "người giám sát", "Ask your supervisor if you can leave early.", "su|per|vi|sor", 0),
      word("teamwork", "/ˈtiːm.wɜːk/", "tinh thần đồng đội", "The project succeeded thanks to good teamwork.", "team|work", 0),
      word("initiative", "/ɪˈnɪʃ.ə.tɪv/", "sự chủ động, sáng kiến", "She showed initiative by solving the problem herself.", "i|ni|tia|tive", 1),
      word("competent", "/ˈkɒm.pɪ.tənt/", "có năng lực, thạo việc", "He's a very competent accountant.", "com|pe|tent", 0),
      word("diligent", "/ˈdɪl.ɪ.dʒənt/", "siêng năng, cần mẫn", "She is a diligent and careful worker.", "dil|i|gent", 0),
      word("multitask", "/ˌmʌl.tiˈtɑːsk/", "làm nhiều việc cùng lúc", "In this job you have to be able to multitask.", "mul|ti|task", 2),
      word("burnout", "/ˈbɜːn.aʊt/", "tình trạng kiệt sức vì công việc", "Working seventy hours a week led to burnout.", "burn|out", 0),
      word("dismiss", "/dɪˈsmɪs/", "sa thải; gạt bỏ", "He was dismissed for stealing from the company.", "dis|miss", 1),
      word("probation", "/prəˈbeɪ.ʃən/", "thời gian thử việc", "New staff are on probation for two months.", "pro|ba|tion", 1),
      word("occupation", "/ˌɒk.jəˈpeɪ.ʃən/", "nghề nghiệp", "Please write your name and occupation on the form.", "oc|cu|pa|tion", 2),
      word("executive", "/ɪɡˈzek.jə.tɪv/", "giám đốc điều hành, cán bộ quản lý", "She is a senior executive at a car company.", "ex|ec|u|tive", 1),
      word("workplace", "/ˈwɜːk.pleɪs/", "nơi làm việc", "Bullying in the workplace is not acceptable.", "work|place", 0),
      word("commitment", "/kəˈmɪt.mənt/", "sự tận tâm, cam kết", "We thank her for her commitment to the team.", "com|mit|ment", 1),
      word("expertise", "/ˌek.spɜːˈtiːz/", "chuyên môn", "We need someone with expertise in marketing.", "ex|per|tise", 2),
      word("mentor", "/ˈmen.tɔː/", "người hướng dẫn, cố vấn", "My mentor taught me how to deal with clients.", "men|tor", 0),
      word("trainee", "/ˌtreɪˈniː/", "thực tập sinh, người được đào tạo", "She joined the bank as a trainee manager.", "train|ee", 1),
      word("earnings", "/ˈɜː.nɪŋz/", "thu nhập", "His earnings have doubled in five years.", "earn|ings", 0),
      word("labour", "/ˈleɪ.bə/", "sức lao động, nhân công", "Labour costs are lower in rural areas.", "la|bour", 0),
      word("permanent", "/ˈpɜː.mə.nənt/", "lâu dài, cố định", "After a year, she was offered a permanent contract.", "per|ma|nent", 0),
      word("temporary", "/ˈtem.pər.ər.i/", "tạm thời", "He found a temporary job for the summer.", "tem|po|rar|y", 0),
    ],
  },
  {
    id: "tam-ly-hanh-vi",
    title: "Tâm lý và hành vi",
    words: [
      word("anxiety", "/æŋˈzaɪ.ə.ti/", "sự lo âu", "Exams cause a lot of anxiety for students.", "anx|i|e|ty", 1, "Chữ x ở đây đọc là /z/: ang-ZAI-ờ-ti."),
      word("motivation", "/ˌməʊ.tɪˈveɪ.ʃən/", "động lực", "I've lost my motivation to study.", "mo|ti|va|tion", 2),
      word("subconscious", "/sʌbˈkɒn.ʃəs/", "tiềm thức", "Dreams may reveal our subconscious fears.", "sub|con|scious", 1),
      word("self-esteem", "/ˌself.ɪˈstiːm/", "lòng tự trọng, sự tự tin vào bản thân", "Praise can help build a child's self-esteem.", "self|es|teem", 2),
      word("frustration", "/frʌsˈtreɪ.ʃən/", "sự bực bội, thất vọng", "He shouted in frustration when the computer crashed.", "frus|tra|tion", 1),
      word("insecure", "/ˌɪn.sɪˈkjʊə/", "thiếu tự tin, bất an", "She feels insecure about her appearance.", "in|se|cure", 2),
      word("temper", "/ˈtem.pə/", "tính khí; cơn nóng giận", "He lost his temper and slammed the door.", "tem|per", 0),
      word("cope", "/kəʊp/", "đương đầu, xoay xở", "How do you cope with stress?", "cope", 0),
      word("overwhelmed", "/ˌəʊ.vəˈwelmd/", "bị choáng ngợp, quá tải", "I felt overwhelmed by all the work.", "o|ver|whelmed", 2),
      word("phobia", "/ˈfəʊ.bi.ə/", "nỗi ám ảnh sợ hãi", "She has a phobia of spiders.", "pho|bi|a", 0),
      word("mindset", "/ˈmaɪnd.set/", "tư duy, lối suy nghĩ", "A positive mindset helps you learn faster.", "mind|set", 0),
      word("procrastinate", "/prəˈkræs.tɪ.neɪt/", "trì hoãn", "I always procrastinate when I have an essay to write.", "pro|cras|ti|nate", 1),
      word("addiction", "/əˈdɪk.ʃən/", "sự nghiện", "Phone addiction is a real problem among teenagers.", "ad|dic|tion", 1),
      word("obsessed", "/əbˈsest/", "bị ám ảnh, mê mẩn", "He's obsessed with football.", "ob|sessed", 1),
      word("peer", "/pɪə/", "người cùng trang lứa", "Teenagers often feel pressure from their peers.", "peer", 0),
      word("conform", "/kənˈfɔːm/", "tuân theo, làm theo số đông", "Students feel they have to conform to fit in.", "con|form", 1),
      word("envy", "/ˈen.vi/", "sự ghen tị; ghen tị", "I envy people who can sleep anywhere.", "en|vy", 0),
      word("jealousy", "/ˈdʒel.ə.si/", "sự ghen tị, ghen tuông", "Jealousy ruined their friendship.", "jeal|ou|sy", 0),
      word("pessimistic", "/ˌpes.ɪˈmɪs.tɪk/", "bi quan", "He's pessimistic about his chances of getting the job.", "pes|si|mis|tic", 2),
      word("tendency", "/ˈten.dən.si/", "xu hướng, khuynh hướng", "She has a tendency to worry too much.", "ten|den|cy", 0),
      word("curiosity", "/ˌkjʊə.riˈɒs.ə.ti/", "sự tò mò", "Children learn a lot through curiosity.", "cu|ri|os|i|ty", 2),
      word("gratitude", "/ˈɡræt.ɪ.tʃuːd/", "lòng biết ơn", "I wrote her a letter to express my gratitude.", "grat|i|tude", 0),
      word("emotional", "/ɪˈməʊ.ʃən.əl/", "xúc động; (thuộc) cảm xúc", "She became very emotional when she said goodbye.", "e|mo|tion|al", 1),
      word("courage", "/ˈkʌr.ɪdʒ/", "lòng can đảm", "It took courage to speak in front of everyone.", "cour|age", 0, "ou đọc là /ʌ/: KA-rij, trọng âm ở âm đầu."),
      word("patience", "/ˈpeɪ.ʃəns/", "sự kiên nhẫn", "Learning a language takes time and patience.", "pa|tience", 0),
      word("panic", "/ˈpæn.ɪk/", "hoảng loạn", "Don't panic if you forget a word.", "pan|ic", 0),
      word("guilt", "/ɡɪlt/", "cảm giác tội lỗi", "She felt a lot of guilt about leaving her children.", "guilt", 0, "Chữ u không đọc: /ɡɪlt/."),
      word("shame", "/ʃeɪm/", "sự xấu hổ", "He hid his face in shame.", "shame", 0),
      word("embarrassment", "/ɪmˈbær.əs.mənt/", "sự ngượng ngùng", "Her face went red with embarrassment.", "em|bar|rass|ment", 1),
      word("relief", "/rɪˈliːf/", "sự nhẹ nhõm", "It was a relief to hear that everyone was safe.", "re|lief", 1),
      word("satisfaction", "/ˌsæt.ɪsˈfæk.ʃən/", "sự hài lòng", "Helping others gives me a lot of satisfaction.", "sat|is|fac|tion", 2),
      word("sympathy", "/ˈsɪm.pə.θi/", "sự cảm thông", "I have a lot of sympathy for people who lose their jobs.", "sym|pa|thy", 0),
    ],
  },
  {
    id: "giao-duc-nghien-cuu",
    title: "Giáo dục và nghiên cứu",
    words: [
      word("curriculum", "/kəˈrɪk.jə.ləm/", "chương trình giảng dạy", "Coding is now part of the school curriculum.", "cur|ric|u|lum", 1),
      word("tuition", "/tʃuːˈɪʃ.ən/", "học phí; sự dạy kèm", "Tuition fees have risen again this year.", "tu|i|tion", 1),
      word("undergraduate", "/ˌʌn.dəˈɡrædʒ.u.ət/", "sinh viên đại học (chưa tốt nghiệp)", "She is an undergraduate at Hanoi University.", "un|der|grad|u|ate", 2),
      word("postgraduate", "/ˌpəʊstˈɡrædʒ.u.ət/", "sau đại học", "He's doing a postgraduate course in law.", "post|grad|u|ate", 1),
      word("dissertation", "/ˌdɪs.əˈteɪ.ʃən/", "luận văn", "I'm writing my dissertation on climate policy.", "dis|ser|ta|tion", 2),
      word("lecturer", "/ˈlek.tʃər.ə/", "giảng viên đại học", "She's a lecturer in economics.", "lec|tur|er", 0),
      word("seminar", "/ˈsem.ɪ.nɑː/", "buổi thảo luận chuyên đề", "We have a seminar on Thursday afternoons.", "sem|i|nar", 0),
      word("assessment", "/əˈses.mənt/", "sự đánh giá", "Assessment is based on coursework and a final exam.", "as|sess|ment", 1),
      word("literacy", "/ˈlɪt.ər.ə.si/", "khả năng đọc viết", "The country has a literacy rate of over 95 per cent.", "lit|er|a|cy", 0),
      word("faculty", "/ˈfæk.əl.ti/", "khoa (đại học); đội ngũ giảng viên", "He works in the Faculty of Medicine.", "fac|ul|ty", 0),
      word("academic", "/ˌæk.əˈdem.ɪk/", "(thuộc) học thuật", "Her academic results are excellent.", "ac|a|dem|ic", 2),
      word("survey", "/ˈsɜː.veɪ/", "cuộc khảo sát", "We did a survey of 500 students.", "sur|vey", 0),
      word("findings", "/ˈfaɪn.dɪŋz/", "kết quả nghiên cứu", "The findings will be published next month.", "find|ings", 0),
      word("sample", "/ˈsɑːm.pəl/", "mẫu (nghiên cứu, thử nghiệm)", "The study used a sample of 1,000 adults.", "sam|ple", 0),
      word("questionnaire", "/ˌkwes.tʃəˈneə/", "bảng câu hỏi", "Please fill in this short questionnaire.", "ques|tion|naire", 2),
      word("analysis", "/əˈnæl.ə.sɪs/", "sự phân tích", "A careful analysis of the data showed a clear pattern.", "a|nal|y|sis", 1),
      word("reference", "/ˈref.ər.əns/", "tài liệu tham khảo; sự đề cập", "Include a list of references at the end of your essay.", "ref|er|ence", 0),
      word("bibliography", "/ˌbɪb.liˈɒɡ.rə.fi/", "thư mục tài liệu", "Every thesis must have a bibliography.", "bib|li|og|ra|phy", 2),
      word("scholar", "/ˈskɒl.ə/", "học giả", "He is a respected scholar of Asian history.", "schol|ar", 0, "ch đọc là /k/: SKOL-ờ."),
      word("compulsory", "/kəmˈpʌl.sər.i/", "bắt buộc", "English is a compulsory subject in secondary school.", "com|pul|sor|y", 1),
      word("attendance", "/əˈten.dəns/", "sự có mặt, chuyên cần", "Attendance at all lectures is expected.", "at|tend|ance", 1),
      word("vocational", "/vəʊˈkeɪ.ʃən.əl/", "(thuộc) dạy nghề", "He went to a vocational school to train as a chef.", "vo|ca|tion|al", 1),
      word("conduct", "/kənˈdʌkt/", "tiến hành", "The researchers conducted interviews with 50 teachers.", "con|duct", 1),
      word("coursework", "/ˈkɔːs.wɜːk/", "bài tập tính điểm trong khoá học", "Coursework counts for 40 per cent of the final grade.", "course|work", 0),
      word("educational", "/ˌedʒ.ʊˈkeɪ.ʃən.əl/", "(mang tính) giáo dục", "The museum is fun and educational for children.", "ed|u|ca|tion|al", 2),
      word("intelligence", "/ɪnˈtel.ɪ.dʒəns/", "trí thông minh", "He is a man of great intelligence.", "in|tel|li|gence", 1),
      word("institute", "/ˈɪn.stɪ.tʃuːt/", "viện", "She works at a research institute in Hanoi.", "in|sti|tute", 0),
      word("discipline", "/ˈdɪs.ə.plɪn/", "kỷ luật", "The school is known for its strict discipline.", "dis|ci|pline", 0),
      word("educate", "/ˈedʒ.u.keɪt/", "giáo dục, dạy dỗ", "She was educated in Australia.", "ed|u|cate", 0),
      word("bachelor", "/ˈbætʃ.əl.ə/", "cử nhân", "He has a bachelor's degree in economics.", "bach|el|or", 0),
      word("kindergarten", "/ˈkɪn.dəˌɡɑː.tən/", "trường mẫu giáo", "My daughter starts kindergarten next month.", "kin|der|gar|ten", 0),
    ],
  },
  {
    id: "du-lich-nganh-du-lich",
    title: "Du lịch và ngành du lịch",
    words: [
      word("hospitality", "/ˌhɒs.pɪˈtæl.ə.ti/", "lòng hiếu khách; ngành nhà hàng khách sạn", "She wants a career in hospitality.", "hos|pi|tal|i|ty", 2),
      word("excursion", "/ɪkˈskɜː.ʃən/", "chuyến tham quan ngắn", "We went on an excursion to Ha Long Bay.", "ex|cur|sion", 1),
      word("backpacker", "/ˈbækˌpæk.ə/", "khách du lịch ba lô", "The old quarter is full of cheap hostels for backpackers.", "back|pack|er", 0),
      word("landmark", "/ˈlænd.mɑːk/", "địa danh nổi tiếng", "The Eiffel Tower is the most famous landmark in Paris.", "land|mark", 0),
      word("stopover", "/ˈstɒpˌəʊ.və/", "điểm dừng chân (quá cảnh)", "We had a two-day stopover in Singapore.", "stop|o|ver", 0),
      word("boarding", "/ˈbɔː.dɪŋ/", "việc lên máy bay", "Boarding starts thirty minutes before departure.", "board|ing", 0),
      word("ecotourism", "/ˈiː.kəʊˌtʊə.rɪ.zəm/", "du lịch sinh thái", "Ecotourism brings money to local villages without harming nature.", "e|co|tou|ri|sm", 0),
      word("off-season", "/ˌɒfˈsiː.zən/", "mùa thấp điểm", "Hotels are much cheaper in the off-season.", "off|sea|son", 1),
      word("overbooked", "/ˌəʊ.vəˈbʊkt/", "bị đặt quá chỗ", "The flight was overbooked, so we had to wait for the next one.", "o|ver|booked", 2),
      word("amenity", "/əˈmiː.nə.ti/", "tiện nghi", "The hotel has excellent amenities, including a pool and a gym.", "a|men|i|ty", 1),
      word("exotic", "/ɪɡˈzɒt.ɪk/", "kỳ lạ, đậm chất ngoại quốc", "We tried lots of exotic fruits at the market.", "ex|ot|ic", 1),
      word("picturesque", "/ˌpɪk.tʃərˈesk/", "đẹp như tranh", "Sa Pa is a picturesque mountain town.", "pic|tur|esque", 2),
      word("overseas", "/ˌəʊ.vəˈsiːz/", "ở nước ngoài", "More Vietnamese people are travelling overseas.", "o|ver|seas", 2),
      word("voyage", "/ˈvɔɪ.ɪdʒ/", "chuyến đi biển dài", "The voyage across the Pacific took three weeks.", "voy|age", 0),
      word("expedition", "/ˌek.spəˈdɪʃ.ən/", "cuộc thám hiểm", "They joined an expedition to Son Doong Cave.", "ex|pe|di|tion", 2),
      word("hitchhike", "/ˈhɪtʃ.haɪk/", "đi nhờ xe", "He hitchhiked across Europe when he was a student.", "hitch|hike", 0),
      word("upmarket", "/ˌʌpˈmɑː.kɪt/", "cao cấp", "They stayed in an upmarket hotel near the lake.", "up|mar|ket", 1),
      word("touristy", "/ˈtʊə.rɪ.sti/", "quá đông khách du lịch, mang tính thương mại", "The town has become too touristy for my taste.", "tou|ris|ty", 0),
      word("getaway", "/ˈɡet.ə.weɪ/", "kỳ nghỉ ngắn", "Da Lat is perfect for a weekend getaway.", "get|a|way", 0),
      word("embark", "/ɪmˈbɑːk/", "lên tàu; bắt đầu", "Passengers can embark from two o'clock.", "em|bark", 1),
      word("unspoilt", "/ʌnˈspɔɪlt/", "còn hoang sơ", "The island has unspoilt beaches.", "un|spoilt", 1),
      word("tourism", "/ˈtʊə.rɪ.zəm/", "ngành du lịch", "Tourism is an important part of the economy.", "tou|ri|sm", 0),
      word("breathtaking", "/ˈbreθˌteɪ.kɪŋ/", "đẹp ngoạn mục", "The view from the top was breathtaking.", "breath|tak|ing", 0),
      word("jet-lagged", "/ˈdʒet.læɡd/", "bị mệt vì lệch múi giờ", "I was too jet-lagged to go out on the first night.", "jet|lagged", 0),
      word("cuisine", "/kwɪˈziːn/", "ẩm thực", "Many tourists come to Vietnam for its cuisine.", "cui|sine", 1),
      word("lounge", "/laʊndʒ/", "phòng chờ", "We waited in the departure lounge for two hours.", "lounge", 0),
      word("trek", "/trek/", "chuyến đi bộ đường dài", "We went on a three-day trek through the mountains.", "trek", 0),
      word("self-catering", "/ˌselfˈkeɪ.tər.ɪŋ/", "(chỗ ở) tự nấu ăn", "We rented a self-catering apartment by the beach.", "self|ca|ter|ing", 1),
      word("tan", "/tæn/", "làn da rám nắng", "She came back from Nha Trang with a lovely tan.", "tan", 0),
    ],
  },
  {
    id: "xu-huong-thay-doi",
    title: "Mô tả xu hướng và thay đổi",
    words: [
      word("trend", "/trend/", "xu hướng", "There is a growing trend towards working from home.", "trend", 0),
      word("surge", "/sɜːdʒ/", "sự tăng vọt; tăng vọt", "There was a surge in demand for face masks.", "surge", 0),
      word("plummet", "/ˈplʌm.ɪt/", "giảm mạnh, tụt dốc", "House prices plummeted after the crisis.", "plum|met", 0),
      word("dip", "/dɪp/", "sự giảm nhẹ; giảm nhẹ", "Sales dipped slightly in March.", "dip", 0),
      word("plunge", "/plʌndʒ/", "lao dốc, giảm đột ngột", "The value of the currency plunged overnight.", "plunge", 0),
      word("stabilise", "/ˈsteɪ.bəl.aɪz/", "ổn định", "Prices have stabilised after a difficult year.", "sta|bi|lise", 0),
      word("dramatic", "/drəˈmæt.ɪk/", "mạnh mẽ, đột ngột", "There has been a dramatic increase in crime.", "dra|mat|ic", 1),
      word("considerable", "/kənˈsɪd.ər.ə.bəl/", "đáng kể", "The project cost a considerable amount of money.", "con|sid|er|a|ble", 1),
      word("steadily", "/ˈsted.əl.i/", "một cách đều đặn", "The number of visitors has risen steadily.", "stead|i|ly", 0),
      word("substantial", "/səbˈstæn.ʃəl/", "lớn, đáng kể", "She received a substantial pay rise.", "sub|stan|tial", 1),
      word("rapid", "/ˈræp.ɪd/", "nhanh chóng", "The city has seen rapid growth in recent years.", "rap|id", 0),
      word("escalate", "/ˈes.kə.leɪt/", "leo thang", "The argument quickly escalated into a fight.", "es|ca|late", 0),
      word("diminish", "/dɪˈmɪn.ɪʃ/", "giảm bớt, suy giảm", "The pain diminished after a few days.", "di|min|ish", 1),
      word("halve", "/hɑːv/", "giảm một nửa", "The company has halved its costs.", "halve", 0, "Chữ l không đọc: /hɑːv/, giống 'half' nhưng kết thúc bằng /v/."),
      word("shrink", "/ʃrɪŋk/", "co lại, thu hẹp", "The market for DVDs has shrunk.", "shrink", 0),
      word("expand", "/ɪkˈspænd/", "mở rộng", "The business expanded into China last year.", "ex|pand", 1),
      word("evolve", "/ɪˈvɒlv/", "tiến hoá, phát triển dần", "The company has evolved from a small shop into a big chain.", "e|volve", 1),
      word("transform", "/trænsˈfɔːm/", "biến đổi hoàn toàn", "The internet has transformed the way we shop.", "trans|form", 1),
      word("alter", "/ˈɒl.tə/", "thay đổi, sửa đổi", "We had to alter our plans because of the weather.", "al|ter", 0),
      word("modify", "/ˈmɒd.ɪ.faɪ/", "điều chỉnh", "The design was modified to make it safer.", "mod|i|fy", 0),
      word("upward", "/ˈʌp.wəd/", "đi lên", "The graph shows an upward trend in sales.", "up|ward", 0),
      word("downturn", "/ˈdaʊn.tɜːn/", "sự suy giảm (kinh tế)", "Many people lost their jobs in the economic downturn.", "down|turn", 0),
      word("revolution", "/ˌrev.əˈluː.ʃən/", "cuộc cách mạng", "Smartphones started a revolution in communication.", "rev|o|lu|tion", 2),
      word("constant", "/ˈkɒn.stənt/", "không đổi; liên tục", "The temperature is kept constant at 20 degrees.", "con|stant", 0),
      word("outnumber", "/ˌaʊtˈnʌm.bə/", "đông hơn, nhiều hơn", "Women now outnumber men at the university.", "out|num|ber", 1),
      word("boost", "/buːst/", "thúc đẩy, làm tăng", "The festival boosted local tourism.", "boost", 0),
      word("decrease", "/dɪˈkriːs/", "giảm", "The number of smokers has decreased.", "de|crease", 1),
      word("reduction", "/rɪˈdʌk.ʃən/", "sự giảm", "There has been a reduction in traffic since the metro opened.", "re|duc|tion", 1),
      word("noticeable", "/ˈnəʊ.tɪ.sə.bəl/", "dễ nhận thấy", "There has been a noticeable improvement in her English.", "no|tice|a|ble", 0),
      word("growth", "/ɡrəʊθ/", "sự tăng trưởng", "The economy saw strong growth last year.", "growth", 0),
      word("stable", "/ˈsteɪ.bəl/", "ổn định", "Prices have remained stable this year.", "sta|ble", 0),
    ],
  },
  {
    id: "tinh-cach-moi-quan-he",
    title: "Tính cách và các mối quan hệ",
    words: [
      word("stubborn", "/ˈstʌb.ən/", "bướng bỉnh", "He's too stubborn to admit he was wrong.", "stub|born", 0),
      word("arrogant", "/ˈær.ə.ɡənt/", "kiêu ngạo", "I found him rude and arrogant.", "ar|ro|gant", 0),
      word("compassionate", "/kəmˈpæʃ.ən.ət/", "giàu lòng trắc ẩn", "She is a kind and compassionate doctor.", "com|pas|sion|ate", 1),
      word("considerate", "/kənˈsɪd.ər.ət/", "chu đáo, biết nghĩ cho người khác", "It was very considerate of you to call.", "con|sid|er|ate", 1),
      word("loyal", "/ˈlɔɪ.əl/", "trung thành", "He has always been a loyal friend.", "loy|al", 0),
      word("sincere", "/sɪnˈsɪə/", "chân thành", "Please accept my sincere apologies.", "sin|cere", 1),
      word("extrovert", "/ˈek.strə.vɜːt/", "người hướng ngoại", "My sister is a real extrovert who loves meeting people.", "ex|tro|vert", 0),
      word("bossy", "/ˈbɒs.i/", "hách dịch, thích sai khiến", "My older brother was always bossy.", "boss|y", 0),
      word("naive", "/naɪˈiːv/", "ngây thơ, cả tin", "It was naive of me to believe him.", "na|ive", 1, "Hai âm tiết: nai-IIV, trọng âm ở âm thứ hai."),
      word("trustworthy", "/ˈtrʌstˌwɜː.ði/", "đáng tin cậy", "She's honest and trustworthy.", "trust|wor|thy", 0),
      word("self-centred", "/ˌselfˈsen.təd/", "ích kỷ, chỉ nghĩ đến bản thân", "He's too self-centred to notice other people's problems.", "self|cen|tred", 1),
      word("bond", "/bɒnd/", "sự gắn bó; mối liên kết", "There is a strong bond between the twins.", "bond", 0),
      word("acquaintance", "/əˈkweɪn.təns/", "người quen", "He's not a close friend, just an acquaintance.", "ac|quaint|ance", 1),
      word("companion", "/kəmˈpæn.jən/", "bạn đồng hành", "My dog is my constant companion.", "com|pan|ion", 1),
      word("engagement", "/ɪnˈɡeɪdʒ.mənt/", "sự đính hôn", "They announced their engagement at Christmas.", "en|gage|ment", 1),
      word("upbringing", "/ˈʌpˌbrɪŋ.ɪŋ/", "sự nuôi dạy", "She had a strict upbringing.", "up|bring|ing", 0),
      word("betray", "/bɪˈtreɪ/", "phản bội", "I felt betrayed when she told everyone my secret.", "be|tray", 1),
      word("flatter", "/ˈflæt.ə/", "tâng bốc, khen nịnh", "He flattered her by saying she looked twenty.", "flat|ter", 0),
      word("quarrel", "/ˈkwɒr.əl/", "cuộc cãi vã; cãi nhau", "They had a quarrel about money.", "quar|rel", 0),
      word("mature", "/məˈtʃʊə/", "chín chắn, trưởng thành", "She's very mature for her age.", "ma|ture", 1),
      word("witty", "/ˈwɪt.i/", "dí dỏm", "He gave a witty speech at the wedding.", "wit|ty", 0),
      word("tolerant", "/ˈtɒl.ər.ənt/", "khoan dung, bao dung", "We should be tolerant of other people's opinions.", "tol|er|ant", 0),
      word("grumpy", "/ˈɡrʌm.pi/", "cáu kỉnh", "My dad is always grumpy in the morning.", "grum|py", 0),
      word("possessive", "/pəˈzes.ɪv/", "chiếm hữu, hay ghen", "Her boyfriend is very possessive.", "pos|ses|sive", 1),
      word("rebellious", "/rɪˈbel.i.əs/", "nổi loạn", "He was a rebellious teenager.", "re|bel|li|ous", 1),
      word("honesty", "/ˈɒn.ə.sti/", "sự trung thực", "I value honesty more than anything in a friend.", "hon|es|ty", 0, "Chữ h không đọc: O-nờ-sti."),
      word("romance", "/rəʊˈmæns/", "chuyện tình lãng mạn", "Their holiday romance turned into a marriage.", "ro|mance", 1),
      word("aggressive", "/əˈɡres.ɪv/", "hung hăng", "He becomes aggressive when he's drunk.", "ag|gres|sive", 1),
      word("enthusiastic", "/ɪnˌθjuː.ziˈæs.tɪk/", "nhiệt tình", "The students are enthusiastic about the project.", "en|thu|si|as|tic", 3),
      word("faithful", "/ˈfeɪθ.fəl/", "chung thuỷ, trung thành", "He remained faithful to his wife.", "faith|ful", 0),
      word("humorous", "/ˈhjuː.mər.əs/", "hài hước", "She wrote a humorous article about her first job.", "hu|mor|ous", 0),
    ],
  },
];

export default topics;
