import { word } from "../builders";
import type { WordTopic } from "../types";

/** Extra C1 vocabulary by topic, reviewed with spaced repetition (see /tu-vung). */
const topics: WordTopic[] = [
  {
    id: "khoa-hoc-cong-nghe",
    title: "Khoa học và công nghệ",
    words: [
      word("empirical", "/ɪmˈpɪr.ɪ.kəl/", "dựa trên thực nghiệm", "There is little empirical evidence to support the theory.", "em|pir|i|cal", 1),
      word("replicate", "/ˈrep.lɪ.keɪt/", "lặp lại (thí nghiệm) cho cùng kết quả", "Other labs have failed to replicate the results.", "rep|li|cate", 0),
      word("anomaly", "/əˈnɒm.ə.li/", "điều bất thường, dị thường", "The researchers could not explain the anomaly in the data.", "a|nom|a|ly", 1, "Nhấn âm 2: a-NOM-a-ly."),
      word("catalyst", "/ˈkæt.əl.ɪst/", "chất xúc tác; tác nhân thúc đẩy", "The discovery acted as a catalyst for further research.", "cat|a|lyst", 0),
      word("genome", "/ˈdʒiː.nəʊm/", "bộ gen", "Scientists have mapped the entire human genome.", "ge|nome", 0),
      word("quantum", "/ˈkwɒn.təm/", "lượng tử", "Quantum computers could solve problems that ordinary machines cannot.", "quan|tum", 0),
      word("synthesis", "/ˈsɪn.θə.sɪs/", "sự tổng hợp", "The synthesis of new materials is at the heart of modern chemistry.", "syn|the|sis", 0),
      word("nanotechnology", "/ˌnæn.əʊ.tekˈnɒl.ə.dʒi/", "công nghệ nano", "Nanotechnology may transform the way we deliver drugs.", "nan|o|tech|nol|o|gy", 3),
      word("theorem", "/ˈθɪə.rəm/", "định lý", "The theorem was finally proved after three centuries.", "theo|rem", 0),
      word("calibrate", "/ˈkæl.ɪ.breɪt/", "hiệu chỉnh (thiết bị đo)", "The instruments must be calibrated before each experiment.", "cal|i|brate", 0),
      word("molecular", "/məˈlek.jə.lə/", "(thuộc) phân tử", "She specialises in molecular biology.", "mo|lec|u|lar", 1),
      word("velocity", "/vəˈlɒs.ə.ti/", "vận tốc", "The particles travel at an extremely high velocity.", "ve|loc|i|ty", 1),
      word("simulation", "/ˌsɪm.jəˈleɪ.ʃən/", "sự mô phỏng", "Computer simulations predicted the storm's path accurately.", "sim|u|la|tion", 2),
      word("correlate", "/ˈkɒr.ə.leɪt/", "có tương quan", "Income levels correlate strongly with life expectancy.", "cor|re|late", 0),
      word("causation", "/kɔːˈzeɪ.ʃən/", "quan hệ nhân quả", "Correlation does not necessarily imply causation.", "cau|sa|tion", 1),
      word("postulate", "/ˈpɒs.tʃə.leɪt/", "đưa ra giả thuyết, cho rằng", "Einstein postulated that the speed of light is constant.", "pos|tu|late", 0),
      word("fission", "/ˈfɪʃ.ən/", "sự phân hạch", "Nuclear fission releases enormous amounts of energy.", "fis|sion", 0),
      word("spectrum", "/ˈspek.trəm/", "quang phổ; dải, phổ rộng", "Views on the issue cover the whole political spectrum.", "spec|trum", 0),
      word("microbe", "/ˈmaɪ.krəʊb/", "vi sinh vật", "Some microbes can survive in boiling water.", "mi|crobe", 0),
      word("automate", "/ˈɔː.tə.meɪt/", "tự động hoá", "Many routine tasks in the factory have been automated.", "au|to|mate", 0),
      word("biotechnology", "/ˌbaɪ.əʊ.tekˈnɒl.ə.dʒi/", "công nghệ sinh học", "Advances in biotechnology have produced drought-resistant crops.", "bi|o|tech|nol|o|gy", 3),
      word("mutation", "/mjuːˈteɪ.ʃən/", "sự đột biến", "A single genetic mutation can cause the disease.", "mu|ta|tion", 1),
      word("evolutionary", "/ˌiː.vəˈluː.ʃən.ər.i/", "(thuộc) tiến hoá", "The fossil fills an important gap in our evolutionary history.", "e|vo|lu|tion|ar|y", 2),
      word("dissect", "/daɪˈsekt/", "mổ xẻ; phân tích kỹ", "Students dissected a frog in the biology class.", "dis|sect", 1),
      word("sterile", "/ˈster.aɪl/", "vô trùng", "Surgical instruments must be kept completely sterile.", "ster|ile", 0),
      word("robotics", "/rəʊˈbɒt.ɪks/", "ngành rô-bốt học", "Japan has invested heavily in robotics.", "ro|bot|ics", 1),
      word("interface", "/ˈɪn.tə.feɪs/", "giao diện", "The new interface is far more intuitive than the old one.", "in|ter|face", 0),
      word("configure", "/kənˈfɪɡ.ə/", "cấu hình, thiết lập", "The network has to be configured by a specialist.", "con|fig|ure", 1),
      word("inertia", "/ɪˈnɜː.ʃə/", "quán tính; sự trì trệ", "Institutional inertia has slowed down the reforms.", "i|ner|tia", 1),
      word("trajectory", "/trəˈdʒek.tər.i/", "quỹ đạo; hướng phát triển", "The company's growth trajectory looks promising.", "tra|jec|to|ry", 1),
      word("isotope", "/ˈaɪ.sə.təʊp/", "đồng vị", "Radioactive isotopes are used to date ancient rocks.", "i|so|tope", 0),
      word("centrifuge", "/ˈsen.trɪ.fjuːdʒ/", "máy ly tâm", "The samples were spun in a centrifuge.", "cen|tri|fuge", 0),
      word("exponential", "/ˌek.spəˈnen.ʃəl/", "(tăng) theo cấp số nhân", "The internet has seen exponential growth since the 1990s.", "ex|po|nen|tial", 2),
      word("viable", "/ˈvaɪ.ə.bəl/", "khả thi", "Solar power is now a commercially viable alternative.", "vi|a|ble", 0),
    ],
  },
  {
    id: "phap-ly",
    title: "Pháp luật và ngôn ngữ pháp lý",
    words: [
      word("litigation", "/ˌlɪt.ɪˈɡeɪ.ʃən/", "sự kiện tụng", "The dispute could lead to years of costly litigation.", "lit|i|ga|tion", 2),
      word("plaintiff", "/ˈpleɪn.tɪf/", "nguyên đơn", "The plaintiff is seeking damages for lost earnings.", "plain|tiff", 0),
      word("jurisdiction", "/ˌdʒʊə.rɪsˈdɪk.ʃən/", "quyền tài phán, thẩm quyền", "The case falls outside the court's jurisdiction.", "ju|ris|dic|tion", 2),
      word("statute", "/ˈstætʃ.uːt/", "đạo luật (thành văn)", "The rights of tenants are protected by statute.", "stat|ute", 0),
      word("amendment", "/əˈmend.mənt/", "bản sửa đổi (luật)", "Parliament passed an amendment to the tax law.", "a|mend|ment", 1),
      word("liability", "/ˌlaɪ.əˈbɪl.ə.ti/", "trách nhiệm pháp lý", "The company denied any liability for the accident.", "li|a|bil|i|ty", 2),
      word("indemnity", "/ɪnˈdem.nə.ti/", "sự bồi thường; bảo đảm bồi thường", "The contract includes an indemnity against any losses.", "in|dem|ni|ty", 1),
      word("breach", "/briːtʃ/", "sự vi phạm (hợp đồng, luật)", "Selling the data was a clear breach of contract.", "breach", 0),
      word("tribunal", "/traɪˈbjuː.nəl/", "toà án đặc biệt, hội đồng xét xử", "She took her employer to an employment tribunal.", "tri|bu|nal", 1),
      word("testimony", "/ˈtes.tɪ.mə.ni/", "lời khai", "The witness's testimony was crucial to the case.", "tes|ti|mo|ny", 0, "Nhấn âm đầu: TES-ti-mo-ny."),
      word("affidavit", "/ˌæf.əˈdeɪ.vɪt/", "bản khai có tuyên thệ", "He signed an affidavit confirming the facts.", "af|fi|da|vit", 2),
      word("acquit", "/əˈkwɪt/", "tuyên trắng án", "The jury acquitted him of all charges.", "ac|quit", 1),
      word("precedent", "/ˈpres.ɪ.dənt/", "tiền lệ", "The ruling sets an important legal precedent.", "prec|e|dent", 0),
      word("injunction", "/ɪnˈdʒʌŋk.ʃən/", "lệnh cấm (của toà)", "The court granted an injunction to stop the protest.", "in|junc|tion", 1),
      word("arbitration", "/ˌɑː.bɪˈtreɪ.ʃən/", "sự phân xử trọng tài", "The pay dispute went to arbitration.", "ar|bi|tra|tion", 2),
      word("infringe", "/ɪnˈfrɪndʒ/", "vi phạm (quyền, bản quyền)", "The design infringes the company's patent.", "in|fringe", 1),
      word("void", "/vɔɪd/", "vô hiệu (về pháp lý)", "The agreement was declared null and void.", "void", 0),
      word("enforceable", "/ɪnˈfɔː.sə.bəl/", "có hiệu lực thi hành", "A verbal agreement is not always legally enforceable.", "en|force|a|ble", 1),
      word("statutory", "/ˈstætʃ.ə.tər.i/", "theo luật định", "Employees are entitled to statutory sick pay.", "stat|u|to|ry", 0),
      word("culpable", "/ˈkʌl.pə.bəl/", "đáng bị khiển trách, có lỗi", "The report held the managers culpable for the accident.", "cul|pa|ble", 0),
      word("perjury", "/ˈpɜː.dʒər.i/", "tội khai man trước toà", "He was jailed for committing perjury.", "per|ju|ry", 0),
      word("solicitor", "/səˈlɪs.ɪ.tə/", "luật sư tư vấn (Anh)", "You should ask a solicitor to check the contract.", "so|lic|i|tor", 1),
      word("parole", "/pəˈrəʊl/", "sự tha có điều kiện", "He was released on parole after serving ten years.", "pa|role", 1),
      word("inadmissible", "/ˌɪn.ədˈmɪs.ə.bəl/", "không được chấp nhận (làm chứng cứ)", "The judge ruled the recording inadmissible.", "in|ad|mis|si|ble", 2),
      word("decree", "/dɪˈkriː/", "sắc lệnh, nghị định", "The president ruled by decree for six months.", "de|cree", 1),
      word("loophole", "/ˈluːp.həʊl/", "kẽ hở (luật)", "The company exploited a loophole in the tax rules.", "loop|hole", 0),
      word("clemency", "/ˈklem.ən.si/", "sự khoan hồng", "The governor refused to grant clemency.", "clem|en|cy", 0),
      word("impartial", "/ɪmˈpɑː.ʃəl/", "công bằng, không thiên vị", "Judges must remain strictly impartial.", "im|par|tial", 1),
      word("exonerate", "/ɪɡˈzɒn.ə.reɪt/", "minh oan, giải tội", "The inquiry exonerated the pilot from any blame.", "ex|on|er|ate", 1),
      word("adjudicate", "/əˈdʒuː.dɪ.keɪt/", "phân xử, xét xử", "An independent panel will adjudicate the dispute.", "ad|ju|di|cate", 1),
      word("subpoena", "/səˈpiː.nə/", "trát đòi hầu toà", "The court issued a subpoena to the former director.", "sub|poe|na", 1, "b câm: /səˈpiː.nə/."),
      word("misdemeanour", "/ˌmɪs.dɪˈmiː.nə/", "tội nhẹ, hành vi sai trái", "He was fined for a minor misdemeanour.", "mis|de|mea|nour", 2),
    ],
  },
  {
    id: "hoc-thuat-nghien-cuu",
    title: "Viết học thuật và nghiên cứu",
    words: [
      word("citation", "/saɪˈteɪ.ʃən/", "trích dẫn", "Each citation must include the page number.", "ci|ta|tion", 1),
      word("qualitative", "/ˈkwɒl.ɪ.tə.tɪv/", "định tính", "The study combines surveys with qualitative interviews.", "qual|i|ta|tive", 0),
      word("quantitative", "/ˈkwɒn.tɪ.tə.tɪv/", "định lượng", "Quantitative data can be analysed statistically.", "quan|ti|ta|tive", 0),
      word("dataset", "/ˈdeɪ.tə.set/", "bộ dữ liệu", "The researchers made their dataset publicly available.", "da|ta|set", 0),
      word("footnote", "/ˈfʊt.nəʊt/", "chú thích cuối trang", "The source is given in a footnote.", "foot|note", 0),
      word("appendix", "/əˈpen.dɪks/", "phụ lục", "The full questionnaire appears in the appendix.", "ap|pen|dix", 1),
      word("annotate", "/ˈæn.ə.teɪt/", "chú giải, ghi chú", "Students annotated the poem with their own comments.", "an|no|tate", 0),
      word("discourse", "/ˈdɪs.kɔːs/", "diễn ngôn; bài diễn thuyết", "The term has become common in political discourse.", "dis|course", 0),
      word("corroborate", "/kəˈrɒb.ə.reɪt/", "chứng thực, củng cố (bằng chứng)", "Later studies corroborated her findings.", "cor|rob|o|rate", 1),
      word("extrapolate", "/ɪkˈstræp.ə.leɪt/", "suy rộng, ngoại suy", "It is risky to extrapolate from such a small sample.", "ex|trap|o|late", 1),
      word("deduce", "/dɪˈdʒuːs/", "suy ra, suy luận", "From the evidence, we can deduce that the site was abandoned.", "de|duce", 1),
      word("inference", "/ˈɪn.fər.əns/", "sự suy luận; kết luận rút ra", "The inference drawn from the data seems reasonable.", "in|fer|ence", 0),
      word("validity", "/vəˈlɪd.ə.ti/", "tính hợp lệ, giá trị (của lập luận)", "Critics question the validity of the survey.", "va|lid|i|ty", 1),
      word("rigorous", "/ˈrɪɡ.ər.əs/", "chặt chẽ, nghiêm ngặt", "The drug went through rigorous testing.", "rig|or|ous", 0),
      word("scrutinise", "/ˈskruː.tɪ.naɪz/", "xem xét kỹ lưỡng", "Reviewers will scrutinise every detail of the proposal.", "scru|ti|nise", 0),
      word("conjecture", "/kənˈdʒek.tʃə/", "sự phỏng đoán", "Without further evidence, this remains pure conjecture.", "con|jec|ture", 1),
      word("criterion", "/kraɪˈtɪə.ri.ən/", "tiêu chí (số nhiều: criteria)", "Cost was the main criterion for choosing a supplier.", "cri|te|ri|on", 1),
      word("synopsis", "/sɪˈnɒp.sɪs/", "bản tóm lược", "The synopsis gives a brief outline of the plot.", "syn|op|sis", 1),
      word("treatise", "/ˈtriː.tɪs/", "chuyên luận", "He wrote a lengthy treatise on political economy.", "trea|tise", 0),
      word("manuscript", "/ˈmæn.jə.skrɪpt/", "bản thảo", "She sent the manuscript to three publishers.", "man|u|script", 0),
      word("excerpt", "/ˈek.sɜːpt/", "đoạn trích", "The newspaper printed an excerpt from her new book.", "ex|cerpt", 0),
      word("preliminary", "/prɪˈlɪm.ɪ.nər.i/", "sơ bộ, ban đầu", "The preliminary results look encouraging.", "pre|lim|i|nar|y", 1),
      word("delineate", "/dɪˈlɪn.i.eɪt/", "phác hoạ, mô tả rõ ranh giới", "The first chapter delineates the scope of the study.", "de|lin|e|ate", 1),
      word("elucidate", "/ɪˈluː.sɪ.deɪt/", "làm sáng tỏ", "The author tries to elucidate the causes of the crisis.", "e|lu|ci|date", 1),
      word("posit", "/ˈpɒz.ɪt/", "đặt ra, cho rằng (làm tiền đề)", "Some theorists posit that language is innate.", "pos|it", 0),
      word("anecdotal", "/ˌæn.ɪkˈdəʊ.təl/", "dựa trên giai thoại (không có số liệu)", "The evidence so far is largely anecdotal.", "an|ec|do|tal", 2),
      word("longitudinal", "/ˌlɒŋ.ɡɪˈtʃuː.dɪ.nəl/", "(nghiên cứu) theo thời gian dài", "A longitudinal study followed the children for twenty years.", "lon|gi|tu|di|nal", 2),
      word("demographic", "/ˌdem.əˈɡræf.ɪk/", "(thuộc) nhân khẩu học", "The survey collected demographic data such as age and income.", "dem|o|graph|ic", 2),
      word("terminology", "/ˌtɜː.mɪˈnɒl.ə.dʒi/", "thuật ngữ", "Legal terminology can be confusing for non-specialists.", "ter|mi|nol|o|gy", 2),
      word("attribute", "/əˈtrɪb.juːt/", "quy cho, cho là do", "The decline is often attributed to rising costs.", "at|trib|ute", 1, "Động từ nhấn âm 2 (at-TRIB-ute); danh từ 'thuộc tính' nhấn âm 1 (AT-tri-bute)."),
      word("seminal", "/ˈsem.ɪ.nəl/", "có ảnh hưởng lớn, mở đường", "Her seminal paper changed the field forever.", "sem|i|nal", 0),
      word("exposition", "/ˌek.spəˈzɪʃ.ən/", "sự trình bày, giải thích", "The book offers a clear exposition of the theory.", "ex|po|si|tion", 2),
      word("compile", "/kəmˈpaɪl/", "biên soạn, tập hợp", "We compiled a list of all relevant studies.", "com|pile", 1),
      word("juxtapose", "/ˌdʒʌk.stəˈpəʊz/", "đặt cạnh nhau (để so sánh)", "The essay juxtaposes two very different theories.", "jux|ta|pose", 2),
    ],
  },
  {
    id: "phe-binh-nghe-thuat",
    title: "Phê bình nghệ thuật và văn học",
    words: [
      word("aesthetic", "/iːsˈθet.ɪk/", "(thuộc) thẩm mỹ", "The building has great aesthetic appeal.", "aes|thet|ic", 1),
      word("allegory", "/ˈæl.ə.ɡər.i/", "truyện ngụ ngôn, phúng dụ", "The novel is an allegory of the rise of dictatorship.", "al|le|go|ry", 0),
      word("protagonist", "/prəˈtæɡ.ən.ɪst/", "nhân vật chính", "The protagonist is a young doctor in rural Ireland.", "pro|tag|o|nist", 1),
      word("antagonist", "/ænˈtæɡ.ən.ɪst/", "nhân vật phản diện", "The antagonist is more interesting than the hero.", "an|tag|o|nist", 1),
      word("motif", "/məʊˈtiːf/", "mô-típ, hình ảnh lặp lại", "Water is a recurring motif in her paintings.", "mo|tif", 1),
      word("satire", "/ˈsæt.aɪə/", "sự châm biếm; tác phẩm trào phúng", "The play is a sharp satire on modern politics.", "sat|ire", 0),
      word("irony", "/ˈaɪ.rə.ni/", "sự trớ trêu; lối nói mỉa", "The irony is that the anti-smoking campaigner was a smoker.", "i|ro|ny", 0),
      word("pastiche", "/pæsˈtiːʃ/", "tác phẩm mô phỏng phong cách", "The film is a clever pastiche of 1950s horror movies.", "pas|tiche", 1),
      word("avant-garde", "/ˌæv.ɒ̃ˈɡɑːd/", "tiên phong (nghệ thuật)", "The gallery shows avant-garde artists from Eastern Europe.", "av|ant|garde", 2),
      word("evocative", "/ɪˈvɒk.ə.tɪv/", "gợi cảm xúc, gợi nhớ", "Her evocative descriptions bring the village to life.", "e|voc|a|tive", 1),
      word("poignant", "/ˈpɔɪ.njənt/", "thấm thía, gây xúc động", "The film ends with a poignant scene at the station.", "poi|gnant", 0, "Chữ g câm: /ˈpɔɪ.njənt/."),
      word("melancholy", "/ˈmel.əŋ.kɒl.i/", "nỗi u sầu; u buồn", "The music has a gentle, melancholy quality.", "mel|an|chol|y", 0),
      word("sublime", "/səˈblaɪm/", "tuyệt diệu, siêu phàm", "The view from the summit was simply sublime.", "sub|lime", 1),
      word("prose", "/prəʊz/", "văn xuôi", "His prose is simple but powerful.", "prose", 0),
      word("stanza", "/ˈstæn.zə/", "khổ thơ", "The final stanza changes the mood of the poem.", "stan|za", 0),
      word("sonnet", "/ˈsɒn.ɪt/", "thơ xon-nê (14 dòng)", "Shakespeare wrote 154 sonnets.", "son|net", 0),
      word("canon", "/ˈkæn.ən/", "các tác phẩm kinh điển được công nhận", "Her novels are now part of the literary canon.", "can|on", 0),
      word("portrayal", "/pɔːˈtreɪ.əl/", "sự khắc hoạ, miêu tả", "The film's portrayal of war is brutally honest.", "por|tray|al", 1),
      word("virtuoso", "/ˌvɜː.tjuˈəʊ.səʊ/", "nghệ sĩ bậc thầy; điêu luyện", "He gave a virtuoso performance on the violin.", "vir|tu|o|so", 2),
      word("rendition", "/renˈdɪʃ.ən/", "sự trình diễn, thể hiện (bài hát)", "She sang a moving rendition of the national anthem.", "ren|di|tion", 1),
      word("choreography", "/ˌkɒr.iˈɒɡ.rə.fi/", "nghệ thuật biên đạo múa", "The choreography was both elegant and daring.", "cho|re|og|ra|phy", 2, "ch đọc là /k/, nhấn âm 3: cho-re-OG-ra-phy."),
      word("curator", "/kjʊəˈreɪ.tə/", "người phụ trách bảo tàng/triển lãm", "The curator chose every piece in the exhibition.", "cu|ra|tor", 1),
      word("connoisseur", "/ˌkɒn.əˈsɜː/", "người sành sỏi", "He is a connoisseur of French wine.", "con|nois|seur", 2),
      word("trite", "/traɪt/", "sáo rỗng, nhàm", "The ending felt trite and predictable.", "trite", 0),
      word("derivative", "/dɪˈrɪv.ə.tɪv/", "thiếu sáng tạo, bắt chước", "Critics dismissed the album as derivative.", "de|riv|a|tive", 1),
      word("pretentious", "/prɪˈten.ʃəs/", "làm bộ, khoe mẽ", "I found the dialogue pretentious and hard to follow.", "pre|ten|tious", 1),
      word("idyllic", "/ɪˈdɪl.ɪk/", "yên bình, thơ mộng", "The novel is set in an idyllic mountain village.", "i|dyl|lic", 1),
      word("understated", "/ˌʌn.dəˈsteɪ.tɪd/", "tinh tế, không phô trương", "Her understated performance won her an award.", "un|der|stat|ed", 2),
      word("lyrical", "/ˈlɪr.ɪ.kəl/", "trữ tình, bay bổng", "The book is full of lyrical descriptions of nature.", "lyr|i|cal", 0),
      word("denouement", "/deɪˈnuː.mɒ̃/", "đoạn kết, phần gỡ nút", "The denouement reveals who the killer really was.", "de|noue|ment", 1, "Từ gốc Pháp: /deɪˈnuː.mɒ̃/, không đọc t cuối."),
      word("foreshadow", "/fɔːˈʃæd.əʊ/", "báo trước, điềm báo", "The storm in chapter one foreshadows the tragedy.", "fore|shad|ow", 1),
      word("anthology", "/ænˈθɒl.ə.dʒi/", "tuyển tập", "The anthology includes poems from twenty countries.", "an|thol|o|gy", 1),
      word("memoir", "/ˈmem.wɑː/", "hồi ký", "The former minister has just published her memoir.", "mem|oir", 0),
      word("hyperbole", "/haɪˈpɜː.bəl.i/", "phép cường điệu, nói quá", "Calling it the best film ever made is pure hyperbole.", "hy|per|bo|le", 1, "Đọc 4 âm tiết, e cuối đọc /i/: hy-PER-bo-le."),
      word("catharsis", "/kəˈθɑː.sɪs/", "sự thanh lọc cảm xúc", "Writing about the loss was a form of catharsis for him.", "ca|thar|sis", 1),
      word("ode", "/əʊd/", "bài thơ ca ngợi (thơ ode)", "Keats wrote an ode to a nightingale.", "ode", 0),
      word("surreal", "/səˈrɪəl/", "siêu thực, kỳ ảo", "The whole evening had a surreal, dreamlike quality.", "sur|real", 1),
    ],
  },
  {
    id: "chinh-tri-quan-tri",
    title: "Chính trị và quản trị nhà nước",
    words: [
      word("sovereignty", "/ˈsɒv.rɪn.ti/", "chủ quyền", "The country defended its sovereignty over the islands.", "sov|reign|ty", 0, "Chữ g câm: /ˈsɒv.rɪn.ti/."),
      word("legislative", "/ˈledʒ.ɪ.slə.tɪv/", "(thuộc) lập pháp", "Parliament is the country's main legislative body.", "leg|is|la|tive", 0),
      word("electorate", "/iˈlek.tər.ət/", "cử tri (toàn thể)", "Half the electorate did not vote.", "e|lec|tor|ate", 1),
      word("coalition", "/ˌkəʊ.əˈlɪʃ.ən/", "liên minh (chính phủ)", "The two parties formed a coalition government.", "co|a|li|tion", 2),
      word("bipartisan", "/ˌbaɪˈpɑː.tɪ.zæn/", "được cả hai đảng ủng hộ", "The bill received bipartisan support.", "bi|par|ti|san", 1),
      word("bureaucracy", "/bjʊəˈrɒk.rə.si/", "bộ máy quan liêu", "Small firms complain about excessive bureaucracy.", "bu|reau|cra|cy", 1),
      word("autonomy", "/ɔːˈtɒn.ə.mi/", "quyền tự trị, tự chủ", "The region was granted greater autonomy.", "au|ton|o|my", 1),
      word("regime", "/reɪˈʒiːm/", "chế độ (cầm quyền)", "The military regime was overthrown in 1989.", "re|gime", 1),
      word("authoritarian", "/ˌɔː.θɒr.ɪˈteə.ri.ən/", "độc đoán, chuyên chế", "The country is drifting towards authoritarian rule.", "au|thor|i|tar|i|an", 3),
      word("incumbent", "/ɪnˈkʌm.bənt/", "người đương nhiệm", "The incumbent is expected to win a second term.", "in|cum|bent", 1),
      word("mandate", "/ˈmæn.deɪt/", "sự uỷ nhiệm (của cử tri)", "The government has a clear mandate for reform.", "man|date", 0),
      word("ratify", "/ˈræt.ɪ.faɪ/", "phê chuẩn", "The treaty has been ratified by forty countries.", "rat|i|fy", 0),
      word("veto", "/ˈviː.təʊ/", "quyền phủ quyết; phủ quyết", "The president vetoed the new law.", "ve|to", 0),
      word("lobby", "/ˈlɒb.i/", "vận động hành lang", "Farmers lobbied hard against the new tax.", "lob|by", 0),
      word("partisan", "/ˌpɑː.tɪˈzæn/", "thiên vị một đảng phái", "The debate became bitterly partisan.", "par|ti|san", 2),
      word("constituency", "/kənˈstɪtʃ.u.ən.si/", "khu vực bầu cử", "She has represented this constituency for twelve years.", "con|stit|u|en|cy", 1),
      word("diplomacy", "/dɪˈpləʊ.mə.si/", "ngoại giao", "The crisis was resolved through quiet diplomacy.", "di|plo|ma|cy", 1),
      word("sanction", "/ˈsæŋk.ʃən/", "lệnh trừng phạt", "The UN imposed economic sanctions on the regime.", "sanc|tion", 0),
      word("embargo", "/ɪmˈbɑː.ɡəʊ/", "lệnh cấm vận", "An arms embargo was imposed on both sides.", "em|bar|go", 1),
      word("secular", "/ˈsek.jə.lə/", "thế tục, không tôn giáo", "France is a secular state.", "sec|u|lar", 0),
      word("ideology", "/ˌaɪ.diˈɒl.ə.dʒi/", "hệ tư tưởng", "The party has abandoned its old ideology.", "i|de|ol|o|gy", 2),
      word("populist", "/ˈpɒp.jə.lɪst/", "dân tuý", "Populist leaders promise simple answers to complex problems.", "pop|u|list", 0),
      word("demagogue", "/ˈdem.ə.ɡɒɡ/", "kẻ mị dân", "He was accused of being a dangerous demagogue.", "dem|a|gogue", 0),
      word("dissent", "/dɪˈsent/", "sự bất đồng chính kiến", "The regime does not tolerate political dissent.", "dis|sent", 1),
      word("insurgency", "/ɪnˈsɜː.dʒən.si/", "cuộc nổi dậy vũ trang", "The army has struggled to contain the insurgency.", "in|sur|gen|cy", 1),
      word("accountability", "/əˌkaʊn.təˈbɪl.ə.ti/", "trách nhiệm giải trình", "Citizens demand greater accountability from public officials.", "ac|count|a|bil|i|ty", 3),
      word("transparency", "/trænˈspær.ən.si/", "sự minh bạch", "The new rules aim to increase transparency in public spending.", "trans|par|en|cy", 1),
      word("governance", "/ˈɡʌv.ən.əns/", "sự quản trị", "Good governance is essential for economic growth.", "gov|ern|ance", 0),
      word("devolution", "/ˌdiː.vəˈluː.ʃən/", "sự phân quyền cho địa phương", "Devolution gave Scotland its own parliament.", "de|vo|lu|tion", 2),
      word("legitimacy", "/ləˈdʒɪt.ə.mə.si/", "tính chính danh, hợp pháp", "Many questioned the legitimacy of the election.", "le|git|i|ma|cy", 1),
      word("statesman", "/ˈsteɪts.mən/", "chính khách lỗi lạc", "He is remembered as a great statesman.", "states|man", 0),
      word("envoy", "/ˈen.vɔɪ/", "đặc phái viên", "A special envoy was sent to negotiate a ceasefire.", "en|voy", 0),
      word("annex", "/ænˈeks/", "sáp nhập (lãnh thổ)", "The territory was annexed after the war.", "an|nex", 1),
      word("impeach", "/ɪmˈpiːtʃ/", "luận tội (quan chức)", "Congress voted to impeach the president.", "im|peach", 1),
      word("manifesto", "/ˌmæn.ɪˈfes.təʊ/", "cương lĩnh tranh cử", "The party's manifesto promises free childcare.", "man|i|fes|to", 2),
      word("abstain", "/æbˈsteɪn/", "bỏ phiếu trắng; kiêng", "Three members abstained in the vote.", "ab|stain", 1),
    ],
  },
  {
    id: "kinh-te-tai-chinh",
    title: "Kinh tế và tài chính",
    words: [
      word("austerity", "/ɒsˈter.ə.ti/", "chính sách thắt lưng buộc bụng", "Years of austerity have hit public services hard.", "aus|ter|i|ty", 1),
      word("inflationary", "/ɪnˈfleɪ.ʃən.ər.i/", "gây lạm phát", "Rising wages could have an inflationary effect.", "in|fla|tion|ar|y", 1),
      word("deflation", "/dɪˈfleɪ.ʃən/", "giảm phát", "Deflation can be just as harmful as inflation.", "de|fla|tion", 1),
      word("fiscal", "/ˈfɪs.kəl/", "(thuộc) tài khoá, ngân sách", "The government announced a tighter fiscal policy.", "fis|cal", 0),
      word("monetary", "/ˈmʌn.ɪ.tər.i/", "(thuộc) tiền tệ", "The central bank controls monetary policy.", "mon|e|tar|y", 0),
      word("liquidity", "/lɪˈkwɪd.ə.ti/", "tính thanh khoản", "Banks need enough liquidity to survive a crisis.", "li|quid|i|ty", 1),
      word("insolvency", "/ɪnˈsɒl.vən.si/", "tình trạng mất khả năng thanh toán", "The firm is facing insolvency.", "in|sol|ven|cy", 1),
      word("dividend", "/ˈdɪv.ɪ.dend/", "cổ tức", "Shareholders received a dividend of 5%.", "div|i|dend", 0),
      word("equity", "/ˈek.wɪ.ti/", "vốn cổ phần; sự công bằng", "The founders still hold most of the company's equity.", "eq|ui|ty", 0),
      word("collateral", "/kəˈlæt.ər.əl/", "tài sản thế chấp", "He used his house as collateral for the loan.", "col|lat|er|al", 1),
      word("deficit", "/ˈdef.ɪ.sɪt/", "thâm hụt", "The budget deficit has doubled in two years.", "def|i|cit", 0),
      word("surplus", "/ˈsɜː.pləs/", "thặng dư", "The country has a large trade surplus.", "sur|plus", 0),
      word("stagnation", "/stæɡˈneɪ.ʃən/", "sự trì trệ", "The economy has suffered a decade of stagnation.", "stag|na|tion", 1),
      word("volatile", "/ˈvɒl.ə.taɪl/", "biến động mạnh, bất ổn", "Oil prices have been extremely volatile this year.", "vol|a|tile", 0),
      word("commodity", "/kəˈmɒd.ə.ti/", "hàng hoá (nguyên liệu thô)", "Coffee is one of the world's most traded commodities.", "com|mod|i|ty", 1),
      word("conglomerate", "/kənˈɡlɒm.ər.ət/", "tập đoàn đa ngành", "The brand is owned by a huge media conglomerate.", "con|glom|er|ate", 1),
      word("remuneration", "/rɪˌmjuː.nəˈreɪ.ʃən/", "thù lao", "Directors' remuneration has risen sharply.", "re|mu|ne|ra|tion", 3),
      word("levy", "/ˈlev.i/", "thuế, khoản thu; đánh thuế", "A new levy was imposed on sugary drinks.", "lev|y", 0),
      word("depreciation", "/dɪˌpriː.ʃiˈeɪ.ʃən/", "sự mất giá, khấu hao", "The depreciation of the currency made imports more expensive.", "de|pre|ci|a|tion", 3),
      word("lucrative", "/ˈluː.krə.tɪv/", "sinh lời, béo bở", "He left teaching for a more lucrative career in finance.", "lu|cra|tive", 0),
      word("entrepreneurial", "/ˌɒn.trə.prəˈnɜː.ri.əl/", "có tinh thần khởi nghiệp", "The city has a lively entrepreneurial culture.", "en|tre|pre|neur|i|al", 3),
      word("procurement", "/prəˈkjʊə.mənt/", "sự mua sắm (của tổ chức)", "The scandal exposed corruption in public procurement.", "pro|cure|ment", 1),
      word("privatise", "/ˈpraɪ.vɪ.taɪz/", "tư nhân hoá", "The railways were privatised in the 1990s.", "pri|va|tise", 0),
      word("quota", "/ˈkwəʊ.tə/", "hạn ngạch", "The government set strict quotas on fish catches.", "quo|ta", 0),
      word("macroeconomic", "/ˌmæk.rəʊ.iː.kəˈnɒm.ɪk/", "(thuộc) kinh tế vĩ mô", "Macroeconomic stability attracts foreign investors.", "mac|ro|e|co|nom|ic", 4),
      word("audit", "/ˈɔː.dɪt/", "kiểm toán", "An independent audit revealed serious errors in the accounts.", "au|dit", 0),
      word("bailout", "/ˈbeɪl.aʊt/", "gói cứu trợ tài chính", "The bank received a huge government bailout.", "bail|out", 0),
      word("embezzle", "/ɪmˈbez.əl/", "biển thủ, tham ô", "The accountant embezzled funds from the charity.", "em|bez|zle", 1),
      word("creditor", "/ˈkred.ɪ.tə/", "chủ nợ", "The company could not pay its creditors.", "cred|i|tor", 0),
      word("underwrite", "/ˌʌn.dəˈraɪt/", "bảo lãnh (tài chính), bảo hiểm", "The government agreed to underwrite the loans.", "un|der|write", 2),
      word("oligopoly", "/ˌɒl.ɪˈɡɒp.əl.i/", "thị trường độc quyền nhóm", "The mobile market is an oligopoly of three firms.", "ol|i|gop|o|ly", 2),
    ],
  },
  {
    id: "xa-hoi-bat-binh-dang",
    title: "Vấn đề xã hội và bất bình đẳng",
    words: [
      word("marginalise", "/ˈmɑː.dʒɪ.nəl.aɪz/", "gạt ra bên lề", "Older workers often feel marginalised in the digital economy.", "mar|gin|al|ise", 0),
      word("disenfranchise", "/ˌdɪs.ɪnˈfræn.tʃaɪz/", "tước quyền (bầu cử)", "The new ID law may disenfranchise poorer voters.", "dis|en|fran|chise", 2),
      word("disparity", "/dɪˈspær.ə.ti/", "sự chênh lệch", "There is a huge disparity between rich and poor regions.", "dis|par|i|ty", 1),
      word("inequity", "/ɪˈnek.wɪ.ti/", "sự bất công", "The report highlights inequities in access to healthcare.", "in|eq|ui|ty", 1),
      word("deprivation", "/ˌdep.rɪˈveɪ.ʃən/", "sự thiếu thốn", "Many children grow up in conditions of severe deprivation.", "dep|ri|va|tion", 2),
      word("destitute", "/ˈdes.tɪ.tʃuːt/", "cơ cực, không một xu dính túi", "The war left thousands of families destitute.", "des|ti|tute", 0),
      word("impoverished", "/ɪmˈpɒv.ər.ɪʃt/", "bị bần cùng hoá", "The charity works in impoverished rural areas.", "im|pov|er|ished", 1),
      word("underprivileged", "/ˌʌn.dəˈprɪv.əl.ɪdʒd/", "thiệt thòi, kém may mắn", "The scheme offers scholarships to underprivileged students.", "un|der|priv|i|leged", 2),
      word("stigma", "/ˈstɪɡ.mə/", "sự kỳ thị, vết nhơ", "There is still a stigma attached to mental illness.", "stig|ma", 0),
      word("bigotry", "/ˈbɪɡ.ə.tri/", "sự cố chấp, kỳ thị", "The campaign aims to fight racism and bigotry.", "big|ot|ry", 0),
      word("xenophobia", "/ˌzen.əˈfəʊ.bi.ə/", "sự bài ngoại", "Economic hardship can fuel xenophobia.", "xen|o|pho|bi|a", 2, "x đầu từ đọc là /z/."),
      word("segregation", "/ˌseɡ.rɪˈɡeɪ.ʃən/", "sự phân biệt, tách biệt (chủng tộc)", "In 1954, the US Supreme Court ruled that racial segregation in schools was unconstitutional.", "seg|re|ga|tion", 2),
      word("assimilate", "/əˈsɪm.ɪ.leɪt/", "hoà nhập, đồng hoá", "Immigrants often take years to assimilate fully.", "as|sim|i|late", 1),
      word("emancipation", "/ɪˌmæn.sɪˈpeɪ.ʃən/", "sự giải phóng", "She campaigned for the emancipation of women.", "e|man|ci|pa|tion", 3),
      word("egalitarian", "/ɪˌɡæl.ɪˈteə.ri.ən/", "theo chủ nghĩa bình đẳng", "Scandinavian countries are known for their egalitarian values.", "e|gal|i|tar|i|an", 3),
      word("meritocracy", "/ˌmer.ɪˈtɒk.rə.si/", "chế độ trọng nhân tài", "Is our society really a meritocracy?", "mer|i|toc|ra|cy", 2),
      word("affluent", "/ˈæf.lu.ənt/", "giàu có, sung túc", "They live in an affluent suburb of London.", "af|flu|ent", 0),
      word("philanthropy", "/fɪˈlæn.θrə.pi/", "lòng từ thiện, hoạt động từ thiện", "Her philanthropy has funded dozens of schools.", "phi|lan|thro|py", 1),
      word("altruistic", "/ˌæl.truˈɪs.tɪk/", "vị tha", "Not all volunteers have purely altruistic motives.", "al|tru|is|tic", 2),
      word("gentrification", "/ˌdʒen.trɪ.fɪˈkeɪ.ʃən/", "sự quý tộc hoá (khu dân cư)", "Gentrification has pushed long-term residents out of the area.", "gen|tri|fi|ca|tion", 3),
      word("displacement", "/dɪˈspleɪs.mənt/", "sự di dời, mất nơi ở", "The dam caused the displacement of thousands of villagers.", "dis|place|ment", 1),
      word("exploitation", "/ˌek.splɔɪˈteɪ.ʃən/", "sự bóc lột", "The report exposes the exploitation of migrant workers.", "ex|ploi|ta|tion", 2),
      word("empowerment", "/ɪmˈpaʊ.ə.mənt/", "sự trao quyền", "Education is key to the empowerment of women.", "em|pow|er|ment", 1),
      word("discriminatory", "/dɪˈskrɪm.ɪ.nə.tər.i/", "mang tính phân biệt đối xử", "The court ruled that the policy was discriminatory.", "dis|crim|i|na|to|ry", 1),
      word("inclusivity", "/ˌɪn.kluːˈsɪv.ɪ.ti/", "tính hoà nhập, bao trùm", "The festival celebrates diversity and inclusivity.", "in|clu|siv|i|ty", 2),
      word("juvenile", "/ˈdʒuː.vən.aɪl/", "(thuộc) vị thành niên", "Juvenile crime has fallen over the last decade.", "ju|ve|nile", 0),
      word("delinquency", "/dɪˈlɪŋ.kwən.si/", "hành vi phạm pháp (của thanh thiếu niên)", "Poverty is often linked to juvenile delinquency.", "de|lin|quen|cy", 1),
      word("alienation", "/ˌeɪ.li.əˈneɪ.ʃən/", "sự xa lánh, cảm giác lạc lõng", "Many young people feel a sense of alienation from politics.", "a|li|e|na|tion", 3),
      word("entrenched", "/ɪnˈtrentʃt/", "ăn sâu, bám rễ", "Gender roles are deeply entrenched in the culture.", "en|trenched", 1),
      word("systemic", "/sɪˈstem.ɪk/", "mang tính hệ thống", "The inquiry found evidence of systemic racism.", "sys|tem|ic", 1),
      word("upheaval", "/ʌpˈhiː.vəl/", "sự biến động lớn", "The country went through a period of social upheaval.", "up|heav|al", 1),
      word("asylum", "/əˈsaɪ.ləm/", "sự tị nạn (chính trị)", "Thousands of people have applied for asylum.", "a|sy|lum", 1),
      word("diaspora", "/daɪˈæs.pər.ə/", "cộng đồng kiều bào", "The Vietnamese diaspora in the US is very active.", "di|as|po|ra", 1),
      word("socioeconomic", "/ˌsəʊ.si.əʊˌek.əˈnɒm.ɪk/", "(thuộc) kinh tế - xã hội", "Students from all socioeconomic backgrounds are welcome.", "so|ci|o|ec|o|nom|ic", 5),
      word("plight", "/plaɪt/", "cảnh ngộ khốn khổ", "The film draws attention to the plight of refugees.", "plight", 0),
      word("patriarchal", "/ˌpeɪ.triˈɑː.kəl/", "gia trưởng, phụ hệ", "Women still face many barriers in a patriarchal society.", "pa|tri|ar|chal", 2),
      word("ostracise", "/ˈɒs.trə.saɪz/", "tẩy chay, xa lánh", "He was ostracised by his colleagues after the scandal.", "os|tra|cise", 0),
    ],
  },
  {
    id: "moi-truong-ben-vung",
    title: "Môi trường và phát triển bền vững",
    words: [
      word("carbon-neutral", "/ˌkɑː.bənˈnjuː.trəl/", "trung hoà các-bon", "The company aims to be carbon-neutral by 2030.", "car|bon|neu|tral", 2),
      word("decarbonise", "/ˌdiːˈkɑː.bən.aɪz/", "khử các-bon", "We must decarbonise the power sector quickly.", "de|car|bon|ise", 1),
      word("mitigate", "/ˈmɪt.ɪ.ɡeɪt/", "giảm nhẹ", "Planting trees can help mitigate the effects of flooding.", "mit|i|gate", 0),
      word("depletion", "/dɪˈpliː.ʃən/", "sự cạn kiệt", "The depletion of fish stocks worries scientists.", "de|ple|tion", 1),
      word("desertification", "/dɪˌzɜː.tɪ.fɪˈkeɪ.ʃən/", "sự sa mạc hoá", "Overgrazing has accelerated desertification in the region.", "de|ser|ti|fi|ca|tion", 4),
      word("toxin", "/ˈtɒk.sɪn/", "độc tố", "The algae release toxins that kill fish.", "tox|in", 0),
      word("conservationist", "/ˌkɒn.səˈveɪ.ʃən.ɪst/", "nhà bảo tồn thiên nhiên", "Conservationists are fighting to save the forest.", "con|ser|va|tion|ist", 2),
      word("ecological", "/ˌiː.kəˈlɒdʒ.ɪ.kəl/", "(thuộc) sinh thái", "The oil spill was an ecological disaster.", "e|co|log|i|cal", 2),
      word("geothermal", "/ˌdʒiː.əʊˈθɜː.məl/", "(thuộc) địa nhiệt", "Iceland gets much of its energy from geothermal sources.", "ge|o|ther|mal", 2),
      word("hydroelectric", "/ˌhaɪ.drəʊ.ɪˈlek.trɪk/", "(thuộc) thuỷ điện", "The hydroelectric dam supplies power to the whole province.", "hy|dro|e|lec|tric", 3),
      word("offset", "/ˌɒfˈset/", "bù đắp, bù trừ", "Airlines let passengers offset the carbon from their flights.", "off|set", 1),
      word("sequestration", "/ˌsiː.kwesˈtreɪ.ʃən/", "sự thu giữ (các-bon)", "Forests play a key role in carbon sequestration.", "se|ques|tra|tion", 2),
      word("permafrost", "/ˈpɜː.mə.frɒst/", "tầng đất đóng băng vĩnh cửu", "Melting permafrost releases large amounts of methane.", "per|ma|frost", 0),
      word("arid", "/ˈær.ɪd/", "khô cằn", "Few crops can grow in such an arid climate.", "ar|id", 0),
      word("aquifer", "/ˈæk.wɪ.fə/", "tầng ngậm nước", "The city draws its water from an underground aquifer.", "aq|ui|fer", 0),
      word("runoff", "/ˈrʌn.ɒf/", "dòng chảy tràn (nước mưa, phân bón)", "Fertiliser runoff from farms pollutes the lake.", "run|off", 0),
      word("greenwashing", "/ˈɡriːnˌwɒʃ.ɪŋ/", "tẩy xanh (quảng cáo 'xanh' giả)", "Activists accused the oil company of greenwashing.", "green|wash|ing", 0),
      word("upcycle", "/ˈʌp.saɪ.kəl/", "tái chế nâng cấp", "She upcycles old jeans into bags.", "up|cy|cle", 0),
      word("finite", "/ˈfaɪ.naɪt/", "có hạn", "Fossil fuels are a finite resource.", "fi|nite", 0, "Đọc /ˈfaɪ.naɪt/, khác với infinite /ˈɪn.fɪ.nət/."),
      word("irreversible", "/ˌɪr.ɪˈvɜː.sə.bəl/", "không thể đảo ngược", "Some of the damage to the reef is irreversible.", "ir|re|ver|si|ble", 2),
      word("flora", "/ˈflɔː.rə/", "hệ thực vật", "The island is home to unique flora and fauna.", "flo|ra", 0),
      word("fauna", "/ˈfɔː.nə/", "hệ động vật", "The park protects the region's native fauna.", "fau|na", 0),
      word("degradation", "/ˌdeɡ.rəˈdeɪ.ʃən/", "sự suy thoái", "Soil degradation reduces crop yields.", "deg|ra|da|tion", 2),
      word("reforestation", "/ˌriː.fɒr.ɪˈsteɪ.ʃən/", "sự tái trồng rừng", "The reforestation project has planted a million trees.", "re|for|es|ta|tion", 3),
      word("methane", "/ˈmiː.θeɪn/", "khí mê-tan", "Cattle produce large quantities of methane.", "meth|ane", 0),
      word("photovoltaic", "/ˌfəʊ.təʊ.vɒlˈteɪ.ɪk/", "quang điện", "Photovoltaic panels convert sunlight into electricity.", "pho|to|vol|ta|ic", 3),
      word("stewardship", "/ˈstjuː.əd.ʃɪp/", "sự quản lý có trách nhiệm", "Farmers have a role in the stewardship of the land.", "stew|ard|ship", 0),
      word("incinerate", "/ɪnˈsɪn.ər.eɪt/", "đốt (rác) thành tro", "The city incinerates most of its household waste.", "in|cin|er|ate", 1),
      word("watershed", "/ˈwɔː.tə.ʃed/", "bước ngoặt; lưu vực", "The Paris Agreement was a watershed in climate policy.", "wa|ter|shed", 0),
      word("overfishing", "/ˌəʊ.vəˈfɪʃ.ɪŋ/", "sự đánh bắt quá mức", "Overfishing has pushed several species close to extinction.", "o|ver|fish|ing", 2),
      word("anthropogenic", "/ˌæn.θrə.pəˈdʒen.ɪk/", "do con người gây ra", "Most scientists agree that recent warming is anthropogenic.", "an|thro|po|gen|ic", 3),
      word("effluent", "/ˈef.lu.ənt/", "nước thải (công nghiệp)", "The factory was fined for pumping effluent into the river.", "ef|flu|ent", 0),
    ],
  },
  {
    id: "suc-khoe-dao-duc",
    title: "Sức khoẻ, y học và đạo đức",
    words: [
      word("euthanasia", "/ˌjuː.θəˈneɪ.zi.ə/", "an tử", "Euthanasia is legal in only a few countries.", "eu|tha|na|si|a", 2),
      word("bioethics", "/ˈbaɪ.əʊˌeθ.ɪks/", "đạo đức sinh học", "Gene editing raises difficult questions in bioethics.", "bi|o|eth|ics", 0),
      word("placebo", "/pləˈsiː.bəʊ/", "giả dược", "Half the patients were given a placebo.", "pla|ce|bo", 1),
      word("pathogen", "/ˈpæθ.ə.dʒən/", "mầm bệnh", "The pathogen spreads through contaminated water.", "path|o|gen", 0),
      word("epidemiology", "/ˌep.ɪ.diː.miˈɒl.ə.dʒi/", "dịch tễ học", "She is a professor of epidemiology.", "ep|i|de|mi|ol|o|gy", 4),
      word("prognosis", "/prɒɡˈnəʊ.sɪs/", "tiên lượng (bệnh)", "The doctors say the prognosis is good.", "prog|no|sis", 1),
      word("palliative", "/ˈpæl.i.ə.tɪv/", "giảm nhẹ (không chữa khỏi)", "She works in palliative care for cancer patients.", "pal|li|a|tive", 0),
      word("immunise", "/ˈɪm.jə.naɪz/", "tiêm chủng, miễn dịch", "All children should be immunised against measles.", "im|mu|nise", 0),
      word("inoculation", "/ɪˌnɒk.jəˈleɪ.ʃən/", "sự tiêm chủng", "Inoculation has almost eliminated the disease.", "in|oc|u|la|tion", 3),
      word("antibody", "/ˈæn.tiˌbɒd.i/", "kháng thể", "The test detects antibodies to the virus.", "an|ti|bod|y", 0),
      word("anaesthetic", "/ˌæn.əsˈθet.ɪk/", "thuốc gây mê/tê", "The operation is done under general anaesthetic.", "an|aes|thet|ic", 2),
      word("dementia", "/dɪˈmen.ʃə/", "chứng mất trí", "Her grandfather suffers from dementia.", "de|men|tia", 1),
      word("malnutrition", "/ˌmæl.njuːˈtrɪʃ.ən/", "suy dinh dưỡng", "Malnutrition affects millions of children worldwide.", "mal|nu|tri|tion", 2),
      word("sedentary", "/ˈsed.ən.tər.i/", "ít vận động", "A sedentary lifestyle increases the risk of heart disease.", "sed|en|tar|y", 0),
      word("ailment", "/ˈeɪl.mənt/", "bệnh nhẹ, chứng bệnh", "The pharmacist can advise on minor ailments.", "ail|ment", 0),
      word("holistic", "/həˈlɪs.tɪk/", "toàn diện (xét cả con người)", "The clinic takes a holistic approach to health.", "ho|lis|tic", 1),
      word("clinical", "/ˈklɪn.ɪ.kəl/", "(thuộc) lâm sàng", "The drug is still undergoing clinical trials.", "clin|i|cal", 0),
      word("efficacy", "/ˈef.ɪ.kə.si/", "hiệu quả (của thuốc, biện pháp)", "There is little proof of the treatment's efficacy.", "ef|fi|ca|cy", 0),
      word("adverse", "/ˈæd.vɜːs/", "bất lợi, có hại", "Some patients experienced adverse reactions to the vaccine.", "ad|verse", 0),
      word("dosage", "/ˈdəʊ.sɪdʒ/", "liều lượng", "Do not exceed the recommended dosage.", "dos|age", 0),
      word("cloning", "/ˈkləʊ.nɪŋ/", "sự nhân bản vô tính", "Human cloning is banned in most countries.", "clon|ing", 0),
      word("embryo", "/ˈem.bri.əʊ/", "phôi", "Research on human embryos is strictly regulated.", "em|bry|o", 0),
      word("surrogate", "/ˈsʌr.ə.ɡət/", "(người) mang thai hộ; thay thế", "The couple had a baby with the help of a surrogate mother.", "sur|ro|gate", 0),
      word("confidentiality", "/ˌkɒn.fɪ.den.ʃiˈæl.ə.ti/", "tính bảo mật", "Doctors must respect patient confidentiality.", "con|fi|den|ti|al|i|ty", 4),
      word("conscientious", "/ˌkɒn.ʃiˈen.ʃəs/", "tận tâm, chu đáo", "She is a conscientious and caring nurse.", "con|sci|en|tious", 2),
      word("therapeutic", "/ˌθer.əˈpjuː.tɪk/", "có tác dụng chữa bệnh", "Gardening can be very therapeutic.", "ther|a|peu|tic", 2),
      word("psychiatric", "/ˌsaɪ.kiˈæt.rɪk/", "(thuộc) tâm thần học", "He spent a month in a psychiatric hospital.", "psy|chi|at|ric", 2, "p câm, ch đọc /k/: /ˌsaɪ.kiˈæt.rɪk/."),
      word("relapse", "/rɪˈlæps/", "sự tái phát; tái phát", "He relapsed after only a few weeks.", "re|lapse", 1),
      word("debilitating", "/dɪˈbɪl.ɪ.teɪ.tɪŋ/", "làm suy nhược", "Migraines can be a debilitating condition.", "de|bil|i|tat|ing", 1),
      word("benign", "/bɪˈnaɪn/", "lành tính", "Fortunately, the tumour was benign.", "be|nign", 1, "Chữ g câm: /bɪˈnaɪn/."),
      word("malignant", "/məˈlɪɡ.nənt/", "ác tính", "Tests showed that the growth was malignant.", "ma|lig|nant", 1),
      word("invasive", "/ɪnˈveɪ.sɪv/", "xâm lấn", "The new technique is less invasive than traditional surgery.", "in|va|sive", 1),
      word("triage", "/ˈtriː.ɑːʒ/", "sự phân loại bệnh nhân cấp cứu", "Nurses carry out triage when patients arrive.", "tri|age", 0),
      word("sanitation", "/ˌsæn.ɪˈteɪ.ʃən/", "vệ sinh môi trường (nước, cống)", "Poor sanitation leads to the spread of disease.", "san|i|ta|tion", 2),
      word("contraception", "/ˌkɒn.trəˈsep.ʃən/", "biện pháp tránh thai", "The clinic offers free advice on contraception.", "con|tra|cep|tion", 2),
      word("longevity", "/lɒnˈdʒev.ə.ti/", "tuổi thọ", "Diet may be the secret of their longevity.", "lon|gev|i|ty", 1),
      word("susceptible", "/səˈsep.tə.bəl/", "dễ mắc, dễ bị ảnh hưởng", "Older people are more susceptible to infection.", "sus|cep|ti|ble", 1),
    ],
  },
  {
    id: "truyen-thong-thuyet-phuc",
    title: "Truyền thông và thuyết phục",
    words: [
      word("rhetoric", "/ˈret.ər.ɪk/", "lối nói hoa mỹ, tu từ", "His speech was full of empty rhetoric.", "rhet|o|ric", 0, "h câm, nhấn âm 1: RHET-o-ric (khác rhetorical nhấn âm 2)."),
      word("disinformation", "/ˌdɪs.ɪn.fəˈmeɪ.ʃən/", "thông tin sai lệch (cố ý)", "The campaign spread disinformation on social media.", "dis|in|for|ma|tion", 3),
      word("sensationalise", "/senˈseɪ.ʃən.əl.aɪz/", "giật gân hoá", "The press sensationalised the story.", "sen|sa|tion|al|ise", 1),
      word("editorial", "/ˌed.ɪˈtɔː.ri.əl/", "bài xã luận", "The newspaper's editorial criticised the plan.", "ed|i|to|ri|al", 2),
      word("manipulative", "/məˈnɪp.jə.lə.tɪv/", "thao túng", "The advert uses manipulative techniques to target children.", "ma|nip|u|la|tive", 1),
      word("slant", "/slɑːnt/", "góc nhìn thiên lệch", "The report has a clear political slant.", "slant", 0),
      word("cogent", "/ˈkəʊ.dʒənt/", "có sức thuyết phục, chặt chẽ", "She made a cogent case for reform.", "co|gent", 0),
      word("eloquent", "/ˈel.ə.kwənt/", "hùng hồn, lưu loát", "He gave an eloquent speech at the ceremony.", "el|o|quent", 0),
      word("insinuate", "/ɪnˈsɪn.ju.eɪt/", "ám chỉ (điều xấu)", "Are you insinuating that I lied?", "in|sin|u|ate", 1),
      word("innuendo", "/ˌɪn.juˈen.dəʊ/", "lời bóng gió", "The article relies on rumour and innuendo.", "in|nu|en|do", 2),
      word("defamation", "/ˌdef.əˈmeɪ.ʃən/", "sự phỉ báng", "The actor sued the magazine for defamation.", "def|a|ma|tion", 2),
      word("libel", "/ˈlaɪ.bəl/", "tội bôi nhọ (bằng văn bản)", "The newspaper lost a libel case.", "li|bel", 0),
      word("clickbait", "/ˈklɪk.beɪt/", "tiêu đề câu nhấp chuột", "Headlines like that are just clickbait.", "click|bait", 0),
      word("polarise", "/ˈpəʊ.lə.raɪz/", "phân cực, chia rẽ", "The debate has polarised public opinion.", "po|lar|ise", 0),
      word("sway", "/sweɪ/", "làm lung lay, tác động (ý kiến)", "Voters are easily swayed by television adverts.", "sway", 0),
      word("soundbite", "/ˈsaʊnd.baɪt/", "câu nói ngắn gọn để trích trên truyền thông", "Politicians love a catchy soundbite.", "sound|bite", 0),
      word("orator", "/ˈɒr.ə.tə/", "nhà hùng biện", "Churchill was a brilliant orator.", "or|a|tor", 0),
      word("scaremongering", "/ˈskeəˌmʌŋ.ɡər.ɪŋ/", "sự gieo rắc hoang mang", "The minister dismissed the warnings as scaremongering.", "scare|mon|ger|ing", 0),
      word("whistle-blower", "/ˈwɪs.əlˌbləʊ.ə/", "người tố giác (sai phạm nội bộ)", "A whistle-blower leaked the documents to the press.", "whis|tle|blow|er", 0),
      word("anonymity", "/ˌæn.ɒnˈɪm.ə.ti/", "sự ẩn danh", "The source spoke on condition of anonymity.", "an|on|ym|i|ty", 2),
      word("newsworthy", "/ˈnjuːzˌwɜː.ði/", "đáng đưa tin", "Editors decide what is newsworthy.", "news|wor|thy", 0),
      word("subliminal", "/ˌsʌbˈlɪm.ɪ.nəl/", "(tác động) tiềm thức", "Subliminal advertising is banned on British television.", "sub|lim|i|nal", 1),
      word("pundit", "/ˈpʌn.dɪt/", "nhà bình luận, chuyên gia", "Political pundits predicted a narrow win.", "pun|dit", 0),
      word("verbatim", "/vɜːˈbeɪ.tɪm/", "nguyên văn", "The speech was reported verbatim in the newspaper.", "ver|ba|tim", 1),
      word("fallacy", "/ˈfæl.ə.si/", "ngụy biện; quan niệm sai", "It is a fallacy that money brings happiness.", "fal|la|cy", 0),
      word("captivate", "/ˈkæp.tɪ.veɪt/", "làm say mê", "Her story captivated the audience.", "cap|ti|vate", 0),
      word("demonise", "/ˈdiː.mə.naɪz/", "quỷ hoá, bôi xấu", "The media tend to demonise young people.", "de|mon|ise", 0),
      word("mouthpiece", "/ˈmaʊθ.piːs/", "cơ quan ngôn luận, người phát ngôn", "The channel is seen as a mouthpiece of the government.", "mouth|piece", 0),
      word("gatekeeper", "/ˈɡeɪtˌkiː.pə/", "người gác cổng (kiểm soát thông tin)", "Editors used to be the gatekeepers of information.", "gate|keep|er", 0),
      word("readership", "/ˈriː.də.ʃɪp/", "lượng độc giả", "The magazine has a readership of two million.", "read|er|ship", 0),
      word("censure", "/ˈsen.ʃə/", "sự khiển trách chính thức", "The minister faced censure from Parliament.", "cen|sure", 0),
      word("spin-doctor", "/ˈspɪnˌdɒk.tə/", "chuyên gia 'lái' dư luận", "The party's spin-doctors worked hard to limit the damage.", "spin|doc|tor", 0),
      word("embellish", "/ɪmˈbel.ɪʃ/", "thêm thắt, tô vẽ", "He tends to embellish his stories.", "em|bel|lish", 1),
    ],
  },
  {
    id: "danh-tu-lap-luan",
    title: "Danh từ trừu tượng trong lập luận",
    words: [
      word("rationale", "/ˌræʃ.əˈnɑːl/", "lý do cơ bản, cơ sở lập luận", "The rationale behind the decision was never explained.", "ra|tion|ale", 2, "Nhấn âm cuối: ra-tion-ALE /ˌræʃ.əˈnɑːl/."),
      word("premise", "/ˈprem.ɪs/", "tiền đề", "The argument rests on a false premise.", "prem|ise", 0),
      word("caveat", "/ˈkæv.i.æt/", "lời cảnh báo, điều kiện kèm theo", "I agree, with one caveat: we need more funding.", "cav|e|at", 0),
      word("paradox", "/ˈpær.ə.dɒks/", "nghịch lý", "It is a paradox that having more choice can make people less satisfied.", "par|a|dox", 0),
      word("dichotomy", "/daɪˈkɒt.ə.mi/", "sự phân đôi, đối lập", "There is a false dichotomy between economy and environment.", "di|chot|o|my", 1),
      word("paradigm", "/ˈpær.ə.daɪm/", "mô hình, hệ khuôn mẫu", "The discovery led to a paradigm shift in physics.", "par|a|digm", 0, "Chữ g câm: /ˈpær.ə.daɪm/."),
      word("ambiguity", "/ˌæm.bɪˈɡjuː.ə.ti/", "sự mơ hồ, nước đôi", "The ambiguity of the wording caused a dispute.", "am|bi|gu|i|ty", 2),
      word("tenet", "/ˈten.ɪt/", "nguyên lý, giáo lý", "Free speech is a central tenet of democracy.", "ten|et", 0),
      word("axiom", "/ˈæk.si.əm/", "tiên đề, chân lý hiển nhiên", "It is an axiom of economics that people respond to incentives.", "ax|i|om", 0),
      word("corollary", "/kəˈrɒl.ər.i/", "hệ quả tất yếu", "Higher unemployment is a corollary of the cuts.", "co|rol|la|ry", 1),
      word("contention", "/kənˈten.ʃən/", "luận điểm; sự tranh cãi", "It is my contention that the law is unfair.", "con|ten|tion", 1),
      word("assertion", "/əˈsɜː.ʃən/", "sự khẳng định, lời quả quyết", "There is no evidence for his assertion.", "as|ser|tion", 1),
      word("presupposition", "/ˌpriː.sʌp.əˈzɪʃ.ən/", "giả định ngầm, tiền giả định", "The theory is based on several questionable presuppositions.", "pre|sup|po|si|tion", 3),
      word("ramification", "/ˌræm.ɪ.fɪˈkeɪ.ʃən/", "hậu quả (phức tạp, lan rộng)", "Have you considered the legal ramifications?", "ram|i|fi|ca|tion", 3),
      word("repercussion", "/ˌriː.pəˈkʌʃ.ən/", "tác động dội lại, hậu quả", "The scandal had serious repercussions for the party.", "re|per|cus|sion", 2),
      word("prerequisite", "/ˌpriːˈrek.wɪ.zɪt/", "điều kiện tiên quyết", "Stability is a prerequisite for growth.", "pre|req|ui|site", 1),
      word("credibility", "/ˌkred.əˈbɪl.ə.ti/", "sự đáng tin cậy, uy tín", "The scandal damaged the minister's credibility.", "cred|i|bil|i|ty", 2),
      word("discrepancy", "/dɪˈskrep.ən.si/", "sự chênh lệch, không khớp", "There is a discrepancy between the two reports.", "dis|crep|an|cy", 1),
      word("nuance", "/ˈnjuː.ɒns/", "sắc thái tinh tế", "The translation loses much of the nuance of the original.", "nu|ance", 0),
      word("trade-off", "/ˈtreɪd.ɒf/", "sự đánh đổi", "There is always a trade-off between speed and quality.", "trade|off", 0),
      word("prerogative", "/prɪˈrɒɡ.ə.tɪv/", "đặc quyền", "Choosing the ministers is the prime minister's prerogative.", "pre|rog|a|tive", 1),
      word("generalisation", "/ˌdʒen.ər.əl.aɪˈzeɪ.ʃən/", "sự khái quát hoá, vơ đũa cả nắm", "It is a sweeping generalisation to say all teenagers are lazy.", "gen|er|al|i|sa|tion", 4),
      word("counterpoint", "/ˈkaʊn.tə.pɔɪnt/", "sự tương phản, luận điểm đối trọng", "Her calm voice was a counterpoint to his anger.", "coun|ter|point", 0),
      word("analogy", "/əˈnæl.ə.dʒi/", "phép so sánh tương đồng", "He drew an analogy between the brain and a computer.", "a|nal|o|gy", 1),
      word("quandary", "/ˈkwɒn.dri/", "tình thế khó xử", "I'm in a quandary about which job to accept.", "quan|dary", 0),
      word("impetus", "/ˈɪm.pɪ.təs/", "động lực thúc đẩy", "The report gave new impetus to the campaign.", "im|pe|tus", 0),
      word("prevalence", "/ˈprev.əl.əns/", "sự phổ biến, tỷ lệ mắc", "The prevalence of obesity has doubled.", "prev|a|lence", 0),
      word("propensity", "/prəˈpen.sə.ti/", "xu hướng, thiên hướng", "He has a propensity to exaggerate.", "pro|pen|si|ty", 1),
      word("predicament", "/prɪˈdɪk.ə.mənt/", "tình cảnh khó khăn", "The loss of her job left her in a difficult predicament.", "pre|dic|a|ment", 1),
      word("ethos", "/ˈiː.θɒs/", "đặc tính, tinh thần (của tổ chức)", "The school has a strong ethos of community service.", "e|thos", 0),
      word("foresight", "/ˈfɔː.saɪt/", "sự nhìn xa trông rộng", "Thanks to her foresight, we had enough supplies.", "fore|sight", 0),
      word("underpinning", "/ˈʌn.dəˌpɪn.ɪŋ/", "nền tảng (lý thuyết)", "The policy lacks any theoretical underpinning.", "un|der|pin|ning", 0),
      word("semantics", "/sɪˈmæn.tɪks/", "ngữ nghĩa; chuyện chữ nghĩa", "Whether we call it a tax or a fee is just semantics.", "se|man|tics", 1),
      word("antithesis", "/ænˈtɪθ.ə.sɪs/", "sự đối lập hoàn toàn", "His behaviour is the antithesis of good leadership.", "an|tith|e|sis", 1),
      word("conundrum", "/kəˈnʌn.drəm/", "câu hỏi hóc búa", "Funding pensions is a conundrum for every government.", "co|nun|drum", 1),
      word("facet", "/ˈfæs.ɪt/", "khía cạnh", "The book explores every facet of her life.", "fac|et", 0),
      word("gist", "/dʒɪst/", "ý chính", "I didn't understand every word, but I got the gist.", "gist", 0),
    ],
  },
  {
    id: "tinh-tu-trang-tu-danh-gia",
    title: "Tính từ và trạng từ đánh giá",
    words: [
      word("plausible", "/ˈplɔː.zə.bəl/", "hợp lý, nghe có lý", "Her explanation sounded perfectly plausible.", "plau|si|ble", 0),
      word("tenuous", "/ˈten.ju.əs/", "mong manh, yếu ớt", "The link between the two events is tenuous at best.", "ten|u|ous", 0),
      word("spurious", "/ˈspjʊə.ri.əs/", "giả mạo, không có căn cứ", "The claim is based on spurious statistics.", "spu|ri|ous", 0),
      word("ubiquitous", "/juːˈbɪk.wɪ.təs/", "có mặt khắp nơi", "Smartphones have become ubiquitous.", "u|biq|ui|tous", 1),
      word("pervasive", "/pəˈveɪ.sɪv/", "lan tràn, thấm sâu", "Corruption remains pervasive in the industry.", "per|va|sive", 1),
      word("unequivocally", "/ˌʌn.ɪˈkwɪv.ə.kəl.i/", "một cách dứt khoát, rõ ràng", "The minister unequivocally denied the allegations.", "un|e|quiv|o|cal|ly", 2),
      word("meticulous", "/məˈtɪk.jə.ləs/", "tỉ mỉ, kỹ lưỡng", "She keeps meticulous records of every experiment.", "me|tic|u|lous", 1),
      word("paramount", "/ˈpær.ə.maʊnt/", "tối quan trọng", "Safety is of paramount importance.", "par|a|mount", 0),
      word("pivotal", "/ˈpɪv.ə.təl/", "then chốt", "She played a pivotal role in the negotiations.", "piv|o|tal", 0),
      word("detrimental", "/ˌdet.rɪˈmen.təl/", "có hại", "Lack of sleep is detrimental to your health.", "det|ri|men|tal", 2),
      word("conducive", "/kənˈdʒuː.sɪv/", "có lợi cho, tạo điều kiện", "A noisy office is not conducive to concentration.", "con|du|cive", 1),
      word("intrinsic", "/ɪnˈtrɪn.zɪk/", "thuộc bản chất, nội tại", "Learning has intrinsic value beyond getting a job.", "in|trin|sic", 1),
      word("inherent", "/ɪnˈher.ənt/", "vốn có, cố hữu", "There are risks inherent in any investment.", "in|her|ent", 1),
      word("cursory", "/ˈkɜː.sər.i/", "qua loa, lướt qua", "He gave the report only a cursory glance.", "cur|so|ry", 0),
      word("arbitrary", "/ˈɑː.bɪ.trər.i/", "tuỳ tiện", "The decision seemed completely arbitrary.", "ar|bi|trar|y", 0),
      word("divisive", "/dɪˈvaɪ.sɪv/", "gây chia rẽ", "Immigration remains a divisive issue.", "di|vi|sive", 1),
      word("dubious", "/ˈdʒuː.bi.əs/", "đáng ngờ", "The company has a dubious reputation.", "du|bi|ous", 0),
      word("far-reaching", "/ˌfɑːˈriː.tʃɪŋ/", "sâu rộng", "The reforms will have far-reaching consequences.", "far|reach|ing", 1),
      word("exemplary", "/ɪɡˈzem.plər.i/", "gương mẫu, mẫu mực", "His behaviour in class has been exemplary.", "ex|em|pla|ry", 1),
      word("lamentable", "/ləˈmen.tə.bəl/", "đáng tiếc, tệ hại", "The team's performance was lamentable.", "la|men|ta|ble", 1),
      word("egregious", "/ɪˈɡriː.dʒəs/", "nghiêm trọng, trắng trợn", "It was an egregious abuse of power.", "e|gre|gious", 1),
      word("deplorable", "/dɪˈplɔː.rə.bəl/", "đáng trách, tồi tệ", "The prisoners were kept in deplorable conditions.", "de|plor|a|ble", 1),
      word("laudable", "/ˈlɔː.də.bəl/", "đáng khen", "Their aims are laudable, but the plan is unrealistic.", "lau|da|ble", 0),
      word("inadvertently", "/ˌɪn.ədˈvɜː.tənt.li/", "vô tình", "I inadvertently deleted the file.", "in|ad|ver|tent|ly", 2),
      word("invariably", "/ɪnˈveə.ri.ə.bli/", "luôn luôn, không thay đổi", "The meetings invariably start late.", "in|var|i|a|bly", 1),
      word("conspicuous", "/kənˈspɪk.ju.əs/", "dễ thấy, nổi bật", "He felt conspicuous in his bright red suit.", "con|spic|u|ous", 1),
      word("markedly", "/ˈmɑː.kɪd.li/", "rõ rệt", "Her health has improved markedly.", "mark|ed|ly", 0, "Đọc 3 âm tiết /ˈmɑː.kɪd.li/, không đọc 'markt-ly'."),
      word("demonstrably", "/dɪˈmɒn.strə.bli/", "một cách có thể chứng minh", "The claim is demonstrably false.", "de|mon|stra|bly", 1),
      word("inexorably", "/ɪˈnek.sər.ə.bli/", "một cách không thể cưỡng lại", "Prices are rising inexorably.", "i|nex|o|ra|bly", 1),
      word("purportedly", "/pəˈpɔː.tɪd.li/", "được cho là (chưa chắc đúng)", "The letter was purportedly written by the king.", "pur|port|ed|ly", 1),
      word("unwarranted", "/ʌnˈwɒr.ən.tɪd/", "không có cơ sở, không chính đáng", "The criticism was completely unwarranted.", "un|war|rant|ed", 1),
      word("untenable", "/ʌnˈten.ə.bəl/", "không thể bảo vệ/duy trì", "His position as leader became untenable.", "un|ten|a|ble", 1),
      word("robust", "/rəʊˈbʌst/", "vững chắc, mạnh mẽ", "We need robust evidence before changing the policy.", "ro|bust", 1),
      word("succinct", "/səkˈsɪŋkt/", "ngắn gọn, súc tích", "Keep your answers clear and succinct.", "suc|cinct", 1, "cc đọc là /ks/: /səkˈsɪŋkt/."),
      word("verbose", "/vɜːˈbəʊs/", "dài dòng", "The report is verbose and poorly organised.", "ver|bose", 1),
      word("incisive", "/ɪnˈsaɪ.sɪv/", "sắc sảo", "She is known for her incisive analysis.", "in|ci|sive", 1),
      word("judicious", "/dʒuːˈdɪʃ.əs/", "sáng suốt, khôn ngoan", "A judicious use of colour can transform a room.", "ju|di|cious", 1),
      word("blatant", "/ˈbleɪ.tənt/", "trắng trợn, lộ liễu", "It was a blatant lie.", "bla|tant", 0),
    ],
  },
  {
    id: "goc-hy-lap-latin",
    title: "Từ gốc Hy Lạp và Latin",
    words: [
      word("hubris", "/ˈhjuː.brɪs/", "sự ngạo mạn quá mức", "The CEO's hubris led to the company's collapse.", "hu|bris", 0),
      word("nemesis", "/ˈnem.ə.sɪs/", "kẻ thù truyền kiếp; sự báo ứng", "The champion finally beat his old nemesis.", "nem|e|sis", 0),
      word("charisma", "/kəˈrɪz.mə/", "sức hút cá nhân", "She has the charisma of a natural leader.", "cha|ris|ma", 1, "ch đọc /k/: /kəˈrɪz.mə/."),
      word("dogma", "/ˈdɒɡ.mə/", "giáo điều", "We should question political dogma.", "dog|ma", 0),
      word("psyche", "/ˈsaɪ.ki/", "tâm hồn, tâm lý", "The war left deep scars on the national psyche.", "psy|che", 0, "p câm, e cuối đọc /i/: /ˈsaɪ.ki/."),
      word("panacea", "/ˌpæn.əˈsiː.ə/", "thuốc chữa bách bệnh", "Technology is not a panacea for poor education.", "pan|a|ce|a", 2),
      word("crux", "/krʌks/", "mấu chốt", "The crux of the matter is who pays.", "crux", 0),
      word("alibi", "/ˈæl.ɪ.baɪ/", "chứng cứ ngoại phạm", "The suspect had a strong alibi.", "al|i|bi", 0),
      word("memorandum", "/ˌmem.əˈræn.dəm/", "bị vong lục, bản ghi nhớ", "The two countries signed a memorandum of understanding.", "mem|o|ran|dum", 2),
      word("addendum", "/əˈden.dəm/", "phần bổ sung", "An addendum was added to the contract.", "ad|den|dum", 1),
      word("quorum", "/ˈkwɔː.rəm/", "số đại biểu tối thiểu", "The meeting was cancelled because there was no quorum.", "quo|rum", 0),
      word("hiatus", "/haɪˈeɪ.təs/", "sự gián đoạn, tạm ngưng", "The band returned after a five-year hiatus.", "hi|a|tus", 1),
      word("kudos", "/ˈkjuː.dɒs/", "uy tín, sự ca ngợi", "Winning the prize brought her a lot of kudos.", "ku|dos", 0),
      word("pseudonym", "/ˈsjuː.də.nɪm/", "bút danh", "She wrote under a male pseudonym.", "pseu|do|nym", 0, "p câm: /ˈsjuː.də.nɪm/."),
      word("epitome", "/ɪˈpɪt.ə.mi/", "hình mẫu tiêu biểu", "He is the epitome of good manners.", "e|pit|o|me", 1, "Đọc 4 âm tiết: e-PIT-o-me /ɪˈpɪt.ə.mi/."),
      word("apathy", "/ˈæp.ə.θi/", "sự thờ ơ", "Voter apathy is a growing problem.", "ap|a|thy", 0),
      word("enigma", "/ɪˈnɪɡ.mə/", "điều bí ẩn", "The artist remains an enigma to his fans.", "e|nig|ma", 1),
      word("genesis", "/ˈdʒen.ə.sɪs/", "nguồn gốc, sự khởi nguồn", "The book traces the genesis of the idea.", "gen|e|sis", 0),
      word("pathos", "/ˈpeɪ.θɒs/", "sức gợi thương cảm", "The scene is full of pathos.", "pa|thos", 0),
      word("lexicon", "/ˈlek.sɪ.kən/", "từ vựng (của một ngành, ngôn ngữ)", "'Selfie' has entered the English lexicon.", "lex|i|con", 0),
      word("symposium", "/sɪmˈpəʊ.zi.əm/", "hội thảo chuyên đề", "She spoke at an international symposium on AI.", "sym|po|si|um", 1),
      word("consortium", "/kənˈsɔː.ti.əm/", "liên doanh, tập đoàn hợp tác", "A consortium of banks financed the project.", "con|sor|ti|um", 1),
      word("moratorium", "/ˌmɒr.əˈtɔː.ri.əm/", "lệnh tạm hoãn", "The government declared a moratorium on new mines.", "mor|a|to|ri|um", 2),
      word("stratum", "/ˈstrɑː.təm/", "tầng lớp; địa tầng", "The tax affects every stratum of society.", "stra|tum", 0),
      word("circa", "/ˈsɜː.kə/", "khoảng (năm)", "The church was built circa 1450.", "cir|ca", 0),
      word("etymology", "/ˌet.ɪˈmɒl.ə.dʒi/", "từ nguyên học", "The etymology of the word is uncertain.", "et|y|mol|o|gy", 2),
      word("prologue", "/ˈprəʊ.lɒɡ/", "lời mở đầu", "The novel opens with a short prologue.", "pro|logue", 0),
    ],
  },
];

export default topics;
