import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "nguyen-am-doi",
  title: "Nguyên âm đôi",
  minutes: 20,
  lecture: {
    title: "Tám nguyên âm đôi và cách trượt âm",
    blocks: [
      p("Khách nước ngoài hỏi số điện thoại, học trò tôi đáp “My phôn number is…”. Người nghe vẫn hiểu, nhưng nghe ngay ra giọng Việt. Lý do là từ **phone** /fəʊn/ có một **nguyên âm đôi**, còn chúng ta lại đọc thành một âm “ô” phẳng lì."),
      p("Nguyên âm đôi là **hai nguyên âm nối liền trong một âm tiết**: miệng bắt đầu ở vị trí của âm thứ nhất rồi **trượt** sang vị trí của âm thứ hai. Âm đầu rõ và dài hơn, âm sau nhẹ, như cái đuôi. Nếu hàm và môi không chuyển động khi các bạn đọc, tức là các bạn chưa trượt."),
      table(
        ["Âm", "Trượt từ… sang…", "Ví dụ", "Gần với tiếng Việt"],
        ["/eɪ/", "/e/ sang /ɪ/", "day, rain, name", "“ê-i”, không phải “ê”"],
        ["/aɪ/", "/a/ sang /ɪ/", "my, time, nice", "“ai”"],
        ["/ɔɪ/", "/ɔ/ sang /ɪ/", "boy, coin, noise", "“oi”"],
        ["/aʊ/", "/a/ sang /ʊ/", "now, house, down", "“ao”"],
        ["/əʊ/", "/ə/ sang /ʊ/", "go, phone, home", "“ơ-u”, không phải “ô”"],
        ["/ɪə/", "/ɪ/ sang /ə/", "near, here, idea", "“i-ơ”, gần “ia”"],
        ["/eə/", "/e/ sang /ə/", "hair, where, care", "“e-ơ”"],
        ["/ʊə/", "/ʊ/ sang /ə/", "tour, poor, sure", "“u-ơ”, gần “ua”"],
      ),
      ex("I'll phone you when I get home.", "Về đến nhà tôi sẽ gọi cho bạn.", "Phone và home đều có /əʊ/: bắt đầu bằng “ơ” rồi khép môi tròn thành “u”."),
      ex("The boy found a coin near the house.", "Cậu bé nhặt được một đồng xu gần ngôi nhà.", "Boy và coin có /ɔɪ/, found và house có /aʊ/, near có /ɪə/."),
      ex("Where can I buy a nice chair?", "Tôi có thể mua một chiếc ghế đẹp ở đâu?", "Where và chair có /eə/, buy và nice có /aɪ/."),
      p("Âm **/əʊ/** là dấu hiệu rõ nhất của giọng Anh-Anh: người Anh bắt đầu bằng /ə/ (gần “ơ”), còn người Mỹ bắt đầu bằng âm gần “ô”. Ba âm **/ɪə/ /eə/ /ʊə/** thì kết thúc bằng /ə/, và trong tiếng Anh-Anh chữ “r” ở cuối từ như near, hair, tour **không đọc**."),
      mistake("phone đọc thành “phôn”, no đọc thành “nô”", "phone /fəʊn/, no /nəʊ/: trượt từ “ơ” sang “u”", "Tiếng Việt có âm “ô” đơn, nên người Việt thay nguyên âm đôi bằng một âm phẳng. Phải để môi chuyển động từ thả lỏng sang tròn trong cùng một âm tiết."),
      mistake("late đọc thành “lết”, take đọc thành “tếch”", "late /leɪt/, take /teɪk/: kéo “ê” rồi trượt sang “i”, giữ phụ âm cuối", "Người Việt vừa đọc /eɪ/ thành “ê” ngắn, vừa nuốt âm cuối. Late mà đọc thành “lết” thì người nghe khó phân biệt với let /let/."),
      mistake("now và no đọc giống nhau", "now /naʊ/ (mở rộng miệng, “ao”), no /nəʊ/ (“ơ-u”)", "Khi hai nguyên âm đôi đều bị đọc thành một âm đơn, now và no nghe như nhau. Hãy mở miệng rộng ở đầu /aʊ/."),
      tip("Đặt **một ngón tay lên cằm** khi đọc day, my, now, go. Nếu cằm và môi **di chuyển** trong lúc đọc, các bạn đang trượt đúng. Lúc mới tập, hãy đọc chậm và phóng đại độ trượt: “ê… i”, “ơ… u”, rồi nhanh dần cho đến khi thành một âm tiết."),
      teacher("Tôi dạy nguyên âm đôi bằng một câu các bạn nói hằng ngày: **“Hello, how are you? I'm going home now.”** Trong câu đó có /əʊ/, /aʊ/, /aɪ/ đủ cả. Các bạn thu âm giọng mình, nghe lại xem hello có còn là “hê-lô” không, home có còn là “hôm” không. Tự nghe giọng mình là cách sửa nhanh nhất mà tôi biết."),
    ],
  },
  words: [
    word("phone", "/fəʊn/", "điện thoại; gọi điện", "Can I use your phone?", "phone", 0, "Không đọc “phôn”: bắt đầu bằng “ơ” rồi tròn môi thành “u”, cuối từ giữ âm /n/."),
    word("rain", "/reɪn/", "mưa", "It often rains in Hanoi in summer.", "rain", 0, "Trượt “ê-i” rồi mới đến /n/, đừng đọc thành “rên”."),
    word("time", "/taɪm/", "thời gian", "What time is it?", "time", 0, "Mở miệng cho /a/ rồi trượt lên /ɪ/, cuối từ khép môi cho /m/."),
    word("boy", "/bɔɪ/", "cậu bé", "The boy is my son.", "boy", 0),
    word("house", "/haʊs/", "ngôi nhà", "Their house is near the lake.", "house", 0, "Đọc “hao” rồi thêm /s/ ở cuối; nhiều người Việt bỏ mất /s/."),
    word("near", "/nɪə/", "gần", "Is there a bank near here?", "near", 0, "Trượt “i-ơ”, không đọc chữ “r” cuối trong tiếng Anh-Anh."),
    word("hair", "/heə/", "tóc", "She has long black hair.", "hair", 0, "Trượt “e-ơ”; đừng đọc thành “he” hay “hia”."),
    word("tour", "/tʊə/", "chuyến tham quan", "We went on a tour of the old town.", "tour", 0, "Trượt “u-ơ”; nhiều người Anh ngày nay cũng đọc là /tɔː/."),
  ],
  exercises: [
    listen("pa-n03-1", "wait", ["wet", "wait", "white"], 1, "Wait /weɪt/ có /eɪ/ trượt “ê-i”. Wet /wet/ chỉ có một âm “e” ngắn, white /waɪt/ có /aɪ/."),
    listen("pa-n03-2", "coat", ["cot", "caught", "coat"], 2, "Coat /kəʊt/ có nguyên âm đôi /əʊ/, môi chuyển từ thả lỏng sang tròn. Cot /kɒt/ và caught /kɔːt/ là nguyên âm đơn."),
    mc("pa-n03-3", "Từ nào có nguyên âm đôi /aʊ/?", ["house", "horse", "hose"], 0, "House /haʊs/ có /aʊ/ (“ao”). Horse /hɔːs/ có /ɔː/, hose /həʊz/ có /əʊ/."),
    mc("pa-n03-4", "Từ nào có âm /eə/?", ["hear", "her", "hair", "hire"], 2, "Hair /heə/ trượt “e-ơ”. Hear /hɪə/ có /ɪə/, her /hɜː/ có /ɜː/, hire có /aɪə/."),
    fill("pa-n03-5", "My ___ is Lan. (tên, có âm /eɪ/)", ["name"], "Name /neɪm/: kéo “ê” rồi trượt sang “i”, rồi khép môi cho /m/. Đừng đọc thành “nêm”."),
    fill("pa-n03-6", "I'll ___ you tonight. (gọi điện, có âm /əʊ/)", ["phone"], "Phone /fəʊn/ trượt từ “ơ” sang “u”. Call cũng là gọi điện nhưng có âm /ɔː/, không phải /əʊ/."),
    reorder("pa-n03-7", "Where is my brown coat?", "Where + is + my + tính từ + danh từ? Where có /eə/, brown có /aʊ/, coat có /əʊ/."),
    reorder("pa-n03-8", "Don't go home alone.", "Câu mệnh lệnh phủ định: Don't + động từ. Cả bốn từ đều có /əʊ/, rất tốt để luyện trượt âm."),
  ],
  speaking: [
    say("I'll phone you when I get home.", "Về đến nhà tôi sẽ gọi cho bạn."),
    say("The boy found a coin near the house.", "Cậu bé nhặt được một đồng xu gần ngôi nhà."),
    say("It's time to go now.", "Đến giờ đi rồi."),
  ],
});
