import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "phu-am-huu-thanh-vo-thanh",
  title: "Phụ âm hữu thanh và vô thanh",
  minutes: 20,
  lecture: {
    title: "Các cặp phụ âm và hai âm /θ/, /ð/",
    blocks: [
      p("Trong cuộc họp, một kỹ sư người Việt nói “I sink so” thay cho **I think so** (tôi nghĩ vậy). Đồng nghiệp người Anh mỉm cười, vì sink là chìm. Phụ âm tiếng Anh có nhiều âm không có trong tiếng Việt, và nhiều cặp âm chỉ khác nhau ở **một chi tiết nhỏ**: dây thanh có rung hay không."),
      p("Phụ âm **vô thanh** chỉ có hơi đi ra, dây thanh **không rung**. Phụ âm **hữu thanh** có cùng vị trí môi và lưỡi, nhưng dây thanh **rung**. Vì vậy chúng đi thành từng cặp: miệng đặt y hệt nhau, chỉ khác ở cổ họng."),
      table(
        ["Vô thanh", "Hữu thanh", "Cặp từ ví dụ"],
        ["/p/", "/b/", "pig – big"],
        ["/t/", "/d/", "town – down"],
        ["/k/", "/ɡ/", "coat – goat"],
        ["/f/", "/v/", "fan – van"],
        ["/s/", "/z/", "sip – zip"],
        ["/ʃ/", "/ʒ/", "pressure – pleasure"],
        ["/tʃ/", "/dʒ/", "cheap – jeep"],
        ["/θ/", "/ð/", "think – this"],
      ),
      tip("**Phép thử cổ họng**: đặt hai ngón tay lên cổ, kéo dài “ssss” rồi chuyển sang “zzzz”. Với /s/ cổ họng im lặng, với /z/ các bạn sẽ thấy **rung** dưới ngón tay. Làm tương tự với /f/ và /v/. Đây là cách tự kiểm tra đơn giản nhất mà không cần ai bên cạnh."),
      p("Hai âm **/θ/** (think) và **/ð/** (this) không có trong tiếng Việt. Đặt **đầu lưỡi giữa hai hàm răng**, hơi thò ra ngoài một chút, rồi thổi hơi qua khe giữa lưỡi và răng trên. Với /θ/ chỉ có hơi; với /ð/ thêm tiếng rung ở cổ họng. Chữ “th” tiếng Việt là âm khác hẳn, đừng dùng nó thay thế."),
      ex("I think this is my bag.", "Tôi nghĩ đây là túi của tôi.", "Think bắt đầu bằng /θ/ (chỉ có hơi), this bắt đầu bằng /ð/ (có rung). Cả hai đều phải thò đầu lưỡi."),
      ex("Thank you, that's very kind of you.", "Cảm ơn bạn, bạn thật tốt.", "Thank có /θ/, that có /ð/, very có /v/: môi dưới chạm răng trên."),
      mistake("think đọc thành sink /sɪŋk/ hoặc “tink”", "think /θɪŋk/: đầu lưỡi giữa hai răng, thổi hơi", "Tiếng Việt không có /θ/, nên người Việt thay bằng âm gần nhất là “x” hoặc “t”. Nhưng sink là chìm, còn thin (gầy) sẽ thành sin (tội lỗi) hay tin (hộp thiếc)."),
      mistake("this đọc thành “dis”, they đọc thành “dây”", "this /ðɪs/, they /ðeɪ/: đầu lưỡi giữa hai răng, cổ họng rung", "Người Việt thay /ð/ bằng “d” hoặc “đ”. Lưỡi của các bạn đang chạm lợi phía sau răng; hãy đưa nó ra phía trước, chạm vào mép răng."),
      p("Người miền Bắc hay đọc “s” và “x” giống nhau, nên **/ʃ/** (she) dễ bị đọc thành **/s/** (see). Với /ʃ/, môi hơi chu tròn ra trước, lưỡi lùi lại, như khi ra hiệu “suỵt”. Người miền Nam lại hay đọc **/v/** thành âm giống “d” hoặc “gi”, nên very nghe như “ye-ry”. Với /v/, **răng trên phải chạm môi dưới**."),
      ex("She sells sea shells on the seashore.", "Cô ấy bán vỏ sò trên bờ biển.", "Câu luyện lưỡi nổi tiếng: she, shells, shore có /ʃ/ môi chu tròn; sells, sea có /s/ môi dẹt."),
      mistake("very đọc thành “ye-ry”, video đọc thành “dì-đêu”", "very /ˈver.i/, video /ˈvɪd.i.əʊ/: răng trên chạm môi dưới", "Trong giọng miền Nam, chữ “v” thường được đọc gần với “d” hoặc “gi”. Tiếng Anh thì bắt buộc môi dưới chạm răng trên, nếu không very sẽ không còn là very."),
      teacher("Tôi luôn bảo học trò: **hãy để lưỡi ra ngoài khi nói th**, đừng xấu hổ. Người Việt ngại thò lưỡi vì thấy không lịch sự, nhưng trong tiếng Anh đó là điều bắt buộc. Mỗi sáng các bạn đứng trước gương đọc năm lần: **“I think this is the third thing.”** Nhìn thấy đầu lưỡi thì đúng, không thấy thì làm lại."),
    ],
  },
  words: [
    word("think", "/θɪŋk/", "nghĩ", "I think it's a good idea.", "think", 0, "Đầu lưỡi giữa hai răng, thổi hơi; không đọc thành sink hay “tink”."),
    word("this", "/ðɪs/", "này, đây", "This is my friend, Nam.", "this", 0, "Giống /θ/ nhưng cổ họng rung; không đọc thành “dít”."),
    word("very", "/ˈver.i/", "rất", "The food here is very good.", "ver|y", 0, "Răng trên chạm môi dưới cho /v/; đừng đọc thành “ye-ry” hay “be-ry”."),
    word("zoo", "/zuː/", "sở thú", "We took the children to the zoo.", "zoo", 0, "/z/ có rung ở cổ họng như tiếng ong; không đọc thành “du” hay “su”."),
    word("shoe", "/ʃuː/", "chiếc giày", "I can't find my other shoe.", "shoe", 0, "Chu môi tròn như ra hiệu “suỵt” cho /ʃ/; khác với sue /suː/."),
    word("measure", "/ˈmeʒ.ə/", "đo", "Please measure the room.", "meas|ure", 0, "/ʒ/ là bản hữu thanh của /ʃ/: môi chu tròn và cổ họng rung, gần chữ “gi” kéo dài."),
    word("judge", "/dʒʌdʒ/", "thẩm phán; đánh giá", "Don't judge a book by its cover.", "judge", 0, "Có hai âm /dʒ/, đầu và cuối; cuối từ vẫn phải bật nhẹ /dʒ/ ra."),
    word("cheap", "/tʃiːp/", "rẻ", "The bread here is cheap.", "cheap", 0, "/tʃ/ vô thanh, bật hơi mạnh; khác với jeep /dʒiːp/ có rung."),
  ],
  exercises: [
    listen("pa-n04-1", "think", ["sink", "think", "tink"], 1, "Think /θɪŋk/ có đầu lưỡi giữa hai răng, tiếng hơi mềm. Sink bắt đầu bằng /s/ rít, tink bắt đầu bằng /t/ bật."),
    listen("pa-n04-2", "shell", ["shell", "sell", "cell"], 0, "Shell /ʃel/ môi chu tròn, âm dày. Sell và cell đều đọc là /sel/, môi dẹt."),
    mc("pa-n04-3", "Từ nào bắt đầu bằng phụ âm hữu thanh?", ["pig", "cap", "tea", "big"], 3, "Big bắt đầu bằng /b/ hữu thanh (cổ họng rung). Pig /p/, cap /k/, tea /t/ đều là vô thanh."),
    mc("pa-n04-4", "Từ nào có âm /ð/?", ["think", "they", "three", "thank"], 1, "They /ðeɪ/ có /ð/ hữu thanh. Think, three, thank đều bắt đầu bằng /θ/ vô thanh."),
    fill("pa-n04-5", "I ___ it's going to rain. (nghĩ, có âm /θ/)", ["think"], "Think /θɪŋk/: thò đầu lưỡi, thổi hơi. Đọc thành sink là thành “chìm”."),
    fill("pa-n04-6", "___ is my brother, Minh. (Đây là, có âm /ð/)", ["This", "this"], "This /ðɪs/ dùng để giới thiệu người đứng gần. Đầu lưỡi giữa hai răng, cổ họng rung."),
    reorder("pa-n04-7", "They think the shoes are very cheap.", "They think + mệnh đề. Câu có đủ /ð/, /θ/, /ʃ/, /v/ và /tʃ/ để các bạn đọc to."),
    reorder("pa-n04-8", "Is this your van?", "Câu hỏi với to be: Is + this + your + danh từ? Van có /v/: răng trên chạm môi dưới."),
  ],
  speaking: [
    say("I think this is my bag.", "Tôi nghĩ đây là túi của tôi."),
    say("Thank you, that's very kind of you.", "Cảm ơn bạn, bạn thật tốt."),
    say("She sells sea shells on the seashore.", "Cô ấy bán vỏ sò trên bờ biển."),
  ],
});
