import { A, B, correct, dialogue, ex, fill, free, lesson, listen, listenQ, mc, mistake, p, reading, reorder, say, summary, table, task, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "phu-am-huu-thanh-vo-thanh",
  title: "Phụ âm hữu thanh và vô thanh",
  minutes: 30,
  lecture: {
    title: "Các cặp phụ âm và hai âm /θ/, /ð/",
    blocks: [
      p("Trong cuộc họp, một kỹ sư người Việt nói “I sink so” thay cho **I think so** (tôi nghĩ vậy). Đồng nghiệp người Anh mỉm cười, vì sink là chìm. Phụ âm tiếng Anh có nhiều âm không có trong tiếng Việt, và nhiều cặp âm chỉ khác nhau ở **một chi tiết nhỏ**: dây thanh có rung hay không."),
      p("Phụ âm **vô thanh** chỉ có hơi đi ra, dây thanh **không rung**. Phụ âm **hữu thanh** có cùng vị trí môi và lưỡi, nhưng dây thanh **rung**. Vì vậy chúng đi thành từng cặp: miệng đặt y hệt nhau, chỉ khác ở cổ họng. Phần lớn các cặp có **cặp từ tối thiểu**, tức hai từ chỉ khác nhau đúng một âm; riêng /ʃ/–/ʒ/ và /θ/–/ð/ hầu như không có cặp thông dụng, nên tôi cho từ ví dụ."),
      table(
        ["Vô thanh", "Hữu thanh", "Cặp từ tối thiểu hoặc từ ví dụ"],
        ["/p/", "/b/", "pig – big"],
        ["/t/", "/d/", "town – down"],
        ["/k/", "/ɡ/", "coat – goat"],
        ["/f/", "/v/", "fan – van"],
        ["/s/", "/z/", "sip – zip"],
        ["/ʃ/", "/ʒ/", "shoe (có /ʃ/), measure (có /ʒ/)"],
        ["/tʃ/", "/dʒ/", "cheap – jeep"],
        ["/θ/", "/ð/", "think (có /θ/), this (có /ð/)"],
      ),
      tip("**Phép thử cổ họng**: đặt hai ngón tay lên cổ, kéo dài “ssss” rồi chuyển sang “zzzz”. Với /s/ cổ họng im lặng, với /z/ các bạn sẽ thấy **rung** dưới ngón tay. Làm tương tự với /f/ và /v/. Đây là cách tự kiểm tra đơn giản nhất mà không cần ai bên cạnh."),
      p("Hai âm **/θ/** (think) và **/ð/** (this) không có trong tiếng Việt. Đặt **đầu lưỡi giữa hai hàm răng**, hơi thò ra ngoài một chút, rồi thổi hơi qua khe giữa lưỡi và răng trên. Với /θ/ chỉ có hơi; với /ð/ thêm tiếng rung ở cổ họng. Chữ “th” tiếng Việt là âm khác hẳn, đừng dùng nó thay thế."),
      ex("I think this is my bag.", "Tôi nghĩ đây là túi của tôi.", "Think bắt đầu bằng /θ/ (chỉ có hơi), this bắt đầu bằng /ð/ (có rung). Cả hai đều phải thò đầu lưỡi."),
      ex("Thank you, that's very kind of you.", "Cảm ơn bạn, bạn thật tốt.", "Thank có /θ/, that có /ð/, very có /v/: môi dưới chạm răng trên."),
      mistake("think đọc thành sink /sɪŋk/ hoặc “tink”", "think /θɪŋk/: đầu lưỡi giữa hai răng, thổi hơi", "Tiếng Việt không có /θ/, nên người Việt thay bằng âm gần nhất là “x” hoặc “t”. Nhưng sink là chìm, còn thin (gầy) sẽ thành sin (tội lỗi) hay tin (hộp thiếc)."),
      mistake("this đọc thành “dít”, they đọc thành “đây”", "this /ðɪs/, they /ðeɪ/: đầu lưỡi giữa hai răng, cổ họng rung", "Người Việt thay /ð/ bằng “d” hoặc “đ”, vì lưỡi đang chạm lợi phía sau răng. Hãy đưa đầu lưỡi ra phía trước, chạm vào mép răng trên, rồi mới cho hơi và tiếng rung đi ra."),
      p("Người miền Bắc thường đọc “s” và “x” giống nhau, nên **/ʃ/** (she) dễ bị đọc thành **/s/** (see). Với /ʃ/, môi hơi chu tròn ra trước, lưỡi lùi lại, như khi ra hiệu “suỵt”. Người miền Nam lại hay đọc chữ “v” gần như “d” hoặc “gi”, nên very nghe như “ye-ry”. Với **/v/**, **răng trên phải chạm môi dưới** và cổ họng rung."),
      ex("She sells sea shells on the seashore.", "Cô ấy bán vỏ sò trên bờ biển.", "Câu luyện lưỡi nổi tiếng: she, shells, shore có /ʃ/ môi chu tròn; sells, sea có /s/ môi dẹt."),
      mistake("very đọc thành “ye-ry”, video đọc thành “dì-đêu”", "very /ˈver.i/, video /ˈvɪd.i.əʊ/: răng trên chạm môi dưới", "Trong giọng miền Nam, chữ “v” thường được đọc gần với “d” hoặc “gi”. Tiếng Anh thì bắt buộc môi dưới chạm răng trên, nếu không very sẽ không còn là very."),
      teacher("Tôi luôn bảo học trò: **hãy để lưỡi ra ngoài khi nói th**, đừng xấu hổ. Người Việt ngại thò lưỡi vì thấy không lịch sự, nhưng trong tiếng Anh đó là điều bắt buộc. Mỗi sáng các bạn đứng trước gương đọc năm lần: **“I think this is the third thing.”** Nhìn thấy đầu lưỡi thì đúng, không thấy thì làm lại."),
      summary(
        "Cặp vô thanh và hữu thanh đặt miệng giống nhau, chỉ khác **dây thanh có rung** hay không.",
        "Phép thử: đặt tay lên cổ, /s/ im lặng, /z/ rung.",
        "/θ/ và /ð/: **đầu lưỡi giữa hai hàm răng**. Think không phải sink, this không phải “dít”.",
        "/ʃ/ môi chu tròn (she), /s/ môi dẹt (see).",
        "/v/: răng trên chạm môi dưới, cổ rung. Đừng đọc very thành “ye-ry” hay “be-ry”.",
      ),
    ],
  },
  words: [
    word("think", "/θɪŋk/", "nghĩ", "I think it's a good idea.", "think", 0, "Đầu lưỡi giữa hai răng, thổi hơi; không đọc thành sink hay “tink”."),
    word("this", "/ðɪs/", "này, đây", "This is my friend, Nam.", "this", 0, "Giống /θ/ nhưng cổ họng rung; không đọc thành “dít”."),
    word("very", "/ˈver.i/", "rất", "The food here is very good.", "ver|y", 0, "Răng trên chạm môi dưới cho /v/; đừng đọc thành “ye-ry” hay “be-ry”."),
    word("zoo", "/zuː/", "sở thú", "The children love the zoo.", "zoo", 0, "/z/ có rung ở cổ họng như tiếng ong; không đọc thành “du” hay “su”."),
    word("shoe", "/ʃuː/", "chiếc giày", "I can't find my other shoe.", "shoe", 0, "Chu môi tròn như ra hiệu “suỵt” cho /ʃ/; khác với sue /suː/."),
    word("measure", "/ˈmeʒ.ə/", "đo", "Please measure the room.", "meas|ure", 0, "/ʒ/ là bản hữu thanh của /ʃ/: đặt lưỡi và chu môi y như khi nói /ʃ/ (“suỵt”), rồi cho cổ họng rung. Đừng đọc thành “gi” hay “d” tiếng Việt."),
    word("judge", "/dʒʌdʒ/", "thẩm phán; đánh giá", "Don't judge a book by its cover.", "judge", 0, "Có hai âm /dʒ/, đầu và cuối; cuối từ vẫn phải bật nhẹ /dʒ/ ra."),
    word("cheap", "/tʃiːp/", "rẻ", "The bread here is cheap.", "cheap", 0, "/tʃ/ vô thanh, bật hơi mạnh; khác với jeep /dʒiːp/ có rung."),
  ],
  dialogue: dialogue(
    "Mua giày ở chợ",
    "Anh Tom, một giáo viên người Anh, đi mua giày ở chợ Bến Thành. Chị Thảo bán hàng giúp anh chọn một đôi vừa chân.",
    { A: "Anh Tom (khách)", B: "Chị Thảo (người bán)" },
    B("Hello. These shoes are very nice. Do you like them?", "Chào anh. Đôi giày này đẹp lắm. Anh có thích không?"),
    A("I think so. Are they leather?", "Tôi nghĩ là có. Chúng bằng da phải không?"),
    B("Yes, they are. What size are you?", "Vâng, đúng rồi. Anh đi cỡ bao nhiêu?"),
    A("I think I'm a forty-three.", "Tôi nghĩ tôi đi cỡ bốn mươi ba."),
    B("Here are the forty-threes. Try them on.", "Đây là cỡ bốn mươi ba. Anh đi thử đi."),
    A("Thanks. They're a bit tight. Do you have a size forty-four?", "Cảm ơn chị. Hơi chật một chút. Chị có cỡ bốn mươi bốn không?"),
    B("Yes. These are a forty-four.", "Có ạ. Đôi này cỡ bốn mươi bốn."),
    A("These are perfect. How much are they?", "Đôi này vừa khít. Bao nhiêu tiền vậy chị?"),
    B("Seven hundred thousand dong. That's very cheap!", "Bảy trăm nghìn đồng. Thế là rẻ lắm đấy!"),
    A("Is six hundred thousand OK?", "Sáu trăm nghìn được không chị?"),
    B("Six hundred and fifty. That's my best price.", "Sáu trăm năm mươi. Đó là giá tốt nhất rồi."),
    A("OK. Thank you very much.", "Được. Cảm ơn chị nhiều."),
  ),
  dialogueQuestions: [
    mc("pa-n04-d1", "Cuối cùng anh Tom đi vừa đôi giày cỡ bao nhiêu?", ["Bốn mươi ba", "Bốn mươi bốn", "Bốn mươi hai"], 1, "Cỡ bốn mươi ba hơi chật (a bit tight), cỡ bốn mươi bốn thì vừa (These are perfect)."),
    listenQ("pa-n04-d2", "Cuối cùng anh Tom trả bao nhiêu tiền?", "Six hundred and fifty. That's my best price.", ["Sáu trăm nghìn đồng", "Bảy trăm nghìn đồng", "Sáu trăm năm mươi nghìn đồng"], 2, "Chị Thảo chốt giá “six hundred and fifty” (thousand dong) và anh Tom đồng ý."),
    mc("pa-n04-d3", "Đôi giày làm bằng gì?", ["Da", "Vải", "Nhựa"], 0, "Anh Tom hỏi “Are they leather?” và chị Thảo trả lời “Yes, they are.”"),
  ],
  reading: reading({
    title: "Cửa hàng giày của chị Thu",
    text: `Thu's Shoe Shop is near the city zoo. We sell shoes for men, women and children. Our shoes are leather, and they are very cheap.

This Thursday and Friday, all sandals are three hundred thousand dong. Buy two pairs and get a free pair of socks.

Do you think your shoes are too old? Bring them to us. We can clean and fix them in thirty minutes.

We open from seven in the morning to nine in the evening, every day. Come in and say hello!`,
    glossary: [["sandals", "dép quai hậu, xăng-đan"], ["pair", "đôi"], ["socks", "tất"], ["fix", "sửa"]],
    questions: [
      mc("pa-n04-r1", "Cửa hàng này bán gì?", ["Quần áo trẻ em", "Giày dép", "Đồ chơi"], 1, "“We sell shoes for men, women and children.”"),
      mc("pa-n04-r2", "Xăng-đan có giá ba trăm nghìn đồng vào những ngày nào?", ["Thứ Năm và thứ Sáu", "Thứ Bảy và Chủ nhật", "Mọi ngày trong tuần"], 0, "“This Thursday and Friday, all sandals are three hundred thousand dong.” Thursday bắt đầu bằng /θ/."),
      fill("pa-n04-r3", "We can clean and fix your old shoes in ___ minutes. (số phút)", ["thirty", "30"], "“We can clean and fix them in thirty minutes.” Thirty bắt đầu bằng /θ/."),
      mc("pa-n04-r4", "Mua hai đôi xăng-đan thì được tặng gì?", ["Một đôi giày da", "Một cái túi", "Một đôi tất"], 2, "“Buy two pairs and get a free pair of socks.”"),
      mc("pa-n04-r5", "Cửa hàng mở cửa khi nào?", ["Từ chín giờ sáng đến bảy giờ tối, trừ Chủ nhật", "Từ bảy giờ sáng đến chín giờ tối, ngày nào cũng mở", "Chỉ vào thứ Năm và thứ Sáu"], 1, "“We open from seven in the morning to nine in the evening, every day.”"),
    ],
  }),
  exercises: [
    listen("pa-n04-1", "think", ["sink", "think", "tink"], 1, "Think /θɪŋk/ có đầu lưỡi giữa hai răng, tiếng hơi mềm. Sink bắt đầu bằng /s/ rít, tink bắt đầu bằng /t/ bật."),
    listen("pa-n04-2", "shell", ["sell", "fell", "shell"], 2, "Shell /ʃel/ môi chu tròn, âm dày. Sell /sel/ môi dẹt, tiếng rít mảnh; fell /fel/ răng trên chạm môi dưới."),
    mc("pa-n04-3", "Từ nào bắt đầu bằng phụ âm hữu thanh?", ["pig", "cap", "tea", "big"], 3, "Big bắt đầu bằng /b/ hữu thanh (cổ họng rung). Pig /p/, cap /k/, tea /t/ đều là vô thanh."),
    mc("pa-n04-4", "Từ nào có âm /ð/?", ["think", "they", "three", "thank"], 1, "They /ðeɪ/ có /ð/ hữu thanh. Think, three, thank đều bắt đầu bằng /θ/ vô thanh."),
    fill("pa-n04-5", "I ___ this bag is very cheap. (nghĩ, có âm /θ/)", ["think"], "Think /θɪŋk/: thò đầu lưỡi, thổi hơi. Đọc thành sink là thành “chìm”."),
    fill("pa-n04-6", "___ is my brother, Minh. (Đây là, có âm /ð/)", ["This", "this"], "This /ðɪs/ dùng để giới thiệu người đứng gần. Đầu lưỡi giữa hai răng, cổ họng rung."),
    reorder("pa-n04-7", "They think the shoes are very cheap.", "They think + mệnh đề. Câu có đủ /ð/, /θ/, /ʃ/, /v/ và /tʃ/ để các bạn đọc to."),
    reorder("pa-n04-8", "My brother drives a very big van.", "Chủ ngữ + drives + a + very + tính từ + danh từ. Very và van có /v/: răng trên chạm môi dưới; brother có /ð/."),
    correct("pa-n04-9", "She think the shoes are cheap.", "She thinks the shoes are cheap.", "Chủ ngữ she nên động từ thêm -s: thinks /θɪŋks/. Đầu từ là /θ/ (thò lưỡi), cuối từ có cụm /ŋks/, đừng nuốt."),
    correct("pa-n04-10", "These shoe are very cheap.", ["These shoes are very cheap.", "This shoe is very cheap."], "These đi với danh từ số nhiều: these shoes, đọc /ʃuːz/ với /z/ rung ở cuối. Nếu muốn nói một chiếc thì dùng this shoe is."),
  ],
  speaking: [
    say("I think this is my bag.", "Tôi nghĩ đây là túi của tôi."),
    say("Thank you, that's very kind of you.", "Cảm ơn bạn, bạn thật tốt."),
    say("She sells sea shells on the seashore.", "Cô ấy bán vỏ sò trên bờ biển."),
  ],
  freeSpeaking: free(
    "What do you think of the shops near your home?",
    "Nói 3–4 câu về một cửa hàng gần nhà bạn: nó bán gì, giá thế nào, bạn nghĩ gì về nó. Dùng think, this, these, very, shoes, shop.",
    "There is a very nice shop near my home. It sells shoes and clothes. I think the prices there are cheap. These shoes on my feet are from that shop.",
  ),
  task: task({
    prompt: "Viết 5 câu giới thiệu một cửa hàng gần nhà bạn (bán gì, giá thế nào, bạn và người thân nghĩ gì về nó), dùng nhiều từ có /θ/, /ð/, /v/, /ʃ/ và /z/. Rồi đứng trước gương đọc to từng câu, một tay đặt lên cổ để kiểm tra độ rung.",
    hints: [
      "Từ có /θ/: think, three, thank, Thursday; từ có /ð/: this, these, there, brother, mother.",
      "Từ có /v/: very, five, seven; từ có /ʃ/: shop, shoes, shirt.",
      "Có thể bắt đầu bằng: There is a small shop near my house. It sells…",
    ],
    model: "There is a small shop near my house. It sells shoes and shirts. The shoes there are very cheap. My brother thinks the shirts are nice. On Thursdays my mother and I go there together.",
    checklist: [
      "Có ít nhất hai từ có /θ/ (thinks, Thursdays) và hai từ có /ð/ (there, brother, mother)",
      "Nhìn gương thấy đầu lưỡi giữa hai răng mỗi khi đọc th",
      "Very: răng trên chạm môi dưới cho /v/, không đọc thành “ye-ry”",
      "Shop, shoes, shirts: môi chu tròn cho /ʃ/, nghe khác see, sip",
      "Tay đặt lên cổ thấy rung ở /z/ cuối shoes, sells và ở /ð/ trong there, brother",
    ],
    minWords: 25,
  }),
});
