import { A, B, dialogue, ex, fill, lesson, listen, mc, mistake, p, reorder, say, summary, table, task, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "bao-nhieu",
  title: "Bao nhiêu là đủ?",
  minutes: 20,
  lecture: {
    title: "Much, many, a lot of, a few, a little",
    blocks: [
      p("Bạn đi chợ chuẩn bị cơm khách, người bạn nước ngoài hỏi: “Cần mua bao nhiêu trứng, bao nhiêu đường?”. Tiếng Việt chỉ có một chữ **“bao nhiêu”** và một chữ **“nhiều”**, dùng cho mọi thứ. Tiếng Anh thì phải hỏi trước một câu: thứ này **đếm được** hay **không đếm được**?"),
      p("Nhắc lại từ A1: danh từ **đếm được** đếm từng cái và có số nhiều (an egg, two eggs). Danh từ **không đếm được** không có a/an, không thêm -s (water, rice, sugar). Bài này dạy bạn nói về **số lượng** của cả hai nhóm."),
      table(
        ["Ý nghĩa", "Đếm được (số nhiều)", "Không đếm được"],
        ["Hỏi bao nhiêu", "How many eggs?", "How much sugar?"],
        ["Nhiều (câu hỏi, phủ định)", "many", "much"],
        ["Nhiều (câu khẳng định)", "a lot of / lots of", "a lot of / lots of"],
        ["Một vài, một chút", "a few", "a little"],
      ),
      ex("How many eggs do we need for the cake?", "Làm bánh cần bao nhiêu quả trứng?"),
      ex("How much sugar do you want in your coffee?", "Bạn muốn cho bao nhiêu đường vào cà phê?", "How much còn dùng để hỏi giá (How much is it?). Nếu sau How much có danh từ như sugar, money, time thì đó là hỏi số lượng."),
      p("**Much** và **many** chủ yếu dùng trong **câu hỏi** và **câu phủ định**. Trong **câu khẳng định**, người bản xứ gần như luôn nói **a lot of** hoặc **lots of** (thân mật hơn), dùng được cho cả hai nhóm danh từ."),
      ex("We don't have much time. The bus leaves at eight.", "Chúng ta không có nhiều thời gian đâu. Xe buýt chạy lúc tám giờ."),
      ex("There are a lot of people at the market today.", "Hôm nay chợ đông người lắm."),
      p("**A few** (một vài) đi với danh từ đếm được số nhiều, **a little** (một chút, một ít) đi với danh từ không đếm được. Cả hai mang nghĩa tích cực: ít thôi nhưng **vẫn có**."),
      ex("I have a few friends in Hanoi.", "Tôi có vài người bạn ở Hà Nội."),
      ex("Can I have a little milk in my tea, please?", "Cho tôi một chút sữa vào trà được không?"),
      tip("Mẹo nhớ: **few** đi với thứ **đếm được** (few friends), **little** đi với thứ **đổ được, rắc được** (little milk, little salt). Bỏ chữ **a** đi thì nghĩa thành tiêu cực: **few** friends là “rất ít bạn, gần như không có ai”, nghe rất buồn. Ở A2, bạn cứ dùng **a few** và **a little** cho an toàn."),
      mistake("How many money do you have?", "How much money do you have?", "Tiếng Việt đếm được “một đồng, hai đồng” nên người Việt tưởng money đếm được. Trong tiếng Anh, money không đếm được, ta đếm bằng dollars, dong."),
      mistake("I have many homeworks today.", "I have a lot of homework today.", "Homework không đếm được nên không thêm -s. Câu khẳng định lại dùng a lot of tự nhiên hơn many."),
      mistake("There are a lot people here.", "There are a lot of people here.", "Người Việt hay nuốt mất of vì nói nhanh. A lot of là một cụm, không bỏ of được."),
      teacher("Học viên của tôi hay hỏi: “Sao câu khẳng định dùng much lại nghe sai?”. Không hẳn sai, nhưng nghe cứng và trang trọng như văn viết, người ta hầu như không nói vậy. Tôi dặn các bạn một quy tắc sống: **khẳng định thì a lot of, hỏi và phủ định thì much/many**. Mỗi lần đi chợ, các bạn hãy tự hỏi thầm bằng tiếng Anh từng món: How many tomatoes? How much rice? Chỉ cần một tháng như vậy, phản xạ đếm được hay không đếm được sẽ thành tự nhiên."),
      summary(
        "Trước khi nói số lượng, tự hỏi: danh từ này đếm được hay không đếm được?",
        "How many + danh từ đếm được số nhiều; How much + danh từ không đếm được.",
        "Câu hỏi và phủ định dùng much / many; câu khẳng định dùng a lot of, không bỏ of.",
        "A few + danh từ đếm được số nhiều, a little + danh từ không đếm được: ít nhưng vẫn có.",
        "Money, homework, information, furniture không đếm được: không thêm -s, không dùng many.",
      ),
    ],
  },
  words: [
    word("money", "/ˈmʌn.i/", "tiền", "I don't have much money this month.", "mon|ey", 0, "Đọc là /ˈmʌn.i/, chữ o đọc gần như “â”: “mân-ni”, không đọc là “mô-ney”."),
    word("sugar", "/ˈʃʊɡ.ər/", "đường (ăn)", "How much sugar do you take?", "sug|ar", 0, "Chữ s ở đầu đọc là /ʃ/ như “sờ” uốn lưỡi, không đọc là /s/."),
    word("salt", "/sɒlt/", "muối", "Add a little salt to the soup.", "salt", 0, "Nhớ âm /l/ và /t/ ở cuối, đừng đọc thành “xon”."),
    word("information", "/ˌɪn.fəˈmeɪ.ʃən/", "thông tin", "I need some information about the trip.", "in|for|ma|tion", 2, "Information không đếm được: không nói an information hay informations. Trọng âm ở âm thứ ba: in-phơ-MÂY-sần."),
    word("traffic", "/ˈtræf.ɪk/", "giao thông, xe cộ", "There's a lot of traffic in the morning.", "traf|fic", 0),
    word("homework", "/ˈhəʊm.wɜːk/", "bài tập về nhà", "We don't have much homework today.", "home|work", 0),
    word("furniture", "/ˈfɜː.nɪ.tʃər/", "đồ đạc trong nhà", "There isn't much furniture in the room.", "fur|ni|ture", 0, "Furniture không đếm được: không nói furnitures. Một món đồ là a piece of furniture."),
    word("kilo", "/ˈkiː.ləʊ/", "cân, ki-lô-gam", "I'd like two kilos of oranges, please.", "ki|lo", 0),
  ],
  exercises: [
    mc("a2-n10-1", "How ___ eggs do we need?", ["much", "many", "a lot"], 1, "Eggs là danh từ đếm được số nhiều nên dùng How many."),
    mc("a2-n10-2", "There isn't ___ traffic on the road today.", ["many", "a few", "much"], 2, "Traffic không đếm được, câu phủ định nên dùng much."),
    fill("a2-n10-3", "How ___ money do you need for the trip?", ["much"], "Money không đếm được nên hỏi How much."),
    fill("a2-n10-4", "Can I have a ___ milk in my coffee, please?", ["little"], "Milk không đếm được nên dùng a little (một chút)."),
    reorder("a2-n10-5", "How much sugar do you want?", "How much + danh từ không đếm được + do you + động từ?"),
    reorder("a2-n10-6", "My sister has a lot of friends.", "Câu khẳng định dùng a lot of, không bỏ of."),
    listen("a2-n10-7", "We only have a few eggs left.", ["Chúng ta còn rất nhiều trứng.", "Chúng ta chỉ còn vài quả trứng.", "Chúng ta không còn quả trứng nào."], 1, "A few là một vài: vẫn còn, nhưng ít."),
    listen("a2-n10-8", "How much luggage do you have?", ["Bạn có bao nhiêu hành lý?", "Hành lý của bạn giá bao nhiêu?", "Hành lý của bạn ở đâu?"], 0, "Sau How much là danh từ luggage nên đây là hỏi số lượng, không phải hỏi giá."),
  ],
  speaking: [
    say("How many people are coming to the party?", "Có bao nhiêu người đến dự tiệc?"),
    say("We don't have much time, so let's hurry.", "Chúng ta không có nhiều thời gian đâu, nhanh lên nào."),
    say("Can I have a little sugar, please?", "Cho tôi xin một chút đường nhé."),
  ],
  dialogue: dialogue(
    "Đi chợ nấu tiệc",
    "Tối nay Mai và Anna, bạn người Đức ở cùng nhà, mời mười người bạn đến ăn. Hai người đi chợ và bàn xem cần mua bao nhiêu thứ.",
    { A: "Mai, người Việt", B: "Anna, bạn cùng nhà người Đức" },
    A("We're cooking for ten people tonight. How many eggs do we need?", "Tối nay mình nấu cho mười người. Cần bao nhiêu quả trứng nhỉ?"),
    B("About twenty. We only have a few eggs at home.", "Khoảng hai mươi quả. Ở nhà chỉ còn vài quả thôi."),
    A("OK. And how much rice do we have?", "Được. Còn gạo thì nhà mình còn bao nhiêu?"),
    B("Not much. Let's buy two kilos.", "Không nhiều đâu. Mình mua hai cân nhé."),
    A("Do we need any sugar?", "Mình có cần đường không?"),
    B("Just a little, for the sauce. We have a lot of salt at home.", "Chỉ một chút thôi, để làm nước sốt. Ở nhà còn nhiều muối rồi."),
    A("What about vegetables?", "Còn rau thì sao?"),
    B("Let's get a lot of vegetables. My friends love Vietnamese salad.", "Mua nhiều rau vào nhé. Bạn mình rất thích gỏi Việt Nam."),
    A("How much money do you have? I don't have much with me.", "Bạn mang bao nhiêu tiền? Mình không mang nhiều."),
    B("I have five hundred thousand dong. Don't worry.", "Mình có năm trăm nghìn đồng. Đừng lo."),
    A("Great. Oh, there are a lot of people at the market today!", "Tuyệt. Ôi, hôm nay chợ đông người quá!"),
    B("Yes. Let's be quick. We don't have much time.", "Ừ. Nhanh lên nào. Mình không có nhiều thời gian đâu."),
  ),
  task: task({
    prompt: "Cuối tuần bạn mời bạn bè đến nhà ăn tối. Viết tin nhắn 5–6 câu cho người bạn cùng nhà: nhà còn gì, cần mua gì, mua bao nhiêu.",
    hints: [
      "Hỏi về số lượng với How many (đếm được) hoặc How much (không đếm được).",
      "Nhà còn ít: a few + danh từ đếm được, a little + danh từ không đếm được.",
      "Câu khẳng định dùng a lot of, câu phủ định dùng much hoặc many.",
      "Nói số cân bằng kilo: two kilos of chicken.",
    ],
    model: "Hi Tom, six friends are coming for dinner on Saturday. We only have a few eggs, so please buy ten more. We have a lot of rice, but we don't have many tomatoes. There's only a little salt, and we don't have much sugar. We need two kilos of chicken and a lot of vegetables. How much money do you need? I'll give it to you tonight.",
    checklist: [
      "Dùng many với danh từ đếm được, much với danh từ không đếm được.",
      "Câu khẳng định dùng a lot of, không bỏ of.",
      "Có ít nhất 1 câu với a few và 1 câu với a little.",
      "Không thêm -s cho danh từ không đếm được (rice, sugar, money).",
      "Có ít nhất 1 câu hỏi How much hoặc How many.",
    ],
    minWords: 30,
  }),
});
