import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "cua-ai",
  title: "Cái này của ai?",
  minutes: 22,
  lecture: {
    title: "Đại từ tân ngữ, đại từ sở hữu, whose và 's",
    blocks: [
      p("Cuối buổi họp, trên bàn còn một cái ô và một chùm chìa khóa. Bạn muốn hỏi “Cái này của ai?” và trả lời “Của tôi” hay “Của chị Lan”. Tiếng Việt chỉ cần chữ **“tôi”** và chữ **“của”** cho mọi vị trí. Tiếng Anh thì đổi hình thức theo **vị trí trong câu**, và đó là lý do người Việt hay lẫn."),
      table(
        ["Chủ ngữ", "Tân ngữ", "Tính từ sở hữu", "Đại từ sở hữu"],
        ["I", "me", "my", "mine"],
        ["you", "you", "your", "yours"],
        ["he", "him", "his", "his"],
        ["she", "her", "her", "hers"],
        ["it", "it", "its", "(ít dùng)"],
        ["we", "us", "our", "ours"],
        ["they", "them", "their", "theirs"],
      ),
      p("**Đại từ tân ngữ** (me, him, her, us, them) đứng **sau động từ** hoặc **sau giới từ** như with, for, to. Nói gọn: người làm hành động dùng I, người **nhận** hành động dùng me."),
      ex("My grandmother lives alone, so I call her every evening.", "Bà tôi sống một mình nên tối nào tôi cũng gọi điện cho bà."),
      ex("Can you come with us?", "Bạn đi cùng chúng tôi được không?"),
      p("**Đại từ sở hữu** (mine, yours, hers, ours, theirs) thay cho cả cụm **tính từ sở hữu + danh từ**, để khỏi lặp lại danh từ. My umbrella → **mine**. Sau đại từ sở hữu **không có danh từ** nữa."),
      ex("This isn't my umbrella. Mine is black.", "Đây không phải ô của tôi. Ô của tôi màu đen."),
      p("Muốn hỏi **của ai**, dùng **Whose + danh từ + is this / are these?** hoặc gọn hơn **Whose is this?** Trả lời bằng tên người + **'s**: **It's Lan's.** Với danh từ số nhiều đã có -s, chỉ thêm dấu **'**: my parents' house."),
      ex("Whose keys are these? They're Nam's.", "Chùm chìa khóa này của ai? Của Nam đấy."),
      ex("This is my parents' house.", "Đây là nhà của bố mẹ tôi.", "Parents đã có -s nên chỉ thêm dấu nháy: parents'. Khi đọc, parents' và parents nghe giống hệt nhau."),
      tip("**Whose** (của ai) và **who's** (= who is, ai là) đọc giống hệt nhau: /huːz/. Khi viết, hãy tự hỏi: thay bằng “who is” được không? Được thì viết who's, không được thì viết whose. Và nhớ: **hers, yours, ours, theirs** không bao giờ có dấu '."),
      mistake("Can you help I?", "Can you help me?", "Tiếng Việt dùng “tôi” cả khi làm chủ ngữ lẫn khi đứng sau động từ. Tiếng Anh thì sau động từ phải đổi sang tân ngữ: me."),
      mistake("This book is my.", "This book is mine.", "My luôn cần danh từ theo sau (my book). Đứng một mình ở cuối câu thì dùng mine."),
      mistake("the car of my father", "my father's car", "Người Việt dịch từng chữ “xe của bố tôi”. Với người, tiếng Anh dùng 's và đặt người sở hữu lên trước: my father's car."),
      mistake("Is this bag her's?", "Is this bag hers?", "Đại từ sở hữu không có dấu ': hers, yours, ours, theirs. Chỉ tên người và danh từ mới dùng 's."),
      teacher("Có một bài tập tôi cho học viên làm suốt mấy chục năm và chưa lần nào thất bại: cầm một đồ vật trong nhà lên, hỏi to **Whose is this?**, rồi tự trả lời **It's mine.**, **It's my mum's.**, **It's theirs.** Làm với mười đồ vật mỗi tối. Miệng quen rồi thì các bạn sẽ không bao giờ nói “This is my” hay “help I” nữa. Ngữ pháp này phải thuộc bằng miệng, không phải bằng mắt."),
    ],
  },
  words: [
    word("whose", "/huːz/", "của ai", "Whose phone is this?", "whose", 0, "Chữ w không đọc, âm cuối là /z/: “hu-z”."),
    word("mine", "/maɪn/", "của tôi", "That bag isn't mine.", "mine", 0, "Nhớ âm /n/ ở cuối, đừng đọc thành “mai”."),
    word("key", "/kiː/", "chìa khóa", "I can't find my keys.", "key", 0, "Đọc là /kiː/ như “ki” kéo dài, chữ e và y không đọc riêng."),
    word("wallet", "/ˈwɒl.ɪt/", "ví (đựng tiền)", "Is this your wallet?", "wal|let", 0),
    word("belong", "/bɪˈlɒŋ/", "thuộc về", "This umbrella belongs to my teacher.", "be|long", 1, "Belong luôn đi với to: belong to somebody."),
    word("borrow", "/ˈbɒr.əʊ/", "mượn", "Can I borrow your pen?", "bor|row", 0),
    word("lend", "/lend/", "cho mượn", "Can you lend me your bike?", "lend", 0, "Borrow là mình mượn của người khác, lend là mình cho người khác mượn."),
    word("own", "/əʊn/", "của riêng; sở hữu", "She has her own room.", "own", 0, "Đọc là /əʊn/, chữ w không đọc thành âm riêng."),
  ],
  exercises: [
    mc("a2-n12-1", "___ bag is this? It's Hoa's.", ["Who's", "Who", "Whose"], 2, "Hỏi của ai dùng whose. Who's là who is, nghĩa khác hẳn."),
    mc("a2-n12-2", "This isn't my pen. ___ is blue.", ["My", "Mine", "Me", "I"], 1, "Mine thay cho my pen; sau mine không có danh từ."),
    fill("a2-n12-3", "My brother lives in Da Nang. I often visit ___ at the weekend. (anh ấy)", ["him"], "Sau động từ visit, he đổi thành tân ngữ him."),
    fill("a2-n12-4", "This is my ___ car. (father)", ["father's"], "Với người sở hữu, thêm 's: my father's car."),
    reorder("a2-n12-5", "Whose bag is on the chair?", "Whose + danh từ + động từ: Whose bag is...? Whose đứng ngay trước danh từ cần hỏi."),
    reorder("a2-n12-6", "Can you lend me your pen?", "Lend + người (tân ngữ me) + vật: lend me your pen."),
    listen("a2-n12-7", "Is this wallet yours?", ["Đây có phải ví của bạn không?", "Đây có phải ví của anh ấy không?", "Bạn có ví không?"], 0, "Yours là của bạn."),
    listen("a2-n12-8", "Those glasses are hers, not his.", ["Cặp kính đó là của anh ấy, không phải của cô ấy.", "Cặp kính đó là của cô ấy, không phải của anh ấy.", "Cặp kính đó là của họ."], 1, "Hers là của cô ấy, his là của anh ấy."),
  ],
  speaking: [
    say("Excuse me, whose phone is this?", "Xin lỗi, điện thoại này của ai vậy?"),
    say("It isn't mine. I think it's my sister's.", "Không phải của tôi. Tôi nghĩ là của chị tôi."),
    say("Can you help me with this bag, please?", "Bạn giúp tôi mang cái túi này được không?"),
  ],
});
