import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "du-doan-tuong-lai",
  title: "Dự đoán tương lai",
  minutes: 20,
  lecture: {
    title: "Will, won't và might để dự đoán",
    blocks: [
      p("Ở bài Kế hoạch cuối tuần, bạn dùng **be going to** cho những dự định đã tính sẵn. Nhưng hằng ngày ta còn hay **đoán**: “Chắc chiều nay mưa”, “Đội tuyển mình sẽ thắng”, “Giá nhà sẽ không giảm đâu”. Để nói điều mình nghĩ sẽ xảy ra, tiếng Anh dùng **will / won't + động từ nguyên mẫu**."),
      table(
        ["Thể", "Cấu trúc", "Ví dụ"],
        ["Khẳng định", "chủ ngữ + will ('ll) + V", "It'll be sunny tomorrow."],
        ["Phủ định", "chủ ngữ + won't + V", "Prices won't go down."],
        ["Nghi vấn", "Will + chủ ngữ + V?", "Will she pass the exam?"],
        ["Trả lời ngắn", "Yes, she will. / No, she won't.", "No, she won't. She didn't study."],
      ),
      p("Khi đoán, ta ít khi chắc chắn một trăm phần trăm. Tiếng Anh có sẵn các “nấc” để nói mình chắc đến đâu. **Might + V** nghĩa là có thể, khoảng năm mươi phần trăm."),
      table(
        ["Mức độ chắc chắn", "Ví dụ", "Nghĩa"],
        ["gần như chắc chắn", "She'll definitely pass.", "Chắc chắn cô ấy sẽ đỗ."],
        ["khá chắc", "She'll probably pass.", "Có lẽ cô ấy sẽ đỗ."],
        ["nửa nọ nửa kia", "She might pass.", "Cô ấy có thể đỗ."],
        ["khá chắc là không", "She probably won't pass.", "Có lẽ cô ấy sẽ không đỗ."],
        ["gần như chắc chắn không", "She definitely won't pass.", "Chắc chắn cô ấy sẽ không đỗ."],
      ),
      p("Để ý vị trí: **probably / definitely đứng sau will**, nhưng **đứng trước won't**. Muốn nói nhẹ nhàng, người bản xứ rất hay mở đầu bằng **I think...** hoặc **I don't think...**"),
      ex("I think it'll rain this afternoon.", "Tôi nghĩ chiều nay trời sẽ mưa."),
      ex("I don't think he'll come.", "Tôi nghĩ anh ấy sẽ không đến.", "Tiếng Việt nói “tôi nghĩ… sẽ không”, nhưng tiếng Anh tự nhiên hơn khi phủ định ở think: I don't think... will."),
      ex("Don't worry. You'll definitely find a good job.", "Đừng lo. Chắc chắn bạn sẽ tìm được việc tốt."),
      ex("I might be late tonight. The traffic is terrible.", "Tối nay tôi có thể về muộn. Đường tắc kinh khủng.", "Might đi thẳng với động từ nguyên mẫu, không có to và không thêm s: she might be, không phải she mights be."),
      ex("Will people live on Mars one day?", "Liệu một ngày nào đó con người có sống trên sao Hỏa không?"),
      tip("**Won't** đọc là /wəʊnt/, nghe như “uơn-t”, miệng tròn và kéo dài. **Want** đọc là /wɒnt/, âm ngắn. Đọc lẫn hai từ này thì người nghe tưởng bạn nói want (muốn) chứ không phải won't (sẽ không), nghĩa ngược hẳn. Nhớ bật âm /t/ ở cuối won't."),
      mistake("He won't probably come.", "He probably won't come.", "Probably đứng sau will (he'll probably come) nhưng đứng trước won't. Học trò hay đặt theo kiểu tiếng Việt “sẽ không có lẽ”, nghe rất lạ."),
      mistake("It will maybe rain tomorrow.", "It might rain tomorrow.", "Dịch từng chữ “trời sẽ có lẽ mưa” sẽ ra câu sai. Maybe thường đứng đầu câu (Maybe it'll rain), còn gọn nhất là dùng might."),
      mistake("It might to rain tonight.", "It might rain tonight.", "Quen nói want to, need to, học trò hay thêm to sau might. Might cũng như will, should: theo sau luôn là động từ nguyên mẫu không có to."),
      teacher("Sau nhiều năm đứng lớp, tôi để ý người Việt dùng will cho mọi thứ thuộc về tương lai, còn người bản xứ lại chọn rất kỹ: đoán thì will, dự định thì going to, không chắc thì might. Mỗi sáng đọc tin thời tiết, các em hãy tự nói ba câu: một câu với **will**, một câu với **probably won't**, một câu với **might**. Chỉ cần hai tuần là các “nấc” chắc chắn này sẽ bật ra tự nhiên."),
    ],
  },
  words: [
    word("future", "/ˈfjuː.tʃər/", "tương lai", "What will you do in the future?", "fu|ture", 0),
    word("predict", "/prɪˈdɪkt/", "dự đoán", "Nobody can predict the future.", "pre|dict", 1, "Nhớ đọc rõ cả /k/ và /t/ ở cuối: /prɪˈdɪkt/."),
    word("weather", "/ˈweð.ər/", "thời tiết", "The weather will be better tomorrow.", "weath|er", 0, "Âm /ð/ đặt đầu lưỡi giữa hai hàm răng, không đọc thành “ve-dơ”."),
    word("probably", "/ˈprɒb.ə.bli/", "có lẽ, có khả năng", "It'll probably be cold tonight.", "prob|a|bly", 0),
    word("definitely", "/ˈdef.ɪ.nət.li/", "chắc chắn", "I'll definitely call you tomorrow.", "def|i|nite|ly", 0, "Bốn âm tiết, trọng âm ở âm đầu: ĐÉP-fi-nợt-li."),
    word("rain", "/reɪn/", "mưa", "I think it'll rain this evening.", "rain", 0),
    word("win", "/wɪn/", "thắng", "Do you think Vietnam will win?", "win", 0),
    word("worry", "/ˈwʌr.i/", "lo lắng", "Don't worry. Everything will be fine.", "wor|ry", 0, "Âm /ʌ/ gần giống “ă” ngắn trong tiếng Việt, nghe như “uă-ri”, không đọc thành “uo-ri” theo mặt chữ."),
  ],
  exercises: [
    mc("a2-n06-1", "I'm sure Vietnam ___ the match tonight.", ["wins", "will win", "might win", "win"], 1, "Đã nói I'm sure (tôi chắc chắn) thì dùng will win. Might win chỉ là có thể, không hợp với sure."),
    mc("a2-n06-2", "Chọn câu đúng.", ["She probably won't come.", "She won't probably come.", "She will not probably come."], 0, "Probably đứng trước won't."),
    fill("a2-n06-3", "Take an umbrella. It ___ rain this afternoon. (có thể)", ["might", "may", "could"], "Không chắc chắn, chỉ là có thể: might rain (may, could cũng đúng)."),
    fill("a2-n06-4", "I don't think he ___ pass the exam. (sẽ)", ["will"], "Mẫu câu I don't think + chủ ngữ + will + động từ nguyên mẫu."),
    reorder("a2-n06-5", "I think she will love Hoi An.", "I think + chủ ngữ + will + động từ nguyên mẫu: cách dự đoán nhẹ nhàng, tự nhiên."),
    reorder("a2-n06-6", "Do you think prices will go up?", "Hỏi ý kiến người khác về tương lai: Do you think + chủ ngữ + will...?"),
    listen("a2-n06-7", "It probably won't be very hot tomorrow.", ["Mai chắc chắn sẽ rất nóng.", "Hôm nay có lẽ không nóng lắm.", "Mai có lẽ sẽ không nóng lắm."], 2, "Probably won't: có lẽ sẽ không. Tomorrow là ngày mai."),
    listen("a2-n06-8", "I might go to the party, but I'm not sure.", ["Có thể tôi sẽ đi dự tiệc, nhưng tôi chưa chắc.", "Chắc chắn tôi sẽ đi dự tiệc.", "Tôi không đi dự tiệc được đâu."], 0, "Might go: có thể sẽ đi, người nói chưa chắc chắn."),
  ],
  speaking: [
    say("I think it will rain this evening.", "Tôi nghĩ tối nay trời sẽ mưa."),
    say("She'll definitely pass the exam.", "Chắc chắn cô ấy sẽ đỗ kỳ thi."),
    say("I might visit my parents next month, but I'm not sure.", "Tháng sau có thể tôi sẽ về thăm bố mẹ, nhưng tôi chưa chắc."),
  ],
});
