import { A, B, correct, dialogue, ex, fill, free, lesson, listen, listenQ, mc, mistake, p, reading, reorder, say, summary, table, task, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "ky-nghi-cua-toi",
  title: "Kỳ nghỉ của tôi",
  minutes: 30,
  lecture: {
    title: "Câu hỏi Wh- ở quá khứ đơn và động từ bất quy tắc",
    blocks: [
      p("Nghỉ Tết hay nghỉ hè xong, quay lại công ty, đồng nghiệp nước ngoài sẽ hỏi bạn: **Where did you go?**, **How long did you stay?** Câu hỏi thì dễ hiểu, nhưng đến lượt mình hỏi lại, rất nhiều người Việt buột miệng “Where you went?”. Bài này giúp bạn hỏi và kể về một kỳ nghỉ cho trọn vẹn."),
      p("Công thức chỉ có một: **Từ để hỏi + did + chủ ngữ + động từ nguyên mẫu?** Did đã gánh phần quá khứ, nên động từ chính được “nghỉ”, quay về dạng nguyên mẫu."),
      table(
        ["Từ để hỏi", "Câu hỏi", "Trả lời mẫu"],
        ["Where (ở đâu)", "Where did you go?", "We went to Phu Quoc."],
        ["When (khi nào)", "When did you leave?", "We left on Friday morning."],
        ["How long (bao lâu)", "How long did you stay?", "We stayed for five days."],
        ["Who... with (với ai)", "Who did you go with?", "I went with my family."],
        ["How (bằng cách nào)", "How did you get there?", "We flew."],
        ["What (cái gì)", "What did you do there?", "We swam and ate seafood."],
      ),
      ex("Where did you go last summer?", "Hè năm ngoái bạn đi đâu?"),
      ex("How long did you stay in Sa Pa?", "Bạn ở Sa Pa bao lâu?", "How long hỏi khoảng thời gian. Trả lời gọn: For three days. hoặc chỉ Three days."),
      ex("Who did you go with?", "Bạn đi với ai?", "Giới từ with nằm ở cuối câu. Người Việt quen nói “đi với ai” nên hay đưa with lên đầu thành “With who did you go?”, nghe rất cứng."),
      p("Riêng câu hỏi với **to be** thì không dùng did, mà dùng **was / were** như bạn đã học ở bài Cuối tuần vừa rồi (A1) và bài Hôm qua bạn làm gì: **How was your holiday?** – **It was great!**, **How was the weather?** – **It was sunny every day.**"),
      table(
        ["Nguyên mẫu", "Quá khứ", "Nghĩa"],
        ["fly", "flew", "bay, đi máy bay"],
        ["take", "took", "mang, đi (xe), chụp (ảnh)"],
        ["swim", "swam", "bơi"],
        ["leave", "left", "rời đi, khởi hành"],
        ["spend", "spent", "tiêu (tiền), dành (thời gian)"],
        ["sleep", "slept", "ngủ"],
        ["bring", "brought", "mang theo"],
        ["lose", "lost", "đánh mất"],
        ["come", "came", "đến"],
        ["drive", "drove", "lái xe"],
      ),
      tip("Học động từ bất quy tắc theo **nhóm cùng vần** thì nhanh thuộc hơn nhiều: **sleep – slept, leave – left, spend – spent** (đều kết thúc bằng /t/); **bring – brought, buy – bought** (đều có vần “ought”, đọc là /ɔːt/). Đọc brought là /brɔːt/, không đọc thành “brao”."),
      mistake("Where you went last summer?", "Where did you go last summer?", "Tiếng Việt hỏi “Bạn đã đi đâu?” mà không cần trợ động từ, nên học trò hay bỏ did. Câu hỏi quá khứ trong tiếng Anh bắt buộc có did đứng trước chủ ngữ."),
      mistake("How long did you stayed there?", "How long did you stay there?", "Đã có did báo quá khứ rồi thì động từ chính phải về nguyên mẫu. Quá khứ chỉ đánh dấu một lần."),
      mistake("I went to Nha Trang in holiday.", "I went to Nha Trang on holiday.", "Dịch từng chữ “trong kỳ nghỉ” sẽ ra in. Tiếng Anh nói đi nghỉ là on holiday."),
      teacher("Khi đứng lớp, tôi thấy nhiều học viên thuộc làu bảng động từ bất quy tắc, nhưng cứ đặt câu hỏi là quên did. Vì thế tôi dặn các bạn một câu: **“Có did thì động từ nghỉ”**. Mỗi tối trước khi ngủ, các bạn hãy tự hỏi mình năm câu về ngày hôm đó: Where did I go? What did I eat? Who did I talk to?... rồi tự trả lời bằng động từ quá khứ. Làm đều một tuần là miệng tự quen."),
      summary(
        "Hỏi chuyện đã qua: từ để hỏi + did + chủ ngữ + động từ nguyên mẫu? (Where did you go?)",
        "Có did thì động từ nghỉ: nói How long did you stay?, không nói did you stayed.",
        "Hỏi cảm nhận bằng to be thì dùng was, không dùng did: How was your holiday? How was the weather?",
        "Giới từ để cuối câu hỏi: Who did you go with?",
        "Trả lời bằng động từ quá khứ, nhiều từ bất quy tắc: flew, took, swam, left, spent, brought. Đi nghỉ là on holiday.",
      ),
    ],
  },
  words: [
    word("holiday", "/ˈhɒl.ə.deɪ/", "kỳ nghỉ", "We had a wonderful holiday in Da Lat.", "hol|i|day", 0),
    word("trip", "/trɪp/", "chuyến đi", "How was your trip to Hue?", "trip", 0, "Nhớ giữ âm /p/ ở cuối bằng cách mím môi, đừng nuốt thành “tri”."),
    word("seafood", "/ˈsiː.fuːd/", "hải sản", "We ate a lot of seafood in Nha Trang.", "sea|food", 0, "Hai nguyên âm đều dài: /iː/ và /uː/. Seafood không đếm được, không nói seafoods."),
    word("island", "/ˈaɪ.lənd/", "hòn đảo", "Phu Quoc is a beautiful island.", "is|land", 0, "Chữ s không đọc: /ˈaɪ.lənd/."),
    word("hotel", "/həʊˈtel/", "khách sạn", "We stayed in a small hotel near the sea.", "ho|tel", 1, "Trọng âm rơi vào âm tiết sau: hơu-TEL. Người Việt hay đọc nhấn âm đầu thành “HÔ-ten”."),
    word("flight", "/flaɪt/", "chuyến bay", "Our flight left at six in the morning.", "flight", 0),
    word("luggage", "/ˈlʌɡ.ɪdʒ/", "hành lý", "I lost my luggage at the airport.", "lug|gage", 0, "Luggage là danh từ không đếm được: không nói “two luggages”."),
    word("souvenir", "/ˌsuː.vənˈɪə/", "quà lưu niệm", "I brought some souvenirs for my colleagues.", "sou|ven|ir", 2),
  ],
  exercises: [
    mc("a2-n02-1", "Where ___ you go last summer?", ["do", "did", "were", "went"], 1, "Hỏi về chuyện đã qua với động từ thường thì dùng did: Where did you go?"),
    mc("a2-n02-2", "A: How long did you stay in Hoi An? B: ___", ["In May.", "With my sister.", "For four days.", "By bus."], 2, "How long hỏi khoảng thời gian, nên trả lời For four days. In May trả lời cho When, With my sister cho Who... with, By bus cho How."),
    fill("a2-n02-3", "We ___ to Phu Quoc and stayed in a small hotel. (fly)", ["flew"], "Fly là động từ bất quy tắc: fly → flew."),
    fill("a2-n02-4", "How long did you ___ in Da Lat? (stay)", ["stay"], "Sau did, động từ giữ nguyên mẫu: stay, không phải stayed."),
    reorder("a2-n02-5", "Who did you go with?", "Who + did + chủ ngữ + go, và giới từ with nằm ở cuối câu."),
    reorder("a2-n02-6", "How did you get to the island?", "How hỏi về cách đi lại. Get to + nơi chốn nghĩa là đến được nơi đó."),
    listen("a2-n02-7", "We left early and took a lot of photos.", ["Chúng tôi đến muộn và chụp nhiều ảnh.", "Chúng tôi rời đi sớm và mua nhiều quà.", "Chúng tôi rời đi sớm và chụp rất nhiều ảnh."], 2, "Left là quá khứ của leave (rời đi), took là quá khứ của take (chụp ảnh: take photos)."),
    listen("a2-n02-8", "How was your holiday?", ["Kỳ nghỉ của bạn thế nào?", "Bạn đi nghỉ ở đâu?", "Bạn đi nghỉ bao lâu?"], 0, "How was...? hỏi cảm nhận: thế nào. Câu này dùng was vì là động từ to be."),
    correct("a2-n02-9", "Where you stayed in Da Lat?", ["Where did you stay in Da Lat?"], "Câu hỏi quá khứ với động từ thường cần did đứng trước chủ ngữ, và động từ chính về nguyên mẫu: Where did you stay?"),
    correct("a2-n02-10", "What did you bought for your mother?", ["What did you buy for your mother?"], "Có did thì động từ nghỉ: buy, không phải bought. Quá khứ chỉ đánh dấu một lần."),
  ],
  freeSpeaking: free(
    "Tell me about a holiday you enjoyed. Where did you go, and what did you do?",
    "Kể về một kỳ nghỉ bạn thích: đi đâu, với ai, đi bằng gì, ở bao lâu, làm gì và kỳ nghỉ thế nào.",
    "Two years ago I went to Hoi An with my parents. We took the train from Hanoi to Da Nang, and the trip took about sixteen hours. We stayed in a small hotel near the old town for three days. We walked a lot, ate cao lau and took hundreds of photos. It was a lovely holiday.",
  ),
  speaking: [
    say("Where did you go on holiday last year?", "Năm ngoái bạn đi nghỉ ở đâu?"),
    say("I flew to Phu Quoc with my family.", "Tôi bay ra Phú Quốc cùng gia đình."),
    say("We stayed in a small hotel near the beach for five days.", "Chúng tôi ở một khách sạn nhỏ gần biển trong năm ngày."),
  ],
  dialogue: dialogue(
    "Sau kỳ nghỉ Tết",
    "Ngày đầu đi làm sau Tết, David, đồng nghiệp người Mỹ, hỏi Hương về chuyến đi Phú Quốc. Hương kể lại rồi hỏi ngược lại David.",
    { A: "David (đồng nghiệp)", B: "Hương" },
    A("Hi Huong! How was your holiday?", "Chào Hương! Kỳ nghỉ của bạn thế nào?"),
    B("It was wonderful, thanks. I went to Phu Quoc with my family.", "Tuyệt lắm, cảm ơn bạn. Mình đi Phú Quốc với gia đình."),
    A("Lucky you! How did you get there?", "Sướng thế! Bạn đi bằng gì?"),
    B("We flew from Hanoi. The flight took two hours.", "Nhà mình bay từ Hà Nội. Chuyến bay mất hai tiếng."),
    A("How long did you stay?", "Bạn ở đó bao lâu?"),
    B("We stayed for five days in a small hotel near the beach.", "Nhà mình ở năm ngày trong một khách sạn nhỏ gần biển."),
    A("What did you do there?", "Bạn làm gì ở đó?"),
    B("We swam every morning and ate a lot of seafood. I brought some souvenirs for the team, too.", "Sáng nào cũng đi bơi và ăn rất nhiều hải sản. Mình còn mang quà lưu niệm về cho cả nhóm nữa."),
    A("Oh, thank you! How was the weather?", "Ồ, cảm ơn bạn! Thời tiết thế nào?"),
    B("It was sunny every day. What about you? Where did you go?", "Ngày nào cũng nắng. Còn bạn? Bạn đi đâu?"),
    A("I didn't go anywhere. I stayed in Hanoi and slept a lot!", "Mình chẳng đi đâu cả. Mình ở Hà Nội và ngủ thật nhiều!"),
    B("That sounds nice, too!", "Nghe cũng thích đấy chứ!"),
  ),
  dialogueQuestions: [
    listenQ("a2-n02-d1", "Gia đình Hương đến Phú Quốc bằng cách nào?", "We flew from Hanoi. The flight took two hours.", ["Đi tàu hỏa", "Đi máy bay", "Đi xe khách", "Đi ô tô riêng"], 1, "We flew: chúng tôi bay, tức là đi máy bay. Chuyến bay mất hai tiếng."),
    mc("a2-n02-d2", "Hương ở Phú Quốc bao lâu?", ["Năm ngày", "Hai ngày", "Một tuần"], 0, "Hương nói: We stayed for five days in a small hotel near the beach."),
    mc("a2-n02-d3", "Kỳ nghỉ Tết, David đã làm gì?", ["Đi Phú Quốc cùng Hương", "Về Mỹ thăm gia đình", "Ở lại Hà Nội và ngủ thật nhiều"], 2, "David nói: I didn't go anywhere. I stayed in Hanoi and slept a lot!"),
  ],
  reading: reading({
    title: "Blog du lịch: bốn ngày ở Hà Giang",
    text: `Last October, my friend Tuan and I went to Ha Giang for four days. We took a night bus from Hanoi and arrived at six in the morning. We were tired, but the mountains were beautiful.

On the first day, we rented two motorbikes. We rode over a high mountain pass to Dong Van and stopped many times to take photos. In the evening, we stayed at a homestay there. The owner cooked a big dinner for us, and we slept very well.

On the third day, it rained all morning, so we didn't ride far. We visited a Sunday market and bought some souvenirs for our families.

What did I like best? The people. They were very friendly and always smiled at us. The trip wasn't cheap, and the roads were difficult, but I want to go back next year.`,
    glossary: [
      ["mountains", "núi, vùng núi"],
      ["rented", "đã thuê (quá khứ của rent)"],
      ["rode", "đã đi xe, cưỡi (quá khứ của ride)"],
      ["pass", "đèo"],
      ["homestay", "nhà dân nhận khách ở lại"],
      ["owner", "chủ nhà"],
    ],
    questions: [
      mc("a2-n02-r1", "Bài blog chủ yếu kể về điều gì?", ["Cách thuê xe máy ở Hà Nội", "Chuyến đi Hà Giang bốn ngày của tác giả", "Một phiên chợ ở Đồng Văn", "Các món ăn của người vùng núi"], 1, "Câu đầu tiên đã nói ý chính: Last October, my friend Tuan and I went to Ha Giang for four days."),
      mc("a2-n02-r2", "Tác giả và bạn đi từ Hà Nội đến Hà Giang bằng gì?", ["Xe máy", "Máy bay", "Xe khách đi đêm", "Tàu hỏa"], 2, "We took a night bus from Hanoi: họ đi xe khách đêm. Xe máy là thuê ở Hà Giang."),
      mc("a2-n02-r3", "Vì sao ngày thứ ba họ không đi xa?", ["Vì xe máy bị hỏng", "Vì trời mưa cả buổi sáng", "Vì họ quá mệt", "Vì họ ở homestay cả ngày"], 1, "It rained all morning, so we didn't ride far."),
      fill("a2-n02-r4", "Hoàn thành câu theo bài đọc: On the third day, they ___ a Sunday market. (visit)", ["visited"], "Kể chuyện đã qua nên dùng quá khứ: visit → visited."),
      mc("a2-n02-r5", "Tác giả thích điều gì nhất trong chuyến đi?", ["Những con đèo", "Bữa tối ở homestay", "Người dân thân thiện", "Chợ phiên"], 2, "What did I like best? The people. They were very friendly."),
    ],
  }),
  task: task({
    prompt: "Viết 6–8 câu (ít nhất 50 từ) kể về một kỳ nghỉ gần đây của bạn: đi đâu, với ai, đi bằng gì, ở bao lâu, làm gì và kỳ nghỉ thế nào. Kết thúc bằng một câu hỏi Wh- để hỏi lại người nghe.",
    hints: [
      "Trả lời lần lượt các câu hỏi Where, Who... with, How, How long, What.",
      "Dùng động từ bất quy tắc của bài: went, flew, took, swam, spent, brought.",
      "Nói cảm nhận bằng was: It was a wonderful holiday.",
      "Câu hỏi cuối: Where did you go last summer?",
    ],
    model: "Last summer I went to Da Nang with my two best friends. We took the train from Hue, and the trip took three hours. We stayed in a small hotel near the beach for four days. Every morning we swam in the sea, and in the evening we ate seafood. I spent a lot of money on souvenirs. It was a wonderful holiday! Where did you go last summer?",
    checklist: [
      "Trả lời được ít nhất 4 ý: đi đâu, với ai, bằng gì, bao lâu, làm gì",
      "Mọi động từ kể chuyện đều ở dạng quá khứ",
      "Có ít nhất 3 động từ bất quy tắc (went, took, flew, swam, spent...)",
      "Có 1 câu cảm nhận với was (It was...)",
      "Câu hỏi cuối có did + động từ nguyên mẫu (Where did you go?, không viết Where did you went?)",
    ],
    minWords: 50,
  }),
});
