import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "ky-nghi-cua-toi",
  title: "Kỳ nghỉ của tôi",
  minutes: 20,
  lecture: {
    title: "Câu hỏi Wh- ở quá khứ đơn và động từ bất quy tắc",
    blocks: [
      p("Nghỉ Tết hay nghỉ hè xong, quay lại công ty, đồng nghiệp nước ngoài sẽ hỏi bạn: **Where did you go?**, **How long did you stay?** Câu hỏi thì dễ hiểu, nhưng đến lượt mình hỏi lại, rất nhiều người Việt buột miệng “Where you went?”. Bài này giúp bạn hỏi và kể về một kỳ nghỉ cho trọn vẹn."),
      p("Công thức chỉ có một: **Từ để hỏi + did + chủ ngữ + động từ nguyên mẫu?** Did đã gánh phần quá khứ, nên động từ chính được “nghỉ”, quay về dạng nguyên mẫu."),
      table(
        ["Từ để hỏi", "Câu hỏi", "Trả lời mẫu"],
        ["Where (ở đâu)", "Where did you go?", "We went to Phu Quoc."],
        ["When (khi nào)", "When did you leave?", "We left on Friday morning."],
        ["How long (bao lâu)", "How long did you stay?", "We stayed for five days."],
        ["Who... with (với ai)", "Who did you go with?", "I went with my family."],
        ["How (bằng cách nào)", "How did you get there?", "We flew."],
        ["What (cái gì)", "What did you do there?", "We swam and ate seafood."],
      ),
      ex("Where did you go last summer?", "Hè năm ngoái bạn đi đâu?"),
      ex("How long did you stay in Sa Pa?", "Bạn ở Sa Pa bao lâu?", "How long hỏi khoảng thời gian. Trả lời gọn: For three days. hoặc chỉ Three days."),
      ex("Who did you go with?", "Bạn đi với ai?", "Giới từ with nằm ở cuối câu. Người Việt quen nói “đi với ai” nên hay đưa with lên đầu thành “With who did you go?”, nghe rất cứng."),
      p("Riêng câu hỏi với **to be** thì không dùng did, mà dùng **was / were** như bạn đã học ở bài Cuối tuần vừa rồi (A1) và bài Hôm qua bạn làm gì: **How was your holiday?** – **It was great!**, **How was the weather?** – **It was sunny every day.**"),
      table(
        ["Nguyên mẫu", "Quá khứ", "Nghĩa"],
        ["fly", "flew", "bay, đi máy bay"],
        ["take", "took", "mang, đi (xe), chụp (ảnh)"],
        ["swim", "swam", "bơi"],
        ["leave", "left", "rời đi, khởi hành"],
        ["spend", "spent", "tiêu (tiền), dành (thời gian)"],
        ["sleep", "slept", "ngủ"],
        ["bring", "brought", "mang theo"],
        ["lose", "lost", "đánh mất"],
        ["come", "came", "đến"],
        ["drive", "drove", "lái xe"],
      ),
      tip("Học động từ bất quy tắc theo **nhóm cùng vần** thì nhanh thuộc hơn nhiều: **sleep – slept, leave – left, spend – spent** (đều kết thúc bằng /t/); **bring – brought, buy – bought** (đều có vần “ought”, đọc là /ɔːt/). Đọc brought là /brɔːt/, không đọc thành “brao”."),
      mistake("Where you went last summer?", "Where did you go last summer?", "Tiếng Việt hỏi “Bạn đã đi đâu?” mà không cần trợ động từ, nên học trò hay bỏ did. Câu hỏi quá khứ trong tiếng Anh bắt buộc có did đứng trước chủ ngữ."),
      mistake("How long did you stayed there?", "How long did you stay there?", "Đã có did báo quá khứ rồi thì động từ chính phải về nguyên mẫu. Quá khứ chỉ đánh dấu một lần."),
      mistake("I went to Nha Trang in holiday.", "I went to Nha Trang on holiday.", "Dịch từng chữ “trong kỳ nghỉ” sẽ ra in. Tiếng Anh nói đi nghỉ là on holiday."),
      teacher("Sau nhiều năm dạy, tôi thấy học viên thuộc làu bảng động từ bất quy tắc, nhưng cứ đặt câu hỏi là quên did. Vì thế tôi dặn các bạn một câu: **“Có did thì động từ nghỉ”**. Mỗi tối trước khi ngủ, các bạn hãy tự hỏi mình năm câu về ngày hôm đó: Where did I go? What did I eat? Who did I talk to?... rồi tự trả lời bằng động từ quá khứ. Làm đều một tuần là miệng tự quen."),
    ],
  },
  words: [
    word("holiday", "/ˈhɒl.ə.deɪ/", "kỳ nghỉ", "We had a wonderful holiday in Da Lat.", "hol|i|day", 0),
    word("trip", "/trɪp/", "chuyến đi", "How was your trip to Hue?", "trip", 0, "Nhớ bật âm /p/ ở cuối bằng cách mím môi, đừng nuốt thành “tri”."),
    word("beach", "/biːtʃ/", "bãi biển", "We spent every morning on the beach.", "beach", 0, "Nguyên âm /iː/ phải kéo dài. Đọc ngắn thành /ɪ/ sẽ ra một từ khác rất khó nghe."),
    word("island", "/ˈaɪ.lənd/", "hòn đảo", "Phu Quoc is a beautiful island.", "is|land", 0, "Chữ s không đọc: /ˈaɪ.lənd/."),
    word("hotel", "/həʊˈtel/", "khách sạn", "We stayed in a small hotel near the sea.", "ho|tel", 1, "Trọng âm rơi vào âm tiết sau: hơu-TEL. Người Việt hay đọc nhấn âm đầu thành “HÔ-ten”."),
    word("flight", "/flaɪt/", "chuyến bay", "Our flight left at six in the morning.", "flight", 0),
    word("luggage", "/ˈlʌɡ.ɪdʒ/", "hành lý", "I lost my luggage at the airport.", "lug|gage", 0, "Luggage là danh từ không đếm được: không nói “two luggages”."),
    word("souvenir", "/ˌsuː.vənˈɪər/", "quà lưu niệm", "I brought some souvenirs for my colleagues.", "sou|ven|ir", 2),
  ],
  exercises: [
    mc("a2-n02-1", "Where ___ you go last summer?", ["do", "did", "were", "went"], 1, "Hỏi về chuyện đã qua với động từ thường thì dùng did: Where did you go?"),
    mc("a2-n02-2", "A: How long did you stay in Hoi An? B: ___", ["In May.", "With my sister.", "For four days.", "By bus."], 2, "How long hỏi khoảng thời gian, nên trả lời For four days. In May trả lời cho When, With my sister cho Who... with, By bus cho How."),
    fill("a2-n02-3", "We ___ to Phu Quoc and stayed in a small hotel. (fly)", ["flew"], "Fly là động từ bất quy tắc: fly → flew."),
    fill("a2-n02-4", "How long did you ___ in Da Lat? (stay)", ["stay"], "Sau did, động từ giữ nguyên mẫu: stay, không phải stayed."),
    reorder("a2-n02-5", "Who did you go with?", "Who + did + chủ ngữ + go, và giới từ with nằm ở cuối câu."),
    reorder("a2-n02-6", "How did you get to the island?", "How hỏi về cách đi lại. Get to + nơi chốn nghĩa là đến được nơi đó."),
    listen("a2-n02-7", "We left early and took a lot of photos.", ["Chúng tôi đến muộn và chụp nhiều ảnh.", "Chúng tôi rời đi sớm và mua nhiều quà.", "Chúng tôi rời đi sớm và chụp rất nhiều ảnh."], 2, "Left là quá khứ của leave (rời đi), took là quá khứ của take (chụp ảnh: take photos)."),
    listen("a2-n02-8", "How was your holiday?", ["Kỳ nghỉ của bạn thế nào?", "Bạn đi nghỉ ở đâu?", "Bạn đi nghỉ bao lâu?"], 0, "How was...? hỏi cảm nhận: thế nào. Câu này dùng was vì là động từ to be."),
  ],
  speaking: [
    say("Where did you go on holiday last year?", "Năm ngoái bạn đi nghỉ ở đâu?"),
    say("I flew to Phu Quoc with my family.", "Tôi bay ra Phú Quốc cùng gia đình."),
    say("We stayed in a small hotel near the beach for five days.", "Chúng tôi ở một khách sạn nhỏ gần biển trong năm ngày."),
  ],
});
