import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "qua-va-khong-du",
  title: "Quá… và không đủ…",
  minutes: 20,
  lecture: {
    title: "Too, enough, too much và too many",
    blocks: [
      p("Đi mua giày, bạn thử một đôi và muốn nói với người bán: “Đôi này chật quá, không đủ rộng”. Hoặc đi ăn, bạn muốn nói món canh cay quá không ăn được. Để nói **vượt quá mức** hay **chưa đạt mức** mình cần, tiếng Anh dùng **too** và **enough**."),
      p("Cái bẫy lớn nhất với người Việt là chữ **“quá”**. Tiếng Việt nói “Đẹp quá!” để khen, nghĩa là **rất đẹp**. Nhưng **too** trong tiếng Anh luôn mang nghĩa **quá mức, gây ra vấn đề**. Khen thì dùng **very**, **really** hoặc **so**."),
      table(
        ["Cấu trúc", "Nghĩa", "Ví dụ"],
        ["too + tính từ", "quá (gây vấn đề)", "These shoes are too small."],
        ["tính từ + enough", "đủ", "Is the room big enough?"],
        ["not + tính từ + enough", "không đủ", "The bag isn't big enough."],
        ["enough + danh từ", "đủ (bao nhiêu thứ)", "We have enough chairs."],
        ["too many + danh từ số nhiều", "quá nhiều (đếm được)", "There are too many cars."],
        ["too much + danh từ không đếm được", "quá nhiều (không đếm được)", "I have too much work."],
      ),
      ex("These shoes are too small for me. Do you have a bigger size?", "Đôi giày này chật quá so với tôi. Chị có cỡ lớn hơn không?"),
      ex("This room isn't big enough for six people.", "Phòng này không đủ rộng cho sáu người."),
      ex("We don't have enough chairs for everyone.", "Chúng ta không có đủ ghế cho mọi người.", "Enough đứng trước danh từ nhưng đứng sau tính từ: enough chairs, nhưng big enough."),
      ex("There are too many motorbikes in the city centre.", "Trung tâm thành phố có quá nhiều xe máy."),
      p("Muốn nói rõ **quá... nên không làm được gì**, hoặc **đủ... để làm gì**, thêm **to + động từ nguyên mẫu** vào sau."),
      ex("The tea is too hot to drink.", "Trà nóng quá, không uống được.", "Không nói “too hot to drink it”, vì chủ ngữ the tea đã là thứ được uống rồi."),
      ex("My son is old enough to go to school by bus.", "Con trai tôi đã đủ lớn để tự đi học bằng xe buýt."),
      tip("Mẹo nhớ vị trí của **enough**: “**sau tính, trước danh**”: big **enough**, **enough** money. Còn phát âm: enough đọc là /ɪˈnʌf/, chữ **gh** đọc thành /f/ và trọng âm rơi vào âm sau: i-NÁP."),
      mistake("The view here is too beautiful!", "The view here is really beautiful!", "Tiếng Việt khen “Đẹp quá!”, nên người Việt dịch thành too beautiful. Nhưng too nghĩa là đẹp tới mức có vấn đề. Khen thì dùng really, very hoặc so."),
      mistake("He isn't enough old to drive.", "He isn't old enough to drive.", "Tiếng Việt nói “đủ lớn” (đủ đứng trước), nên người học đặt enough trước tính từ. Tiếng Anh ngược lại: tính từ + enough."),
      mistake("There is too much people here.", "There are too many people here.", "People là danh từ đếm được số nhiều, nên dùng too many và are."),
      teacher("Tôi đã chứng kiến không ít lần học trò khen chủ nhà người nước ngoài “Your house is too big!” và chủ nhà ngẩn người, tưởng mình bị chê. Nên các em nhớ kỹ: **too là lời phàn nàn, very là lời khen**. Cách luyện của tôi: mỗi ngày nhìn quanh và nói ba câu than phiền nhỏ bằng too, ba câu bằng not enough. Ví dụ: My coffee is too sweet. My desk isn't big enough. Nói thành tiếng, nhanh và vui, như đang càu nhàu thật."),
    ],
  },
  words: [
    word("enough", "/ɪˈnʌf/", "đủ", "Do we have enough time?", "e|nough", 1, "Chữ gh đọc là /f/, trọng âm ở âm thứ hai: i-NÁP."),
    word("tight", "/taɪt/", "chật, bó", "These jeans are too tight.", "tight", 0, "Chữ gh câm; nhớ bật âm /t/ ở cuối."),
    word("loose", "/luːs/", "rộng, lỏng", "This shirt is a bit loose.", "loose", 0, "Loose kết thúc bằng âm /s/. Đừng nhầm với lose /luːz/ (mất, thua)."),
    word("sweet", "/swiːt/", "ngọt", "This coffee is too sweet for me.", "sweet", 0, "Nguyên âm dài /iː/ và nhớ bật âm /t/ ở cuối."),
    word("crowded", "/ˈkraʊ.dɪd/", "đông đúc", "The market is too crowded at the weekend.", "crowd|ed", 0, "Đuôi -ed đọc là /ɪd/ vì crowd kết thúc bằng âm /d/."),
    word("noisy", "/ˈnɔɪ.zi/", "ồn ào", "It's too noisy to sleep here.", "nois|y", 0),
    word("spicy", "/ˈspaɪ.si/", "cay", "The soup is too spicy for me.", "spic|y", 0),
    word("space", "/speɪs/", "chỗ, không gian", "There isn't enough space for a sofa.", "space", 0, "Nhớ âm /s/ ở cuối, không đọc thành “xpây”."),
  ],
  exercises: [
    mc("a2-n11-1", "This bag is ___. I can't carry it.", ["too heavy", "heavy enough", "enough heavy"], 0, "Nặng quá mức nên không mang được: too heavy."),
    mc("a2-n11-2", "Is the room ___ for four people?", ["enough big", "too big enough", "big enough", "too enough"], 2, "Enough đứng sau tính từ: big enough."),
    fill("a2-n11-3", "There are too ___ people on this bus.", ["many"], "People là danh từ đếm được số nhiều nên dùng too many."),
    fill("a2-n11-4", "I don't have ___ money to buy a new car. (đủ)", ["enough"], "Enough đứng trước danh từ: enough money."),
    reorder("a2-n11-5", "My suitcase is too heavy to carry.", "Too + tính từ + to + động từ nguyên mẫu: nặng quá, không mang được."),
    reorder("a2-n11-6", "She isn't old enough to drive.", "Not + tính từ + enough + to + động từ nguyên mẫu."),
    listen("a2-n11-7", "The soup is too spicy for me.", ["Món canh này cay vừa đủ với tôi.", "Món canh này không cay lắm.", "Món canh này cay quá đối với tôi."], 2, "Too spicy là cay quá mức, người nói thấy khó ăn."),
    listen("a2-n11-8", "We don't have enough time.", ["Chúng ta có quá nhiều thời gian.", "Chúng ta không có đủ thời gian.", "Chúng ta có đủ thời gian."], 1, "Don't have enough là không có đủ."),
  ],
  speaking: [
    say("This shirt is too big for me.", "Cái áo này rộng quá so với tôi."),
    say("The room isn't big enough for our family.", "Căn phòng không đủ rộng cho gia đình chúng tôi."),
    say("There are too many people here today.", "Hôm nay ở đây đông người quá."),
  ],
});
