import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "tieu-su",
  title: "Kể về cuộc đời một người",
  minutes: 22,
  lecture: {
    title: "Before, after, when với quá khứ đơn và cách nói ngày tháng, năm",
    blocks: [
      p("Giới thiệu ông bà với bạn nước ngoài, kể về một người nổi tiếng, hay trả lời phỏng vấn xin việc, bạn đều phải làm ba việc: **nói năm sinh**, **nói ngày tháng của các sự kiện**, và **nối các sự kiện theo thứ tự**. Bài này gom đủ cả ba."),
      p("Tiếng Việt nói “Tôi sinh năm 1995” như một hành động mình tự làm. Tiếng Anh thì coi việc được sinh ra là điều xảy ra với mình, nên luôn nói **was / were born**: **I was born in 1995.** Hỏi lại: **Where were you born?**, **When were you born?**"),
      table(
        ["Mốc thời gian", "Giới từ", "Ví dụ"],
        ["năm", "in", "in 1998"],
        ["tháng", "in", "in May"],
        ["tháng và năm", "in", "in May 1998"],
        ["ngày cụ thể", "on", "on 5 May, on 5 May 1998"],
        ["thập niên", "in", "in the 1990s"],
      ),
      table(
        ["Viết", "Đọc"],
        ["1998", "nineteen ninety-eight"],
        ["2005", "two thousand and five"],
        ["2019", "twenty nineteen hoặc two thousand and nineteen"],
        ["5 May", "the fifth of May"],
        ["21 June", "the twenty-first of June"],
      ),
      tip("Năm trước 2000 thì **cắt đôi** mà đọc: 19|98 thành nineteen ninety-eight. Ngày trong tháng đọc bằng **số thứ tự**: fifth, twenty-first, không đọc là five hay twenty-one. Viết là 5 May, nhưng nói thành **the fifth of May**."),
      p("Để nối các sự kiện, dùng **when** (khi), **before** (trước khi), **after** (sau khi). Sau ba từ này có thể là **một mệnh đề đầy đủ** (có chủ ngữ và động từ ở quá khứ đơn) hoặc **một danh từ**. Mệnh đề có when / before / after đứng đầu câu thì thêm dấu phẩy."),
      ex("She was born in Hai Phong in 1985.", "Bà ấy sinh ra ở Hải Phòng năm 1985."),
      ex("After he left school, he worked in a factory.", "Học hết phổ thông, anh ấy vào làm ở một nhà máy.", "Leave school là học xong phổ thông, không phải “rời khỏi trường” theo nghĩa đen."),
      ex("When I was twenty-two, I got my first job.", "Năm hai mươi hai tuổi, tôi có công việc đầu tiên.", "Tiếng Việt nói “năm hai mươi hai tuổi”. Tiếng Anh nói When I was twenty-two, hoặc at the age of twenty-two."),
      ex("My grandparents got married before the war.", "Ông bà tôi cưới nhau trước chiến tranh.", "Before ở đây đi với một danh từ: before the war."),
      mistake("I born in 1995.", "I was born in 1995.", "Tiếng Việt “tôi sinh năm…” không có chữ nào tương ứng với was, nên học trò hay bỏ. Tiếng Anh bắt buộc phải có was / were trước born."),
      mistake("She got married on 2010.", "She got married in 2010.", "Chỉ có năm thì dùng in. Có ngày cụ thể mới dùng on: on 12 June 2010."),
      mistake("After finish university, I moved to Hanoi.", "After I finished university, I moved to Hanoi.", "Tiếng Việt “sau khi tốt nghiệp” không cần chủ ngữ. Tiếng Anh cần một mệnh đề đầy đủ sau after: chủ ngữ + động từ đã chia ở quá khứ."),
      teacher("Bài tập tôi giao cho mọi lớp A2 suốt mấy chục năm nay là: **viết một tiểu sử năm câu về ông bà hoặc bố mẹ mình**, có năm sinh, năm cưới, công việc, và ít nhất một câu với before, after hay when. Rồi đọc to lên. Tôi nghe rất nhiều bạn đọc năm như đọc số điện thoại, “one nine nine eight”. Người bản xứ nghe sẽ khựng lại ngay. Các bạn hãy tập đọc năm sinh của từng người trong nhà cho trơn miệng trước đã."),
    ],
  },
  words: [
    word("born", "/bɔːn/", "được sinh ra", "My mother was born in Nam Dinh.", "born", 0),
    word("married", "/ˈmær.id/", "đã kết hôn", "They got married in 1990.", "mar|ried", 0, "Chỉ có hai âm tiết, đuôi -ed đọc là /d/ nhẹ, không đọc thành “me-ri-đờ”."),
    word("graduate", "/ˈɡrædʒ.u.eɪt/", "tốt nghiệp", "She graduated from university in 2012.", "grad|u|ate", 0),
    word("university", "/ˌjuː.nɪˈvɜː.sə.ti/", "trường đại học", "He went to university in Hanoi.", "u|ni|ver|si|ty", 2, "Trọng âm chính ở âm thứ ba: diu-ni-VƠ-xi-ti."),
    word("career", "/kəˈrɪər/", "sự nghiệp", "She had a long career as a doctor.", "ca|reer", 1, "Trọng âm ở âm sau: cơ-RIA. Âm đầu chỉ là /kə/ nhẹ, đừng đọc rõ thành “ca-ri-ơ”."),
    word("retire", "/rɪˈtaɪər/", "nghỉ hưu", "My father retired when he was sixty.", "re|tire", 1),
    word("die", "/daɪ/", "mất, qua đời", "My grandfather died in 2015.", "die", 0),
  ],
  exercises: [
    mc("a2-n04-1", "My father ___ in 1965.", ["born", "is born", "borned", "was born"], 3, "Nói về năm sinh trong quá khứ luôn dùng was born."),
    mc("a2-n04-2", "They got married ___ 12 June 1990.", ["on", "in", "at"], 0, "Có ngày cụ thể (12 June) thì dùng on."),
    fill("a2-n04-3", "___ she finished university, she moved to Ho Chi Minh City. (sau khi)", ["after"], "Sau khi là after, theo sau là một mệnh đề đầy đủ: she finished university."),
    fill("a2-n04-4", "I was born ___ 1998.", ["in"], "Chỉ có năm thì dùng in."),
    reorder("a2-n04-5", "She was born in a small village.", "Chủ ngữ + was born + nơi sinh."),
    reorder("a2-n04-6", "When did your parents get married?", "When + did + chủ ngữ + get married, động từ get giữ nguyên mẫu vì đã có did."),
    listen("a2-n04-7", "My grandfather was born on the tenth of March.", ["Ông tôi mất ngày mười tháng Ba.", "Ông tôi sinh ngày mười tháng Ba.", "Ông tôi sinh ngày mười tháng Tư."], 1, "Was born là được sinh ra. The tenth of March là ngày mười tháng Ba."),
    listen("a2-n04-8", "Before she became a teacher, she worked in a bank.", ["Sau khi làm giáo viên, cô ấy làm ở ngân hàng.", "Khi làm giáo viên, cô ấy cũng làm ở ngân hàng.", "Trước khi làm giáo viên, cô ấy làm ở ngân hàng."], 2, "Before là trước khi: việc làm ngân hàng xảy ra trước."),
  ],
  speaking: [
    say("I was born in Hanoi in nineteen ninety-five.", "Tôi sinh ra ở Hà Nội năm một nghìn chín trăm chín mươi lăm."),
    say("After I finished university, I moved to Da Nang.", "Sau khi tốt nghiệp đại học, tôi chuyển đến Đà Nẵng."),
    say("My parents got married on the fifth of May.", "Bố mẹ tôi cưới nhau vào ngày mùng năm tháng Năm."),
  ],
});
