import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "vua-moi-da-chua",
  title: "Vừa mới, đã, chưa",
  minutes: 22,
  lecture: {
    title: "Hiện tại hoàn thành với just, already và yet",
    blocks: [
      p("Người Việt gặp nhau hay hỏi “Ăn cơm chưa?”, sếp hỏi “Em gửi email chưa?”, bạn nhắn “Mình vừa mới tới nơi”. Ba chữ **“vừa mới”**, **“đã... rồi”** và **“chưa”** trong tiếng Anh là **just**, **already** và **yet**, và chúng đi cùng **thì hiện tại hoàn thành**: **have / has + V3**."),
      p("Ở bài “Bạn đã từng…?”, ta dùng hiện tại hoàn thành với **ever / never** để nói về **trải nghiệm trong cả đời**. Bài này dùng cùng thì đó nhưng cho những việc **vừa xảy ra gần đây**, mà **kết quả còn liên quan đến bây giờ**: email đã gửi rồi, nên sếp khỏi lo; tàu vừa chạy, nên ta lỡ tàu."),
      table(
        ["Từ", "Nghĩa", "Loại câu", "Vị trí", "Ví dụ"],
        ["just", "vừa mới", "khẳng định", "giữa have và V3", "I've just arrived."],
        ["already", "đã... rồi (sớm hơn dự kiến)", "khẳng định", "giữa have và V3", "She's already left."],
        ["yet", "chưa", "phủ định", "cuối câu", "I haven't finished yet."],
        ["yet", "... chưa?", "câu hỏi", "cuối câu", "Have you eaten yet?"],
      ),
      table(
        ["Nguyên mẫu", "Quá khứ", "Quá khứ phân từ (V3)"],
        ["do", "did", "done"],
        ["send", "sent", "sent"],
        ["leave", "left", "left"],
        ["buy", "bought", "bought"],
        ["write", "wrote", "written"],
        ["have", "had", "had"],
      ),
      ex("I've just arrived at the hotel. I'll call you later.", "Anh vừa mới đến khách sạn. Lát nữa anh gọi em nhé."),
      ex("Don't worry. I've already sent the email to the customer.", "Đừng lo. Em đã gửi email cho khách hàng rồi.", "Already hàm ý việc xong sớm hơn người kia nghĩ."),
      ex("Have you had lunch yet? No, not yet.", "Bạn ăn trưa chưa? Chưa, mình chưa ăn.", "Đây chính là câu “Ăn cơm chưa?” của người Việt. Trả lời ngắn “chưa” là Not yet."),
      ex("The train has just left. We missed it by one minute.", "Tàu vừa chạy mất rồi. Chúng ta lỡ chuyến chỉ vì một phút."),
      table(
        ["Muốn nói", "Dùng", "Ví dụ"],
        ["Đã từng... trong đời chưa", "ever / never", "Have you ever been to Japan?"],
        ["Việc gần đây đã làm chưa", "yet", "Have you done your homework yet?"],
        ["Vừa mới xảy ra", "just", "He's just gone out."],
      ),
      tip("Mẹo nhớ vị trí: **just** và **already** “chen vào giữa” have và V3, còn **yet** “đứng gác cuối câu”. Khi nói, người bản xứ gần như luôn nối âm: **I've just** đọc liền thành /aɪv dʒʌst/, **She's already** thành /ʃiːz ɔːlˈred.i/. Đừng tách rời từng chữ."),
      mistake("I didn't finish my report yet.", "I haven't finished my report yet.", "Tiếng Việt không chia thì, “chưa làm xong” nghe như quá khứ nên người Việt dùng didn't. Trong tiếng Anh-Anh, đi với yet là hiện tại hoàn thành: haven't + V3."),
      mistake("I have finished my homework yet.", "I have already finished my homework.", "Yet chỉ dùng trong câu phủ định và câu hỏi. Câu khẳng định “đã... rồi” dùng already."),
      mistake("I've just seen him yesterday.", "I saw him yesterday.", "Có thời điểm cụ thể (yesterday) thì không dùng hiện tại hoàn thành, dù trong đầu bạn nghĩ “vừa mới”. Chuyển sang quá khứ đơn."),
      teacher("Học trò Việt Nam may mắn hơn người nước khác ở bài này, vì chúng ta đã có sẵn thói quen hỏi “**...chưa?**” mỗi ngày. Tôi dặn các em: **mỗi lần định hỏi “chưa” bằng tiếng Việt, hãy nói thầm câu tiếng Anh với yet**. Have you eaten yet? Have you finished yet? Have they arrived yet? Và mỗi tối, trước khi ngủ, liệt kê ba việc hôm nay đã làm rồi với already, ba việc chưa làm với haven't... yet. Một tháng thôi, cấu trúc này sẽ là của các em."),
    ],
  },
  words: [
    word("just", "/dʒʌst/", "vừa mới", "I've just got home.", "just", 0, "Nhớ bật cả /s/ và /t/ ở cuối, đừng đọc thành “giớt”."),
    word("already", "/ɔːlˈred.i/", "đã... rồi", "The film has already started.", "al|rea|dy", 1),
    word("yet", "/jet/", "chưa (trong câu hỏi và phủ định)", "Has the bus come yet?", "yet", 0, "Âm đầu là /j/, giống chữ “d” trong giọng miền Nam; nhớ bật nhẹ âm /t/ ở cuối."),
    word("arrive", "/əˈraɪv/", "đến nơi", "Our guests have just arrived.", "ar|rive", 1, "Nhớ âm /v/ ở cuối: cắn nhẹ môi dưới."),
    word("send", "/send/", "gửi", "Have you sent the photos yet?", "send", 0),
    word("leave", "/liːv/", "rời đi, rời khỏi", "The plane has already left.", "leave", 0, "Leave có nguyên âm dài /iː/, khác với live /lɪv/ (sống)."),
    word("tidy", "/ˈtaɪ.di/", "dọn dẹp, gọn gàng", "I've just tidied my desk.", "ti|dy", 0),
    word("book", "/bʊk/", "đặt (vé, phòng, bàn)", "We've already booked a table for dinner.", "book", 0),
  ],
  exercises: [
    mc("a2-n16-1", "I've ___ finished my homework. Can I go out now?", ["just", "yet", "ever"], 0, "Vừa mới làm xong: just, đứng giữa have và V3."),
    mc("a2-n16-2", "Have you sent the email ___?", ["just", "never", "yet"], 2, "Câu hỏi “đã... chưa?” dùng yet ở cuối câu."),
    fill("a2-n16-3", "I haven't had lunch ___. (chưa)", ["yet"], "Câu phủ định với nghĩa “chưa” dùng yet ở cuối câu."),
    fill("a2-n16-4", "The train has ___ left. We missed it by one minute. (vừa mới)", ["just"], "Vừa mới xảy ra dùng just, đứng giữa has và V3."),
    reorder("a2-n16-5", "Have you finished your homework yet?", "Have + chủ ngữ + V3 + tân ngữ + yet?"),
    reorder("a2-n16-6", "I have just arrived at the station.", "Just đứng giữa have và quá khứ phân từ arrived."),
    listen("a2-n16-7", "I haven't tidied my room yet.", ["Tôi đã dọn phòng rồi.", "Tôi vừa mới dọn phòng.", "Tôi chưa dọn phòng."], 2, "Haven't... yet nghĩa là chưa làm."),
    listen("a2-n16-8", "They've already booked the tickets.", ["Họ đã đặt vé rồi.", "Họ chưa đặt vé.", "Họ sắp đặt vé."], 0, "Already nghĩa là đã... rồi."),
  ],
  speaking: [
    say("I've just arrived at the airport.", "Tôi vừa mới đến sân bay."),
    say("Have you had dinner yet?", "Bạn ăn tối chưa?"),
    say("I haven't finished my work yet.", "Tôi vẫn chưa làm xong việc."),
  ],
});
