import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "cau-tao-tu",
  title: "Cấu tạo từ",
  minutes: 24,
  lecture: {
    title: "Tiền tố, hậu tố, họ từ và trọng âm dịch chuyển",
    blocks: [
      p("Tiếng Việt không đổi hình dạng từ: “quyết định” vừa là động từ vừa là danh từ, “sáng tạo” vừa là động từ vừa là tính từ. Tiếng Anh thì khác: decide, decision, decisive, decisively là bốn từ cho bốn vị trí trong câu. Ở trình độ C1, vốn từ tăng nhanh nhất không phải nhờ học từ mới, mà nhờ nắm **cấu tạo từ**: biết một gốc từ là đoán và dùng được cả **họ từ** (word family)."),
      p("**Tiền tố** (prefix) đứng trước gốc từ, làm thay đổi **nghĩa** nhưng thường giữ nguyên từ loại."),
      table(
        ["Tiền tố", "Nghĩa", "Ví dụ"],
        ["un-", "không, ngược lại", "unreliable, unlock, unaware"],
        ["dis-", "không, bỏ đi, ngược lại", "disagree, disconnect, dishonest"],
        ["mis-", "sai, nhầm", "misunderstand, misspell, misinterpret"],
        ["over-", "quá mức", "overcook, overestimate, overworked"],
        ["under-", "chưa đủ, dưới mức", "underpaid, underestimate, undercooked"],
      ),
      ex("Many first-time founders underestimate how long it takes to find customers.", "Nhiều người lần đầu khởi nghiệp đánh giá thấp thời gian cần để tìm được khách hàng."),
      mistake("I unagree with this proposal.", "I disagree with this proposal.", "Un- và dis- đều mang nghĩa “không”, nhưng mỗi gốc từ chỉ đi với một tiền tố cố định. Hầu như không có quy tắc nào để đoán; phải học cả từ, và tra từ điển khi không chắc."),
      p("**Hậu tố** (suffix) đứng sau gốc từ và thường đổi **từ loại**. Nhìn hậu tố là biết từ đó đứng ở vị trí nào trong câu."),
      table(
        ["Hậu tố", "Tạo ra", "Ví dụ"],
        ["-tion / -sion", "danh từ", "create → creation, decide → decision"],
        ["-ment", "danh từ", "develop → development, agree → agreement"],
        ["-ity", "danh từ (từ tính từ)", "creative → creativity, able → ability"],
        ["-ive", "tính từ", "create → creative, decide → decisive"],
        ["-ise (Mỹ: -ize)", "động từ", "priority → prioritise, modern → modernise"],
      ),
      ex("Her decision was quick and decisive.", "Quyết định của cô ấy nhanh chóng và dứt khoát.", "Decision là danh từ (chủ ngữ), decisive là tính từ (sau was). Cùng một họ từ, khác vị trí."),
      mistake("She is a very creativity person.", "She is a very creative person.", "Trước danh từ person cần tính từ. Vì tiếng Việt không đổi hình dạng từ, học trò hay lấy nhầm từ trong cùng họ. Hãy tự hỏi: chỗ trống cần danh từ, động từ, tính từ hay trạng từ?"),
      p("Điểm khó nhất với người Việt là **trọng âm dịch chuyển**. Khi thêm hậu tố, trọng âm có thể chạy sang âm tiết khác. Quy tắc hữu ích: với **-tion**, **-ic**, **-ity**, **-ical**, trọng âm rơi vào âm tiết **ngay trước** hậu tố."),
      table(
        ["Từ gốc", "Cùng họ", "Cùng họ"],
        ["PHOtograph", "phoTOgrapher, phoTOgraphy", "photoGRAPHic"],
        ["eCOnomy", "eCOnomist", "ecoNOmic"],
        ["POlitics", "poLItical", "poliTIcian"],
        ["creATE", "creAtion", "creaTIvity"],
      ),
      ex("Her photographs are stunning; she has been a professional photographer for years, and her photographic style is instantly recognisable.", "Ảnh của cô ấy tuyệt đẹp; cô ấy đã là nhiếp ảnh gia chuyên nghiệp nhiều năm, và phong cách nhiếp ảnh của cô ấy nhìn là nhận ra ngay.", "Ba từ cùng họ, ba vị trí trọng âm: PHOtographs, phoTOgrapher, photoGRAPHic. Đọc to cả câu để nghe trọng âm chạy từ âm tiết đầu sang âm tiết thứ hai rồi thứ ba."),
      mistake("I love PHOtography.", "I love phoTOgraphy.", "Người Việt đọc mỗi âm tiết mạnh như nhau, nên khi đã thuộc PHOtograph thì cứ giữ trọng âm đó cho cả họ từ. Người bản xứ nghe sai trọng âm còn khó hiểu hơn nghe sai một nguyên âm."),
      tip("Khi học một từ mới, hãy ghi **cả họ từ** thành một hàng, đánh dấu trọng âm bằng chữ in hoa: deCIDE, deCIsion, deCIsive. Đọc to cả hàng ba lần. Tai và miệng sẽ nhớ **sự dịch chuyển** trọng âm như nhớ một giai điệu."),
      teacher("Sau năm mươi năm dạy, tôi dám nói: học trò Việt mất điểm Writing và Speaking vì **sai từ loại** nhiều hơn vì thiếu từ. Thầy có một bài tập mỗi ngày: chọn một gốc từ trong bài báo vừa đọc, viết ra họ từ của nó, rồi đặt bốn câu, mỗi câu dùng một từ loại khác nhau. Chỉ mười phút, nhưng làm đều đặn một học kỳ thì vốn từ tăng gấp ba mà không cần học thêm gốc mới nào."),
    ],
  },
  words: [
    word("misinterpret", "/ˌmɪs.ɪnˈtɜː.prɪt/", "hiểu sai, diễn giải sai", "Journalists misinterpreted the minister's comments.", "mis|in|ter|pret", 2),
    word("underestimate", "/ˌʌn.dəˈres.tɪ.meɪt/", "đánh giá thấp", "Never underestimate your competitors.", "un|der|es|ti|mate", 2, "Trọng âm chính ở es, còn un mang trọng âm phụ. Âm cuối /t/ cần đọc rõ."),
    word("disproportionate", "/ˌdɪs.prəˈpɔː.ʃən.ət/", "không cân xứng, quá mức", "The punishment was disproportionate to the offence.", "dis|pro|por|tion|ate", 2),
    word("photography", "/fəˈtɒɡ.rə.fi/", "nghệ thuật nhiếp ảnh", "He took up photography after he retired.", "pho|tog|ra|phy", 1, "Trọng âm ở âm tiết thứ hai: pho-TOG-ra-phy, khác với PHO-to-graph."),
    word("decisive", "/dɪˈsaɪ.sɪv/", "quyết đoán, mang tính quyết định", "The manager was calm and decisive during the crisis.", "de|ci|sive", 1),
    word("prioritise", "/praɪˈɒr.ɪ.taɪz/", "ưu tiên", "You need to prioritise the most urgent tasks.", "pri|or|i|tise", 1, "Anh-Mỹ viết là prioritize."),
    word("authenticity", "/ˌɔː.θenˈtɪs.ə.ti/", "tính xác thực, tính chân thật", "Experts questioned the authenticity of the painting.", "au|then|tic|i|ty", 2, "Hậu tố -ity kéo trọng âm về âm tiết ngay trước: auTHENtic thành authenTICity."),
    word("affix", "/ˈæf.ɪks/", "phụ tố (tiền tố hoặc hậu tố)", "Un- and -ment are both common affixes.", "af|fix", 0),
  ],
  exercises: [
    mc("c1-n04-1", "Từ nào có trọng âm rơi vào âm tiết thứ hai?", ["photograph", "photography", "photographic", "photocopy"], 1, "Photography: pho-TOG-ra-phy. Photograph và photocopy nhấn âm đầu, photographic nhấn âm thứ ba."),
    mc("c1-n04-2", "The instructions were so unclear that many users ___ them.", ["ununderstood", "disunderstood", "overunderstood", "misunderstood"], 3, "Mis- nghĩa là hiểu sai, làm sai. Các lựa chọn còn lại không phải là từ có thật."),
    fill("c1-n04-3", "We completely ___estimated the cost of the project; it cost twice as much as we planned.", ["under"], "Chi phí thực tế gấp đôi dự kiến, tức là ta đã đánh giá thấp: underestimate."),
    fill("c1-n04-4", "Her ___ to resign surprised the whole department. (decide)", ["decision"], "Sau her cần một danh từ: decide thành decision."),
    reorder("c1-n04-5", "Her creativity impressed everyone on the team.", "Creativity là danh từ, làm chủ ngữ của câu."),
    reorder("c1-n04-6", "Many people underestimate the importance of sleep.", "Underestimate: under- nghĩa là dưới mức, đánh giá thấp."),
    listen("c1-n04-7", "The manager was very decisive during the crisis.", ["Người quản lý đã quyết định nghỉ việc trong cuộc khủng hoảng.", "Người quản lý do dự trong cuộc khủng hoảng.", "Người quản lý rất quyết đoán trong cuộc khủng hoảng."], 2, "Decisive là tính từ: quyết đoán."),
    listen("c1-n04-8", "His comments were completely misinterpreted by the press.", ["Báo chí đã hiểu sai hoàn toàn bình luận của anh ấy.", "Báo chí đã đăng đầy đủ bình luận của anh ấy.", "Anh ấy đã hiểu sai các bài báo."], 0, "Mis- + interpret: diễn giải sai. Câu bị động, người hiểu sai là báo chí."),
  ],
  speaking: [
    say("I studied photography at university.", "Tôi học nhiếp ảnh ở trường đại học."),
    say("We should never underestimate our competitors.", "Chúng ta không bao giờ nên đánh giá thấp đối thủ."),
    say("Her decision was quick and decisive.", "Quyết định của cô ấy nhanh chóng và dứt khoát."),
  ],
});
