import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "dong-tu-tuong-thuat",
  title: "Tường thuật tinh tế",
  minutes: 22,
  lecture: {
    title: "Động từ tường thuật và mẫu câu đi kèm",
    blocks: [
      p("Sau một cuộc họp căng thẳng, sếp hỏi bạn: “Vậy khách hàng nói gì?”. Nếu bạn chỉ lặp **he said… she said…**, người nghe không biết ai đang trách ai, ai xin lỗi, ai khăng khăng giữ ý. Người viết giỏi chọn đúng **động từ tường thuật** (accuse, deny, urge, insist…) để kể lại cả **thái độ** của người nói, không cần chép lại từng chữ. Ở cấp B2 bạn đã gặp suggest và tell; bài này đi trọn các mẫu câu khó hơn."),
      table(
        ["Mẫu câu", "Động từ thường gặp", "Ví dụ"],
        ["V + to V", "agree, refuse, offer, promise, threaten", "She refused to sign the contract."],
        ["V + người + to V", "urge, warn, advise, persuade, encourage, remind", "The doctor urged him to stop smoking."],
        ["V + V-ing", "deny, admit, suggest, recommend", "He denied taking the money."],
        ["V + giới từ + V-ing", "insist on, apologise for, confess to, object to", "She insisted on paying the bill."],
        ["V + người + giới từ + V-ing", "accuse sb of, blame sb for, congratulate sb on, thank sb for", "They accused him of lying."],
        ["V + that + mệnh đề", "admit, deny, insist, suggest, explain", "He admitted that he had made a mistake."],
      ),
      p("Nguyên tắc cốt lõi: động từ tường thuật **tóm lại ý định** của người nói. Câu “I didn't take it!” không cần kể lại nguyên văn; chỉ cần **He denied taking it.** Mỗi động từ kéo theo một mẫu câu riêng, nên phải học **cả khối**, không học riêng một chữ."),
      ex("She accused him of lying to the whole team.", "Cô ấy buộc tội anh ta đã nói dối cả nhóm.", "Lời gốc có thể là: “You lied to all of us!”. Accuse luôn đi với of, không đi với for hay about."),
      ex("My lawyer warned me not to sign anything until I had read it carefully.", "Luật sư dặn tôi đừng ký gì cho đến khi đọc kỹ.", "Lời khuyên phủ định: warn + người + not to V. Chữ not đứng ngay trước to."),
      ex("The minister denied having received any payment.", "Vị bộ trưởng phủ nhận việc đã nhận bất kỳ khoản tiền nào.", "Having + V3 nhấn mạnh việc đã xảy ra trong quá khứ. Denied receiving cũng đúng và phổ biến hơn trong văn nói."),
      mistake("They accused him for stealing the data.", "They accused him of stealing the data.", "Tiếng Việt nói “buộc tội ai vì…”, nên người Việt tự động dịch “vì” thành for. Nhưng accuse đi với of; còn blame mới đi với for: They blamed him for the leak."),
      mistake("He denied to take the money.", "He denied taking the money.", "Tiếng Việt “chối không lấy” không cho biết động từ sau ở dạng nào, nên nhiều người đoán bừa to V. Deny và admit đi với V-ing (hoặc that + mệnh đề)."),
      mistake("She insisted to pay for dinner.", "She insisted on paying for dinner.", "Dịch từ “khăng khăng đòi trả tiền” dễ sinh ra to V. Insist đi với on + V-ing, hoặc insist that + mệnh đề."),
      ex("He apologised to the customers for keeping them waiting.", "Anh ấy xin lỗi khách hàng vì đã để họ phải chờ.", "Apologise không có tân ngữ trực tiếp: phải nói apologise to someone for something, không nói apologise someone."),
      p("Riêng **suggest** có hai cách dùng ở trình độ cao (mẫu thứ hai chính là thể giả định các bạn vừa học ở chương trước): **suggest + V-ing** (thường người nói cũng tham gia) và **suggest that + chủ ngữ + (should) + động từ nguyên mẫu**. Ở mẫu thứ hai, động từ **không chia** theo chủ ngữ, kể cả khi chủ ngữ là ngôi thứ ba số ít."),
      ex("The consultant suggested that the firm reduce its overheads.", "Chuyên gia tư vấn đề xuất công ty cắt giảm chi phí vận hành.", "Reduce giữ nguyên mẫu dù chủ ngữ là the firm. Có thể viết the firm should reduce."),
      tip("Học động từ tường thuật theo **cặp động từ và giới từ**, đọc to như một chữ: **accuse-of**, **blame-for**, **apologise-for**, **insist-on**, **congratulate-on**. Mẹo nhớ: “buộc tội OF, đổ lỗi FOR, khăng khăng ON”. Còn nhóm **urge, warn, advise, persuade** thì luôn là **người + to V**."),
      teacher("Sau nhiều năm dạy, tôi thấy học viên giỏi ngữ pháp đến đâu thì khi kể chuyện vẫn chỉ dùng **said**. Mỗi tối, các bạn lấy một đoạn hội thoại trong ngày (tin nhắn của sếp, một cảnh cãi nhau trong phim) rồi viết lại bằng **ba động từ tường thuật khác nhau**. Khi chép vào sổ, đừng bao giờ ghi riêng chữ accuse; hãy ghi cả khối **accuse somebody of doing something**. Tự kiểm tra bằng một câu hỏi: “Sau động từ này là to V, V-ing hay giới từ?”. Trả lời được ngay thì mới là thuộc."),
    ],
  },
  words: [
    word("accuse", "/əˈkjuːz/", "buộc tội, cáo buộc", "The opposition accused the mayor of wasting public money.", "ac|cuse", 1, "Âm cuối là /z/, đừng nuốt mất; đọc /əˈkjuːz/, không đọc “ắc-kiu”."),
    word("urge", "/ɜːdʒ/", "thúc giục, kêu gọi mạnh mẽ", "Experts urge parents to limit their children's screen time.", "urge", 0, "Nguyên âm /ɜː/ kéo dài, cuối từ bật rõ âm /dʒ/."),
    word("reiterate", "/riˈɪt.ər.eɪt/", "nhắc lại, khẳng định lại", "The minister reiterated that taxes would not rise.", "re|it|er|ate", 1, "Bốn âm tiết, trọng âm ở âm thứ hai: ri-IT-er-ate. Đừng đọc dính thành “rai-tơ-rết”."),
    word("commend", "/kəˈmend/", "khen ngợi, biểu dương (trang trọng)", "The report commended the staff for their quick response.", "com|mend", 1, "Commend + người + for + danh từ hoặc V-ing, cùng mẫu với thank và praise."),
    word("allegation", "/ˌæl.əˈɡeɪ.ʃən/", "lời cáo buộc (chưa được chứng minh)", "He strongly rejected the allegation of bribery.", "al|le|ga|tion", 2),
    word("reluctant", "/rɪˈlʌk.tənt/", "miễn cưỡng, không muốn", "She was reluctant to admit that she had been wrong.", "re|luc|tant", 1),
    word("negligence", "/ˈneɡ.lɪ.dʒəns/", "sự cẩu thả, tắc trách", "The hospital was blamed for negligence.", "neg|li|gence", 0),
    word("confess", "/kənˈfes/", "thú nhận", "He finally confessed to breaking the vase.", "con|fess", 1, "Confess to + V-ing: to ở đây là giới từ, nên sau nó là V-ing."),
  ],
  exercises: [
    mc("c1-n10-1", "“It was you who leaked the report!” she said. → She accused him ___ the report.", ["to leak", "for leaking", "of leaking", "that he leaked"], 2, "Accuse + người + of + V-ing. Không dùng for, cũng không dùng to V."),
    fill("c1-n10-2", "The manager apologised ___ the misunderstanding.", ["for"], "Apologise for + danh từ hoặc V-ing. Nếu có người thì thêm to: apologised to us for the misunderstanding."),
    mc("c1-n10-3", "Chọn câu đúng.", ["He admitted to steal the money.", "He admitted stealing the money.", "He admitted steal the money.", "He admitted him stealing the money."], 1, "Admit + V-ing (hoặc admit to + V-ing). Không dùng to V hay động từ nguyên mẫu trần."),
    fill("c1-n10-4", "My doctor warned me ___ to eat so much salt.", ["not"], "Lời cảnh báo phủ định: warn + người + not to V."),
    reorder("c1-n10-5", "The teacher urged us to read more widely.", "Urge + người + to V: thúc giục ai làm gì. Trạng từ more widely đứng sau động từ read."),
    reorder("c1-n10-6", "She insisted on seeing the manager.", "Insist on + V-ing: sau giới từ on là V-ing, không dùng to see."),
    listen("c1-n10-7", "The spokesperson denied that the company had misled investors.", ["Người phát ngôn phủ nhận việc công ty đã đánh lừa nhà đầu tư.", "Người phát ngôn thừa nhận công ty đã lừa dối nhà đầu tư.", "Nhà đầu tư cáo buộc người phát ngôn nói dối."], 0, "Deny that + mệnh đề: phủ nhận rằng… Mislead nghĩa là đánh lừa, làm hiểu sai."),
    listen("c1-n10-8", "My colleague suggested that we ask the client for more time.", ["Khách hàng đề nghị chúng tôi làm nhanh hơn.", "Đồng nghiệp tôi đã xin khách hàng thêm thời gian.", "Đồng nghiệp tôi từ chối xin thêm thời gian.", "Đồng nghiệp tôi gợi ý chúng tôi xin khách hàng thêm thời gian."], 3, "Suggest that we ask: gợi ý rằng chúng tôi nên xin. Người đồng nghiệp chưa tự đi xin."),
  ],
  speaking: [
    say("She accused me of taking her seat.", "Cô ấy buộc tội tôi đã chiếm chỗ của cô ấy."),
    say("The doctor urged him to get more sleep.", "Bác sĩ thúc giục anh ấy ngủ nhiều hơn."),
    say("I apologise for keeping you waiting.", "Tôi xin lỗi vì đã để anh chị phải chờ."),
  ],
});
