import { A, B, dialogue, ex, fill, lesson, listen, mc, mistake, p, reorder, say, summary, table, task, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "dong-tu-tuong-thuat",
  title: "Tường thuật tinh tế",
  minutes: 22,
  lecture: {
    title: "Động từ tường thuật và mẫu câu đi kèm",
    blocks: [
      p("Sau một cuộc họp căng thẳng, sếp hỏi bạn: “Vậy khách hàng nói gì?”. Nếu bạn chỉ lặp **he said… she said…**, người nghe không biết ai đang trách ai, ai xin lỗi, ai khăng khăng giữ ý. Người viết giỏi chọn đúng **động từ tường thuật** (accuse, deny, urge, insist…) để kể lại cả **thái độ** của người nói, không cần chép lại từng chữ. Ở cấp B2 bạn đã gặp suggest và tell; bài này đi trọn các mẫu câu khó hơn."),
      table(
        ["Mẫu câu", "Động từ thường gặp", "Ví dụ"],
        ["V + to V", "agree, refuse, offer, promise, threaten", "She refused to sign the contract."],
        ["V + người + to V", "urge, warn, advise, persuade, encourage, remind", "The doctor urged him to stop smoking."],
        ["V + V-ing", "deny, admit, suggest, recommend", "He denied taking the money."],
        ["V + giới từ + V-ing", "insist on, apologise for, confess to, object to", "She insisted on paying the bill."],
        ["V + người + giới từ + V-ing", "accuse sb of, blame sb for, congratulate sb on, thank sb for", "They accused him of lying."],
        ["V + that + mệnh đề", "admit, deny, insist, suggest, explain", "He admitted that he had made a mistake."],
      ),
      p("Nguyên tắc cốt lõi: động từ tường thuật **tóm lại ý định** của người nói. Câu “I didn't take it!” không cần kể lại nguyên văn; chỉ cần **He denied taking it.** Mỗi động từ kéo theo một mẫu câu riêng, nên phải học **cả khối**, không học riêng một chữ."),
      ex("She accused him of lying to the whole team.", "Cô ấy buộc tội anh ta đã nói dối cả nhóm.", "Lời gốc có thể là: “You lied to all of us!”. Accuse luôn đi với of, không đi với for hay about."),
      ex("My lawyer warned me not to sign anything until I had read it carefully.", "Luật sư dặn tôi đừng ký gì cho đến khi đọc kỹ.", "Lời khuyên phủ định: warn + người + not to V. Chữ not đứng ngay trước to."),
      ex("The minister denied having received any payment.", "Vị bộ trưởng phủ nhận việc đã nhận bất kỳ khoản tiền nào.", "Having + V3 nhấn mạnh việc đã xảy ra trong quá khứ. Denied receiving cũng đúng và phổ biến hơn trong văn nói."),
      mistake("They accused him for stealing the data.", "They accused him of stealing the data.", "Tiếng Việt nói “buộc tội ai vì…”, nên người Việt tự động dịch “vì” thành for. Nhưng accuse đi với of; còn blame mới đi với for: They blamed him for the leak."),
      mistake("He denied to take the money.", "He denied taking the money.", "Tiếng Việt “chối không lấy” không cho biết động từ sau ở dạng nào, nên nhiều người đoán bừa to V. Deny và admit đi với V-ing (hoặc that + mệnh đề)."),
      mistake("She insisted to pay for dinner.", "She insisted on paying for dinner.", "Dịch từ “khăng khăng đòi trả tiền” dễ sinh ra to V. Insist đi với on + V-ing, hoặc insist that + mệnh đề."),
      ex("He apologised to the customers for keeping them waiting.", "Anh ấy xin lỗi khách hàng vì đã để họ phải chờ.", "Apologise không có tân ngữ trực tiếp: phải nói apologise to someone for something, không nói apologise someone."),
      p("Riêng **suggest** có hai cách dùng ở trình độ cao (mẫu thứ hai chính là thể giả định các bạn vừa học ở chương trước): **suggest + V-ing** (thường người nói cũng tham gia) và **suggest that + chủ ngữ + (should) + động từ nguyên mẫu**. Ở mẫu thứ hai, động từ **không chia** theo chủ ngữ, kể cả khi chủ ngữ là ngôi thứ ba số ít."),
      ex("The consultant suggested that the firm reduce its overheads.", "Chuyên gia tư vấn đề xuất công ty cắt giảm chi phí vận hành.", "Reduce giữ nguyên mẫu dù chủ ngữ là the firm. Có thể viết the firm should reduce."),
      tip("Học động từ tường thuật theo **cặp động từ và giới từ**, đọc to như một chữ: **accuse-of**, **blame-for**, **apologise-for**, **insist-on**, **congratulate-on**. Mẹo nhớ: “buộc tội OF, đổ lỗi FOR, khăng khăng ON”. Còn nhóm **urge, warn, advise, persuade** thì luôn là **người + to V**."),
      teacher("Sau nhiều năm dạy, tôi thấy học viên giỏi ngữ pháp đến đâu thì khi kể chuyện vẫn chỉ dùng **said**. Mỗi tối, các bạn lấy một đoạn hội thoại trong ngày (tin nhắn của sếp, một cảnh cãi nhau trong phim) rồi viết lại bằng **ba động từ tường thuật khác nhau**. Khi chép vào sổ, đừng bao giờ ghi riêng chữ accuse; hãy ghi cả khối **accuse somebody of doing something**. Tự kiểm tra bằng một câu hỏi: “Sau động từ này là to V, V-ing hay giới từ?”. Trả lời được ngay thì mới là thuộc."),
      summary(
        "Động từ tường thuật kể lại cả **thái độ** người nói (accuse, deny, urge, insist, apologise), không chỉ said.",
        "Học **cả khối mẫu câu**: agree, refuse, offer, promise + to V; urge, warn, advise, persuade + người + to V; deny, admit + V-ing.",
        "Cặp động từ và giới từ + V-ing: **accuse of, blame for, apologise for, insist on, congratulate on, confess to**.",
        "Lời khuyên phủ định: warn someone **not to** V. Apologise **to** someone **for** something.",
        "**Suggest + V-ing**, hoặc suggest that + S + (should) + V nguyên mẫu; không nói suggest someone to V.",
      ),
    ],
  },
  words: [
    word("accuse", "/əˈkjuːz/", "buộc tội, cáo buộc", "The opposition accused the mayor of wasting public money.", "ac|cuse", 1, "Âm cuối là /z/, đừng nuốt mất; đọc /əˈkjuːz/, không đọc “ắc-kiu”."),
    word("urge", "/ɜːdʒ/", "thúc giục, kêu gọi mạnh mẽ", "Experts urge parents to limit their children's screen time.", "urge", 0, "Nguyên âm /ɜː/ kéo dài, cuối từ bật rõ âm /dʒ/."),
    word("reiterate", "/riˈɪt.ər.eɪt/", "nhắc lại, khẳng định lại", "The minister reiterated that taxes would not rise.", "re|it|er|ate", 1, "Bốn âm tiết, trọng âm ở âm thứ hai: ri-IT-er-ate. Đừng đọc dính thành “rai-tơ-rết”."),
    word("commend", "/kəˈmend/", "khen ngợi, biểu dương (trang trọng)", "The report commended the staff for their quick response.", "com|mend", 1, "Commend + người + for + danh từ hoặc V-ing, cùng mẫu với thank và praise."),
    word("allegation", "/ˌæl.əˈɡeɪ.ʃən/", "lời cáo buộc (chưa được chứng minh)", "He strongly rejected the allegation of bribery.", "al|le|ga|tion", 2),
    word("reluctant", "/rɪˈlʌk.tənt/", "miễn cưỡng, không muốn", "She was reluctant to admit that she had been wrong.", "re|luc|tant", 1),
    word("negligence", "/ˈneɡ.lɪ.dʒəns/", "sự cẩu thả, tắc trách", "The hospital was blamed for negligence.", "neg|li|gence", 0),
    word("confess", "/kənˈfes/", "thú nhận", "He finally confessed to breaking the vase.", "con|fess", 1, "Confess to + V-ing: to ở đây là giới từ, nên sau nó là V-ing."),
  ],
  exercises: [
    mc("c1-n10-1", "“It was you who leaked the report!” she said. → She accused him ___ the report.", ["to leak", "for leaking", "of leaking", "that he leaked"], 2, "Accuse + người + of + V-ing. Không dùng for, cũng không dùng to V."),
    fill("c1-n10-2", "The manager apologised ___ the misunderstanding.", ["for"], "Apologise for + danh từ hoặc V-ing. Nếu có người thì thêm to: apologised to us for the misunderstanding."),
    mc("c1-n10-3", "Chọn câu đúng.", ["He admitted to steal the money.", "He admitted stealing the money.", "He admitted steal the money.", "He admitted him stealing the money."], 1, "Admit + V-ing (hoặc admit to + V-ing). Không dùng to V hay động từ nguyên mẫu trần."),
    fill("c1-n10-4", "My doctor warned me ___ to eat so much salt.", ["not"], "Lời cảnh báo phủ định: warn + người + not to V."),
    reorder("c1-n10-5", "The teacher urged us to read more widely.", "Urge + người + to V: thúc giục ai làm gì. Trạng từ more widely đứng sau động từ read."),
    reorder("c1-n10-6", "She insisted on seeing the manager.", "Insist on + V-ing: sau giới từ on là V-ing, không dùng to see."),
    listen("c1-n10-7", "The spokesperson denied that the company had misled investors.", ["Người phát ngôn phủ nhận việc công ty đã đánh lừa nhà đầu tư.", "Người phát ngôn thừa nhận công ty đã lừa dối nhà đầu tư.", "Nhà đầu tư cáo buộc người phát ngôn nói dối."], 0, "Deny that + mệnh đề: phủ nhận rằng… Mislead nghĩa là đánh lừa, làm hiểu sai."),
    listen("c1-n10-8", "My colleague suggested that we ask the client for more time.", ["Khách hàng đề nghị chúng tôi làm nhanh hơn.", "Đồng nghiệp tôi đã xin khách hàng thêm thời gian.", "Đồng nghiệp tôi từ chối xin thêm thời gian.", "Đồng nghiệp tôi gợi ý chúng tôi xin khách hàng thêm thời gian."], 3, "Suggest that we ask: gợi ý rằng chúng tôi nên xin. Người đồng nghiệp chưa tự đi xin."),
  ],
  speaking: [
    say("She accused me of taking her seat.", "Cô ấy buộc tội tôi đã chiếm chỗ của cô ấy."),
    say("The doctor urged him to get more sleep.", "Bác sĩ thúc giục anh ấy ngủ nhiều hơn."),
    say("I apologise for keeping you waiting.", "Tôi xin lỗi vì đã để anh chị phải chờ."),
  ],
  dialogue: dialogue(
    "Báo cáo lại một buổi họp căng thẳng với khách hàng",
    "Chi, quản lý khách hàng của một công ty phần mềm ở TP.HCM, vừa họp xong với một khách hàng Nhật đang không hài lòng vì dự án bị trễ. Chị báo cáo lại cho sếp là anh Quân.",
    { A: "Anh Quân, giám đốc dự án", B: "Chi, quản lý khách hàng" },
    A("So how did the meeting go? Were they still angry?", "Buổi họp thế nào rồi? Họ vẫn còn giận à?"),
    B("At first, yes. Their director accused us of missing the deadline on purpose.", "Lúc đầu thì có. Giám đốc bên họ buộc tội mình cố tình trễ hạn."),
    A("On purpose? That's absurd. What did you say?", "Cố tình ư? Vô lý quá. Em đã nói gì?"),
    B("I denied delaying anything deliberately, but I admitted that our testing had taken too long.", "Em phủ nhận chuyện cố tình trì hoãn, nhưng thừa nhận là khâu kiểm thử của mình đã kéo dài quá lâu."),
    A("Fair enough. Did you apologise?", "Vậy là hợp lý. Em có xin lỗi không?"),
    B("I apologised to them for not keeping them informed. That seemed to calm things down.", "Em xin lỗi họ vì đã không cập nhật tình hình thường xuyên. Có vẻ như vậy làm không khí dịu xuống."),
    A("Good. Did they threaten to cancel the contract?", "Tốt. Họ có dọa hủy hợp đồng không?"),
    B("Not directly, but their lawyer warned us not to miss another deadline.", "Không trực tiếp, nhưng luật sư của họ cảnh báo mình không được trễ hạn thêm lần nào nữa."),
    A("And the new timeline? Did they agree to it?", "Còn tiến độ mới thì sao? Họ có đồng ý không?"),
    B("Eventually. They insisted on receiving weekly progress reports, and they urged us to add more testers.", "Cuối cùng thì có. Họ khăng khăng đòi nhận báo cáo tiến độ hằng tuần, và thúc giục mình bổ sung thêm người kiểm thử."),
    A("That's reasonable. I suggest that you send the first report this Friday.", "Như vậy là hợp lý. Anh đề nghị em gửi bản báo cáo đầu tiên vào thứ sáu này."),
    B("Will do. Oh, and their director congratulated us on the new design, so it wasn't all bad news.", "Em sẽ làm ạ. À, giám đốc bên họ còn khen mình về thiết kế mới, nên cũng không toàn tin xấu."),
  ),
  task: task({
    prompt: "Một đồng nghiệp vắng mặt trong buổi họp căng thẳng với nhà cung cấp hôm qua. Hãy viết email kể lại cho người đó ai đã nói gì và với thái độ ra sao. Không dùng said; hãy chọn đúng động từ tường thuật và mẫu câu đi kèm.",
    hints: [
      "Chọn động từ theo thái độ: accuse, deny, admit, apologise, refuse, warn, agree, insist, urge.",
      "Kiểm tra mẫu câu sau mỗi động từ: to V, người + to V, V-ing hay giới từ + V-ing.",
      "Kể theo trình tự cuộc họp, kết thúc bằng một đề xuất với suggest.",
    ],
    model: "Hi Tuan,\n\nSince you missed yesterday's meeting with the supplier, here is a quick summary. Things started badly. Their sales manager accused us of changing the order at the last minute, but Lan denied making any changes after the deadline and showed him the emails. He then admitted that there had been a mix-up on their side and apologised for causing so much confusion. However, he refused to lower the delivery fee. Lan warned him not to expect a long-term contract under those conditions, and in the end he agreed to split the cost with us. Before we left, he insisted on meeting again next month and urged us to confirm all future orders in writing. I suggest that we reply by Friday so that we don't lose momentum.\n\nBest,\nMai",
    checklist: [
      "Dùng ít nhất năm động từ tường thuật khác nhau và không dùng said.",
      "Mỗi động từ đi đúng mẫu câu (to V, người + to V, V-ing, giới từ + V-ing).",
      "Accuse đi với of, apologise đi với for, insist đi với on.",
      "Có ít nhất một câu phủ định dạng warn hoặc advise + người + not to V.",
      "Người đọc hiểu rõ ai nói gì, với thái độ nào, theo đúng trình tự.",
    ],
    minWords: 100,
  }),
});
