import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "menh-de-quan-he-nang-cao",
  title: "Mệnh đề quan hệ nâng cao",
  minutes: 24,
  lecture: {
    title: "Giới từ + which/whom, whereby, lượng từ + of whom/which",
    blocks: [
      p("Ở cấp B2, bạn đã dùng who, which, that, whose để nối câu. Nhưng khi viết email trang trọng, báo cáo hay bài IELTS Writing, bạn sẽ cần những câu như **the conditions under which staff work** hay **two hundred applicants, most of whom were graduates**. Đây là các dạng mệnh đề quan hệ giúp câu văn gọn, chặt và nghe rất chuyên nghiệp."),
      table(
        ["Cấu trúc", "Văn nói", "Văn trang trọng"],
        ["Giới từ + which", "This is the company I work for.", "This is the company for which I work."],
        ["Giới từ + whom", "The man I spoke to was helpful.", "The man to whom I spoke was helpful."],
        ["in which thay cho where", "the city where I grew up", "the city in which I grew up"],
        ["whereby", "a system where users pay monthly", "a system whereby users pay monthly"],
      ),
      p("Quy tắc: khi đưa giới từ lên trước, chỉ được dùng **which** (cho vật) hoặc **whom** (cho người). **Không bao giờ** dùng that hay who ngay sau giới từ. Giới từ nào thì do động từ hoặc tính từ trong mệnh đề quyết định: rely **on**, responsible **for**, work **under** conditions."),
      ex("The conditions under which the staff work are unacceptable.", "Điều kiện làm việc của nhân viên là không thể chấp nhận được.", "Gốc là: the staff work under these conditions. Giới từ under được đưa lên trước which."),
      ex("She is the colleague on whom I rely most.", "Cô ấy là đồng nghiệp mà tôi dựa vào nhiều nhất.", "Rely on somebody, nên giới từ on đi cùng whom."),
      mistake("The person to who I spoke was very helpful.", "The person to whom I spoke was very helpful.", "Tiếng Việt chỉ có một chữ “mà” dù đứng ở đâu. Tiếng Anh đổi hình thức: đứng sau giới từ thì bắt buộc là whom. Cũng không dùng that sau giới từ: không nói in that I was born."),
      mistake("The hotel in which we stayed in was lovely.", "The hotel in which we stayed was lovely.", "Đã đưa giới từ in lên trước which thì phải bỏ in ở cuối. Người Việt hay đọc lại câu gốc “stay in” và quên xóa giới từ thừa."),
      p("**Whereby** nghĩa là “mà theo đó, nhờ đó”, dùng để mô tả **cách một hệ thống vận hành**. Nó thường đi sau những danh từ như **system, scheme, agreement, arrangement, process**. Whereby rất trang trọng; trong văn nói người ta dùng where hoặc in which."),
      ex("The government introduced a scheme whereby first-time buyers pay lower taxes.", "Chính phủ đưa ra một chương trình mà theo đó người mua nhà lần đầu được đóng thuế thấp hơn."),
      p("Khi muốn nói **một phần** của nhóm người hoặc vật vừa nhắc, ta dùng **lượng từ + of whom** (người) hoặc **lượng từ + of which** (vật). Lượng từ có thể là some, many, most, all, none, both, neither, each, half, one, two… Mệnh đề này luôn đứng **sau dấu phẩy**."),
      table(
        ["Hai câu riêng", "Gộp bằng mệnh đề quan hệ"],
        ["I have three brothers. None of them lives nearby.", "I have three brothers, none of whom lives nearby."],
        ["We received two hundred applications. Most of them were excellent.", "We received two hundred applications, most of which were excellent."],
        ["She wrote four novels. Two of them became films.", "She wrote four novels, two of which became films."],
      ),
      mistake("I invited ten friends, most of them came late.", "I invited ten friends, most of whom came late.", "Tiếng Việt nối hai câu bằng dấu phẩy rất thoải mái, nhưng tiếng Anh coi đó là lỗi nối câu. Hoặc dùng most of whom, hoặc tách thành hai câu: I invited ten friends. Most of them came late."),
      p("**Which** còn có thể thay cho **cả mệnh đề** phía trước, không chỉ một danh từ. Loại này luôn có dấu phẩy phía trước và không dùng that hay what thay được."),
      ex("The train was cancelled, which meant we had to take a taxi.", "Chuyến tàu bị hủy, điều đó có nghĩa là chúng tôi phải đi taxi.", "Which ở đây là “việc tàu bị hủy”. Người Việt hay viết nhầm what meant, vì dịch “điều mà”."),
      tip("Mẹo chọn giới từ: tách mệnh đề ra thành một câu riêng. “I spoke **to** the man” thì viết **to whom**; “I work **for** the company” thì viết **for which**. Còn với lượng từ, hãy thử thay bằng **of them**: nếu “most of them” đúng thì “most of whom/which” cũng đúng."),
      teacher("Sau nhiều năm dạy, tôi thấy học viên thường mắc một trong hai tật: hoặc sợ không dám dùng, hoặc dùng quá tay đến mức câu nào cũng có **to whom**. Mỗi đoạn văn trang trọng chỉ cần **một hai câu** như vậy là đủ tạo ấn tượng. Cách luyện của tôi: mỗi ngày lấy hai câu ngắn trong bài báo, ví dụ “We interviewed ten people. None of them agreed.”, rồi gộp lại bằng **none of whom**. Làm đều một tháng, các bạn sẽ viết được mà không cần nghĩ."),
    ],
  },
  words: [
    word("whereby", "/weəˈbaɪ/", "mà theo đó, nhờ đó (trang trọng)", "We have an arrangement whereby my neighbour feeds the cat when I travel.", "where|by", 1),
    word("respondent", "/rɪˈspɒn.dənt/", "người trả lời khảo sát", "The survey had five hundred respondents, most of whom were under thirty.", "re|spon|dent", 1),
    word("scheme", "/skiːm/", "chương trình, kế hoạch (của tổ chức)", "The company runs a scheme whereby staff can buy shares at a discount.", "scheme", 0, "Chữ ch đọc là /k/: /skiːm/, không đọc “xờ-chim”."),
    word("entitle", "/ɪnˈtaɪ.təl/", "cho quyền, cho phép hưởng", "All employees are entitled to twenty days of paid leave.", "en|ti|tle", 1),
    word("applicant", "/ˈæp.lɪ.kənt/", "người nộp đơn, ứng viên", "We interviewed six applicants, none of whom had enough experience.", "ap|pli|cant", 0),
    word("incentive", "/ɪnˈsen.tɪv/", "sự khuyến khích, động lực", "Lower taxes are an incentive for companies to invest.", "in|cen|tive", 1),
    word("framework", "/ˈfreɪm.wɜːk/", "khuôn khổ, khung", "This is the framework within which all decisions are made.", "frame|work", 0),
    word("participant", "/pɑːˈtɪs.ɪ.pənt/", "người tham gia", "The participants, all of whom were volunteers, completed the test.", "par|tic|i|pant", 1),
  ],
  exercises: [
    mc("c1-n12-1", "The manager ___ I reported the problem was very understanding.", ["to who", "to whom", "to that", "whom to"], 1, "Report something to somebody, nên giới từ to đứng trước whom. Sau giới từ không dùng who hay that."),
    fill("c1-n12-2", "I have two sisters, both of ___ work as nurses.", ["whom"], "Both of whom: cả hai người trong số đó. Chỉ người nên dùng whom."),
    mc("c1-n12-3", "Chọn câu đúng.", ["The project on which we worked on was a success.", "The project on that we worked was a success.", "The project which we worked was a success.", "The project on which we worked was a success."], 3, "Work on a project: đưa on lên trước which và bỏ on ở cuối câu."),
    fill("c1-n12-4", "The bank introduced a system ___ customers can pay by phone. (mà theo đó, một từ)", ["whereby", "where"], "Whereby là cách viết trang trọng nhất; where cũng đúng nhưng mang tính văn nói hơn."),
    reorder("c1-n12-5", "They agreed on a plan whereby profits are shared.", "Whereby đứng sau danh từ plan và mở ra một mệnh đề đầy đủ: profits are shared."),
    reorder("c1-n12-6", "I have three cousins, none of whom lives nearby.", "Lượng từ none + of whom, đứng sau dấu phẩy, bổ sung thông tin về three cousins. Trong văn trang trọng, none đi với động từ số ít: lives."),
    listen("c1-n12-7", "We interviewed twenty candidates, none of whom had the right experience.", ["Không ai trong số hai mươi ứng viên được phỏng vấn có kinh nghiệm phù hợp.", "Cả hai mươi ứng viên đều có kinh nghiệm phù hợp.", "Chúng tôi chưa phỏng vấn ứng viên nào."], 0, "None of whom: không ai trong số họ."),
    listen("c1-n12-8", "He apologised in front of everyone, which I didn't expect.", ["Anh ấy không xin lỗi, đúng như tôi dự đoán.", "Anh ấy muốn tôi xin lỗi trước mặt mọi người.", "Tôi đã không ngờ anh ấy lại xin lỗi trước mặt mọi người."], 2, "Which thay cho cả mệnh đề trước: việc anh ấy xin lỗi trước mặt mọi người."),
  ],
  speaking: [
    say("She is the person on whom I rely most.", "Cô ấy là người mà tôi dựa vào nhiều nhất."),
    say("I bought three books, none of which I have read yet.", "Tôi đã mua ba cuốn sách, chưa đọc cuốn nào cả."),
    say("The meeting ran late, which meant I missed my bus.", "Cuộc họp kéo dài, vì thế tôi lỡ chuyến xe buýt."),
  ],
});
