import { ex, fill, lesson, listen, mc, mistake, p, reorder, say, table, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "trang-tu-binh-luan",
  title: "Trạng từ bình luận",
  minutes: 20,
  lecture: {
    title: "Nói ra thái độ chỉ bằng một trạng từ",
    blocks: [
      p("Người Việt khi nói tiếng Anh hay mở đầu câu nào cũng bằng **I think** hoặc **Maybe**. Người bản xứ thì gói thái độ của mình vào **một trạng từ** đứng đầu câu: **Frankly**, **Admittedly**, **Presumably**. Những trạng từ này không bổ nghĩa cho động từ, mà **bình luận cả câu**: người nói chắc chắn đến đâu, đang thừa nhận, đang đoán, hay đang nói thẳng."),
      table(
        ["Trạng từ", "Thái độ người nói", "Ví dụ"],
        ["undoubtedly, clearly, certainly", "rất chắc chắn", "Undoubtedly, this is her best novel."],
        ["arguably", "có cơ sở để khẳng định, dù có thể có người không đồng ý", "He is arguably the best player of his generation."],
        ["presumably", "đoán dựa trên logic", "Presumably, the meeting has been cancelled."],
        ["seemingly, apparently", "có vẻ như (theo bề ngoài hoặc nghe nói)", "The seemingly simple task took hours."],
        ["admittedly", "phải thừa nhận (nhượng bộ)", "Admittedly, the price is high."],
        ["frankly, honestly", "nói thẳng, thật lòng", "Frankly, I don't think it will work."],
      ),
      p("Về vị trí: phổ biến nhất là **đầu câu, có dấu phẩy**. Có thể đặt **giữa câu**, sau be hoặc trợ động từ và trước động từ chính: **He has undoubtedly improved.** Đặt **cuối câu** thì chủ yếu trong văn nói, như một lời nói thêm: **It was a mistake, frankly.** Một số trạng từ như seemingly và arguably còn đứng ngay trước tính từ hoặc cụm danh từ."),
      ex("Arguably, the internet has changed education more than any other invention.", "Có thể nói internet đã thay đổi giáo dục nhiều hơn bất kỳ phát minh nào khác.", "Arguably nghĩa là “có lý do để nói rằng”, một lời khẳng định mạnh nhưng khiêm tốn."),
      mistake("This is an arguably topic.", "This is a controversial topic.", "Thấy argue là “tranh cãi”, nhiều người Việt tưởng arguably là “gây tranh cãi”. Thực ra arguably là trạng từ, nghĩa là “có thể nói là”, và không dùng như tính từ. Muốn nói gây tranh cãi thì dùng controversial."),
      ex("Presumably, you've already heard the news.", "Chắc là anh chị đã nghe tin rồi.", "Presumably: tôi đoán vậy vì có lý do hợp lý, gần với I assume."),
      ex("The seemingly endless meeting finally ended at seven.", "Cuộc họp tưởng như dài vô tận rốt cuộc cũng kết thúc lúc bảy giờ.", "Seemingly đứng trước tính từ endless. Nó ngầm nói rằng bề ngoài là vậy, thực tế có thể khác."),
      mistake("Undoubtedly that he is the best candidate.", "Undoubtedly, he is the best candidate.", "Tiếng Việt nói “Chắc chắn rằng…”, nên người Việt hay thêm that sau trạng từ. Trạng từ bình luận không đi với that. Nếu muốn dùng that thì đổi cấu trúc: There is no doubt that he is the best candidate."),
      p("Trạng từ bình luận chia làm hai nhóm đối lập. Nhóm **rào đón** (hedging) làm lời nói mềm và thận trọng: **seemingly, apparently, presumably, arguably**. Nhóm **nhấn mạnh** (boosting) làm lời nói mạnh và dứt khoát: **undoubtedly, clearly, certainly, definitely**. Trong bài luận học thuật, chọn đúng nhóm cho thấy bạn biết **mức độ chắc chắn** của bằng chứng."),
      table(
        ["Mức độ chắc chắn", "Trạng từ", "Ví dụ"],
        ["Rất chắc", "undoubtedly, clearly", "The policy has clearly failed."],
        ["Khá chắc, có lập luận", "arguably", "The policy has arguably failed."],
        ["Đoán dựa vào logic", "presumably", "The policy has presumably been reviewed."],
        ["Chỉ theo bề ngoài", "seemingly, apparently", "The policy has seemingly worked."],
      ),
      mistake("Undoubtedly, it might possibly be true.", "It might be true. / It is undoubtedly true.", "Trộn trạng từ nhấn mạnh với từ rào đón khiến câu tự mâu thuẫn. Chọn một thái độ: chắc chắn hoặc thận trọng, không vừa chắc vừa ngờ."),
      ex("Admittedly, the new system is expensive, but it will undoubtedly save us time.", "Phải thừa nhận là hệ thống mới đắt, nhưng chắc chắn nó sẽ giúp chúng ta tiết kiệm thời gian.", "Admittedly nhượng bộ trước, undoubtedly nhấn mạnh lập trường sau. Đây là cặp rất hữu ích khi thuyết phục."),
      p("Chú ý **giọng điệu**: **frankly** và **honestly** báo hiệu sắp có một lời nói thẳng, thường là lời chê. Nói với khách hàng hay cấp trên, câu mở đầu bằng Frankly có thể nghe gay gắt. Muốn nhẹ hơn, dùng **To be honest** hoặc thêm từ làm mềm: **Frankly, I'm not sure it's the best option.**"),
      tip("Phát âm: **undoubtedly** có chữ b câm, đọc /ʌnˈdaʊ.tɪd.li/. **Presumably** đọc /prɪˈzjuː.mə.bli/, chữ s đọc là /z/. Khi trạng từ đứng đầu câu, hãy **ngắt nhẹ** sau nó, đúng chỗ dấu phẩy, để người nghe nhận ra đó là lời bình luận."),
      teacher("Sau năm mươi năm dạy, tôi nhận ra một điều: trò nào bỏ được thói quen **I think** ở đầu mỗi câu thì tiếng Anh nghe lên hẳn một bậc. Các em hãy tự đặt luật: mỗi ngày viết năm câu nhận xét về tin tức hoặc công việc, mỗi câu mở đầu bằng **một trạng từ khác nhau** trong bài này. Rồi tự hỏi: “Mình đang chắc chắn, đang đoán hay đang thừa nhận?”. Trả lời được câu đó thì chọn trạng từ sẽ không bao giờ sai."),
    ],
  },
  words: [
    word("arguably", "/ˈɑːɡ.ju.ə.bli/", "có thể nói là, có cơ sở để cho rằng", "She is arguably the most talented designer in the company.", "ar|gu|a|bly", 0, "Trọng âm ở âm đầu: AR-gu-a-bly. Không liên quan đến nghĩa “gây tranh cãi”."),
    word("presumably", "/prɪˈzjuː.mə.bli/", "chắc là, có lẽ là (đoán có cơ sở)", "Presumably, the price includes breakfast.", "pre|sum|a|bly", 1, "Chữ s đọc là /z/: pri-ZYOO-ma-bly."),
    word("seemingly", "/ˈsiː.mɪŋ.li/", "có vẻ như, tưởng như", "They solved a seemingly impossible problem.", "seem|ing|ly", 0),
    word("undoubtedly", "/ʌnˈdaʊ.tɪd.li/", "chắc chắn, không còn nghi ngờ gì", "This is undoubtedly the best solution we have.", "un|doubt|ed|ly", 1, "Chữ b câm, giống trong doubt /daʊt/."),
    word("frankly", "/ˈfræŋ.kli/", "nói thẳng ra, thật lòng mà nói", "Frankly, the service was disappointing.", "frank|ly", 0),
    word("supposedly", "/səˈpəʊ.zɪd.li/", "nghe nói là, được cho là (nhưng có thể không đúng)", "The hotel is supposedly the best in town, but our room was tiny.", "sup|pos|ed|ly", 1, "Đọc đủ bốn âm tiết, đuôi ed đọc là /ɪd/. Tránh nói supposably."),
    word("stance", "/stɑːns/", "lập trường, quan điểm", "The company has taken a firm stance on climate change.", "stance", 0),
    word("ostensibly", "/ɒsˈten.sə.bli/", "bề ngoài là, trên danh nghĩa là (thực chất có thể khác)", "The trip was ostensibly for business, but he spent most of it on the beach.", "os|ten|si|bly", 1, "Trọng âm ở âm tiết thứ hai: os-TEN-si-bly."),
  ],
  exercises: [
    mc("c1-n15-1", "Bạn đoán (dựa vào logic) rằng đồng nghiệp đã nhận được email của mình. Bạn nói: “___, you've received my email.”", ["Frankly", "Presumably", "Undoubtedly", "Admittedly"], 1, "Presumably dùng khi đoán có cơ sở. Undoubtedly quá chắc chắn; Frankly và Admittedly không hợp nghĩa."),
    fill("c1-n15-2", "He is ___ the greatest footballer of his generation, though some would disagree. (có thể nói là)", ["arguably"], "Arguably: khẳng định mạnh nhưng thừa nhận có người không đồng ý, hợp với vế though some would disagree."),
    mc("c1-n15-3", "Câu nào vừa thừa nhận điểm yếu vừa giữ vững lập trường?", ["Frankly, the course is expensive, so nobody should take it.", "Presumably, the course is expensive.", "Admittedly, the course is expensive, but it is worth every penny.", "Seemingly, the course is worth every penny."], 2, "Admittedly nhượng bộ (thừa nhận giá cao), rồi but đưa ra lập trường (vẫn đáng đồng tiền)."),
    fill("c1-n15-4", "The ___ simple question turned out to be very difficult. (có vẻ như, tưởng như)", ["seemingly", "apparently", "deceptively"], "Seemingly (hoặc deceptively: đơn giản một cách đánh lừa) đứng trước tính từ simple: bề ngoài tưởng đơn giản, thực tế lại khó."),
    reorder("c1-n15-5", "They faced a seemingly impossible task.", "Seemingly đứng ngay trước tính từ impossible. Mạo từ a đi với seemingly vì từ này bắt đầu bằng phụ âm."),
    reorder("c1-n15-6", "It was an admittedly risky decision.", "Admittedly đứng trước tính từ risky; an đứng trước admittedly vì từ này bắt đầu bằng nguyên âm."),
    listen("c1-n15-7", "Frankly, I don't think this plan will work.", ["Nói thẳng là tôi không nghĩ kế hoạch này sẽ hiệu quả.", "Tôi tin kế hoạch này chắc chắn sẽ thành công.", "Có vẻ như kế hoạch này đã được thực hiện."], 0, "Frankly báo hiệu một lời nói thẳng, ở đây là lời nghi ngờ."),
    listen("c1-n15-8", "The shop is supposedly open until ten, but it was already closed.", ["Cửa hàng mở đến mười giờ và lúc đó vẫn còn mở.", "Cửa hàng đóng cửa lúc mười giờ như thường lệ.", "Cửa hàng không bao giờ mở cửa buổi tối.", "Nghe nói cửa hàng mở đến mười giờ, vậy mà lúc đó đã đóng rồi."], 3, "Supposedly: được cho là như vậy, nhưng thực tế lại khác."),
  ],
  speaking: [
    say("Frankly, I think we need more time.", "Nói thẳng là tôi nghĩ chúng ta cần thêm thời gian."),
    say("Presumably, the train will be late again.", "Chắc là tàu lại đến muộn nữa rồi."),
    say("It is arguably the best café in town.", "Có thể nói đó là quán cà phê ngon nhất thị trấn."),
  ],
});
