import { A, B, dialogue, ex, fill, lesson, listen, mc, mistake, p, reorder, say, summary, table, task, teacher, tip, word } from "../../builders";

export default lesson({
  slug: "viet-luan-va-tom-tat",
  title: "Viết luận và tóm tắt",
  minutes: 24,
  lecture: {
    title: "Diễn đạt lại, tóm tắt và bố cục bài luận",
    blocks: [
      p("Trong IELTS Writing, giám khảo trừ điểm khi bạn chép lại nguyên câu đề bài. Ở trường đại học nước ngoài, chép nguyên câu của người khác mà không ghi nguồn bị coi là **đạo văn** (plagiarism), có thể bị đánh trượt cả môn. Còn ở công ty, sếp cần bạn **tóm tắt** một báo cáo hai mươi trang thành vài dòng. Cả ba tình huống đều đòi hỏi một kỹ năng: nói lại ý của người khác **bằng lời của mình**."),
      p("Có ba kỹ thuật **diễn đạt lại** (paraphrase): **đổi từ đồng nghĩa**, **đổi từ loại** (động từ thành danh từ, tính từ thành trạng từ…) và **đổi cấu trúc câu** (chủ động sang bị động, mệnh đề sang cụm danh từ). Một câu diễn đạt lại tốt thường kết hợp **ít nhất hai** kỹ thuật, và phải giữ **nguyên ý** của câu gốc."),
      table(
        ["Kỹ thuật", "Câu gốc", "Câu diễn đạt lại"],
        ["Từ đồng nghĩa", "Many people are worried about rising house prices.", "A large number of people are concerned about increasing property prices."],
        ["Đổi từ loại", "The population grew rapidly.", "There was rapid growth in the population."],
        ["Chủ động sang bị động", "The government should fund public transport.", "Public transport should be funded by the government."],
        ["Mệnh đề sang cụm danh từ", "Because it rained heavily, the match was cancelled.", "Heavy rain led to the cancellation of the match."],
      ),
      ex("Daily reading is associated with better academic performance among children.", "Việc đọc sách hằng ngày gắn liền với kết quả học tập tốt hơn ở trẻ em.", "Câu gốc: Children who read every day tend to do better at school. Đã đổi từ loại (read thành reading), đổi từ (do better at school thành academic performance) và đổi cấu trúc câu."),
      mistake("The government should grab powerful measures.", "The government should take firm action.", "Tra từ điển Anh-Việt rồi thay từ đồng nghĩa một cách máy móc sẽ phá vỡ kết hợp từ. Tiếng Anh nói take action, take measures; không ai nói grab measures."),
      mistake("Scientists have proved that coffee is harmful.", "Some researchers believe that coffee may have negative effects on health.", "Câu gốc là Some scientists believe coffee may be harmful. Khi diễn đạt lại, người Việt hay “chốt” ý cho mạnh, biến có thể thành đã chứng minh. Paraphrase phải giữ đúng mức độ chắc chắn và phạm vi (some, may) của câu gốc."),
      p("**Tóm tắt** (summarise) khác diễn đạt lại ở chỗ bạn phải **rút ngắn**. Các bước: đọc hết đoạn gốc, gạch chân **ý chính**, bỏ ví dụ, số liệu phụ và chi tiết lặp lại, rồi viết lại bằng lời của mình, dài khoảng **một phần ba** bản gốc. Bản tóm tắt **không thêm ý kiến cá nhân**. Cụm mở đầu hay dùng: **The article argues that…**, **According to the author,…**, **The report concludes that…**"),
      ex("The author argues that remote work improves productivity but may weaken team relationships.", "Tác giả lập luận rằng làm việc từ xa giúp tăng năng suất nhưng có thể làm suy giảm quan hệ trong nhóm.", "Một bài báo dài được tóm trong một câu: động từ tường thuật, ý chính, và ý phụ quan trọng nhất."),
      p("Một bài luận chuẩn có ba phần. **Mở bài**: giới thiệu bối cảnh và nêu **thesis statement** (câu luận điểm, lập trường của cả bài). **Thân bài**: mỗi đoạn một ý, mở đầu bằng **topic sentence** (câu chủ đề), sau đó giải thích và đưa ví dụ. **Kết bài**: nhắc lại luận điểm **bằng từ khác** và tóm lại các ý chính."),
      table(
        ["Thành phần", "Chức năng", "Câu mẫu"],
        ["Thesis statement", "Nêu lập trường của cả bài", "This essay argues that cities should invest more in public transport."],
        ["Topic sentence", "Nêu ý chính của một đoạn thân bài", "The main advantage of public transport is that it reduces congestion."],
        ["Conclusion", "Khẳng định lại lập trường, tóm các ý", "In conclusion, public transport deserves greater investment because it benefits both people and the environment."],
      ),
      ex("One major drawback of fast fashion is the damage it causes to the environment.", "Một nhược điểm lớn của thời trang nhanh là tác hại nó gây ra cho môi trường.", "Topic sentence tốt nêu rõ ý chính và đủ cụ thể để người đọc đoán được cả đoạn sẽ nói về điều gì."),
      mistake("In conclusion, public transport is good. Another benefit is that it creates jobs.", "In conclusion, public transport reduces congestion and pollution, so it deserves greater investment.", "Văn nghị luận tiếng Việt quen “mở rộng vấn đề” ở kết bài, nên nhiều bạn đưa thêm ý mới vào đoạn cuối. Bài luận tiếng Anh không làm vậy: kết bài chỉ khẳng định lại và tóm tắt, không thêm lập luận mới."),
      p("Bài luận C1 còn phải **liền mạch** giữa các câu (cohesion). Ngoài từ nối đã học ở B2, hãy dùng **this / these + danh từ tóm ý** để gói cả câu trước thành một chủ ngữ mới: House prices rose by thirty per cent last year. **This increase** has pushed many young families out of the city. Kết hợp với phép thay thế (do so, one) của bài Nói gọn mà không mất ý và danh từ hóa của bài Văn phong học thuật, bài viết sẽ vừa chặt vừa không lặp từ."),
      p("Để **tránh đạo văn**: khi giữ nguyên câu chữ của tác giả, đặt trong **ngoặc kép** và ghi nguồn; khi diễn đạt lại, vẫn phải **ghi nguồn** (According to Smith…). Chỉ đổi vài từ mà giữ nguyên khung câu gốc (người ta gọi là **patchwriting**) vẫn bị coi là đạo văn."),
      tip("Mẹo **gập sách**: đọc đoạn gốc hai lần, rồi gập sách hoặc tắt màn hình, viết lại theo trí nhớ. Sau đó mở ra so sánh. Nếu thấy một chuỗi **ba bốn từ liền nhau** giống hệt bản gốc (trừ thuật ngữ chuyên môn), hãy viết lại chỗ đó."),
      teacher("Sau nhiều năm dạy, tôi thấy người Việt không thiếu ý, mà thiếu **thói quen viết lại**. Mỗi tuần, các bạn chọn một bài báo tiếng Anh ngắn, tóm nó trong **đúng ba câu**: một câu nêu ý chính, hai câu nêu hai ý phụ. Rồi viết lại câu tiêu đề theo **hai cách khác nhau**. Tự kiểm tra bằng câu hỏi: “Nếu tác giả đọc bản của mình, họ có thấy ý mình bị bóp méo không?”. Viết đủ mười tuần, các bạn sẽ thấy bài luận của mình gọn và chắc hơn rất nhiều."),
      summary(
        "Diễn đạt lại bằng cách kết hợp **ít nhất hai** kỹ thuật (từ đồng nghĩa, đổi từ loại, đổi cấu trúc câu) và giữ nguyên ý, nguyên mức độ chắc chắn của câu gốc.",
        "Thay từ đồng nghĩa phải giữ đúng **kết hợp từ**: take action, take measures; không có grab measures.",
        "Bản tóm tắt dài khoảng **một phần ba** bản gốc, bỏ ví dụ và số liệu phụ, **không thêm ý kiến cá nhân**.",
        "Bố cục: mở bài có **thesis statement**, mỗi đoạn thân bài có một **topic sentence**, kết bài **không thêm ý mới**.",
        "Tránh đạo văn: giữ nguyên câu chữ thì dùng ngoặc kép và ghi nguồn; diễn đạt lại vẫn phải ghi nguồn.",
      ),
    ],
  },
  words: [
    word("paraphrase", "/ˈpær.ə.freɪz/", "diễn đạt lại (bằng lời của mình)", "Try to paraphrase the question in your introduction.", "par|a|phrase", 0, "Trọng âm ở âm đầu: PAR-a-phrase; ph đọc là /f/."),
    word("summarise", "/ˈsʌm.ər.aɪz/", "tóm tắt", "Can you summarise the report in one paragraph?", "sum|ma|rise", 0, "Tiếng Anh-Mỹ viết summarize."),
    word("plagiarise", "/ˈpleɪ.dʒər.aɪz/", "đạo văn", "Students who plagiarise may fail the course.", "pla|gia|rise", 0, "Chữ g đọc là /dʒ/: PLAY-jer-ize. Danh từ là plagiarism."),
    word("thesis", "/ˈθiː.sɪs/", "luận điểm; luận văn", "Your thesis should be clear from the first paragraph.", "the|sis", 0, "Âm /θ/ đặt lưỡi giữa hai hàm răng, không đọc “thi-sít”. Số nhiều là theses."),
    word("coherent", "/kəʊˈhɪə.rənt/", "mạch lạc, chặt chẽ", "Each paragraph should present a coherent argument.", "co|her|ent", 1),
    word("outline", "/ˈaʊt.laɪn/", "dàn ý; phác thảo", "Write a brief outline before you start your essay.", "out|line", 0, "Danh từ và động từ đều nhấn âm đầu: OUT-line."),
    word("synonym", "/ˈsɪn.ə.nɪm/", "từ đồng nghĩa", "Increase is a useful synonym for rise.", "syn|o|nym", 0),
    word("cite", "/saɪt/", "trích dẫn, dẫn nguồn", "Always cite your sources in academic writing.", "cite", 0, "Đọc giống hệt site và sight: /saɪt/."),
  ],
  exercises: [
    mc("c1-n16-1", "Câu nào diễn đạt lại tốt nhất: Many young people cannot afford to buy a house.", ["Many young people cannot afford to buy a home.", "A large number of young adults are unable to purchase property.", "Young people do not want to buy houses.", "All young people are too poor to buy a house."], 1, "Đổi từ và cấu trúc nhưng giữ nguyên ý. Phương án A chỉ đổi một từ; C đổi nghĩa; D phóng đại thành all."),
    fill("c1-n16-2", "The economy grew slowly. → There was slow economic ___.", ["growth"], "Đổi từ loại: động từ grow thành danh từ growth, trạng từ slowly thành tính từ slow."),
    mc("c1-n16-3", "Câu nào phù hợp nhất để làm thesis statement?", ["Technology is a very interesting topic.", "In this essay, I will talk about some things.", "Some people like social media and some do not.", "This essay argues that social media does more harm than good to teenagers."], 3, "Thesis statement phải nêu rõ lập trường có thể tranh luận được. Các câu còn lại quá chung chung."),
    fill("c1-n16-4", "If you use someone else's exact words, you must ___ the source. (trích dẫn, ghi nguồn)", ["cite", "acknowledge", "credit", "reference"], "Cite the source: ghi nguồn. Đồng thời phải đặt câu trích trong ngoặc kép."),
    reorder("c1-n16-5", "The article argues that tourism harms local communities.", "Cụm mở đầu bản tóm tắt: The article argues that + mệnh đề."),
    reorder("c1-n16-6", "Each paragraph should begin with a topic sentence.", "Mỗi đoạn thân bài mở đầu bằng một câu chủ đề nêu ý chính."),
    listen("c1-n16-7", "In summary, the report finds that online learning works best when combined with classroom teaching.", ["Báo cáo kết luận rằng học trực tuyến nên thay thế hoàn toàn học trên lớp.", "Báo cáo cho thấy học trên lớp không còn hiệu quả.", "Tóm lại, báo cáo cho thấy học trực tuyến hiệu quả nhất khi kết hợp với dạy trên lớp."], 2, "In summary: tóm lại. Combined with: kết hợp với."),
    listen("c1-n16-8", "Rents rose sharply last year. This increase has hit young families hardest.", ["Tiền thuê nhà tăng mạnh năm ngoái, và mức tăng này ảnh hưởng nặng nhất đến các gia đình trẻ.", "Tiền thuê nhà tăng mạnh nên các gia đình trẻ chuyển về quê.", "Các gia đình trẻ đã làm tiền thuê nhà tăng mạnh.", "Tiền thuê nhà năm nay sẽ tăng mạnh hơn năm ngoái."], 0, "This increase là danh từ tóm ý, gói lại cả câu trước (tiền thuê nhà tăng mạnh) để câu sau nối liền mạch mà không lặp lại."),
  ],
  speaking: [
    say("This essay argues that cities should invest more in public transport.", "Bài luận này lập luận rằng các thành phố nên đầu tư nhiều hơn vào giao thông công cộng."),
    say("In other words, the problem is not money but time.", "Nói cách khác, vấn đề không phải là tiền mà là thời gian."),
    say("According to the author, reading every day improves concentration.", "Theo tác giả, đọc sách mỗi ngày giúp cải thiện khả năng tập trung."),
  ],
  dialogue: dialogue(
    "Buổi góp ý bài luận với giảng viên",
    "Nam, học viên cao học người Việt tại một trường đại học ở Anh, gặp giảng viên hướng dẫn là tiến sĩ Evans để nhận góp ý cho bản nháp bài luận đầu tiên.",
    { A: "Tiến sĩ Evans, giảng viên", B: "Nam, học viên cao học" },
    A("Nam, I've read your draft. Your ideas are strong, but your introduction copies the question almost word for word.", "Nam, tôi đã đọc bản nháp của em. Ý tưởng rất tốt, nhưng mở bài gần như chép lại nguyên văn đề bài."),
    B("I see. How should I paraphrase it?", "Em hiểu rồi. Em nên diễn đạt lại thế nào ạ?"),
    A("Combine techniques: change the words and, ideally, the structure too. The question says: cities are growing rapidly. What could you write?", "Hãy kết hợp các kỹ thuật: đổi từ, và tốt nhất là đổi cả cấu trúc câu. Đề bài viết: các thành phố đang phát triển nhanh. Em có thể viết thế nào?"),
    B("Perhaps: urban areas are experiencing rapid growth.", "Có lẽ là: các khu vực đô thị đang tăng trưởng nhanh chóng."),
    A("Much better. You've changed the words, the word class and the structure. Now, where's your thesis statement?", "Tốt hơn nhiều. Em đã đổi từ loại và cấu trúc. Giờ thì câu luận điểm của em nằm ở đâu?"),
    B("I think it's at the end of the second paragraph.", "Em nghĩ nó ở cuối đoạn thứ hai ạ."),
    A("Move it to the introduction. The reader should know your position from the very start.", "Hãy chuyển nó lên mở bài. Người đọc cần biết lập trường của em ngay từ đầu."),
    B("Understood. What about my summary of the Smith article? Is it too long?", "Em hiểu rồi. Còn phần tóm tắt bài báo của Smith thì sao ạ? Có quá dài không?"),
    A("It's almost as long as the original. Keep the main argument, drop the examples, and aim for about a third of the length.", "Nó dài gần bằng bản gốc. Giữ lập luận chính, bỏ các ví dụ, và cố gắng rút xuống khoảng một phần ba."),
    B("And I shouldn't add my own opinion there, should I?", "Và em không nên đưa ý kiến riêng vào phần đó, đúng không ạ?"),
    A("Exactly. Save your views for the body paragraphs. One more thing: your conclusion introduces a new argument.", "Chính xác. Để dành quan điểm của em cho phần thân bài. Còn một điều nữa: kết bài của em lại đưa ra một lập luận mới."),
    B("So the conclusion should only restate my thesis and summarise the main points. I'll revise it tonight.", "Vậy kết bài chỉ nên khẳng định lại luận điểm và tóm tắt các ý chính. Tối nay em sẽ sửa lại ạ."),
  ),
  task: task({
    prompt: "Viết đoạn mở bài và một đoạn thân bài cho đề: Some people believe that working from home is better for employees than working in an office. To what extent do you agree? Chú ý diễn đạt lại đề bài, không chép nguyên văn.",
    hints: [
      "Câu đầu mở bài diễn đạt lại đề bằng ít nhất hai kỹ thuật: đổi từ, đổi từ loại, đổi cấu trúc.",
      "Câu cuối mở bài là thesis statement nêu rõ lập trường của bạn.",
      "Đoạn thân bài mở bằng topic sentence, sau đó giải thích và đưa ví dụ; nếu dùng số liệu thì ghi nguồn.",
      "Dùng this hoặc these + danh từ (this trend, this drawback) để nối các câu.",
    ],
    model: "In recent years, a growing number of companies have allowed their staff to work remotely. While some argue that this arrangement benefits employees more than traditional office work, this essay argues that its advantages are real but often exaggerated, and that a hybrid model is the most effective option.\n\nThe main weakness of full-time remote work is the damage it can do to relationships within a team. According to a recent survey of two thousand office workers, more than half of those who worked entirely from home felt isolated from their colleagues. This sense of isolation matters because informal conversations, such as a quick chat after a meeting, are often where problems are solved and trust is built. Video calls can replace formal meetings, but they rarely create these spontaneous moments. This drawback suggests that the office still plays an essential role, and that employees benefit most when they can divide their week between home and the workplace.",
    checklist: [
      "Câu mở bài diễn đạt lại đề bài, không có chuỗi ba bốn từ liền nhau chép từ đề.",
      "Cuối mở bài có thesis statement nêu rõ lập trường.",
      "Đoạn thân bài mở đầu bằng một topic sentence rõ ràng, chỉ nói một ý chính.",
      "Có ít nhất một cụm this hoặc these + danh từ tóm ý để nối câu.",
      "Số liệu hay ý của người khác đều có ghi nguồn (According to...).",
    ],
    minWords: 110,
  }),
});
