import { correct, fill, listenQ, mc, reorder } from "../builders";
import type { Exercise } from "../types";

/** Extra final-test items for Tiếng Anh B2, 10 per chapter (two of each kind), drawn at random with the original bank. */
export const FINAL_EXTRA_TIENG_ANH_B2: Exercise[][] = [
  // Chapter 1: email, meetings, reported speech, calls and online meetings, perfect continuous tenses
  [
    mc("b2-f21", "“Have you sent the invoice to Mr Weber?” My manager asked me ___.", ["did I send the invoice to Mr Weber", "had I sent the invoice to Mr Weber", "if I had sent the invoice to Mr Weber", "if had I sent the invoice to Mr Weber"], 2, "Tường thuật câu hỏi Yes/No: asked + if/whether + trật tự câu kể (chủ ngữ trước động từ), và have sent lùi thành had sent."),
    mc("b2-f22", "By the time the conference ends on Friday, our team ___ on the event for six months.", ["will be working", "will have been working", "has been working", "had been working"], 1, "Thời lượng (for six months) tính đến một mốc trong tương lai (By the time the conference ends) dùng will have been + V-ing."),
    fill("b2-f23", "“Please don't forward this email to the client.” Lan told me ___ forward the email to the client. (bảo đừng)", ["not to"], "Tường thuật lời dặn đừng làm gì: told + người + not to V."),
    fill("b2-f24", "Mr Brown hasn't joined the call yet. He ___ have lost the link, but I'm not sure. (có thể đã)", ["might", "may", "could"], "Might / may / could have + V3: có thể đã xảy ra nhưng chưa chắc. Người nói không chắc nên không dùng must have."),
    reorder("b2-f25", "Could you tell me when the client will be arriving?", "Sau Could you tell me là trật tự câu kể: when the client will be arriving, không đảo will lên trước chủ ngữ. Will be + V-ing hỏi về việc đã sắp xếp sẵn."),
    reorder("b2-f26", "The supplier promised to replace the damaged boxes.", "Promise + to V: tường thuật một lời hứa gọn trong một câu, thay cho He said: We will replace them."),
    listenQ("b2-f27", "Anh Nam nhờ người nghe làm gì?", "Hi, it's Nam from the sales team. Sorry, you're breaking up a lot. Could you call me back on my office number? It's extension two one eight.", ["Nói to hơn một chút", "Gửi cho anh một tin nhắn thoại", "Tắt mic khi không nói", "Gọi lại cho anh vào số máy lẻ hai một tám ở văn phòng"], 3, "Could you call me back… It's extension two one eight: nhờ gọi lại vào số máy lẻ. You're breaking up nghĩa là tiếng bị đứt quãng, không phải nhờ nói to."),
    listenQ("b2-f28", "Người nói nghĩ vì sao chị Hoa chưa trả lời tin nhắn?", "Hoa still hasn't replied. She can't have forgotten about the deadline, because she reminded me about it yesterday. She must have been stuck in meetings all day.", ["Chị ấy bị kẹt trong các cuộc họp suốt cả ngày", "Chị ấy quên mất hạn chót", "Chị ấy bị ốm nên nghỉ làm", "Điện thoại của chị ấy bị hỏng"], 0, "Must have been stuck: chắc hẳn đã bị kẹt họp. Can't have forgotten: không thể nào đã quên, vì hôm qua chị ấy còn nhắc người nói."),
    correct("b2-f29", "When the new manager arrived in 2022, the team has been using the same software for ten years.", ["When the new manager arrived in 2022, the team had been using the same software for ten years.", "When the new manager arrived in 2022, the team had used the same software for ten years."], "Mốc là arrived (quá khứ), nên thời lượng kéo dài đến mốc đó dùng had been + V-ing, không dùng has been."),
    correct("b2-f30", "I would appreciate if you could confirm the booking by Friday.", ["I would appreciate it if you could confirm the booking by Friday.", "I'd appreciate it if you could confirm the booking by Friday."], "Mẫu nhờ việc trang trọng là I would appreciate it if you could + V. Chữ it không được bỏ."),
  ],
  // Chapter 2: third and mixed conditionals, wish, unless / in case / supposing, modal perfects, unreal past
  [
    mc("b2-f31", "My colleague keeps interrupting me in meetings. I wish he ___ doing that.", ["will stop", "stops", "would stop", "is stopping"], 2, "Wish + would + V: phàn nàn về hành động của người khác mà mình muốn họ thay đổi."),
    mc("b2-f32", "___ the bank refused our loan, what would we do?", ["Unless", "In case", "Otherwise", "Supposing"], 3, "Supposing (giả sử) đưa ra một giả thiết rồi hỏi tiếp. Tình huống khó xảy ra nên dùng quá khứ refused và would ở vế sau."),
    fill("b2-f33", "If we had hired a second designer last spring, we ___ be so far behind schedule now. (không phải)", ["wouldn't", "would not"], "Câu hỗn hợp: vế if nói về quá khứ (had + V3), vế chính nói về hiện tại (now) nên dùng would + V, không có have."),
    fill("b2-f34", "I ___ have eaten such a big lunch. Now I can hardly stay awake in this meeting. (lẽ ra không nên)", ["shouldn't", "should not", "oughtn't to", "ought not to"], "Shouldn't have + V3: lẽ ra không nên làm, nhưng đã làm rồi."),
    reorder("b2-f35", "It's high time we replaced these old computers.", "It's high time + chủ ngữ + quá khứ đơn: lẽ ra phải làm từ lâu rồi, dù đang nói về bây giờ."),
    reorder("b2-f36", "She spoke to me as if I were a child.", "As if + quá khứ (were) cho điều không có thật: thực tế tôi không phải trẻ con."),
    listenQ("b2-f37", "Vì sao người nói in thêm bản chương trình họp?", "I'll print ten extra copies of the agenda in case more people turn up. If nobody else comes, we can keep them for next week.", ["Để phòng khi có thêm người đến họp", "Vì đã có thêm mười người đăng ký", "Vì tuần sau có một cuộc họp khác", "Vì khách hàng yêu cầu có bản in"], 0, "In case more people turn up: in sẵn ngay bây giờ để phòng khi có thêm người đến, dù họ có đến hay không."),
    listenQ("b2-f38", "Điều nào đúng về việc dịch bản hợp đồng?", "I spent the whole weekend translating the contract into English. On Monday I found out that the client's lawyer had already done it, so I needn't have bothered.", ["Người nói định dịch nhưng rồi đã không làm", "Người nói đã dịch, nhưng hóa ra không cần thiết", "Luật sư nhờ người nói dịch giúp", "Người nói chưa dịch xong vì hết thời gian"], 1, "Needn't have bothered: đã bỏ công làm rồi mới biết là không cần, vì luật sư của khách đã dịch trước."),
    correct("b2-f39", "If we had chose a cheaper hotel, we would have saved a lot of money.", ["If we had chosen a cheaper hotel, we would have saved a lot of money.", "If we'd chosen a cheaper hotel, we would have saved a lot of money.", "If we had chosen a cheaper hotel, we'd have saved a lot of money.", "If we'd chosen a cheaper hotel, we'd have saved a lot of money."], "Vế if của câu loại 3 là had + V3. Choose, chose, chosen, nên phải là had chosen."),
    correct("b2-f40", "I wish I would have checked the figures before the meeting.", ["I wish I had checked the figures before the meeting.", "I wish I'd checked the figures before the meeting."], "Tiếc về quá khứ dùng wish + had + V3, giống vế if của câu loại 3. Không dùng would have sau wish."),
  ],
  // Chapter 3: relative clauses, describing data, linkers, participle clauses
  [
    mc("b2-f41", "Which sentence about the project engineers is correct?", ["The engineers who works on this project are based in Hanoi.", "The engineers who they work on this project are based in Hanoi.", "The engineers, that work on this project, are based in Hanoi.", "The engineers who work on this project are based in Hanoi."], 3, "Động từ trong mệnh đề chia theo engineers (số nhiều) nên là work; who đã thay cho chủ ngữ nên không thêm they; sau dấu phẩy không dùng that."),
    mc("b2-f42", "Our rent has gone up by twenty per cent. ___, two of our biggest clients have moved to a competitor.", ["Nevertheless", "Whereas", "Moreover", "On the other hand"], 2, "Ý sau thêm một tin xấu cùng chiều với ý trước nên dùng moreover (hơn nữa). Nevertheless và on the other hand chỉ sự đối lập; whereas là liên từ, phải nối hai mệnh đề trong cùng một câu."),
    fill("b2-f43", "Last year there was a fall ___ fifteen per cent in the number of customer complaints. (giới từ sau danh từ)", ["of"], "Sau danh từ chỉ sự thay đổi (a fall, a rise) dùng of + mức thay đổi. By chỉ đi với động từ: Complaints fell by fifteen per cent."),
    fill("b2-f44", "___ the survey results, the board decided to open a branch in Can Tho. (study; xong việc này rồi mới quyết định)", ["Having studied"], "Having + V3: nghiên cứu xong kết quả khảo sát rồi mới quyết định. Chủ ngữ the board làm cả hai việc nên rút gọn được."),
    reorder("b2-f45", "Customers whose orders arrive late will receive a voucher.", "Whose + danh từ chỉ sở hữu: đơn hàng của khách. Sau whose orders là động từ của mệnh đề (arrive), rồi mới đến động từ chính will receive."),
    reorder("b2-f46", "Our revenue is expected to reach twelve billion dong.", "Be expected to + V dùng để dự báo số liệu: cho thấy đây là dự đoán, không phải lời hứa chắc chắn."),
    listenQ("b2-f47", "Doanh số xe máy điện thay đổi thế nào?", "Sales of electric motorbikes fell slightly in the first quarter. However, they rose sharply in the second quarter and reached just over twenty thousand units in June.", ["Tăng mạnh rồi giảm nhẹ vào tháng Sáu", "Giảm nhẹ rồi tăng mạnh, đạt nhỉnh hơn hai mươi nghìn chiếc vào tháng Sáu", "Giảm nhẹ rồi chững lại ở khoảng hai mươi nghìn chiếc", "Tăng đều suốt nửa năm, đạt gần hai mươi nghìn chiếc"], 1, "Fell slightly: giảm nhẹ; rose sharply: tăng mạnh; just over: nhỉnh hơn một chút."),
    listenQ("b2-f48", "Kết luận của người nói là gì?", "One advantage of the new booking system is that it saves a lot of time. The main drawback is that it is quite expensive. On balance, I believe we should buy it.", ["Nên mua hệ thống đặt chỗ mới", "Không nên mua vì hệ thống quá đắt", "Nên chờ một phiên bản rẻ hơn", "Hệ thống mới không tiết kiệm được thời gian"], 0, "On balance, I believe…: sau khi cân cả mặt lợi (tiết kiệm thời gian) và mặt hại (khá đắt), người nói kết luận là nên mua."),
    correct("b2-f49", "We work with a designer who her ideas are always original.", ["We work with a designer whose ideas are always original."], "Chỉ sở hữu (ý tưởng của nhà thiết kế) dùng whose + danh từ, không dùng who + her."),
    correct("b2-f50", "Founding in 1998, the company now employs three hundred people.", ["Founded in 1998, the company now employs three hundred people.", "Established in 1998, the company now employs three hundred people."], "Công ty được thành lập (nghĩa bị động), nên phần rút gọn dùng V3: Founded. V-ing mang nghĩa chủ động."),
  ],
  // Chapter 4: negotiation, articles, to V or V-ing, complaints
  [
    mc("b2-f51", "I really regret ___ my old camera. I'd love to have it back now.", ["selling", "to sell", "sell", "to selling"], 0, "Regret + V-ing: hối tiếc vì đã làm việc gì. Regret to + V chỉ dùng trong thông báo trang trọng như We regret to inform you…"),
    mc("b2-f52", "After the trial, the driver was sent to ___ for three years.", ["the prison", "a prison", "prison", "prisons"], 2, "Nói về mục đích chính của nhà tù (đi tù) thì không dùng mạo từ: be sent to prison."),
    fill("b2-f53", "We were wondering ___ you could extend the payment period to sixty days. (liệu)", ["if", "whether"], "We were wondering if (whether) + chủ ngữ + could: lời đề nghị mềm mỏng khi đàm phán, phía sau là trật tự câu kể."),
    fill("b2-f54", "We regret that you ___ twice for the same booking. (charge, bị động)", ["were charged", "have been charged"], "Dùng bị động để nêu sự việc mà không chỉ tay vào người: you were charged twice, thay vì nói nhân viên nào đã thu tiền hai lần."),
    reorder("b2-f55", "The manager apologised for keeping us waiting.", "Apologise for + V-ing, vì for là giới từ. Keep somebody waiting: bắt ai phải chờ."),
    reorder("b2-f56", "Have you tried calling their head office?", "Try + V-ing: thử một cách xem có hiệu quả không."),
    listenQ("b2-f57", "Người nói chắc chắn điều gì?", "I definitely remember sending the invoice on Monday, but the client says they never got it. I'll check my sent emails.", ["Mình phải nhớ gửi hóa đơn vào thứ Hai", "Khách hàng đã nhận được hóa đơn", "Mình đã quên gửi hóa đơn cho khách", "Mình đã gửi hóa đơn vào thứ Hai"], 3, "Remember + V-ing: nhớ lại việc đã làm. Người nói chắc là đã gửi, dù khách nói chưa nhận được."),
    listenQ("b2-f58", "Nhà cung cấp đề xuất gì?", "I'm afraid we can't offer a ten per cent discount. However, if you order a thousand units, we could go up to seven per cent.", ["Giảm mười phần trăm cho mọi đơn hàng", "Giảm bảy phần trăm nếu đặt một nghìn sản phẩm", "Không giảm giá trong bất kỳ trường hợp nào", "Giảm bảy phần trăm cho đơn hàng hiện tại"], 1, "Từ chối mềm bằng I'm afraid we can't…, rồi đưa ra đề xuất có điều kiện: if you order a thousand units, we could…"),
    correct("b2-f59", "The patience is the most important quality for a negotiator.", ["Patience is the most important quality for a negotiator."], "Danh từ trừu tượng nói chung (patience) không dùng the."),
    correct("b2-f60", "I clearly remember to switch off the heater before I left, but it was still on when I got home.", ["I clearly remember switching off the heater before I left, but it was still on when I got home.", "I clearly remember switching the heater off before I left, but it was still on when I got home.", "I clearly remember having switched off the heater before I left, but it was still on when I got home."], "Nhớ lại việc đã làm dùng remember + V-ing; remember to + V là nhớ để làm một việc chưa làm."),
  ],
];
