import { correct, fill, listenQ, mc, reorder } from "../builders";
import type { Exercise } from "../types";

/** Extra final-test items for Tiếng Anh C1, 10 per chapter (two of each kind), drawn at random with the original bank. */
export const FINAL_EXTRA_TIENG_ANH_C1: Exercise[][] = [
  // Chương 1: cụm động từ và kết hợp từ, tỉnh lược và thay thế, tương lai nâng cao, cấu tạo từ, từ dễ nhầm và ngôn ngữ ước lượng
  [
    mc("c1-f21", "Notice from HR: All staff ___ report to the new office at eight on Monday morning. No exceptions will be made.", ["are bound to", "are about to", "are to", "are on the verge of"], 2, "Be to + V dùng cho kế hoạch chính thức hoặc chỉ thị (bạn phải làm). Bound to là dự đoán chắc chắn, about to không đi với mốc thời gian, on the verge of phải đi với danh từ hoặc V-ing."),
    mc("c1-f22", "Will the new manager want to change the whole schedule? — I don't expect ___.", ["so", "not", "yes", "one"], 0, "Với expect, think, believe, câu trả lời phủ định thường là don't + động từ + so: I don't expect so. Không nói I don't expect not."),
    fill("c1-f23", "The weather in the mountains is notoriously ___, so pack for rain as well as sunshine. (PREDICT)", ["unpredictable"], "Sau is cần tính từ: predict thành predictable; nghĩa câu là thời tiết thất thường nên thêm tiền tố un-: unpredictable."),
    fill("c1-f24", "The belief that boys should not cry is still deeply ___ in some families. (ăn sâu, bám rễ)", ["rooted", "ingrained", "entrenched", "embedded"], "Deeply rooted (hoặc deeply ingrained, deeply entrenched) là kết hợp từ mạnh: ăn sâu bám rễ, khó thay đổi."),
    reorder("c1-f25", "She is bound to notice the mistake.", "Be bound to + V nguyên mẫu: người nói tin chắc điều đó sẽ xảy ra."),
    reorder("c1-f26", "We were bitterly disappointed by the decision.", "Bitterly disappointed là kết hợp từ mạnh: vô cùng thất vọng. Trạng từ bitterly đứng ngay trước disappointed."),
    listenQ("c1-f27", "Người nói ngụ ý điều gì?", "The hall holds two hundred people or thereabouts, so we'll have to keep the guest list fairly short.", ["Hội trường chứa được đúng hai trăm người, không hơn không kém.", "Họ cần tìm một hội trường lớn hơn.", "Hội trường quá rộng so với số khách dự kiến.", "Hội trường chỉ chứa được khoảng hai trăm người, nên phải hạn chế số khách mời."], 3, "Or thereabouts là cách nói ước lượng: khoảng chừng đó. Keep the guest list short cho thấy phải mời ít khách cho vừa sức chứa."),
    listenQ("c1-f28", "Chuyện gì đã xảy ra với hợp đồng?", "We were on the verge of signing the contract when their chief executive resigned, and the whole deal fell through.", ["Hai bên đã ký hợp đồng ngay trước khi giám đốc từ chức.", "Hai bên sắp ký thì giám đốc điều hành bên kia từ chức, và thương vụ đổ bể.", "Hợp đồng chỉ bị hoãn lại cho đến khi có giám đốc mới.", "Giám đốc bên kia từ chức vì hợp đồng bị hủy."], 1, "On the verge of signing: sắp ký nhưng chưa ký. Fell through: đổ bể, không thành."),
    correct("c1-f29", "We've run out of brown bread, but there's some white one.", ["We've run out of brown bread, but there's some white.", "We've run out of brown bread, but there is some white.", "We've run out of brown bread, but there's some white bread.", "We've run out of brown bread, but there is some white bread."], "Bread là danh từ không đếm được nên không thay bằng one. Chỉ cần bỏ danh từ đi (some white) hoặc nhắc lại danh từ."),
    correct("c1-f30", "The decision to close the factory was a big disappointed for everyone.", ["The decision to close the factory was a big disappointment for everyone."], "Sau a big cần một danh từ: disappoint thành disappointment. Disappointed là tính từ chỉ cảm xúc của người."),
  ],
  // Chương 2: đảo ngữ, câu chẻ, điều kiện nâng cao, thể giả định
  [
    mc("c1-f31", "Under no circumstances ___ the laboratory without safety glasses.", ["visitors should enter", "should visitors enter", "visitors enter", "do visitors should enter"], 1, "Under no circumstances đứng đầu câu thì đảo động từ khuyết thiếu lên trước chủ ngữ: should visitors enter."),
    mc("c1-f32", "(Văn phong trang trọng) The fire inspector demanded that the building ___ until the wiring had been replaced.", ["is not used", "does not be used", "not to be used", "not be used"], 3, "Sau demand that dùng thể giả định: phủ định chỉ cần not + be + V3, không mượn does, không dùng to và không lùi thì."),
    fill("c1-f33", "What the manager did ___ call every unhappy customer personally. (một từ)", ["was"], "Wh-cleft với do: What + S + did + was + động từ nguyên mẫu. Động từ be chia theo thì của mệnh đề What (did nên là was)."),
    fill("c1-f34", "If it ___ been for your directions, we would never have found the village. (không có, phủ định)", ["hadn't", "had not"], "If it hadn't been for + danh từ: nếu không nhờ, dùng cho quá khứ. Vế chính would have + V3 xác nhận đây là điều kiện loại ba."),
    reorder("c1-f35", "Little did they realise how serious the problem was.", "Little đứng đầu câu (hoàn toàn không) thì đảo trợ động từ lên trước chủ ngữ: did they realise, động từ realise ở nguyên mẫu."),
    reorder("c1-f36", "Residents are demanding that the factory be closed down.", "Demand that + S + be + V3: thể giả định ở dạng bị động, không dùng is closed."),
    listenQ("c1-f37", "Có thể suy ra điều gì từ câu này?", "Had the ambulance arrived five minutes later, we might not be talking to him today.", ["Xe cứu thương đến kịp nên người bệnh đã qua khỏi.", "Xe cứu thương đã đến muộn năm phút.", "Người bệnh đã không qua khỏi.", "Họ không muốn nói chuyện với người bệnh nữa."], 0, "Had + S + V3 là đảo ngữ của If the ambulance had arrived: điều trái với quá khứ. Thực tế xe đến kịp, nên hôm nay người ấy vẫn còn đây."),
    listenQ("c1-f38", "Người nói muốn nói điều gì với người đề nghị giúp đỡ?", "I do appreciate the offer, but what I really need right now is time, not money.", ["Họ cần cả tiền lẫn thời gian ngay lập tức.", "Họ chỉ cần tiền, không cần thêm thời gian.", "Họ thật lòng cảm ơn lời đề nghị, nhưng điều họ cần là thời gian chứ không phải tiền.", "Họ từ chối vì nghĩ lời đề nghị không thật lòng."], 2, "Do appreciate là do nhấn mạnh: thật sự trân trọng. Wh-cleft what I really need is time đặt trọng tâm vào thời gian."),
    correct("c1-f39", "Seldom the manager has praised anyone so publicly.", ["Seldom has the manager praised anyone so publicly.", "The manager has seldom praised anyone so publicly."], "Seldom đứng đầu câu thì trợ động từ has phải đứng trước chủ ngữ: Seldom has the manager praised."),
    correct("c1-f40", "The regulations require that every visitor wore a helmet on site.", ["The regulations require that every visitor wear a helmet on site.", "The regulations require that every visitor should wear a helmet on site.", "The regulations require that every visitor wears a helmet on site."], "Câu chính ở hiện tại (require) nên động từ sau that không thể ở quá khứ. Văn trang trọng dùng nguyên mẫu wear; lối Anh-Anh dùng should wear hoặc wears."),
  ],
  // Chương 3: nhượng bộ, động từ tường thuật, bị động tường thuật, mệnh đề quan hệ nâng cao
  [
    mc("c1-f41", "___ as the idea may sound, it would be almost impossible to put into practice.", ["Attractive", "However attractive", "Although attractive", "Despite attractive"], 0, "Tính từ + as + S + may + V: dù nghe hấp dẫn đến đâu. Tính từ đứng một mình ở đầu câu; However attractive thì không đi với as, còn although và despite không dùng trong mẫu này."),
    mc("c1-f42", "“Don't forget to back up your files before the update,” the IT manager told us. Câu tường thuật nào đúng?", ["The IT manager reminded us of backing up our files before the update.", "The IT manager accused us of not backing up our files before the update.", "The IT manager reminded us to back up our files before the update.", "The IT manager denied backing up our files before the update."], 2, "Remind + người + to V: nhắc ai làm gì. Remind sb of là làm ai nhớ đến điều gì; accuse và deny thì sai ý câu gốc."),
    fill("c1-f43", "The fire is believed to have ___ started deliberately. (một từ; có người cố ý gây ra đám cháy)", ["been"], "Đám cháy bị ai đó gây ra, và việc đó xảy ra trước lúc người ta nhận định, nên dùng to have been + V3."),
    fill("c1-f44", "Investors were surprised by the ease ___ which the start-up raised its first million dollars. (giới từ)", ["with"], "Do with ease (một cách dễ dàng), giới từ with được đưa lên trước which: the ease with which."),
    reorder("c1-f45", "The lecture was cancelled, which annoyed many students.", "Dấu phẩy + which thay cho cả mệnh đề phía trước: việc buổi giảng bị hủy khiến nhiều sinh viên bực mình."),
    reorder("c1-f46", "Two men are reported to have been detained.", "To have been + V3: hai người bị tạm giữ (bị động), và việc đó xảy ra trước lúc đưa tin."),
    listenQ("c1-f47", "Người nói đánh giá khách sạn thế nào?", "Granted, the hotel was a bit noisy at night. That said, I'd happily stay there again, if only for the view.", ["Rất thất vọng vì tiếng ồn và sẽ không quay lại.", "Khách sạn yên tĩnh nhưng quang cảnh xấu.", "Chỉ quay lại nếu khách sạn giảm giá.", "Nhìn chung hài lòng, dù thừa nhận ban đêm hơi ồn."], 3, "Granted thừa nhận một điểm yếu, That said lật lại ngay: người nói vẫn sẵn lòng quay lại, dù chỉ vì quang cảnh."),
    listenQ("c1-f48", "Khi nào họ sẽ đi tàu đêm?", "Our flight might be cancelled, in which case we'll take the night train to Hue instead.", ["Dù thế nào họ cũng sẽ đi tàu đêm.", "Nếu chuyến bay bị hủy.", "Nếu tàu đêm còn vé.", "Sau khi chuyến bay hạ cánh ở Huế."], 1, "In which case nghĩa là nếu vậy thì, thay cho cả vế our flight might be cancelled."),
    correct("c1-f49", "The manager suggested me to take a few days off.", ["The manager suggested that I take a few days off.", "The manager suggested that I should take a few days off.", "The manager suggested I take a few days off.", "The manager suggested I should take a few days off.", "The manager suggested that I took a few days off.", "The manager suggested I took a few days off.", "The manager suggested taking a few days off."], "Suggest không đi với người + to V. Dùng suggest that + S + (should) + V nguyên mẫu, hoặc suggest + V-ing."),
    correct("c1-f50", "Tired as she was, but she finished the report before midnight.", ["Tired as she was, she finished the report before midnight.", "Tired though she was, she finished the report before midnight.", "Although she was tired, she finished the report before midnight.", "Though she was tired, she finished the report before midnight."], "Tính từ + as + S + V đã là mệnh đề nhượng bộ (dù mệt đến mấy), nên vế sau không thêm but, giống như với although và much as."),
  ],
  // Chương 4: ngôn ngữ tinh tế, văn phong học thuật, trạng từ bình luận và rào đón, viết luận và tóm tắt
  [
    mc("c1-f51", "Based on a single small survey, the authors ___ that the new timetable may reduce stress among students.", ["demonstrate", "prove", "establish", "suggest"], 3, "Động từ dẫn phải khớp với độ mạnh của bằng chứng: một khảo sát nhỏ chỉ đủ để suggest. Demonstrate, prove, establish quá mạnh."),
    mc("c1-f52", "Câu nào diễn đạt lại đúng câu: Unemployment rose sharply last year.", ["Last year, unemployment was risen sharply.", "There was a sharp rise in unemployment last year.", "There was a sharp rise in employment last year.", "Unemployment may have risen slightly last year."], 1, "Câu đúng đổi từ loại (rose thành a rise, sharply thành sharp) và đổi cấu trúc mà giữ nguyên ý. Các câu còn lại sai ngữ pháp, đổi nghĩa hoặc đổi mức độ chắc chắn."),
    fill("c1-f53", "This is ___ the most important discovery of the decade; nobody in the field disputes it. (DOUBT)", ["undoubtedly", "doubtless"], "Trạng từ bình luận nhấn mạnh sự chắc chắn: doubt thành undoubtedly, đứng sau be và trước cụm danh từ."),
    fill("c1-f54", "The ___ of a four-day week led to a sharp rise in job applications. (INTRODUCE)", ["introduction"], "Danh từ hóa: sau the và trước of cần danh từ, introduce thành introduction. Cả ý trở thành chủ ngữ của câu."),
    reorder("c1-f55", "These findings appear to support the original hypothesis.", "Rào đón bằng động từ: appear to + V giúp kết luận thận trọng hơn khẳng định trần These findings support..."),
    reorder("c1-f56", "There is evidence to suggest that demand is falling.", "There is evidence to suggest that...: khẳng định có căn cứ mà vẫn khách quan, không cần I think."),
    listenQ("c1-f57", "Người quản lý thực sự muốn nói gì?", "Thanks for the report. It's a little on the long side, and the conclusions aren't exactly clear, so you might want to have another look before Friday.", ["Báo cáo rất tốt, không cần sửa gì thêm.", "Báo cáo hơi ngắn, cần bổ sung thêm số liệu.", "Báo cáo quá dài, kết luận chưa rõ, và cần sửa lại trước thứ Sáu.", "Nếu rảnh thì có thể xem lại, không bắt buộc."], 2, "A little on the long side và not exactly clear là nói giảm: báo cáo dài và kết luận không rõ. You might want to... của cấp trên thực chất là yêu cầu."),
    listenQ("c1-f58", "Vì sao bài viết vẫn bị coi là đạo văn?", "You've changed a few words, but the sentence structure is exactly the same as the original, so it would still count as plagiarism.", ["Vì chỉ đổi vài từ mà vẫn giữ nguyên khung câu của bản gốc.", "Vì đổi quá nhiều từ nên làm sai ý bản gốc.", "Vì bài viết ngắn hơn nhiều so với bản gốc.", "Vì người viết đưa ý kiến cá nhân vào bài."], 0, "Chỉ thay vài từ mà giữ nguyên cấu trúc câu gốc (patchwriting) vẫn bị coi là đạo văn. Diễn đạt lại phải đổi cả từ lẫn cấu trúc."),
    correct("c1-f59", "The emerge of electric scooters has changed city traffic.", ["The emergence of electric scooters has changed city traffic."], "Emerge là động từ; danh từ là emergence. Thêm the trước động từ không biến nó thành danh từ."),
    correct("c1-f60", "It is worth to note that the sample was small.", ["It is worth noting that the sample was small.", "It's worth noting that the sample was small."], "Worth đi với V-ing, không đi với to V: It is worth noting that..."),
  ],
];
