import type { LessonMedia } from "../types";

/** Videos and links for Bước 0: Phát âm lessons, by lesson slug; checked 2026-09-26 (oEmbed + content). */
export const MEDIA_PHAT_AM_IPA: Record<string, LessonMedia> = {
  "lam-quen-bang-ipa": { kind: "youtube", youtubeId: "HqUl2Q74eSI", title: "Bảng phiên âm tiếng Anh IPA - Cách phát âm chuẩn 44 âm quốc tế | IELTS FIGHTER", source: "IELTS Fighter", minutes: 24, lang: "vi", note: "Cô giáo giới thiệu trọn bảng IPA giọng Anh-Anh (44 âm, 20 nguyên âm và 24 phụ âm) trên bảng, kèm từ ví dụ để đọc theo." },
  "nguyen-am-ngan-va-dai": { kind: "youtube", youtubeId: "KI3mgasrYgE", title: "Bài 03: Nguyên Âm Đơn | Talk To Miss Lan", source: "misslanenglish (Talk to Miss Lan)", minutes: 13, lang: "vi", note: "Miss Lan đi qua 12 nguyên âm đơn theo từng cặp ngắn – dài như /ɪ/–/iː/, /ʊ/–/uː/, chỉ khẩu hình và cho đọc lặp lại." },
  "nguyen-am-doi": { kind: "youtube", youtubeId: "XeaKFbibFdc", title: "Bài 04: Nguyên Âm Đôi | Talk To Miss Lan", source: "misslanenglish (Talk to Miss Lan)", minutes: 7, lang: "vi", note: "Tám nguyên âm đôi trên bảng IPA Anh-Anh (có /əʊ/), cách trượt từ âm đầu sang âm sau và từ ví dụ để luyện theo." },
  "phu-am-huu-thanh-vo-thanh": { kind: "youtube", youtubeId: "3-nrc63Aq2M", title: "Bài 05: Phụ âm | Talk To Miss Lan", source: "misslanenglish (Talk to Miss Lan)", minutes: 18, lang: "vi", note: "Đi lần lượt các cặp phụ âm vô thanh – hữu thanh (/p/–/b/, /s/–/z/, /ʃ/–/ʒ/, /θ/–/ð/…), giải thích chỗ đặt môi, lưỡi và độ rung." },
  "am-cuoi": { kind: "youtube", youtubeId: "WhMr06xiNvg", title: "Bài 09: Cách phát âm cuối trong tiếng Anh | Talk To Miss Lan", source: "misslanenglish (Talk to Miss Lan)", minutes: 8, lang: "vi", note: "Vì sao âm cuối quyết định nghĩa (white, wine, wife) và cách đọc rõ âm cuối thay vì nuốt mất như thói quen tiếng Việt." },
  "duoi-s-va-ed": { kind: "youtube", youtubeId: "MbvKiX3PAmI", title: "Công thức \"ăn trọn\" điểm các câu phát âm đuôi -ed, -s, -es // Chống liệt tiếng Anh", source: "Elight Learning English", minutes: 14, lang: "vi", note: "Ba cách đọc -ed và ba cách đọc -s/-es dựa trên âm vô thanh, hữu thanh ở cuối từ gốc, có bảng ví dụ và bài tập nhận diện." },
  "trong-am-tu": { kind: "youtube", youtubeId: "gvfKO14OSDs", title: "Mẹo Ghi Nhớ Cách Nhấn Trọng Âm Tiếng Anh CỰC DỄ | KISS English", source: "KISS English Center", minutes: 22, lang: "vi", note: "Âm tiết là gì, cách đọc dấu trọng âm ˈ ˌ trong phiên âm từ điển và các mẹo nhớ vị trí trọng âm của từ hai âm tiết trở lên." },
  "nhan-cau-noi-am-ngu-dieu": { kind: "youtube", youtubeId: "rnJCKda4oWU", title: "Sentence Stress in English Pronunciation", source: "Oxford Online English", minutes: 13, lang: "en", note: "Giáo viên Anh chỉ cách nhấn từ nội dung, đọc lướt từ chức năng và dời trọng âm câu để nhấn ý, có câu mẫu để luyện nhịp điệu." },
};
