import type { LessonMedia } from "../types";

/** Videos and links for Tiếng Anh B1 lessons, by lesson slug; checked 2026-09-26 (oEmbed + content). */
export const MEDIA_TIENG_ANH_B1: Record<string, LessonMedia> = {
  // chapter 1
  "ke-lai-mot-chuyen": { kind: "youtube", youtubeId: "WwXpGX8b_-M", title: "Phân Biệt Thì Quá Khứ Đơn và Quá Khứ Tiếp Diễn - Bài 9 | TLH English", source: "TLH ENGLISH", minutes: 9, lang: "vi", note: "Phân biệt quá khứ đơn và quá khứ tiếp diễn, khi nào một hành động đang diễn ra thì bị hành động khác cắt ngang." },
  "da-duoc-bao-lau": { kind: "youtube", youtubeId: "PbGnR-5gYpk", title: "Thì hiện tại hoàn thành: Cấu trúc, cách dùng và dấu hiệu | Anh Ngữ ZIM", source: "ZIM Academy", minutes: 6, lang: "vi", note: "Ôn gọn cách dùng, cấu trúc và dấu hiệu của thì hiện tại hoàn thành, trong đó có for và since." },
  "qua-khu-hoan-thanh": { kind: "youtube", youtubeId: "5ucwoK_6bsY", title: "THÌ QUÁ KHỨ HOÀN THÀNH: Công Thức, Cách Dùng và Dấu Hiệu Nhận Biết | Ms Thuỷ KISS English", source: "KISS English Center", minutes: 12, lang: "vi", note: "Công thức had + V3 và cách dùng để kể việc đã xảy ra trước một việc khác trong quá khứ." },
  "would-va-used-to": { kind: "youtube", youtubeId: "RMt6KRtG9wQ", title: "Cách dùng \"used to\" và \"would\" để nói về thói quen trong quá khứ | Talk to Miss Lan", source: "misslanenglish (Talk to Miss Lan)", minutes: 23, lang: "vi", note: "Khi nào dùng used to, khi nào dùng would để kể về thói quen ngày trước, kèm nhiều ví dụ giao tiếp." },
  "hien-tai-hoan-thanh-tiep-dien": { kind: "youtube", youtubeId: "h-cprKWQmY0", title: "Thì hiện tại hoàn thành tiếp diễn: Công thức, cách dùng, dấu hiệu nhận biết | Anh Ngữ ZIM", source: "ZIM Academy", minutes: 6, lang: "vi", note: "Công thức have been + V-ing và cách nhấn mạnh một việc kéo dài từ quá khứ đến bây giờ." },
  // chapter 2
  "tuong-lai-tiep-dien-hoan-thanh": { kind: "youtube", youtubeId: "P4m_q7uhJYQ", title: "Thì TƯƠNG LAI ĐƠN, TƯƠNG LAI TIẾP DIỄN, TƯƠNG LAI HOÀN THÀNH & TƯƠNG LAI HOÀN THÀNH TIẾP DIỄN", source: "5+ English", minutes: 7, lang: "vi", note: "Đặt will be doing và will have done cạnh các thì tương lai khác để thấy rõ khác biệt." },
  "suy-doan-hien-tai": { kind: "youtube", youtubeId: "SxY9Okh2Cqw", title: "How to use MODALS of Deduction & Speculation in the PRESENT 🕵🏻‍♀️", source: "English with Linguivers", minutes: 9, lang: "en", note: "Dùng must, might, could, can't để suy đoán về hiện tại, luyện qua các tình huống như thám tử." },
  "cau-hoi-duoi": { kind: "youtube", youtubeId: "efJl83Mk1Z4", title: "Câu Hỏi Đuôi | TAG QUESTIONS | T-ENGLISH CLASS", source: "T - English", minutes: 7, lang: "vi", note: "Quy tắc lập câu hỏi đuôi: câu khẳng định đi với đuôi phủ định và ngược lại, cùng các trường hợp đặc biệt." },
  "neu-thi": { kind: "youtube", youtubeId: "lG-K-EyWeKQ", title: "Phá Đảo 4 LOẠI CÂU ĐIỀU KIỆN TRONG TIẾNG ANH / Chống Liệt Tiếng Anh Ep. 26", source: "Elight Learning English", minutes: 21, lang: "vi", note: "Hệ thống các loại câu điều kiện, giúp phân biệt rõ loại 1 (có thể xảy ra) và loại 2 (giả định)." },
  "wish-va-used-to": { kind: "youtube", youtubeId: "R_eFfxRMORE", title: "TẤT TẦN TẦN về cấu trúc Wish & If Only - Cách dùng CÂU MONG ƯỚC ở Hiện tại, Quá khứ & Tương lai", source: "5+ English", minutes: 10, lang: "vi", note: "Wish và if only với quá khứ đơn (ước cho hiện tại) và quá khứ hoàn thành (tiếc về quá khứ)." },
  // chapter 3
  "cong-viec-va-phong-van": { kind: "youtube", youtubeId: "aqO5RlRKfUs", title: "HỌC TIẾNG ANH PHÂN BIỆT TÍNH TỪ ĐUÔI ED VÀ ĐUÔI ING CỰC DỄ | Tiếng Anh cơ bản", source: "The Anh English", minutes: 10, lang: "vi", note: "Phân biệt tính từ -ed (cảm xúc của người) và -ing (tính chất của sự việc) như bored và boring." },
  "bay-to-y-kien": { kind: "youtube", youtubeId: "fQcga26aoL8", title: "How to agree or disagree in English", source: "British Council | English", minutes: 4, lang: "en", note: "Bài nói trình độ B1: các cụm để đồng ý, phản đối một cách lịch sự khi trao đổi ý kiến." },
  "dong-tu-theo-sau": { kind: "youtube", youtubeId: "OQNF2J7eH-k", title: "Danh Động Từ (Gerunds): TO V, V-ING trong tiếng Anh / Chống Liệt Tếng Anh Ep. 19", source: "Elight Learning English", minutes: 20, lang: "vi", note: "Nhóm động từ theo sau là to V và nhóm theo sau là V-ing, kèm ví dụ và bài luyện." },
  "cau-hoi-gian-tiep": { kind: "youtube", youtubeId: "CzoxIVPtPgI", title: "Indirect Questions - 6 Minute Grammar", source: "BBC Learning English", minutes: 6, lang: "en", note: "Hỏi lịch sự với Could you tell me…, Do you know if…, và cách đổi trật tự từ trong câu hỏi gián tiếp." },
  "cau-tuong-thuat": { kind: "youtube", youtubeId: "4hOUOxM8fa4", title: "TẤT TẦN TẬT về câu trực tiếp, gián tiếp (phần 1)  [Ngữ pháp tiếng Anh]", source: "Elight Learning English", minutes: 16, lang: "vi", note: "Cách chuyển lời nói trực tiếp sang tường thuật: lùi thì, đổi đại từ và từ chỉ thời gian, nơi chốn." },
  // chapter 4
  "tin-tuc-va-su-viec": { kind: "youtube", youtubeId: "a9GnbpR96Ow", title: "Làm chủ câu bị động (Passive Voice) trong 5 phút [Ngữ pháp tiếng Anh cơ bản - Các loại câu #6]", source: "Elight Learning English", minutes: 11, lang: "vi", note: "Nền tảng câu bị động: be + V3, cách chuyển câu chủ động sang bị động ở hiện tại đơn và quá khứ đơn." },
  "bi-dong-moi-thi": { kind: "youtube", youtubeId: "08JAjcNG9CQ", title: "Câu Bị Động Trong 12 Thì và với Động Từ Khuyết Thiếu / Chống Liệt Tiếng Anh Ep. 30", source: "Elight Learning English", minutes: 18, lang: "vi", note: "Chia câu bị động ở các thì, trong đó có hiện tại hoàn thành, tương lai, và với động từ khuyết thiếu." },
  "menh-de-quan-he": { kind: "youtube", youtubeId: "E2hdanfRzO0", title: "Tất tần tật về mệnh đề quan hệ trong tiếng Anh  [Ngữ pháp tiếng Anh cơ bản - Các loại câu #14]", source: "Elight Learning English", minutes: 13, lang: "vi", note: "Dùng who, which, that, where, whose để nối câu và mô tả người, vật, nơi chốn." },
  "so-sanh-nang-cao": { kind: "youtube", youtubeId: "Fr83ObluJ2A", title: "English Grammar: Modifying Comparatives - a lot, far more, much, a little, slightly", source: "ENGLISH with James · engVid", minutes: 9, lang: "en", note: "Dùng much, far, a lot, a bit, slightly trước so sánh hơn để nói chênh lệch nhiều hay ít cho chính xác." },
  "cum-dong-tu-thong-dung": { kind: "youtube", youtubeId: "WMfb4OPitf8", title: "Hội Thoại Tiếng Anh Hàng Ngày: 10 Cụm Động Từ Thông Dụng | KISS English", source: "KISS English Center", minutes: 21, lang: "vi", note: "Học 10 cụm động từ hay dùng qua một đoạn hội thoại đời thường, kèm giải nghĩa bằng tiếng Việt." },
};
