import type { LessonMedia } from "../types";

/** Videos and links for Tiếng Anh A2 lessons, by lesson slug; checked 2026-09-26 (oEmbed + content). */
export const MEDIA_TIENG_ANH_A2: Record<string, LessonMedia> = {
  "hom-qua-ban-lam-gi": { kind: "youtube", youtubeId: "UQ51d8QFtxU", title: "[Elight] #8 Thì quá khứ đơn: tất tần tật về cấu trúc và cách dùng - Ngữ pháp tiếng Anh cơ bản", source: "Elight Learning English", minutes: 7, lang: "vi", note: "Ôn lại cấu trúc khẳng định, phủ định, câu hỏi với did và cách dùng thì quá khứ đơn." },
  "ky-nghi-cua-toi": { kind: "youtube", youtubeId: "wsLXA83fMXk", title: "Bảng Động Từ Bất Quy Tắc: Mẹo Nhớ V1 V2 V3 Siêu Nhanh + File PDF | Ms Thủy", source: "KISS English Center", minutes: 18, lang: "vi", note: "Chia động từ bất quy tắc thành ba nhóm có quy luật để nhớ nhanh dạng quá khứ và quá khứ phân từ." },
  "ngay-xua-toi-tung": { kind: "youtube", youtubeId: "V2quIYo41Ig", title: "Used To & Would - 6 Minute Grammar", source: "BBC Learning English", minutes: 6, lang: "en", note: "Bài ngữ pháp ngắn của BBC về used to để nói thói quen và trạng thái ngày xưa, kèm would và câu đố cuối bài." },
  "qua-khu-tiep-dien": { kind: "youtube", youtubeId: "mCzSc4DBYjM", title: "Thì quá khứ tiếp diễn: Cấu trúc và cách dùng   [Ngữ pháp tiếng Anh cơ bản - Các thì #7]", source: "Elight Learning English", minutes: 7, lang: "vi", note: "Các cách dùng quá khứ tiếp diễn, gồm hành động đang diễn ra thì một hành động khác xen vào với when." },
  "tieu-su": { kind: "youtube", youtubeId: "XjA1Y9Zw_QE", title: "Cách Đọc và Viết NGÀY THÁNG NĂM Trong Tiếng Anh (Chuẩn Xác) | Ms Thuỷ KISS English", source: "KISS English Center", minutes: 18, lang: "vi", note: "Cách viết và cách đọc ngày tháng năm trong tiếng Anh cho đúng, rất cần khi kể năm sinh và các mốc trong đời một người." },
  "ke-hoach-cuoi-tuan": { kind: "youtube", youtubeId: "-8660VeIj4U", title: "Present continuous and going to - 6 Minute Grammar", source: "BBC Learning English", minutes: 6, lang: "en", note: "Khi nào dùng be going to, khi nào dùng hiện tại tiếp diễn cho kế hoạch đã sắp xếp, có câu hỏi về dự định và quiz." },
  "du-doan-tuong-lai": { kind: "youtube", youtubeId: "jcAX1RtKq3U", title: "Talking about the future - 6 Minute Grammar", source: "BBC Learning English", minutes: 6, lang: "en", note: "Dùng will, might và going to để dự đoán, mức độ chắc chắn khác nhau và cách đặt câu hỏi." },
  "dieu-kien-loai-0-va-1": { kind: "youtube", youtubeId: "K-MKAjvvcsw", title: "How to use the zero and first conditional - 6 Minute Grammar", source: "BBC Learning English", minutes: 6, lang: "en", note: "Phân biệt câu điều kiện loại 0 (sự thật luôn đúng) và loại 1 (khả năng có thể xảy ra), có quiz cuối bài." },
  "loi-moi-va-de-nghi": { kind: "youtube", youtubeId: "7wT7BzAoyj0", title: "Making Suggestions in English - Spoken English Lesson", source: "Oxford Online English", minutes: 10, lang: "en", note: "Các mẫu rủ rê như Let's, Shall we, Why don't we, cách nhận lời và từ chối lịch sự kèm lý do." },
  "goi-dien-thoai": { kind: "youtube", youtubeId: "zNpmtVZFXS0", title: "Talking on the Phone in English - English Phone Vocabulary Lesson", source: "Oxford Online English", minutes: 12, lang: "en", note: "Bốn đoạn hội thoại qua điện thoại, sau đó giải thích các câu quen thuộc để gọi, nghe máy và xử lý khi cuộc gọi gặp trục trặc." },
  "so-sanh-va-mua-sam": { kind: "youtube", youtubeId: "nxWr0FcdrqU", title: "SO SÁNH | COMPARISON | Ngữ pháp Tiếng Anh cơ bản | T-English Class", source: "T - English", minutes: 18, lang: "vi", note: "Tổng hợp so sánh bằng (as...as), so sánh hơn và so sánh nhất với tính từ ngắn, tính từ dài và dạng bất quy tắc." },
  "bao-nhieu": { kind: "youtube", youtubeId: "XxGzMZZ_Hjc", title: "Quantifiers: much, many, little/few, a lot of, some, every, any - English Grammar lesson", source: "Lingportal Online School of English", minutes: 6, lang: "en", note: "Much, many, a lot of với danh từ đếm được và không đếm được, phân biệt few / a few, little / a little." },
  "qua-va-khong-du": { kind: "youtube", youtubeId: "q4xfTdojGEM", title: "How To Use TOO & ENOUGH | English Grammar Lesson", source: "mmmEnglish", minutes: 8, lang: "en", note: "Too và enough đứng ở đâu với tính từ, trạng từ và danh từ, kèm too many và not enough, có nhiều ví dụ." },
  "cua-ai": { kind: "youtube", youtubeId: "O2LBZ_zqmGs", title: "ĐẠI TỪ SỞ HỮU: Cách Sử Dụng Chi Tiết Và Đầy Đủ Nhất | Ms Thuỷ KISS English", source: "KISS English Center", minutes: 7, lang: "vi", note: "Cách dùng đại từ sở hữu mine, yours, his, hers và phân biệt với tính từ sở hữu my, your." },
  "hoi-duong-va-di-lai": { kind: "youtube", youtubeId: "SHXPpsIJTb0", title: "Asking for and giving directions: Easy English Conversations 💬 Episode 5", source: "BBC Learning English", minutes: 4, lang: "en", note: "Đoạn hội thoại ngắn về hỏi đường và chỉ đường, luyện các câu chỉ hướng và vị trí thường gặp." },
  "suc-khoe-va-loi-khuyen": { kind: "youtube", youtubeId: "POFfLs0Uaio", title: "Modal Verbs - How to Use Must, Have to and Should - English Grammar Lesson", source: "Oxford Online English", minutes: 11, lang: "en", note: "Phân biệt must và have to, mustn't và don't have to, và should để khuyên." },
  "ban-da-tung": { kind: "youtube", youtubeId: "dQiYjKYSH0w", title: "Thì hiện tại hoàn thành: cấu trúc, cách dùng   [Ngữ pháp tiếng Anh cơ bản - Các thì #4]", source: "Elight Learning English", minutes: 7, lang: "vi", note: "Cấu trúc have / has + V3 và các cách dùng chính của thì hiện tại hoàn thành, nền tảng để nói về trải nghiệm với ever / never." },
  "vua-moi-da-chua": { kind: "youtube", youtubeId: "8_nhtAwI0dA", title: "The present perfect with 'just', 'already' and 'yet' - 6 Minute Grammar", source: "BBC Learning English", minutes: 6, lang: "en", note: "Vị trí và nghĩa của just, already và yet trong thì hiện tại hoàn thành, có quiz cuối bài." },
};
