import type { LessonMedia } from "../types";

/** Videos and links for Tiếng Anh A1 lessons, by lesson slug; checked 2026-09-26 (oEmbed + content). */
export const MEDIA_TIENG_ANH_A1: Record<string, LessonMedia> = {
  "chao-hoi-va-gioi-thieu": { kind: "youtube", youtubeId: "qELTZre8fgk", title: "Động Từ TO BE Trong Tiếng Anh | Bài Học Ngữ Pháp Cơ Bản (Bài 1)", source: "Study English with Us!", minutes: 17, lang: "vi", note: "Cô TK giải thích cách dùng am, is, are trong câu khẳng định, phủ định, câu hỏi và những lỗi người mới hay mắc." },
  "gia-dinh-va-do-vat": { kind: "youtube", youtubeId: "a9_a0kH1XYM", title: "5 phút thành thạo 4 đại từ chỉ định this-that-these-those [Ngữ pháp tiếng Anh cơ bản-Các loại từ#15]", source: "Elight Learning English", minutes: 4, lang: "vi", note: "Bài giảng ngắn phân biệt this, that, these, those theo gần xa và số ít, số nhiều, kèm ví dụ dễ nhớ." },
  "so-tuoi-va-so-dien-thoai": { kind: "youtube", youtubeId: "nByW9tG8Imk", title: "SỐ ĐẾM TRONG TIẾNG ANH - Cách Đếm Số Từ 1 Đến 100 Chuẩn Chỉnh 100% | KISS English", source: "KISS English Center", minutes: 10, lang: "vi", note: "Cô Thủy hướng dẫn đọc số đếm từ 1 đến 100 một cách rõ ràng, dễ theo." },
  "nghe-nghiep-va-quoc-tich": { kind: "youtube", youtubeId: "QSoE8snwmuE", title: "Bạn làm nghề gì? | Cách hỏi và trả lời nghề nghiệp bằng tiếng Anh", source: "Study English with Us!", minutes: 19, lang: "vi", note: "Cô TK dạy cách hỏi và trả lời về nghề nghiệp bằng tiếng Anh. Phần quốc tịch của bài không có trong video." },
  "mot-ngay-cua-toi": { kind: "youtube", youtubeId: "q8jpjL0GPhk", title: "[Ngữ Pháp Tiếng Anh] Bài #1: THÌ HIỆN TẠI ĐƠN - Nắm Vững Các Thì Trong Tiếng Anh | KISS English", source: "KISS English Center", minutes: 16, lang: "vi", note: "Cô Thủy giải thích thì hiện tại đơn để nói thói quen hằng ngày, cách thêm -s/-es và các dấu hiệu nhận biết như always, usually." },
  "do-an-va-goi-mon": { kind: "youtube", youtubeId: "BFUaT9EqGig", title: "DANH TỪ ĐẾM ĐƯỢC và KHÔNG ĐẾM ĐƯỢC Trong Tiếng Anh (Đầy Đủ Nhất) | Ms Thuỷ KISS English", source: "KISS English Center", minutes: 12, lang: "vi", note: "Cô Thủy phân biệt danh từ đếm được và không đếm được và cách dùng từng loại, nền tảng để gọi món cho đúng." },
  "thoi-gian-va-lich-hen": { kind: "youtube", youtubeId: "6L5VJmjWO-Y", title: "Dùng giới từ chỉ thời gian: At-In-On như nào là chuẩn ? [Ngữ pháp tiếng Anh cơ bản -Các loại từ #12]", source: "Elight Learning English", minutes: 5, lang: "vi", note: "Bài giảng ngắn về quy tắc in, on, at với tháng, thứ, ngày và giờ, đúng phần giới từ của bài." },
  "so-thich": { kind: "youtube", youtubeId: "oByX5MbZCQk", title: "Like + Verb-ING, Like + Infinitive, Enjoy + Verb-ING | Learn English Grammar with Woodward English", source: "Woodward English", minutes: 9, lang: "en", note: "Bài giảng tiếng Anh chậm, rõ về động từ đi sau like, love, enjoy: V-ing hay to + động từ, và vì sao enjoy chỉ đi với V-ing." },
  "hoi-dap-hang-ngay": { kind: "youtube", youtubeId: "49bKfTBy9Tc", title: "English Grammar - Present Simple - WH- QUESTIONS", source: "English with Alex · engVid", minutes: 7, lang: "en", note: "Thầy Alex dạy công thức từ để hỏi + do/does + chủ ngữ + động từ nguyên mẫu, đúng mẫu câu hỏi Where do you live? của bài." },
  "mua-sam-va-mau-sac": { kind: "youtube", youtubeId: "QMEz-SdcE-I", title: "Đi Mua Sắm Bằng Tiếng Anh | Hỏi Giá, Trả Giá & Giao Tiếp Cơ Bản", source: "Study English with Us!", minutes: 19, lang: "vi", note: "Cô giáo dạy các câu dùng khi đi mua sắm như How much is this?, cách nói giá và từ cheap, expensive." },
  "toi-co-the": { kind: "youtube", youtubeId: "SeLYwHeOodM", title: "Can Can't Cannot | Learn English Grammar | Basic English Lesson by Woodward English", source: "Woodward English", minutes: 14, lang: "en", note: "Bài giảng tiếng Anh cơ bản về can: câu khẳng định, phủ định, câu hỏi, câu trả lời ngắn và cách phát âm can, can't." },
  "mo-ta-nguoi": { kind: "youtube", youtubeId: "9OzIMC6XCiE", title: "How to describe people in English! Easy English Conversations Episode 17", source: "BBC Learning English", minutes: 8, lang: "en", note: "Hội thoại giọng Anh rất dễ của BBC: hỏi What does he look like? và tả chiều cao, kiểu tóc, màu tóc." },
  "nha-va-noi-chon": { kind: "youtube", youtubeId: "xCrsoRmPFok", title: "THERE IS - THERE ARE in English | Sentences & Questions | Learn English Grammar | Woodward English", source: "Woodward English", minutes: 9, lang: "en", note: "Bài giảng tiếng Anh cơ bản phân biệt there is và there are, cách đặt câu phủ định và câu hỏi Is there…?, Are there…?" },
  "thanh-pho-cua-toi": { kind: "youtube", youtubeId: "Sw17ebFsCZ0", title: "14 TK: Asking for Directions - Hỏi Thăm Đường Đi", source: "Study English with Us!", minutes: 18, lang: "vi", note: "Cô TK dạy cách hỏi đường và chỉ đường bằng tiếng Anh khi đi du lịch hoặc khi có người nước ngoài hỏi mình." },
  "dang-lam-gi": { kind: "youtube", youtubeId: "ZZtHS_NU-5g", title: "[Elight] - #7 Thì hiện tại tiếp diễn: cấu trúc, cách dùng - Ngữ pháp tiếng Anh cơ bản", source: "Elight Learning English", minutes: 10, lang: "vi", note: "Bài giảng về cấu trúc am/is/are + V-ing, cách dùng thì hiện tại tiếp diễn và quy tắc thêm -ing." },
  "cuoi-tuan-vua-roi": { kind: "youtube", youtubeId: "S8boTEMrpIk", title: "WAS hay WERE? Bạn Đang Dùng Sai Rất Nhiều!", source: "Study English with Us!", minutes: 22, lang: "vi", note: "Cô TK giải thích khi nào dùng was, khi nào dùng were, cách đặt câu phủ định và câu hỏi khi kể chuyện hôm qua." },
};
