import type { LessonMedia } from "../types";

/** Videos and links for Tiếng Anh C1 lessons, by lesson slug; checked 2026-09-26 (oEmbed + content). */
export const MEDIA_TIENG_ANH_C1: Record<string, LessonMedia> = {
  "noi-tu-nhien": { kind: "youtube", youtubeId: "gHmMWBpUzgc", title: "10 ADVANCED COLLOCATIONS YOU NEED TO KNOW! C1 & C2 level vocabulary", source: "To The Point English with Ben.", minutes: 14, lang: "en", note: "Mười kết hợp từ mạnh trình độ C1–C2 kèm ví dụ, giúp câu của bạn tự nhiên như người bản xứ." },
  "tinh-luoc-va-thay-the": { kind: "youtube", youtubeId: "4clDYkIcOUI", title: "Ellipsis: How to Omit Words and Speak English Naturally", source: "English with Jennifer", minutes: 15, lang: "en", note: "Khi nào được lược bỏ từ (sau trợ động từ, động từ khuyết thiếu, to, that...) để nói gọn mà không mất ý, có bài kiểm tra nhanh." },
  "tuong-lai-nang-cao": { kind: "link", url: "https://dictionary.cambridge.org/grammar/british-grammar/future-other-expressions", title: "Future: other expressions to talk about the future", source: "Cambridge Dictionary Grammar", lang: "en", note: "Giải thích ngắn gọn be about to, be on the point of, be due to và be to kèm ví dụ chuẩn Anh." },
  "cau-tao-tu": { kind: "youtube", youtubeId: "l6XCOoO0Mpk", title: "ALL Prefixes and Suffixes! - English Lesson", source: "Learn English with Papa Teach Me", minutes: 14, lang: "en", note: "Các tiền tố, hậu tố thông dụng và cách phân biệt dis-, un-, mis-, in-/im-/ir-." },
  "tu-de-nham-va-ngon-ngu-uoc-luong": { kind: "youtube", youtubeId: "0MKoWAKhqMI", title: "6 Minute Vocabulary: Dealing with false friends", source: "BBC Learning English", minutes: 6, lang: "en", note: "Hiểu “từ quen mặt mà lạ nghĩa” là gì và cách tránh dùng nhầm." },
  "dao-ngu-de-nhan-manh": { kind: "youtube", youtubeId: "_tmLvRqcf14", title: "Câu đảo ngữ trong tiếng Anh và các loại câu đảo ngữ | IELTS FIGHTER", source: "IELTS Fighter", minutes: 7, lang: "vi", note: "Các dạng đảo ngữ để nhấn mạnh, gồm đảo ngữ sau trạng từ phủ định, kèm bài tập." },
  "cau-che-va-nhan-manh": { kind: "youtube", youtubeId: "Dj0ePce_xmE", title: "CLEFT SENTENCES | advanced complex sentences in English + TEST!", source: "Arnel's Everyday English", minutes: 21, lang: "en", note: "Từng bước câu chẻ với It, What và All để nhấn mạnh, có bài kiểm tra cuối video." },
  "dieu-kien-nang-cao": { kind: "youtube", youtubeId: "fnx7rZ9x9Wo", title: "Cách dùng CÂU ĐIỀU KIỆN ĐẢO trong tiếng Anh / Chống Liệt Tiếng Anh Ep. 27", source: "Elight Learning English", minutes: 21, lang: "vi", note: "Cách đảo ngữ câu điều kiện (Should, Were, Had đứng đầu câu) để nói trang trọng hơn." },
  "bang-thai-cach": { kind: "youtube", youtubeId: "HACjSYEfdcw", title: "Chuyên đề THỨC GIẢ ĐỊNH | Trang Anh English", source: "Trang Anh English", minutes: 19, lang: "vi", note: "Chuyên đề thức giả định: khi nào động từ giữ nguyên mẫu sau các động từ, tính từ chỉ đề nghị, yêu cầu." },
  "dong-tu-tuong-thuat": { kind: "youtube", youtubeId: "Pu_3OgQxe2s", title: "6 Minute Vocabulary: How to use English reporting verbs like 'insist', 'demand' and 'advise'", source: "BBC Learning English", minutes: 6, lang: "en", note: "Động từ tường thuật như insist, demand, advise và mẫu câu đi kèm mỗi động từ." },
  "bi-dong-nang-cao": { kind: "youtube", youtubeId: "MpsrdpUKOTA", title: "Passive Reporting Verbs in English |  IT IS SAID THAT, IT IS THOUGHT THAT", source: "Oxford English Now", minutes: 8, lang: "en", note: "Hai cách bị động tường thuật: It is said that... và He is said to..., khi nào dùng trong văn trang trọng." },
  "menh-de-quan-he-nang-cao": { kind: "youtube", youtubeId: "zvddzzLtTx0", title: "Prepositions in Relative Clauses", source: "Oxford English Now", minutes: 7, lang: "en", note: "Giới từ đặt đầu mệnh đề quan hệ (in which, to whom) hay cuối mệnh đề, và khác biệt về độ trang trọng." },
  "ngon-ngu-tinh-te": { kind: "youtube", youtubeId: "0uO_GKExLMo", title: "Polite & Professional English: How to soften your language", source: "Adam’s English Lessons · engVid", minutes: 13, lang: "en", note: "Các cách làm mềm lời nói: biến khẳng định thành ý kiến, dùng động từ khuyết thiếu, câu hỏi phủ định và cách từ chối lịch sự." },
  "van-phong-hoc-thuat": { kind: "youtube", youtubeId: "32e3QlxHq7k", title: "What is Nominalisation? How to nominalise a sentence in academic writing.", source: "Academic English UK", minutes: 8, lang: "en", note: "Cách danh từ hóa động từ, tính từ để câu học thuật gọn và khách quan hơn, có bài tập mẫu." },
  "trang-tu-binh-luan": { kind: "youtube", youtubeId: "2leLcHI9U1s", title: "19 Adverbs to Express Your Opinion in English | Build Your Vocabulary", source: "Speak Confident English", minutes: 16, lang: "en", note: "Mười chín trạng từ bình luận như apparently, arguably, admittedly để nói ra thái độ chỉ bằng một từ." },
  "viet-luan-va-tom-tat": { kind: "youtube", youtubeId: "gzdhDzAswuA", title: "Cách Paraphrase trong IELTS Writing Task 2", source: "IELTS Nguyễn Huyền", minutes: 14, lang: "vi", note: "Các cách diễn đạt lại (paraphrase) khi viết bài luận, đúng kỹ năng trọng tâm của bài." },
};
