import type { LessonMedia } from "../types";

/** Videos and links for Tiếng Anh B2 lessons, by lesson slug; checked 2026-09-26 (oEmbed + content). */
export const MEDIA_TIENG_ANH_B2: Record<string, LessonMedia> = {
  "viet-email-chuyen-nghiep": { kind: "youtube", youtubeId: "rnuE6lS531c", title: "Viết EMAIL tiếng Anh chuyên nghiệp hơn bằng 10 cụm từ này | IELTS with Datio", source: "Datio English", minutes: 6, lang: "vi", note: "Mười cụm từ giúp email công việc nghe lịch sự, chuyên nghiệp hơn." },
  "hop-va-thao-luan": { kind: "youtube", youtubeId: "WQpM0NVM0CM", title: "PAST MODALS: could have | may have | might have | must have | should have | would have - GRAMMAR", source: "Arnel's Everyday English", minutes: 14, lang: "en", note: "Phân biệt must have, might have, could have khi suy đoán về quá khứ, kèm cách đọc nối tự nhiên." },
  "tuong-thuat-loi-noi": { kind: "youtube", youtubeId: "65IYYeNbUTs", title: "Câu Trực Tiếp, Gián Tiếp trong Tiếng Anh - P1 / Chống Liệt tiếng Anh Ep. 33", source: "Elight Learning English", minutes: 13, lang: "vi", note: "Cách chuyển câu trực tiếp sang câu tường thuật: lùi thì, đổi đại từ và trạng từ thời gian." },
  "goi-dien-va-hop-truc-tuyen": { kind: "youtube", youtubeId: "PLhAzAymMsY", title: "40 English Phrases You Need for Online Meetings", source: "Maria Sheeran", minutes: 5, lang: "en", note: "Bốn mươi câu dùng khi họp online: mở đầu, xen ngang, báo lỗi âm thanh, mất kết nối, rời sớm và kết thúc." },
  "cac-thi-hoan-thanh-tiep-dien": { kind: "youtube", youtubeId: "nOid1SbUo1k", title: "Thì quá khứ hoàn thành tiếp diễn: Công thức, cách dùng, dấu hiệu nhận biết | Anh Ngữ ZIM", source: "ZIM Academy", minutes: 5, lang: "vi", note: "Cách dùng, công thức và dấu hiệu của thì quá khứ hoàn thành tiếp diễn." },
  "tiec-nuoi-va-gia-dinh": { kind: "youtube", youtubeId: "njrEFGt4l5k", title: "CÂU ĐIỀU KIỆN Hỗn Hợp & các loại CÂU ĐIỀU KIỆN Nâng Cao khác / Chống Liệt Tiếng Anh Ep. 28", source: "Elight Learning English", minutes: 21, lang: "vi", note: "Câu điều kiện hỗn hợp nối quá khứ với hiện tại và các dạng điều kiện nâng cao." },
  "dieu-kien-khong-chi-if": { kind: "link", url: "https://dictionary.cambridge.org/grammar/british-grammar/conditionals-other-expressions-unless-should-as-long-as", title: "Conditionals: other expressions (unless, should, as long as)", source: "Cambridge Dictionary", lang: "en", note: "Trang ngữ pháp Cambridge về unless, as long as, providing, otherwise và supposing, có nhiều ví dụ." },
  "dong-tu-khuyet-thieu-qua-khu": { kind: "youtube", youtubeId: "G0L3EnSDWEo", title: "CẤU TRÚC 23/111 - SHOULD HAVE DONE - Lẽ ra nên làm - Thắng Phạm", source: "Thắng Phạm", minutes: 15, lang: "vi", note: "Cách dùng should have done để nói điều lẽ ra nên làm, với nhiều ví dụ giao tiếp." },
  "gia-dinh-khong-that": { kind: "youtube", youtubeId: "QMAcLQ7joQo", title: "English grammar - UNREAL PAST (if, if only, wish, it's time) - gramática inglesa", source: "Your English Web: Weekly English video lessons", minutes: 5, lang: "en", note: "Vì sao dùng thì quá khứ sau wish, if only, would rather và it's time để nói điều không có thật." },
  "thuyet-trinh": { kind: "youtube", youtubeId: "NVibktx8jgs", title: "20 cụm từ phải dùng khi Thuyết Trình bằng tiếng Anh | IELTS with Datio", source: "Datio English", minutes: 3, lang: "vi", note: "Hai mươi cụm dẫn dắt để mở đầu, chuyển ý và kết thúc bài thuyết trình." },
  "mo-ta-so-lieu": { kind: "youtube", youtubeId: "e4kYvMEQU3w", title: "Describe Trends in Business English - Describing Statistics, Sales and Market Trends", source: "Oxford Online English", minutes: 15, lang: "en", note: "Cách mô tả xu hướng, tỷ lệ phần trăm và tốc độ thay đổi của doanh số, đúng ngữ cảnh báo cáo công việc." },
  "tu-noi-nang-cao": { kind: "youtube", youtubeId: "nLxL-O7OzWY", title: "Vocabulary - however, nevertheless, nonetheless, in addition, moreover, furthermore", source: "Interactive English", minutes: 12, lang: "en", note: "Phân biệt however, nevertheless, moreover, furthermore và mức độ trang trọng của từng từ." },
  "rut-gon-menh-de": { kind: "youtube", youtubeId: "zB5BE5I73Ew", title: "Mệnh Đề Phân Từ là gì? Tất cả những gì bạn cần biết về chủ điểm này! Chống Liệt Tiếng Anh Ep. 21", source: "Elight Learning English", minutes: 14, lang: "vi", note: "Cách rút gọn mệnh đề bằng phân từ V-ing và V3 với nhiều ví dụ." },
  "dam-phan-va-thuyet-phuc": { kind: "youtube", youtubeId: "-3mFnAk9sbw", title: "How to Negotiate in English - Business English Lesson", source: "Oxford Online English", minutes: 19, lang: "en", note: "Qua một tình huống đàm phán mẫu, học cách nêu lập trường, đề xuất, nhượng bộ và từ chối lịch sự." },
  "mao-tu": { kind: "youtube", youtubeId: "Z4AhZLylP5o", title: "Mạo từ tiếng Anh - Bí kíp tuyệt mật siêu dễ hiểu [Ngữ pháp tiếng Anh cơ bản - Các loại từ #14.]", source: "Elight Learning English", minutes: 23, lang: "vi", note: "Khi nào dùng a, an, the và khi nào không dùng mạo từ." },
  "to-v-hay-v-ing": { kind: "youtube", youtubeId: "9zAPiZ4uS6g", title: "Remember to do (infinitive) | Remember doing ( gerund) | With a change in meaning", source: "Oxford English Now", minutes: 10, lang: "en", note: "Nghĩa khác nhau của remember, forget, regret, try, stop và mean khi đi với to V hay V-ing, có bài tập cuối video." },
  "than-phien-va-xu-ly": { kind: "youtube", youtubeId: "TSFo3RdebD0", title: "How to handle a complaint - Business English", source: "Simple English Videos", minutes: 8, lang: "en", note: "So sánh một cách xử lý khiếu nại tệ và một cách tốt để học lời xin lỗi, giải thích và đề xuất giải pháp." },
};
