import type { SentenceDrill } from "../my-plan";

const A1 = "tieng-anh-a1";
const A2 = "tieng-anh-a2";

const toBe = { course: A1, lesson: "chao-hoi-va-gioi-thieu", title: "Động từ to be: am, is, are" };
const jobs = { course: A1, lesson: "nghe-nghiep-va-quoc-tich", title: "a/an với nghề nghiệp, quốc tịch và câu hỏi Wh- với to be" };
const family = { course: A1, lesson: "gia-dinh-va-do-vat", title: "a/an, số nhiều, this/that và my/your" };
const myDay = { course: A1, lesson: "mot-ngay-cua-toi", title: "Thì hiện tại đơn và trạng từ tần suất" };
const time = { course: A1, lesson: "thoi-gian-va-lich-hen", title: "Nói giờ, thứ, tháng và giới từ in/on/at" };
const hobbies = { course: A1, lesson: "so-thich", title: "like, love, enjoy, hate + V-ing" };
const habits = { course: A1, lesson: "hoi-dap-hang-ngay", title: "Câu hỏi Wh- với do/does và cách nói tần suất" };
const food = { course: A1, lesson: "do-an-va-goi-mon", title: "Danh từ đếm được, không đếm được và cách gọi món" };
const shopping = { course: A1, lesson: "mua-sam-va-mau-sac", title: "Quần áo, màu sắc, How much is/are và tính từ đứng trước danh từ" };
const can = { course: A1, lesson: "toi-co-the", title: "Can và can't: khả năng và xin phép" };
const looks = { course: A1, lesson: "mo-ta-nguoi", title: "Have got, has got và tính từ tả ngoại hình" };
const home = { course: A1, lesson: "nha-va-noi-chon", title: "There is, there are và giới từ chỉ vị trí" };
const city = { course: A1, lesson: "thanh-pho-cua-toi", title: "Nơi chốn trong thành phố, giới từ và chỉ đường đơn giản" };
const now = { course: A1, lesson: "dang-lam-gi", title: "Thì hiện tại tiếp diễn: am, is, are + V-ing" };
const wasWere = { course: A1, lesson: "cuoi-tuan-vua-roi", title: "Was, were và there was, there were" };

const past = { course: A2, lesson: "hom-qua-ban-lam-gi", title: "Thì quá khứ đơn: kể chuyện đã xảy ra" };
const pastQ = { course: A2, lesson: "ky-nghi-cua-toi", title: "Câu hỏi Wh- ở quá khứ đơn và động từ bất quy tắc" };
const usedTo = { course: A2, lesson: "ngay-xua-toi-tung", title: "Used to: thói quen và trạng thái trong quá khứ" };
const pastCont = { course: A2, lesson: "qua-khu-tiep-dien", title: "Thì quá khứ tiếp diễn với when và while" };
const life = { course: A2, lesson: "tieu-su", title: "Before, after, when với quá khứ đơn và cách nói ngày tháng, năm" };
const plans = { course: A2, lesson: "ke-hoach-cuoi-tuan", title: "Be going to và hiện tại tiếp diễn chỉ tương lai" };
const predict = { course: A2, lesson: "du-doan-tuong-lai", title: "Will, won't và might để dự đoán" };
const ifs = { course: A2, lesson: "dieu-kien-loai-0-va-1", title: "Câu điều kiện loại 0 và loại 1" };
const compare = { course: A2, lesson: "so-sanh-va-mua-sam", title: "So sánh hơn, so sánh nhất và as...as" };
const amount = { course: A2, lesson: "bao-nhieu", title: "Much, many, a lot of, a few, a little" };
const tooEnough = { course: A2, lesson: "qua-va-khong-du", title: "Too, enough, too much và too many" };
const whose = { course: A2, lesson: "cua-ai", title: "Đại từ tân ngữ, đại từ sở hữu, whose và 's" };
const directions = { course: A2, lesson: "hoi-duong-va-di-lai", title: "Câu mệnh lệnh để chỉ đường và nói về phương tiện" };
const advice = { course: A2, lesson: "suc-khoe-va-loi-khuyen", title: "Should, have to và must" };
const ever = { course: A2, lesson: "ban-da-tung", title: "Thì hiện tại hoàn thành với ever và never" };
const justYet = { course: A2, lesson: "vua-moi-da-chua", title: "Hiện tại hoàn thành với just, already và yet" };

/** Sentence-splitting drills for A1 and A2 grammar, easiest first. */
export const DRILLS_A1_A2: SentenceDrill[] = [
  // ---------- A1 ----------
  {
    id: "a1-woman-is-nurse",
    level: "A1",
    en: "The woman next to my sister is a nurse from Hue.",
    verb: "is",
    subject: "The woman next to my sister",
    sign: "Is là động từ to be, đi với một người (she). Next to my sister chỉ nói rõ người phụ nữ nào, nên chủ ngữ là cả cụm The woman next to my sister, không phải my sister.",
    chunks: ["The woman", "next to my sister", "is", "a nurse", "from Hue"],
    meaning: "Người phụ nữ bên cạnh chị gái tôi là y tá, quê ở Huế.",
    review: toBe,
  },
  {
    id: "a1-an-engineer-doctors",
    level: "A1",
    en: "My father is an engineer, and my two uncles are doctors.",
    verb: "is (vế đầu) và are (vế sau)",
    subject: "My father (vế đầu), my two uncles (vế sau)",
    sign: "Cắt câu ở and. Một người làm nghề gì thì có a hoặc an: an engineer (dùng an vì engineer bắt đầu bằng âm nguyên âm). Nhiều người thì bỏ a, thêm -s (doctors), và to be đổi thành are.",
    chunks: ["My father", "is", "an engineer,", "and my two uncles", "are", "doctors"],
    meaning: "Bố tôi là kỹ sư, còn hai người chú của tôi là bác sĩ.",
    review: jobs,
  },
  {
    id: "a1-where-is-manager-from",
    level: "A1",
    en: "Where is the new manager of your company from?",
    verb: "is",
    subject: "the new manager of your company",
    sign: "Câu hỏi Wh- với to be: từ để hỏi + is + chủ ngữ. Chủ ngữ là cả cụm dài the new manager of your company, nằm giữa is và from. Where ở đầu câu đi với from ở cuối câu: Where … from? là hỏi đến từ đâu.",
    chunks: ["Where", "is", "the new manager", "of your company", "from?"],
    meaning: "Người quản lý mới của công ty bạn quê ở đâu?",
    review: jobs,
  },
  {
    id: "a1-those-boxes",
    level: "A1",
    en: "Those two boxes next to the door are for my parents.",
    verb: "are",
    subject: "Those two boxes next to the door",
    sign: "Those chỉ nhiều vật ở xa người nói, nên đi với are và danh từ số nhiều (boxes thêm -es vì tận cùng bằng x). Next to the door nói rõ những cái hộp nào; động từ chính are đứng sau cả cụm này.",
    chunks: ["Those two boxes", "next to the door", "are", "for my parents"],
    meaning: "Hai cái hộp cạnh cửa kia là cho bố mẹ tôi.",
    review: family,
  },
  {
    id: "a1-visit-them",
    level: "A1",
    en: "Our parents live near us, so we visit them every Sunday.",
    verb: "live (vế đầu) và visit (vế sau)",
    subject: "Our parents (vế đầu), we (vế sau)",
    sign: "Cắt câu ở so (nên). Our (của chúng tôi) đứng trước danh từ. Sau giới từ và động từ dùng us, them (near us, visit them), không dùng we, they. Them ở vế sau chính là our parents.",
    chunks: ["Our parents", "live", "near us,", "so we", "visit them", "every Sunday"],
    meaning: "Bố mẹ chúng tôi sống gần nhà chúng tôi, nên Chủ nhật nào chúng tôi cũng sang thăm bố mẹ.",
    review: family,
  },
  {
    id: "a1-woman-above-works",
    level: "A1",
    en: "The woman in the flat above us works at a hospital in the city centre.",
    verb: "works",
    subject: "The woman in the flat above us",
    sign: "Hiện tại đơn nói về việc làm thường ngày. Works có -s vì chủ ngữ là một người (she). In the flat above us chỉ nói rõ người phụ nữ nào; đừng tưởng the flat hay us là chủ ngữ.",
    chunks: ["The woman", "in the flat above us", "works", "at a hospital", "in the city centre"],
    meaning: "Người phụ nữ ở căn hộ phía trên nhà chúng tôi làm việc ở một bệnh viện trong trung tâm thành phố.",
    review: myDay,
  },
  {
    id: "a1-always-usually",
    level: "A1",
    en: "My boss is always busy on Mondays, so she usually has lunch at her desk.",
    verb: "is (vế đầu) và has (vế sau)",
    subject: "My boss (vế đầu), she (vế sau)",
    sign: "Trạng từ tần suất đứng sau to be (is always) nhưng đứng trước động từ thường (usually has). Has là have của she ở hiện tại đơn; have lunch là ăn trưa, không phải “có” bữa trưa.",
    chunks: ["My boss", "is always busy", "on Mondays,", "so she", "usually has lunch", "at her desk"],
    meaning: "Thứ Hai nào sếp tôi cũng bận, nên chị ấy thường ăn trưa ngay tại bàn làm việc.",
    review: myDay,
  },
  {
    id: "a1-doesnt-eat-because",
    level: "A1",
    en: "My husband doesn't eat breakfast at home because he leaves very early.",
    verb: "doesn't eat (vế đầu) và leaves (vế sau)",
    subject: "My husband (vế đầu), he (vế sau)",
    sign: "Doesn't + động từ nguyên mẫu là phủ định của hiện tại đơn với he, she, it: đã có doesn't thì eat không thêm -s. Because mở đầu vế nói lý do; vế này không có doesn't nên leaves vẫn có -s.",
    chunks: ["My husband", "doesn't eat", "breakfast", "at home", "because he leaves", "very early"],
    meaning: "Chồng tôi không ăn sáng ở nhà vì anh ấy ra khỏi nhà rất sớm.",
    review: myDay,
  },
  {
    id: "a1-meeting-at-on",
    level: "A1",
    en: "The meeting with our new customers is at ten o'clock on Friday morning.",
    verb: "is",
    subject: "The meeting with our new customers",
    sign: "Chủ ngữ là The meeting (một cuộc họp); with our new customers chỉ nói rõ cuộc họp nào, nên động từ là is, không phải are. At + giờ (at ten o'clock); có tên thứ kèm buổi thì dùng on (on Friday morning), không dùng in.",
    chunks: ["The meeting", "with our new customers", "is", "at ten o'clock", "on Friday morning"],
    meaning: "Cuộc họp với các khách hàng mới của chúng tôi diễn ra lúc mười giờ sáng thứ Sáu.",
    review: time,
  },
  {
    id: "a1-enjoys-hates",
    level: "A1",
    en: "My wife enjoys cooking for our friends, but she hates washing the dishes afterwards.",
    verb: "enjoys (vế đầu) và hates (vế sau); cooking và washing không phải động từ chính",
    subject: "My wife (vế đầu), she (vế sau)",
    sign: "Enjoy, like, love, hate + V-ing: thích hay ghét làm việc gì. Cooking và washing là việc được thích hoặc bị ghét, đứng sau động từ chính. Enjoys, hates có -s vì chủ ngữ là một người.",
    chunks: ["My wife", "enjoys", "cooking for our friends,", "but she", "hates", "washing the dishes", "afterwards"],
    meaning: "Vợ tôi thích nấu ăn cho bạn bè, nhưng lại ghét rửa bát sau đó.",
    review: hobbies,
  },
  {
    id: "a1-does-son-like",
    level: "A1",
    en: "Does your son like playing football with his friends at the weekend?",
    verb: "does … like (playing không phải động từ chính)",
    subject: "your son",
    sign: "Câu hỏi có hay không ở hiện tại đơn: Does + chủ ngữ + động từ nguyên mẫu? Đã có does nên like không thêm -s. Playing football là việc được thích. Trả lời ngắn: Yes, he does. / No, he doesn't.",
    chunks: ["Does", "your son", "like", "playing football", "with his friends", "at the weekend?"],
    meaning: "Con trai bạn có thích đá bóng với bạn bè vào cuối tuần không?",
    review: hobbies,
  },
  {
    id: "a1-how-often-long-subject",
    level: "A1",
    en: "How often do you and your husband visit your parents in the countryside?",
    verb: "do … visit",
    subject: "you and your husband",
    sign: "How often…? hỏi bao lâu một lần. Công thức: từ để hỏi + do + chủ ngữ + động từ nguyên mẫu. Chủ ngữ ở đây dài: you and your husband nằm giữa do và visit; chủ ngữ nhiều người nên dùng do, không dùng does.",
    chunks: ["How often", "do", "you and your husband", "visit", "your parents", "in the countryside?"],
    meaning: "Bao lâu thì vợ chồng bạn về quê thăm bố mẹ một lần?",
    review: habits,
  },
  {
    id: "a1-any-milk-some-eggs",
    level: "A1",
    en: "There isn't any milk in the fridge, but there are some eggs on the table.",
    verb: "isn't (trong there isn't, vế đầu) và are (trong there are, vế sau)",
    subject: "any milk (vế đầu), some eggs (vế sau); there chỉ là chủ ngữ hình thức",
    sign: "Milk không đếm được: đi với isn't và không thêm -s. Câu phủ định dùng any, câu khẳng định dùng some. Eggs đếm được, số nhiều, nên đi với there are.",
    chunks: ["There isn't", "any milk", "in the fridge,", "but there are", "some eggs", "on the table"],
    meaning: "Trong tủ lạnh không còn chút sữa nào, nhưng trên bàn có mấy quả trứng.",
    review: food,
  },
  {
    id: "a1-how-much-jeans",
    level: "A1",
    en: "How much are those black jeans in the shop window?",
    verb: "are",
    subject: "those black jeans in the shop window",
    sign: "Jeans luôn là số nhiều nên hỏi giá bằng How much are…?, không dùng is. Tính từ chỉ màu đứng trước danh từ: black jeans, không nói jeans black. In the shop window chỉ nói rõ cái quần nào.",
    chunks: ["How much", "are", "those black jeans", "in the shop window?"],
    meaning: "Cái quần bò đen trong tủ kính kia giá bao nhiêu?",
    review: shopping,
  },
  {
    id: "a1-cant-read",
    level: "A1",
    en: "My grandmother can't read the small print on medicine bottles without her glasses.",
    verb: "can't read",
    subject: "My grandmother",
    sign: "Can't + động từ nguyên mẫu: không có khả năng làm gì. Sau can't, read không thêm -s và không có to. Without her glasses là khi không đeo kính.",
    chunks: ["My grandmother", "can't read", "the small print", "on medicine bottles", "without her glasses"],
    meaning: "Bà tôi không đọc được chữ nhỏ trên lọ thuốc nếu không đeo kính.",
    review: can,
  },
  {
    id: "a1-shes-tall-shes-got",
    level: "A1",
    en: "She's very tall, and she's got long curly black hair.",
    verb: "'s = is (vế đầu) và 's got = has got (vế sau)",
    subject: "She",
    sign: "Cùng là 's nhưng khác nghĩa. She's very tall: 's là is, vì chiều cao dùng to be. She's got: 's là has, vì có got theo sau; has got là có (tóc, mắt, kính). Ba tính từ đứng theo thứ tự độ dài, kiểu, màu: long curly black.",
    chunks: ["She's", "very tall,", "and she's got", "long curly black hair"],
    meaning: "Cô ấy rất cao và có mái tóc đen, dài và xoăn.",
    review: looks,
  },
  {
    id: "a1-what-does-look-like",
    level: "A1",
    en: "What does your new manager look like?",
    verb: "does … look like",
    subject: "your new manager",
    sign: "What does … look like? hỏi ngoại hình: trông thế nào. Like ở đây không có nghĩa là thích; look like đi liền nhau là trông giống. Câu trả lời tả dáng người, tóc, mắt: She's tall and she's got short hair.",
    chunks: ["What", "does", "your new manager", "look like?"],
    meaning: "Người quản lý mới của bạn trông thế nào?",
    review: looks,
  },
  {
    id: "a1-there-are-photos",
    level: "A1",
    en: "There are some old family photos on the wall behind my bed.",
    verb: "are (trong there are)",
    subject: "some old family photos; there chỉ là chủ ngữ hình thức",
    sign: "There are + danh từ số nhiều: ở đâu đó có những thứ gì. Không dịch “có” thành have. Hai cụm vị trí nối nhau: on the wall (trên tường), rồi behind my bed nói rõ bức tường nào.",
    chunks: ["There are", "some old family photos", "on the wall", "behind my bed"],
    meaning: "Trên bức tường phía sau giường tôi có mấy tấm ảnh gia đình cũ.",
    review: home,
  },
  {
    id: "a1-opposite-next-to",
    level: "A1",
    en: "The new pharmacy is on Le Loi Street, opposite the park and next to a small café.",
    verb: "is",
    subject: "The new pharmacy",
    sign: "Sau is là ba cụm chỉ vị trí đứng nối tiếp, cụm nào cũng trả lời câu hỏi ở đâu. On + tên đường. Opposite (đối diện) không có of; next to (bên cạnh) phải đủ cả hai từ.",
    chunks: ["The new pharmacy", "is", "on Le Loi Street,", "opposite the park", "and next to a small café"],
    meaning: "Hiệu thuốc mới nằm trên đường Lê Lợi, đối diện công viên và cạnh một quán cà phê nhỏ.",
    review: city,
  },
  {
    id: "a1-look-is-waving",
    level: "A1",
    en: "Look! The man at the bus stop over there is waving at you.",
    verb: "is waving (Look! là một câu mệnh lệnh riêng)",
    subject: "The man at the bus stop over there",
    sign: "Look! báo hiệu việc đang xảy ra ngay lúc nói. Is waving (is + V-ing) là hiện tại tiếp diễn. Chủ ngữ là The man; at the bus stop over there chỉ nói rõ người đàn ông nào.",
    chunks: ["Look!", "The man", "at the bus stop", "over there", "is waving", "at you"],
    meaning: "Nhìn kìa! Người đàn ông ở bến xe buýt đằng kia đang vẫy tay với bạn.",
    review: now,
  },
  {
    id: "a1-usually-but-today",
    level: "A1",
    en: "My father usually drives to work, but today he is taking the bus.",
    verb: "drives (vế đầu) và is taking (vế sau)",
    subject: "My father (vế đầu), he (vế sau)",
    sign: "Usually đi với hiện tại đơn (drives): thói quen thường ngày. Today đi với hiện tại tiếp diễn (is taking): hôm nay khác thường. Cắt câu ở but để thấy hai thì khác nhau.",
    chunks: ["My father", "usually drives", "to work,", "but today", "he", "is taking", "the bus"],
    meaning: "Bố tôi thường lái xe đi làm, nhưng hôm nay ông đi xe buýt.",
    review: now,
  },
  {
    id: "a1-was-were",
    level: "A1",
    en: "The hotel was clean and quiet, but the rooms were very small.",
    verb: "was (vế đầu) và were (vế sau)",
    subject: "The hotel (vế đầu), the rooms (vế sau)",
    sign: "Was và were là quá khứ của to be. The hotel là một vật nên dùng was; the rooms là nhiều vật nên dùng were. Câu kể chuyện đã qua (chẳng hạn một chuyến đi) dù không có từ yesterday.",
    chunks: ["The hotel", "was", "clean and quiet,", "but the rooms", "were", "very small"],
    meaning: "Khách sạn sạch sẽ và yên tĩnh, nhưng các phòng thì rất nhỏ.",
    review: wasWere,
  },
  {
    id: "a1-there-were-people",
    level: "A1",
    en: "There were a lot of people at the night market last Saturday, so it was very noisy.",
    verb: "were (trong there were, vế đầu) và was (vế sau)",
    subject: "a lot of people (vế đầu; there chỉ là chủ ngữ hình thức), it (vế sau)",
    sign: "There were + danh từ số nhiều (people) là quá khứ của there are. Last Saturday báo hiệu quá khứ, không có on hay the đứng trước. Vế sau so it was: it chỉ không khí ở chợ đêm hôm đó.",
    chunks: ["There were", "a lot of people", "at the night market", "last Saturday,", "so it was", "very noisy"],
    meaning: "Thứ Bảy tuần trước chợ đêm rất đông người, nên rất ồn ào.",
    review: wasWere,
  },
  {
    id: "a1-what-does-man-do",
    level: "A1",
    en: "What does the man next to your father do?",
    verb: "does … do (do ở cuối là động từ chính, does chỉ là trợ động từ)",
    subject: "the man next to your father",
    sign: "What + does + chủ ngữ + do? là câu hỏi nghề nghiệp: người đó làm nghề gì. Does chỉ để tạo câu hỏi; do ở cuối mới là động từ chính (làm). Chủ ngữ the man next to your father nằm giữa hai từ này.",
    chunks: ["What", "does", "the man", "next to your father", "do?"],
    meaning: "Người đàn ông bên cạnh bố bạn làm nghề gì?",
    review: habits,
  },

  // ---------- A2 ----------
  {
    id: "a2-cleaned-and-went",
    level: "A2",
    en: "Last Saturday my wife and I cleaned the whole house and then went to the cinema.",
    verb: "cleaned và went (hai động từ chung một chủ ngữ)",
    subject: "my wife and I",
    sign: "Last Saturday báo hiệu quá khứ đơn. Cleaned là động từ có quy tắc (thêm -ed); went là quá khứ bất quy tắc của go. And then nối hai việc xảy ra nối tiếp, chủ ngữ my wife and I không nhắc lại.",
    chunks: ["Last Saturday", "my wife and I", "cleaned", "the whole house", "and then went", "to the cinema"],
    meaning: "Thứ Bảy tuần trước vợ tôi và tôi dọn dẹp cả nhà rồi đi xem phim.",
    review: past,
  },
  {
    id: "a2-who-did-you-go-with",
    level: "A2",
    en: "Who did you go to the wedding with last month?",
    verb: "did … go",
    subject: "you",
    sign: "Từ để hỏi + did + chủ ngữ + động từ nguyên mẫu: có did nên go không đổi thành went. Who ở đầu câu đi với with ở cuối: Who … with? là hỏi đi cùng ai. Who không phải chủ ngữ; chủ ngữ là you.",
    chunks: ["Who", "did", "you", "go", "to the wedding", "with", "last month?"],
    meaning: "Tháng trước bạn đi dự đám cưới với ai?",
    review: pastQ,
  },
  {
    id: "a2-didnt-use-to",
    level: "A2",
    en: "I didn't use to like vegetables when I was a child, but now I eat them every day.",
    verb: "didn't use to like (vế đầu) và eat (vế sau); was thuộc vế when",
    subject: "I",
    sign: "Didn't use to + động từ nguyên mẫu: ngày xưa không như vậy, bây giờ đã khác. Đã có didn't thì viết use to, không có d. When I was a child chỉ nói thời điểm; vế but now dùng hiện tại đơn cho thói quen bây giờ.",
    chunks: ["I", "didn't use to like", "vegetables", "when I was a child,", "but now I", "eat them", "every day"],
    meaning: "Hồi nhỏ tôi không thích rau, nhưng bây giờ ngày nào tôi cũng ăn rau.",
    review: usedTo,
  },
  {
    id: "a2-there-used-to-be",
    level: "A2",
    en: "There used to be a small cinema on this street, but now it's a car park.",
    verb: "used to be (vế đầu) và 's = is (vế sau)",
    subject: "a small cinema (vế đầu; there chỉ là chủ ngữ hình thức), it (vế sau)",
    sign: "There used to be + danh từ: ngày xưa ở đây có cái gì, bây giờ không còn. Used ở đây không có nghĩa là dùng. Vế sau now it's (it is) nói hiện tại: chỗ đó giờ là bãi đỗ xe.",
    chunks: ["There used to be", "a small cinema", "on this street,", "but now", "it's", "a car park"],
    meaning: "Ngày xưa trên con phố này có một rạp chiếu phim nhỏ, nhưng bây giờ chỗ đó là bãi đỗ xe.",
    review: usedTo,
  },
  {
    id: "a2-while-was-waiting",
    level: "A2",
    en: "While I was waiting for the bus this morning, I saw an old friend from school.",
    verb: "was waiting (vế While) và saw (vế chính)",
    subject: "I",
    sign: "While đứng trước việc dài đang diễn ra: was waiting (was + V-ing, quá khứ tiếp diễn). Việc ngắn xảy ra giữa lúc đó dùng quá khứ đơn: saw (quá khứ của see). Vế chính bắt đầu sau dấu phẩy.",
    chunks: ["While I was waiting", "for the bus", "this morning,", "I", "saw", "an old friend", "from school"],
    meaning: "Sáng nay trong lúc đang chờ xe buýt, tôi gặp một người bạn cũ hồi đi học.",
    review: pastCont,
  },
  {
    id: "a2-after-finishing",
    level: "A2",
    en: "After finishing university, my sister moved to Ho Chi Minh City and found a job in a bank.",
    verb: "moved và found (finishing không phải động từ chính)",
    subject: "my sister",
    sign: "After + V-ing (after finishing): sau khi làm xong việc gì. Cụm này không có chủ ngữ riêng; người học xong chính là my sister ở vế chính. Moved (thêm -ed) và found (quá khứ của find) là hai việc nối tiếp.",
    chunks: ["After finishing university,", "my sister", "moved", "to Ho Chi Minh City", "and found", "a job", "in a bank"],
    meaning: "Học xong đại học, chị gái tôi chuyển vào Thành phố Hồ Chí Minh và tìm được việc ở một ngân hàng.",
    review: life,
  },
  {
    id: "a2-before-he-opened",
    level: "A2",
    en: "Before he opened his own restaurant, my uncle worked as a cook in a hotel for ten years.",
    verb: "opened (vế Before) và worked (vế chính)",
    subject: "he (vế Before), my uncle (vế chính); he chính là my uncle",
    sign: "Vế Before đứng đầu câu, có dấu phẩy, kể việc xảy ra sau. Tiếng Anh cho phép he đứng trước người mà nó chỉ: he ở đây là my uncle. Worked … for ten years là quá khứ đơn vì quãng thời gian đó đã kết thúc.",
    chunks: ["Before he opened", "his own restaurant,", "my uncle", "worked", "as a cook", "in a hotel", "for ten years"],
    meaning: "Trước khi mở nhà hàng riêng, chú tôi đã làm đầu bếp ở một khách sạn suốt mười năm.",
    review: life,
  },
  {
    id: "a2-are-you-going-to-buy",
    level: "A2",
    en: "Are you and your husband going to buy a new flat this year?",
    verb: "are … going to buy",
    subject: "you and your husband",
    sign: "Câu hỏi với be going to: đảo are lên trước chủ ngữ. Chủ ngữ you and your husband nằm giữa are và going to buy. Going ở đây không có nghĩa là đi; be going to + động từ nguyên mẫu là dự định.",
    chunks: ["Are", "you and your husband", "going to buy", "a new flat", "this year?"],
    meaning: "Năm nay vợ chồng bạn có định mua căn hộ mới không?",
    review: plans,
  },
  {
    id: "a2-im-meeting-friday",
    level: "A2",
    en: "I'm meeting my old classmates at a restaurant near the station on Friday evening.",
    verb: "'m meeting = am meeting",
    subject: "I",
    sign: "Am + V-ing trông như việc đang xảy ra, nhưng on Friday evening cho biết đây là tương lai: một cuộc hẹn đã sắp xếp (có người, có chỗ, có giờ). Phải nhìn cụm thời gian ở cuối câu mới biết.",
    chunks: ["I'm meeting", "my old classmates", "at a restaurant", "near the station", "on Friday evening"],
    meaning: "Tối thứ Sáu tôi hẹn gặp các bạn học cũ ở một nhà hàng gần nhà ga.",
    review: plans,
  },
  {
    id: "a2-raining-ill-take",
    level: "A2",
    en: "It's raining really hard, so I'll take a taxi to the office today.",
    verb: "'s raining (vế đầu) và 'll take = will take (vế sau)",
    subject: "It (vế đầu), I (vế sau)",
    sign: "It's raining là hiện tại tiếp diễn: trời đang mưa. I'll (I will) + động từ nguyên mẫu: quyết định ngay lúc nói, sau khi thấy trời mưa, chứ không phải kế hoạch từ trước.",
    chunks: ["It's raining", "really hard,", "so I'll take", "a taxi", "to the office", "today"],
    meaning: "Trời đang mưa to quá, nên hôm nay tôi sẽ đi taxi đến cơ quan.",
    review: plans,
  },
  {
    id: "a2-might-depends",
    level: "A2",
    en: "We might go to the beach this weekend, but it depends on the weather.",
    verb: "might go (vế đầu) và depends (vế sau)",
    subject: "We (vế đầu), it (vế sau)",
    sign: "Might + động từ nguyên mẫu: có thể sẽ, chưa chắc chắn (kém chắc hơn will). Sau might không có to. Vế sau it depends on…: còn tùy vào…; it chỉ chuyện có đi biển hay không.",
    chunks: ["We", "might go", "to the beach", "this weekend,", "but it depends", "on the weather"],
    meaning: "Cuối tuần này có thể chúng tôi sẽ đi biển, nhưng còn tùy thời tiết.",
    review: predict,
  },
  {
    id: "a2-dont-think-will",
    level: "A2",
    en: "I don't think the new bridge will be ready before the end of the year.",
    verb: "don't think (của cả câu) và will be (trong ý được nghĩ)",
    subject: "I (cho don't think), the new bridge (cho will be)",
    sign: "I don't think + câu: phủ định đặt ở think, nhưng nghĩa là tôi nghĩ việc đó sẽ không xảy ra; đừng hiểu là tôi không nghĩ. Ý được nghĩ là the new bridge will be ready: will + be để dự đoán.",
    chunks: ["I don't think", "the new bridge", "will be ready", "before the end of the year"],
    meaning: "Tôi nghĩ cây cầu mới sẽ không xong trước cuối năm.",
    review: predict,
  },
  {
    id: "a2-zero-if-coffee",
    level: "A2",
    en: "If I drink coffee in the evening, I don't sleep well at night.",
    verb: "drink (vế If) và don't sleep (vế chính)",
    subject: "I",
    sign: "If + hiện tại đơn, hiện tại đơn: câu điều kiện loại 0, chuyện lần nào cũng vậy (hễ… là…). Không có will vì đây không phải dự đoán cho một lần trong tương lai mà là điều luôn đúng với tôi.",
    chunks: ["If I drink coffee", "in the evening,", "I", "don't sleep well", "at night"],
    meaning: "Hễ buổi tối uống cà phê là đêm đó tôi ngủ không ngon.",
    review: ifs,
  },
  {
    id: "a2-wont-unless",
    level: "A2",
    en: "We won't finish the project on time unless everyone works this weekend.",
    verb: "won't finish (vế chính) và works (vế unless)",
    subject: "We (vế chính), everyone (vế unless)",
    sign: "Vế chính đứng trước, vế unless đứng sau nên không có dấu phẩy. Unless = if … not (trừ khi). Sau unless dùng hiện tại đơn dù nói về tương lai; works có -s vì everyone đi với động từ số ít.",
    chunks: ["We", "won't finish", "the project", "on time", "unless everyone works", "this weekend"],
    meaning: "Chúng ta sẽ không xong dự án đúng hạn, trừ khi cuối tuần này mọi người đều đi làm.",
    review: ifs,
  },
  {
    id: "a2-much-more-expensive",
    level: "A2",
    en: "Flats in the city centre are much more expensive than houses in my village.",
    verb: "are",
    subject: "Flats in the city centre",
    sign: "Tính từ dài (expensive) so sánh hơn bằng more … than. Much đứng trước more để nhấn mạnh: đắt hơn nhiều. Chủ ngữ là Flats (số nhiều nên dùng are); in the city centre chỉ nói rõ căn hộ ở đâu.",
    chunks: ["Flats", "in the city centre", "are", "much more expensive", "than houses", "in my village"],
    meaning: "Căn hộ ở trung tâm thành phố đắt hơn nhiều so với nhà ở làng tôi.",
    review: compare,
  },
  {
    id: "a2-cheapest-not-as-good",
    level: "A2",
    en: "The cheapest phone in this shop is not as good as my old one.",
    verb: "is",
    subject: "The cheapest phone in this shop",
    sign: "The + tính từ-est là so sánh nhất: the cheapest (rẻ nhất). Cả cụm The cheapest phone in this shop là chủ ngữ. Not as + tính từ + as: không bằng. One thay cho phone để khỏi lặp lại.",
    chunks: ["The cheapest phone", "in this shop", "is not as good as", "my old one"],
    meaning: "Chiếc điện thoại rẻ nhất ở cửa hàng này không tốt bằng chiếc cũ của tôi.",
    review: compare,
  },
  {
    id: "a2-a-little-a-few",
    level: "A2",
    en: "We still have a little money, so we can buy a few snacks for the trip.",
    verb: "have (vế đầu) và can buy (vế sau)",
    subject: "We",
    sign: "A little + danh từ không đếm được (money): một ít. A few + danh từ đếm được số nhiều (snacks): vài cái. Cả hai đều là ít nhưng vẫn có, nên câu mang ý tích cực.",
    chunks: ["We", "still have", "a little money,", "so we", "can buy", "a few snacks", "for the trip"],
    meaning: "Chúng tôi vẫn còn một ít tiền, nên có thể mua vài món ăn vặt cho chuyến đi.",
    review: amount,
  },
  {
    id: "a2-how-many-hours",
    level: "A2",
    en: "How many hours do you spend on your phone every day?",
    verb: "do … spend",
    subject: "you",
    sign: "How many + danh từ đếm được số nhiều (hours) hỏi số lượng. Cả cụm How many hours là thứ được hỏi; sau đó mới đến do + chủ ngữ + động từ nguyên mẫu. Spend time on: dành thời gian cho.",
    chunks: ["How many hours", "do", "you", "spend", "on your phone", "every day?"],
    meaning: "Mỗi ngày bạn dành bao nhiêu giờ cho điện thoại?",
    review: amount,
  },
  {
    id: "a2-too-hot-to-drink",
    level: "A2",
    en: "The coffee in this paper cup is too hot to drink right now.",
    verb: "is (to drink không phải động từ chính)",
    subject: "The coffee in this paper cup",
    sign: "Too + tính từ: quá mức, gây ra vấn đề. Thêm to + động từ để nói hậu quả: too hot to drink là nóng quá nên chưa uống được. Đừng hiểu là nóng để uống.",
    chunks: ["The coffee", "in this paper cup", "is", "too hot", "to drink", "right now"],
    meaning: "Cà phê trong cốc giấy này nóng quá, bây giờ chưa uống được.",
    review: tooEnough,
  },
  {
    id: "a2-not-old-enough",
    level: "A2",
    en: "My son isn't old enough to ride a motorbike, so he goes to school by bus.",
    verb: "isn't (vế đầu) và goes (vế sau)",
    subject: "My son (vế đầu), he (vế sau)",
    sign: "Enough đứng sau tính từ: old enough (đủ tuổi). Isn't … old enough to + động từ: chưa đủ tuổi để làm gì. Vế sau so (nên) nói kết quả; goes có -s vì là thói quen của một người.",
    chunks: ["My son", "isn't old enough", "to ride a motorbike,", "so he", "goes", "to school", "by bus"],
    meaning: "Con trai tôi chưa đủ tuổi đi xe máy, nên cháu đi học bằng xe buýt.",
    review: tooEnough,
  },
  {
    id: "a2-mine-husbands",
    level: "A2",
    en: "The red car outside is mine, and the white one next to it is my husband's.",
    verb: "is (vế đầu) và is (vế sau)",
    subject: "The red car outside (vế đầu), the white one next to it (vế sau)",
    sign: "Mine (của tôi) đứng một mình, không có danh từ theo sau. My husband's là của chồng tôi; sau 's không cần nhắc lại car. One thay cho car, còn it trong next to it chỉ chiếc xe đỏ.",
    chunks: ["The red car", "outside", "is", "mine,", "and the white one", "next to it", "is", "my husband's"],
    meaning: "Chiếc ô tô màu đỏ ở ngoài kia là của tôi, còn chiếc màu trắng bên cạnh là của chồng tôi.",
    review: whose,
  },
  {
    id: "a2-whose-keys",
    level: "A2",
    en: "Whose keys are those on the table next to the door?",
    verb: "are",
    subject: "those (những cái kia)",
    sign: "Whose + danh từ hỏi của ai: Whose keys là chìa khóa của ai. Sau đó đến are + those; on the table next to the door chỉ rõ những cái nào. Whose (của ai) khác who's (who is, ai là).",
    chunks: ["Whose keys", "are", "those", "on the table", "next to the door?"],
    meaning: "Chùm chìa khóa trên bàn cạnh cửa kia là của ai?",
    review: whose,
  },
  {
    id: "a2-go-straight-turn-left",
    level: "A2",
    en: "Go straight on, turn left at the traffic lights, and the bank is on your right.",
    verb: "go và turn (câu mệnh lệnh), is (vế cuối)",
    subject: "hai lệnh đầu không có chủ ngữ (ngầm hiểu là you); the bank ở vế cuối",
    sign: "Câu mệnh lệnh bắt đầu bằng động từ nguyên mẫu, không có chủ ngữ: Go straight on, turn left. At + chỗ rẽ: at the traffic lights. Vế cuối and the bank is on your right là câu bình thường, có chủ ngữ the bank.",
    chunks: ["Go straight on,", "turn left", "at the traffic lights,", "and the bank", "is", "on your right"],
    meaning: "Đi thẳng, đến đèn giao thông thì rẽ trái, ngân hàng nằm ở bên tay phải bạn.",
    review: directions,
  },
  {
    id: "a2-how-long-does-it-take",
    level: "A2",
    en: "How long does it take to get to the airport by taxi from here?",
    verb: "does … take (to get không phải động từ chính)",
    subject: "it (chủ ngữ hình thức, không có nghĩa là nó)",
    sign: "How long does it take…? hỏi mất bao lâu. It không chỉ vật nào cả, chỉ đứng làm chủ ngữ; to get to the airport mới là việc được nói đến. Trả lời: It takes about twenty minutes.",
    chunks: ["How long", "does it take", "to get to the airport", "by taxi", "from here?"],
    meaning: "Từ đây đi taxi ra sân bay mất bao lâu?",
    review: directions,
  },
  {
    id: "a2-should-if-headache",
    level: "A2",
    en: "You should see a doctor if your headache doesn't go away by tomorrow.",
    verb: "should see (vế chính) và doesn't go away (vế if)",
    subject: "You (vế chính), your headache (vế if)",
    sign: "Should + động từ nguyên mẫu: lời khuyên (nên), sau should không có to. Vế if đứng sau nên không có dấu phẩy; doesn't go away là hiện tại đơn dù nói về ngày mai. Go away ở đây là hết (đau), không phải đi đi.",
    chunks: ["You", "should see", "a doctor", "if your headache", "doesn't go away", "by tomorrow"],
    meaning: "Nếu đến mai vẫn chưa hết đau đầu thì bạn nên đi khám bác sĩ.",
    review: advice,
  },
  {
    id: "a2-dont-have-to-mustnt",
    level: "A2",
    en: "You don't have to pay for parking here, but you mustn't stay longer than two hours.",
    verb: "don't have to pay (vế đầu) và mustn't stay (vế sau)",
    subject: "You",
    sign: "Don't have to + động từ: không cần, không bắt buộc. Mustn't + động từ: cấm, không được. Hai cụm trông giống nhau nhưng nghĩa khác hẳn: gửi xe miễn phí, nhưng không được ở quá hai tiếng.",
    chunks: ["You", "don't have to pay", "for parking", "here,", "but you", "mustn't stay", "longer than two hours"],
    meaning: "Ở đây bạn không phải trả tiền đỗ xe, nhưng không được đỗ quá hai tiếng.",
    review: advice,
  },
  {
    id: "a2-have-you-ever-tried",
    level: "A2",
    en: "Have you ever tried the street food in the old quarter of Hanoi?",
    verb: "have … tried",
    subject: "you",
    sign: "Have + chủ ngữ + ever + V3?: hỏi về trải nghiệm trong đời, không hỏi khi nào. Tried là V3 của try. Ever (đã bao giờ) đứng giữa chủ ngữ và V3.",
    chunks: ["Have", "you", "ever tried", "the street food", "in the old quarter", "of Hanoi?"],
    meaning: "Bạn đã bao giờ ăn thử đồ ăn đường phố ở phố cổ Hà Nội chưa?",
    review: ever,
  },
  {
    id: "a2-has-just-left",
    level: "A2",
    en: "The manager has just left the office, so you can't speak to him now.",
    verb: "has just left (vế đầu) và can't speak (vế sau)",
    subject: "The manager (vế đầu), you (vế sau)",
    sign: "Has + just + V3 (left là V3 của leave): vừa mới xảy ra, kết quả còn liên quan đến bây giờ, nên vế sau mới nói bây giờ không gặp được. Just đứng giữa has và V3.",
    chunks: ["The manager", "has just left", "the office,", "so you", "can't speak to him", "now"],
    meaning: "Anh quản lý vừa mới rời văn phòng, nên bây giờ bạn không nói chuyện với anh ấy được.",
    review: justYet,
  },
  {
    id: "a2-havent-finished-yet",
    level: "A2",
    en: "I haven't finished the report yet because my computer broke down yesterday.",
    verb: "haven't finished (vế đầu) và broke down (vế because)",
    subject: "I (vế đầu), my computer (vế because)",
    sign: "Haven't + V3 + yet: chưa làm xong (tính đến bây giờ); yet đứng cuối vế. Vế because có yesterday là thời điểm cụ thể nên dùng quá khứ đơn: broke down (quá khứ của break down, bị hỏng).",
    chunks: ["I", "haven't finished", "the report", "yet", "because my computer", "broke down", "yesterday"],
    meaning: "Tôi vẫn chưa làm xong báo cáo vì hôm qua máy tính của tôi bị hỏng.",
    review: justYet,
  },
  {
    id: "a2-been-twice-last-time",
    level: "A2",
    en: "I've been to Japan twice, and the last time I went there was in 2019.",
    verb: "'ve been (vế đầu) và was (vế sau; went không phải động từ chính của vế này)",
    subject: "I (vế đầu), the last time I went there (vế sau)",
    sign: "I've been to + nơi chốn: đã từng đến (hiện tại hoàn thành, không nói khi nào). Khi nêu thời gian cụ thể (in 2019) thì chuyển sang quá khứ đơn. Ở vế sau, cả cụm the last time I went there (lần gần nhất tôi đến đó) là chủ ngữ của was.",
    chunks: ["I've been", "to Japan", "twice,", "and the last time", "I went there", "was", "in 2019"],
    meaning: "Tôi đã đến Nhật Bản hai lần, lần gần nhất là năm 2019.",
    review: ever,
  },
];
