import type { SentenceDrill } from "../my-plan";

const B1 = "tieng-anh-b1";
const FOR_SINCE = { course: B1, lesson: "da-duoc-bao-lau", title: "Hiện tại hoàn thành với for và since" };
const ED_ING = { course: B1, lesson: "cong-viec-va-phong-van", title: "Tính từ -ed và -ing, nói về kinh nghiệm" };
const WOULD = { course: B1, lesson: "would-va-used-to", title: "Would + V cho thói quen trong quá khứ, used to và quá khứ đơn khi kể chuyện" };
const PAST_PERFECT = { course: B1, lesson: "qua-khu-hoan-thanh", title: "Quá khứ hoàn thành: had + V3" };
const PPC = { course: B1, lesson: "hien-tai-hoan-thanh-tiep-dien", title: "Hiện tại hoàn thành tiếp diễn: have been + V-ing" };
const DEDUCTION = { course: B1, lesson: "suy-doan-hien-tai", title: "Động từ khuyết thiếu chỉ sự suy đoán ở hiện tại" };
const TAGS = { course: B1, lesson: "cau-hoi-duoi", title: "Question tags: đuôi phủ định, đuôi khẳng định và ngữ điệu" };
const FUTURE = { course: B1, lesson: "tuong-lai-tiep-dien-hoan-thanh", title: "Will be doing, will have done, by + thời gian, this time next week" };
const CONDITIONALS = { course: B1, lesson: "neu-thi", title: "Câu điều kiện loại 1 và loại 2" };
const WISH = { course: B1, lesson: "wish-va-used-to", title: "Wish / if only + quá khứ đơn và quá khứ hoàn thành; be used to và get used to + V-ing" };
const VERB_PATTERNS = { course: B1, lesson: "dong-tu-theo-sau", title: "Động từ + to V và động từ + V-ing" };
const PHRASAL = { course: B1, lesson: "cum-dong-tu-thong-dung", title: "Cụm động từ: get up, look for, give up, turn on/off, find out, pick up" };
const PASSIVE_BASIC = { course: B1, lesson: "tin-tuc-va-su-viec", title: "Câu bị động ở hiện tại đơn và quá khứ đơn" };
const PASSIVE_ALL = { course: B1, lesson: "bi-dong-moi-thi", title: "Bị động với hiện tại hoàn thành, tương lai, động từ khuyết thiếu và have something done" };
const INDIRECT = { course: B1, lesson: "cau-hoi-gian-tiep", title: "Câu hỏi gián tiếp: Could you tell me…, Do you know if…" };
const REPORTED = { course: B1, lesson: "cau-tuong-thuat", title: "Say và tell, lùi thì, đổi đại từ và từ chỉ thời gian" };
const RELATIVE = { course: B1, lesson: "menh-de-quan-he", title: "Mệnh đề quan hệ: who, which, that, where, whose" };
const COMPARE = { course: B1, lesson: "so-sanh-nang-cao", title: "Much/far/a bit + so sánh hơn, the… the…, not as… as, twice as… as, so và such" };

/** Sentence-splitting drills for B1 grammar, easiest first. */
export const DRILLS_B1: SentenceDrill[] = [
  {
    id: "b1-worked-for-years",
    level: "B1",
    en: "Our team has worked with the same supplier for more than ten years.",
    verb: "has worked",
    subject: "Our team",
    sign: "Has + V3 (worked) là thì hiện tại hoàn thành. For + một khoảng thời gian (more than ten years): việc bắt đầu từ hơn mười năm trước và đến giờ vẫn tiếp tục.",
    chunks: ["Our team", "has worked", "with the same supplier", "for more than ten years"],
    meaning: "Nhóm chúng tôi đã làm việc với cùng một nhà cung cấp hơn mười năm nay (và vẫn đang làm).",
    review: FOR_SINCE,
  },
  {
    id: "b1-tag-does-she",
    level: "B1",
    en: "Your sister doesn't work at the hospital any more, does she?",
    verb: "doesn't work (does she chỉ là câu hỏi đuôi, không phải động từ mới)",
    subject: "Your sister",
    sign: "Câu chính phủ định (doesn't work) nên đuôi khẳng định (does she?). Đuôi lặp lại trợ động từ does và thay chủ ngữ bằng đại từ she. Cả cái đuôi chỉ mang nghĩa “phải không?”. Not … any more: không còn … nữa.",
    chunks: ["Your sister", "doesn't work", "at the hospital", "any more,", "does she?"],
    meaning: "Chị gái bạn không còn làm ở bệnh viện nữa, phải không?",
    review: TAGS,
  },
  {
    id: "b1-would-every-sunday",
    level: "B1",
    en: "When we were children, our father would take us to the beach every Sunday morning.",
    verb: "would take (không phải were)",
    subject: "our father",
    sign: "Would + động từ nguyên mẫu ở đây không có nghĩa “sẽ”: nó kể một việc lặp đi lặp lại trong quá khứ, giống used to. Every Sunday morning cho thấy đó là thói quen. Vế When we were children chỉ dựng mốc thời gian.",
    chunks: ["When we were children,", "our father", "would take us", "to the beach", "every Sunday morning"],
    meaning: "Hồi chúng tôi còn nhỏ, sáng Chủ nhật nào bố cũng đưa chúng tôi ra biển.",
    review: WOULD,
  },
  {
    id: "b1-inspiring-worried",
    level: "B1",
    en: "The new manager's speech was inspiring, but most of the staff still felt worried about their jobs.",
    verb: "was (vế đầu) và felt (vế sau)",
    subject: "The new manager's speech (vế đầu), most of the staff (vế sau)",
    sign: "Tính từ đuôi -ing (inspiring) tả cái gây ra cảm xúc: bài phát biểu truyền cảm hứng. Tính từ đuôi -ed (worried) tả cảm xúc của người: nhân viên thấy lo. Cắt câu ở but.",
    chunks: ["The new manager's speech", "was", "inspiring,", "but most of the staff", "still felt", "worried", "about their jobs"],
    meaning: "Bài phát biểu của vị quản lý mới rất truyền cảm hứng, nhưng phần lớn nhân viên vẫn thấy lo lắng cho công việc của mình.",
    review: ED_ING,
  },
  {
    id: "b1-train-had-left",
    level: "B1",
    en: "By the time we arrived at the station, the last train had already left.",
    verb: "arrived (vế By the time) và had already left (vế chính)",
    subject: "we (vế By the time), the last train (vế chính)",
    sign: "Had + V3 (had left) là quá khứ hoàn thành: việc xảy ra trước một việc khác trong quá khứ. Tàu chạy trước, chúng tôi đến sau. By the time nghĩa là “vào lúc mà”.",
    chunks: ["By the time we arrived at the station,", "the last train", "had already left"],
    meaning: "Lúc chúng tôi đến ga thì chuyến tàu cuối đã chạy mất rồi.",
    review: PAST_PERFECT,
  },
  {
    id: "b1-been-working-since",
    level: "B1",
    en: "She has been working on the same report since eight o'clock, so she looks exhausted.",
    verb: "has been working (vế đầu) và looks (vế sau)",
    subject: "She",
    sign: "Have/has been + V-ing là hiện tại hoàn thành tiếp diễn: việc bắt đầu từ trước (since eight o'clock), kéo dài liên tục đến bây giờ và để lại dấu vết thấy được: cô ấy trông kiệt sức. So mở đầu vế nói kết quả.",
    chunks: ["She", "has been working", "on the same report", "since eight o'clock,", "so she looks exhausted"],
    meaning: "Cô ấy cặm cụi với bản báo cáo đó từ tám giờ đến giờ, nên trông kiệt sức.",
    review: PPC,
  },
  {
    id: "b1-must-be-on-holiday",
    level: "B1",
    en: "Their lights are off and nobody is answering the phone, so they must be on holiday.",
    verb: "are và is answering (hai dấu hiệu), must be (lời kết luận)",
    subject: "Their lights, nobody, they",
    sign: "Must be ở đây không có nghĩa “phải”: đó là suy đoán gần như chắc chắn dựa trên dấu hiệu (đèn tắt, không ai nghe máy). So mở đầu vế kết luận.",
    chunks: ["Their lights", "are off", "and nobody", "is answering", "the phone,", "so they", "must be", "on holiday"],
    meaning: "Nhà họ tắt đèn và không ai nghe điện thoại, nên chắc hẳn họ đang đi nghỉ.",
    review: DEDUCTION,
  },
  {
    id: "b1-will-be-lying",
    level: "B1",
    en: "This time next week, I will be lying on a beach while you are sitting in the office.",
    verb: "will be lying (vế chính) và are sitting (vế while)",
    subject: "I (vế chính), you (vế while)",
    sign: "Will be + V-ing là tương lai tiếp diễn: việc sẽ đang diễn ra vào một lúc trong tương lai (this time next week). Sau while, dù nói về tương lai, vẫn dùng thì hiện tại (are sitting), không dùng will.",
    chunks: ["This time next week,", "I", "will be lying", "on a beach", "while you are sitting", "in the office"],
    meaning: "Giờ này tuần sau, tôi đang nằm trên bãi biển còn bạn thì đang ngồi trong văn phòng.",
    review: FUTURE,
  },
  {
    id: "b1-will-have-finished",
    level: "B1",
    en: "By the end of next year, the city will have finished the new bridge across the river.",
    verb: "will have finished",
    subject: "the city",
    sign: "Will have + V3 là tương lai hoàn thành: việc sẽ xong trước một mốc trong tương lai. By + mốc thời gian (by the end of next year) nghĩa là “trước, chậm nhất là”.",
    chunks: ["By the end of next year,", "the city", "will have finished", "the new bridge", "across the river"],
    meaning: "Chậm nhất là cuối năm sau, thành phố sẽ làm xong cây cầu mới bắc qua sông.",
    review: FUTURE,
  },
  {
    id: "b1-suggested-decided",
    level: "B1",
    en: "My manager suggested taking the early flight, but I decided to wait until the next morning.",
    verb: "suggested (vế đầu) và decided (vế sau)",
    subject: "My manager (vế đầu), I (vế sau)",
    sign: "Động từ đứng trước quyết định dạng của động từ theo sau: suggest + V-ing (suggested taking), decide + to V (decided to wait). Taking và to wait không phải động từ chính; chúng là việc được gợi ý và việc được quyết định.",
    chunks: ["My manager", "suggested", "taking the early flight,", "but I", "decided", "to wait", "until the next morning"],
    meaning: "Quản lý của tôi gợi ý đi chuyến bay sớm, nhưng tôi quyết định đợi đến sáng hôm sau.",
    review: VERB_PATTERNS,
  },
  {
    id: "b1-pick-me-up",
    level: "B1",
    en: "My flight lands at midnight, so my brother has promised to pick me up at the airport.",
    verb: "lands (vế đầu) và has promised (vế sau)",
    subject: "My flight (vế đầu), my brother (vế sau)",
    sign: "Pick up (đón) là cụm động từ tách được: khi tân ngữ là đại từ (me), nó bắt buộc đứng giữa, nên là pick me up, không nói pick up me. Promise + to V. Lands là hiện tại đơn cho giờ giấc theo lịch trình.",
    chunks: ["My flight", "lands", "at midnight,", "so my brother", "has promised", "to pick me up", "at the airport"],
    meaning: "Chuyến bay của tôi hạ cánh lúc nửa đêm, nên anh trai tôi đã hứa ra sân bay đón tôi.",
    review: PHRASAL,
  },
  {
    id: "b1-getting-used-to",
    level: "B1",
    en: "After two months in Seoul, she is slowly getting used to eating breakfast at six in the morning.",
    verb: "is getting used to",
    subject: "she",
    sign: "Get used to + V-ing: dần quen với việc gì. To ở đây là giới từ nên theo sau là eating, không phải eat. Đừng lẫn với used to + V (hồi trước hay làm, nay không còn).",
    chunks: ["After two months in Seoul,", "she", "is slowly getting used to", "eating breakfast", "at six in the morning"],
    meaning: "Sau hai tháng ở Seoul, cô ấy đang dần quen với việc ăn sáng lúc sáu giờ.",
    review: WISH,
  },
  {
    id: "b1-if-had-more-time",
    level: "B1",
    en: "If I had more free time in the evenings, I would join a language club near my office.",
    verb: "had (vế If) và would join (vế chính)",
    subject: "I",
    sign: "If + quá khứ đơn (had), would + động từ nguyên mẫu: câu điều kiện loại 2, nói chuyện không có thật ở hiện tại. Had là quá khứ về hình thức nhưng nói về bây giờ: thực tế là tôi không có nhiều thời gian rảnh.",
    chunks: ["If I had more free time", "in the evenings,", "I", "would join", "a language club", "near my office"],
    meaning: "Nếu buổi tối có nhiều thời gian rảnh hơn thì tôi sẽ tham gia một câu lạc bộ ngoại ngữ gần cơ quan (nhưng thực tế tôi không có).",
    review: CONDITIONALS,
  },
  {
    id: "b1-unless-weather",
    level: "B1",
    en: "Unless the weather improves by Friday, the organisers will move the concert indoors.",
    verb: "improves (vế Unless) và will move (vế chính)",
    subject: "the weather (vế Unless), the organisers (vế chính)",
    sign: "Unless nghĩa là if not (trừ khi, nếu không). Đây vẫn là câu điều kiện loại 1: vế Unless dùng hiện tại đơn (improves) dù nói về thứ Sáu tới, vế chính dùng will + động từ nguyên mẫu. Không thêm not sau unless.",
    chunks: ["Unless the weather improves by Friday,", "the organisers", "will move", "the concert", "indoors"],
    meaning: "Nếu đến thứ Sáu thời tiết không khá hơn, ban tổ chức sẽ chuyển buổi hòa nhạc vào trong nhà.",
    review: CONDITIONALS,
  },
  {
    id: "b1-wish-hadnt-agreed",
    level: "B1",
    en: "I wish I hadn't agreed to work this weekend, because my friends are going to the beach without me.",
    verb: "wish (động từ chính); hadn't agreed nằm trong điều ước, are going ở vế because",
    subject: "I (vế chính), my friends (vế because)",
    sign: "Wish + had + V3 (hadn't agreed): tiếc một việc đã làm trong quá khứ; thực tế là tôi đã nhận lời. Agree + to V (agreed to work). Are going là hiện tại tiếp diễn chỉ kế hoạch đã định.",
    chunks: ["I wish", "I hadn't agreed", "to work this weekend,", "because my friends", "are going", "to the beach", "without me"],
    meaning: "Giá mà tôi đã không nhận lời đi làm cuối tuần này, vì bạn bè tôi sẽ đi biển mà không có tôi.",
    review: WISH,
  },
  {
    id: "b1-library-was-opened",
    level: "B1",
    en: "The new library was opened by the mayor last month and is used by hundreds of students every day.",
    verb: "was opened và is used (cả hai đều ở dạng bị động)",
    subject: "The new library",
    sign: "Be + V3 là câu bị động: thư viện không tự làm gì, mà được người khác làm. Was opened (quá khứ đơn) là việc một lần tháng trước; is used (hiện tại đơn) là việc diễn ra thường xuyên. By + người cho biết ai làm việc đó.",
    chunks: ["The new library", "was opened", "by the mayor", "last month", "and is used", "by hundreds of students", "every day"],
    meaning: "Thư viện mới được thị trưởng khánh thành tháng trước và ngày nào cũng có hàng trăm sinh viên sử dụng.",
    review: PASSIVE_BASIC,
  },
  {
    id: "b1-trees-have-been-planted",
    level: "B1",
    en: "More than two hundred trees have been planted along the river since the project started.",
    verb: "have been planted (không phải started)",
    subject: "More than two hundred trees",
    sign: "Have/has been + V3 là bị động ở hiện tại hoàn thành: cây được (người ta) trồng, tính từ lúc dự án bắt đầu đến giờ. Since + một vế (since the project started) cho mốc bắt đầu.",
    chunks: ["More than two hundred trees", "have been planted", "along the river", "since the project started"],
    meaning: "Từ khi dự án bắt đầu đến nay, hơn hai trăm cây xanh đã được trồng dọc bờ sông.",
    review: PASSIVE_ALL,
  },
  {
    id: "b1-bags-must-be-checked",
    level: "B1",
    en: "All bags must be checked before passengers are allowed to enter the waiting area.",
    verb: "must be checked (vế chính) và are allowed (vế before)",
    subject: "All bags (vế chính), passengers (vế before)",
    sign: "Động từ khuyết thiếu + be + V3 (must be checked) là bị động: túi phải được kiểm tra. Ở đây must nghĩa là “phải”, không phải suy đoán. Are allowed to + V cũng là bị động: hành khách được phép làm gì.",
    chunks: ["All bags", "must be checked", "before passengers", "are allowed", "to enter the waiting area"],
    meaning: "Tất cả túi xách phải được kiểm tra trước khi hành khách được phép vào khu vực chờ.",
    review: PASSIVE_ALL,
  },
  {
    id: "b1-had-car-repaired",
    level: "B1",
    en: "I had my car repaired at a small garage near my office, and it cost much less than I expected.",
    verb: "had … repaired (vế đầu) và cost (vế sau)",
    subject: "I (vế đầu), it (vế sau)",
    sign: "Have + đồ vật + V3 (had my car repaired): thuê người khác làm việc đó, tôi không tự sửa. Cost ở đây là quá khứ (cost – cost – cost); it chỉ việc sửa xe. Much less than: ít hơn nhiều so với.",
    chunks: ["I", "had my car repaired", "at a small garage", "near my office,", "and it", "cost much less", "than I expected"],
    meaning: "Tôi mang xe đi sửa ở một gara nhỏ gần cơ quan, và tiền sửa thấp hơn nhiều so với tôi dự tính.",
    review: PASSIVE_ALL,
  },
  {
    id: "b1-tell-me-where",
    level: "B1",
    en: "Could you tell me where the nearest pharmacy is and whether it opens on Sundays?",
    verb: "Could you tell (động từ chính); is và opens nằm trong phần câu hỏi gián tiếp",
    subject: "you",
    sign: "Sau Could you tell me là câu hỏi gián tiếp, theo trật tự câu kể: where the nearest pharmacy is (không phải where is), whether it opens (không có does). Whether nghĩa là “liệu… có… không”.",
    chunks: ["Could you tell me", "where the nearest pharmacy is", "and whether it opens", "on Sundays?"],
    meaning: "Anh chị có thể cho tôi biết hiệu thuốc gần nhất ở đâu và Chủ nhật có mở cửa không?",
    review: INDIRECT,
  },
  {
    id: "b1-told-not-to-lift",
    level: "B1",
    en: "The doctor told my father not to lift anything heavy for at least two weeks.",
    verb: "told (không phải lift)",
    subject: "The doctor",
    sign: "Tell + người + (not) to + V: kể lại một lời dặn hoặc yêu cầu. Lời gốc của bác sĩ là “Don't lift anything heavy”. Not đứng ngay trước to.",
    chunks: ["The doctor", "told my father", "not to lift", "anything heavy", "for at least two weeks"],
    meaning: "Bác sĩ dặn bố tôi không được nhấc vật gì nặng trong ít nhất hai tuần.",
    review: REPORTED,
  },
  {
    id: "b1-told-us-closed",
    level: "B1",
    en: "The receptionist told us that the hotel restaurant was closed for repairs that week.",
    verb: "told (động từ chính); was nằm trong lời được kể lại",
    subject: "The receptionist",
    sign: "Told + người nghe (us) + that: kể lại lời người khác. Lời gốc là “The restaurant is closed for repairs this week”; khi kể lại, is lùi thành was và this week đổi thành that week.",
    chunks: ["The receptionist", "told us", "that the hotel restaurant", "was closed", "for repairs", "that week"],
    meaning: "Lễ tân bảo chúng tôi rằng tuần đó nhà hàng của khách sạn đóng cửa để sửa chữa.",
    review: REPORTED,
  },
  {
    id: "b1-asked-whether-delivery",
    level: "B1",
    en: "A customer asked me whether the price included delivery and how long it would take.",
    verb: "asked (động từ chính); included và would take nằm trong câu hỏi được kể lại",
    subject: "A customer",
    sign: "Asked + câu hỏi tường thuật. Câu hỏi Có/Không dùng whether (hoặc if); câu hỏi có từ để hỏi giữ how long. Cả hai theo trật tự câu kể và lùi thì: “Does the price include delivery?” thành whether the price included delivery, “How long will it take?” thành how long it would take.",
    chunks: ["A customer", "asked me", "whether the price included delivery", "and how long", "it would take"],
    meaning: "Một khách hàng hỏi tôi giá đó đã gồm phí giao hàng chưa và giao mất bao lâu.",
    review: REPORTED,
  },
  {
    id: "b1-the-longer-the-more",
    level: "B1",
    en: "The longer you wait to book your flight, the more you will usually have to pay.",
    verb: "wait (vế đầu) và will have to pay (vế sau)",
    subject: "you",
    sign: "The + so sánh hơn…, the + so sánh hơn…: càng… càng…. Vế đầu là điều kiện (càng đợi lâu), vế sau là kết quả (càng phải trả nhiều). Mỗi vế có chủ ngữ và động từ riêng; cắt câu ở dấu phẩy.",
    chunks: ["The longer you wait", "to book your flight,", "the more", "you will usually have to pay"],
    meaning: "Bạn càng chần chừ đặt vé máy bay thì thường càng phải trả nhiều tiền.",
    review: COMPARE,
  },
  {
    id: "b1-not-as-close-twice",
    level: "B1",
    en: "The new office is not as close to the city centre as the old one, but it is twice as big.",
    verb: "is not (vế đầu) và is (vế sau)",
    subject: "The new office (vế đầu), it (vế sau)",
    sign: "Not as + tính từ + as: không… bằng. Twice as + tính từ (+ as the old one, được hiểu ngầm): gấp đôi. The old one là the old office; one thay cho danh từ để khỏi lặp.",
    chunks: ["The new office", "is not as close", "to the city centre", "as the old one,", "but it", "is twice as big"],
    meaning: "Văn phòng mới không gần trung tâm thành phố bằng văn phòng cũ, nhưng rộng gấp đôi.",
    review: COMPARE,
  },
  {
    id: "b1-hotel-where-we-stayed",
    level: "B1",
    en: "The small hotel where we stayed last summer has closed because there were not enough tourists.",
    verb: "has closed (không phải stayed)",
    subject: "The small hotel",
    sign: "Where we stayed last summer chỉ rõ khách sạn nào (where thay cho nơi chốn). Tạm bỏ cụm này, câu còn The small hotel has closed. Động từ chính đứng sau cả cụm dài, đừng dừng lại ở stayed.",
    chunks: ["The small hotel", "where we stayed last summer", "has closed", "because there were not enough tourists"],
    meaning: "Khách sạn nhỏ mà chúng tôi ở hè năm ngoái đã đóng cửa vì không có đủ khách du lịch.",
    review: RELATIVE,
  },
  {
    id: "b1-woman-whose-car",
    level: "B1",
    en: "The woman whose car was stolen outside the office is waiting for the police in reception.",
    verb: "is waiting (không phải was stolen)",
    subject: "The woman",
    sign: "Whose + danh từ (whose car): người mà xe của cô ấy… Cụm whose car was stolen outside the office chỉ rõ người phụ nữ nào; trong cụm có bị động was stolen. Bỏ cụm này, câu còn The woman is waiting for the police.",
    chunks: ["The woman", "whose car was stolen outside the office", "is waiting", "for the police", "in reception"],
    meaning: "Người phụ nữ bị trộm xe ngay trước cơ quan đang đợi cảnh sát ở quầy lễ tân.",
    review: RELATIVE,
  },
  {
    id: "b1-timetable-which-starts",
    level: "B1",
    en: "The new timetable, which starts on Monday, means that most buses will run every ten minutes.",
    verb: "means (không phải starts hay will run)",
    subject: "The new timetable",
    sign: "Cụm giữa hai dấu phẩy (which starts on Monday) là mệnh đề không xác định: chỉ thêm thông tin, bỏ đi câu vẫn đủ nghĩa, và không dùng that ở đây. Means có -s vì chủ ngữ là timetable. Sau means that là một vế mới với will run.",
    chunks: ["The new timetable,", "which starts on Monday,", "means", "that most buses", "will run", "every ten minutes"],
    meaning: "Lịch chạy xe mới, áp dụng từ thứ Hai, có nghĩa là hầu hết các tuyến xe buýt sẽ có chuyến mười phút một lần.",
    review: RELATIVE,
  },
  {
    id: "b1-although-road-repaired",
    level: "B1",
    en: "Although the road was repaired only last year, it has already been damaged again by heavy lorries.",
    verb: "was repaired (vế Although) và has already been damaged (vế chính)",
    subject: "the road (vế Although), it (vế chính)",
    sign: "Cả hai vế đều bị động: was repaired (quá khứ đơn, sửa hồi năm ngoái) và has been damaged (hiện tại hoàn thành, kết quả thấy bây giờ). By heavy lorries cho biết cái gì gây hư hỏng. Although báo hai vế trái ý nhau: mới sửa mà đã hỏng; vế sau không thêm but.",
    chunks: ["Although the road was repaired only last year,", "it", "has already been damaged again", "by heavy lorries"],
    meaning: "Dù con đường mới được sửa hồi năm ngoái, nó đã lại bị xe tải nặng làm hư hỏng.",
    review: PASSIVE_ALL,
  },
  {
    id: "b1-engineer-was-asked-why",
    level: "B1",
    en: "The engineer who had designed the bridge was asked why the work had not been finished on time.",
    verb: "was asked (không phải had designed)",
    subject: "The engineer",
    sign: "Who had designed the bridge chỉ rõ kỹ sư nào; bỏ cụm này, câu còn The engineer was asked… Động từ chính was asked là bị động: kỹ sư bị hỏi. Phần sau là câu hỏi được kể lại, theo trật tự câu kể (why the work had not been finished, không phải why had the work…), và lùi thì về quá khứ hoàn thành.",
    chunks: ["The engineer", "who had designed the bridge", "was asked", "why the work", "had not been finished", "on time"],
    meaning: "Người kỹ sư đã thiết kế cây cầu bị hỏi vì sao công trình không hoàn thành đúng hạn.",
    review: REPORTED,
  },
];
