import type { SentenceDrill } from "../my-plan";

const B2 = "tieng-anh-b2";
const PERF_CONT = { course: B2, lesson: "cac-thi-hoan-thanh-tiep-dien", title: "Quá khứ hoàn thành tiếp diễn và tương lai hoàn thành tiếp diễn" };
const NOT_ONLY_IF = { course: B2, lesson: "dieu-kien-khong-chi-if", title: "Unless, provided that, as long as, in case, otherwise, suppose" };
const DEDUCTION_PAST = { course: B2, lesson: "hop-va-thao-luan", title: "Suy đoán về quá khứ và xen ngang lịch sự" };
const SHOULD_HAVE = { course: B2, lesson: "dong-tu-khuyet-thieu-qua-khu", title: "Should have, could have, needn't have và didn't need to" };
const THIRD_MIXED = { course: B2, lesson: "tiec-nuoi-va-gia-dinh", title: "Câu điều kiện loại 3, câu hỗn hợp và wish" };
const UNREAL_PAST = { course: B2, lesson: "gia-dinh-khong-that", title: "Would rather, it's time, as if và wish: quá khứ giả định" };
const REPORTED = { course: B2, lesson: "tuong-thuat-loi-noi", title: "Câu tường thuật và lùi thì" };
const RELATIVE = { course: B2, lesson: "thuyet-trinh", title: "Mệnh đề quan hệ và cụm dẫn dắt khi thuyết trình" };
const PARTICIPLE = { course: B2, lesson: "rut-gon-menh-de", title: "Mệnh đề phân từ và mệnh đề quan hệ rút gọn" };
const LINKERS = { course: B2, lesson: "tu-noi-nang-cao", title: "Từ nối chỉ đối lập, bổ sung, kết quả và cách đặt dấu câu" };
const ARTICLES = { course: B2, lesson: "mao-tu", title: "Khi nào dùng the, khi nào không dùng mạo từ" };
const TO_OR_ING = { course: B2, lesson: "to-v-hay-v-ing", title: "Động từ đổi nghĩa khi đi với to V hay V-ing" };
const DATA = { course: B2, lesson: "mo-ta-so-lieu", title: "Động từ, danh từ chỉ xu hướng, trạng từ mức độ và giới từ đi với số liệu" };

const C1 = "tieng-anh-c1";
const COMMENT = { course: C1, lesson: "trang-tu-binh-luan", title: "Nói ra thái độ chỉ bằng một trạng từ" };
const ELLIPSIS = { course: C1, lesson: "tinh-luoc-va-thay-the", title: "Tỉnh lược và thay thế" };
const INVERSION = { course: C1, lesson: "dao-ngu-de-nhan-manh", title: "Đảo ngữ phủ định" };
const CLEFT = { course: C1, lesson: "cau-che-va-nhan-manh", title: "Câu chẻ, do nhấn mạnh và đưa thành phần lên đầu câu" };
const COND_ADV = { course: C1, lesson: "dieu-kien-nang-cao", title: "Were to, should, đảo ngữ, but for và supposing" };
const SUBJUNCTIVE = { course: C1, lesson: "bang-thai-cach", title: "Thể giả định sau động từ, tính từ và trong thành ngữ cố định" };
const REPORTING = { course: C1, lesson: "dong-tu-tuong-thuat", title: "Động từ tường thuật và mẫu câu đi kèm" };
const PASSIVE_REPORT = { course: C1, lesson: "bi-dong-nang-cao", title: "Bị động tường thuật trong văn báo chí và học thuật" };
const RELATIVE_ADV = { course: C1, lesson: "menh-de-quan-he-nang-cao", title: "Giới từ + which/whom, whereby, lượng từ + of whom/which" };
const CONCESSION = { course: C1, lesson: "lap-luan-va-phan-bien", title: "Nhượng bộ nâng cao: Much as, Granted, albeit, notwithstanding" };
const ACADEMIC = { course: C1, lesson: "van-phong-hoc-thuat", title: "Danh từ hóa, cấu trúc khách quan và ngôn ngữ dẫn nguồn" };

/** Sentence-splitting drills for B2 and C1 grammar, easiest first. */
export const DRILLS_B2_C1: SentenceDrill[] = [
  // B2
  {
    id: "b2-unless-funding",
    level: "B2",
    en: "Unless the council approves the extra funding before March, the library will have to reduce its opening hours at weekends.",
    verb: "will have to reduce (vế chính); approves là động từ của vế Unless",
    subject: "the library (vế chính), the council (vế Unless)",
    sign: "Unless = if… not: nếu hội đồng không duyệt. Câu nói về tương lai nhưng sau Unless vẫn dùng hiện tại đơn (approves), không dùng will và không thêm not.",
    chunks: ["Unless the council approves the extra funding", "before March,", "the library", "will have to reduce", "its opening hours", "at weekends"],
    meaning: "Nếu hội đồng thành phố không duyệt khoản kinh phí bổ sung trước tháng Ba, thư viện sẽ phải giảm giờ mở cửa vào cuối tuần.",
    review: NOT_ONLY_IF,
  },
  {
    id: "b2-provided-that",
    level: "B2",
    en: "Employees may work from home two days a week, provided that they remain available by phone during core office hours.",
    verb: "may work (vế chính); remain thuộc vế provided that",
    subject: "Employees (vế chính), they (vế provided that)",
    sign: "Provided that = với điều kiện là, trang trọng hơn as long as. Vế điều kiện đứng sau dấu phẩy và dùng hiện tại đơn (remain). Bỏ vế này ra, câu chính còn Employees may work from home two days a week.",
    chunks: ["Employees", "may work from home", "two days a week,", "provided that they remain available by phone", "during core office hours"],
    meaning: "Nhân viên được làm việc tại nhà hai ngày mỗi tuần, với điều kiện họ luôn liên lạc được qua điện thoại trong khung giờ làm việc chính.",
    review: NOT_ONLY_IF,
  },
  {
    id: "b2-in-case-hall",
    level: "B2",
    en: "The organisers have booked a second hall in case more participants register for the conference than they originally expected.",
    verb: "have booked (không phải register)",
    subject: "The organisers",
    sign: "Have booked (hiện tại hoàn thành): việc đã làm xong rồi. In case = phòng khi: đặt thêm hội trường ngay bây giờ để phòng hờ, chứ không phải đợi có thêm người mới đặt. Sau in case dùng hiện tại đơn (register) cho tương lai.",
    chunks: ["The organisers", "have booked", "a second hall", "in case more participants register for the conference", "than they originally expected"],
    meaning: "Ban tổ chức đã đặt thêm một hội trường nữa, phòng khi số người đăng ký dự hội nghị nhiều hơn họ dự tính ban đầu.",
    review: NOT_ONLY_IF,
  },
  {
    id: "b2-had-been-waiting",
    level: "B2",
    en: "By the time the technician finally arrived, the staff had been waiting outside the locked server room for almost two hours.",
    verb: "had been waiting (không phải arrived)",
    subject: "the staff",
    sign: "Had been + V-ing là quá khứ hoàn thành tiếp diễn: việc chờ kéo dài liên tục đến một mốc trong quá khứ. Mốc đó là vế By the time the technician finally arrived (quá khứ đơn). For almost two hours cho biết đã kéo dài bao lâu.",
    chunks: ["By the time the technician finally arrived,", "the staff", "had been waiting", "outside the locked server room", "for almost two hours"],
    meaning: "Đến lúc kỹ thuật viên cuối cùng cũng tới thì nhân viên đã đứng chờ bên ngoài phòng máy chủ bị khóa gần hai tiếng đồng hồ.",
    review: PERF_CONT,
  },
  {
    id: "b2-will-have-been-testing",
    level: "B2",
    en: "By the end of next year, the research team will have been testing the new water filters in rural schools for five years.",
    verb: "will have been testing",
    subject: "the research team",
    sign: "Will have been + V-ing là tương lai hoàn thành tiếp diễn: tính thời lượng của một việc kéo dài đến một mốc tương lai. By + mốc (the end of next year) và for + khoảng (five years) là hai dấu hiệu đi cùng.",
    chunks: ["By the end of next year,", "the research team", "will have been testing", "the new water filters", "in rural schools", "for five years"],
    meaning: "Tính đến cuối năm sau, nhóm nghiên cứu sẽ thử nghiệm các bộ lọc nước mới ở những trường học nông thôn được tròn năm năm.",
    review: PERF_CONT,
  },
  {
    id: "b2-regret-to-inform",
    level: "B2",
    en: "We regret to inform you that the workshop planned for next Saturday has been cancelled because the guest speaker is no longer able to attend.",
    verb: "regret (to inform); has been cancelled là động từ của mệnh đề that",
    subject: "We",
    sign: "Regret + to V (regret to inform) = rất tiếc phải báo, dùng trong thông báo trang trọng; khác với regret + V-ing là hối tiếc vì đã làm. Trong mệnh đề that, planned for next Saturday là cụm rút gọn (which was planned), còn động từ là has been cancelled (bị động hiện tại hoàn thành).",
    chunks: ["We", "regret to inform you", "that the workshop", "planned for next Saturday", "has been cancelled", "because the guest speaker is no longer able to attend"],
    meaning: "Chúng tôi rất tiếc phải thông báo rằng buổi hội thảo dự kiến vào thứ Bảy tới đã bị hủy vì diễn giả khách mời không thể tham dự được nữa.",
    review: TO_OR_ING,
  },
  {
    id: "b2-stopped-tried",
    level: "B2",
    en: "After the accident, the factory stopped using the old machines and tried installing extra safety sensors to see whether they would reduce the risk.",
    verb: "stopped (using) và tried (installing)",
    subject: "the factory",
    sign: "Stop + V-ing = thôi hẳn không làm nữa (không dùng máy cũ nữa), khác stop + to V là dừng lại để làm việc khác. Try + V-ing = thử một cách xem có hiệu quả không; cụm to see whether… cho thấy đây là phép thử. Try + to V mới là cố gắng làm một việc khó.",
    chunks: ["After the accident,", "the factory", "stopped using", "the old machines", "and tried installing", "extra safety sensors", "to see whether they would reduce the risk"],
    meaning: "Sau vụ tai nạn, nhà máy thôi hẳn không dùng các máy cũ nữa và thử lắp thêm cảm biến an toàn để xem chúng có giảm được rủi ro hay không.",
    review: TO_OR_ING,
  },
  {
    id: "b2-must-have-been-sent",
    level: "B2",
    en: "The documents must have been sent to the wrong department, because nobody in the finance office remembers receiving them last week.",
    verb: "must have been sent (vế đầu) và remembers (vế because)",
    subject: "The documents (vế đầu), nobody in the finance office (vế because)",
    sign: "Must have + V3 = chắc hẳn đã: đoán gần như chắc chắn về quá khứ. Ở đây là bị động: must have been sent = chắc hẳn đã bị gửi. Vế because là bằng chứng cho lời đoán. Remember + V-ing = nhớ lại việc đã xảy ra.",
    chunks: ["The documents", "must have been sent", "to the wrong department,", "because nobody in the finance office", "remembers receiving them", "last week"],
    meaning: "Chắc hẳn tài liệu đã bị gửi nhầm sang phòng khác, vì không ai ở phòng tài chính nhớ là đã nhận được chúng vào tuần trước.",
    review: DEDUCTION_PAST,
  },
  {
    id: "b2-should-have-informed",
    level: "B2",
    en: "Looking back, the project manager should have informed the client about the delay instead of hoping that the team would catch up in time.",
    verb: "should have informed (không phải hoping hay would catch up)",
    subject: "the project manager",
    sign: "Should have + V3 = lẽ ra nên làm nhưng đã không làm: lời trách hoặc rút kinh nghiệm. Instead of + V-ing (hoping) là việc người đó đã làm thay vào đó. Looking back = nhìn lại, cụm mở đầu cố định.",
    chunks: ["Looking back,", "the project manager", "should have informed", "the client", "about the delay", "instead of hoping", "that the team would catch up in time"],
    meaning: "Nhìn lại thì lẽ ra người quản lý dự án nên báo cho khách hàng về việc chậm trễ, thay vì hy vọng cả nhóm sẽ kịp đuổi theo tiến độ.",
    review: SHOULD_HAVE,
  },
  {
    id: "b2-might-have-been-caused",
    level: "B2",
    en: "The sudden drop in online orders might have been caused by the technical problems that customers reported on the website over the weekend.",
    verb: "might have been caused (không phải reported)",
    subject: "The sudden drop in online orders",
    sign: "Might have + V3 = có thể đã, lời đoán chưa chắc chắn. Been caused là bị động: sự sụt giảm bị gây ra bởi (by) các sự cố. Cụm that customers reported… chỉ nói rõ sự cố nào; reported là động từ của cụm này, không phải của cả câu.",
    chunks: ["The sudden drop in online orders", "might have been caused", "by the technical problems", "that customers reported on the website", "over the weekend"],
    meaning: "Việc đơn hàng trực tuyến giảm đột ngột có thể là do các sự cố kỹ thuật mà khách hàng đã báo trên trang web vào cuối tuần.",
    review: DEDUCTION_PAST,
  },
  {
    id: "b2-third-conditional-bridge",
    level: "B2",
    en: "If the engineers had checked the design more carefully, the bridge would not have needed such expensive repairs only a year after it opened.",
    verb: "had checked (vế If) và would not have needed (vế chính)",
    subject: "the engineers (vế If), the bridge (vế chính)",
    sign: "If + had + V3, would have + V3: câu điều kiện loại 3, nói điều trái với quá khứ. Thực tế: các kỹ sư đã không kiểm tra kỹ, nên cây cầu đã phải sửa rất tốn kém.",
    chunks: ["If the engineers had checked the design more carefully,", "the bridge", "would not have needed", "such expensive repairs", "only a year after it opened"],
    meaning: "Nếu các kỹ sư kiểm tra thiết kế cẩn thận hơn thì cây cầu đã không phải sửa chữa tốn kém như vậy chỉ một năm sau khi thông xe.",
    review: THIRD_MIXED,
  },
  {
    id: "b2-mixed-conditional-training",
    level: "B2",
    en: "If the company had invested in staff training ten years ago, it would not be struggling to find skilled workers now.",
    verb: "had invested (vế If) và would not be struggling (vế chính)",
    subject: "the company (vế If), it (vế chính)",
    sign: "Câu điều kiện hỗn hợp: vế If ở quá khứ hoàn thành (had invested, ten years ago) là nguyên nhân trong quá khứ; vế chính dùng would + V (would not be struggling, now) là kết quả ở hiện tại. Thực tế: công ty đã không đầu tư nên bây giờ đang chật vật.",
    chunks: ["If the company had invested in staff training", "ten years ago,", "it", "would not be struggling", "to find skilled workers", "now"],
    meaning: "Nếu mười năm trước công ty đầu tư vào đào tạo nhân viên thì bây giờ họ đã không phải chật vật tìm lao động có tay nghề.",
    review: THIRD_MIXED,
  },
  {
    id: "b2-supposing-supplier",
    level: "B2",
    en: "Supposing the main supplier went out of business tomorrow, the factory could only keep running for about three weeks on the materials in stock.",
    verb: "could keep running (vế chính); went thuộc vế Supposing",
    subject: "the factory (vế chính), the main supplier (vế Supposing)",
    sign: "Supposing = giả sử: đưa ra một tình huống giả định, không đi kèm if. Động từ ở dạng quá khứ (went) dù nói về ngày mai, vì người viết cho là khó xảy ra. Vế chính dùng could + V như câu điều kiện loại 2.",
    chunks: ["Supposing the main supplier went out of business tomorrow,", "the factory", "could only keep running", "for about three weeks", "on the materials in stock"],
    meaning: "Giả sử ngày mai nhà cung cấp chính phá sản thì nhà máy chỉ có thể duy trì hoạt động khoảng ba tuần với lượng nguyên liệu còn trong kho.",
    review: NOT_ONLY_IF,
  },
  {
    id: "b2-wish-had-kept",
    level: "B2",
    en: "Many of the residents interviewed for the survey wish the city had kept the old park instead of turning it into a car park.",
    verb: "wish (không phải interviewed)",
    subject: "Many of the residents interviewed for the survey",
    sign: "Interviewed for the survey là cụm rút gọn (who were interviewed) bổ nghĩa cho residents, nên không phải động từ chính. Wish + had + V3 (had kept): tiếc về một việc trong quá khứ. Thực tế: thành phố đã không giữ lại công viên.",
    chunks: ["Many of the residents", "interviewed for the survey", "wish", "the city had kept the old park", "instead of turning it into a car park"],
    meaning: "Nhiều cư dân được phỏng vấn trong cuộc khảo sát ước gì thành phố đã giữ lại công viên cũ thay vì biến nó thành bãi đỗ xe.",
    review: THIRD_MIXED,
  },
  {
    id: "b2-would-rather-postponed",
    level: "B2",
    en: "Most of the staff would rather the management postponed the move to the new office until the renovation work has been fully completed.",
    verb: "would rather (postponed là việc của người khác: the management)",
    subject: "Most of the staff",
    sign: "Would rather + người khác + quá khứ đơn (the management postponed): muốn người khác làm gì. Động từ ở dạng quá khứ nhưng nói về hiện tại và tương lai, không chỉ thời gian quá khứ.",
    chunks: ["Most of the staff", "would rather", "the management postponed", "the move to the new office", "until the renovation work has been fully completed"],
    meaning: "Phần lớn nhân viên muốn ban lãnh đạo hoãn việc chuyển sang văn phòng mới cho đến khi công trình cải tạo hoàn tất hẳn.",
    review: UNREAL_PAST,
  },
  {
    id: "b2-high-time-rules",
    level: "B2",
    en: "It is high time the government introduced clearer rules for delivery companies, whose drivers often work long hours without proper insurance.",
    verb: "is (khung It is high time); introduced là động từ của vế sau",
    subject: "It (khung câu), the government (vế sau)",
    sign: "It is high time + chủ ngữ + quá khứ đơn (introduced): lẽ ra phải làm từ lâu rồi; dạng quá khứ nhưng nói về bây giờ. Sau dấu phẩy, whose drivers… là mệnh đề không xác định, chỉ thêm thông tin về các công ty giao hàng.",
    chunks: ["It is high time", "the government introduced", "clearer rules for delivery companies,", "whose drivers often work long hours", "without proper insurance"],
    meaning: "Đã đến lúc chính phủ phải ban hành quy định rõ ràng hơn cho các công ty giao hàng, vốn có tài xế thường làm việc nhiều giờ mà không có bảo hiểm đầy đủ.",
    review: UNREAL_PAST,
  },
  {
    id: "b2-whereas-generations",
    level: "B2",
    en: "Younger employees tend to prefer flexible working hours, whereas their older colleagues are more likely to value job security and a clear career path.",
    verb: "tend (vế đầu) và are (vế whereas)",
    subject: "Younger employees (vế đầu), their older colleagues (vế whereas)",
    sign: "Whereas là liên từ: nối hai sự thật song song để so sánh trong cùng một câu, nghĩa là trong khi đó. Nó không mang nghĩa trái mong đợi như however.",
    chunks: ["Younger employees", "tend to prefer", "flexible working hours,", "whereas their older colleagues", "are more likely to value", "job security and a clear career path"],
    meaning: "Nhân viên trẻ thường thích giờ làm linh hoạt, trong khi đồng nghiệp lớn tuổi hơn có xu hướng coi trọng sự ổn định công việc và lộ trình thăng tiến rõ ràng.",
    review: LINKERS,
  },
  {
    id: "b2-nevertheless-software",
    level: "B2",
    en: "The new software was expensive and difficult to install; nevertheless, most departments reported that it had saved them several hours of work each week.",
    verb: "was (vế đầu) và reported (vế sau); had saved là động từ trong mệnh đề that",
    subject: "The new software (vế đầu), most departments (vế sau)",
    sign: "Nevertheless là trạng từ liên kết (dù vậy), nên đứng sau dấu chấm phẩy và có dấu phẩy theo sau. Ý sau trái với điều người đọc chờ đợi từ ý trước. Reported that + had saved: tường thuật, lùi thì.",
    chunks: ["The new software", "was", "expensive and difficult to install;", "nevertheless,", "most departments", "reported", "that it had saved them", "several hours of work each week"],
    meaning: "Phần mềm mới vừa đắt vừa khó cài đặt; dù vậy, hầu hết các phòng ban cho biết nó đã giúp họ tiết kiệm được vài giờ làm việc mỗi tuần.",
    review: LINKERS,
  },
  {
    id: "b2-denied-explained",
    level: "B2",
    en: "The supplier denied sending the wrong items and explained that the order had been changed by someone in our own purchasing department.",
    verb: "denied (sending) và explained",
    subject: "The supplier",
    sign: "Deny + V-ing (denied sending) = phủ nhận đã làm việc gì; không dùng deny to V. Explain that + mệnh đề; had been changed là bị động quá khứ hoàn thành, lùi thì vì động từ tường thuật ở quá khứ.",
    chunks: ["The supplier", "denied sending", "the wrong items", "and explained", "that the order had been changed", "by someone in our own purchasing department"],
    meaning: "Nhà cung cấp phủ nhận việc gửi nhầm hàng và giải thích rằng đơn hàng đã bị chính một người trong phòng mua hàng của chúng ta thay đổi.",
    review: REPORTED,
  },
  {
    id: "b2-asked-whether",
    level: "B2",
    en: "The auditor asked the head of the sales team whether the figures in last year's report had been checked by an independent accountant.",
    verb: "asked (had been checked là động từ của câu hỏi được tường thuật)",
    subject: "The auditor",
    sign: "Câu hỏi Yes/No khi tường thuật dùng whether (hoặc if) và trật tự câu kể: the figures… had been checked, không đảo had lên trước chủ ngữ. Câu gốc là Have the figures been checked…?, lùi thì thành had been checked.",
    chunks: ["The auditor", "asked", "the head of the sales team", "whether the figures in last year's report", "had been checked", "by an independent accountant"],
    meaning: "Kiểm toán viên hỏi trưởng nhóm kinh doanh xem các số liệu trong báo cáo năm ngoái đã được một kế toán độc lập kiểm tra chưa.",
    review: REPORTED,
  },
  {
    id: "b2-suggested-warned",
    level: "B2",
    en: "During the meeting, the consultant suggested moving the launch to the autumn and warned us not to promise customers a date we could not guarantee.",
    verb: "suggested (moving) và warned",
    subject: "the consultant",
    sign: "Suggest + V-ing (suggested moving), không nói suggested us to move. Warn + người + not to V (warned us not to promise): cảnh báo ai đừng làm gì. A date we could not guarantee là mệnh đề quan hệ đã lược that.",
    chunks: ["During the meeting,", "the consultant", "suggested moving the launch", "to the autumn", "and warned us", "not to promise customers", "a date we could not guarantee"],
    meaning: "Trong cuộc họp, chuyên gia tư vấn đề xuất dời buổi ra mắt sang mùa thu và cảnh báo chúng tôi đừng hứa với khách hàng một mốc ngày mà mình không bảo đảm được.",
    review: REPORTED,
  },
  {
    id: "b2-non-defining-programme",
    level: "B2",
    en: "The new training programme, which was designed by a team of former teachers, has already been adopted by more than forty schools in the region.",
    verb: "has been adopted (không phải was designed)",
    subject: "The new training programme",
    sign: "Cụm giữa hai dấu phẩy (which was designed…) là mệnh đề quan hệ không xác định: chỉ thêm thông tin, bỏ đi câu vẫn đủ nghĩa. Bỏ ra, câu còn The new training programme has already been adopted… Has been adopted là bị động hiện tại hoàn thành.",
    chunks: ["The new training programme,", "which was designed by a team of former teachers,", "has already been adopted", "by more than forty schools", "in the region"],
    meaning: "Chương trình đào tạo mới, vốn do một nhóm cựu giáo viên thiết kế, đã được hơn bốn mươi trường trong vùng áp dụng.",
    review: RELATIVE,
  },
  {
    id: "b2-whose-applicants",
    level: "B2",
    en: "Applicants whose previous experience is mainly in sales should explain in their cover letter how their skills would transfer to a technical role.",
    verb: "should explain (không phải is)",
    subject: "Applicants whose previous experience is mainly in sales",
    sign: "Whose + danh từ (whose previous experience) chỉ sở hữu: những ứng viên mà kinh nghiệm của họ… Đây là mệnh đề xác định nên không có dấu phẩy, vì nó cho biết nhóm ứng viên nào. Sau explain, how their skills would transfer là câu hỏi gián tiếp nên giữ trật tự câu kể.",
    chunks: ["Applicants", "whose previous experience is mainly in sales", "should explain", "in their cover letter", "how their skills would transfer to a technical role"],
    meaning: "Những ứng viên có kinh nghiệm trước đây chủ yếu trong mảng bán hàng nên giải thích trong thư xin việc rằng kỹ năng của họ sẽ được áp dụng vào một vị trí kỹ thuật như thế nào.",
    review: RELATIVE,
  },
  {
    id: "b2-having-analysed",
    level: "B2",
    en: "Having analysed the results of the customer survey, the marketing team decided to redesign the packaging rather than lower the price.",
    verb: "decided (không phải analysed)",
    subject: "the marketing team",
    sign: "Having + V3 ở đầu câu là mệnh đề phân từ: việc phân tích xong hẳn rồi mới đến việc quyết định. Nó mượn chủ ngữ của mệnh đề chính: chính the marketing team đã phân tích. Rather than + V nguyên mẫu (lower) = thay vì.",
    chunks: ["Having analysed the results of the customer survey,", "the marketing team", "decided to redesign", "the packaging", "rather than lower the price"],
    meaning: "Sau khi phân tích kết quả khảo sát khách hàng, nhóm marketing quyết định thiết kế lại bao bì thay vì giảm giá.",
    review: PARTICIPLE,
  },
  {
    id: "b2-built-station",
    level: "B2",
    en: "Built more than a century ago and rarely repaired since then, the old railway station now needs urgent work to make it safe for passengers.",
    verb: "needs (built và repaired không phải động từ chính)",
    subject: "the old railway station",
    sign: "Cụm mở đầu bằng V3 (Built…, repaired…) là mệnh đề phân từ mang nghĩa bị động: nhà ga được xây, hiếm khi được sửa. Nó mượn chủ ngữ của mệnh đề chính sau dấu phẩy. Needs có -s vì chủ ngữ số ít.",
    chunks: ["Built more than a century ago", "and rarely repaired since then,", "the old railway station", "now needs", "urgent work", "to make it safe for passengers"],
    meaning: "Được xây từ hơn một thế kỷ trước và từ đó đến nay hiếm khi được sửa chữa, nhà ga cũ giờ cần được tu sửa gấp để bảo đảm an toàn cho hành khách.",
    review: PARTICIPLE,
  },
  {
    id: "b2-complaints-received",
    level: "B2",
    en: "Most of the complaints received by the customer service department last month were about late deliveries rather than the quality of the products.",
    verb: "were (không phải received)",
    subject: "Most of the complaints received by the customer service department last month",
    sign: "Received ở đây không phải quá khứ đơn mà là V3 trong mệnh đề quan hệ rút gọn (which were received): những lời phàn nàn mà phòng chăm sóc khách hàng nhận được. Động từ chính là were, hợp với chủ ngữ số nhiều complaints.",
    chunks: ["Most of the complaints", "received by the customer service department", "last month", "were", "about late deliveries", "rather than the quality of the products"],
    meaning: "Phần lớn những lời phàn nàn mà phòng chăm sóc khách hàng nhận được tháng trước là về việc giao hàng chậm chứ không phải về chất lượng sản phẩm.",
    review: PARTICIPLE,
  },
  {
    id: "b2-sharp-rise-followed",
    level: "B2",
    en: "According to the survey, there was a sharp rise in the number of visitors to the museum's website in the first quarter, followed by a gradual fall over the next six months.",
    verb: "was (there was); followed không phải động từ chính",
    subject: "a sharp rise (there was + cụm danh từ)",
    sign: "There was + tính từ + danh từ (a sharp rise, a gradual fall) là cách mô tả số liệu bằng danh từ, cùng nghĩa với rose sharply, fell gradually. In the number of… cho biết cái gì tăng. Followed by… là cụm phân từ: sau đó là một đợt giảm.",
    chunks: ["According to the survey,", "there was", "a sharp rise", "in the number of visitors to the museum's website", "in the first quarter,", "followed by a gradual fall", "over the next six months"],
    meaning: "Theo khảo sát, số lượt truy cập trang web của bảo tàng tăng mạnh trong quý một, sau đó giảm dần trong sáu tháng tiếp theo.",
    review: DATA,
  },
  {
    id: "b2-articles-report",
    level: "B2",
    en: "The report that the committee published in June argues that students who lack access to computers at home are the ones most likely to fall behind.",
    verb: "argues (không phải published hay are)",
    subject: "The report that the committee published in June",
    sign: "The report có the vì cụm that the committee published in June cho biết bản báo cáo cụ thể nào. Students và computers không có mạo từ vì nói chung về cả một nhóm, dù students có mệnh đề who đi kèm. At home là cụm cố định, không có the.",
    chunks: ["The report", "that the committee published in June", "argues", "that students", "who lack access to computers at home", "are the ones most likely to fall behind"],
    meaning: "Bản báo cáo mà ủy ban công bố hồi tháng Sáu cho rằng chính những học sinh không có máy tính ở nhà là nhóm dễ bị tụt lại phía sau nhất.",
    review: ARTICLES,
  },
  {
    id: "b2-long-np-growth",
    level: "B2",
    en: "The rapid growth of online shopping among older customers in small towns has forced many local shops to rethink the way they display their products.",
    verb: "has forced",
    subject: "The rapid growth of online shopping among older customers in small towns",
    sign: "Chủ ngữ là một cụm danh từ dài 12 từ, lõi là growth (sự tăng trưởng); các cụm of…, among…, in… đứng sau bổ nghĩa cho growth. Tìm has forced trước rồi mới quay lại gom chủ ngữ. Force + người + to V = buộc ai phải làm gì.",
    chunks: ["The rapid growth of online shopping", "among older customers", "in small towns", "has forced", "many local shops", "to rethink the way they display their products"],
    meaning: "Việc mua sắm trực tuyến tăng nhanh ở nhóm khách hàng lớn tuổi tại các thị trấn nhỏ đã buộc nhiều cửa hàng địa phương phải nghĩ lại cách trưng bày sản phẩm.",
    review: DATA,
  },
  {
    id: "b2-long-np-plan",
    level: "B2",
    en: "A detailed plan for reducing the amount of plastic waste produced by the canteen will be presented to the board at the next meeting.",
    verb: "will be presented (không phải produced)",
    subject: "A detailed plan for reducing the amount of plastic waste produced by the canteen",
    sign: "Lõi của chủ ngữ là plan. For reducing… cho biết kế hoạch để làm gì (giới từ + V-ing); produced by the canteen là cụm rút gọn (which is produced) bổ nghĩa cho plastic waste. Động từ chính là will be presented, bị động tương lai.",
    chunks: ["A detailed plan", "for reducing the amount of plastic waste", "produced by the canteen", "will be presented", "to the board", "at the next meeting"],
    meaning: "Một kế hoạch chi tiết nhằm giảm lượng rác thải nhựa do căng-tin thải ra sẽ được trình lên ban giám đốc trong cuộc họp tới.",
    review: PARTICIPLE,
  },

  // C1
  {
    id: "c1-undoubtedly-timetable",
    level: "C1",
    en: "The new timetable has undoubtedly reduced waiting times at the busiest stations, although it caused some confusion among passengers during the first few weeks.",
    verb: "has reduced (vế chính) và caused (vế although)",
    subject: "The new timetable (vế chính), it (vế although)",
    sign: "Undoubtedly là trạng từ bình luận, nói thái độ người viết (chắc chắn là); nó đứng giữa câu, sau trợ động từ has. Bỏ nó ra, câu vẫn đủ: The new timetable has reduced waiting times.",
    chunks: ["The new timetable", "has undoubtedly reduced", "waiting times", "at the busiest stations,", "although it caused some confusion among passengers", "during the first few weeks"],
    meaning: "Lịch chạy tàu mới chắc chắn đã giảm thời gian chờ ở những ga đông nhất, dù nó gây ra ít nhiều bối rối cho hành khách trong vài tuần đầu.",
    review: COMMENT,
  },
  {
    id: "c1-arguably-weakness",
    level: "C1",
    en: "Arguably, the most significant weakness of the proposal is its assumption that customers will accept higher prices without switching to cheaper alternatives.",
    verb: "is (will accept nằm trong mệnh đề that)",
    subject: "the most significant weakness of the proposal",
    sign: "Arguably = có thể nói là: trạng từ rào đón, người viết đưa ra nhận định nhưng thừa nhận người khác có thể không đồng ý; nó không có nghĩa gây tranh cãi. Its assumption that… là danh từ + mệnh đề that nói rõ giả định đó là gì.",
    chunks: ["Arguably,", "the most significant weakness of the proposal", "is", "its assumption", "that customers will accept higher prices", "without switching to cheaper alternatives"],
    meaning: "Có thể nói điểm yếu lớn nhất của bản đề xuất là nó mặc định rằng khách hàng sẽ chấp nhận giá cao hơn mà không chuyển sang những lựa chọn rẻ hơn.",
    review: COMMENT,
  },
  {
    id: "c1-neither-did-analysts",
    level: "C1",
    en: "Most of the senior managers did not believe the merger would succeed, and neither did the analysts who had studied the two companies' accounts.",
    verb: "did not believe (vế đầu) và did (vế neither, thay cho did not believe)",
    subject: "Most of the senior managers (vế đầu), the analysts who had studied the two companies' accounts (vế sau)",
    sign: "Neither + trợ động từ + chủ ngữ (neither did the analysts) = các nhà phân tích cũng không. Did thay cho cả cụm believe the merger would succeed để khỏi lặp lại; trợ động từ khớp với thì quá khứ của vế trước, và chủ ngữ đứng sau did.",
    chunks: ["Most of the senior managers", "did not believe", "the merger would succeed,", "and neither did", "the analysts", "who had studied the two companies' accounts"],
    meaning: "Phần lớn các quản lý cấp cao không tin vụ sáp nhập sẽ thành công, và những nhà phân tích từng nghiên cứu sổ sách của hai công ty cũng vậy.",
    review: ELLIPSIS,
  },
  {
    id: "c1-done-so-report",
    level: "C1",
    en: "The committee had promised to publish a full report on the incident, but it has not yet done so, and few observers now expect it to.",
    verb: "had promised, has not done (so) và expect",
    subject: "The committee, it (= the committee), few observers",
    sign: "Done so thay cho cả cụm published a full report on the incident, cách nói của văn trang trọng. Ở cuối câu, expect it to dừng ở to: phần publish a full report bị lược vì người đọc đã biết. Muốn hiểu, hãy chép cụm động từ ở vế đầu vào hai chỗ này.",
    chunks: ["The committee", "had promised", "to publish a full report on the incident,", "but it has not yet done so,", "and few observers", "now expect it to"],
    meaning: "Ủy ban đã hứa công bố một báo cáo đầy đủ về sự cố, nhưng đến giờ vẫn chưa làm, và giờ đây ít người theo dõi còn mong họ sẽ làm.",
    review: ELLIPSIS,
  },
  {
    id: "c1-under-no-circumstances",
    level: "C1",
    en: "Under no circumstances should confidential client data be stored on personal devices or sent to private email addresses.",
    verb: "should be stored (và should be sent)",
    subject: "confidential client data",
    sign: "Under no circumstances (trong bất kỳ trường hợp nào cũng không) đứng đầu câu nên đảo ngữ: động từ khuyết thiếu should lên trước chủ ngữ. Câu thường: Confidential client data should under no circumstances be stored… Be stored và (be) sent là bị động.",
    chunks: ["Under no circumstances", "should", "confidential client data", "be stored on personal devices", "or sent to private email addresses"],
    meaning: "Trong bất kỳ trường hợp nào, dữ liệu mật của khách hàng cũng không được lưu trên thiết bị cá nhân hoặc gửi đến địa chỉ email riêng.",
    review: INVERSION,
  },
  {
    id: "c1-not-only-policy",
    level: "C1",
    en: "Not only did the new policy fail to reduce costs, but it also damaged the morale of staff who had supported it from the start.",
    verb: "did… fail (vế đầu) và damaged (vế but)",
    subject: "the new policy (vế đầu), it (vế sau)",
    sign: "Not only đứng đầu câu nên đảo ngữ: mượn did đặt trước chủ ngữ, động từ chính về nguyên mẫu (fail, không phải failed). Vế sau but it also… giữ trật tự bình thường.",
    chunks: ["Not only did", "the new policy", "fail to reduce costs,", "but it also damaged", "the morale of staff", "who had supported it from the start"],
    meaning: "Chính sách mới không những không giảm được chi phí mà còn làm suy giảm tinh thần của những nhân viên đã ủng hộ nó ngay từ đầu.",
    review: INVERSION,
  },
  {
    id: "c1-no-sooner-relocate",
    level: "C1",
    en: "No sooner had the company announced its plans to relocate than local residents began organising protests outside its headquarters.",
    verb: "had announced (vế No sooner) và began (vế than)",
    subject: "the company (vế đầu), local residents (vế than)",
    sign: "No sooner + had + chủ ngữ + V3 … than …: vừa mới… thì đã… Had được đảo lên trước chủ ngữ. No sooner luôn đi với than, không đi với when.",
    chunks: ["No sooner had", "the company", "announced its plans to relocate", "than local residents", "began organising protests", "outside its headquarters"],
    meaning: "Công ty vừa công bố kế hoạch chuyển trụ sở thì người dân địa phương đã bắt đầu tổ chức biểu tình bên ngoài trụ sở chính.",
    review: INVERSION,
  },
  {
    id: "c1-only-after-inspection",
    level: "C1",
    en: "Only after the second inspection had been completed did the authorities admit that the building was unsafe for public use.",
    verb: "did… admit (không phải had been completed)",
    subject: "the authorities",
    sign: "Với Only after, đảo ngữ nằm ở mệnh đề chính: did the authorities admit. Cụm ngay sau only (the second inspection had been completed) giữ trật tự bình thường. Câu thường: The authorities admitted… only after the second inspection had been completed.",
    chunks: ["Only after the second inspection had been completed", "did", "the authorities", "admit", "that the building was unsafe for public use"],
    meaning: "Chỉ sau khi đợt kiểm tra thứ hai kết thúc, nhà chức trách mới thừa nhận tòa nhà không an toàn để công chúng sử dụng.",
    review: INVERSION,
  },
  {
    id: "c1-it-cleft-service",
    level: "C1",
    en: "It was not the price but the poor after-sales service that persuaded many customers to switch to a competitor last year.",
    verb: "was (khung câu chẻ It was… that); persuaded là động từ của phần còn lại",
    subject: "It (khung câu); phần được nhấn mạnh: not the price but the poor after-sales service",
    sign: "Câu chẻ It + be + phần nhấn mạnh + that + phần còn lại. Bỏ khung It was… that, câu thường là: The poor after-sales service, not the price, persuaded many customers… Câu nhấn mạnh rằng lý do là dịch vụ hậu mãi, không phải giá.",
    chunks: ["It was", "not the price but the poor after-sales service", "that persuaded many customers", "to switch to a competitor", "last year"],
    meaning: "Chính dịch vụ hậu mãi kém, chứ không phải giá cả, đã khiến nhiều khách hàng chuyển sang đối thủ cạnh tranh vào năm ngoái.",
    review: CLEFT,
  },
  {
    id: "c1-wh-cleft-manager",
    level: "C1",
    en: "What the new manager failed to understand was that the team needed clear priorities rather than more meetings and longer reports.",
    verb: "was (failed và needed nằm trong các mệnh đề con)",
    subject: "What the new manager failed to understand",
    sign: "Câu chẻ với What: cả mệnh đề What… understand làm chủ ngữ, rồi đến was, rồi phần được nhấn mạnh (that the team needed…). Câu thường: The new manager failed to understand that the team needed…",
    chunks: ["What the new manager failed to understand", "was", "that the team needed clear priorities", "rather than more meetings and longer reports"],
    meaning: "Điều người quản lý mới không hiểu được là cả nhóm cần những ưu tiên rõ ràng chứ không cần thêm cuộc họp hay những bản báo cáo dài hơn.",
    review: CLEFT,
  },
  {
    id: "c1-should-you-require",
    level: "C1",
    en: "Should you require any further information about the application process, please do not hesitate to contact our admissions office.",
    verb: "do not hesitate (câu mệnh lệnh); require thuộc vế Should",
    subject: "you (ẩn trong câu mệnh lệnh; vế Should cũng là you)",
    sign: "Should + chủ ngữ + V nguyên mẫu ở đầu câu = If you require: câu điều kiện đảo ngữ, rất trang trọng, hay gặp ở cuối thư. Sau Should là require, không thêm -s hay -d.",
    chunks: ["Should you require any further information", "about the application process,", "please do not hesitate", "to contact our admissions office"],
    meaning: "Nếu anh/chị cần thêm thông tin về quy trình nộp hồ sơ, xin đừng ngần ngại liên hệ với phòng tuyển sinh của chúng tôi.",
    review: COND_ADV,
  },
  {
    id: "c1-had-been-taken-seriously",
    level: "C1",
    en: "Had the warning signs been taken seriously, the authorities could have evacuated the area long before the river burst its banks.",
    verb: "could have evacuated (vế chính); had been taken thuộc vế đảo ngữ",
    subject: "the authorities (vế chính), the warning signs (vế Had)",
    sign: "Had + chủ ngữ + V3 ở đầu câu = If the warning signs had been taken seriously: câu điều kiện loại 3 đảo ngữ, bỏ if. Been taken là bị động. Thực tế: các dấu hiệu cảnh báo đã bị xem nhẹ.",
    chunks: ["Had the warning signs been taken seriously,", "the authorities", "could have evacuated", "the area", "long before the river burst its banks"],
    meaning: "Nếu các dấu hiệu cảnh báo được coi trọng thì nhà chức trách đã có thể sơ tán khu vực từ lâu trước khi sông tràn bờ.",
    review: COND_ADV,
  },
  {
    id: "c1-were-to-tax",
    level: "C1",
    en: "Were the government to raise the tax on sugary drinks, manufacturers would probably respond by reducing the sugar content of their products.",
    verb: "would respond (vế chính); to raise thuộc vế Were",
    subject: "manufacturers (vế chính), the government (vế Were)",
    sign: "Were + chủ ngữ + to V ở đầu câu = If the government were to raise: giả định khá xa, trang trọng. Vế chính dùng would + V như câu điều kiện loại 2. By + V-ing (by reducing) cho biết họ phản ứng bằng cách nào.",
    chunks: ["Were the government to raise", "the tax on sugary drinks,", "manufacturers", "would probably respond", "by reducing the sugar content of their products"],
    meaning: "Nếu chính phủ tăng thuế đối với đồ uống có đường, các nhà sản xuất có lẽ sẽ phản ứng bằng cách giảm hàm lượng đường trong sản phẩm.",
    review: COND_ADV,
  },
  {
    id: "c1-but-for-volunteers",
    level: "C1",
    en: "But for the generous support of local volunteers, the festival would never have survived the financial difficulties of its first few years.",
    verb: "would never have survived",
    subject: "the festival",
    sign: "But for + danh từ = nếu không có (= If it hadn't been for). Vế chính would have + V3 cho thấy đây là giả định về quá khứ. Thực tế: nhờ có tình nguyện viên nên lễ hội đã trụ được.",
    chunks: ["But for the generous support of local volunteers,", "the festival", "would never have survived", "the financial difficulties", "of its first few years"],
    meaning: "Nếu không có sự hỗ trợ hào phóng của các tình nguyện viên địa phương, lễ hội đã không bao giờ vượt qua được những khó khăn tài chính trong vài năm đầu.",
    review: COND_ADV,
  },
  {
    id: "c1-recommended-replace",
    level: "C1",
    en: "The inspectors recommended that the school replace its outdated heating system and that every classroom be checked for damp before the winter.",
    verb: "recommended (replace và be checked thuộc các mệnh đề that)",
    subject: "The inspectors",
    sign: "Recommend that + chủ ngữ + V nguyên mẫu là thể giả định: the school replace (không thêm -s), every classroom be checked (be giữ nguyên, không đổi thành is hay was). Câu chính ở quá khứ nhưng mệnh đề that không lùi thì.",
    chunks: ["The inspectors", "recommended", "that the school replace its outdated heating system", "and that every classroom be checked for damp", "before the winter"],
    meaning: "Đoàn thanh tra khuyến nghị nhà trường thay hệ thống sưởi đã lỗi thời và kiểm tra ẩm mốc ở mọi lớp học trước mùa đông.",
    review: SUBJUNCTIVE,
  },
  {
    id: "c1-essential-submit",
    level: "C1",
    en: "It is essential that every applicant submit the signed form by Friday, as late applications cannot be considered under the new regulations.",
    verb: "is (khung It is essential); submit thuộc mệnh đề that",
    subject: "It (khung câu), every applicant (mệnh đề that)",
    sign: "It is essential that + chủ ngữ + V nguyên mẫu: thể giả định. Every applicant là số ít nhưng động từ vẫn là submit, không thêm -s. As ở đây nghĩa là vì.",
    chunks: ["It is essential", "that every applicant submit the signed form", "by Friday,", "as late applications cannot be considered", "under the new regulations"],
    meaning: "Mỗi ứng viên bắt buộc phải nộp mẫu đơn đã ký trước thứ Sáu, vì theo quy định mới, hồ sơ nộp muộn sẽ không được xem xét.",
    review: SUBJUNCTIVE,
  },
  {
    id: "c1-accused-urged",
    level: "C1",
    en: "The union accused the management of ignoring safety concerns and urged its members not to return to work until the faulty equipment had been replaced.",
    verb: "accused và urged",
    subject: "The union",
    sign: "Accuse + người + of + V-ing (accused the management of ignoring): buộc tội ai làm gì. Urge + người + not to V (urged its members not to return): kêu gọi ai đừng làm gì. Hai động từ tường thuật này kể lại cả thái độ của công đoàn, không chỉ là said.",
    chunks: ["The union", "accused the management", "of ignoring safety concerns", "and urged its members", "not to return to work", "until the faulty equipment had been replaced"],
    meaning: "Công đoàn cáo buộc ban quản lý phớt lờ những lo ngại về an toàn và kêu gọi đoàn viên không quay lại làm việc cho đến khi thiết bị hỏng được thay thế.",
    review: REPORTING,
  },
  {
    id: "c1-believed-to-have-been-sold",
    level: "C1",
    en: "The missing painting is believed to have been sold to a private collector shortly after it disappeared from the gallery more than thirty years ago.",
    verb: "is believed (to have been sold)",
    subject: "The missing painting",
    sign: "Chủ ngữ + is believed + to have been V3: bây giờ người ta tin rằng bức tranh đã bị bán từ trước. To have + V3 chỉ việc xảy ra trước lúc tin; been sold là bị động. Câu tương đương: It is believed that the missing painting was sold…",
    chunks: ["The missing painting", "is believed", "to have been sold to a private collector", "shortly after it disappeared from the gallery", "more than thirty years ago"],
    meaning: "Người ta tin rằng bức tranh bị mất đã được bán cho một nhà sưu tầm tư nhân ngay sau khi nó biến mất khỏi phòng tranh hơn ba mươi năm trước.",
    review: PASSIVE_REPORT,
  },
  {
    id: "c1-said-to-have-been-negotiating",
    level: "C1",
    en: "The former director is said to have been negotiating with several investors for months before the board finally agreed to sell the company.",
    verb: "is said (to have been negotiating)",
    subject: "The former director",
    sign: "Is said + to have been V-ing: người ta nói rằng ông ấy đã đàm phán liên tục suốt nhiều tháng trước đó. To have been + V-ing nhấn mạnh một quá trình kéo dài trong quá khứ; before the board finally agreed… là mốc kết thúc.",
    chunks: ["The former director", "is said", "to have been negotiating with several investors", "for months", "before the board finally agreed", "to sell the company"],
    meaning: "Người ta nói rằng cựu giám đốc đã đàm phán với nhiều nhà đầu tư suốt mấy tháng trước khi hội đồng quản trị cuối cùng đồng ý bán công ty.",
    review: PASSIVE_REPORT,
  },
  {
    id: "c1-long-been-assumed",
    level: "C1",
    en: "It has long been assumed that older workers are reluctant to learn new technologies, but the survey described in this article suggests otherwise.",
    verb: "has been assumed (vế đầu) và suggests (vế but)",
    subject: "It (vế đầu), the survey described in this article (vế sau)",
    sign: "It has long been assumed that… = từ lâu người ta vẫn mặc định rằng: bị động khách quan, không nói ai giả định. Described in this article là cụm rút gọn bổ nghĩa cho survey. Otherwise thay cho cả ý ngược lại: người lao động lớn tuổi không ngại học công nghệ mới.",
    chunks: ["It has long been assumed", "that older workers are reluctant to learn new technologies,", "but the survey", "described in this article", "suggests otherwise"],
    meaning: "Từ lâu người ta vẫn mặc định rằng người lao động lớn tuổi ngại học công nghệ mới, nhưng cuộc khảo sát được nêu trong bài viết này lại cho thấy điều ngược lại.",
    review: PASSIVE_REPORT,
  },
  {
    id: "c1-extent-to-which",
    level: "C1",
    en: "The extent to which young people trust online news depends largely on the habits they developed at home and at school.",
    verb: "depends (không phải trust hay developed)",
    subject: "The extent to which young people trust online news",
    sign: "The extent to which + mệnh đề = mức độ mà: giới từ to được đưa lên trước which (gốc là young people trust online news to an extent). Cả cụm 8 từ là chủ ngữ, nên động từ chính depends có -s. The habits they developed là mệnh đề quan hệ đã lược which/that.",
    chunks: ["The extent", "to which young people trust online news", "depends largely", "on the habits", "they developed at home and at school"],
    meaning: "Mức độ giới trẻ tin vào tin tức trên mạng phụ thuộc phần lớn vào những thói quen họ hình thành ở nhà và ở trường.",
    review: RELATIVE_ADV,
  },
  {
    id: "c1-whereby-scheme",
    level: "C1",
    en: "The council has introduced a scheme whereby residents who recycle their household waste correctly receive a small discount on their annual tax bill.",
    verb: "has introduced (receive là động từ trong mệnh đề whereby)",
    subject: "The council",
    sign: "Whereby = mà theo đó, hay đi sau scheme, system, agreement. Trong mệnh đề whereby, chủ ngữ là residents who recycle… correctly (có thêm mệnh đề who lồng bên trong) và động từ là receive.",
    chunks: ["The council", "has introduced", "a scheme", "whereby residents", "who recycle their household waste correctly", "receive a small discount", "on their annual tax bill"],
    meaning: "Hội đồng thành phố đã đưa ra một chương trình mà theo đó cư dân nào phân loại rác sinh hoạt để tái chế đúng cách sẽ được giảm một khoản nhỏ trong hóa đơn thuế hằng năm.",
    review: RELATIVE_ADV,
  },
  {
    id: "c1-most-of-whom",
    level: "C1",
    en: "The survey was sent to over three thousand graduates, most of whom said that they would have chosen a different course if they had known more about the job market.",
    verb: "was sent (said là động từ trong mệnh đề most of whom)",
    subject: "The survey",
    sign: "Most of whom (lượng từ + of whom) đứng sau dấu phẩy, thay cho most of the graduates; không nối bằng dấu phẩy + most of them. Trong mệnh đề này, would have chosen… if they had known… là câu điều kiện loại 3.",
    chunks: ["The survey", "was sent", "to over three thousand graduates,", "most of whom said", "that they would have chosen a different course", "if they had known more about the job market"],
    meaning: "Bản khảo sát được gửi tới hơn ba nghìn người đã tốt nghiệp, phần lớn trong số họ nói rằng họ đã chọn ngành khác nếu biết rõ hơn về thị trường việc làm.",
    review: RELATIVE_ADV,
  },
  {
    id: "c1-much-as-admire",
    level: "C1",
    en: "Much as I admire the author's ambition, I find it difficult to accept her claim that technology alone can solve the problem of inequality.",
    verb: "find (vế chính); admire thuộc vế Much as",
    subject: "I",
    sign: "Much as + S + V = dù rất… (nhượng bộ, trang trọng); vế sau không thêm but. Find it difficult to accept: it là tân ngữ giả, thay cho to accept her claim… Her claim that… là danh từ + mệnh đề that nói rõ nội dung khẳng định.",
    chunks: ["Much as I admire the author's ambition,", "I", "find it difficult", "to accept her claim", "that technology alone can solve the problem of inequality"],
    meaning: "Dù tôi rất ngưỡng mộ tham vọng của tác giả, tôi khó lòng chấp nhận khẳng định của bà rằng chỉ riêng công nghệ có thể giải quyết vấn đề bất bình đẳng.",
    review: CONCESSION,
  },
  {
    id: "c1-albeit-recover",
    level: "C1",
    en: "The local economy has finally begun to recover, albeit more slowly than most forecasters had predicted at the start of the year.",
    verb: "has begun (to recover)",
    subject: "The local economy",
    sign: "Albeit = mặc dù, đi với một cụm ngắn chứ không đi với mệnh đề đầy đủ: ở đây là cụm trạng từ more slowly than… Câu tương đương: although it has recovered more slowly than…",
    chunks: ["The local economy", "has finally begun", "to recover,", "albeit more slowly", "than most forecasters had predicted", "at the start of the year"],
    meaning: "Kinh tế địa phương cuối cùng đã bắt đầu phục hồi, dù chậm hơn so với dự báo của hầu hết các chuyên gia hồi đầu năm.",
    review: CONCESSION,
  },
  {
    id: "c1-impressive-as",
    level: "C1",
    en: "Impressive as the new building may look, many of the people who work there complain that it is too hot in summer and too noisy all year.",
    verb: "complain (look thuộc vế nhượng bộ)",
    subject: "many of the people who work there",
    sign: "Tính từ + as + chủ ngữ + động từ (Impressive as the new building may look) = dù tòa nhà trông ấn tượng đến đâu: mệnh đề nhượng bộ, as ở đây nghĩa là although, không phải because. Vế sau không có but.",
    chunks: ["Impressive as the new building may look,", "many of the people", "who work there", "complain", "that it is too hot in summer", "and too noisy all year"],
    meaning: "Tòa nhà mới trông ấn tượng đến đâu thì nhiều người làm việc ở đó vẫn phàn nàn rằng mùa hè thì quá nóng, còn quanh năm thì quá ồn.",
    review: CONCESSION,
  },
  {
    id: "c1-failure-of-scheme",
    level: "C1",
    en: "The failure of the scheme to attract young families can be partly explained by the absence of affordable housing and the closure of the local school.",
    verb: "can be explained",
    subject: "The failure of the scheme to attract young families",
    sign: "Danh từ hóa: thay vì viết The scheme failed to attract young families because there was no affordable housing and the local school closed, câu gói các ý vào cụm danh từ the failure of…, the absence of…, the closure of… Câu gọn và khách quan, hợp văn học thuật.",
    chunks: ["The failure of the scheme", "to attract young families", "can be partly explained", "by the absence of affordable housing", "and the closure of the local school"],
    meaning: "Việc chương trình không thu hút được các gia đình trẻ có thể được lý giải một phần bởi tình trạng thiếu nhà ở vừa túi tiền và việc trường học địa phương đóng cửa.",
    review: ACADEMIC,
  },
  {
    id: "c1-remains-unclear",
    level: "C1",
    en: "It remains unclear whether the introduction of tuition fees has had any significant effect on the number of students from low-income families applying to university.",
    verb: "remains (has had nằm trong mệnh đề whether)",
    subject: "It (chủ ngữ giả, thay cho cả mệnh đề whether)",
    sign: "It remains unclear whether… = vẫn chưa rõ liệu…: cấu trúc khách quan để nêu một câu hỏi bỏ ngỏ. Trong mệnh đề whether, chủ ngữ là cụm danh từ hóa the introduction of tuition fees, động từ là has had. Applying to university là cụm rút gọn bổ nghĩa cho students.",
    chunks: ["It remains unclear", "whether the introduction of tuition fees", "has had any significant effect", "on the number of students from low-income families", "applying to university"],
    meaning: "Vẫn chưa rõ liệu việc áp dụng học phí có ảnh hưởng đáng kể nào đến số học sinh từ các gia đình thu nhập thấp nộp đơn vào đại học hay không.",
    review: ACADEMIC,
  },
  {
    id: "c1-decision-by-authorities",
    level: "C1",
    en: "The decision by the regional authorities to close three of the five hospitals in the area without consulting local doctors has provoked widespread anger.",
    verb: "has provoked (không phải close hay consulting)",
    subject: "The decision by the regional authorities to close three of the five hospitals in the area without consulting local doctors",
    sign: "Chủ ngữ dài 20 từ, lõi là decision. Sau lõi là ba lớp bổ nghĩa: by… (ai quyết định), to close… (quyết định làm gì), without consulting… (làm như thế nào). Gom hết lại mới gặp động từ chính has provoked.",
    chunks: ["The decision", "by the regional authorities", "to close three of the five hospitals in the area", "without consulting local doctors", "has provoked", "widespread anger"],
    meaning: "Quyết định của chính quyền khu vực đóng cửa ba trong số năm bệnh viện trong vùng mà không hỏi ý kiến các bác sĩ địa phương đã gây ra làn sóng phẫn nộ rộng khắp.",
    review: ACADEMIC,
  },
  {
    id: "c1-only-when-cleft",
    level: "C1",
    en: "It is only when the full costs of the project are taken into account that its benefits begin to look rather less impressive.",
    verb: "is (khung câu chẻ It is… that); begin là động từ của phần còn lại",
    subject: "It (khung câu); phần được nhấn mạnh: only when the full costs of the project are taken into account",
    sign: "Câu chẻ nhấn mạnh thời điểm: It is + only when… + that… Bỏ khung It is… that, câu thường là: Its benefits begin to look rather less impressive only when the full costs of the project are taken into account. Are taken into account là bị động.",
    chunks: ["It is", "only when the full costs of the project are taken into account", "that its benefits", "begin to look", "rather less impressive"],
    meaning: "Chỉ khi tính đến toàn bộ chi phí của dự án thì lợi ích của nó mới bắt đầu trông kém ấn tượng hơn hẳn.",
    review: CLEFT,
  },
];
